### ISSUE TITLE
Independent package names

### ISSUE THREAD

**Issue by pedrouid** [WalletConnect/walletconnect-monorepo#1]
It would be awesome to manage all packages from this monorepo and keeping them as independent package names (eg `walletconnect` instead of `@walletconnect/walletconnect`). I know that Facebook is able to do this with Lerna.js for their React libraries.

Not sure if this is the right place to look but I think this is where they do it:
https://github.com/facebook/create-react-app/blob/next/tasks/publish.sh#L39

Regardless just a nitpick to get the packages name to be easy to find.

**Comment by pedrouid** [comment]
cc @jdkanani

**Comment by jdkanani** [comment]
Yeah, that would work. Will make changes.

**Comment by jdkanani** [comment]
Pushed in new commits. Both packages, `walletconnect-core` & `walletconnect` prod build is broken right now. Calling @shahbhavir (Jedi) for the help :)

**Comment by pedrouid** [comment]
Hey @jdkanani @shahbhavir, have you guys looked into what's wrong with the prod builds? I wanted to test out publishing from the mono-repo

**Comment by jdkanani** [comment]
@shahbhavir is working on it. We upgraded Babel and that changed some behavior. By end of this week we can start publishing it.

**Comment by pedrouid** [comment]
Awesome!

**Comment by jdkanani** [comment]
@pedrouid also I wanted to discuss on QR code thing. I would say we shouldn't add QR canvas element dependency in the library itself.

Let's say 
 - if we want to connect the mobile browser to walletconnect through deep links
 - if we want to do some cool stuff like use Audio QR code 😉 (@ricburton would love your thought on this one)

In such cases, using `walletconnect/walletconnect` lib with QR dependency would be the problem.
