### ISSUE TITLE
ChainId is typed as "number", but is returned as "string"

### ISSUE THREAD

**Issue by TheDutchCoder** [WalletConnect/walletconnect-monorepo#1003]
**Describe the bug**
The type for `chainId` is number, but it's actually returned as a string.

**SDK Version (if relevant)**
 - Client: JS
 - Version 1.7.1

**To Reproduce**
1. Switch networks and log the `typeof` on chainId
2. Comes back as a string, not a number

**Expected behavior**
Type to be string (or return value to be a number)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 101.0.4951.41

**Comment by mubarakone** [comment]
Try using the latest v1.7.8, and let me know what happens

**Comment by TheDutchCoder** [comment]
Still the same type: `chainId: number;` in `index.d.ts`

Package version: `"version": "1.7.8",`

**Comment by finessevanes** [comment]
@TheDutchCoder is this still an issue?

**Comment by TheDutchCoder** [comment]
I no longer work with WalletConnect so I can't verify this issue anymore, sorry.

**Comment by finessevanes** [comment]
@TheDutchCoder no problem, thanks for the reply.
