### ISSUE TITLE
WalletConnect modal doesn't open fine for Electron apps

### ISSUE THREAD

**Issue by marco-souza** [WalletConnect/walletconnect-monorepo#1007]
**Is your feature request related to a problem? Please describe.**

At the moment, the WalletConnect modal is checking first if we're running a NodeJS app. The problem is electron apps have both (Node & Browser), but it's showing the QR code as text.

**Describe the solution you'd like**
Change this [code](https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/legacy/modal/src/index.ts#L6-L9) to check first if we have a browser available.

**Aditional Context**
I'm working in a fix for this

**Comment by cbonaco1** [comment]
hey @marco-souza do you happen to have an update on this fix? I'm currently running into the same issue trying to use WalletConnect in an electron app. when I try to connect, the text of the QR code prints out to the console as you mentioned.

**Comment by marco-souza** [comment]
hello @cbonaco1, I have this [proposal](https://github.com/WalletConnect/walletconnect-monorepo/pull/1017/files) open. We're already using it internally at my company.

**Comment by cbonaco1** [comment]
oh great! and with this change, the modal opens inside the Electron app as expected?

**Comment by marco-souza** [comment]
We didn't have any more bug reports about this, so I think it fixes it.
