### ISSUE TITLE
Error in pong messages

### ISSUE THREAD

**Issue by ptsayli** [WalletConnect/walletconnect-monorepo#101]
I am getting repeated errors due to "pong"

![Screen Shot 2019-04-15 at 8 51 05 PM](https://user-images.githubusercontent.com/16133838/56144760-96362080-5fc0-11e9-8bb8-7a76a61dde9e.png)

**Comment by pedrouid** [comment]
Great catch again 🙏 I was seeing all these errors on the console but ignored it for now. Thanks for debugging it!
