### ISSUE TITLE
undefined is not an object (evaluating 'subtle.digest') on iOS/Safari

### ISSUE THREAD

**Issue by matthewcarlreetz** [WalletConnect/walletconnect-monorepo#1018]
**Describe the bug**
On iOS Safari throws an error when initializing the WalletConnectClient.  

**SDK Version (if relevant)**
 - Client: `React 18.0.0 - web`
 - Version `"@walletconnect/client": "2.0.0-beta.26"`

**To Reproduce**
1. Initialize the client `WalletConnectClient.init({})`
2. Error is thrown
> Unhandled Runtime Error
TypeError: undefined is not an object (evaluating 'subtle.digest')

**Expected behavior**
No error to be thrown

**Screenshots**
![IMG_0D95955C9FCA-1](https://user-images.githubusercontent.com/1760821/166700686-ce6143ee-d143-4e15-b033-d123c0a088fe.jpg)

**Smartphone (please complete the following information):**
- Device: iPhone 11
 - OS: iOS 15.4.1
 - Browser Safari

**Additional context**
Chrome works well without error.

**Comment by matthewcarlreetz** [comment]
This appears only when debugging, seems to work fine in a deployed environment.

**Comment by finessevanes** [comment]
@matthewcarlreetz is this still an issue?
