### ISSUE TITLE
(web3-provider) listing desktop wallets breaks the Desktop tab on modal

### ISSUE THREAD

**Issue by vphilot** [WalletConnect/walletconnect-monorepo#1029]
**Describe the bug**
Using the `qrcodeModalOptions: { desktopLinks: string[] }` option breaks the Desktop tab on the WalletConnect modal, and nothing shows up

**SDK Version (if relevant)**
 - Client: JS
 - Version 1.7.8

**To Reproduce**
1. Create a new `WalletConnectProvider` instance and pass the following `qrcodeModalOptions` object:
```js
const provider = new WalletConnectProvider({
    infuraId: "27e484dcd9e3efcfd25a83a78777cdf1",
    qrcodeModalOptions: {
      desktopLinks: ["metamask"]
    }
  })
```
repro here: https://codesandbox.io/s/little-dream-pulm0s (notice the Desktop tab disappears)

**Expected behavior**
`desktopLinks` should enable displaying a filtered list based on string array that was passed

**Screenshots**
![image](https://user-images.githubusercontent.com/30128268/167464211-c322f3b7-f76a-4432-a2ed-a48fccefc874.jpeg)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version 101.0.4951.54

**Comment by bkrem** [comment]
Hi @vphilot,

Thank you for providing the sandbox example.

The issue here seems to be that "metamask" isn't a valid filtering option for the desktop wallets, since it's not part of the set of all known desktop wallets, but rather part of the mobile wallets set.

The filtering works as expected when passing values of known desktop wallets, e.g.:

 ```
desktopLinks: ["ledger", "tokenary", "infinity"]
```

Here's a fork of your sandbox showing the filtering with the values above:

https://codesandbox.io/s/adoring-austin-f7w2xr?file=/src/index.js

**Comment by vphilot** [comment]
@bkrem thank you for your response! [The official registry ](https://walletconnect.com/registry?)doesn't seem to differentiate between mobile and desktop supported wallets, is there any other resource where I could find it? I tried finding clues in the type definitions but it's just a string array.

**Comment by bkrem** [comment]
You're right, this isn't easily visible at the moment and something we can definitely improve in terms of the filtering options on the website's registry. 
I'm adding an issue for us to add a "Desktop/Mobile" filtering option 👍 

The way the modal filters this is based on whether a wallet entry has a `native` or a `universal` link (or both) defined for a given platform. 
E.g. for Infinity Wallet (from https://registry.walletconnect.com/api/v1/wallets):

```json
			"mobile": {
				"native": null,
				"universal": null
			},
			"desktop": {
				"native": "infinity:",
				"universal": "https://infinitywallet.io/"
			},
```

thus making it a desktop-only option in the modal.

**Comment by vphilot** [comment]
@bkrem tha already helps a lot, and thank you for the clarification

**Comment by vicpon** [comment]
metamask can be used as a chrome extension. Are chrome extensions not considered desktop wallets?
