### ISSUE TITLE
not able to importKey in testnet/production server

### ISSUE THREAD

**Issue by deepak-interakt** [WalletConnect/walletconnect-monorepo#1040]
### Discussed in https://github.com/WalletConnect/walletconnect-monorepo/discussions/1039

<div type='discussions-op-text'>

<sup>Originally posted by **deepak-interakt** May 13, 2022</sup>
hi there , i am new to wallet-connect and i made connections like this . in my local machiene metamask and wallet-connect both are working fine where as when i push them to test server / production server just wallet-connect fails to connect and i get this issue : 

browser.ts:44 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'importKey')
    at browser.ts:44:11
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at c (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21:12
    at d (2.0ed14a77.chunk.js:2:694132)
    
`  
  my connection code : 
  
const web3Modal = 
        new Web3Modal({
            cacheProvider: true,
            bridge: "https://bridge.walletconnect.org",
            providerOptions: {
                injected : {
                },
                walletconnect: {
                    package: WalletConnectProvider,
                    options: {
                        infuraId: process.env.REACT_APP_INFURA_ID, 
                        rpc:{
                            1:"https://mainnet.infura.io/v3/" + process.env.REACT_APP_INFURA_ID,
                            4: "https://rinkeby.infura.io/v3/" + process.env.REACT_APP_INFURA_ID,
                            137: "https://polygon-mainnet.infura.io/v3/" + process.env.REACT_APP_INFURA_ID,
                            80001: "https://matic-mumbai.chainstacklabs.com",
                        }
                    },
                },
            },
        });
        
         const connect = useCallback(async () => {
        
        try {
            const rawProvider = await web3Modal.connect();
            _initListeners(rawProvider);
            const connectedProvider = new Web3Provider(rawProvider, "any");
            const chainId = await connectedProvider.getNetwork().then(network => Number(network.chainId));
            const connectedAddress = await connectedProvider.getSigner().getAddress();
            const networkName = await connectedProvider.getNetwork().then(network => String(network.name))
            if( chainId !== null  ) {
                const web3 = new Web3(Web3.givenProvider);
                console.log(Web3.givenProvider)
                const userBalance = await web3.eth.getBalance(connectedAddress) / Math.pow(10,18);
                setBalance(userBalance);
            }
            setAddress(connectedAddress);
            setProviderChainID(chainId);
            setSymbol(getSymbol(chainId));     
            setChainID(chainId); 
            setNetworkName(networkName);      
            setProvider(connectedProvider);    
            setConnected(true);
            return connectedProvider;

        } catch(error) {
            console.log(error);
        }
  
    }, [provider, web3Modal, connected]);

    const checkWrongNetwork =  () => {

        if (providerChainID == 1 || providerChainID == 137) {   
            return false;
        }
        return true;
    };
![Screenshot from 2022-05-13 11-47-02](https://user-images.githubusercontent.com/99709723/168222654-46327491-4327-46ab-8533-1a0ac72307ee.png)

    `
    
  can anyone help me with this
![Screenshot from 2022-05-13 11-47-02](https://user-images.githubusercontent.com/99709723/168222735-1aa874e7-5123-4aae-b145-75850a3e6ff0.png)
</div>

**Comment by Devjohn12** [comment]
Talk to Polygon Support on the [Live support page](https://forummaticnetwork.com/) so that your issue can be looked into.

**Comment by ivanhdzd** [comment]
I think that the error is launched when you don't run your app in a domain without SSL (HTTPS), for testing purposes this error isn't launched in your localhost.

**Comment by ZeeshanAhmadKhalil** [comment]
For me its giving this error on https and on http its not giving this error but i am unable to connect my wallet :/

**Comment by deepak-interakt** [comment]
yeah wallet connect does not work with http , only https:// allowed. thanks and sorry for late response :)
