### ISSUE TITLE
Modal launches MetaMask and other wallets, but never prompts user to approve connection on iOS

### ISSUE THREAD

**Issue by jtshivers** [WalletConnect/walletconnect-monorepo#1041]
This happens with the Standalone Client, the NodeJS Client, and the Web3 Provider. Connecting to wallets through the QR Code Modal works perfectly on desktop, but when I try to connect through Chrome on iOS, it never actually goes through. All it does is launch the app, whether it be MetaMask, Trust Wallet, Coinbase Wallet or Crypto.com. The user is never prompted to approve the connection.

**Comment by ihorbond** [comment]
It works fine for me from both Safari and Chrome on iOS. Are you calling [provider.listAccounts()](https://docs.ethers.io/v5/api/providers/jsonrpc-provider/#JsonRpcProvider-listAccounts) ? 
I tested using my dapp here https://mint.zerocodenft.com/?siteId=fe2b783e-efc3-4cdb-74fa-08da2cbfe856

**Comment by jtshivers** [comment]
I am not calling provider.listAccounts(). I didn't see that suggested anywhere in the docs - do you have a repo I could look at to check how you implemented it?

**Comment by ihorbond** [comment]
@jtshivers you can look here
https://github.com/SmallRuralDog/web3modal-vue

**Comment by nnons** [comment]
+1 on this... Searched wide an far. This has nothing to do with iOS redirecting to app store. This is about universal link switching to a mobile wallet for approval but it never shows up. There is no good answer in the Discord or Github Issues. Replicate: iOS Chrome -> https://example.walletconnect.org/ -> Connect wallet use any of them.

**Comment by finessevanes** [comment]
@nnons @jtshivers is this still an issue?

**Comment by nnons** [comment]
@finessevanes Some wallets route to the correct app. Metamask routes to "Open in App Store"

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version  :)
