### ISSUE TITLE
Error: "client" is read-only. React Native walletconnect 2.0

### ISSUE THREAD

**Issue by daniyalayyaz** [WalletConnect/walletconnect-monorepo#1055]
WARN  Possible Unhandled Promise Rejection (id: 0):
Error: "client" is read-only.
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ndauwallet&modulesOnly=false&runModule=true:112016:32
_callee$@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ndauwallet&modulesOnly=false&runModule=true:112017:16
tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ndauwallet&modulesOnly=false&runModule=true:24208:23
invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ndauwallet&modulesOnly=false&runModule=true:24378:32
tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ndauwallet&modulesOnly=false&runModule=true:24208:23
invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ndauwallet&modulesOnly=false&runModule=true:24280:30
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ndauwallet&modulesOnly=false&runModule=true:24290:21
tryCallOne@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ndauwallet&modulesOnly=false&runModule=true:28929:16
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ndauwallet&modulesOnly=false&runModule=true:29030:27
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ndauwallet&modulesOnly=false&runModule=true:29617:26
_callTimer@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ndauwallet&modulesOnly=false&runModule=true:29517:17
_callReactNativeMicrotasksPass@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ndauwallet&modulesOnly=false&runModule=true:29552:17
callReactNativeMicrotasks@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ndauwallet&modulesOnly=false&runModule=true:29760:44
__callReactNativeMicrotasks@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ndauwallet&modulesOnly=false&runModule=true:3052:46
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ndauwallet&modulesOnly=false&runModule=true:2830:45
__guard@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ndauwallet&modulesOnly=false&runModule=true:3035:15
flushedQueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ndauwallet&modulesOnly=false&runModule=true:2829:21
flushedQueue@[native code]
callFunctionReturnFlushedQueue@[native code]
info Reloading app...
 BUNDLE  ./index.js

 LOG  Running "NdauWallet" with {"rootTag":221}

App.js

client = await WalletConnectClient.init({
      controller: true,
      projectId: "projectid",
      relayUrl: "wss://relay.walletconnect.com",
      metadata: {
        name: 'Wallet Connect',
        description: 'Wallet for WalletConnect',
        url: 'https://walletconnect.com/',
        icons: ['https://avatars.githubusercontent.com/u/37784886']
      },
  
    });

**Comment by finessevanes** [comment]
Is this still an issue?
