### ISSUE TITLE
Provider stuck in limbo after uninstalling wallet

### ISSUE THREAD

**Issue by TheDutchCoder** [WalletConnect/walletconnect-monorepo#1082]
**Describe the bug**
When a user connects with, say, the CoinBase browser extension, and then the user removes the extension without disconnecting first, WalletConnect is stuck in limbo as it keeps track of the connected wallet in localStorage which isn't updated when an extension is uninstalled/disabled.

Users can now no longer use WalletConnect to connect _any_ wallet, until they reinstall, and manually disconnect from the wallet they uninstalled.

**SDK Version (if relevant)**
 - Client: "@walletconnect/web3-provider": "^1.7.1"

**To Reproduce**
1. Connect with CoinBase wallet (browser extension)
2. Uninstall extension
3. Try to connect a wallet

**Expected behavior**
The "active" CoinBase wallet to be removed from localStorage upon disable/uninstall, or to do this after a timeout when events don't reach their target?

**Desktop (please complete the following information):**
 - OS: MacOS 12.3.1
 - Browser Chrome
 - Version 101

**Comment by finessevanes** [comment]
Is this still an issue?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
