### ISSUE TITLE
When using @walletconnect/client in react-native, an error occurs in approveSession

### ISSUE THREAD

**Issue by jwoo9928** [WalletConnect/walletconnect-monorepo#1083]
When using @walletconnect/client in react-native, an error occurs in approveSession in react-native

`	let connector = new WalletConnecter(
				{
					// Required
					uri: 'wc:551cf846-6edf-42a8-bdc9-ea3b3ea11f4f@1?bridge=https%3A%2F%2F7.bridge.walletconnect.org&key=e812a0ea9c887a5f6360e6cd61f56c2f56392934063c9645c1a92b69aa9c9c89',
					// Required
					clientMeta: {
						description: "WalletConnect Developer App",
						url: "https://walletconnect.org",
						icons: ["https://walletconnect.org/walletconnect-logo.png"],
						name: "WalletConnect",
					},
				}
			);
			// await connector.createSession();
			if(!connector.session.connected) {
				let selectedAddresses : Array<string> = await new Promise((resolve, reject) => {
					approvalRequest.current = { resolve, reject };
				});
				console.log("selectedAddresses",selectedAddresses);
				await connector.approveSession({
					accounts:selectedAddresses,
					chainId: 1
				})
				console.log("connector.session.connected",connector.session.connected);
			}`

<img width="840" alt="스크린샷 2022-05-26 오전 11 55 31" src="https://user-images.githubusercontent.com/51700184/170406251-09e870cd-c11d-430a-92e2-b3f61857ec09.png">

**Comment by finessevanes** [comment]
Is this still an issue?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
