### ISSUE TITLE
[Error: System random byte generator is not available.]React Native walletconnectclient v2

### ISSUE THREAD

**Issue by daniyalayyaz** [WalletConnect/walletconnect-monorepo#1090]
During Client.pair({uri})

[Error: System random byte generator is not available.]

**Comment by xzilja** [comment]
@daniyalayyaz We just released `2.0.0-rc.2` along with new installation guides for react-native https://walletconnect-docs-git-react-native-docs-288aaa-walletconnect1.vercel.app/2.0/javascript/guides/react-native

This should resolve your issue, plus not require any manual polyfilling

**Comment by adrianotadao** [comment]
@IljaDaderko do you know any example of walletcconnect 2.0 in react native that I could take a look ?

**Comment by finessevanes** [comment]
https://github.com/WalletConnect/react-native-examples
