### ISSUE TITLE
Is there possible to only select certain amount of wallets as options for user to choose?

### ISSUE THREAD

**Issue by 4D616B6572** [WalletConnect/walletconnect-monorepo#1091]
**Is your feature request related to a problem? Please describe.**
I read the code and find no where i can set only metamask, for example, as a only option for user to choose

**Describe the solution you'd like**
I guess the interface called "IMobileRegistryEntry" (type "IMobileRegistry") in this code will be the thing could fulfill what i need. But it seems like never be implemented anywhere in the entire codebase.

**Additional context**
please help out!

**Comment by mubarakone** [comment]
I've seen something like this in a prev issue.
https://github.com/WalletConnect/walletconnect-monorepo/issues/1029#issuecomment-1123618918

Not sure if `desktopLinks` method work for mobile wallets, but try and pass mobile wallets anyway, rather than desktop wallets like the OP of that issue wanted.

Lmk if it works...

**Comment by mubarakone** [comment]
It is possible: https://docs.walletconnect.com/quick-start/dapps/web3-provider#filter-mobile-linking-options
Either use `desktopLinks` for desktop, or `mobileLinks` for mobile.

**Comment by johnylawrence1987** [comment]
+1

Same issue here, `mobileLinks` not working on v1.8.0

**Comment by Mulander-J** [comment]
> +1
> 
> Same issue here, `mobileLinks` not working on v1.8.0

v1.7.8 set empty `mobileLinks`  see no mobile tag on ios devices. while on andriod devices mobile tag is still exist.

**Comment by chadyj** [comment]
This feature is supported in the next release of Web3Modal standalone mode.
We encourage everyone to upgrade https://github.com/WalletConnect/web3modal
