### ISSUE TITLE
Smart Contract Call Keep Loading on Trust Wallet

### ISSUE THREAD

**Issue by joseptl** [WalletConnect/walletconnect-monorepo#1096]
**Describe the bug**
When I use Trust Wallet to connect to a dapp (with a wallet connect implementation) with my smartphone,  at the time of make a request from the dapp to transfer funds , the trust wallet application opens, but it remains loading indefinitely in the Smart Contract Call interface.

Is this a Trust Wallet bug? or is it due to Wallet Connect?

Wallet Connect Version: 
walletconnect/web3-provider: 1.7.7

**Screenshots**
![WhatsApp Image 2022-05-28 at 12 49 21 AM](https://user-images.githubusercontent.com/83504893/170810485-12ac340e-6039-4412-9621-1c7ada768511.jpeg)

 - Device: Android, Iphone
 - Browser: chrome

**Comment by finessevanes** [comment]
Is this still an issue?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version  :)
