### ISSUE TITLE
Block cache not cleared when switching chains

### ISSUE THREAD

**Issue by kev1n-peters** [WalletConnect/walletconnect-monorepo#1097]
When switching chains the `BlockTracker` doesn't reset the highest block its seen and the block cache middleware (`CacheSubprovider`) doesn't clear its internal block cache. This can cause issues when when switching from a chain with high block numbers to a chain with low block numbers. For example, `tx.wait()` may never resolve when `WalletConnectProvider` is wrapped by a `ethers.providers.Web3Provider`, because the cache middleware will not update its internal cache when a lower block number is seen. Here is a hack that seems to work after switching chains:

```
// HACK: clear the block-cache when switching chains by creating a new CacheSubprovider
// Otherwise ethers may not resolve transaction receipts/waits
const index = walletConnectProvider._providers.findIndex(
  (subprovider: any) => subprovider instanceof CacheSubprovider
);
if (index >= 0) {
  const subprovider = walletConnectProvider._providers[index];
  walletConnectProvider.removeProvider(subprovider);
  walletConnectProvider.addProvider(
    new CacheSubprovider(),
    index
  );
  // also reset the latest block
  walletConnectProvider._blockTracker._resetCurrentBlock();
}
```

**Comment by finessevanes** [comment]
Is this still an issue?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version  :)
