### ISSUE TITLE
Unable to open URL

### ISSUE THREAD

**Issue by saber-yy** [WalletConnect/walletconnect-monorepo#1098]
**Describe the bug**
I am using this library @walletconnect/react-native-dapp in my rn program. When choosing Rainbow, Trust Wallet, Agrent, Metams and other wallets, you can jump normally. 
But when I click on imToken, TokenPocket, Leadger, Authereum and other wallets, I can't jump to it and get the following error message:

Error: Unable to open URL: file:///private/var/containers/Bundle/Application/ 078110DE-D5F4-4254-A6B6-CC86F31BE9C2/ signinclub.app/null/wc%3Furi=wc:ad3cddfe-1617-41c7-809e-7536ee7f4a0a@1%3Fbridge=https%253A%252F%252Fa.bridge.walletconnect.org&key= 839798882410cdd6a8c0e0e58b6c6ce61fb552c34d9133b6c96370fef3d58cb6&redirectUrl=siginclub:. Add the file to LSApplicationQueriesSchemes in Info.plist.

**Please note that the path after signin.app/  is null, I am not sure if this is because some folder was not created successfully**

**SDK Version (if relevant)**
 - Client: React-Native iOS
 - Version ^1.7.8

**Smartphone (please complete the following information):**
 - Device: iPhone13 
 - Version: iOS15.4
 
<img width="994" alt="image" src="https://user-images.githubusercontent.com/16433127/170825268-e6b7fc9e-76b8-4044-826e-0cf91ef07422.png">

**Comment by socheat-leang** [comment]
Any update with this bug ?

**Comment by yokamox** [comment]
I have the same problem when clicking on Ledger on IOS. I get that error in the console.
Tried adding the file querySchema to info.plist but then the error became cannot complete operation or something like that.
Any update on this matter?

**Comment by JungHsuan** [comment]
Same problem here when clicking on imToken on iOS.

`
Error: Unable to open URL: file:///wc%3Furi=wc:26119c71-ba6e-4334-8809-3386e9e2a6ca@1%3Fbridge=https%253A%252F%252Fi.bridge.walletconnect.org&key=632061bbd6356341d1963a6436e33c7b6bf145884a9608012423844fec2f62c3&redirectUrl=https://www.xxxx.com. Add file to LSApplicationQueriesSchemes in your Info.plist.
`

**Comment by negrudev** [comment]
any updates on this?

**Comment by finessevanes** [comment]
Is this still an issue?

**Comment by nmalzieu** [comment]
Yes, I have the same issue

**Comment by nmalzieu** [comment]
Seems the url it tries to open is 
`null/wc?uri=wc%3Adaeac7f5-2e5f-40bc-8866-972ef85c4...`

I think it's because this document => https://registry.walletconnect.org/data/wallets.json
has
```
"mobile":{
          "native":"imtokenv2:",
          "universal":null
       },
```

for imtoken for instance - it has no  universal link.

**Comment by nmalzieu** [comment]
<img width="469" alt="Capture d’écran 2023-03-03 à 09 47 28" src="https://user-images.githubusercontent.com/2102342/222674623-dd85c2be-811c-492c-8157-141ea4db7c25.png">

This code should def fallback to deeplink on iOS if there is no universal link but a deeplink in the JSON!

**Comment by erickgtzh** [comment]
any updates on this?

**Comment by finessevanes** [comment]
@nmalzieu Taking your suggestion to our team to see how they would like to move forward with this issue. Thank you!

cc: @erickgtzh

**Comment by flypaper0** [comment]
I believe the problem that deeplink has wrong URL encoding. It should be RFC 3986 @ganchoradkov

**Comment by finessevanes** [comment]
Hey @nmalzieu @erickgtzh I'm going to be closing this issue since it's a V1 issue (v1 is deprecated). Please take a look at our web example for RN v2:
https://github.com/WalletConnect/react-native-examples/tree/main/dapps/v2Explorer
