### ISSUE TITLE
Cannot use "in" operator to search for "id"

### ISSUE THREAD

**Issue by pedrouid** [WalletConnect/walletconnect-monorepo#1106]
**Describe the bug**

**SDK Version (if relevant)**
 - Client: Javascript
 - Version: 2.0.0-beta.100

**To Reproduce**
1. Call "disconnect" on either dapp or wallet example

**Expected behavior**
It should disconnect successfully without throwing any errors

**Screenshots**
![Screenshot 2022-05-30 at 11 41 52](https://user-images.githubusercontent.com/10136079/170965236-669ed63f-0976-49a5-8168-341153a58acd.png)

**Comment by bkrem** [comment]
Related: https://github.com/WalletConnect/walletconnect-monorepo/issues/558

**Comment by bkrem** [comment]
Required follow-ups post-merge of https://github.com/WalletConnect/walletconnect-utils/pull/16:

- [x] Publish new patch version of `@walletconnect/jsonrpc-utils`
- [ ] Integrate into `@walletconnect/sign-client` for `beta.101`: https://github.com/WalletConnect/walletconnect-monorepo/pull/1124
