### ISSUE TITLE
I want to change the initialization language to English, but I don't know how to set it?

### ISSUE THREAD

**Issue by boonook** [WalletConnect/walletconnect-monorepo#1109]
"@walletconnect/web3-provider": "^1.7.8",

 - "vite": "^2.9.1",
 - "vue": "^3.2.31",

Iwant to change the initialization language to English?

**Comment by boonook** [comment]
can you  help me?

**Comment by finessevanes** [comment]
Is this still an issue?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version  :)
