### ISSUE TITLE
请问一下该怎么设置@walletconnect/web3-provider初始化的语言类型呢？

### ISSUE THREAD

**Issue by boonook** [WalletConnect/walletconnect-monorepo#1111]
"@walletconnect/web3-provider": "^1.7.8",

"vite": "^2.9.1",
"vue": "^3.2.31",
该怎么设置@walletconnect/web3-provider初始化的语言类型呢？

**Comment by finessevanes** [comment]
Is this still an issue?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version  :)
