### ISSUE TITLE
http://example.walletconnect.org doesn't respond after user has signed has signed message with WalletConnect client 

### ISSUE THREAD

**Issue by hboon** [WalletConnect/walletconnect-monorepo#1122]
Tried all 3:

* eth_sign (legacy)
* eth_sign (standard)
* personal_sign

with several apps including AlphaWallet, MetaMask (mobile) and Rainbow. Seems to be broken a few hours ago, worked a while and then broken again.

**Comment by chadyj** [comment]
Thanks for reporting this.
There was a bridge server disruption, but everything should be good now.
