### ISSUE TITLE
Can't connect to Crypto.com's "DeFi Wallet" through `@walletconnect/client`- "Oops! Something went wrong"

### ISSUE THREAD

**Issue by einaralex** [WalletConnect/walletconnect-monorepo#1128]
**Describe the bug**
When trying to scan the QR code with "DeFi Wallet" from Crypto.com, there is an error "Oops! Something went wrong"
The `connect` event never seems to be triggered.

**To Reproduce**
1. Go to ''https://codesandbox.io/s/kxsz6'
2. Open "DeFi Wallet" on your iOS and click the QR scanner in the top right.
3. Scan QR code.
4. Observe errer.

**Expected behavior**
Should allow the user to connect the wallet.

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser: chrome

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: latest
 - App: DeFi Wallet by Crypto.com

**Comment by finessevanes** [comment]
Is this still an issue?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
