### ISSUE TITLE
the Web3 Provider example in the documentation doesn't work

### ISSUE THREAD

**Issue by lucadonnoh** [WalletConnect/walletconnect-monorepo#1129]
**Describe the bug**
if pasted in a js file and ran with Node, the QR pops up but it is not possible to connect.

**@walletconnect/web3-provider Version**
 - Client: JS
 - Version: ^1.7.8

**To Reproduce**
1. `npm install --save web3 @walletconnect/web3-provider`
2. copy and paste this code in a index,js file: 
```javascript
import WalletConnectProvider from "@walletconnect/web3-provider";

const provider = new WalletConnectProvider.default({
    rpc: {
        1: "https://cloudflare-eth.com",
        // ...
    }
});

//  Enable session (triggers QR Code modal)
await provider.enable();
```
3. run `node index.js`
4. wait for the QR to pop up in the terminal
5. try connecting using https://test.walletconnect.org/ or a mobile wallet
6. see that it doesn't connect

**Expected behavior**
I expect the wallet to connect.

**Screenshots**
![immagine](https://user-images.githubusercontent.com/30298476/171850903-6f03c2e6-149c-471d-8eed-463a0567cefb.png)
![immagine](https://user-images.githubusercontent.com/30298476/171851015-a5a6aedf-7871-410a-bd9c-12da91b6d1f7.png)
Using Zerion's wallet:
![index](https://user-images.githubusercontent.com/30298476/171851128-df8dccbb-e091-4ba8-bdb5-8d11e27a2931.jpg)

**Desktop**
 - OS: Windows 10 Pro
 - Browser: Firefox
 - Version: Nightly 103.0a1 (20220602093647)

**Smartphone**
 - Device: iPhone 12
 - OS: iOS 15.6
 - Wallet app: Zerion

**Comment by hackyguru** [comment]
@lucadonnoh does it work when connected with other wallets? just wanted to check if zerion is the only case or it happens with the other wallets as well.

**Comment by lucadonnoh** [comment]
im pretty sure zerion is not the issue here, also tried with MetaMask and Trust Wallet on iOS (other than https://test.walletconnect.org/ )

**Comment by hackyguru** [comment]
Hey, this might be because of breaking changes in the version. [This guide](https://medium.com/walletconnect/beginners-guide-to-the-walletconnect-v2-0-sign-sdk-for-javascript-developers-107f9eebb29b) could be a good reference for you if you are looking to use the v2 sign SDK with JS. @lucadonnoh

**Comment by hackyguru** [comment]
plus there are some code snippets in the article which can help you get a working setup quickly.

**Comment by finessevanes** [comment]
Is this still an issue?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
