### ISSUE TITLE
Missing or invalid emit chainId

### ISSUE THREAD

**Issue by 1648045459** [WalletConnect/walletconnect-monorepo#1136]
**Describe the bug**
chainChanged event not available

**SDK Version (if relevant)**
 - Client: @walletconnect/sign-client
 - Version 2.0.0-beta.100

**To Reproduce**
1. Successfully connected wallet
2. react wallet open session detail
3. click on 'Emit' button
4. See error => "Missing or invalid emit chainId"

**Expected behavior**
chainChanged event available

**Screenshots**
<img  src='https://raw.githubusercontent.com/1648045459/File/master/%E6%88%AA%E5%B1%8F2022-06-06%2014.50.35.png'>

**Desktop (please complete the following information):**
 - Browser chrome
 - Version Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36

**Additional context**

demo:
[Dapp: https://react-app.walletconnect.com/](https://react-app.walletconnect.com/)
[Wallet: https://react-wallet.walletconnect.com/](https://react-wallet.walletconnect.com/)

**Comment by bkrem** [comment]
Thanks for reporting this issue. This bug is already being tracked in the relevant web-examples repo (https://github.com/WalletConnect/web-examples/issues/29) so I will close this here.
