### ISSUE TITLE
Window.localhost.protocol checks fails in react-native chrome debugging

### ISSUE THREAD

**Issue by ptsayli** [WalletConnect/walletconnect-monorepo#114]
```
if (
      typeof window !== 'undefined' &&
      typeof window.location !== 'undefined' &&
      window.location.protocol !== 'https:' &&
      window.location.hostname !== 'localhost'
    ) {
      throw new Error('HTTPS is required for non-localhost origins')
    }
```

This code fails in react-native chrome debugging since it has window object but private IP (development macbook IP) for debugging.

**Comment by ptsayli** [comment]
@pedrouid Exchange key issue is fixed in beta.15 but introduced new bug for react-native (also in beta.16)

**Comment by pedrouid** [comment]
I can push beta.17 instead, we just need a quick fix for this.

**Comment by pedrouid** [comment]
I guess we can bring back the `browser` variable, which is not an elegant solution but it worked

**Comment by pedrouid** [comment]
Actually, we can just move this `"HTTPS is required for non-localhost origins"` error to WebCrypto, which is where it should live

**Comment by ptsayli** [comment]
Yes. But webcrypto & nativecrypto libs are utils. Should it have such checks?

**Comment by pedrouid** [comment]
This check is required by WebCrypto API, it technically would fail anyway whenever it tries to encrypt

**Comment by pedrouid** [comment]
Check issue #78

**Comment by pedrouid** [comment]
We might just remove it all together

**Comment by pedrouid** [comment]
Publishing this now with beta.17
