### ISSUE TITLE
Missing or invalid request chainId

### ISSUE THREAD

**Issue by matthewcarlreetz** [WalletConnect/walletconnect-monorepo#1149]
**Describe the bug**
When making a request `client.request({ topic, chainId: MAINNET, request: { method: "personal_sign", params: [] }})` I get an error "Missing or invalid request chainId"

**SDK Version (if relevant)**
`"@walletconnect/sign-client": "2.0.0-beta.100"`
Wallet  - `"react-native": "0.66.4"`
DAPP - `"react": "18.0.0-beta-149b420f6-20211119"`, `"blitz": "0.45.3"`

**To Reproduce**
1. Init Client
  ```ts
  const client = await client.init({
        projectId,
        relayUrl: "wss://relay.walletconnect.com",
        metadata: {
          name,
          description,
          url,
          icons: ["https://walletconnect.com/walletconnect-logo.png"],
        },
      })
  ```
2. Make connect request
  ```ts
   const NAMESPACE = "somenamespace"
   const MAINNET = `${NAMESPACE}:mainnet`
   const { uri = "", approval } = await client.connect({
        requiredNamespaces: {
          [NAMESPACE]: {
            chains: [MAINNET],
            methods: ["personalSign"],
            events: [],
          },
        },
      })
   ```
 3. Wait for approval
   ```ts      
   const session = await approval()
```
4. Make a request
  ```ts
   client
        .request({
          topic: session.topic,
          chainId: MAINNET,
          request: { method: "personal_sign", params: [] },
        })
  ```
5. `{code: 1000, message: "Missing or invalid request chainId"}`

Receive a successful response from `client.request`

**Screenshots**

**Desktop (please complete the following information):**
  *dApp*
 - OS: Mac OS 12.3.1
 - Browser: Safari

**Smartphone (please complete the following information):**
  *Wallet App*
 - Device: iPhone 11
 - OS: 15.5

**Comment by xzilja** [comment]
@matthewcarlreetz ty for the issue, made a note of this. Error is wrong here. I believe issue is invalid method i.e. `personalSign` vs `personal_sign`

In step 2 you have
```ts
    requiredNamespaces: {
        [NAMESPACE]: {
          chains: [MAINNET],
          methods: ["personalSign"],
          events: [],
        },
      },
```

In step 4
```ts
      .request({
        topic: session.topic,
        chainId: MAINNET,
        request: { method: "personal_sign", params: [] },
      })
```

Could you please verify that this fixes request for you.

**Comment by matthewcarlreetz** [comment]
@IljaDaderko apologies, that was a mistake on my part. I updated to use `personal_sign` for both, but sadly the error is still there.

**Comment by matthewcarlreetz** [comment]
On the wallet/react-native side I have 
```ts
      const approval = await signClient.approve({
        id: loginProposal.id,
        namespaces: {
          [NAMESPACE]: {
            accounts: [],
            methods: ['personal_sign'],
            events: [],
          },
        },
      })
```

**Comment by xzilja** [comment]
@matthewcarlreetz Ah that could be the issue, you need to provide 

```ts
accounts: [`${MAINNET}:0x...`]
```

Right now, as you approved with empty accounts there are no chains in session namespace, hence every chainId you provide will be invalid. 

We fixed this in upcoming beta 101 where when you `approve` in the wallet you need to provide namespace that satisfies `requiredNamespace` or provides "more than" required, but never "less".

Hopefully this was it, but let me know if you are still seeing issues.

**Comment by matthewcarlreetz** [comment]
@IljaDaderko that was it! Thanks!

**Comment by xzilja** [comment]
Closing this for now, we have a separate issue to improve error messages that should make it easier to debug these things in the future. Plus check has been added to ensure you can't pass "invalid" accounts when approving the session.
