### ISSUE TITLE
Our website mobile version bad connection with WalletConnect

### ISSUE THREAD

**Issue by vilnisp** [WalletConnect/walletconnect-monorepo#1162]
**Describe the bug**
On the mobile version of our site busdlotto.net in the place where you need to make a transaction, there is no connection with WalletConnect. If we try to make a transaction again and again wallet pops up only in a 7th time. It turns out to connect to the Metamask wallet and at the moment when we press "APPROVE" transaction nothing happens. An error "OOps, something went wrong" pops up. We cleared the cache and tried from different phones - the problem is with all devices. Our programmers say we must wait for the WalletConnect library update because our site is going through the backend system.

**SDK Version (if relevant)**
 - Client: JS
 - Version 2

**To Reproduce**
1. Go to 'busdlotto.net' on a mobile phone
2. Click on 'Connect wallet'
3. Choose "WalletConnect"
4. Scroll down to 'Buy a ticket" block
5. Press "Buy a ticket"
6. Check the box with a rules
7. Press "Buy ticket now"
8. See that nothing happened
9. Click on the cross and try to buy a ticket until the connection with the wallet appears
10. Try to pay small BNB amount for the commissions
11. See the error

**Expected behavior**
1) We expected that when we press "Buy a ticket" the wallet would immediately fly out/connected (not at the 7th time) 
2) We expected that when we were able to connect to the wallet, we would be able to pay the fee (сomission) without error and subsequently be able to pay for the ticket.

**Screenshots**
I attached a video where we show this issue and explain all the steps
https://user-images.githubusercontent.com/101573130/173799931-6d4b19f0-7529-4f74-b717-e35ebb04b3b8.mp4

**Desktop (please complete the following information):**
All the desktop versions works well, an issue is in a mobile version

**Smartphone (please complete the following information):**
We tried from a lot of phones. For example:
 - Device: LG K52
 - OS: Android 10
 - Browser: Google Chrome 
 - Google Chrome Version: 102.0.5005.99

**Comment by finessevanes** [comment]
Is this still an issue?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version  :)
