### ISSUE TITLE
Sending transactions on iOS shows a deep link prompt after first attempt

### ISSUE THREAD

**Issue by markdalgleish** [WalletConnect/walletconnect-monorepo#1165]
**Describe the bug**

Attempting to send a transaction on iOS via `@walletconnect/ethereum-provider` + ethers shows a prompt to the user to open in the app rather than opening the app automatically after the first attempt.

It seems to be caused by the fact that the deep link navigation is triggered some time after the user interaction has occurred. The browser then intercepts the navigation, giving users a chance to back out of it.

I pushed a minimal repro here: https://github.com/markdalgleish/walletconnnect-deeplink-prompt-issue
It's deployed here: https://walletconnnect-deeplink-prompt-issue.vercel.app

I was also able to reproduce this same issue by simply navigating to the deep link URL after a 1s timeout. To help with debugging, I also included a button for doing this in my minimal repro. Note this doesn't happen if you navigate immediately, so there's also a button for this too for comparison.

I'm not sure if this is something that can be fixed or not, short of pre-emptively navigating to the deep link URL, but I realise that might also cause issues with requests that are still in flight. Either way, I figured it was worth raising since it's not a great user experience.

**SDK Version**
 - Client: JS
 - Version: `@walletconnect/ethereum-provider@1.7.8`

**To Reproduce**
1. Go to https://walletconnnect-deeplink-prompt-issue.vercel.app on iOS.
2. Connect wallet.
3. Tap "Send transaction".
4. Cancel request and go back to browser.
5. Tap "Send transaction" again.
6. See prompt to `Open this page in "App name"?`

**Expected behavior**
Immediately navigates to the app, the same way it did on the first attempt.

**Screenshots**

![Deep link prompt](https://user-images.githubusercontent.com/696693/173999526-cf79893e-184d-4915-9e8a-eb3bf8fb597b.png)

**Smartphone:**
 - Device: iPhone 12 Pro
 - OS: iOS 15.5
 - Browser: Safari

**Comment by markdalgleish** [comment]
Surprisingly I'm not seeing this issue on https://example.walletconnect.org, but looking at the code I can't see why it wouldn't run into this too: https://github.com/WalletConnect/walletconnect-example-dapp/blob/8a3216597474b09a7dcadc84efaf7e393c8eb05d/src/App.tsx#L284-L357

In my repro app, I've tried making the same API calls as the WC example by hard coding multiple `await fetch(...)` calls before navigating and I still get prompted. I can't figure out why the WC example works without issue. Any ideas?

**Comment by intergalacticspacehighway** [comment]
@markdalgleish i think it all comes down to how long does it take before setting `window.location.href` ([WalletConnect uses this](https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/legacy/client/src/core.ts#L1062) instead of window.open). If it happens quickly after the user action it works as expected or else shows the popup. I was able to reproduce the issue by below change in [example](https://github.com/WalletConnect/walletconnect-example-dapp/blob/8a3216597474b09a7dcadc84efaf7e393c8eb05d/src/App.tsx#L284-L357). 

<img width="827" alt="Screenshot 2022-06-24 at 12 25 09 AM" src="https://user-images.githubusercontent.com/23293248/175376160-c6503b25-41a3-476e-a32e-5a2ea6b76adb.png">




https://user-images.githubusercontent.com/23293248/175377437-a5cf5775-63f4-4185-97f5-cbc6deee4c8e.MP4

**Comment by intergalacticspacehighway** [comment]
i think there might not be a solution to this (wishing i am wrong!). I think acceptable UX would be if you're doing "some stuff" before signing/sending transaction, show a `check your wallet` button that a user can tap and redirected, instead of auto redirection. Also, wallet notifications might help in most cases

**Comment by markdalgleish** [comment]
I was also able to introduce this issue to the WalletConnect example by adding the following line after the 2nd network request when sending a transaction, forcing it to wait until the next tick before continuing:

<img width="807" alt="WC example" src="https://user-images.githubusercontent.com/696693/175397780-912c2ae1-b9cc-4237-bc61-74d70d78ea33.png">

If I add this line any earlier it doesn't work. It seems like it's not simply a timing issue and that the browser is using some more advanced heuristics to decide whether a navigation is triggered by a user action or not.

**Comment by intergalacticspacehighway** [comment]
wow. had some more observations.

#### This works as expected
<img width="792" alt="Screenshot 2022-06-24 at 10 05 52 AM" src="https://user-images.githubusercontent.com/23293248/175463060-a9de691a-a232-4134-9fd8-b657aa4f9389.png">

#### This doesn't
<img width="792" alt="Screenshot 2022-06-24 at 9 56 09 AM" src="https://user-images.githubusercontent.com/23293248/175462052-c418d47f-ef2c-4b60-8a69-2aaa0780bdd3.png">

- sometimes it works during first try but fails on subsequent attempts.

#### Extreme, but even this works

<img width="792" alt="Screenshot 2022-06-24 at 9 57 26 AM" src="https://user-images.githubusercontent.com/23293248/175462156-c0f39302-7a0e-42b6-a297-53ed71531c88.png">


I think it might be allowing multiple fetch (under certain timeout) under user action. Here's the server if you want to try `https://my-vercel-functions-six.vercel.app/api?delay=1000`

**Comment by intergalacticspacehighway** [comment]
> I think it might be allowing multiple fetch (under certain timeout) under user action.

if this is true, WalletConnect might have to move window.location.href assignment to fetch API success instead of `call_request_sent` socket listener.

Correction: looking into source code `call_request_sent` appears to be [triggered synchronously](https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/legacy/client/src/core.ts#L709) (not a socket listener). uff. will have to dig more 🤦

**Comment by intergalacticspacehighway** [comment]
okay, i have one more theory.
in your repro example, it's using provider from ethers which does a [bunch of things](https://github.com/ethers-io/ethers.js/blob/master/packages/abstract-signer/src.ts/index.ts#L124) before calling `sendTransaction` on actual WalletConnect's connector instance. I think the ethers provider does gasEstimation and it might be using polling or setTimeout. Will have to dig more, I have a hunch that this might be causing it.

**Comment by markdalgleish** [comment]
I've been digging into [`JsonRpcSigner` in Ethers](https://github.com/ethers-io/ethers.js/blob/master/packages/providers/src.ts/json-rpc-provider.ts) to understand this a bit more, and here's what I've found.

Calling `signer.sendTransaction(tx)` results in two blocks of async work happening before the deep link fires:
- It calls `this.provider._getInternalBlockNumber` ([source](https://github.com/ethers-io/ethers.js/blob/608864fc3f00390e1260048a157af00378a98e41/packages/providers/src.ts/json-rpc-provider.ts#L271))
- It then calls `this.sendUncheckedTransaction` which itself performs a couple of async calls:
  - If the transaction's `gasLimit` property is nullish, it calls `this.provider.estimateGas` ([source](https://github.com/ethers-io/ethers.js/blob/master/packages/providers/src.ts/json-rpc-provider.ts#L226))
  - If the transaction's `to` property exists, it calls `this.provider.resolveName` ([source](https://github.com/ethers-io/ethers.js/blob/608864fc3f00390e1260048a157af00378a98e41/packages/providers/src.ts/json-rpc-provider.ts#L232))

Knowing this, I've been able to work around the timing issues by doing the following:
- Resolve the `gasLimit` and `to` properties up front by calling `signer.populateTransaction` ([source](https://github.com/ethers-io/ethers.js/blob/608864fc3f00390e1260048a157af00378a98e41/packages/abstract-signer/src.ts/index.ts#L197)) rather than doing it as part of the `sendTransaction` call.
- Call `signer.sendUncheckedTransaction` directly so that it doesn't call `this.provider._getInternalBlockNumber`.

I've expanded [my repro](https://walletconnnect-deeplink-prompt-issue.vercel.app) to include a demo of this. There's now an additional row of actions where you can populate a transaction, then—when it's ready—pass it to either `sendTransaction` or `sendUncheckedTransaction`.

![Populate transaction](https://user-images.githubusercontent.com/696693/176101374-14043e38-ad38-4246-9baa-705067bb8905.png)

I've found that tapping "Send transaction" still works most of the time, but occasionally prompts me to open in the app instead of navigating immediately. If I tap "Send unchecked transaction", it takes me directly to the app every time without a prompt.

**Comment by intergalacticspacehighway** [comment]
Thanks for digging in, really makes sense. I have some questions.

Why does it [wait for](https://github.com/ethers-io/ethers.js/blob/608864fc3f00390e1260048a157af00378a98e41/packages/providers/src.ts/json-rpc-provider.ts#L271) `_getInternalBlockNumber` call before calling `sendUncheckedTransaction`, it doesn't seem to be using it's return value in `sendUncheckedTransaction` (unless it mutates stuff or is waiting [purposefully](https://github.com/ethers-io/ethers.js/blob/608864fc3f00390e1260048a157af00378a98e41/packages/providers/src.ts/json-rpc-provider.ts#L270)).

Also, I don't get the reason why should we "estimate" gas on dapp side (unless we specify it explicitly), shouldn't it be handled at the wallet level as it'll eventually calculate it if I am not wrong.

**Comment by markdalgleish** [comment]
Some additional findings in terms of a workaround:

- Calling `signer.populateTransaction` worked with WalletConnect but was throwing errors for me when using MetaMask, so I had to use `provider.estimateGas` and `provider.resolveName` directly. Transactions also support promises for any their values so you can use the [resolveProperties](https://docs.ethers.io/v5/api/utils/properties/#utils-resolveproperties) function from `ethers/lib/utils` ([source](https://github.com/ethers-io/ethers.js/blob/608864fc3f00390e1260048a157af00378a98e41/packages/properties/src.ts/index.ts#L32)) to resolve these ahead of time.
- An alternative to using `signer.sendUncheckedTransaction` is to use [UncheckedJsonRpcSigner](https://docs.ethers.io/v5/api/providers/jsonrpc-provider/#UncheckedJsonRpcSigner) instead ([source](https://github.com/ethers-io/ethers.js/blob/608864fc3f00390e1260048a157af00378a98e41/packages/providers/src.ts/json-rpc-provider.ts#L329)). This gives you a signer with the same interface, but calling `sendTransaction` always uses `sendUncheckedTransaction` internally. You can get an instance of this from `JsonRpcSigner` by calling `signer.connectUnchecked()` ([source](https://github.com/ethers-io/ethers.js/blob/608864fc3f00390e1260048a157af00378a98e41/packages/providers/src.ts/json-rpc-provider.ts#L193)).

EDIT: As per my first point, I've updated my repro to avoid `signer.populateTransaction` and to populate it manually using `resolveProperties`, `provider.resolveName` and `provider.estimateGas`.

**Comment by jxom** [comment]
Update: we are starting to work on "eager" hooks in wagmi (using @markdalgleish's eager populating of txn request) to help with deeplinking issues on iOS.

https://github.com/tmm/wagmi/pull/658

**Comment by xaun** [comment]
Maybe https://github.com/WalletConnect/walletconnect-monorepo/issues/444#issuecomment-1173373084 is related to this? I experience this alert previously but since making the mentioned change in approach, this alert does not show up anymore.

**Comment by markdalgleish** [comment]
I opened a PR adding documentation to the WalletConnect site explaining the cause of these iOS app link issues and how to avoid them which recently got merged. The documentation is now live: https://walletconnect-docs-git-fork-markdalgleish-b4d402-walletconnect1.vercel.app/mobile-linking#ios-app-link-constraints

I'm closing this issue since there's not much else that can be done from a WalletConnect perspective. I've started a GitHub discussion against Ethers to see if anything can be done there to help WalletConnect consumers avoid these issues: https://github.com/ethers-io/ethers.js/discussions/3178
