### ISSUE TITLE
connector.connect() no longer works on Android

### ISSUE THREAD

**Issue by david-mcdowall** [WalletConnect/walletconnect-monorepo#1175]
**Describe the bug**
We are currently using `@walletconnect/react-native-dapp 1.7.5` to allow users to use WalletConnect to connect their existing crypto wallet to our react native dapp. We implemented this several months ago and everything was working as expected, but WalletConnect has now stopped working on Android devices only. When the `connector.connect()` is called - if the user has a wallet installed (such as MetaMask) then they will be automatically pushed through to the wallet app, or if they don't have any wallets installed then they will be redirected to a '404' webpage on the WalletConnect website. 

At this point, if the user has no wallets installed then we expect to see the WalletConnect modal to pop-up displaying all the supported wallets to select from. 

**SDK Version (if relevant)**
 - Client: React Native
 - Version 0.63.4
 - Android SDK 30

**To Reproduce**
Steps to reproduce the behavior (on Android devices):
1. Define connector `const connector = useWalletConnect();`
2. Trigger connect function `connector.connect().then(() => console.log('success')); `

**Expected behavior**
connector.connect() function is expected to trigger the WalletConnect modal displaying all supported wallet options. This works on iOS and used to work on Android. 

**Smartphone (please complete the following information):**
 - Device: Android Galaxy A12
 - OS: Android 11

**Additional context**
I believe the problem lies with the open function inside the `WalletConnectProvider.js` component - specifically inside the if statement for Android devices. The URL `https://walletconnect.org/wallets` is incorrect and this is where the 404 is coming from when no wallets are detected - but the pop-up WalletConnect modal is never displayed, even after completely removing the if statement and forcing the visible attribute to be set to true within the state. 

```
const open = React.useCallback(async (uri, cb) => {
        if (Platform.OS === 'android') {
            const canOpenURL = await Linking.canOpenURL(uri);
            if (!canOpenURL) {
                Linking.openURL('https://walletconnect.org/wallets');
                throw new Error('No wallets found.');
            }
            await Linking.openURL(uri);
        }
        setState({
            uri,
            visible: true,
            cb,
        });
        return undefined;
    }, [setState]);
```

**Comment by david-mcdowall** [comment]
Resolved

404 URL error can be resolved by updating `https://walletconnect.org/wallets` to `https://walletconnect.com/registry`

Apparently WalletConnect modal displaying all supported wallets is not supported on Android - so expected behaviour is now to link to this URL unless any of the supported wallets are installed.

**Comment by tigerraj32** [comment]
This issue still exist, please reopen the issue. Even after changing` https://walletconnect.org/wallets` to `https://walletconnect.com/registry`. They both return 404 URL error.

**Comment by jeremyblong** [comment]
Has anyone actually* resolved this issue? I have successfully gotten it to prompt/open whatever wallet is installed but it does NOT ask permission or indicate any way to connect the wallet to said Dapp application. 

It simply opens whatever wallet is installed and that's it - I've been working on this for 2 days now as this is vital functionality for my use-case. Please help if anyone has any clues or ideas
