### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 

### ISSUE THREAD

**Issue by matthewcarlreetz** [WalletConnect/walletconnect-monorepo#1177]
**Describe the bug**
When initializing the wallet client on React Native I get the warning
> MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 open listeners added. Use emitter.setMaxListeners() to increase limit

**SDK Version (if relevant)**
 - Client: [e.g. JS, Swift, Kotlin]

**To Reproduce**
Init the client...
```ts
      client = await SignClient.init({
            projectId: Config.WALLET_CONNECT_PROJECT_ID,
            relayUrl: 'wss://relay.walletconnect.com',
            metadata: {
              name: 'Wallet',
              description: 'Wallet',
              url: Config.WALLET_CONNECT_METADATA_URL,
              icons: [],
            },
          })
```
**Expected behavior**
No warnings to appear

**Screenshots**
![IMG_0825](https://user-images.githubusercontent.com/1760821/174894074-0b06c5f2-847f-40cf-b545-f988e763defc.PNG)

**Desktop (please complete the following information):**
dApp

OS: Mac OS 12.3.1
Browser: Safari

**Smartphone (please complete the following information):**
Wallet App

Device: iPhone 11
OS: 15.5

**Comment by Jake-Mulhern** [comment]
This is still happening for me.  Is there a way to fix this?

**Comment by vibern0** [comment]
Also happening to me. Did I miss anything?

**Comment by samyan** [comment]
Still the same and multiple bugs...

**Comment by jaan1025** [comment]
same, wtf

**Comment by mighty-phoenix** [comment]
I'm facing the same issue?
How do I fix this?
Quick reply would be highly appreciated!
Thanks!

**Comment by mighty-phoenix** [comment]
Kind ping here!! @matthewcarlreetz @samyan @bkrem @obernardovieira @jaan1025

**Comment by raspberry-zk** [comment]
Same issue!  
Wasn't there any answer?  
It seems in my case it will happen when there is some limitation on the network connection so maybe with the WC relayer.
