### ISSUE TITLE
Error: Session currently disconnected

### ISSUE THREAD

**Issue by gate3** [WalletConnect/walletconnect-monorepo#1192]
**Describe the bug**

I have been able to connect to metamask using the SDK and calling the `.connect`. But immediately after connecting successfully, I try to do a switch network but it gives the error 

`Error: Session currently disconnected`

I checked the .connected property and its actually false. Another thing I tried is to listen to the `connect` event and maybe switch the network there, but no luck. 

**SDK Version (if relevant)**
 - Client: Js React native
 - Version ^1.7.8

**To Reproduce**
1. Use the useWalletConnect hook and get the connector
2. Call the connector.connect
3. Check value of the connector.connected
4. You will see its false

**Expected behavior**
Should stay connected after a successful connection

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Android React Native

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Z Flip
 - OS: Android

**Additional context**

**Comment by finessevanes** [comment]
Is this still an issue?

**Comment by pavandugariya** [comment]
Is this still an issue?

**Comment by anietieasuquo** [comment]
@finessevanes, @pavandugariya Yes actually this is still an issue, and a quite annoying one at that. Is there any solution to this?

**Comment by pavandugariya** [comment]
@anietieasuquo Earlier universal provider was doing it now I switched to the Ethereum provider it's working fine.
you can try Ethereum provider if you have not try

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version  :)
