### ISSUE TITLE
[JS] Improve developer experience when working with new SDK 

### ISSUE THREAD

**Issue by xzilja** [WalletConnect/walletconnect-monorepo#1195]
# Issue 1

While working on example wallet it became clear that namespace change we introduces has a lot of cognitive overhead and requires a ton of work to be done in order to accomplish tasks like selecting accounts and constructing namespace for session approval i.e. a ton of `Object.keys` / `Object.values` has to be used and you have to always be careful to not miss or override something.

There is a bit of further complexity due to CAIP compliant accounts we use and namespace extensions.

We should define list of common wallet and dapp operations that could be performed when namespaces are involved and come up with set of utilities and example to simplify these workflows.

# Issue 2

Reduce amount of types that need to be imported and ensure they are easy to access i.e. no super nested namespaces.

# Issue 3

We were previously using constants for event names, but now have these auto completed by typescript, in fact they need to be autocompleted strings to correctly type event listeners as well. So we should prob remove const usage.

# Issue 4

Throughout the sdk we use `params` object for basically all functions, this results in unexpected ts issue where users hovering over rpc methods or engine methods don't actually see what params are exactly just `params: EngineTypes.ApproveParams`. This doesn't say anything to a newcomer. We should find a way to expose full params objects or at least add jsdoc comments that describe them.

# Issue 5
Need better / more granular errors to be thrown by validation, as these are very general atm. In addition to this we should check whether new error codes are all in place. see WalletConnect/walletconnect-specs#50

**Comment by finessevanes** [comment]
@0xAsimetriq are these still issues? 😁

**Comment by xzilja** [comment]
I think safe to close for now as a lot of these have been addressed 👍
