### ISSUE TITLE
Access to XMLHttpRequest at 'https://relay.walletconnect.com/auth-nonce?did=did:key:z6MkiFoegkfYM1Xic7GK9SCg6VWivBgrf3SURRkTJ2LMKRfE' from origin 'http://localhost:3000' has been bl

### ISSUE THREAD

**Issue by 1648045459** [WalletConnect/walletconnect-monorepo#1199]
**Describe the bug**
Local http://localhost:3000, Client initialization failed
hint:
Access to XMLHttpRequest at 'https://relay.walletconnect.com/auth-nonce?did=did:key:z6MkiFoegkfYM1Xic7GK9SCg6VWivBgrf3SURRkTJ2LMKRfE' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**SDK Version (if relevant)**
 - Client: @walletconnect/sign-client
 - Version v2.0.0-beta.101

**To Reproduce**
1. Download ZIP: https://github.com/WalletConnect/web-examples/archive/refs/heads/main.zip
2. update REACT_APP_PROJECT_ID 
3. npm install
4. npm run start
5. Open the http://localhost:3000 address in the browser

**Expected behavior**
Successfully initialized client, no exception

**Screenshots**
<img src="https://raw.githubusercontent.com/1648045459/File/master/2022-06-28%2015.02.37.png" alt="" >

**Desktop (please complete the following information):**
 - OS: MAC M1
 - Browser chrome
 - Version 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36'

**Comment by bkrem** [comment]
This seems to be a variation of the issue discussed here: https://github.com/WalletConnect/web-examples/issues/38

The recommendation for this is the same as described there in order to align with what the relay expects: https://github.com/WalletConnect/web-examples/issues/38#issuecomment-1181466526
