### ISSUE TITLE
dependencies missing

### ISSUE THREAD

**Issue by lucadonnoh** [WalletConnect/walletconnect-monorepo#1213]
**Describe the bug**
The `tslib` and `better-sqlite3` modules are missing when installing `@walletconnect/sign-client@experimental`.

**Comment by xzilja** [comment]
@lucadonnoh could you try with `2.0.0-rc.2`. `better-sqlite3` is a peer dependency required when using nodejs, so if thats the case you should install it. `tslib` on the other hand shouldn't be, so that might be an actual issue

**Comment by bkrem** [comment]
Closing.

* `tslib` should be fixed for good in https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.1.4
* `better-sqlite3` is no longer used
