### ISSUE TITLE
Unable to build and deploy bridge/relay server

### ISSUE THREAD

**Issue by rollycodes** [WalletConnect/walletconnect-monorepo#1219]
Unable to build and deploy bridge server

1. Repo head has server code removed
2. Versions till 2.0.0-beta.101 have it but "make deploy as per README" doesn't work because Makefile doesn't now have a deploy operation
3. Versions till 2.0.0-beta.26 have a Makefile as per README but the "make deploy" errors out there because of missing caddy.
4. Older versions with caddy issue not present fail the "make deploy" because of some or the other git repo dependency not existing anymore!

Any help here will be highly appreciated! Thanks!

**Comment by vuletiki** [comment]
I simply set `REDIS_URL` env and `yarn start` in relay folder.
I found this link https://github.com/WalletConnect/ts-relay but cannot access or it's wrong.

**Comment by sbc64** [comment]
The relay is located here: https://github.com/WalletConnect/relay

**Comment by olegabr** [comment]
@sbc64 Can it work with WalletConnect v1 clients also?
Is there a way/guide for production deployment?

**Comment by finessevanes** [comment]
Is this still an issue?

**Comment by rollycodes** [comment]
Hi @finessevanes 

For the interim, I used on old repo relay-ts to run relay server for v1 clients. Had to fix a few issues there in a fork though.

Haven't tried the new relay repository shared above. 

Can do that sometime this month if that'd help.

**Comment by tfalencar** [comment]
@rollycodes  can you please add the full link to the repo here (including branch) ? I'm looking in many places but I can't find the code for v1 relay/bridge so far.
