### ISSUE TITLE
Add updateChain method to Client SDK

### ISSUE THREAD

**Issue by pedrouid** [WalletConnect/walletconnect-monorepo#122]
Following Ethereum/EIPs#2015, the client SDK will include a method named `updateChain` which will require the parameters from the JSON-RPC method `wallet_updateChain` described on EIP-2015 as follows:
### Example 1
A JSON-RPC request from a Dapp to switch the Ethereum Goerli chain would be as follows:
```json
{
  "id":1,
  "jsonrpc": "2.0",
  "method": "wallet_updateChain",
  "params": [
    {
      "chainId": 5,
      "networkId": 5,
      "rpcUrl": "https://goerli.infura.io/v3/406405f9c65348f99d0d5c27104b2213",
      "nativeCurrencyName": "gorETH"
    }
  ]
}
```

### Example 2
A JSON-RPC request from a Dapp to switch the POA Network's xDAI chain would be as follows:
```json
{
  "id":1,
  "jsonrpc": "2.0",
  "method": "wallet_updateChain",
  "params": [
    {
      "chainId": 100,
      "networkId": 100,
      "rpcUrl": "https://dai.poa.network",
      "nativeCurrencyName": "xDAI"
    }
  ]
}
```

**Comment by saber-yy** [comment]
@walletconnect/react-native-dapp version : 1.7.8

when i try to call connector.updateChain(chainInfo) , i get this in reject call . 
The method wallet_updateChain does not exist/is not available

**Comment by pingu2k4** [comment]
Same as @saber-yy above. Have also tried sending a custom request with method set to `wallet_updateChain`, and passing in the relevant chainId in params, but get an error stating that the method is not supported.
Is this a 2.0 beta thing still? Would have thought not as was implemented in 2019 according to this?
