### ISSUE TITLE
`Error: Missing or invalid topic field` thrown when calling `killSession`

### ISSUE THREAD

**Issue by khoanguyen-yang** [WalletConnect/walletconnect-monorepo#1234]
**Describe the bug**

**SDK Version (if relevant)**
 - Client: React Native
 - Version: 1.7.1

1. Create a new Wallet Connect instance (using `new` operator, not calling `createSession`)
2. `approveSession` on `session_request` event
3. Kill the session on `'disconnect'` event using `killSession`

**Expected behavior**
No error being thrown

**Additional context**
Running on iOS simulator

**Comment by finessevanes** [comment]
Is this still an issue?

**Comment by gamalielhere** [comment]
@finessevanes yes. This error is still being thrown on 1.8.0

**Comment by audieleon** [comment]
I am also receiving this issue, but in my case, it was because I had an unprotected call that was killing the session even when there was no session. Ideally, this wouldn't throw, or at least it would give a better error?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
