### ISSUE TITLE
Only QR code showing with no options to select wallet 

### ISSUE THREAD

**Issue by 0xmovses** [WalletConnect/walletconnect-monorepo#1235]
**Describe the bug**
On some OS devices the Wallet Connect UI does not show options to connect wallet. Instead just shows a QR code. 
<img width="394" alt="Screenshot 2022-07-11 at 14 10 56" src="https://user-images.githubusercontent.com/35300528/178271795-34f3388b-d6f3-4cd7-b719-9a46eae34b0f.png">
We can confirm this issue is *not* related to wagmi library as the problem also occurs when that library is not used. 

**To Reproduce**
It's tricky to reproduce, I myself can't reproduce only my co-founder on the other side of the planet. It occurs on iPhone 11 Pro iOs 15.5. 

**Expected behavior**
The UI should show the toggle to connect to the desire wallet. As in the screenshot below
<img width="330" alt="Screenshot 2022-07-11 at 14 13 01" src="https://user-images.githubusercontent.com/35300528/178272220-a3eb8e57-d17d-4987-b879-6df43ef684e4.png">

**Comment by bkrem** [comment]
Hi @rvmelkonian,

In my experience this only happens when the modal was unable to resolve wallets from the registry, when a subrequest to e.g. https://registry.walletconnect.com/api/v2/wallets fails.

Could you confirm based on network calls whether this was the case?

**Comment by siosio34** [comment]
I also have this error

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)

**Comment by williamliangwl** [comment]
> Hi @rvmelkonian,
> 
> In my experience this only happens when the modal was unable to resolve wallets from the registry, when a subrequest to e.g. https://registry.walletconnect.com/api/v2/wallets fails.
> 
> Could you confirm based on network calls whether this was the case?

Hi @bkrem @glitch-txs , we are currently facing the same issue and yes when I try to see the network calls, whenever there's failure on request to https://registry.walletconnect.com/api/v2/wallets, it will only show the QR Code

I can reproduce this using the following steps:
1. Open `https://jup.ag` using the mobile web version
2. Change the Dimensions to `iPhone SE`
3. Click `Connect Wallet` and choose `WalletConnect`
4. Only QR Code is shown

However, using the same steps, but by changing the Dimensions to `Samsung Galaxy S8+`, there's no network log about the registry endpoint, but a proper Connect button is showed 

I used Microsoft Edge browser in Macbook to reproduce those
