### ISSUE TITLE
updateChain method is not supported

### ISSUE THREAD

**Issue by pingu2k4** [WalletConnect/walletconnect-monorepo#1261]
**Describe the bug**
updateChain method is not supported

**SDK Version (if relevant)**
 - Client: js
 - Version 1.7.8

**To Reproduce**
1. call connector.updateChain() or sencCustomRequest with a method of `wallet_updateChain`

**Expected behavior**
An error is produced, stating that the method is not supported.

**Additional context**
Appears to have been implemented years ago, according to #122 but it definitely doesn't and can't see any mentions elsewhere of it not working or any documentation to suggest it should or shouldn't be working in 1.x.

**Comment by finessevanes** [comment]
Is this still an issue?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version  :)
