### ISSUE TITLE
Request for support of additional SSL certificate(s)

### ISSUE THREAD

**Issue by XBDRX** [WalletConnect/walletconnect-monorepo#1273]
**Request that you support additional SSL certificates other than Let's Encrypt on your secure socket server**
We're developing apps for LG WebOS Smart TVs that use WalletConnect.

We're having an issue connecting to your secure socket service on WebOS TVs from 2016-2018 and I suspect the issue is caused by last year's expiry of the Let's Encrypt root certificate. Those TVs haven't received a firmware update from LG with the new root and so fail to connect. The issue is described here https://techcrunch.com/2021/09/21/lets-encrypt-root-expiry/

**Proposed Solution**
If LG provide us with their list of trusted roots, I think the issue can be resolved if you're willing to add one of those (in addition to your current certificate). Perhaps you could add it to a staging server initially and give us access, or if you have access to a suitable TV, I could give you a test app and walk you through how to install it?

**Alternative Solutions**
LG are aware of the issue but haven't scheduled an update for these devices with the new certificates. 

**Additional context**
I've emailed Pedro with details of which company I represent and we are happy to provide additional information in support of the request.

**Comment by chadyj** [comment]
Sounds like an interesting use case @XBDRX!

Can you please give more technical context to the problem?  What SSL cert in particular is the problem?

**Comment by XBDRX** [comment]
Hi Chad

Thanks for the response. I'm sure we can arrange a video demo if you would like to see what we're working on.

Here's what is happening:
1. The front page of our TV app presents a QR code
2. The user scans the QR code with the Metamask app on their phone
3. Once scanned, the account is linked on the TV and progresses to the home page showing the user's NFTs

It works fine on TVs from 2019+ but on earlier TVs, we get the following error when trying to connect from the TV (presumably waiting for the accounts linked response) 
`WebSocket connection to 'wss://c.bridge.walletconnect.org/?env=browser&host=&protocol=wc&version=1' failed: WebSocket opening handshake was canceled`

It looks like it's caused by the expiration of 'DST ROOT CA X3' from Let's Encrypt. See https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/ and this post on the official WebOS TV Developer Forum https://developer.lge.com/community/forums/RetrieveForumContent.dev?detailContsId=FC22090525&sMenuId=53&contsTypeCode=QUE&prodTypeCode=TV

To be clear, the problem doesn't lie with WalletConnect but with LG not releasing a firmware update for the older TVs containing the newest Let's Encrypt root certificate. However, they have no timeline for releasing a firmware update and so the next preferred solution for us is that you add support for another of LG's trusted roots in addition to your current ones.

They provide their trusted roots at https://webostv.developer.lge.com/discover/specifications/web-engine/

Happy to arrange a chat at your convenience if you're available.

**Comment by chadyj** [comment]
Thanks @XBDRX for context.  We will investigate.

**Comment by bazaah** [comment]
Hi @XBDRX

So having investigated this a bit here's my analysis so far.

### Top level summary

1. Provide us with a TLS cert/key pair that is signed with the correct trusts for a custom endpoint (e.g `xbdrx.bridge.walletconnect.org`)
2. Use this endpoint in your walletconnect client `bridge:` config

### Details

First, we (WalletConnect) would need a CA signed by one of the trusts that you linked above.

Of the list of trusts, only `rootCA_40`  `rootCA_45`  `rootCA_50` are still valid, as the others expired in 2015. All three are managed by https://www.accv.es/en/, which looks to be a Spanish CA. We would need a TLS certificate either signed by them, or cross signed with their root trusts.

They appear to allow you to purchase TLS certs here: https://www.accv.es/en/tu-certificado/no-personales/ssl/ , though I'm not sure how expensive it is. You may also be able to find some other CA that cross signs with the above Spanish CA, which would
work too.

Whatever the case, you get a TLS cert/key for a custom endpoint, say `xbdrx.bridge.walletconnect.org`.
Then you provide us a copy of the cert/key pair, which we will securely store, and use for connections to that endpoint.

Now, likely you will need our help in proving that you are authorized to receive a certificate for our domain, but that is a problem that will be specific to the TLS cert provider, and we can collaborate there.    

___

I'm also happy to set up a call sometime next week where we can discuss this issue. Do you have an email I can use?

**Comment by XBDRX** [comment]
Fantastic, thankyou. My email address is marc@bedrock.tv

If you contact me there initially, I'll add in the CTO and relevant team members. I will double check with LG if that list of roots is completely up to date.

**Comment by bazaah** [comment]
So, next steps are:

- [x] (us) Modify our cert management
- [x] (us) Create an endpoint in our dev environment using the ZeroSSL based cert
- [x] (you) Test against that endpoint
- [x] (us) Rollout to prod assuming no issues are detected

**Comment by bazaah** [comment]
So I've created a MVP endpoint that should unblock your testing. Note that there is more work needed on our side to automate cert renewal, but you can find a ZeroSSL cert at: `fr0ntierx.bridge.dev.walletconnect.org` right now.

E.g:

```zsh
curl -v https://fr0ntierx.bridge.dev.walletconnect.org/hello
* Server certificate:
*  subject: CN=fr0ntierx.bridge.dev.walletconnect.org
*  start date: Aug 17 00:00:00 2022 GMT
*  expire date: Nov 15 23:59:59 2022 GMT
*  subjectAltName: host "fr0ntierx.bridge.dev.walletconnect.org" matched cert's "fr0ntierx.bridge.dev.walletconnect.org"
*  issuer: C=AT; O=ZeroSSL; CN=ZeroSSL RSA Domain Secure Site CA
*  SSL certificate verify ok.

# snipped...
```

Set your bridge config to use the endpoint above

**Comment by XBDRX** [comment]
Thankyou!

An html redirect from the webOS device to https://fr0ntierx.bridge.dev.walletconnect.org/hello works fine

I've tried adding the bridge url to our config ie

```
export const _walletConnectProvider: WalletConnectProvider = new WalletConnectProvider({  
  rpc: RPC_URLS,
  qrcode: false,
  bridge:'https://fr0ntierx.bridge.dev.walletconnect.org'
});

```

but it looks like it's still using your regular load-balanced bridges eg wss://h.bridge.walletconnect.org

I've updated to the latest '@walletconnect/web3-provider' libs from npm and for build-config reasons, I import the UMD directly from "@walletconnect/web3-provider/dist/umd/index.min"

Is there additional config to perform on your side or does it look like the problem is our side?

**Comment by bazaah** [comment]
So, I've not really looked at the client side at all, but looking at where the bridge is set, [here](https://github.com/WalletConnect/walletconnect-monorepo/blob/1.8.0/packages/clients/core/src/index.ts#L133), and the associated function, [getBridgeUrl](https://github.com/WalletConnect/walletconnect-monorepo/blob/1.8.0/packages/clients/core/src/url.ts#L36) it appears clients force an alphanumeric bridge is selected.

Now, I'm not the right person to ask as to why this is the case. IRRC it was to alleviate load in the early days. We have two ways to handle this

1. Open an issue with the JS team and see if they're happy with making this routing optional
2. Create a patch using [patch-package](https://github.com/ds300/patch-package)

I'd recommend the latter, as it seems faster for the moment, and the patch is relatively simple, just delete [the random bridge bit](https://github.com/WalletConnect/walletconnect-monorepo/blob/1.8.0/packages/clients/core/src/url.ts#L37-L39)

**Comment by XBDRX** [comment]
Thanks. We've patched as described and it works.

**Comment by bazaah** [comment]
Great! If you're happy with that, then I'll get the work required to make this permanent into my queue, and keep you apprised on when we're ready to roll out to prod.

**Comment by bazaah** [comment]
As an update: I've just finished the feature work required for this in `dev`. I still need to do:

- some testing
- write up the documentation about the special casing that occurred out of this request
- merge the feature 
- get the changes out into `prod`

But the hardest bit is likely done now. I'm hopeful that this will land sometime next week.

**Comment by bazaah** [comment]
After the above happens, you'll need to modify your `bridge` url to `https://fr0ntierx.bridge.walletconnect.org` --assuming you're happy with that prefix.

I'll contact you when our end is ready

**Comment by bazaah** [comment]
@XBDRX -- the production endpoint is now live! You can find it at `fr0ntierx.bridge.walletconnect.org`.

I'll leave this issue open for the moment, in case something comes up.

Also as a side note, the `dev.` bridge certificate will expire in approx. 3 months, and will not be renewed.

**Comment by XBDRX** [comment]
Excellent, thank you all very much!
