### ISSUE TITLE
Doesn't include bufferutil or utf-8-validate when importing ws

### ISSUE THREAD

**Issue by johnnyshankman** [WalletConnect/walletconnect-monorepo#1291]
**Describe the bug**
This uses `ws` but does not properly define `bufferutil` and `utf-8-validate` as optional packages. They end up becoming peer dependencies and give me issues like this:

```
 warning  in ./node_modules/@manifoldxyz/manifold-connect-widgets/node_modules/ws/lib/buffer-util.js

Module not found: Error: Can't resolve 'bufferutil' in '/Users/johnshankman/Documents/manifoldxyz/manifold-studio-client-v2/node_modules/@manifoldxyz/manifold-connect-widgets/node_modules/ws/lib'

 warning  in ./node_modules/@manifoldxyz/manifold-connect-widgets/node_modules/ws/lib/validation.js

Module not found: Error: Can't resolve 'utf-8-validate' in '/Users/johnshankman/Documents/manifoldxyz/manifold-studio-client-v2/node_modules/@manifoldxyz/manifold-connect-widgets/node_modules/ws/lib'
```

When I blame who is using ws incorrectly it is this package
```
info Has been hoisted to "ws"
info Reasons this module exists
   - Hoisted from "@walletconnect#web3-provider#web3-provider-engine#ws"
```

**SDK Version (if relevant)**
 - Client: JS
 - Version "@walletconnect/web3-provider@^1.7.0"

**To Reproduce**
1. Use package in a library
2. Package up library for usage via npm
3. Find that it returns this warning in most webpack-type environments

**Expected behavior**
Both packages are defined as optional, or packaged in with this repo. That way I dont get warnings because the package isn't expected to be there, or it is compiled and included.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Node/Chrome

**Comment by finessevanes** [comment]
Is this still an issue?

**Comment by lorenzorzd** [comment]
I'm still having this issue, any workarounds?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
