### ISSUE TITLE
doesn't work for React Native 

### ISSUE THREAD

**Issue by kdong007** [WalletConnect/walletconnect-monorepo#1297]
**Describe the bug**
Im following this doc, but I got two issues:
1. typing with `asyncStorage`
```Type 'AsyncStorageStatic' is missing the following properties from type 'IAsyncStorage<string, any>': store, size, getStorets(2739)```
2. Crypo not found.
```Unable to resolve module crypto from /Users/kdong007/Desktop/projects/openhi-native-app/node_modules/@walletconnect/randombytes/dist/cjs/node/index.js: crypto could not be found within the project or in these directories:
  node_modules
  ../node_modules
   5 | Object.defineProperty(exports, "__esModule", { value: true });
   6 | exports.randomBytes = void 0;
>  7 | const crypto_1 = __importDefault(require("crypto"));
     |                                           ^
   8 | const encoding_1 = require("@walletconnect/encoding");
   9 | function randomBytes(length) {
  10 |     const buf = crypto_1.default.randomBytes(length);
```

**SDK Version (if relevant)**
 - Client: TS+RN+Expo
 - Version 
"@walletconnect/react-native-dapp": "^1.7.8",
"@react-native-async-storage/async-storage": "^1.17.7",

**To Reproduce**
1. expo RN project
2. follow the doc

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chezhe** [comment]
You need `rn-nodeify` to hack it, react-native environment doesn't contain crypto module which belongs to nodejs.

**Comment by gulsher7** [comment]
> **Describe the bug** Im following this doc, but I got two issues:
> 
> 1. typing with `asyncStorage`
>    `Type 'AsyncStorageStatic' is missing the following properties from type 'IAsyncStorage<string, any>': store, size, getStorets(2739)`
> 2. Crypo not found.
> 
> ```
>   node_modules
>   ../node_modules
>    5 | Object.defineProperty(exports, "__esModule", { value: true });
>    6 | exports.randomBytes = void 0;
> >  7 | const crypto_1 = __importDefault(require("crypto"));
>      |                                           ^
>    8 | const encoding_1 = require("@walletconnect/encoding");
>    9 | function randomBytes(length) {
>   10 |     const buf = crypto_1.default.randomBytes(length);
> ```
> 
> **SDK Version (if relevant)**
> 
> * Client: TS+RN+Expo
> * Version
>   "@walletconnect/react-native-dapp": "^1.7.8",
>   "@react-native-async-storage/async-storage": "^1.17.7",
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. expo RN project
> 2. follow the doc
> 
> **Expected behavior**
> 
> **Screenshots**
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

how did you resolve it ? i'm facing same issue

**Comment by elliotsayes** [comment]
> You need `rn-nodeify` to hack it, react-native environment doesn't contain crypto module which belongs to nodejs.

This fixes problem 2, but not problem 1. `rn-nodeify` does not fix the compatibility between `IAsyncStorage` (from `keyvaluestorage`) and `AsyncStorageStatic` from `@react-native-async-storage/async-storage`.

Related issue: https://github.com/react-native-async-storage/async-storage/issues/745

**Comment by elliotsayes** [comment]
> You need `rn-nodeify` to hack it, react-native environment doesn't contain crypto module which belongs to nodejs.

This fixes problem 2, but not problem 1. `rn-nodeify` does not fix the compatibility between `IAsyncStorage` (from `keyvaluestorage`) and `AsyncStorageStatic` from `@react-native-async-storage/async-storage`.

Related issue: https://github.com/react-native-async-storage/async-storage/issues/745
Edit, another: https://github.com/pedrouid/keyvaluestorage/issues/2
