### ISSUE TITLE
outdated react-native-svg causing varies issues

### ISSUE THREAD

**Issue by kdong007** [WalletConnect/walletconnect-monorepo#1301]
**Describe the bug**
the `react-native-svg` dependency is way too outdated. When I use other versions of `react-native-svg`, it give me `tried to register two views with the same name RNSVGSvgView`. If I use the old version as this repo is using, it gives me `requiredNativeComponent: "RNSVGPath" was not found in the UIManager`

**SDK Version (if relevant)**
 - Client: React Native 

**To Reproduce**

**Expected behavior**
Things to be working

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LauColombini** [comment]
@kdong007 How did you solve it?

**Comment by kiran-bhalerao** [comment]
hey @kdong007 @LauColombini how do i fix this issue?

**Comment by EmmanuelSkapple** [comment]
@kdong007 how could you solve?

**Comment by LauColombini** [comment]
@kiran-bhalerao @EmmanuelSkapple Sorry I didn't see the message, [I was able to solve it like this](https://github.com/WalletConnect/walletconnect-monorepo/issues/595#issuecomment-1362077222)
