### ISSUE TITLE
Expo app crashes on Android with error: no identifiers allowed after numeric literal

### ISSUE THREAD

**Issue by thevirinchi** [WalletConnect/walletconnect-monorepo#1306]
**Describe the bug**
Expo application crashes on Android only. And does not return any stack.
![WhatsApp Image 2022-08-01 at 7 18 39 PM](https://user-images.githubusercontent.com/35911796/182162548-a62a032a-27a3-4ae0-97f1-4b0ea415474f.jpeg)

**SDK Version (if relevant)**
 - Client: Expo
 - Version ~45.0.0

**To Reproduce**
1. Create Expo app with expo version ~45.0.0
2. Install @walletconnect/react-native-dapp
3. Run on Android
4. App crashes

**Expected behavior**
App should run as it does in iOS.

**Screenshots**
![WhatsApp Image 2022-08-01 at 7 18 39 PM](https://user-images.githubusercontent.com/35911796/182162548-a62a032a-27a3-4ae0-97f1-4b0ea415474f.jpeg)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser NA
 - Version 12.4 (21F79)

**Smartphone (please complete the following information):**
 - Device: OnePlus A5000
 - OS: Android
 - Browser NA
 - Version Android 10

**Comment by truongngodang** [comment]
same bug

**Comment by daniiba** [comment]
Same bug. 
Any solutions?

**Comment by markcutajar** [comment]
Have encountered the same bug too

**Comment by andrei0x309** [comment]
The issue stems from how you `nodify` the expo app, so it comes from node dependencies:
In order to fix this use this lib: `expo-crypto-polyfills` 

and this metro config:

```javascript
const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);
config.resolver.extraNodeModules = require('expo-crypto-polyfills');

module.exports = config;
```

and delete the rest of the polyfill packages 

It should solve it.
