### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): Error: Secure random number generation is not supported by this browser. Use Chrome, Firefox or Internet Explorer 11 while calling connector.connect()

### ISSUE THREAD

**Issue by FaridMicrocis** [WalletConnect/walletconnect-monorepo#1311]
**Describe the bug**
I got the above error while calling connector.connect() method of useWalletconnect hook. inside React Native app.

**SDK Version (if relevant)**
 I use react-native version 0.69.3

**Comment by billyjacoby** [comment]
Also getting this issue, any word on a fix or workaround?

**Comment by chadyj** [comment]
Please use the bug template and include full information such as WalletConnect SDK version used and other details.

**Comment by finessevanes** [comment]
Is this still an issue?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)

**Comment by CHYGO1985** [comment]
It is Mar 12, 2024, I am still having the issue in a React Native Project

**Comment by glitch-txs** [comment]
@CHYGO1985 feel free to open an new issue here or in the React Native repo
