### ISSUE TITLE
Perform EIP-712 typed data checks

### ISSUE THREAD

**Issue by pedrouid** [WalletConnect/walletconnect-monorepo#133]
Implement `eth_signTypedData` from [EIP-712](https://eips.ethereum.org/EIPS/eip-712) latest spec

Currently the SDK allows for arbitrary parameters. We should use uport's `eth-typed-data` library to parse and format the typed data parameters correctly before sending to the wallet.

**eth-typed-data:** https://www.npmjs.com/package/eth-typed-data

**Comment by BrendanChou** [comment]
Please make sure to also support arrays which are in the latest spec of EIP-712

**Comment by pedrouid** [comment]
Will do. This has been pending for a while. Could you drop the link for the latest spec?

**Comment by BrendanChou** [comment]
It appears as though eth-typed-data does account for arrays, but I was concerned since many RPC providers do not.

From the spec:
> The array values are encoded as the keccak256 hash of the concatenated encodeData of their contents (i.e. the encoding of SomeType[5] is identical to that of a struct containing five members of type SomeType).

**Comment by davekay100** [comment]
@BrendanChou  have you ever got EIP 712 to work with wallet connect? I am trying to get it to work but I am getting an error that I can't identify

**Comment by BrendanChou** [comment]
Every wallet implements it differently so it's pretty annoying, but this might help:
https://github.com/dydxprotocol/solo/blob/d4a984499851adf1e8ab21f9408892aa8bc5fd63/src/modules/Signer.ts#L44

**Comment by davekay100** [comment]
Thanks! This is awesome
