### ISSUE TITLE
Using react-native-dapp with web3-provider

### ISSUE THREAD

**Issue by elliotsayes** [WalletConnect/walletconnect-monorepo#1337]
**Describe the bug**
Using the connector from `react-native-dapp` in `web3-provider`, for use in `ethers.providers` results in errors.

If you follow the method from: https://stackoverflow.com/a/71115091
```js
    const provider = new WalletConnectProvider({
      rpc: {
        137: "https://polygon-rpc.com",
      },
      chainId: 137,
      connector: connector,
      qrcode: false,
    });
    const result = await provider.enable();
    const ethersProvider = new ethers.providers.Web3Provider(provider);
```
Then several wallet apps reject it, e.g. Trust Wallet and Rainbow Wallet:
<img width="300" src="https://user-images.githubusercontent.com/7699058/183564441-cbfc351e-52d3-4074-a3e0-b45a338fc502.PNG"> <img width="300" src="https://user-images.githubusercontent.com/7699058/183564451-c2a41e2e-c7fc-4436-a952-649ac9793e18.PNG">
(Metamask simply does not respond)

If you replace the call to `provider.enable` with an initial `connector.connect`:
```js
    const session = await connector.connect();
    const provider = new WalletConnectProvider({
      rpc: {
        137: "https://polygon-rpc.com",
      },
      chainId: 137,
      connector: connector,
      qrcode: false,
    });
    // const result = await provider.enable();
    const ethersProvider = new ethers.providers.Web3Provider(provider);
```
Then then connecting to the wallets works. However, I instead get an error in `ethers.providers.Web3Provider`:

`Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not an object (evaluating 'new _ethers.default.providers')`

If you use both `connector.connect` and `provider.enable`, you just get the same errors from the wallet apps when executing `provider.enable`.

**SDK Version (if relevant)**
 - Client: react-native
 - Version 0.69.3

**To Reproduce**
1. Run above code in react-native app.

**Expected behavior**
Wallet-connect pairs with wallet, lets `ethers` construct `Web3Provider`.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser N/A
 - Version 12.5

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: 15.6
 - Browser N/A
 - Version N/A

**Additional context**
N/A

**Comment by elliotsayes** [comment]
I managed to get this working with the second method, calling `connector.connect` instead of `provider.enable`:

```js
const session = await connector.connect();
const provider = new WalletConnectProvider({
  rpc: {
    137: "https://polygon-rpc.com",
  },
  chainId: 137,
  connector: connector,
  qrcode: false,
});
const ethersProvider = new ethers.providers.Web3Provider(provider);
```
This should probably be documented somewhere.

My earlier issue is that I imported ethers like:
`import ethers from 'ethers';`
instead of:
`import { ethers } from 'ethers';`

**Comment by KrishEnacton** [comment]
for this , do we already have metamask installed in phone?

**Comment by adurhmn** [comment]
@elliotsayes can you share the working project code of @walletconnect/react-native-dapp & @walletconnect/web3-provider integration? I cannot find that anywhere. It would be easy to understand if I got the entire project setup code.
