### ISSUE TITLE
I created a SWFT DAPP on walletconnect and it is still under review. It's been more than two months, please check it, thank you very much.

### ISSUE THREAD

**Issue by Arnelhub111** [WalletConnect/walletconnect-monorepo#1340]
I created a SWFT DAPP on walletconnect and it is still under review. It's been more than two months, please check it, thank you very much.

_Originally posted by @LGYang in https://github.com/WalletConnect/walletconnect-monorepo/discussions/1335_

**Comment by finessevanes** [comment]
Hey, we have 3 different projects with the SWFT name. Can you provide the UID for the project?

**Comment by bkrem** [comment]
Closing. Looks like relevant submissions were reviewed and changes requested but not resubmitted for review since.
