### ISSUE TITLE
doesn't work for React Native Web

### ISSUE THREAD

**Issue by tuonght93** [WalletConnect/walletconnect-monorepo#1342]
**Describe the bug**
Cannot build on web:
WARNING in ./node_modules/react-native-gesture-handler/lib/module/handlers/gestures/reanimatedWrapper.js 5:15-49
Module not found: Error: Can't resolve 'react-native-reanimated' in '/node_modules/react-native-gesture-handler/lib/module/handlers/gestures'
 @ ./node_modules/react-native-gesture-handler/lib/module/handlers/gestures/GestureDetector.js 5:0-49 295:7-17 302:34-59 304:26-51 363:16-35 487:46-56 487:69-79 487:125-143
 @ ./node_modules/react-native-gesture-handler/lib/module/index.js 14:0-70 14:0-70
 @ ./src/main/Navigation.tsx 1:1659-1706
 @ ./App.web.tsx 1:473-505
 @ ./index.web.js 1:240-256

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

ERROR in ./node_modules/@walletconnect/react-native-dapp/dist/providers/WalletConnectProvider.js 1:0-50
Module not found: Error: Can't resolve '@walletconnect/client' in '/node_modules/@walletconnect/react-native-dapp/dist/providers'
 @ ./node_modules/@walletconnect/react-native-dapp/dist/providers/index.js 1:0-75 1:0-75
 @ ./node_modules/@walletconnect/react-native-dapp/dist/index.js 7:0-63 7:0-63
 @ ./src/main/Navigation.tsx 1:1279-1311
 @ ./App.web.tsx 1:473-505
 @ ./index.web.js 1:240-256

ERROR in ./node_modules/@walletconnect/react-native-dapp/dist/providers/WalletConnectProvider.js 3:0-50
Module not found: Error: Can't resolve 'keyvaluestorage' in '/node_modules/@walletconnect/react-native-dapp/dist/providers'
 @ ./node_modules/@walletconnect/react-native-dapp/dist/providers/index.js 1:0-75 1:0-75
 @ ./node_modules/@walletconnect/react-native-dapp/dist/index.js 7:0-63 7:0-63
 @ ./src/main/Navigation.tsx 1:1279-1311
 @ ./App.web.tsx 1:473-505
 @ ./index.web.js 1:240-256

ERROR in ./node_modules/react-native-gesture-handler/lib/module/components/DrawerLayout.js 12:0-34
Module not found: Error: Can't resolve 'invariant' in '/node_modules/react-native-gesture-handler/lib/module/components'
 @ ./node_modules/react-native-gesture-handler/lib/module/index.js 21:0-68 21:0-68
 @ ./src/main/Navigation.tsx 1:1659-1706
 @ ./App.web.tsx 1:473-505
 @ ./index.web.js 1:240-256

ERROR in ./node_modules/react-native-qrcode-svg/src/index.js 29:4
Module parse failed: Unexpected token (29:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|   return (
>     <G x={logoPosition} y={logoPosition}>
|       <Defs>
|         <ClipPath id='clip-logo-background'>
 @ ./node_modules/react-native-qrcode-svg/index.js 1:0-40 1:0-40
 @ ./node_modules/@walletconnect/react-native-dapp/dist/components/Qrcode.js 3:0-41 19:172-174
 @ ./node_modules/@walletconnect/react-native-dapp/dist/components/index.js 1:0-45 1:0-45
 @ ./node_modules/@walletconnect/react-native-dapp/dist/index.js 1:0-29 1:0-29
 @ ./src/screens/DemoScreen.tsx 1:1784-1827
 @ ./src/main/Navigation.tsx 1:1279-1311
 @ ./App.web.tsx 1:473-505
 @ ./index.web.js 1:240-256

ERROR in ./node_modules/react-native-reanimated-carousel/lib/commonjs/Carousel.js 1:360-394
Module not found: Error: Can't resolve 'react-native-reanimated' in '//node_modules/react-native-reanimated-carousel/lib/commonjs'
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/index.js 1:200-221
 @ ./src/main/Navigation.tsx 1:1659-1706
 @ ./App.web.tsx 1:473-505
 @ ./index.web.js 1:240-256

ERROR in ./node_modules/react-native-reanimated-carousel/lib/commonjs/ScrollViewGesture.js 1:468-502
Module not found: Error: Can't resolve 'react-native-reanimated' in 'node_modules/react-native-reanimated-carousel/lib/commonjs'
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/Carousel.js 1:604-634
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/index.js 1:200-221
 @ ./src/main/Navigation.tsx 1:1659-1706
 @ ./App.web.tsx 1:473-505
 @ ./index.web.js 1:240-256

ERROR in ./node_modules/react-native-reanimated-carousel/lib/commonjs/constants/index.js 1:126-160
Module not found: Error: Can't resolve 'react-native-reanimated' in '/node_modules/react-native-reanimated-carousel/lib/commonjs/constants'
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/hooks/useCarouselController.js 1:177-200
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/Carousel.js 1:423-463
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/index.js 1:200-221
 @ ./src/main/Navigation.tsx 1:1659-1706
 @ ./App.web.tsx 1:473-505
 @ ./index.web.js 1:240-256

ERROR in ./node_modules/react-native-reanimated-carousel/lib/commonjs/hooks/useCarouselController.js 1:228-262
Module not found: Error: Can't resolve 'react-native-reanimated' in '/node_modules/react-native-reanimated-carousel/lib/commonjs/hooks'
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/Carousel.js 1:423-463
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/index.js 1:200-221
 @ ./src/main/Navigation.tsx 1:1659-1706
 @ ./App.web.tsx 1:473-505
 @ ./index.web.js 1:240-256

ERROR in ./node_modules/react-native-reanimated-carousel/lib/commonjs/hooks/useCommonVariables.js 1:265-299
Module not found: Error: Can't resolve 'react-native-reanimated' in '/node_modules/react-native-reanimated-carousel/lib/commonjs/hooks'
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/Carousel.js 1:942-979
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/index.js 1:200-221
 @ ./src/main/Navigation.tsx 1:1659-1706
 @ ./App.web.tsx 1:473-505
 @ ./index.web.js 1:240-256

ERROR in ./node_modules/react-native-reanimated-carousel/lib/commonjs/hooks/useOffsetX.js 1:110-144
Module not found: Error: Can't resolve 'react-native-reanimated' in '/node_modules/react-native-reanimated-carousel/lib/commonjs/hooks'
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/layouts/BaseLayout.js 1:564-594
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/Carousel.js 1:750-781
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/index.js 1:200-221
 @ ./src/main/Navigation.tsx 1:1659-1706
 @ ./App.web.tsx 1:473-505
 @ ./index.web.js 1:240-256

ERROR in ./node_modules/react-native-reanimated-carousel/lib/commonjs/hooks/useOnProgressChange.js 1:132-166
Module not found: Error: Can't resolve 'react-native-reanimated' in '/node_modules/react-native-reanimated-carousel/lib/commonjs/hooks'
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/Carousel.js 1:1005-1043
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/index.js 1:200-221
 @ ./src/main/Navigation.tsx 1:1659-1706
 @ ./App.web.tsx 1:473-505
 @ ./index.web.js 1:240-256

ERROR in ./node_modules/react-native-reanimated-carousel/lib/commonjs/hooks/useVisibleRanges.js 1:126-160
Module not found: Error: Can't resolve 'react-native-reanimated' in '/node_modules/react-native-reanimated-carousel/lib/commonjs/hooks'
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/Carousel.js 1:657-692
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/index.js 1:200-221
 @ ./src/main/Navigation.tsx 1:1659-1706
 @ ./App.web.tsx 1:473-505
 @ ./index.web.js 1:240-256

ERROR in ./node_modules/react-native-reanimated-carousel/lib/commonjs/layouts/BaseLayout.js 1:455-489
Module not found: Error: Can't resolve 'react-native-reanimated' in '/node_modules/react-native-reanimated-carousel/lib/commonjs/layouts'
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/Carousel.js 1:750-781
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/index.js 1:200-221
 @ ./src/main/Navigation.tsx 1:1659-1706
 @ ./App.web.tsx 1:473-505
 @ ./index.web.js 1:240-256

ERROR in ./node_modules/react-native-reanimated-carousel/lib/commonjs/layouts/normal.js 1:118-152
Module not found: Error: Can't resolve 'react-native-reanimated' in '/node_modules/react-native-reanimated-carousel/lib/commonjs/layouts'
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/layouts/index.js 1:92-111
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/hooks/useLayoutConfig.js 1:245-266
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/Carousel.js 1:803-837
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/index.js 1:200-221
 @ ./src/main/Navigation.tsx 1:1659-1706
 @ ./App.web.tsx 1:473-505
 @ ./index.web.js 1:240-256

ERROR in ./node_modules/react-native-reanimated-carousel/lib/commonjs/layouts/parallax.js 1:122-156
Module not found: Error: Can't resolve 'react-native-reanimated' in '/node_modules/react-native-reanimated-carousel/lib/commonjs/layouts'
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/layouts/index.js 1:126-147
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/hooks/useLayoutConfig.js 1:245-266
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/Carousel.js 1:803-837
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/index.js 1:200-221
 @ ./src/main/Navigation.tsx 1:1659-1706
 @ ./App.web.tsx 1:473-505
 @ ./index.web.js 1:240-256

ERROR in ./node_modules/react-native-reanimated-carousel/lib/commonjs/layouts/stack.js 1:488-522
Module not found: Error: Can't resolve 'react-native-reanimated' in '/node_modules/react-native-reanimated-carousel/lib/commonjs/layouts'
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/layouts/index.js 1:159-177
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/hooks/useLayoutConfig.js 1:245-266
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/Carousel.js 1:803-837
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/index.js 1:200-221
 @ ./src/main/Navigation.tsx 1:1659-1706
 @ ./App.web.tsx 1:473-505
 @ ./index.web.js 1:240-256

ERROR in ./node_modules/react-native-reanimated-carousel/lib/commonjs/utils/dealWithAnimation.js 1:117-151
Module not found: Error: Can't resolve 'react-native-reanimated' in '/node_modules/react-native-reanimated-carousel/lib/commonjs/utils'
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/hooks/useCarouselController.js 1:286-323
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/Carousel.js 1:423-463
 @ ./node_modules/react-native-reanimated-carousel/lib/commonjs/index.js 1:200-221
 @ ./src/main/Navigation.tsx 1:1659-1706
 @ ./App.web.tsx 1:473-505
 @ ./index.web.js 1:240-256

ERROR in ./node_modules/styled-components/native/dist/styled-components.native.esm.js 7:0-43
Module not found: Error: Can't resolve 'supports-color' in '/node_modules/styled-components/native/dist'
 @ ./src/main/Navigation.tsx 1:473-516
 @ ./App.web.tsx 1:473-505
 @ ./index.web.js 1:240-256

17 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.73.0 compiled with 18 errors and 1 warning in 360 ms

**SDK Version (if relevant)**
 - Client: TS+RN-CLI
 - Version
  "@walletconnect/react-native-dapp": "^1.8.0",

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by finessevanes** [comment]
@tuonght93 have you tried the latest RN version? https://docs.walletconnect.com/2.0/javascript/guides/react-native

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
