### ISSUE TITLE
Module parse failed: @walletconnect/sign-client

### ISSUE THREAD

**Issue by mrosendin** [WalletConnect/walletconnect-monorepo#1349]
**Description**

I get this error when I `yarn start` my react project

```
./node_modules/@walletconnect/sign-client/dist/index.es.js 317:19
Module parse failed: Unexpected token (317:19)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|             w = {
|         requiredNamespaces: s,
>         relays: r ?? [{
|           protocol: W
|         }],
```

 **@walletconnect/sign-client** version `2.0.0.rc2`

**Comment by xzilja** [comment]
@mrosendin by default we export commonjs version of sdk as you can see here https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/sign-client/package.json#L8-L10 it looks like your project is set up with es module support so you are importing .es file, but it doesn't support something from there, maybe that nullish coalescing `??` operator? 

Hard to tell atm, is this project open sourced so I could have a look?

**Comment by mrosendin** [comment]
Hi @IljaDaderko thank you for your response. The project is private unfortunately but I was able to solve the problem using this SO answer: https://stackoverflow.com/a/67543975/4198841

A few other details: the project is using ESNext which includes support for the nullish coalescing operator, so as the SO answer suggests, it's due to a Babel transpilation issue for the targeted browsers in `package.json`.

**Comment by bradleySuira** [comment]
Hi all found the same issue when was trying to add WC to our project 
<img width="725" alt="Screen Shot 2022-11-20 at 9 59 12 PM" src="https://user-images.githubusercontent.com/1889891/202960240-4168dee4-ebf4-4ed3-b260-452d1c29ef72.png">

it's a Vuejs project so at the end I had to put this in the custom web pack config (`chainWebpack` inside `vue.config.js`)
```
config.module
      .rule('walletConnect')
      .test(/node_modules[\\/]@walletconnect/)
      .use('babel-loader')
      .loader('babel-loader')
```

**Comment by xzilja** [comment]
@bradleySuira Make sure your babel loader is up to date and in fact correct version of it is installed in node_modules (i.e. there is no conflict with older ones).

**Comment by asimaranov** [comment]
The same problem while importing universal provider 
```
./node_modules/@walletconnect/universal-provider/dist/index.es.js 296:97
Module parse failed: Unexpected token (296:97)
You may need an appropriate loader to handle this file type.
|     _classCallCheck(this, a);
| 
>     this.events = new y(), this.rpcProviders = {}, this.providerOpts = t, this.logger = typeof t?.logger < "u" && typeof t?.logger != "string" ? t.logger : v(g({
|       level: t?.logger || h
|     }));
```

**Comment by joesdk99** [comment]
Same problem here! I need to build @walletconnect\sign-client for a chrome web extension and import it in the background.js. But I'm getting this error
`\node_modules\@walletconnect\sign-client\node_modules\@walletconnect\core\dist\index.es.js: Unexpected token: punc (.)`

**Comment by bradleySuira** [comment]
I think that is the same issue @asimaranov  @joesdk99 In my case I updated the web pack settings you should check in your web pack config and specify that the wallet-connect package should be loaded by babel-loader

**Comment by ColligenceLabs** [comment]
I fixed the similar issue via webpack ejecting from my React project and add 2 babel plugins.
Refer: #1973 

Anyway it can be solved but I don't prefer it.

**Comment by steven2308** [comment]
Inspired on @bradleySuira 's answer (which wasn't so clear for me :sweat_smile: ) I ended up with this in vue.config.js (Vue v2.6.11), and it finally solved it:
```
module.exports = {
    configureWebpack: {
        module: {
            rules: [{ test: /node_modules[\\/]@walletconnect/, loader: 'babel-loader' }],
        }
    }
  }
 
  ```

**Comment by tlacloc** [comment]
I tried something similar but got the this error
```
You may need an additional loader to handle the result of these loaders.
|           requiredNamespaces: i,
|           optionalNamespaces: n,
>           relays: o ?? [{
|             protocol: le
|           }],
```
I'm using nuxt, the build part on the nuxt.config is similar as

```
config.module.rules.push({
  test: /node_modules[\\/]@walletconnect/,
  loader: 'babel-loader'
})
```

**Comment by xzilja** [comment]
@tlacloc your babel setup needs this https://babeljs.io/docs/babel-plugin-transform-nullish-coalescing-operator or to be updated to latest version of babel.
