### ISSUE TITLE
Unable to connect Trust Wallet to Web3 on bscscan using WalletConnet

### ISSUE THREAD

**Issue by TSCRIBBANS** [WalletConnect/walletconnect-monorepo#1351]
I am trying to connect my trust wallet (TW) to Web3 to write a contact at this address: [https://bscscan.com/address/0x932c5e1709a6895bc455e799b03f43d3a8ffbd9a#writeContract](url)

1. open the address above and go to "write contract". Steps 1-4 on Laptop
2. click on "connect to web3"
3. a new screen prompts me to connect to MM or wallet connect. 
4. select wallet connect (QR code now visible).      
5. Open TW, go to settings. Under Wallet connect, select, "new connection".   Steps 5-7 on Android device.
6. Scan the QR code.
7.  When I scan, TW says, this may take a few seconds, and then no new connection is made.

I need to emergency withdrawal funds from a contract and this is the only way that I can do it. Once I can add the connection to my TW then I can repeat these steps via the dApp browser in trust wallet. This will allow me to emergency withdrawal the funds. 

I have already reached out to TW and they said there is nothing they can do that I need to contact wallet connect. 

Thanks!

**SDK Version (if relevant)**
 - Client: Koodo/Android
 - Version: 12

**To Reproduce**
1. see above

**Expected behavior**
described above

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser: Safari
 - Version: 15.6

**Smartphone (please complete the following information):**
 - Device: S21
 - OS: 4.1
 - Browser: google
 - Version: 13.31.14.26.arm64

**Additional context**

**Comment by yarosh01** [comment]
@TSCRIBBANS hi, did you manage to solve the problem? I just have the same

**Comment by finessevanes** [comment]
@TSCRIBBANS @yarosh01 hey, are you all using v1 or v2?

**Comment by sathungo** [comment]
i want to cancel bscan api

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version  :)
