### ISSUE TITLE
Types error "Could not find a declaration file for module 'pino'"

### ISSUE THREAD

**Issue by BenRacicot** [WalletConnect/walletconnect-monorepo#1352]
**Describe the bug**
A typings error after installing the WalletConnect types file into my app.

**SDK Version (if relevant)**
"@walletconnect/sign-client": "^2.0.0-rc.2",
"@walletconnect/types": "^2.0.0-rc.2",

**To Reproduce**
To reproduce the behavior follow the instructions on https://docs.walletconnect.com/2.0/javascript/sign/installation
1. Create a new application 
2. Install the packages above
3. Initialize the startup code from the installation page
4. See error in terminal

```
Error: node_modules/@walletconnect/types/dist/types/sign-client/expirer.d.ts:1:24 - error TS7016: Could not find a declaration file for module 'pino'. '/Users/bracicot/dev/wallethack/node_modules/pino/pino.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/pino` if it exists or add a new declaration (.d.ts) file containing `declare module 'pino';`

1 import { Logger } from "pino";
```
Installing Pino in my app does not solve the WalletConnect types error. `"@types/pino": "^7.0.5",`

Also, it is likely beneficial to mention that the mentioned package `npm install --save @walletconnect/jsonrpc-types@rc` does not exist on NPM.

**Expected behavior**
No show-stoppers during WC installation into a web app.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 104

**Additional context**
Please let me know how to best lend a hand.
I'd be willing to create a boilerplate Angular application for WalletConnect if someone would guide me.
Looking forward to V2 :)

**Comment by BenRacicot** [comment]
Started from scratch this am and reinstalling Pino fixed it. Please close and thank you.

**Comment by smelnikov** [comment]
This problem is still relevant.

Is there any reason why sign-client uses the version pino@6.7.0? 
As of version 7, their bundle includes type declarations.
