### ISSUE TITLE
I like to add a chain to the list of supported chains. What would be the procedure for that?

### ISSUE THREAD

**Issue by nomanaliakram321** [WalletConnect/walletconnect-monorepo#1356]
I like to add a chain to the list of supported chains. What would be the procedure for that?

**Comment by edmcnierney** [comment]
I would like to do this, too. I can't find any info in the docs or 2.0 code (and therefore may be looking in the wrong place).

**Comment by finessevanes** [comment]
@nomanaliakram321 @edmcnierney Please view: https://docs.walletconnect.com/2.0/advanced/multichain/overview#register-chain-with-the-explorer
