### ISSUE TITLE
Cannot connect any dapp to react wallet demo

### ISSUE THREAD

**Issue by markibanez** [WalletConnect/walletconnect-monorepo#1357]
### Bug Description
There is an error when attempting to connect any dapp to the react wallet demo. Either when clicking the connect button or scanning a QR code, there is an alert popup that always shows the error message "Error: Relay Protocol not supported: undefined". This error happens in both live demo site and local dev environment.

### Steps to reproduce the behavior in live demo site:
1. Open browser and navigate to https://react-wallet.walletconnect.com/
2. Click on the WalletConnect button (center icon in the bottom toolbar)
3. Paste a WalletConnect URI and click the connect button OR scan a WalletConnect QR code
4. Error modal will show up (see screenshot below)

### Steps to reproduce the behavior in local development environment:
1. Clone repo https://github.com/WalletConnect/web-examples.git
2. Open terminal and navigate to path `[cloned-repo-directory]/wallets/react-wallet-v2`
3. Run `yarn install` command
4. After everything is installed, run `npm run dev` command
5. Open browser and navigate to http://localhost:3001/
6. Click on the WalletConnect button (center icon in the bottom toolbar)
7. Paste a WalletConnect URI and click the connect button OR scan a WalletConnect QR code
8. Error modal will show up (see screenshot below)

### Expected Behavior
Demo wallet is connected to and interacting with dapp

### Screenshots
![image](https://user-images.githubusercontent.com/7534847/185258095-9692b35e-1c18-44b0-8eed-ed7abbd46b89.png)

### Desktop
 - OS: Windows 11
 - Browser: Chrome
 - Version: 104.0.5112.81

### Smart Phone
 - Device: Redmi K40 Pro
 - OS: Android 12
 - Browser: Chrome
 - Version: 104.0.5112.69

**Comment by chadyj** [comment]
Thank you for the detailed bug report.

The wallet you are using is a v2 wallet, and is only compatible with v2 dapps.

What dapp are you using?
Does the dapp support v1 or v2?

**Comment by goingupHQ** [comment]
Thanks for your reply @chadyj 

I tried it with opensea and various dapps that we developed using web3modal, so I presume those use v1. What's interesting is that the wallet also shows the same error when trying to connect with the v2 demo dapps. 

Below are the steps to reproduce:

1. Navigate browser to https://react-dapp-v2-with-ethers.vercel.app/ (this demo is also in the same repo as the demo wallet)
2. Click on one of the blockchain buttons (e.g. Ethereum)
3. Click on "Copy To Clipboard" below the QR code that appears
4. Open a new tab and navigate to https://react-wallet.walletconnect.com/walletconnect
5. Paste WalletConnect uri in the uri text box
6. Click connect button
7. Same error appears

Appreciate it if we could definitively chalk this up to version compatibility so I can move on with another solution.

**Comment by chadyj** [comment]
<img width="416" alt="Screenshot 2022-08-18 at 07 48 46" src="https://user-images.githubusercontent.com/116099/185303772-c73ad786-984f-4eb0-8dbc-4c54785a761a.png">

That dapp is an older version, and isn't compatible with the latest release candidates.

You can try a dapp that has been updated to RC here https://react-app.walletconnect.com/

**Comment by goingupHQ** [comment]
Got it! Before I close this , just want to confirm that v2 is not backwards compatible with v1 and there is no current workaround to make v2 wallets work with v1 dapps.

**Comment by chadyj** [comment]
Correct.
See https://docs.walletconnect.com/2.0/advanced/migrating-from-v1.0 for more info.
