### ISSUE TITLE
Wallet Connect connecting to Ledger Mobile does not emit a 'connect' event on initial approval of DApp 

### ISSUE THREAD

**Issue by Adamj1232** [WalletConnect/walletconnect-monorepo#1371]
**Describe the bug**
Wallet Connect connecting to Ledger Mobile does not emit a 'connect' event on initial approval of DApp 

**SDK Version (if relevant)**
`    "@walletconnect/client": "^1.7.1"`
`    "@walletconnect/qrcode-modal": "^1.7.1"`
 - Client: [JS]

**To Reproduce**
Open https://reactdemo.blocknative.com/ in mobile browser
Click "Select a wallet", choose wallet connect
Search for ledger, select it
Opens ledger live mobile app
Select Polygon account
Click “Connect”
Observe app connected (inside ledger mobile app)
Switch back to block native demo website
Observe wallet connect window still open
Click close wallet connect window
See web3 onboard modal says rejected
Close modal, disconnect ledger app from dapp (don’t close ledger live app)
Refresh blocknative demo web page
Repeat connection process
Observe app now connects

**Expected behavior**
A `connect` event is emitted on approval of DApp connection 

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS15.6.1
 - Browser firefox & chrome

**Additional context**
Connecting to other wallets emits the `connect` event as expected through WalletConnect.
Ledger will connect after initial approval of DApp and reconnect attempt, but does not properly emit on fir approval. 
Link to Blocknative WalletConnect package - https://github.com/blocknative/web3-onboard/blob/43940b8aceca29fb49a6dda5934f07c22b52067e/packages/walletconnect/src/index.ts#L128

**Comment by finessevanes** [comment]
V1 has been deprecated. Please view our migration docs for any questions. https://docs.walletconnect.com/2.0/advanced/migrating-from-v1.0

**Comment by Yojahuang** [comment]
So anyone that is still use v1 should just drop it?
