### ISSUE TITLE
I can't connect my Trust wallet to apps (IOS Device)

### ISSUE THREAD

**Issue by getspooky** [WalletConnect/walletconnect-monorepo#1379]
**Describe the bug**

I can't connect my Trust wallet to website (IOS Device).

> In Android it works as expected

Video :  https://www.dropbox.com/s/qglt0hfb3uxgnvy/RecordIt-85C5402D-0065-4E62-842C-9E82CA7B7E6F.mp4?dl=0

**SDK Version**
 - Client: JS
 - Version 1.6.6

**To Reproduce**
1. Go to any website that support wallet connect 
2. Click on Wallet Connect
4. After few minutes it return `Failed to Connected`

**Expected behavior**

Sign request

**Screenshots**

![IMG_2644](https://user-images.githubusercontent.com/37160072/186759439-00dd6326-eaa9-4279-abc3-5b81c6ba3276.jpeg)

**Desktop**
 - OS: IOS
 - Browser: Chrome, Safari , etc...

**Smartphone :**
 - Device: Phone12
 - Software Version: 15.5
 - Browser : Safari, Chrome , etc ;..

@pedrouid, @ganchoradkov

**Comment by finessevanes** [comment]
Please update to v2 as v1 has been deprecated. Please view migration docs: https://docs.walletconnect.com/2.0/advanced/migrating-from-v1.0
