### ISSUE TITLE
The second WalletConnect instance not trigger session_request very often

### ISSUE THREAD

**Issue by roadmanfong** [WalletConnect/walletconnect-monorepo#1394]
**Describe the bug**
I'm making a wallet, and I need to handle multiple sessions. It works good for first session, but very easily failed afterwards.

**SDK Version (if relevant)**
 - Client: JS
 - Version: 1.8.0

**To Reproduce**
1. connect to https://app.uniswap.org/#/swap?chain=mainnet 
2. then try to connect to https://example.walletconnect.org
3. usually not getting event session_request

**Expected behavior**
Every new wallet connect session can be setup successful

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome, Safari

**Additional context**
Reproducible example
https://codesandbox.io/s/wallet-connect-3f6knv?file=/src/App.tsx

**Comment by sbc64** [comment]
You need to provide a different storageId for each connection. If you dont set a new storageId in your constructor the default storage value of "walletconnect" gets overwritten: https://github.com/WalletConnect/walletconnect-monorepo/blob/c94c1d608e75ef7f0e77572a8627d9412ade24c3/packages/clients/core/src/storage.ts#L5

Try playing around with this:

```typescript
    const connector = new WalletConnect({
      uri,
      storageId: uri,  // <-   Made this to a random value or something you keep track off !!
      clientMeta: {
        description: "WalletConnect Developer App",
        url: "https://walletconnect.org",
        icons: ["https://walletconnect.org/walletconnect-logo.png"],
        name: "WalletConnect"
      }
    });
    ```

**Comment by roadmanfong** [comment]
Thanks a lot!

and I found other workaround is provide dummy session

```ts
const connector = new WalletConnect({
  uri,
  session: {},
  clientMeta: {
        description: "WalletConnect Developer App",
        url: "https://walletconnect.org",
        icons: ["https://walletconnect.org/walletconnect-logo.png"],
        name: "WalletConnect"
      }
})
```

Which is from Metmask 
https://github.com/MetaMask/metamask-mobile/blob/fb7184c14f3afc42f8e77475f05dffd557383c47/app/core/WalletConnect.js#L380
