### ISSUE TITLE
Cannot import wallet connect

### ISSUE THREAD

**Issue by AndonMitev** [WalletConnect/walletconnect-monorepo#1403]
I have created a new react-native-project, version:  "react-native": "0.69.5", using expo.

When I execute steps from the documentation from wallet Section: [Wallet Connect - Wallet React Native](https://docs.walletconnect.com/quick-start/wallets/react-native)

My application is not able to compile:

![image](https://user-images.githubusercontent.com/32274987/187657259-649459fa-d86e-4d49-9b1e-822cf85534e8.png)

**Comment by xzilja** [comment]
Which version of WalletConnect are you using?
