### ISSUE TITLE
personal_sign wrong signature

### ISSUE THREAD

**Issue by olaf89** [WalletConnect/walletconnect-monorepo#141]
I tried integrating walletconnect for my dapp. I was using trust wallet on iOS for testing. I was able to connect and read account.  Unfortunately When i tried to use personal_sign the results were different then by using build in dapp browser and metamask

Update, i think i found the issues

The custom rpc message that im using follows this spec 
https://github.com/ethereum/go-ethereum/wiki/Management-APIs 

Which defines personal_sign payload as 
{"method": "personal_sign", "params": [message, account, password]}

Yet walletconnect expects reverted params where [account, message], and my requests are signing the account instead of message.

Also when reverting the params now walletconnect is trying it sign the raw message, yet the message is a hex prefixed by 0x.

Update2
Even by sending just the plain text message i am being presented with a hex so thats not solving it

**Comment by pedrouid** [comment]
Thanks for reporting this. 🙌 I will fix the reverted params.

However the way Trust Wallet is displaying the message and signing is outside of the WalletConnect's scope.

Could you open an issue on their Github?
https://github.com/TrustWallet

**Comment by olaf89** [comment]
Sure thing, i assumed its related to walletconnect cause the same actions work when using their build in browser, and the message is displayed as plain text.
