### ISSUE TITLE
Transactions not showing when testing on trust wallet.

### ISSUE THREAD

**Issue by olaf89** [WalletConnect/walletconnect-monorepo#142]
I tried integrating walletconnect for my dapp. I was using trust wallet on iOS for testing. I was able to connect and read account. Unfortunately When i tried to sign_transaction there was no response and i was never asked for confirmation on the wallet. 

I tried using sendTransaction api.
```
walletConnector.sendTransaction({data, gas, from , to })
```

as well as sendCustomRequest
```
walletConnector.sendCustomRequest({
    id,
    jsonrpc,
    method: "eth_sendTransaction",
    params: [{ data, gas, from, to }]
})
```

personal_sign methods were asking for approval and retuning results. The signature was wrong tho but i created a separate issue for that https://github.com/WalletConnect/walletconnect-monorepo/issues/141.

**Comment by pedrouid** [comment]
This is also an issue with Trust Wallet. Could your report on their Github?

I've also experienced this which is caused by when you're missing a field on the transaction object. However this should not happen as the only fields that are strictly required are the `from` and `data` fields.
