### ISSUE TITLE
Desktop link for Crypto.com is broken

### ISSUE THREAD

**Issue by Adamj1232** [WalletConnect/walletconnect-monorepo#1421]
**Describe the bug**
When clicking the Crypto.com option within the Desktop tab is broken and opens a tab with a broken link.

**To Reproduce**
1. Go to Curve.fi
2. Click on Connect wallet
3. Select Desktop tab
4. Click crypto.com and see broken link

**Expected behavior**
Takes a user to the proper location

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome, Firefox, Brave

**Comment by looter** [comment]
@Adamj1232 thanks for flagging this. question for you do you have the crypto.com desktop wallet installed? This should be a deeplink and if you have the desktop wallet installed it should route it accordingly.

**Comment by Adamj1232** [comment]
I do not but feel there should be some user feedback if that is the case since it is the first option displayed by default
