### ISSUE TITLE
Support Electron App

### ISSUE THREAD

**Issue by xzjcool** [WalletConnect/walletconnect-monorepo#144]
` "https:" !== window.location.protocol && "localhost" !== window.location.hostname) throw new Error("HTTPS is required for non-localhost origins");`
WalletConnect will check the hostname. but if an app is bundle in Electron, the protocol is file://, and the hostname is ""
So what's the plan to support electron app

**Comment by tiagorvmartins** [comment]
I have the same question, how did you fix it @xzjcool? Thank you
