### ISSUE TITLE
How to update wallet's link as the walletconnect-registry is readonly

### ISSUE THREAD

**Issue by chenyoh** [WalletConnect/walletconnect-monorepo#1443]
Hi, I'm a developer at ONTO Wallet and I need to modify the configuration on Wallet Connect due to a business change, However, I do not have an account to log in Wallet Connect (because the information of creating ONTO Wallet on Wallet Connect was created by submitting PR on Github), may I ask what should I do in this case?

**Comment by looter** [comment]
Hi @chenyoh either reply with an email address you have access to after you create a cloud explorer account and let me know what it is and I can make sure that account is associated with the listing.

**Comment by looter** [comment]
Btw closing this as it's a duplicate with #1414. Will continue the thread there.
