### ISSUE TITLE
When Google Browser clicks the Connect button, it will open a new invalid page while opening the wallet app

### ISSUE THREAD

**Issue by mvpyb** [WalletConnect/walletconnect-monorepo#1450]
**Describe the bug**

When Google Browser clicks the Connect button, it will open a new invalid page while opening the wallet app

The location of the bug: qrcode modal/dist/cjs/index Js line 76 (target: "_blank") 
The solution is to comment out the changed code

**Comment by hackyguru** [comment]
Hi @mvpyb can I know the SDK version and a bit more about your environment?

**Comment by mvpyb** [comment]
"@walletconnect/client": "^1.8.0",
"@walletconnect/qrcode-modal": "^1.8.0",
 "@walletconnect/utils": "^1.8.0",

node 12.18.0
win11

**Comment by mvpyb** [comment]
![1663638959166](https://user-images.githubusercontent.com/34262867/191150288-cc2885ef-5619-4c3e-a733-57c722ff4b2f.jpg)

**Comment by finessevanes** [comment]
hey @mvpyb v1 has been deprecated so please be sure to use the latest SDK. Migration Guide: https://docs.walletconnect.com/2.0/advanced/migrating-from-v1.0
