### ISSUE TITLE
eth_sendTransaction with sendCustomRequest invalid result format

### ISSUE THREAD

**Issue by olaf89** [WalletConnect/walletconnect-monorepo#146]
According to spec https://docs.walletconnect.org/json-rpc/ethereum#example-3 the result should be
```
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": "0xe670ec64341771606e55d6b4ca35a1a6b75ee3d5145a99d05921026d1527331"
}
```

Yet currently txHash is returned as a string without { result } wrapper

Same probably applies to other methods like personal_sign

**Comment by pedrouid** [comment]
Hi @olaf89, the method `sendCustomRequest` is acting as expected as you can see from the README Quick Start:

https://github.com/WalletConnect/walletconnect-monorepo#send-custom-request

This is similar to how Web3 handles `sendAsync` and `send` methods and it's also complaint with the EIP-1193 spec: https://eips.ethereum.org/EIPS/eip-1193

I might expose a method that passes JSON-RPC requests and responses without intervention but this would technically be an internal method to be used for integration with other APIs.

If you are planning to interface directly with the WalletConnect SDK then you should use the `sendCustomRequest` method as is

**Comment by olaf89** [comment]
It would make my integration easier when getting raw responses but i can live with extra mappings on my side.
