### ISSUE TITLE
@walletconnect/web3-provider has sub dependencies with major version differences

### ISSUE THREAD

**Issue by TheDutchCoder** [WalletConnect/walletconnect-monorepo#1476]
**Describe the bug**
This package has dependencies (which have sub dependencies) of the same packages but with different major versions.
Certain build tools will pick one of them, instead of duplicating multiple major versions in the output. This leads to modules not being found.

**SDK Version (if relevant)**
 - Client: JS
 - Version 1.8..0

**To Reproduce**
https://stackblitz.com/edit/github-1wqbue-kp7mfb?file=composables%2FuseMain.ts,app.vue,package.json

Run `npm run build && npm run preview` and you'll see that certain modules can't be resolved.
The underlying problem is that there are a handful of dependencies that have different major versions (e.g. `json-rpc-engine`).
During the build step, one of those major versions will be picked (usually the most recent one), which leads to require/import problems (as some major versions differ in their export strategies).

Really the core problem is that a ton of web3 related libs are not proper ESM.

**Expected behavior**
This package to not have multiple major version dependencies.

I know that this goes upstream as well, to other package authors.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser N/A
 - Version N/A

**Comment by itzaks** [comment]
Yes. This is causing difficulties for us when deploying this. Often I get the following issue when deploying things in production.

```ts
Cannot find module 'json-rpc-engine/src/createAsyncMiddleware'
Require stack:
- /var/task/node_modules/eth-json-rpc-middleware/block-cache.js
- /var/task/node_modules/web3-provider-engine/subproviders/cache.js
- /var/task/node_modules/@walletconnect/web3-provider/dist/cjs/index.js

```

The root cause being different major versions of json-rpc-engine.

**Comment by finessevanes** [comment]
@TheDutchCoder hey, we've deprecated v1, so please migration to v2: https://docs.walletconnect.com/2.0/advanced/migrating-from-v1.0
