### ISSUE TITLE
Websocket in node_modules breaks upgradability

### ISSUE THREAD

**Issue by digitaldonkey** [WalletConnect/walletconnect-monorepo#148]
Node denies any install action because node_modules/websocket is in place. 

Only manuall removal of the node_modules enables `npm i xyz` to run without the following error. Maybe the websocket is somehow misplaced?

```
npm ERR! path /Users/tho/htdocs/ConsenSys/WalletConnectEvaluate/web3ready/node_modules/websocket
npm ERR! code EISGIT
npm ERR! git /Users/tho/htdocs/ConsenSys/WalletConnectEvaluate/web3ready/node_modules/websocket: Appears to be a git repo or submodule.
npm ERR! git     /Users/tho/htdocs/ConsenSys/WalletConnectEvaluate/web3ready/node_modules/websocket
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

**Comment by pedrouid** [comment]
This must be a dependency of webpack because we don't use any special libraries for handling WebSockets, just the native web api

**Comment by digitaldonkey** [comment]
Sooms to be a issue with https://github.com/frozeman/WebSocket-Node#browserifyCompatible

```
"scripts": {
    ...,
    "preinstall": "rm -rf node_modules/react-native-safe-area-view/.git"
  },
```

**Comment by digitaldonkey** [comment]
Seems to be a issue with https://github.com/frozeman/WebSocket-Node#browserifyCompatible which is required by web3-core-requestmanager 1.0.0-beta.37

```
"scripts": {
    ...,
    "preinstall": "rm -rf node_modules/websocket/.git"
  },
```
