### ISSUE TITLE
where are build instructions?

### ISSUE THREAD

**Issue by digitaldonkey** [WalletConnect/walletconnect-monorepo#149]
I remember an older version of WalletConnect had build instructions on the readme, which allowed to use the uncompiled version of WC.
Seems they are gone.
It's kind of impossible to spot the problems in the compiled version (without source maps). 

How is the build/debug process now?

**Comment by pedrouid** [comment]
Each package has it's own build config but you can find it on `webpack.config.js`

For core package: https://github.com/WalletConnect/walletconnect-monorepo/blob/master/packages/core/webpack.config.js

However I do included source-maps as before, you can see the file tree bellow

<img width="282" alt="Screenshot 2019-06-13 18 41 11" src="https://user-images.githubusercontent.com/10136079/59451055-de2fc300-8e0a-11e9-929c-7c78507068a5.png">
