### ISSUE TITLE
Error: Walletconnect Relay protocol not supported

### ISSUE THREAD

**Issue by finessevanes** [WalletConnect/walletconnect-monorepo#1503]
**Describe the bug**
When I connect a v1 dapp with v2 I get an error that the relay protocol is not supported.

**SDK Version (if relevant)**
 - Client: JS
 - Version v2

**To Reproduce**
1. Go to https://app.uniswap.org/#/swap, click Connect Wallet and select WalletConnect. Copy the v1 URI.
3. Go to https://react-wallet.walletconnect.com/walletconnect and paste in the v1 URI. Click Connect
5. See error
6. Go to https://react-app.walletconnect.com/, click Ethereum, then Connect. Copy the v2 URI
7. Go to https://react-wallet.walletconnect.com/walletconnect and paste in the v2 URI. Click Connect
8. See Session Proposal modal

**Expected behavior**
When I click connect I should see a modal titled Session Proposal

**Screenshots**
Error:
<img width="480" alt="error" src="https://user-images.githubusercontent.com/44731696/193695055-eb847eb4-193b-490a-8f5b-da57168197ac.png">

Success:
<img width="419" alt="success" src="https://user-images.githubusercontent.com/44731696/193695083-7830f3ff-fff6-49c8-895b-f17a0a9f5ed9.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: brave
 - Version:  brave v1.44.101

**Comment by finessevanes** [comment]
This error is expected because v2.0 is NOT backwards-compatible with v1.0. 

This is happening because the URI that is being used in the first example is v1.0, not v2.0. 
v1.0 relay uses `x.bridge.walletconnect.org` and v2.0 uses `relay.protocol`.

The URI in the first example:
`wc:76259525-a954-41cc-aa9b-63f4f75cc660@1?bridge=https%3A%2F%2Fr.bridge.walletconnect.org&key=705d48fe4f71d9b6416801c78de0750722227b76836b300f3e2bc00df61a6539
`

The URI in the second example:
`wc:529b87e48a01d2776cc4d7b0cea479c044f02e14e5f8225b4362fe688394da3c@2?relay-protocol=irn&symKey=1c563e69503183e5885aab7f187a67f87054e1a899e9da6a1a9656138e5c53fd`

Have more questions? Check out the [migration docs](https://docs.walletconnect.com/2.0/advanced/migrating-from-v1.0#migration-schedule).

To view what wallets support which protocol, see below:
- [v2.0](https://explorer.walletconnect.com/?version=2)
-  [v1.0](https://explorer.walletconnect.com/?version=1)

**Comment by Jake-Mulhern** [comment]
I think I am running into the same issue.  

Here are the versions of the WalletConnect packages that I am running:
```
"@walletconnect/auth-client": "^2.0.2",
"@walletconnect/react-native-compat": "^2.2.1",
"@walletconnect/sign-client": "^2.2.1",
"@walletconnect/web3wallet": "^1.0.0",
```

and here is the example URI I am getting from OpenSeas while testing my implementation:
```
 wc:e9999361-c2f9-4814-9a07-1172ebe92141@1?bridge=https%3A%2F%2Fe.bridge.walletconnect.org&key=3e3d41ed85ff7879ec2951a916affe3eee6c4923e3e7e9f7196df0e3e4ee9f1e
```

If this is the same type of issue how would I implement both versions of WalletConnect in the same project to cover both version 1 and 2?

**Comment by Jake-Mulhern** [comment]
I can't even seem to find an NFT marketplace that uses V2 at all.  Every URI I've come across is V1.

**Comment by finessevanes** [comment]
@Jake-Mulhern are you building a wallet? If so, Web3Wallet wraps both sign v2 and auth so you don't need to implement them on their own. 

Here is an example wallet of sign v1 and v2 implemented together. LMK if this works for ya!
https://github.com/WalletConnect/web-examples/tree/main/wallets/react-wallet-v2
[Demo Wallet](https://react-wallet.walletconnect.com/)

**Comment by Ao28th28** [comment]
How to fix this?

**Comment by PTGBJC** [comment]
Ainda ns cm funciona mas cm o tempo vou me adaptar

**Comment by AungThuSoe24** [comment]
okx_metax:wc:1338dc92345de5148debba56e07d12d8debb824307ab5fdc17291c656acbeecc@2?expiryTimestamp=1719678468&relay-protocol=irn&symKey=76722856eccca920ba45ab6031b3c381767217e7c8cd712db5ab4b54e567ed51

**Comment by AungThuSoe24** [comment]
Open wallet connect

**Comment by trungpolao99** [comment]
wc:ac4ef27d831c506d62b26aa10472d20a4e56be5011b640f6bb52d97fd0458dd8@2?relay-protocol=irn&symKey=1762f0357b1bb656bdaa1e8e8dc9db815866733ef50b7885b80dfb7d6c33cda9
