### ISSUE TITLE
Doesn't work crypto.com wallet via QRCodeModal React-Native

### ISSUE THREAD

**Issue by pishvanov** [WalletConnect/walletconnect-monorepo#1510]
Hi everyone. 

I faced the problem with wrong linking in WalletConnect Provider.  
![Снимок экрана 2022-10-05 в 15 18 36](https://user-images.githubusercontent.com/98952093/194058562-2792345b-c499-43c5-9574-1444019d9e6a.png)
Clicking on Crypro.com redirect to the [wallet.crypto.com](url) and throw an error : 

![Снимок экрана 2022-10-05 в 15 19 30](https://user-images.githubusercontent.com/98952093/194058735-8296a0b1-d214-4ae5-9515-a7bf05430651.png)

I logged data in node_modules 

`walletServices.map(( item, index ) => console.log( item.mobile ))` 

and got this:

`Object {
  "native": "cryptowallet:",
  "universal": "https://wallet.crypto.com",
}`

I think here should be another universal link. Also, i tried to download cryptowallet mobile app to avoid redirecting, but it doesn't solve the problem.

Please fix, or provide the solution. Thanks.

**Comment by finessevanes** [comment]
@pishvanov is this still an issue?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
