### ISSUE TITLE
Is this possible to use native url when sign transaction with wallet connect

### ISSUE THREAD

**Issue by x64x48** [WalletConnect/walletconnect-monorepo#1529]
**Is your feature request related to a problem? Please describe.**

When we develop our dapp with wallet connect provider, we found an interesting behavior:

The link will go directly to the wallet app (we used metamask here) when user connect to their wallet. Was it native url here found in web3modal (https://github.com/WalletConnect/web3modal/blob/e12df834426ec7e718d8fb77dbc5b2e03fb20a11/packages/core/src/utils/CoreHelpers.ts#L15)?

But when we try to send transaction, it went to App Store first. Supposed this was universal link?

https://user-images.githubusercontent.com/81462372/195514884-3ffdb1b1-8f41-4255-887d-61a540d074df.MP4

Just wonder is this possible to use native url when sign transaction with wallet connect?

Not sure where should I post (metamask or wallet connect https://docs.walletconnect.com/specs)?

**Comment by stormgain-dev** [comment]
Have you read this article? Especially regarding asynchronous handlers?
https://docs.walletconnect.com/1.0/mobile-linking#ios-app-link-constraints
