### ISSUE TITLE
Weird behavior when connect to testnet goerli

### ISSUE THREAD

**Issue by x64x48** [WalletConnect/walletconnect-monorepo#1530]
**Describe the bug**

I found a weird when debug with my metamask (phone). The connection process worked great, but I found the chainId and the latest block number didn't match at first time.

Here is the log for `provider.getNetwork()` and `provider.getBlockNumber()` (looks like the mainnet block number.):
![image](https://user-images.githubusercontent.com/81462372/195564381-1c275686-98a4-4b60-b823-cb4563610e6c.png)

If I refresh the page and reconnect to walletconnect, it worked great as usual.

Also checked, it seems not the same issue: https://github.com/WalletConnect/walletconnect-monorepo/issues/1097

**Comment by finessevanes** [comment]
@x64x48 is this still an issue?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version  :)

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
