### ISSUE TITLE
Xcapit deeplink not working (And other wallets)

### ISSUE THREAD

**Issue by fpiantoni** [WalletConnect/walletconnect-monorepo#1538]
In the react-native walletconnect modal, Xcapit and a few other wallet's are not working (deeplink).

**Comment by crypblizz8** [comment]
Hey there, just to confirm this is for the package `@walletconnect/react-native-dapp`?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
