### ISSUE TITLE
[JS] Cannot import correctly under TypeScript Node 16 module resolution

### ISSUE THREAD

**Issue by Jack-Works** [WalletConnect/walletconnect-monorepo#1601]
**Describe the bug**
Under TypeScript Node 16 module resolution (has `type: module` in the `package.json` and `moduleResolution: Node16` in `tsconfig.json`), this package cannot be imported correctly.

**SDK Version (if relevant)**
 - Client: JS
 - Version 1.8.0

**To Reproduce**
1. Install "@walletconnect/client": "^1.8.0"

```ts
import Client from '@walletconnect/client'
new Client(opts)
// type error
new Client.default(opts)
// runtime error
```

> package.json

```json
{ "type": "module" }
```

> tsconfig.json

```json
{
    "compilerOptions": {
        "moduleResolution": "Node16"
    }
}
```

**Expected behavior**
Can import

**Screenshots**
![image](https://user-images.githubusercontent.com/5390719/200101875-3274f67d-1dea-462b-bd2e-9fca8d1bafe1.png)

**Additional context**
TypeScript thinks this package is a CommonJS package and therefore provides the synthetic export for the CommonJS module.

**Comment by finessevanes** [comment]
v1 has been deprecated. Please migrate to v2: https://docs.walletconnect.com/2.0/advanced/migrating-from-v1.0
