### ISSUE TITLE
SignClient.init is not a function

### ISSUE THREAD

**Issue by akash-brainium** [WalletConnect/walletconnect-monorepo#1621]
**Describe the bug**

**SDK Version (if relevant)**
 - Client: [e.g. JS, Swift, Kotlin]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bkrem** [comment]
Duplicates #1167
