### ISSUE TITLE
"No Accounts Available"

### ISSUE THREAD

**Issue by cbarraford** [WalletConnect/walletconnect-monorepo#163]
Newbie here, trying to build a webapp with walletconnect support. In my local dev environment, i get the following error.
![IMG_0F467D1E8E65-1](https://user-images.githubusercontent.com/246180/61205663-02740d80-a6f1-11e9-8ffd-c992bab42a8c.jpeg)

Any idea why this may be? Do i need to build my own bridge server? If so, i haven't been able to find the documentation for that. Thanks in advanced!

**Comment by pedrouid** [comment]
This looks like a Trust Wallet issue, could you open an issue on their repository

https://github.com/TrustWallet
