### ISSUE TITLE
Error disconnecting session on `session_delete` events

### ISSUE THREAD

**Issue by khoanguyen-yang** [WalletConnect/walletconnect-monorepo#1639]
**Describe the bug**
Context: I am integrating WC V2 into my mobile wallet app.

Got `Error: No matching key. session or pairing topic doesn't exist: ...` when trying to disconnect the session using `signClient.disconnect` on `session_delete` events (receive the events by triggerring Disconnect from the DApp at https://react-app.walletconnect.com/)

The session is retrievable using `signClient.session.get` in `session_request` events though.
And besides, the session can be disconnected successfully if I disconnect it from the wallet by calling `signClient.disconnect` directly.

Only happen when disconnect after receiving `session_delete` events

**SDK Version (if relevant)**
 - Client: JS
 - Version: 2.1.3

**To Reproduce**
You can reproduce the error by using the example at https://github.com/WalletConnect/web-examples/tree/main/wallets/react-wallet-v2
Inside `src/hooks/useWalletConnectEventsManager.ts`, add a handler for `session_delete` event.

```
...
const onSessionDelete = useCallback(
    async (requestEvent: SignClientTypes.EventArguments['session_delete']) => {
      await signClient.disconnect({
        topic: requestEvent.topic,
        reason: getSdkError('USER_DISCONNECTED')
      })
    },
    []
  )

  /******************************************************************************
   * Set up WalletConnect event listeners
   *****************************************************************************/
  useEffect(() => {
    if (initialized) {
      ...
      signClient.on('session_delete', onSessionDelete)
    }
  }, [initialized, onSessionProposal, onSessionRequest])
...
```

**Expected behavior**
Able to disconnect the session or if the session is automatically disconnected there should be documentation specifying this.

**Comment by bkrem** [comment]
Hi @khoanguyen-yang,

> Able to disconnect the session or if the session is automatically disconnected there should documentation specifying this.

I think you already hit the nail on the head here: this needs to be documented better.


> And besides, the session can be disconnected successfully if I disconnect it from the wallet by calling signClient.disconnect directly.
>
> Only happen when disconnect after receiving session_delete events

This is because the client receiving the session delete request (the wallet in your case) is automatically cleaning up the session internally as you suspected, here's the relevant handler method:
https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/sign-client/src/controllers/engine.ts#L656

As shown in the handler code, the `session_delete` event is only emitted **after** the session has been removed, so the `session_delete` event is simply for you to react to a session having been deleted (e.g. to reset your UI to non-connected state etc), not to do the session removal yourself. So there's no need to explicitly call `disconnect` on the receiving client.

**Comment by khoanguyen-yang** [comment]
Thanks for the clarification!

**Comment by adnansudozai** [comment]
In wallet connect v2 i have succesfully pairing and connect my wallet to any daaps every thing is work fine but when I hit any transection from any daaps then daaps return me an error but I receive session_requenst from daps to my wallet and my sign or transection made successfully but daaps show an error and my wallet after paring and connected from any daaps return me an error on console {context: 'client'} 'No matching key. session: 30d220da4220f2c7618a20e992c90a7eafd15a83380adfdd08698c03e4f4894c'
reactConsoleErrorHandler @ ExceptionsManager.js:151
registerError @ LogBox.js:187
console.error @ LogBox.js:67
overrideMethod @ backend.js:2082
LOG @ browser.js:202
(anonymous) @ browser.js:266
getData @ index.cjs.js:1
(anonymous) @ index.cjs.js:1
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ web3.min.js:2
t @ web3.min.js:2
(anonymous) @ asyncToGenerator.js:19
(anonymous) @ index.cjs.js:1
(anonymous) @ index.cjs.js:1
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ web3.min.js:2
t @ web3.min.js:2
(anonymous) @ asyncToGenerator.js:19
(anonymous) @ index.cjs.js:1
(anonymous) @ index.cjs.js:1
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
U @ web3.min.js:2
M @ web3.min.js:2
y @ web3.min.js:2
ExceptionsManager.js:151 {context: 'core'} {context: 'core/expirer'} 'No matching key. expirer: topic:1cf19a0d57a8318503663904ef02b4053a4c7778133b4e6b0ab56cb0ba28ab4a'
