### ISSUE TITLE
generateRandomBytes32 is not a function

### ISSUE THREAD

**Issue by khoanguyen-yang** [WalletConnect/walletconnect-monorepo#1646]
**Describe the bug**
Got this when build a production release on React Native `generateRandomBytes32 is not a function`
Dev mode works fine.

The function is coming from `@walletconnect/utils` so this may not be relevant to environment-specific issues or `shimming`, `polyfiling` things.

Please give me an advice.

**SDK Version (if relevant)**
 - Client: JS
 - Version 2.1.3

**Comment by crypblizz8** [comment]
Hey @khoanguyen-yang, are you still stuck on this issue? 

If still stuck after reading [this guide](https://docs.walletconnect.com/2.0/javascript/guides/react-native), happy to help you further debug.

**Comment by khoanguyen-yang** [comment]
Hello, the error somehow does not appear anymore although I did not make any change relevant to WalletConnect.
Maybe be the reason is coming from outside conflicts.
Closing this now.
