### ISSUE TITLE
React Native: TypeError: crypto_1.default.randomBytes is not a function.

### ISSUE THREAD

**Issue by apostgit** [WalletConnect/walletconnect-monorepo#1647]
Trying to work with @walletconnect/client but get an error which has to do with @walletconenct/randomBytes. The error is 
`[Unhandled promise rejection: TypeError: crypto_1.default.randomBytes is not a function. (In 'crypto_1.default.randomBytes(length)', 'crypto_1.default.randomBytes' is undefined)]`

React Native / Expo SDK 46

I'm using the /client package to connect my application to wallet connect v1 dapps. The pairing with the URI happens, the .approveSession works fine as seen in [this](https://github.com/WalletConnect/web-examples/blob/main/wallets/react-wallet-v2/src/views/LegacySessionProposalModal.tsx) example but when `connect` event fires I get the above error. 

I understand it has to do with the `crypto` package not working with React Native but rn-nodeify and other options and none of them work.

**Comment by finessevanes** [comment]
@apostgit are you still experiencing this issue with our latest version? https://docs.walletconnect.com/2.0/javascript/guides/react-native

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
