### ISSUE TITLE
SignClient.init TypeError: Cannot read properties of undefined (reading 'on')

### ISSUE THREAD

**Issue by elizalucas** [WalletConnect/walletconnect-monorepo#1649]
**Describe the bug**
On calling `Client.init` I am getting the following error: 

```
TypeError: Cannot read properties of undefined (reading 'on')
    at Xe.registerExpirerEvents (index.es.js?6bec:1:23347)
    at Xe.init (index.es.js?6bec:1:6692)
    at async C.initialize (index.es.js?6bec:1:27556)
    at async C.init (index.es.js?6bec:1:27385)
```

Here is the relevant code that I am using that is throwing the error:
```
import Client from '@walletconnect/sign-client'

const _client = await Client.init({
          projectId: '<projectId>',
          metadata: {
            name: 'name',
            description: 'desc',
            url: '#',
            icons: ['https://avatars.githubusercontent.com/u/37784886'],
          },
        })
```

After going through the walletconnect repo I believe the error is being triggered here: https://github.com/WalletConnect/walletconnect-monorepo/blob/77a65f0ee4f8739cb068312f6ded77311b83431b/packages/sign-client/src/controllers/engine.ts#L713 although I am not familiar enough with the code to understand why this would be undefined.

**SDK Version**
 - Client: JS
 - Version ^2.1.0

**Expected behavior**
The client should initialize successfully

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Additional context**
I tried updating my walletconnect version to 2.1.3 - no change in behavior.

**Comment by ganchoradkov** [comment]
hey @elizalucas could you provide us with an example repo where we can reproduce the error?

Many thanks

**Comment by elizalucas** [comment]
Hey @ganchoradkov, unfortunately the repo is private so I'm unable to share. Are there any other details I can give you that would be helpful?

**Comment by elizalucas** [comment]
I resolved this by updating both my walletconnect/sign-client and walletconnect/types to version 2.1.3. Closing this issue.
