### ISSUE TITLE
after I scan QRcode nothing happened

### ISSUE THREAD

**Issue by OstapDutkevych** [WalletConnect/walletconnect-monorepo#1654]
Describe the bug
When I call approval() QRCodeModal is open but when I scan QRcode nothing happen

SDK Version (if relevant)
"@walletconnect/sign-client": "^2.1.1",

To Reproduce
To reproduce the behavior follow the instructions on https://docs.walletconnect.com/2.0/javascript/sign/installation

Create a new application
Install the packages above
Initialize the startup code from the installation page

`const signClient = await SignClient.init({
      projectId: "65540ae88ea4b0258d3f53b4c7f0aacb",
    });

 try {
      const {uri, approval} = await signClient.connect({
        requiredNamespaces: {
          eip155: {
            methods: [
              "eth_sendTransaction",
              "eth_signTransaction",
              "eth_sign",
              "personal_sign",
              "eth_signTypedData",
            ],
            chains: ["eip155:1"],
            events: ["chainChanged", "accountsChanged"],
          },
        },
      });
      if (uri) {
        QRCodeModal.open(uri, () => {
          console.log("EVENT", "QR Code Modal closed");
        });
      }

      // Await session approval from the wallet.
      const session = await approval();
      // Handle the returned session (e.g. update UI to "connected" state).
      // await onSessionConnected(session);
      console.log(session)
    } catch (e) {
      console.error(e);
    } finally {
      // Close the QRCode modal in case it was open.
      QRCodeModal.close();
    }
`

Expected behavior
Should create session after I scan QRcode

Desktop (please complete the following information):

OS: MacOS
Browser Chrome
Additional context
maybe i'm doing something wrong
Could you please tell me what the problem is?
Please let me know how to best lend a hand.

**Comment by ZeeshanAhmadKhalil** [comment]
Why you closed it?
Did you find any solution?
