### ISSUE TITLE
Could not resolve "tslib"

### ISSUE THREAD

**Issue by smelnikov** [WalletConnect/walletconnect-monorepo#1657]
**Describe the bug**
Error when executing the example code

**SDK Version (if relevant)**
"@walletconnect/sign-client": "2.1.3",
"typescript": "^4.9.3",
"vite": "^3.2.4"

**To Reproduce**
Checkout branch `could-not-resolve-tslib` of repo: https://github.com/smelnikov/walletconnect-sample
```sh
yarn install
npx vite
```
Many errors of the same type appear:
```sh
Could not resolve "tslib"

    node_modules/@walletconnect/logger/dist/cjs/index.js:3:24:
      3 │ const tslib_1 = require("tslib");
```

**Expected behavior**
There are no errors at startup.

**Comment by bkrem** [comment]
Fixed in https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.1.4

Please let us know if this is still reproducible and we'll reopen.
