### ISSUE TITLE
TypeError: events_1.EventEmitter is not a constructor in runtime

### ISSUE THREAD

**Issue by smelnikov** [WalletConnect/walletconnect-monorepo#1659]
**Describe the bug**
Error when executing the example code

**SDK Version (if relevant)**
"@walletconnect/sign-client": "2.1.3",
"typescript": "^4.9.3",
"vite": "^3.2.4"

**To Reproduce**
Checkout branch `eventemitter-is-not-a-constructor` of repo: https://github.com/smelnikov/walletconnect-sample
```sh
yarn install
npx vite
```
A runtime error appears:
```sh
Uncaught (in promise) TypeError: events_1.EventEmitter is not a constructor
    at new HeartBeat (heartbeat.ts:15:19)
    at new J2 (index.ts:5:16)
    at new C3 (index.ts:5:16)
    at C3.init (index.ts:5:16)
    at main.ts:3:8
```

**Expected behavior**
There are no errors in runtime.

**Comment by bkrem** [comment]
Fixed in https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.1.4

Thanks again for the minimal reproduction here 🙏 

Please let us know if this is still reproducible and we'll reopen.

**Comment by smelnikov** [comment]
@bkrem Thank you, now this errors (#1657, #1658, #1659) does not occurs.

**Comment by own2pwn** [comment]
Happens to me with 
1. `create vue@latest`
2. `yarn add @walletconnect/auth-client`
```
async function testAuth() {
  const authClient = await AuthClient.init({
    projectId: '<YOUR_PROJECT_ID>',
    metadata: {
      name: 'my-auth-dapp',
      description: 'A dapp using WalletConnect AuthClient',
      url: 'my-auth-dapp.com',
      icons: ['https://my-auth-dapp.com/icons/logo.png']
    }
  })
}
//
<button @click="testAuth">Authorize</button>`
```
@bkrem
