### ISSUE TITLE
React Native: crypto could not to be found within the project or in these directories

### ISSUE THREAD

**Issue by LauColombini** [WalletConnect/walletconnect-monorepo#1662]
**Describe the bug**
Im using react native cli, not expo.

I have this issue:
 ` const crypto_1 = __importDefault(require("crypto"));`

**Screenshots**
<img width="429" alt="Screen Shot 2022-11-18 at 4 42 44 PM" src="https://user-images.githubusercontent.com/53497784/202788981-eb0f604e-dd3c-4059-b5d0-4b4e61dbdc42.png">
<img width="407" alt="Screen Shot 2022-11-18 at 4 42 59 PM" src="https://user-images.githubusercontent.com/53497784/202789022-ac6d91fc-d8c6-4eec-ac75-b917abb9dd3f.png">

I already read issue [#595 ](https://github.com/WalletConnect/walletconnect-monorepo/issues/595)and I can't solve it, I'm a few hours ago and I can't solve it

**Comment by LauColombini** [comment]
@pedrouid @IljaDaderko @brunobar79 I need help on this guys :c please you can help me with this?

**Comment by adrianotadao** [comment]
@LauColombini have you imported **react-native-compat** ?

> import '@walletconnect/react-native-compat';

source: https://docs.walletconnect.com/2.0/javascript/guides/react-native

**Comment by crypblizz8** [comment]
Still stuck on this @LauColombini ? Happy to help look through your repo to help out!

**Comment by LauColombini** [comment]
> Still stuck on this @LauColombini ? Happy to help look through your repo to help out!

Yes im still stuck with this error, you can help me?

**Comment by crypblizz8** [comment]
No worries, could you share a clear reproduction with your files / setup? Thanks

**Comment by LauColombini** [comment]
> #595

[I was able to solve it](https://github.com/WalletConnect/walletconnect-monorepo/issues/595#issuecomment-1362077222)
