### ISSUE TITLE
React Native: Invalid pairing URI is not handled

### ISSUE THREAD

**Issue by santerisarle** [WalletConnect/walletconnect-monorepo#1663]
**Describe the bug**
On React Native, the Pairing API doesn't check for validity of the URI.

The relevant code is this:
`signClient.core.pairing.pair({ uri: "test" })`.

Entering an invalid URI gives the following error:
`"Error: Relay Protocol not supported: undefined"`.

However, a new inactive pairing is created with this string as the topic.

When trying to delete this pairing, it gives the following error:
`Non-base16 character`. So the invalid pairing is stuck.

**SDK Version**
 - Client: JS
 - Version: 2.1.3

**To Reproduce**
Reproduction repository [here](https://github.com/santerisarle/walletconnect-test).

**Expected behavior**
Running the exact same code in Next.js, for example, gives the error: `Missing or invalid. pair() uri` and a new pairing is not created.

It should behave like this in React Native as well.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Simulator
 - OS: iOS 13.7

**Additional context**
The same error happens on version 2.1.0 and also with the deprecated way of pairing: `signClient.pair({ uri })`.

**Comment by crypblizz8** [comment]
@santerisarle still having an issue with this on React Native?

**Comment by santerisarle** [comment]
> @santerisarle still having an issue with this on React Native?

Yes, it's still happening on version 2.2.1.

**Comment by finessevanes** [comment]
@santerisarle is this still an issue in 2.5.2?
