### ISSUE TITLE
Allow custom client metadata (clientMeta) when create new connector

### ISSUE THREAD

**Issue by toanho94** [WalletConnect/walletconnect-monorepo#1664]
**Is your feature request related to a problem? Please describe.**
Our project is using Tauri for building the application and due to the mechanism of Tauri, they always run a local webserver to serve for the UI part. So the hostname of that UI server is always http://localhost:xxxx or tauri://localhost for MacOS.
WalletConnect/core package currently uses the getWindowMetadata utility to fetch the metadata of the website, and the URL in that object will be localhost as I mentioned above.

The problem is that whenever we popup a dialog for initiating a WalletConnect connection, the hostname displayed on the Wallet is http://localhost:xxxx and I really want to change this to use my own public domain (e.g: my-company.com).

**Describe the solution you'd like**
The package is currently used getClientMeta method:
https://github.com/WalletConnect/walletconnect-monorepo/blob/1.8.0/packages/clients/core/src/index.ts#L121

So any custom clientMeta options will be overridden. I'd suggest changing the logic to increase the priority of custom clientMeta options instead of forcing us to use the data from getClientMeta.

**Comment by finessevanes** [comment]
v1 has been deprecated, please migrate to the latest version: https://docs.walletconnect.com/2.0/advanced/migrating-from-v1.0
