### ISSUE TITLE
History cache and keychain make my app so laggy

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/walletconnect-monorepo#1670]
**Describe the bug**
History cache and keychain make my app so laggy

How and when history cache and keychain should be delete in AsyncStorage ? 

I’m trying to delete some unactive pairing. 

Client.paring.delete({ topic: pairing.topic })
// this code will delete some useless stuff keychain in asyncstorage right ?

I recognize that If I use app for a long time. There is a thounsand keychain and history cache. This make everything slowly

![Screen_Shot_2022-11-23_at_17 21 47](https://user-images.githubusercontent.com/116099/203824707-cb77a4ce-6771-4993-a7e3-b2001c336790.png)

**SDK Version (if relevant)**
 - Client: JS
 - Version: 2

**Expected behavior**

Sign and Auth SDKs delete keys when a pairing or session is deleted/unsubscribed

**Comment by KhangBacoor** [comment]
Thank you
