### ISSUE TITLE
[React Native] Initializing SignClient failed

### ISSUE THREAD

**Issue by mobilestar0223** [WalletConnect/walletconnect-monorepo#1674]
**Describe the bug**
On calling `Client.init` I am getting the following error:

``` 
ERROR  {"context": "core"} WebSocket connection failed for URL: wss://relay.walletconnect.com?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtwTFhxVHJ0MmlWdW5hVWF0aFltUTJ4bldzSmExVzgyTlBFRVBlR3B0Vk5YSyIsInN1YiI6Ijg5Njk4YWM0ODVkNWZkYmExZGJjZWNhZWYwMjdiMzFlNWNjODVlNGNhNzA0Y2E1ZDhjNjBjZjljMmQ5YjJjNTIiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTY2OTQzNDYxMiwiZXhwIjoxNjY5NTIxMDEyfQ.39v1g7cdqct06EAp79bukm1y0dg0VRD6LEQry3_ceXLwnuG3bL_zAneZJpvRlEkArOclqxJjjX3NjjK4__l6BA&projectId=a8ab25078194d16f074b02b55c9fda10&ua=wc-2%2Fjs-2.1.3%2Funknown-%2Freact-native
```
```
 ERROR  {"context": "client"} WebSocket connection failed for URL: wss://relay.walletconnect.com?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtwTFhxVHJ0MmlWdW5hVWF0aFltUTJ4bldzSmExVzgyTlBFRVBlR3B0Vk5YSyIsInN1YiI6Ijg5Njk4YWM0ODVkNWZkYmExZGJjZWNhZWYwMjdiMzFlNWNjODVlNGNhNzA0Y2E1ZDhjNjBjZjljMmQ5YjJjNTIiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTY2OTQzNDYxMiwiZXhwIjoxNjY5NTIxMDEyfQ.39v1g7cdqct06EAp79bukm1y0dg0VRD6LEQry3_ceXLwnuG3bL_zAneZJpvRlEkArOclqxJjjX3NjjK4__l6BA&projectId=a8ab25078194d16f074b02b55c9fda10&ua=wc-2%2Fjs-2.1.3%2Funknown-%2Freact-native
```

Here is the relevant code that I am using that is throwing the error:
```
import Client from '@walletconnect/sign-client';

export let signClient: Client;

export async function createSignClient() {
  signClient = await Client.init({
    projectId: '<project_id>',
    metadata: {
      name: 'myapp',
      description: 'myapp',
      url: '#',
      icons: ['https://walletconnect.com/walletconnect-logo.png'],
    },
  });

}
```

**SDK Versions**:
```
"@walletconnect/react-native-compat": "^2.1.4"
"@walletconnect/sign-client": "^2.1.4"
"@walletconnect/types": "^2.1.4"
"react-native": "0.70.3"
```

• OS: MacOS
• React Native

**Comment by devjromero** [comment]
I got the same problem :c,  any update?

**Comment by KayCm** [comment]
try this.

import  { SignClient } from "@walletconnect/sign-client";

 let signClient = await SignClient.init({
      projectId: "xxx",
      metadata: {
        name: 'myapp',
        description: 'myapp',
        url: '#',
        icons: ['https://walletconnect.com/walletconnect-logo.png'],
      },
    });

    console.log("SignClient")
    console.log(signClient)


but, what next?

**Comment by crypblizz8** [comment]
Hey @mobilestar0223, I tried a similar reproduction on my end with `react-native: 0.70.6` + the SignClient initialised. 

I did run into a similar error but that is resolved as per our [React Native section in the Docs ](https://docs.walletconnect.com/2.0/javascript/guides/react-native) by importing the following in my `App.js / App.ts`

`import "@walletconnect/react-native-compat";`

This is to help with the compatibility our SDKs. Let us know if any further issues.

**Comment by mobilestar0223** [comment]
Hi, @KayCm
App couldn't reach to `console.log("SignClient")` line. Error occurs when calling `SignClient.init()` method

**Comment by KayCm** [comment]
> Hi, @KayCm App couldn't reach to `console.log("SignClient")` line. Error occurs when calling `SignClient.init()` method. And I have also done `import "@walletconnect/react-native-compat";` on my App.ts file. cc: @crypblizz8

in my case,
i put the import "@walletconnect/react-native-compat";  in index.js at first line .

**Comment by crypblizz8** [comment]
Still running into issues @mobilestar0223 ? Happy to help look through your repo.

**Comment by mobilestar0223** [comment]
yes, still have the issue

**Comment by crypblizz8** [comment]
Could you share repo or your App.js + index.js + package.json here?

**Comment by crypblizz8** [comment]
@mobilestar0223 We just put up a repo called [react-native-examples.](https://github.com/WalletConnect/react-native-examples)

Here is a link to our [App.tsx](https://github.com/WalletConnect/react-native-examples/blob/main/wallets/rn_expo_wallet/src/screens/App.tsx) for our Expo wallet. Does this help resolve?

```
import '@walletconnect/react-native-compat';
import SignClient from '@walletconnect/sign-client';

// @ts-expect-error - `@env` is a virtualised module via Babel config.
import {ENV_PROJECT_ID, ENV_RELAY_URL} from '@env';

export default function App() {
  const [signClient, setSignClient] = useState<SignClient>();

  async function createClient() {
    try {
      const client = await SignClient.init({
        projectId: ENV_PROJECT_ID,
        relayUrl: ENV_RELAY_URL,
      });
      setSignClient(client);
      await subscribeToEvents(client);
    } catch (e) {
      console.log(e);
    }
  }
  ```

**Comment by aner87** [comment]
I am experiencing the same exact problem using @crypblizz8 's version... I am running it on an Apple Silicon (the very first Macbook Pro year 2020)... could Apple Silicon be the reason perhaps?
@mobilestar0223 and the others facing this issue, what machine do you own?

**Comment by peterferguson** [comment]
+1 for the above

**Comment by RioAU** [comment]
facing same issue is there any solution for this error ? 

Is project need to reviewed first on dashboard first ? 

Some please help me

**Comment by crypblizz8** [comment]
Hey there, the latest versions for RN Wallets has been updated on our repos
https://github.com/WalletConnect/react-native-examples/pulls

Have been using M1/M2 on my setups. With the setup, is it potentially due to how you have set up the `.env` file config? @peterferguson @aner87 @RioAU

**Comment by suntwin-dev** [comment]
hello, i face the same problem in react native.
Then, i set project id allow domains is empty (means allow all domains).
Now its solved, Hope its work for you

**Comment by AndonMitev** [comment]
same issue :X

**Comment by peterferguson** [comment]
> Hey there, the latest versions for RN Wallets has been updated on our repos https://github.com/WalletConnect/react-native-examples/pulls
> 
> Have been using M1/M2 on my setups. With the setup, is it potentially due to how you have set up the `.env` file config? @peterferguson @aner87 @RioAU

Hey @crypblizz8, I looked into the setup of the repos you linked and nothing is different when it comes to the env config. In fact, even if I hard code all the env values I still get the websocket failing to connect. 

I am also experiencing the same problem with the `web3wallet` library. Although when I put in some logs it seems to get further than the sign client which only shows the websocket failed to connect error.

Here are some of the logs
```txt
[EXPO]  LOG  {"context": "core"} {"context": "core/history"} Initialized
[EXPO]  LOG  {"context": "core"} {"context": "core/expirer"} Initialized
[EXPO]  LOG  {"context": "core"} {"context": "core/relayer"} Initialized
[EXPO]  LOG  {"context": "core"} {"context": "core/relayer"} {"context": "core/relayer/messages"} Initialized
[EXPO]  LOG  {"context": "core"} {"context": "core/relayer"} {"context": "core/relayer/subscription"} Initialized
 DEBUG  {"context": "core"} {"context": "core/relayer"} {"context": "core/relayer/messages"} Successfully Restored records for messages
[EXPO]  LOG  {"context": "core"} {"context": "core/relayer"} {"context": "core/relayer/messages"} {"method": "restore", "size": 0, "type": "method"}
[EXPO]  WARN  {"context": "core"} Core Initialization Failure at epoch 1676041306082 [Error: WebSocket connection failed for URL: wss://relay.walletconnect.com?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtmbUxBNVR1TkxNQ25oNWlWb1VpelRBYnUyM1l6QThKd29RV2ZjYjFhVENOUCIsInN1YiI6IjA4MTg4ZWE3ZDYzZmQzMThjZmFmMDc0YWFiYTZkZjI3ODkxZTMzZWYyMDQxYTMzNTE5NDUyMTI5ZjAwNzNjZmYiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTY3NjA0MTMwNSwiZXhwIjoxNjc2MTI3NzA1fQ.uxFlEmoBP7ZjRR01fGjml3LYgdjgclJPcyf3okXsKHEvWslnuevWwoGrBv9mp2qwAfLBpHl_EYG-f68JGJEYBA&projectId=bd105685123997797d8a8ec8d9e952a6&ua=wc-2%2Fjs-2.2.1%2Funknown-%2Freact-native]
[EXPO]  ERROR  {"context": "core"} WebSocket connection failed for URL: wss://relay.walletconnect.com?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtmbUxBNVR1TkxNQ25oNWlWb1VpelRBYnUyM1l6QThKd29RV2ZjYjFhVENOUCIsInN1YiI6IjA4MTg4ZWE3ZDYzZmQzMThjZmFmMDc0YWFiYTZkZjI3ODkxZTMzZWYyMDQxYTMzNTE5NDUyMTI5ZjAwNzNjZmYiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTY3NjA0MTMwNSwiZXhwIjoxNjc2MTI3NzA1fQ.uxFlEmoBP7ZjRR01fGjml3LYgdjgclJPcyf3okXsKHEvWslnuevWwoGrBv9mp2qwAfLBpHl_EYG-f68JGJEYBA&projectId=bd105685123997797d8a8ec8d9e952a6&ua=wc-2%2Fjs-2.2.1%2Funknown-%2Freact-native
[EXPO]  ERROR  {"context": "client"} WebSocket connection failed for URL: wss://relay.walletconnect.com?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtmbUxBNVR1TkxNQ25oNWlWb1VpelRBYnUyM1l6QThKd29RV2ZjYjFhVENOUCIsInN1YiI6IjA4MTg4ZWE3ZDYzZmQzMThjZmFmMDc0YWFiYTZkZjI3ODkxZTMzZWYyMDQxYTMzNTE5NDUyMTI5ZjAwNzNjZmYiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTY3NjA0MTMwNSwiZXhwIjoxNjc2MTI3NzA1fQ.uxFlEmoBP7ZjRR01fGjml3LYgdjgclJPcyf3okXsKHEvWslnuevWwoGrBv9mp2qwAfLBpHl_EYG-f68JGJEYBA&projectId=bd105685123997797d8a8ec8d9e952a6&ua=wc-2%2Fjs-2.2.1%2Funknown-%2Freact-native
[EXPO]  INFO  {"context": "core"} Web3Wallet Initialization Failure
[EXPO]  ERROR  {"context": "core"} WebSocket connection failed for URL: wss://relay.walletconnect.com?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtmbUxBNVR1TkxNQ25oNWlWb1VpelRBYnUyM1l6QThKd29RV2ZjYjFhVENOUCIsInN1YiI6IjA4MTg4ZWE3ZDYzZmQzMThjZmFmMDc0YWFiYTZkZjI3ODkxZTMzZWYyMDQxYTMzNTE5NDUyMTI5ZjAwNzNjZmYiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTY3NjA0MTMwNSwiZXhwIjoxNjc2MTI3NzA1fQ.uxFlEmoBP7ZjRR01fGjml3LYgdjgclJPcyf3okXsKHEvWslnuevWwoGrBv9mp2qwAfLBpHl_EYG-f68JGJEYBA&projectId=bd105685123997797d8a8ec8d9e952a6&ua=wc-2%2Fjs-2.2.1%2Funknown-%2Freact-native
```

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)

**Comment by mertcankose** [comment]
same problem and still no solution

**Comment by glitch-txs** [comment]
hi @mertcankose could you share a [MRE](https://github.com/orgs/WalletConnect/discussions/3457) with more aditional information? This issue is a bit old and from an old version as well.

**Comment by yasincaliskan** [comment]
Problem is still exist
