### ISSUE TITLE
[Sign/Core] Implement additional context for WebSocket error handling

### ISSUE THREAD

**Issue by bkrem** [WalletConnect/walletconnect-monorepo#1681]
## Context

* Relates to https://github.com/WalletConnect/walletconnect-monorepo/issues/1519
* In https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.1.4 we shipped improved error handling for the native/browser `WebSocket` use case. 
* The failing `WebSocket` connection will now return `WebSocket connection failed for: wss://...`

## Problem
* The native/browser WebSocket implementation [returns a generic `Event`](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/error_event#event_type) for `onerror`, not an ErrorEvent with a concrete error message like node's `ws`.
* We currently do not do runtime checks for projectId in Core before the WS connection is attempted

## Proposed changes

* We should investigate whether we can indeed get concrete error messages out of the native/browser `WebSocket`, or at least the `4xx` status code that was returned.
* We should implement runtime checks for the presence of `projectId` in core, since this is a universal requirement across all our v2 SDKs.

**Comment by Billiej88** [comment]
Accepted?
