### ISSUE TITLE
Add ESM file in dist and `module` field in `package.json`

### ISSUE THREAD

**Issue by way2ex** [WalletConnect/walletconnect-monorepo#1684]
**Is your feature request related to a problem? Please describe.**
When I use `@walletconnect/qrcode-modal` in my ESM package and use ts-jest to build, I run into a problem which is ` SyntaxError: Cannot use import statement outside a module`.

I think the problem occurs because `@walletconnect/qrcode-modal` only have a Commonjs file 
![image](https://user-images.githubusercontent.com/24694223/204687877-6c350c66-833c-4e84-8446-37a3dbab34dc.png)

**Describe the solution you'd like**
Add ESM file in dist and `module` field in `package.json` .

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
