### ISSUE TITLE
connected value is not true even wallet is connected correctly on React Native

### ISSUE THREAD

**Issue by mobilestar0223** [WalletConnect/walletconnect-monorepo#1688]
### Discussed in https://github.com/orgs/WalletConnect/discussions/1528

<div type='discussions-op-text'>

<sup>Originally posted by **mobilestar0223** October 12, 2022</sup>
I'm using below code:
```
const connector = useWalletConnect();
await connector.connect();
console.log('connected: ', connector.connected);
```

Wallet is connected correctly, but it prints **"connected: false"** on the console.
Is the expected, and if yes, what is the reason?
</div>

**Comment by ManueleNolli** [comment]
I also have this error

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
