### ISSUE TITLE
[v2.1.4] Throw error when receive request

### ISSUE THREAD

**Issue by vuletiki** [WalletConnect/walletconnect-monorepo#1690]
**Describe the bug**
On Dapp, I send a request. Then I open the wallet and init sign client.
- Expect: Receive request on wallet
- Result: Throw error on wallet, and Dapp too.

Error on wallet
```
{context: "core"} 
{context: "core/pairing"} 
{message: "Unsupported wc_ method. wc_sessionRequest", code: 10001}
```
This issue happen randomly.

**SDK Version (if relevant)**
 - Client: Web
 - Version 2.1.4

**Screenshots**
<img width="544" alt="Screen Shot 2022-11-30 at 19 36 33" src="https://user-images.githubusercontent.com/27724400/204798939-76a552d9-8671-4147-afbc-cf28df9f4bee.png">

**Additional context**
Here is the relevant code that I am using to init the client on wallet:
```
import SignClient from '@walletconnect/sign-client';
await SignClient.init({
    logger: 'debug',
    projectId: PROJECT_ID,
    relayUrl: RELAY_URI,
    metadata: {
      name: '...',
      description: '...',
      url: '...',
      icons: [ ],
    },
})
```

**Comment by finessevanes** [comment]
Hey @vuletiki, do you have a project repo I can test?

**Comment by vuletiki** [comment]
> Hey @vuletiki, do you have a project repo I can test?

Thank for reply, but I cannot provide source code.

**Comment by finessevanes** [comment]
@vuletiki are you still experiencing this issue on the latest SDK version?

**Comment by bkrem** [comment]
Thanks for your initial report here @vuletiki 🙏 

This was fixed in back in https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.2.1 but hadn't been followed up on here. Closing.
