### ISSUE TITLE
web3-provider rpc spam

### ISSUE THREAD

**Issue by samuveth** [WalletConnect/walletconnect-monorepo#1691]
**Describe the bug**
After the user connects using WalletConnect on snapshot.org the RPC gets requested every few seconds without a clear reason. This is creating extra load on our PRC endpoint and slowing it down `rpc.snapshot.org/1`

**SDK Version (if relevant)**
`@walletconnect/web3-provider": "^1.8.0"`

**To Reproduce**
See https://github.com/snapshot-labs/snapshot/issues/3362

**Expected behavior**
The RPC should not get requested again and again without the user doing any actions on the site.

**Comment by ganchoradkov** [comment]
hey @samuveth, what requests are made exactly? 
Usually, the provider is querying for the latest block data which is relevant information and changes every few seconds

**Comment by bonustrack** [comment]
@ganchoradkov The requests sent are using methods "eth_getBlockByNumber" and "eth_blockNumber". Any reason WC request this every few seconds? How is this being used? Can't this be requested only when needed, like when a new action happen?

**Comment by finessevanes** [comment]
Hey, it looks like you're using the old v1 SDK. Please migrate to v2 and v1 is no longer maintained. https://docs.walletconnect.com/2.0/advanced/migrating-from-v1.0
