### ISSUE TITLE
web3-provider:44 Uncaught Error: PollingBlockTracker - encountered an error while attempting to update latest block: undefined

### ISSUE THREAD

**Issue by xpluscal** [WalletConnect/walletconnect-monorepo#1706]
**Describe the bug**
Using web3-provider v.1.8.0 there seems to be a PollingBlockTracker error causing High CPU load

**SDK Version (if relevant)**
 - Client: web3-provider
 - Version 1.8.0

**Comment by xpluscal** [comment]
<img width="512" alt="Screenshot 2022-12-03 at 09 07 23" src="https://user-images.githubusercontent.com/3706722/205398284-e1de6ba3-7e49-4eb0-af8d-7dc75b55a9c1.png">

**Comment by xpluscal** [comment]
Is there an update on this?

**Comment by tiagoscruz** [comment]
I am facing the same issue on a react-native project running **@walletconnect/react-native-dapp**

```
await connector.connect({});

// no problems here, I am able to authenticate with Metamask app

const provider = new WalletConnectProvider({
        rpc: {
          137: 'wss://polygon-rpc.com',
        },
        chainId: 137,
        connector: connector,
        qrcode: false,
      });

// no problems up to here neither

await provider.enable();

// after running the above method, the same error that @xpluscal metioned  is being triggered on an endless loop.
```

**Comment by YerimMoral3s** [comment]
any updates on this??

**Comment by satyatechno** [comment]
> I am facing the same issue on a react-native project running **@walletconnect/react-native-dapp**
> 
> ```
> await connector.connect({});
> 
> // no problems here, I am able to authenticate with Metamask app
> 
> const provider = new WalletConnectProvider({
>         rpc: {
>           137: 'wss://polygon-rpc.com',
>         },
>         chainId: 137,
>         connector: connector,
>         qrcode: false,
>       });
> 
> // no problems up to here neither
> 
> await provider.enable();
> 
> // after running the above method, the same error that @xpluscal metioned  is being triggered on an endless loop.
> ```

I am also facing the same issue is there any updates please share 
Thanks

**Comment by SaTiSH-K-R** [comment]
Any update or work around for this issue?

**Comment by finessevanes** [comment]
Hey all, look like you're all using v1, please migrate to v2: https://docs.walletconnect.com/2.0/advanced/migrating-from-v1.0
