### ISSUE TITLE
Wallet Connect v2 Sign API Problem and Goal

### ISSUE THREAD

**Issue by Luzzotica** [WalletConnect/walletconnect-monorepo#1709]
I see that the Sign API for wallet connect v2 states a pretty significant problem regarding wallet connect v2.

I'm curious what the discussion surrounding this is, what the current options are, and if a conclusion has already been made and the docs just haven't been updated.

I'm looking into creating a dart (flutter) SDK and I'd like to know if this problem has been resolved.

**Comment by chadyj** [comment]
Hey @Luzzotica what is the problem you are referring to?
