### ISSUE TITLE
v1; MetaMask Provider; Can't catch `onChainChanged` event

### ISSUE THREAD

**Issue by TimC0de** [WalletConnect/walletconnect-monorepo#1721]
### Discussed in https://github.com/orgs/WalletConnect/discussions/1712

<div type='discussions-op-text'>

<sup>Originally posted by **TimC0de** December  5, 2022</sup>
I'm integrating Web3Modal v1 (Tried to connect v2, but a lot of issues with MetaMask, probably because MetaMask doesn's support v2 yet). When connecting to wallet via WalletConnect - provider events (such as onChainChanged, onAccountsChanged) work. When connecting via MetaMask (on desktop) - those events don't work. What may be the problem?

P.S. As I understood there is no way to configure MetaMask via `providerOptions`. Can it be the issue?

Thank you for response in advance.</div>

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version  :)
