### ISSUE TITLE
React native - Bug in IOS AppRegisterComponet with V1

### ISSUE THREAD

**Issue by phanvungoc96** [WalletConnect/walletconnect-monorepo#1730]
**Describe the bug**

**SDK Version (if relevant)** 1.8.0
 - Client: [e.g. JS, Swift, Kotlin] 

**To Reproduce**
1. Use "@walletconnect/react-native-dapp": "1.8.0", RN: 0.69.4, react: 18.0.0
2. Then I register component in Index.js 
![image](https://user-images.githubusercontent.com/73456278/206214295-3d508504-576b-4320-99f9-8ff33b7424e2.png)
3. Example I see this work with Expo not Bare, so I don't know how to Fix that, It work well on Android, but IOS get error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/73456278/206213881-3d5030ab-01b3-45b2-a90c-9df1e05d26e9.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] ip 13
 - OS: [e.g. iOS8.1] 12.4

**Additional context**

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
