### ISSUE TITLE
Sign and Auth client not working, also in Demo examples

### ISSUE THREAD

**Issue by jordigagomerino** [WalletConnect/walletconnect-monorepo#1743]
**Describe the bug**
I'm trying to implement de AuthClient and SignClient and connect with Metamask or Rainbow Wallet. With both it fails, it just scan de QR and nothing happens. I though it was my code but when I tried it in the demo the same happens with both demos and wallets. Maybe it is a Metamask and Rainbow problem. Anyone had the same problem?

**SDK Version (if relevant)**
 - Client: JS
 - Version 2.1.4

**To Reproduce**
1. Go to Sign and Auth demo
2. Connect your Metamask or Rainbow Wallet
3. See nothing happens

**Expected behavior**
Connect and get events 

**Screenshots**
I don't have any screenshots it's only the qr showing

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Chrome
 - Version 108.0.5359.94

**Smartphone (please complete the following information):**
 - Device: IPhone 13 Pro Max
 - OS: 16.1.2
 - Wallet: MetaMask and Rainbow
 - Version: 5.12.0 and. 1.8.2 respectively

**Comment by chadyj** [comment]
Hey thanks for submitting this report.

As of today, Rainbow and Metamask don't yet support v2, so your report is expected behavior.

You can try out the demos using our sample wallets https://github.com/WalletConnect/web-examples#readme

**Comment by jordigagomerino** [comment]
Ok! Thank you for your answer. I will use V1 for now.
