### ISSUE TITLE
Send non ethereum

### ISSUE THREAD

**Issue by Vadim51515** [WalletConnect/walletconnect-monorepo#1752]
### Discussed in https://github.com/orgs/WalletConnect/discussions/1751

<div type='discussions-op-text'>

<sup>Originally posted by **Vadim51515** December 12, 2022</sup>
Hi, using the trust app and @walletconnect, I was able to transfer ether. Can I transfer another currency in the same way? (e.g. usdt )</div>

**Comment by Selivaniuk** [comment]
Same +1

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version  :)
