### ISSUE TITLE
SignClient.init failed (React-Native) WalletConnectV2

### ISSUE THREAD

**Issue by antiergit** [WalletConnect/walletconnect-monorepo#1753]
**Describe the bug**
When try to Create instance  SignClient.init in React-Native IOS getting error: [TypeError: Object.fromEntries is not a function. (In 'Object.fromEntries(e.entries())', 'Object.fromEntries' is undefined)]
Note: It working fine on React-Native Android

**SDK Version (if relevant)**
"react-native": "^0.64.2"
"@walletconnect/sign-client": "^2.1.3"
"@walletconnect/react-native-compat": "^2.1.3"

 I have done import "@walletconnect/react-native-compat"; on my App.js file.

Here is my code:

import SignClient from "@walletconnect/sign-client";

             const signClient = await SignClient.init({
                        projectId: "‹project_id>",
                        metadata: {
                            name: "MyApp",
                            description: "MyApp",
                            url: "#",
                            icons: ["https://walletconnect.com/walletconnect-logo.png"],
                        },
                    });
                    console.log("connect get_V2", signClient)

![Screenshot 2022-12-12 at 5 00 03 PM](https://user-images.githubusercontent.com/53866143/207040151-f47198f2-1a0c-49c7-8284-10eb9ec62e7d.png)

![Screenshot 2022-12-12 at 5 01 14 PM](https://user-images.githubusercontent.com/53866143/207040225-57d1b3ed-e7ab-4ec4-ac00-42fce2ec622a.png)

**Comment by ganchoradkov** [comment]
Hey @antiergit, thanks for the report!
 
do you have a repo where we can reproduce the issue?
Seems like `react-native` bundling/building issue

**Comment by a0979470582** [comment]
(for RN Platform) 這是相容性的問題，可以參考這個做法：
(This is a compatibility issue, you can refer to this approach:)
https://stackoverflow.com/questions/68691790/typeerror-object-fromentries-is-not-a-function

**Comment by a0979470582** [comment]
(for RN Platform) and Maybe your next step will occur another issue: `ReferenceError: Can't find variable: globalThis`, you can add this code in shim.js: 
```
function defineGlobalThis() {
  if (typeof globalThis === 'object') return;
  Object.defineProperty(Object.prototype, '__magic__', {
    get: function () {
      return this;
    },
    configurable: true, // This makes it possible to `delete` the getter later.
  });
  __magic__.globalThis = __magic__;
  delete Object.prototype.__magic__;
} 
defineGlobalThis();

```
This works for me.
