### ISSUE TITLE
Handle deeplink Android

### ISSUE THREAD

**Issue by stosabon** [WalletConnect/walletconnect-monorepo#1768]
**Describe the bug**
Not possible to handle deeplink in Android Wallet to create session without NavigationComponent.

**To Reproduce**
1. Try to handle deeplink in any wallet app without navigation component and using `deeplink`. Just using a way with `android:scheme` and `android:host`
2. Deeplink not handled

**Expected behavior**
Expected to handle deeplink.

**Additional context**
The problem may be is because your deeplink scheme doesn't match expected. (example: `app://url`)

**Comment by chadyj** [comment]
@stosabon Can you please use all the issue template fields? It makes it easier for us to help you.
In particular, include the SDK version.

**Describe the bug**
A clear and concise description of what the bug is.

**SDK Version (if relevant)**
 - Client: [e.g. JS, Swift, Kotlin]
 - Version [e.g. 22]


**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by stosabon** [comment]
@chadyj edited description. There are no any device specific cases. It is more about kotlin library implementation

**Comment by chadyj** [comment]
@stosabon What kotlin library?
Unfortunately can't help you unless you give us info such as SDK version.

**Comment by stosabon** [comment]
@chadyj BOM 1.0.1 Sign 2.3.1
You have docs about mobile linking [here](https://docs.walletconnect.com/2.0/kotlin/guides/mobile-linking)
But the problem is that android app can't handle this type of deeplink without NavigationComponent

**Comment by stosabon** [comment]
Example. No idea what scheme and host should be provided to handle deeplink

**Comment by stosabon** [comment]
<img width="595" alt="ac375410-e457-497f-9244-2aca25abf389" src="https://user-images.githubusercontent.com/27279157/207970556-ecc035f7-3b79-46bf-b446-e82097e48148.png">

**Comment by jakubuid** [comment]
Hey, @stosabon, whether you use NavComponent or not is no different.
From Dapp we always expose URI in the following structure:
`wc:090bfe9ca8fd566aa482eff02b3bedba73503278df8be9a5cc14f96104459aae@2?relay-protocol=irn&symKey=5b590af1c5d2c5860312406e56f8930931ad8f105037849d2d9cc332dd60c0f8`

So to trigger your wallet's activity, you could transform the wc: prefix to wc://  and send the URI with intent. Therefore, you can create your scheme. We don't control it. 

Also, to handle session requests with deep links, we introduced a redirect field in AppMetaData. It enables you to provide your custom scheme that triggers communication between a Dapp and a wallet over an active session.

**Comment by stosabon** [comment]
@jakobuid If you always expose `wc:` from dApp, it means that I can't handle it in my app because when I want to create session via deeplink I just click the button in dApp and get URI with structure that you mentioned above without my app specific redirect field, because at this point dApp don't know about my app at all. But this scheme is not supported without NavigationComponent

**Comment by stosabon** [comment]
The main problem is because in example you provided 
```
            <deepLink
                app:action="android.intent.action.VIEW"
                app:uri="wc:/{topic}@2" />
```
It works because NavComponent doesn´t require scheme or host, just uri pattern
And i don't see any way to make the same without NavComponent

**Comment by jakubuid** [comment]
I've used a simplification in my previous comment. Sorry for that.

I meant that Sign SDK always exposes pairing URI in the `wc:` format.

It's up to Dapp's developers how they handle deep-linking communication and the preferred format. It's not related our SDK. 

On our Kotlin Dapp sample, we've chosen to integrate this flow with NavComponent.

If you don't use NavComponent but still want to test communication with your wallet via a deep link, go to `PairingGenerationDialogFragment` in the `com.walletconnect.dapp.ui.connect.pairing_generate` package and change line `34` where we prepare deep linking pairing URI:

` val deeplinkPairingUri = pairingUri.replace("wc:", "wc:/")` to
` val deeplinkPairingUri = pairingUri.replace("wc:", "wc://")`
or whatever format you prefer.

I hope that helps!

**Comment by stosabon** [comment]
@jakobuid But I thought that idea is to make wallet accessible via any dapp (it is possible with qr code), or I am not right?
If any dapp use their own custom scheme it break this logic.

**Comment by jakubuid** [comment]
@stosabon fair point 💯 
We want to support as many wallets as possible, even though it's an example Dapp. 
I'll make sure to provide the above fix in the following week to unblock you.

Thanks for pointing this out 🙏

**Comment by stosabon** [comment]
@jakobuid Please check how deeplinks work (take a look at `scheme` and `host`) [here](https://developer.android.com/training/app-links/deep-linking)
This way anytime user will click deeplink, Android system will provide all wallets that could handle it

**Comment by jakubuid** [comment]
Hey, [PR](https://github.com/WalletConnect/WalletConnectKotlinV2/pull/537) is up. With this change, when you register your wallet's intent filter with ` <data android:scheme="wc" />` the deep link will be received.
