### ISSUE TITLE
Crash when deleting wallet connect session in wallet

### ISSUE THREAD

**Issue by WyattMufson** [WalletConnect/walletconnect-monorepo#1772]
**Describe the bug**
When I connect a dApp with the [Wallet Connect React Wallet](https://react-wallet.walletconnect.com) and delete the session in the wallet (in the sessions page), the dApp crashes. The call stack is:
```
Uncaught (in promise) Error: No matching key. keychain: 5aaaa520505c6774e5c3c7355f9a577caebe6b79aeb133af252eb7a4f1073a76
    at lt.get (index.es.js:1:16104)
    at dt.getSymKey (index.es.js:1:18645)
    at dt.encode (index.es.js:1:17891)
    at je.sendError (index.es.js:1:9128)
    at je.onSessionDeleteRequest (index.es.js:1:14521)
```

I have an event subscriber on my UniversalProvider (`_provider` in the code below) that never gets called:
```
// Subscribe to session delete
    _provider.on(
      'session_delete',
      ({ id, topic }: { id: number; topic: string }) => {
        console.log('session_deleted', id, topic);
      }
    );
```

The only place that the session is getting deleted is in the React wallet, not the dApp.

**SDK Version (if relevant)**
 - Client: TypeScript
 - SDK:
   - "@web3modal/standalone": "^2.0.0-beta.9"
   - "@walletconnect/universal-provider": "^2.1.4"

**To Reproduce**
1. Initializing a UniversalProvider
2. Calling connect
3. Initializing an instance of Web3Modal
4. `openModal` on the Web3Modal
5. Copy+Paste URI into [Wallet Connect React Wallet](https://react-wallet.walletconnect.com)
6. Successfully connect wallet to dApp
7. Delete session in the sessions page in wallet
8. Crash

**Expected behavior**
The session should be deleted and the `'session_delete'` handler should be called.

**Screenshots**
<img width="460" alt="Screen Shot 2022-12-15 at 4 46 39 PM" src="https://user-images.githubusercontent.com/10342911/207975590-998e57d8-1356-4fdd-8ff6-257e76c741a5.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by 10xSebastian** [comment]
+1

**Comment by 10xSebastian** [comment]
+1
```
"@walletconnect/core": "^2.2.1",
"@walletconnect/sign-client": "^2.2.1",
```

```
 const signClient = await SignClient.init({ projectId: window._walletConnectProjectId });
      
  signClient.on("session_event", ({ event }) => {
    console.log('EVENT', event)
  })

  signClient.on("session_update", ({ topic, params }) => {
    console.log('TOPIC???', topic)
    // const { namespaces } = params;
    // const _session = signClient.session.get(topic);
    // // Overwrite the `namespaces` of the existing session with the incoming one.
    // const updatedSession = { ..._session, namespaces };
    // // Integrate the updated session state into your dapp state.
    // console.log('SESSION UPDATE', updatedSession)
  });

  signClient.on("session_delete", () => {
    console.llg("DELETE SESSION")
  });

  const { uri, approval } = await signClient.connect({
    requiredNamespaces: {
      eip155: {
        methods: ["eth_sign"],
        chains: ["eip155:1"],
        events: ["accountsChanged", "chainChanged"],
      },
    },
  });

  await connect({ uri })
  await approval()
  console.log('APPROVED!')
  ```

**Comment by Jake-Mulhern** [comment]
Same issue here

**Comment by ggaabe** [comment]
I'm running into the same issue as well; web3wallet 1.1.1 and universal-provider 2.3.2

**Comment by AndonMitev** [comment]
Same issue here using:

```
  "@walletconnect/core": "2.4.0",
    "@walletconnect/react-native-compat": "2.4.0",
    "@walletconnect/sign-client": "2.4.0",
    "@walletconnect/types": "2.4.0",
    "@walletconnect/web3wallet": "1.1.1",
```

**Comment by AndonMitev** [comment]
Tried with `web3wallet: 1.2.0`, still persist :(

**Comment by 0xApotheosis** [comment]
Same issue, using `web3wallet` `1.2.0`.

If I try to disconnect all topics, I first get my active topics, and then attempt to call `disconnectSession()` with each of them:

```ts
const activeTopics = Object.values(web3wallet.getActiveSessions()).map(session => session.topic)
for await (const topic of activeTopics) {
  try {
    await web3wallet.disconnectSession({ topic, reason: getSdkError('USER_DISCONNECTED') })
  } catch (e) {
    throw new Error(`Error disconnecting session: ${e}, topic: ${topic}`)
  }
}
```

Then I get:

```
Uncaught (in promise) Error: Error disconnecting session: Error: No matching key. 
keychain: ${some-topic}
```

**Comment by ggaabe** [comment]
Not sure if this helps but I also noticed that wagmi's solution to this is they just have a manual patch / catch when this error occurs. But I don't think this actually solves anything, especially when the error occurs when trying to connect:

https://github.com/wagmi-dev/references/blob/main/packages/connectors/src/walletConnect.ts#L164

**Comment by Anmol-Dhiman** [comment]
Is there any solution available for this, I'm getting the same issue when i'm using the simple disconnect option of web3button, i'm using @web3modal/react: ^2.6.2

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/82818771/9d5a4486-e398-4c60-abc6-fa05a38c68b7)

**Comment by UryonBlade** [comment]
I probably figured out this issue. 

Wallet connect send to wagmi the session id after I try to sign a message. 


```
useEffect(() => {
   if (address && isConnected) {
      signMessage(message)
   }
}, [address, isConnected])
  ```
  
  The code above makes Metamask crash. But if you try to do something like:
  
  ```
useEffect(() => {
   if (address && isConnected) {
      setTimeout(() =>  signMessage(message), 1000)
   }
}, [address, isConnected])
  ```
  
this should work. 

Note: this is not a best practice obviously, and I will search another way to wait for the connected event from wallet connect. If I'll be able to figure it out i will update the comment

**Comment by evan-metaseed** [comment]
I had issues related to this with local storage variables stored in my browser. Clearing them programmatically fixed this.

**Comment by jcai** [comment]
@evan-metaseed how to fix this issue?

**Comment by evan-metaseed** [comment]
in javascript you can clear local storage by using localStorage.clear()
