### ISSUE TITLE
Shared core instance example error

### ISSUE THREAD

**Issue by rkreutzer** [WalletConnect/walletconnect-monorepo#1773]
**Describe the bug**
Attempting to use the example for Shared Core Instance in the docs gives "Type 'Core' is not assignable to type 'ICore'." error when doing AuthClient.init. 

**SDK Version (if relevant)**
     "@walletconnect/auth-client": "^1.0.1",
    "@walletconnect/client": "^1.7.8",
    "@walletconnect/core": "^2.1.4",
    "@walletconnect/legacy-types": "^2.0.0-rc.0",
    "@walletconnect/sign-client": "^2.1.4",
    "@walletconnect/types": "^2.1.4",

**To Reproduce**
1. Copy example code from https://docs.walletconnect.com/2.0/javascript/guides/shared-core into new file. VisualCode shows this error even before building.

**Comment by ganchoradkov** [comment]
Hey @rkreutzer thanks for report. 
That is happening due to your `Auth` instance requiring an older `core` version.

We just shipped `Auth v2.0.0` and you shouldn't have this issue

**Comment by rkreutzer** [comment]
I updated to auth-client 2.0.0 and still have same issue. Here is the full error in VSCode:

Type 'Core' is not assignable to type 'ICore'.
  The types of 'opts.keychain.core.relayer.provider' are incompatible between these types.
    Type 'import("d:/rktechworks/idpocket/node_modules/@walletconnect/jsonrpc-types/dist/cjs/provider").IJsonRpcProvider' is not assignable to type 'import("d:/rktechworks/idpocket/node_modules/@walletconnect/auth-client/node_modules/@walletconnect/jsonrpc-types/dist/cjs/provider").IJsonRpcProvider'.
      Property 'setConnection' is protected but type 'IJsonRpcProvider' is not a class derived from 'IJsonRpcProvider'.ts(2322)
client.d.ts(29, 9): The expected type comes from property 'core' which is declared here on type 'Options'

**Comment by bel0v** [comment]
I tried to follow the WalletKit installation example now and got a similar TS issue about the walletconnect core not being compatible with walletKit ICore option.
