### ISSUE TITLE
Duplicated Autonomy apps on page 13

### ISSUE THREAD

**Issue by anhnguyenbitmark** [WalletConnect/walletconnect-monorepo#1774]
**Describe the bug**
I found that there are two Autonomy apps in the wallet.json API from the registry with these following ids:
- `30edc47c24de2727a86d50ba88c3516db28c0494a7c5f0b127e4329e855c6840`
- `f593f4eb9755ff047681a37ebc46706e0e915cf1c2fe0102f5ae47c9f6aa4082`

`f593f4eb9755ff047681a37ebc46706e0e915cf1c2fe0102f5ae47c9f6aa4082` seems to be the one we submitted via the Dashboard.
Could you help to check and remove the duplicated item there?

**To Reproduce**
1. Browse the wallets on the Mobile view
2. Click on page 13
3. There are two Autonomy there

**Expected behavior**
Only one Autonomy app is shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/24427942/208015482-d2605664-a642-4278-8147-a5d0b71d78d9.png)

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS16.1
 - Browser Safari

**Additional context**
I'm from the Autonomy team, who submitted the Autonomy app.

**Comment by bkrem** [comment]
Hi @anhnguyenbitmark,

Thanks for reporting the duplication.

So both of these seem to be registered to Bitmark addresses:
* `30edc47c24de2727a86d50ba88c3516db28c0494a7c5f0b127e4329e855c6840` - thuyen@bitmark.com
* `f593f4eb9755ff047681a37ebc46706e0e915cf1c2fe0102f5ae47c9f6aa4082` - apps@bitmark.com

Just confirming here that we should regard `30edc47c24de2727a86d50ba88c3516db28c0494a7c5f0b127e4329e855c6840` as the duplicate and remove it?

**Comment by anhnguyenbitmark** [comment]
@bkrem Yes, please remove this one: `30edc47c24de2727a86d50ba88c3516db28c0494a7c5f0b127e4329e855c6840`.
Sorry for late reply.

**Comment by bkrem** [comment]
Done ✅
