### ISSUE TITLE
[Sign] Implement optional sessionRequest expiry

### ISSUE THREAD

**Issue by bkrem** [WalletConnect/walletconnect-monorepo#1794]
**Describe the solution you'd like**

* Implement based on the agreed spec: https://github.com/WalletConnect/walletconnect-docs/pull/315/files
* Ensure we surface this in the top-level API in an ergonomic way (see Additional context section for an example)

**Additional context**
- Previous discussion and proposal for basically this in the context of JS Sign specifically: #1739

**Comment by bkrem** [comment]
Creating a dedicated implementation issue for this separate from the discussion in #1739

@ganchoradkov assigning you by default here, but let me know if we need to dig deeper on this before getting into it 👍

**Comment by ganchoradkov** [comment]
Merged & released
https://github.com/WalletConnect/walletconnect-monorepo/pull/1851
