### ISSUE TITLE
ethereum-provider: mismatch between `chainId` and `rpcUrl`

### ISSUE THREAD

**Issue by alexdupre** [WalletConnect/walletconnect-monorepo#1805]
**Describe the bug**

In certain situations the `rpcUrl` used by the underlying http connection doesn't match the currently selected `chainId`, with the result that the wallet is working on a chain, while other RPC calls are sent on a different one.

The issue has been verified with the 1.8.0 version, but it seems to be worsened in the 2.0 branch.

**SDK Version**
 - ethereum-provider
 - 1.8.0 and 2.1.5

**Expected behavior**

My understanding is that the `http` connection should always match the selected `chainId`.

The `http` connection is instantiated in the constructor of the provider and re-instantiated after a `chainChanged` event. It seems there are two issues though:

1) [verified in 1.8.0 and likely present in 2.1.5, not sure if there is a co-responsibility of the wallet]: during the pairing process and session creation, the user can select a different network, compared to the preferred/first one. At this point no `chainChanged` event is generated and the `http` connection is still pointing to the `chainId` selected in the costructor. This can be easily verified using the Bifrost wallet.

2) [likely present in 2.1.5]: while in version 1.8.0 the `http` variable was correctly re-assigned on `chainChanged` events (https://github.com/WalletConnect/walletconnect-monorepo/blob/1.8.0/packages/providers/ethereum-provider/src/index.ts#L115), that doesn't seem to happen anymore in version 2.0 (https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/providers/ethereum-provider/src/index.ts#L193 and https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/providers/ethereum-provider/src/index.ts#L213-L214), with the result that it'll continue to point to the url of the first network passed in the constructor

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
