### ISSUE TITLE
handling sessions when user closes browser / website

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/walletconnect-monorepo#1816]
**What I want to achieve:**

1. User logs into the website and connects a wallet.
2. User leaves the website (closes current browser) but the session is still running.
3. User gets back to the website while session is running.
 I want to be able to manage that session with the SignClient object the same way I would be able to as in stage 1.

**What I've tried:**

I was abled to get user's account and chain id using `JSON.parse(window.localStorage.getItem('wc@2:client:0.3//session')` 

so if the user comes back to the website and he's still connected I can take this information from local storage.

I also noticed that if the user disconnects from trust wallet while the website is closed, once the website is opened again there's gonna be a delay before the local storage is cleared. How can I prevent from saving the states before the session is closed in local storage?

this way I can get the user's account and chain id from local storage, but I'm not abled to use SignClient object to disconnect from that session, I'm also not abled to use it as a provider with ethers js.

in case this is not ment to happen, what's the reason of saving the sessions in localstorage? would it be safe if I use `window.localStorage.clear()` when I start my app?

**Comment by ganchoradkov** [comment]
Hey @glitch-txs, you don't need to query localStorage directly.
When your app is started, you can query the active sessions with `this.session.getAll()` and get the users account data.

To your second question: 
When one party disconnects from a session while the other is offline, the session will be removed automatically when the offline party comes online. 
You should be listening to the event `session_delete` to be notified when other party has disconnected to update your app appropriately

**Comment by glitch-txs** [comment]
thanks, how do I update the signClient to a current session? Because I can't use it as a provider when reloading the website.

**Comment by ganchoradkov** [comment]
The sign-client has internal storage so when you restart your app, the sessions are restored automatically

**Comment by glitch-txs** [comment]
It doesn't work on this example, I took it from the monorepo as well as reading the docs.

I'm using the standalone version together with the Universal-provider package to wrap the signClient object and use it with ethers.js

When I try to call the smart contract it will fail if the page was reloaded

https://github.com/glitch-txs/walletconnect-standalone-ethers-integration/blob/main/pages/index.tsx

Thanks

**Comment by ganchoradkov** [comment]
I'm seeing you're clearing the localstorage when the app is loaded
`    window.localStorage.clear()
`
This wipes the sign-client storage and makes it impossible to restore its state

**Comment by glitch-txs** [comment]
yes that's is me just testing, but without that line I'm getting the same result, sorry about that

it does make sense though, what if there are many sessions? which I know is possible as from reading the localStorage

**Comment by glitch-txs** [comment]
Was my code! Sorry, thanks for your help I appreciate it
