### ISSUE TITLE
Support for Susono EVM Network

### ISSUE THREAD

**Issue by AndonMitev** [WalletConnect/walletconnect-monorepo#1842]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC: `http://142.93.170.103:9650/ext/bc/2VsZe5DstWw2bfgdx3YbjKcMsJnNDjni95sZorBEdk9L9Qr9Fr/rpc`
2. **namespaces**: eip:155
3. **chains**: eip155:13812

**Avalanche subnet**
This is avalanche subnet

**Comment by bkrem** [comment]
Hi @AndonMitev,

Some questions:
* Why is the JSON-RPC endpoint a bare IP?
* Are you aware of wallets actively developing for Susono?

**Comment by AndonMitev** [comment]
Hey @bkrem, Sorry RPC url was updated, here is the new one:

JSON-RPC: `https://gateway.opn.network/node/ext/bc/2VsZe5DstWw2bfgdx3YbjKcMsJnNDjni95sZorBEdk9L9Qr9Fr/rpc`

Well we are the first one because this is our subchain on Avalanche so i'm not aware if there are any others

**Comment by AndonMitev** [comment]
Yes, we have integrated wallet connect v2 in our wallet and plug our Susono network in https://react-app.walletconnect.com/ which is evm compatible btw, avalaunch subchain and is working as expected, so how we can submit our chain and wallet for support :P
