### ISSUE TITLE
"@walletconnect/web3-provider": latest.    issue with package ..pipeline failing and local working fine..

### ISSUE THREAD

**Issue by talararavikumar** [WalletConnect/walletconnect-monorepo#1846]
### Discussed in https://github.com/orgs/WalletConnect/discussions/1845

<div type='discussions-op-text'>

<sup>Originally posted by **talararavikumar** January  6, 2023</sup>
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/ethereumjs/ethereumjs-abi.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
</div>

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version  :)
