### ISSUE TITLE
search input not work in ui-modal-component

### ISSUE THREAD

**Issue by kringt06** [WalletConnect/walletconnect-monorepo#1848]
**Describe the bug**
search input not work in ui-modal-component
当在主流弹窗组件中触发walletconnect弹窗的时候，会出现input无法点击的bug

**SDK Version (if relevant)**
 - Client: JS
 - Version [@walletconnect/ethereum-provider: 1.8]

**To Reproduce**
1. 渲染一个弹窗组件chakra-ui modal（组件需要支持点击弹窗外区域会关闭弹窗）；
2. 再弹窗组件中写一个按钮去触发walletconnect登录钱包；
3. 点击tab，点击input search；

**Expected behavior**
正常

**Additional context**
原因是因为这类弹窗组件会监听click事件，去实现检测点击区域，这会和walletconnect的点击事件冲突，导致walletconnect input无法捕获正确的事件

**Comment by rick897887** [comment]
I'm having the same problem. I'm using a Chakra-UI Modal to display a list of Wagmi.sh connectors, including Wallet Connect, and when the Wallet Connect modal pops-up the search function doesn't register the click and doesn't receive focus.

**Comment by TyrantKingBen** [comment]
> I'm having the same problem. I'm using a Chakra-UI Modal to display a list of Wagmi.sh connectors, including Wallet Connect, and when the Wallet Connect modal pops-up the search function doesn't register the click and doesn't receive focus.

You can set `trapFocus` to `false` to prevent this with Chakra UI. See https://chakra-ui.com/docs/components/modal#prevent-focus-trapping.

**Comment by rick897887** [comment]
I tried trapFocus="false" and the problem still persists.

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
