### ISSUE TITLE
Add Waves blockchain

### ISSUE THREAD

**Issue by msmolyakov** [WalletConnect/walletconnect-monorepo#1849]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
  https://docs.waves.tech/en/waves-node/node-api/
2. Write a [CASA namespace](https://github.com/ChainAgnostic/namespaces) spec.
  **GitHub Link:** https://github.com/ChainAgnostic/namespaces/pull/49
3. **namespaces**:
   _\*known chain namespaces (e.g. eip:155 for Ethereum/EVM-based chains, solana, ...)_
  waves
4. **chains**:
   _\*known chains, where the primary key is a compound key composed of namespace + reference (e.g. ETH mainnet is eip155:1)_
  `waves:087` — mainnet
  `waves:084` — testnet
  `waves:083` — stagenet
5. Submit this template.

**Additional context**
We are the [Keeper Wallet](https://keeper-wallet.app) team and this is the first wallet for Waves that supports the WalletConnect protocol.

**Comment by bkrem** [comment]
Hi @msmolyakov,

Thanks for the proposal to add Waves. A couple of notes for the request:

> Write a [CASA namespace](https://github.com/ChainAgnostic/namespaces) spec.
> waves

Should this be a link?

>chains:
> waves:87
> waves:84

Which one is testnet and which one mainnet?

**Comment by msmolyakov** [comment]
Hi @bkrem, we're [adding Waves blockchain](https://github.com/ChainAgnostic/namespaces/pull/49) to the ChainAgnostic namespaces.

`waves:87` is mainnet and `waves:84` is testnet. Updated the description.

**Comment by msmolyakov** [comment]
Hi @bkrem, I think we are ready for the final PR review and merge. Please check. Any questions or suggestions?

**Comment by bkrem** [comment]
Thanks for the updates and creating the CASA namespace spec. Added `waves` namespace and the indicated chains to WalletConnect Cloud 👍
