### ISSUE TITLE
Dapps can fake the url shown to the user on the wallet side

### ISSUE THREAD

**Issue by sirasistant** [WalletConnect/walletconnect-monorepo#1864]
**Describe the bug**
When performing Client.init on the dapp side, the dapp can pass these parameters:
```
import SignClient from "@walletconnect/sign-client";

const signClient = await SignClient.init({
  projectId: "<YOUR_PROJECT_ID>",
  // optional parameters
  relayUrl: "<YOUR RELAY URL>",
  metadata: {
    name: "Example Dapp",
    description: "Example Dapp",
    url: "#",
    icons: ["https://walletconnect.com/walletconnect-logo.png"],
  },
});
```
These parameters include the dapp URL. The metadata will get to the wallet side on the [wc_sessionpropose](https://github.com/WalletConnect/walletconnect-specs/blob/main/sign/rpc-methods.md#wc_sessionpropose) event, without any validation on the URL. It's normal behaviour for a wallet to use this URL from the dapp metadata to inform the user of who the requester of the connection or signature is. If this URL can be changed to whatever other URL desired by the dapp developer, it will allow them to show their connections or transactions as if they came from another dapp trusted by the user (like Uniswap).
Should the relay nodes be validating the URL in the metadata against the `Origin` header of the http requests?

**SDK Version (if relevant)**
 - Client: JS
 - Version 2.2.0

**To Reproduce**
1. Clone the [walletconnect examples repo](https://github.com/WalletConnect/web-examples)
2. Add your walletconnect project id in the .env.local for the projects `react-wallet-v2` and `react-dapp-v2`
3. Modify the `react-dapp-v2` code `ClientContext.tsx` to:
```
        logger: DEFAULT_LOGGER,
        relayUrl: relayerRegion,
        projectId: DEFAULT_PROJECT_ID,
        metadata: {
          name: "Trust me, I'm Uniswap",
          description: "A very trusted site",
          url: 'https://app.uniswap.org',
          icons: [],
        },
```
4. Launch both sites by using `npm i && npm run dev` on both `react-wallet-v2` and `react-dapp-v2`
5. Connect the dapp to the wallet, and ask for a signature with `eth_sign`

**Expected behavior**
The wallet should not show a URL that is different from the one the connection initated from.
Note: this works also outside of localhost, try using a cloudflare tunnel to get the example dapp deployed to a domain with https and the issue will still be there.

**Screenshots**
![image](https://user-images.githubusercontent.com/5372114/212073358-82770ee0-a712-4cb2-85f4-733ae05c664d.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Opera
 - Version -

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
