### ISSUE TITLE
Add Stacks chain

### ISSUE THREAD

**Issue by yknl** [WalletConnect/walletconnect-monorepo#1867]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets
   **GitHub Link**: https://docs.xverse.app/wallet-connect/reference/api_reference
2. Write a [CASA namespace](https://github.com/ChainAgnostic/namespaces) spec.
   **GitHub Link**: https://github.com/ChainAgnostic/namespaces/tree/main/stacks
3. **namespaces**: 
stacks:
4. **chains**:
stacks:1 (mainnet) 
stacks:2147483648 (testnet)
5. Submit this template.

**Additional context**
We're the team working on [Xverse wallet](https://www.xverse.app/). Xverse wallet now supports using WalletConnect to connect with apps on the Stacks blockchain.

**Comment by bkrem** [comment]
Thanks for the solid submission with the relevant links @yknl 🙌 

Both Stacks chains should now be available on https://cloud.walletconnect.com in the Chains selector 👍
