### ISSUE TITLE
Unable to Choose Chain on Trust Wallet - Standalone

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/walletconnect-monorepo#1871]
I'm not able to choose a specific chain in Trust wallet.

I'm using the standalone version with the universal-provider and ethers.js

My code:

```tsx
import { UniversalProvider } from '@walletconnect/universal-provider';
import { Web3Modal } from '@web3modal/standalone'
import { ethers } from 'ethers';

const web3Modal = new Web3Modal({ 
  // projectId: process.env.NEXT_PUBLIC_PROJECT_ID 
  standaloneChains: ["eip155:1", "eip155:137"],
})

export default function HomePage() {

const [childProvider, setChildProvider] = useState<any>()

 async function onInitializeSignClient() {
    
    const provider = await UniversalProvider.init({
      projectId: process.env.NEXT_PUBLIC_PROJECT_ID,
      metadata: {
        name: "Glitch Dapp",
        description: "Glitch Dapp",
        url: "mywebsite.com",
        icons: ["url-icon.com"],
      },
    });

    setChildProvider(provider)

  }

  async function onOpenModal() {

    await childProvider?.connect({
      namespaces: {
        eip155: {
          methods: [
            "eth_sendTransaction",
            "eth_signTransaction",
            "eth_sign",
            "personal_sign",
            "eth_signTypedData",
          ],
          chains: ["eip155:1", "eip155:137"],
          events: ["chainChanged", "accountsChanged", "connect", "disconnect"],
        },
      },
    })

    web3Modal?.closeModal();
        
    //  Create Web3 Provider
    const web3Provider = new ethers.providers.Web3Provider(childProvider);

    const signer = web3Provider.getSigner()
    const address = await signer.getAddress()
    const chainId = await signer.getChainId()
     console.log(address, chainId)
  }

  useEffect(() => {
    onInitializeSignClient().catch((e: any)=> console.log(e))
  }, [])

  return (
    <>
    <button onClick={onOpenModal}>Connect Wallet</button>
    </>
  )
}
```

This is what I get when I connect with Trust Wallet:
![1673887075875](https://user-images.githubusercontent.com/66949816/212729527-cd07ffb6-51e7-4fca-aa04-616b7e62b536.jpg)
---
![1673887075863](https://user-images.githubusercontent.com/66949816/212729537-ed71bc3a-0451-4698-a795-ce6b4442a975.jpg)

So I'm not able to choose the chain I want to connect like this where as you can see there's an arrow that allows me to select different chains:

![1673887075844](https://user-images.githubusercontent.com/66949816/212729861-33240590-3246-46b4-91f5-fe2a6f114043.jpg)

My question:
Does this mean that I'm connecting myself to both chains at the same time? If so is the case, how do I handle this on the dapp with universal-provider?
How do I select the chain that will be used to trigger the smart contract function request to the user's wallet? 
And what if I want the user to choose the chain before connecting?

**Comment by ganchoradkov** [comment]
hey @glitch-txs, I'm seeing you have configured chains `chains: ["eip155:1", "eip155:137"],`. In v2 protocol all chains are 'connected' simultaneously meaning you can send transaction requests for all chains without the need to switch the chain first.

If you'd like to listen for a chain switch on the dapp side, you should subscribe to `session_event` 
Snippet from our docs
```
signClient.on("session_event", (event) => {
  // Handle session events, such as "chainChanged", "accountsChanged", etc.

  interface Event {
    id: number;
    topic: string;
    params: {
      event: { name: string; data: any };
      chainId: string;
    };
  }
});

**Comment by glitch-txs** [comment]
Thanks for your comment, unfortunately I'm not hable to choose/switch chain using Trust Wallet and it picks up the first chain I configured. I'm also not able to choose the chain Id in ethers js as it depends on the wallets currently chain connection.

So basically my issue is, I'm not able to choose chain we I'm connected to Trust Wallet.

**Comment by ganchoradkov** [comment]
I just tested with Trust Wallet, using our example dapp at https://react-app.walletconnect.com/ and I'm able to connect and use/sign transactions with multiple chains without having to switch. I'm not able to find/see the `arrow` you mentioned in the first comment

**Comment by glitch-txs** [comment]
The arrow appears on v1 that it allows to switch, not on v2.

Right, the thing is, when I send a transaction to the wallet it will pick up the first chain, but if I want to sign that tx using other chain I'm not able to switch

**Comment by ganchoradkov** [comment]
Could you test with our example dapp if that's the case too? As I'm able to sign transactions with any of the chains connected

**Comment by glitch-txs** [comment]
I see you can choose the chain from the dapp on the example you mentioned, I assume this is using the request function from SignClient where you can set the chain Id.

But this is not possible on ethers js at least not that I'm aware of

When you instantiate a Contract you add the abi, the contract address and the signer. The chain Id is implicit in the signer.


![IMG_20230118_045740.jpg](https://user-images.githubusercontent.com/66949816/213115268-c3939a83-4569-440a-abca-4f798098e7c3.jpg)

**Comment by ganchoradkov** [comment]
Seeing the examples above, while in `ethers.js` you can have a chain active, you should be able to request on any chain configured in the `universal-provider` using `childProvider.request(args, <the chainId e.g. eip155:1>)`

**Comment by glitch-txs** [comment]
I see you can choose the chain from the dapp, I assume this is using the request function from SignClient where you can set the chain Id.

But this is not possible on ethers js at least not that I'm aware of

When you instantiate a Contract you add the abi, the contract address and the signer. The chain Id is implicit in the signer.


![IMG_20230118_045740.jpg](https://user-images.githubusercontent.com/66949816/213115268-c3939a83-4569-440a-abca-4f798098e7c3.jpg)

**Comment by glitch-txs** [comment]
Yes, but I don't want to use the signClient to make the request, I'm instead using ethers.js which doesn't allows you to choose chain Id when creating a request.

If I use the signClient then I need to do some hex conversions which ethers.js simplifies.

**Comment by glitch-txs** [comment]
This is how I can call a contract with ethers (here I'm calling the read-only function "name" of an ERC20), as you can see there's no parameter for chain Id.

```tsx
const erc20Contract = new ethers.Contract(contractAddress, ERC20Abi, signer) 
  
     const name = await erc20Contract.name()
```

**Comment by ganchoradkov** [comment]
Unfortunately, that is a shortcoming of `ethers` being single-chain. 
What you could do is call `provider.setDefaultChain('eip155:1')` before the request, this will switch the chain in `ethers` and you will be able to make the call for the correct chain

**Comment by glitch-txs** [comment]
It seems so, they are landing v6 soon, I'll check on that or request this feature.

Thanks for your time, I'll try a work around with that function 🙂
