### ISSUE TITLE
non-React Framework Warns Standalone

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/walletconnect-monorepo#1883]
I'm getting this warns when working on Solid.js with standalone and universal-provider packages, so far it works well on localhost but it would be nice if this warns weren't there as it shouldn't depend on React right?

![imagen](https://user-images.githubusercontent.com/66949816/213823121-d92b8fab-c14e-4fc3-a109-a56938202d2d.png)

**Comment by xzilja** [comment]
@glitch-txs this looks like pnpm related warning for state library that we use `valtio`, which has optional peerDependency on `react`. Not too familiar with pnpm, do you have suggestions on how these kinds of errors are handled there? My understanding is that you can still use everything, but seeing this after install is deff not ideal.
