### ISSUE TITLE
Multi-chain support ?!?

### ISSUE THREAD

**Issue by 10xSebastian** [WalletConnect/walletconnect-monorepo#1884]
Desired Behaviour:

I want to access all chains the user has set up on his wallet.

Current Behaviour:

I can't detect what chains the user has set up on his wallet, prior to creating a proposal/requiredNamespaces.

So if a user selects Blockchain A, the dApp will not be able to switch to Blockchain B (without restarting the entire connection process)

Asking the user which blockchains he believes he is gonna interact with as early as connecting his wallet is not an option.

Example:

A user connects a wallet. He picks Ethereum because it's the chain he believes he is gonna interact on. During the interaction with the dapp he will need to interact on BSC but signing on that chain is not possible anymore (as it was not requested upon connecting).

Question:

Is there a way to detect what chains the wallet supports so that I can add all supported wallets to the proposal/requiredNamespace?

Or is there a way to upgrade an existing session to get access to more chains without restarting the entire process?

**Comment by 10xSebastian** [comment]
similar problem: https://github.com/WalletConnect/walletconnect-monorepo/discussions/1697

**Comment by ganchoradkov** [comment]
Hey @10xSebastian 
the expected behavior from dapps will be to allow the user to select which chains they want to connect prior to establishing a session. Please check out our example dapp for reference https://react-app.walletconnect.com/

Once session is established, it can be updated to include additional chains using `signClient.update` method
https://docs.walletconnect.com/2.0/javascript/web3wallet/wallet-usage#updating-a-session
but that should be a wallet responsibility as they have to choose explicit account/address for the new chains.

**Comment by 10xSebastian** [comment]
Thanks for the quick response. Still unsatisfying.

If you would send me money from Bulgaria to Switzerland, would you know which banking networks will be used?

**Comment by 10xSebastian** [comment]
Or if you want to use your Apple Wallet, you need to know which tokenization standard will be used and need to select it prior to using it.

Same with credit cards. Before you tap it onto a POS.

Or the internet. Which subnets are you gonna interact with?

**Comment by 10xSebastian** [comment]
What happened to the idea of `requiredNamespaces: {}`?

**Comment by ganchoradkov** [comment]
The requiredNamespaces are designed to be complient with `CAIP-25` https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-25.md

requesting empty `requiredNamespaces: {}` means the user will select, via the wallet, which chains they want to interact with.
Having access to all chains/addresses on the user's wallet is not possible unless explicitly approved by the user.
