### ISSUE TITLE
Allow for multiple providers over one connection

### ISSUE THREAD

**Issue by oed** [WalletConnect/walletconnect-monorepo#189]
Currently each provider requires it's own connector. However, in many cases a dapp might want to use multiple protocols if a wallet supports them. By allowing providers to accept a connector that's already in use multiple providers can share one connector.

**Comment by KamesCG** [comment]
To echo what @oed said it would be great to start experimenting with multiple protocol standards via multiple provider. Just got WalletConnect setup over the weekend and going to start experimenting with supporting the 3ID protocol, so maybe I can be beta tester for anything?

https://github.com/KamesCG/ethid-mobile

**Comment by pedrouid** [comment]
Already supported on the `next` tag. You can test this with the new WalletConnect SDK.

https://www.npmjs.com/package/walletconnect/v/1.0.0-beta.89

Example (using walletconnect@1.0.0-beta.89)
```typescript
import WalletConnect from "walletconnect";
 
//  Create WalletConnect SDK instance
const wc = new WalletConnect();
 
//  Connect session (triggers QR Code modal)
const connector = await wc.connect();
 
//  Get your desired provider
 
const web3Provider = await wc.getWeb3Provider({
  infuraId: "<INSERT_INFURA_APP_ID>",
});
 
const channelProvider = await wc.getChannelProvider();
 
const starkwareProvider = await wc.getStarkwareProvider({
  contractAddress: "<INSERT_CONTRACT_ADDRESS>",
});
 
const threeIdProvider = await wc.getThreeIdProvider();
```
