### ISSUE TITLE
Does not properly close the websocket connection to relayer.

### ISSUE THREAD

**Issue by antondalgren** [WalletConnect/walletconnect-monorepo#1897]
**Describe the bug**
The websocket connection is not closed.
The heartbeat is not stopped.  

**To Reproduce**
```typescript
import {SignClient} from "@walletconnect/sign-client";
import wtfnode from "wtfnode"

async function main() {
  const client = await SignClient.init({ projectId: "-" });
  await client.core.relayer.transportClose();
  wtfnode.dump();
}

main().catch(error => console.log(error));
```
Output: 
```sh
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 1 (tty) (stdio)
- Sockets:
  - x.x.x.x:1337 -> x.x.x.x:443
- Timers:
  - (30000 ~ 30 s) bound destroy @ /../node_modules/ws/lib/websocket.js:307
- Intervals:
  - (5000 ~ 5 s) (anonymous) @ /../node_modules/@walletconnect/heartbeat/dist/cjs/heartbeat.js:45
```
**Expected behavior**

```typescript
const client = await SignClient.init({ projectId: "-" });
await client.core.relayer.transportClose(); // Or any other intuitive path to find the clear it up.
```

Where the websocket connection is closed and heartbeat is stopped.

**Comment by antondalgren** [comment]
We have identified two issues.

The method call `client.core.relayer.transportClose()` is not async, as it probably should be. That way we will wait for the connection to be closed before moving on to the next step. 

See WS & HTTP implementation. https://github.com/WalletConnect/walletconnect-utils/blob/f23761516903bb7c65f9bba34dcfb1f014f2bc4e/jsonrpc/ws-connection/src/ws.ts#L73-L79 https://github.com/WalletConnect/walletconnect-utils/blob/f23761516903bb7c65f9bba34dcfb1f014f2bc4e/jsonrpc/http-connection/src/http.ts#L69-L74

The second issue is that when we call `client.core.relayer.transportClose()`, the connection is being closed eventually, but because the publisher/subscribers are not aware of this, they emit `connection_stalled` event that calls `restartTransport`
https://github.com/WalletConnect/walletconnect-monorepo/blob/e34e87c4e477be8c3aaf6dee8c33ced5a720bbc3/packages/core/src/controllers/relayer.ts#L270-L272

`restartTransport` however should be aware of that the connection has been explicitly closed and thus not try to reopen the connection. 
https://github.com/WalletConnect/walletconnect-monorepo/blob/e34e87c4e477be8c3aaf6dee8c33ced5a720bbc3/packages/core/src/controllers/relayer.ts#L191-L195


Solution to second issue:
```typescript 
  public async restartTransport(relayUrl?: string) {
    if(this.transportExplicitlyClosed) {
      return;
    }
    await this.transportClose();
    await new Promise<void>((resolve) => setTimeout(resolve, RELAYER_RECONNECT_TIMEOUT));
    await this.transportOpen(relayUrl);
  }
```

**Comment by ganchoradkov** [comment]
Hey @antondalgren, thanks for the report.
I checked your example and indeed the connection is not closed before `transportClose()` resolves and it takes ~40ms for the socket to be disconnected and registered as such.

Regarding the `subscriber`, it is triggered by a `heartbeat` event but that is already aware of the explicit close so it shouldn't restart the connection
https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/core/src/controllers/subscriber.ts#L364 

Regarding the relayer, are you trying to publish a request while the transport is closed?
It was intentionally designed as is currently for the scenario where
- the connection drops
- the app sends a request
- connection is restarted automatically & request delivered

**Comment by antondalgren** [comment]
> Hey @antondalgren, thanks for the report. I checked your example and indeed the connection is not closed before `transportClose()` resolves and it takes ~40ms for the socket to be disconnected and registered as such.
https://github.com/WalletConnect/walletconnect-utils/pull/49
> Regarding the `subscriber`, it is triggered by a `heartbeat` event but that is already aware of the explicit close so it shouldn't restart the connection https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/core/src/controllers/subscriber.ts#L364

Fair enough!

> Regarding the relayer, are you trying to publish a request while the transport is closed? It was intentionally designed as is currently for the scenario where
> 
> * the connection drops
> * the app sends a request
> * connection is restarted automatically & request delivered

**Comment by antondalgren** [comment]
Thank you for taking the time @ganchoradkov 

> Hey @antondalgren, thanks for the report. I checked your example and indeed the connection is not closed before `transportClose()` resolves and it takes ~40ms for the socket to be disconnected and registered as such.

Implemented a solution here: https://github.com/WalletConnect/walletconnect-utils/pull/49

> Regarding the `subscriber`, it is triggered by a `heartbeat` event but that is already aware of the explicit close so it shouldn't restart the connection https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/core/src/controllers/subscriber.ts#L364

Yeah, seems like it was only applicable to publishers.

> Regarding the relayer, are you trying to publish a request while the transport is closed? It was intentionally designed as is currently for the scenario where
> 
> * the connection drops
> * the app sends a request
> * connection is restarted automatically & request delivered

I'm just trying to close the connection to the relayer. 

It is good that it tries to restart the connection and redeliver the message on network failure and unexpected events that cause the connection to drop. But if i explicitly close it, I do not want or expect the system to reopen the connection.

**Comment by amiryadid-fb** [comment]
Experiencing the same issue with the heartbeat looping over it, we currently suspect those opened handles are a source for a memory leak.
Is there an ETA on the version that'll fix this?
Also, even if the connection is closed I believe nothing actually stops the heartbeat from continuing to pulse, which is also required as part of the cleanup
