### ISSUE TITLE
walletconnect: ReferenceError: safeBuffer is not defined

### ISSUE THREAD

**Issue by jinchung** [WalletConnect/walletconnect-monorepo#19]
I get this error after using the latest walletconnect package (v0.6.2) and do yarn start. It gives me:
<img width="1449" alt="screen shot 2018-09-05 at 6 32 05 pm" src="https://user-images.githubusercontent.com/1285228/45166003-fca1c780-b1c3-11e8-800f-3e3c920a6366.png">

**Comment by pedrouid** [comment]
FIXED!
