### ISSUE TITLE
new chain request - Kadena

### ISSUE THREAD

**Issue by tim-eucalyptus** [WalletConnect/walletconnect-monorepo#1905]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
   **GitHub Link**: TBD
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   **GitHub Link**: TBD
3. **namespaces**: kadena
   _\*known chain namespaces (e.g. eip:155 for Ethereum/EVM-based chains, solana, ...)_
4. **chains**: mainnet01, testnet04, development
   _\*known chains, where the primary key is a compound key composed of namespace + reference (e.g. ETH mainnet is eip155:1)._
   _Please provide labels for each chain (e.g. mainnet, testnet, devnet, ...)_
5. **RPC endpoints**: https://kadena2.app.runonflux.io/chainweb/0.0/mainnet01/chain/1/pact/api/v1/send
   _\*list of common/canonical RPC endpoints for the chain(s)_
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**: 626
   _\* slip44 coin type used in the namespace_

**Additional context**
https://github.com/kadena-io/KIPs/blob/jam/wallet-connect/kip-0017.md

**Comment by bkrem** [comment]
Hi @tim-eucalyptus,

Submission looks good in general but there doesn't seem to be a [namespace spec in CASA](https://github.com/ChainAgnostic/namespaces) yet.

This is a requirement for us to continue with any chains in the Kadena ecosystem.

**Comment by bkrem** [comment]
Closing as stale since there seems to be no CASA spec PR merged or in flight.

Feel free to comment here if the namespaces spec is merged in CASA and we can reopen here 👍
