### ISSUE TITLE
@walletconnect/web3-provider greatly increases bundle size for websites that include it

### ISSUE THREAD

**Issue by BrendanChou** [WalletConnect/walletconnect-monorepo#191]
This takes up about 20% of our entire webpack bundle, which slows down the loading time for our site for all users. I suspect other sites have similar issues

<img width="756" alt="Screen Shot 2019-10-21 at 3 16 10 PM" src="https://user-images.githubusercontent.com/3680392/67247306-c8b05280-f415-11e9-9d20-735e6b66b904.png">

**Comment by pedrouid** [comment]
Hey @BrendanChou, sorry it took me so long to get back on this but working on this right now... already made some significant progress.

<img width="1920" alt="Screenshot 2020-02-13 19 59 14" src="https://user-images.githubusercontent.com/10136079/74468783-b615c980-4e9b-11ea-988c-a6a3acf30bc5.png">

Just need to do some more testing but you can test it in your side by installing with `next` tag

```sh
npm install --save @walletconnect/web3-provider@next

# OR

yarn add @walletconnect/web3-provider@next
```

**Comment by BrendanChou** [comment]
Great, thanks! Will check it out

**Comment by everettwho** [comment]
@pedrouid Thanks for working on this, our bundle size has reduced significantly since the changes. Keep us updated on any other bundle size reductions that might come in the future!
