### ISSUE TITLE
Invalid transaction 

### ISSUE THREAD

**Issue by mariano-aguero** [WalletConnect/walletconnect-monorepo#192]
Hello , I have a problem with the transaction string returned when I send a transaction. I preconfigure web3-react with WalletConnect and ethers.js ,  I'm using trust wallet.

The result is too long and is not a valid transaction hash

`0xf9016b3f8503b9aca000836134d394325a2e0f3cca2ddbaebb4dfc38df8d19ca165b4780b90104762c38fd000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000dc0a2185031ecf89f091a39c63c2857a7d5c301a0000000000000000000000000000000000000000000000000000000000015180000000000000000000000000000000000000000000000000000000005de089b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000116c6a686c6a6c6b6a39383639383739383700000000000000000000000000000026a01948e3f3226ba6689850088f8cfe5d21e791806b28426cccdf1f684bdd1415afa06d1b7c90783634e081fd42cf1237aafbaa6d9f6b136e23c8b8ea472d4a74d12a`

This is my code:

```
      const abi = ['function askQuestion(uint256 template_id, string question, address arbitrator, uint32 timeout, uint32 opening_ts, uint256 nonce) public payable returns (bytes32)']
      const arbitratorAddress = getContractAddress(networkId, 'realitioArbitrator')
      const realitioAddress = getContractAddress(networkId, 'realitio')

      const openingTimestamp = openingDateMoment.unix()
      const args = [0, question, arbitratorAddress, '86400', openingTimestamp, 0]

      const iface = new ethers.utils.Interface(abi)
      const dataRealitio = iface.functions.askQuestion.encode(args)
      const tx = {
          from: user,
          to: realitioAddress,
          data: dataRealitio,
      }
      const tx = await walletConnector.sendTransaction(tx)
      console.log(tx)
```

I'm just wondering if I'm missing something here ?, Thanks in advance!

**Comment by pedrouid** [comment]
This has been fixed on the latest release of Trust wallet
