### ISSUE TITLE
Wallet Connect does not open wallet selection modal in android only

### ISSUE THREAD

**Issue by itsnyx** [WalletConnect/walletconnect-monorepo#1927]
hello, everybody im using :
`    "@walletconnect/react-native-dapp": "^1.8.0",
`and when i use 

`    connector.connect();`
it does not open the wallet selection modal in android instead it opens the webpage in browser.

how can i solve this issue?

**Comment by clucasalcantara** [comment]
Hey @itsnyx!

Actually, this is not a bug and yes how Android works, since it relies on a different modality of universal links what you need to do is check if the device has the wallet app that the user is trying to open installed and show a message/give feedback if not, otherwise, if the deep link is recognized it will show as an option to connect. If you try to open an unrecognized deep link it will fall back for the web.


```
// Add an if to check when clicking to connect on a wallet if the platform is android 
if (Platform.OS === 'android') {
        // check if the URI for the desired wallet is recognized by the device
        const supported = await Linking.canOpenURL(uri);
        
        if (!supported) {
          // return message/feedback asking to install the app
       }
}
// If all is good, call connect which will trigger the android modal for it
connect();
```

### functional example:

https://user-images.githubusercontent.com/6919712/216780060-3b5d50c0-f851-49fd-af64-86cdb0c1f6c9.mp4

**Comment by eavelasquez** [comment]
> Hey @itsnyx!
> 
> Actually, this is not a bug and yes how Android works, since it relies on a different modality of universal links what you need to do is check if the device has the wallet app that the user is trying to open installed and show a message/give feedback if not, otherwise, if the deep link is recognized it will show as an option to connect. If you try to open an unrecognized deep link it will fall back for the web.
> 
> ```
> // Add an if to check when clicking to connect on a wallet if the platform is android 
> if (Platform.OS === 'android') {
>         // check if the URI for the desired wallet is recognized by the device
>         const supported = await Linking.canOpenURL(uri);
>         
>         if (!supported) {
>           // return message/feedback asking to install the app
>        }
> }
> // If all is good, call connect which will trigger the android modal for it
> connect();
> ```
> 
> ### functional example:
>  wallet.connection.mp4

Hey @clucasalcantara. So, in order to connect, it must be through a specific wallet that you want the user to use? Could you tell me how I could do it for Metamask?

**Comment by itsnyx** [comment]
@clucasalcantara do you know if i can create a custom modal for this like the one in ios?

**Comment by clucasalcantara** [comment]
@eavelasquez Actually no, but the android modal will show up for every app that the user has installed AND those that we have support, for meta mask you can do a map on the wallet services array, check for meta mask installed by ` Linking.canOpenURL(URI);` and  send a message to the user saying that he needs to install it :)

**Comment by clucasalcantara** [comment]
@itsnyx I didn't found how to do it yet, so I'm using this technique that I just described but I'll let you know if I find something 🗡️

**Comment by itsnyx** [comment]
thanks @clucasalcantara. I'm closing this issue fix : https://github.com/WalletConnect/walletconnect-monorepo/issues/1927#issuecomment-1416802721
