### ISSUE TITLE
Add deprecation info to all v1 packages

### ISSUE THREAD

**Issue by timjrobinson** [WalletConnect/walletconnect-monorepo#1930]
I only just learnt today via Twitter that V1 of wallet connect is going to be turned off in 3 weeks!

Yet none of the packages we use have any information about this in them. We use: https://www.npmjs.com/package/@walletconnect/web3-provider which only goes up to v1.8

There is also https://www.npmjs.com/package/walletconnect that only goes up to 1.7.8

Apparently we should be using https://www.npmjs.com/package/@walletconnect/web3wallet now?

Every package that uses V1 wallet connect should have a deprecation notice with a link on how to migrate.

**Comment by bkrem** [comment]
Hi @timjrobinson,

Thank you for raising this 🙏  We were indeed missing the deprecation messaging on the legacy npm packages.

The following packages have now been marked as deprecated:

```
@walletconnect/truffle-provider 
@walletconnect/web3-provider 
@walletconnect/web3-subprovider
@walletconnect/client 
@walletconnect/ethereum-provider@1.x
@walletconnect/qrcode-modal 
@walletconnect/types@1.x
```

For guidance on migration regarding each existing v1.x use case please see: https://docs.walletconnect.com/2.0/advanced/migrating-from-v1.0
