### ISSUE TITLE
Unable to connect to Trust, Omni, or AlphaWallet

### ISSUE THREAD

**Issue by finessevanes** [WalletConnect/walletconnect-monorepo#1952]
**Describe the bug**

- Reported by  user midpoint on [Discord](https://discord.com/channels/492410046307631105/1065751486644101131/1066849011081949234)

Unable to connect to Trust, AlphaWallet, or Omni, but dapp can connect to example wallet: https://react-wallet.walletconnect.com/walletconnect

**SDK Version (if relevant)**
 - Client: JS
 - Version: sign-client v2.3.3:

**To Reproduce**
1. Go to https://test.poolygotchi.com/
2. Click on connect, select WalletConnect
3. Try scanning QR code with Trust, AlphaWallet, or Omni

**Expected behavior**
User should be able to successfully connect to wallet

**Screenshots**
![IMG_6171](https://user-images.githubusercontent.com/44731696/217673793-c06314e2-9607-41b9-a110-9d2a929ad033.PNG)
![IMG_6170](https://user-images.githubusercontent.com/44731696/217673796-0ec9529c-9416-484d-8314-9288af521729.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS16.2

**Additional context**
Code to connect:
```
const { uri, approval } = await signClientWC.connect({
      requiredNamespaces: {
        eip155: {
          methods: [
            "eth_sendTransaction",
            "eth_signTransaction",
            "eth_sign",
          ],
          chains: ["eip155:1", "eip155:10", "eip155:137", "eip155:43114", "eip155:420"],
          events: ["chainChanged", "accountsChanged"],
        },
      },
    });
```

**Comment by antondalgren** [comment]
I haven't confirmed, but `["eth_signTransaction","eth_sign"]` are problematic transactions for wallets, outlined in https://github.com/WalletConnect/web-examples/issues/92

**Comment by trmid** [comment]
> I haven't confirmed, but `["eth_signTransaction","eth_sign"]` are problematic transactions for wallets, outlined in [WalletConnect/web-examples#92](https://github.com/WalletConnect/web-examples/issues/92)

Removing the mentioned methods from the scope did not fix the problem when using Zerion and TrustWallet.

**Comment by glitch-txs** [comment]
@trmid I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
