### ISSUE TITLE
Connect -> Approve Proposals Are Nondeterministic

### ISSUE THREAD

**Issue by Luzzotica** [WalletConnect/walletconnect-monorepo#1959]
**Is your feature request related to a problem? Please describe.**
The Connect -> Approve process currently relies on a there not being additional Proposals while one is being handled, otherwise they will all complete with the same SessionData. 

This is due to the fact that there is no identifier linking a Proposal to a Session. They are loosely coupled by time (A Proposal was Approved, I assume it's most recent proposal I sent off).  

While this is a valid assumption to make, I personally feel that creating a more deterministic approach to this would be better. The dApp can't *always* trust that the most recent Proposal is the one being Approved, and if it wasn't, you end up with mismatching data.

**Describe the solution you'd like**
This can be resolved by optionally adding the `pairingTopic` to the WcSessionSettleRequest, and use that to get the correct Proposal each time.

**Describe alternatives you've considered**
Another option is to use the JsonRpc Payload Id as an optional `proposalId` in the WcSessionSettleRequest, but this feels less elegant.

**Additional context**
This wouldn't be a breaking change, dApps could go on assuming that the last Proposal created is the one to use, but if there's a `pairingTopic` in the settle request the protocol can use that to get the exact Proposal instead

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
