### ISSUE TITLE
Deep Linking  not connected to dApp in React-Native IOS, OS version higher than 12(WalletConnect V1)

### ISSUE THREAD

**Issue by antiergit** [WalletConnect/walletconnect-monorepo#1961]
when try to connect with dApp via deep linking, getting uri from the dapp and session created successfully, After that connector.approveSession({accounts:[accounts],chainId:chainId}) called but unable to connect with dApp(pancakeswap, uniswap). But its working fine with lower OS version of 12 iphones and also working all android devices.

**SDK Version (if relevant)**
 - @walletconnect/client
 - Version [ "^1.8.0"]

 - OS: [iOS]
 - Version [higher than 12]

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
