### ISSUE TITLE
EthereumProvider init error: ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor

### ISSUE THREAD

**Issue by justinkchen** [WalletConnect/walletconnect-monorepo#1967]
**Describe the bug**

Trying to initialize an instance of the EthereumProvider but receiving error of `ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor` seemingly due to not calling `super()` from here https://discord.com/channels/492410046307631105/1073632288140697663/1073634371401166958.  Not sure how this works for others since it seems like a strict requirement

**To Reproduce**
1. Try out a sample code bit of 
```
  import { EthereumProvider } from '@walletconnect/ethereum-provider';

  const provider = await EthereumProvider.init({
    projectId: 'projectId',
    chains: [chainId],
  });
```

2. `yarn start` should work, but then when I try to call the code that runs it I get the above ReferenceError at that `init` line

**Expected behavior**
Should be able to call 
```
  import { EthereumProvider } from '@walletconnect/ethereum-provider';

  const provider = await EthereumProvider.init({
    projectId: 'projectId',
    chains: [chainId],
  });
```
without any issues

**Screenshots**
![Screenshot 2023-02-10 at 12 48 12 PM](https://user-images.githubusercontent.com/1000741/218160817-5b361ea9-1555-4d26-833a-514927c471c1.png)

**Comment by justinkchen** [comment]
pinging on this again!

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
