### ISSUE TITLE
Web3Wallet Doesnt Have Pair Function

### ISSUE THREAD

**Issue by Luzzotica** [WalletConnect/walletconnect-monorepo#1969]
**Describe the bug**
As per the [Web3Wallet spec](https://docs.walletconnect.com/2.0/specs/meta-clients/web3wallet/sdk-api), there should be a `pair` function in the [Web3Wallet client](https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/web3wallet/src/types/client.ts), however there is none. 

Thus, the spec must change, or the Web3Wallet client must be updated.

I feel like the spec is correct. There needs to be a pair function. That's what's used when you've scanned a QR code with the wallet. Not having one likely makes this SDK unusable.

**SDK Version (if relevant)**
Javascript Monorepo

**To Reproduce**
N/A

**Expected behavior**
There needs to be a `pair` function.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ganchoradkov** [comment]
Hey @Luzzotica , the web3wallet SDK is intended to be used by wallets exclusively. Pairing initiation (`signClient.connect`) is a dapp responsibility and thus intentionally omitted from the web3wallet

**Comment by ganchoradkov** [comment]
Hey @Luzzotica , seems I misunderstood your report. Yes, the web3wallet will include `pair` fx in the next update.
Will keep you posted :+1:
