### ISSUE TITLE
wallet_addEthereumChain failing

### ISSUE THREAD

**Issue by saisumit** [WalletConnect/walletconnect-monorepo#1972]
### Discussed in https://github.com/orgs/WalletConnect/discussions/1960

<div type='discussions-op-text'>

<sup>Originally posted by **GrahamMcBain** February 10, 2023</sup>
(Question from Discord)

If Network Already exists in meta mask => Switch Chain Happens - No problem
If Network Doesn't Exist => Nothing Happens, If I try to do provider.request("wallet_addEthereumChain") it fails and gives an error "The Provider does not have a rpcUrl to make a request for the requested method: wallet_addEthereumChain" or sometimes there is no response or Nothing Happens.
We have observed similar behaviour across various clients including wagmi, web3-onboard, web-react and even web3modal, which feels such a simple use-case but doesn't works</div>

**Comment by ganchoradkov** [comment]
hey @saisumit as per the docs https://docs.metamask.io/guide/rpc-api.html#wallet-addethereumchain 
when calling `wallet_addEthereumChain` you must provide rpc urls as the error message is suggesting

**Comment by mbcse** [comment]
@ganchoradkov 

If we add still it doesn't work. There is no response. It doesn't add the chain to the metamask.

**Comment by saisumit** [comment]
+1 to @mbcse this doesn't add the chain to the connected wallet.

**Comment by ong-appxplore** [comment]
Hi, any solution or workaround for this yet?

**Comment by saisumit** [comment]
@ganchoradkov can you help or anyone on your team ??????

**Comment by ganchoradkov** [comment]
@saisumit, could you specify which SDK version you're using?
Note that metamask does not yet support v2.

As for the `add_ethereumChain` could you provide an example repo where we can reproduce it?

**Comment by GouthamJM** [comment]
We are also facing the same issue

**Comment by mayankmotiyani** [comment]
**i am giving you the reference** : https://www.freecodecamp.org/news/how-to-add-custom-network-to-metamask/

window.ethereum.request({
      method: "wallet_addEthereumChain",
      params: [{
        chainId: "0x89",
        rpcUrls: ["https://polygon-rpc.com/"],
        chainName: "Matic Mainnet",
        nativeCurrency: {
          name: "MATIC",
          symbol: "MATIC",
          decimals: 18
        },
        blockExplorerUrls: ["https://polygonscan.com/"]
      }]
    });


may be it will help you ..

**Comment by finessevanes** [comment]
Thanks for reporting everyone.

Details such as the following would help:
1) Version of the package you are using
2) Reproducible code via a codeBox, error logs, and/or reproduction steps
3) Which wallet (platform and version) you used to get to the issue
