### ISSUE TITLE
Universal Provider not working (Official example app)

### ISSUE THREAD

**Issue by jurosh** [WalletConnect/walletconnect-monorepo#1981]
**Describe the bug**
Universal provider not unlocking: https://react-dapp-v2-with-ethers.vercel.app/
Official app repo: https://github.com/WalletConnect/web-examples/tree/main/dapps/react-dapp-v2-with-ethers

**SDK Version (if relevant)**
    "@walletconnect/universal-provider": "^2.1.4",
    "@web3modal/standalone": "^2.0.0-beta.10",

**To Reproduce**
1. Go to https://react-dapp-v2-with-ethers.vercel.app/
2. Click on Chain (eg. Ethereum)
3. Scan QR Code with Mobile App (Trust / Metamask)
4. (Nothing is happening)

**Expected behavior**
Wallet should be unlocked.

**Desktop (please complete the following information):**
 - Browser latest Chrome

**Smartphone (please complete the following information):**
- Tried on Android (Trust and Metamask) and iOS (Trust)

**Additional context**
Console output (until QR scan, nothing else after scan):

```
{context: 'core'} {context: 'core/history'} 'Successfully Restored records for history'
_app-da70b36bf4bbce96.js:33 {context: 'core'} {context: 'core/relayer'} {context: 'core/relayer/messages'} 'Successfully Restored records for messages'
_app-da70b36bf4bbce96.js:33 {context: 'core'} 'Core Initilization Success'
_app-da70b36bf4bbce96.js:33 {context: 'client'} 'SignClient Initilization Success'
_app-da70b36bf4bbce96.js:13 RESTORED PAIRINGS:  []
_app-da70b36bf4bbce96.js:13 Enabling EthereumProvider for chainId:  137
_app-da70b36bf4bbce96.js:33 {context: 'core'} {context: 'core/pairing'} {context: 'core/pairing/pairing'} 'Setting value'
_app-da70b36bf4bbce96.js:33 {context: 'core'} {context: 'core/relayer'} {context: 'core/relayer/subscription'} 'Subscribing Topic'
_app-da70b36bf4bbce96.js:33 {context: 'core'} {context: 'core/relayer'} {context: 'core/relayer/subscription'} 'Outgoing Relay Payload'
_app-da70b36bf4bbce96.js:33 {context: 'core'} {context: 'core/relayer'} 'Incoming Relay Payload'
_app-da70b36bf4bbce96.js:33 {context: 'core'} {context: 'core/relayer'} {context: 'core/relayer/subscription'} 'Setting subscription'
_app-da70b36bf4bbce96.js:33 {context: 'core'} {context: 'core/relayer'} {context: 'core/relayer/subscription'} 'Emitting subscription_created'
_app-da70b36bf4bbce96.js:33 {context: 'core'} {context: 'core/relayer'} {context: 'core/relayer/subscription'} {type: 'event', event: 'subscription_created', data: {…}}
_app-da70b36bf4bbce96.js:33 {context: 'core'} {context: 'core/relayer'} {context: 'core/relayer/subscription'} 'Successfully Subscribed Topic'
_app-da70b36bf4bbce96.js:33 {context: 'core'} {context: 'core/expirer'} 'Emitting expirer_created'
_app-da70b36bf4bbce96.js:33 {context: 'core'} {context: 'core/expirer'} {type: 'event', event: 'expirer_created', data: {…}}
_app-da70b36bf4bbce96.js:33 {context: 'core'} {context: 'core/history'} 'Setting JSON-RPC request history record'
_app-da70b36bf4bbce96.js:33 {context: 'core'} {context: 'core/history'} 'Emitting history_created'
_app-da70b36bf4bbce96.js:33 {context: 'core'} {context: 'core/history'} {type: 'event', event: 'history_created', record: {…}}
_app-da70b36bf4bbce96.js:33 {context: 'core'} {context: 'core/relayer'} {context: 'core/relayer/publisher'} 'Publishing Payload'
_app-da70b36bf4bbce96.js:33 {context: 'core'} {context: 'core/relayer'} {context: 'core/relayer/publisher'} 'Outgoing Relay Payload'
_app-da70b36bf4bbce96.js:33 {context: 'client'} 'Setting value'
_app-da70b36bf4bbce96.js:33 {context: 'core'} {context: 'core/expirer'} 'Emitting expirer_created'
_app-da70b36bf4bbce96.js:33 {context: 'core'} {context: 'core/expirer'} {type: 'event', event: 'expirer_created', data: {…}}
_app-da70b36bf4bbce96.js:13 EVENT QR Code Modal open
_app-da70b36bf4bbce96.js:33 {context: 'core'} {context: 'core/relayer'} 'Incoming Relay Payload'
_app-da70b36bf4bbce96.js:33 {context: 'core'} {context: 'core/relayer'} {context: 'core/relayer/publisher'} 'Successfully Published Payload'
```

**Comment by ganchoradkov** [comment]
hey @jurosh, I just tested the link you shared with Trust Wallet (iOS latest) and connection/usage seems to work fine.
Metamask is not yet supporting v2 and that is the reason you're not able to connect with MM.

You could check which wallets support v2 here: https://explorer.walletconnect.com/?version=2

**Comment by jurosh** [comment]
Me and another guy just tested TrustWallet and it's not working reliable at all. I cannot connect. The other guy can, but he needs to always clear site Cache to make it work. So this is def real problem...

Which wallet type are you using in TrustWallet ? (Which chain? Multi or Single Wallet?)

On the other hand, https://web3modal.com/ is working for me fine (Just occasionally fails to connect).

**Comment by ganchoradkov** [comment]
@jurosh I'm using multi chain wallet. 
Are you may be trying to use a test chain and/or chain that it's not supported by Trust?

**Comment by jurosh** [comment]
Hmm.. Looks like I needed to restart TrustWallet and now it seems to work. Will do further testing.

**Comment by jurosh** [comment]
It really seems to work consistently now (fingers crossed) with Multichain wallets. Even in my dApp.

What I am still not able to connect is Single-Chain TrustWallet wallet. Neither working on iOS or Android. I see only "Connecting may take a few seconds"

**Comment by inartin** [comment]
Testing the official demo, scanning with MetaMask (Android) and nothing happens, the scanner just closes. 
So it doesn't work.
