### ISSUE TITLE
Web3Wallet - "session_delete" event is missing in Web3WalletTypes.Event

### ISSUE THREAD

**Issue by buenaondalab** [WalletConnect/walletconnect-monorepo#1983]
**Describe the bug**
As per the [Web3Wallet spec](https://docs.walletconnect.com/2.0/specs/meta-clients/web3wallet/sdk-api), there should be a "session_delete" event to subscribe:

```typescript
// subscribe to session delete (SIGN)
public abstract on("session_delete", (sessionDelete: { id: number, topic: string }) => {}): void;
```
but it is not present in type Web3WalletTypes.Event.

**SDK Version (if relevant)**
 Javascript Monorepo

**To Reproduce**
```typescript
const web3Wallet = await Web3Wallet.init({ core, metadata });
web3Wallet.on('session_delete', () => {});
```

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 N/A

**Additional context**
N/A

**Comment by ganchoradkov** [comment]
Hey @buenaondalab , are you using latest version of `web3wallet`?
The `session_delete` should be present in the events types
https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/web3wallet/src/types/client.ts#L30
https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/web3wallet/src/controllers/engine.ts#L107

**Comment by AndonMitev** [comment]
I have the same issue using "@walletconnect/web3wallet": "1.1.1",

<img width="698" alt="image" src="https://user-images.githubusercontent.com/32274987/218723784-e7fa9511-5b8e-4436-bfd3-87b7b20b6112.png">

**Comment by AndonMitev** [comment]
> Hey @buenaondalab , are you using latest version of `web3wallet`? The `session_delete` should be present in the events types https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/web3wallet/src/types/client.ts#L30 https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/web3wallet/src/controllers/engine.ts#L107

in the shared example they are private?

**Comment by ganchoradkov** [comment]
Hey @AndonMitev , please update to `1.2.0` and the issues should be resolved for you

**Comment by buenaondalab** [comment]
@ganchoradkov @AndonMitev - I was using version `1.1.1`, updating to `1.2.0` solved the issue. Thank you.

**Comment by AndonMitev** [comment]
Yes i just, updated to 1.2.0 but for some reason when i call:

```
 web3wallet.on('session_delete', async (proposal: SignClientTypes.EventArguments['session_delete']) => {
      
       web3wallet.disconnectSession({
           topic: proposal.topic,
           reason: getSdkError('USER_DISCONNECTED'),
         });
       });
```

always throw this error:

https://github.com/WalletConnect/walletconnect-monorepo/issues/1772

any ideas

**Comment by ganchoradkov** [comment]
Hey @AndonMitev , when you receive the ` web3wallet.on('session_delete'` event the session is already cleared from the client internally so you don't have to add 
```
 web3wallet.disconnectSession({
           topic: proposal.topic,
           reason: getSdkError('USER_DISCONNECTED'),
         });
       });
