### ISSUE TITLE
no 'close' event emitted on mobile disconnect

### ISSUE THREAD

**Issue by NoahZinsmeister** [WalletConnect/walletconnect-monorepo#199]
Hmm, well I thought #194 would fix this, but it didn't.

Currently, if I connect to my dApp with a mobile wallet and then end the session from the wallet, the browser doesn't get a 'close' event for me to know that the session is over.

I'm using web3-provider.

**Comment by Velenir** [comment]
There's a `stop` event you can listen on. It comes from [`web3-provider-engine`](https://github.com/MetaMask/web3-provider-engine/blob/a17a32fab2717e5c6d600c5a8c25f9591c085aff/index.js#L83) as WalletConnectProvider extends ProviderEngine.
There's also `disconnect` event on wallet connector (`provider.wc`)

I don't think there's ever a `close` event

**Comment by pedrouid** [comment]
I see what you mean, I will add a subscription to the `disconnect` event on the client to trigger a `close` event on the provider

**Comment by pedrouid** [comment]
Should be fixed now!
