### ISSUE TITLE
chainChanged V2 Null pointer in Provider JS

### ISSUE THREAD

**Issue by redpathdesign** [WalletConnect/walletconnect-monorepo#1991]
### Discussed in https://github.com/orgs/WalletConnect/discussions/1978

<div type='discussions-op-text'>

<sup>Originally posted by **redpathdesign** February 13, 2023</sup>
 Javascript error in notify of Chain Changed. The javascript used is
 
**ethereum-provider@2.3.3**
      and latest was tested.
**ethereum-provider@4.2.2**

The Dapp established a connection with AlphaWallet (V2 support).
Nothing complicated here. Simply connect to the Wallet using QRcode.

```
   provider =  new EthereumProvider();
    const chainlist = [1];   //[1, 3, 4, 5, 42, 137];  

    await provider.initialize({
        projectId: "7cdb73265a92cf503dde9xxxxxxxxxxxx", // REQUIRED your projectId 
        chains: chainlist, // REQUIRED chain ids 
          metadata: {
            name: "MeMyselfAndI",
            description: "Connect to Ethereum using WalletConnect V2",
            url: "none",
            icons: [
              "static/images/myself.svg"
            ]
           }
      }); 

    //  Enable session (triggers QR Code modal)
    try{
         await provider.enable();
    } catch(error){
	alert("*Provider not connected");
	return null;
    }

 provider.on("disconnect", (error, payload) => {
    console.log("on Disconnect: Provider Disconnect: "+error+" "+ payload);
 });

 provider.on('chainChanged', (_chainId) => {
     console.log("chainChanged");
     console.log(_chainId);
 });
```

When a CHAIN is changed on the AlphaWallet a Javscript error occurs in the Provider JS.

**Provider2.3.3.js:3710** Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at iu (provider2.3.3.js:3710:30)
    at Ay.isValidUpdate (provider2.3.3.js:10495:31)
    
```

        function iu(t, e, r) {
            let n = null;
            const i = Object.keys(t), <====== :3710
                s = Object.keys(e);
            return gr(i, s) ? i.forEach(o => {
                if (n) return;
                const a = t[o].chains,
                    c = kn(e[o].accounts);
                gr(a, c) ? gr(t[o].methods, e[o].methods) ? gr(t[o].events, e[o].events) || (n = se("NON_CONFORMING_NAMESPACES", `${r} namespaces events don't satisfy requiredNamespaces events for ${o}`)) : n = se("NON_CONFORMING_NAMESPACES", `${r} namespaces methods don't satisfy requiredNamespaces methods for ${o}`) : n = se("NON_CONFORMING_NAMESPACES", `${r} namespaces accounts don't satisfy requiredNamespaces chains for ${o}`)
            }) : n = se("NON_CONFORMING_NAMESPACES", `${r} namespaces keys don't satisfy requiredNamespaces`), n
        }
```

I assume Object is Null.

I tested this with 4.2.2 and same issue.

Well anyway let me know, maybe some event is not set to be called and Object is NULL for the initialize().
Or AlphaWallet has an issue.
</div>

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
