### ISSUE TITLE
ethereum-provider: the `disconnect` event is not emitted

### ISSUE THREAD

**Issue by alexdupre** [WalletConnect/walletconnect-monorepo#1994]
**Describe the bug**
The `disconnect` event is not emitted when the session is closed on the wallet. The `session_delete` even is emitted, though, but I guess it should be re-mapped.

**SDK Version (if relevant)**
 - Client: ethereum-provider
 - Version 2.4.3

**Additional context**
Tested with a beta version of Bifrost wallet (Android)

**Comment by redpathdesign** [comment]
I don't even get the event if I force a disconnect from the Wallet either.  But that is not as bad as the Null trap for switching chains.

**Comment by intergalacticspacehighway** [comment]
Same issue. @alexdupre Does it clear up session from localStorage for you?
