### ISSUE TITLE
import @walletconnect/ethereum-provider in nuxt

### ISSUE THREAD

**Issue by seven-feng** [WalletConnect/walletconnect-monorepo#2001]
![image](https://user-images.githubusercontent.com/34559731/219332813-ce11f380-d330-454b-9d5b-782f19eca02a.png)

**Comment by glitch-txs** [comment]
You must be using Nuxt 2? 
You can either use a cdn or refactor the bundler configuration. 

Here's an example of cdn usage that you can adapt to Nuxt.

Closing for now as completed, please reopen if the issue still persists. Thank you!
