### ISSUE TITLE
ethereum-provider: QR modal doesn't close on error

### ISSUE THREAD

**Issue by alexdupre** [WalletConnect/walletconnect-monorepo#2003]
**Describe the bug**
If the session is rejected by the wallet (e.g. the required namespace is not supported or the user aborted the pairing) an uncaught exception is logged in browser console and the modal is not closed, but the same QRCode cannot be used anymore.

**SDK Version (if relevant)**
 - Client: ethereum-provider
 - Version 2.4.4

**To Reproduce**
1. Start pairing
2. Reject pairing on wallet
3. See the error in cosole, but the modal is still open
4. Scan the qrcode again

**Expected behavior**
The modal should be correctly closed and an error thrown (or the QRCode should remain usable).

**Screenshots**
![image](https://user-images.githubusercontent.com/3694371/219379050-fadef892-8b8a-4568-9593-534844d1c55c.png)

**Additional context**
Tested with a beta version of Bifrost wallet

**Comment by Velenir** [comment]
In my local testing the problem with QR modal not reacting to connection rejected on the Wallet stems from [signer.connect](https://github.com/WalletConnect/walletconnect-monorepo/blob/c643010944ff932cf33a9aff97647aff580bdeaa/providers/ethereum-provider/src/EthereumProvider.ts#L250-L260) error being swallowed. Need to rethrow it at the very least.
