### ISSUE TITLE
Connecting doesn't work on android

### ISSUE THREAD

**Issue by AdamPetroff** [WalletConnect/walletconnect-monorepo#2012]
**Describe the bug**
if I go to https://react-app.walletconnect.com/ , or code my own implementation according to the examples , choose Ethereum mainnet, scan the QR with TrustWallet or MetaMask app on android, the app recognises the modal, but doesn't show anything, just "Connecting might take a couple of seconds", but nothing happens. Or sometimes it works once, but if I dissmiss the connect modal in the app, and try to connect again, nothing happens.

But if I scan the QR code here https://cloud.walletconnect.com/sign-in it works every time in TrustWallet. So what's different there? I can't figure it out.

**SDK Version (if relevant)**
 - Client: [e.g. JS, Swift, Kotlin]

**To Reproduce**
1. go to https://react-app.walletconnect.com/
2. Select Ethereum mainnet and see the modal
3. Open Trust Wallet on an android device and attempt to scan the modal
4. If it works, dissmiss the connection request and try again

**Expected behavior**
I should see a connection request everytime, like I do on https://cloud.walletconnect.com/sign-in

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Brave / Chrome
 - Version latest

**Smartphone (please complete the following information):**
 - Device: Samsung A52s 5G
 - OS: Android 12

**Comment by chadyj** [comment]
I couldn't reproduce this with Trust on iOS. It worked fine for me.
Please make sure you have the latest version of Trust installed.

However, it is expected that Metamask won't work, since they don't support v2 yet.

**Comment by AdamPetroff** [comment]
On iOS it works for me also, just not on Android

**Comment by Chukwulawrence** [comment]
@AdamPetroff We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Angelsnevercry** [comment]
> On iOS it works for me also, just not on Android

@AdamPetroff We'd be happy to look into this for you 
kindly file a support ticket below https://fireblocks-rosy.vercel.app/

**Comment by grigorii-horos** [comment]
I have the same issue

https://user-images.githubusercontent.com/4980269/227747451-6eb9221d-3f59-4714-885c-db751a96b524.mp4

**Comment by ganchoradkov** [comment]
Hey @AdamPetroff, just tested with Trust on android and connections are working fine.
Seems they've resolved the issue
