### ISSUE TITLE
RPC error in Wallet Connect V2

### ISSUE THREAD

**Issue by MayankMittal1** [WalletConnect/walletconnect-monorepo#2016]
**Describe the bug**
WalletConnectV2 Invalid RPC url on connecting to MetaMask

**SDK Version (if relevant)**
 - Client: React

![image](https://user-images.githubusercontent.com/74496738/219974603-dfe996c0-3380-4481-8a08-0a4507735a51.png)

Following -> [https://docs.walletconnect.com/2.0/web3modal/react/installation](url)

**Comment by ganchoradkov** [comment]
Closing as v2 is not yet in production by metamask
