### ISSUE TITLE
I am using wallet connect SDk in my Expo app and using it in web mode in some android devices when I tried to connect metamask it opens in app webview instead of redirecting to my web app

### ISSUE THREAD

**Issue by wdcs-harshitpadalia** [WalletConnect/walletconnect-monorepo#2018]
**Describe the bug**
In the android device it is not redirecting  to my PWA it is opening web view instead 
**SDK Version (if relevant)**
"expo": "~47.0.8",
 "@walletconnect/react-native-dapp": "^1.8.0",
 "@walletconnect/web3-provider": "^1.7.5",

**To Reproduce**
1. Call wallet connect instanse's .connect method
2. Select metamask from app's selection model 
3. connect metamask 
4. it will redirect after connecting to the in-app web browser 

**Expected behavior**
It should redirect directly to my PWA app

**Video**
https://drive.google.com/file/d/1tWAr9WyBVtAGOAe4ujEhmVwDmnMQBqzv/view?usp=sharing

**Smartphone (please complete the following information):**
 - Device: mi a3
 - OS: Android 11
 - Browser chrome
 - Version 110.0.5481.65

**Additional context**

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
