### ISSUE TITLE
Websocket connection fails after a while

### ISSUE THREAD

**Issue by AlexandrosGounis** [WalletConnect/walletconnect-monorepo#2019]
**Describe the bug**
The following applies to connections between DApps and Wallet clients.
Leaving a tab open for a couple of hours, or merely toggling wifi off/on results in the following error:

```
Websocket connection to 'wss://relay.walletconnect.com/?auth=...' failed: The operation could not be completed. (error 54 - Connection reset by peer)
```
 
**SDK Version (if relevant)**
 - Client: JS

**Expected behavior**
Websockets should restore connections if there is any kind of interruption.

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Browser: Safari

**Comment by ganchoradkov** [comment]
Hey @AlexandrosGounis, thanks for the report!
 Which SDK version are you using?

**Comment by AlexandrosGounis** [comment]
> Hey @AlexandrosGounis, thanks for the report! Which SDK version are you using?

We are currently using `@walletconnect/sign-client@2.4.0` and `@walletconnect/utils@2.4.0`

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
