### ISSUE TITLE
 import @walletconnect/ethereum-provider in angular

### ISSUE THREAD

**Issue by Loque18** [WalletConnect/walletconnect-monorepo#2027]
**Describe the bug**
I am doing a web3 app in angular, I need to connect using the eth provider, (please don't suggets using web3modal or any library that handles the wallets, I need to do it this way)

here is the log of the errors 
```bat
Error: node_modules/@web3modal/core/dist/_types/src/controllers/ClientCtrl.d.ts:4:22 - error TS2307: Cannot find module '@web3modal/ethereum' or its corresponding type declarations.

4     client(): import("@web3modal/ethereum").EthereumClient;
                       ~~~~~~~~~~~~~~~~~~~~~

Error: node_modules/@web3modal/core/dist/_types/src/controllers/OptionsCtrl.d.ts:8:32 - error TS2307: Cannot find module '@wagmi/chains' or its corresponding type declarations.

8     getSelectedChain(): import("@wagmi/chains").Chain | undefined;
                                 ~~~~~~~~~~~~~~~

Error: node_modules/@web3modal/core/dist/_types/src/types/controllerTypes.d.ts:1:44 - error TS2307: Cannot find module '@web3modal/ethereum' or its corresponding type declarations.

1 import type { Chain, EthereumClient } from '@web3modal/ethereum';
```

**SDK Version (if relevant)**
 - Client: @walletconnect/ethereum-provider
 - Version ^2.4.4

**To Reproduce**
1. ng new web3-app
2. npm i "@walletconnect/ethereum-provider
3. import { EthereumProvider } from "@walletconnect/ethereum-provider";
4. See error in console

**Expected behavior**
to work lol

**Screenshots**
![image](https://user-images.githubusercontent.com/28642447/220439551-2a3b6478-dfef-4f39-b812-fb3214752430.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 110.0.5481.104 (Official Build) (64-bit)

**Additional context**
I get it to work with a workaround, but I can not use types, using the following 

```js
const { EthereumProvider } = require('@walletconnect/ethereum-provider');
```

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Try adding "`skipLibCheck": true` in the tscofing.json file.

Please reopen if you still encounter this issue with the latest version :)
