### ISSUE TITLE
Unsupported methods. connect(), namespace, methods should be an array of strings or empty array for no methods even though its declared in namespace

### ISSUE THREAD

**Issue by TheOpenXproject** [WalletConnect/walletconnect-monorepo#2045]
**Describe the bug**
Im getting Unsupported methods. connect(), namespace, methods should be an array of strings or empty array for no methods
although the methods array is declared.
**SDK Version (if relevant)**
 - Client: JS
 - Version 2
 - 

**To Reproduce**

import UniversalProvider from "@walletconnect/universal-provider";

 let sourceProvider = await UniversalProvider.init({
            logger: "info",
            projectId:"projectID", // REQUIRED your projectId
          });

 let namespace = {
              namespaces: {
                eip155: {
                  methods: [
                    "eth_sendTransaction",
                    "eth_signTransaction",
                    "eth_sign",
                    "personal_sign",
                    "eth_signTypedData"
                  ],
                  chains: ["eip155:10"],
                  events: ["chainChanged", "accountsChanged"],
                  rpcMap: {
                   10:
                      "https://rpc.walletconnect.com?allthestuff",
                  },
                },
                skipPairing: false, // optional to skip pairing ( later it can be resumed by invoking .pair())
              },
            }

await sourceProvider.connect(namespace);

**Expected behavior**
it should not throw an error since the methods array is declared inside the namespace

**Screenshots**

![image](https://user-images.githubusercontent.com/74208258/221353110-58a0301e-34d1-4671-b948-74597975e7fe.png)

![image](https://user-images.githubusercontent.com/74208258/221353130-a9646da9-456e-4515-87ba-4d1f13abeef4.png)

**Desktop (please complete the following information):**

using chrome atm.

**Smartphone (please complete the following information):**

NA

**Additional context**
Any help would be greatly appreciated. i dont know if its an actual bug or just something i missed.
thank you very much in advance !

**Comment by ganchoradkov** [comment]
Hey @TheOpenXproject, the error is thrown because of the param
`skipPairing: false, // optional to skip pairing ( later it can be resumed by invoking .pair())` in the config.

The validation is considering it as a namespace since it's on the same level as `eip155` and thus fails validation.
