### ISSUE TITLE
when using @walletconnect/ethereum-provider cannot pass in web3 modal options

### ISSUE THREAD

**Issue by wighawag** [WalletConnect/walletconnect-monorepo#2052]
**Describe the bug**
when using `@walletconnect/ethereum-provider` I cannot pass in `Web3Modal` options including the following
 - explorerAllowList
 - themeZIndex

**Expected behavior**
We should be able to pass in all the option we want for `Web3Modal` via the  `@walletconnect/ethereum-provider` init function

**Additional context**

See discussions
- https://discord.com/channels/492410046307631105/1079865498432438412
- https://discord.com/channels/492410046307631105/1078631528256520232

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
