### ISSUE TITLE
ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor

### ISSUE THREAD

**Issue by justinkchen** [WalletConnect/walletconnect-monorepo#2079]
**Describe the bug**
When trying to use EthereumProvider (latest version), I keep getting this error coming from `sign-client` . The built code seems to call `this ` before the `super` gets called. Any ideas?

![Screenshot 2023-03-08 at 9 45 48 AM](https://user-images.githubusercontent.com/1000741/223744297-ec41a664-d33f-475e-a183-4868107baea3.png)

**Comment by ganchoradkov** [comment]
Hey @justinkchen , are you trying to initialize the `EthereumProvider` using ` = new EthereumProvider` instead of the required `= await EthereumProvider.init`?

**Comment by justinkchen** [comment]
No I'm calling 

```
const provider = await EthereumProvider.init({
    projectId: PROJECT_ID,
    chains: [chainId],
  });

  await provider.connect();
  await provider.enable();

  const web3Instance = new Web3(provider)
```

The sign-client code looks fine in the repo....it just seems to be built with all the `this` references before the call to super which makes it error out for some reason

@ganchoradkov

**Comment by justinkchen** [comment]
Basically have been trying to migrate from the v1 web3provider option (https://docs.walletconnect.com/1.0/quick-start/dapps/web3-provider), we manage the connection ourselves so a bit harder to migrate completely to web3modal

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
