### ISSUE TITLE
Missing Module Folder

### ISSUE THREAD

**Issue by sunniebb** [WalletConnect/walletconnect-monorepo#2088]
**Describe the bug**
I am trying to implement `ThirdWebProvider` sdk in my NextJS typescript app.

Upon importing the provider, i got an error noting that there is a missing file or directory.

`./node_modules/@walletconnect/ethereum-provider/dist/esm/index.js`

The noted path above is what is missing. Is this something on your end?

**SDK Version (if relevant)**
 - Client: [e.g. JS, Swift, Kotlin]

**To Reproduce**
1. install
     "@thirdweb-dev/react": "^3.10.3",
    "@thirdweb-dev/sdk": "^3.10.3",
    "ethers": "^5.0.0",
2. import { ThirdwebProvider } from "@thirdweb-dev/react";
3. set provider
4. run app

**Expected behavior**
Should run properly

**Desktop (please complete the following information):**
 - OS: version 12.5
 - Browser Chrome
 - Version latest

**Additional context**

**Comment by ganchoradkov** [comment]
Hey @JackyLau215, I would suggest recreating the issue in the ThirdWebProvider repo as we have no control over third party implementations
