### ISSUE TITLE
Hanging promise and "We don't support the chainId" with @walletconnect/ethereum-provider

### ISSUE THREAD

**Issue by winter38** [WalletConnect/walletconnect-monorepo#2092]
**Describe the bug**
I am using @walletconnect/ethereum-provider with various chains (for eth and polygon it works fine).
When using OKEx (eip155:53) and trying to check net id 

```javascript
provider = await EthereumProvider.init({
                projectId: xxx",
                chains: [53]
            });
await ethereumProvider.connect();
...
const networkId = await web3.eth.net.getId(); // will cause hanging promise
```

I scan qr code from ImToken wallet with OKEx chain testnet - and i see request  with 400 error

rpc.walletconnect.com/v1/?chainId=eip155:53&projectId=xxx
Request:
jsonrp":"2.0", method: "net_version", params:[]
Response:
field: "chainId", description: "We don't support the chainId you provided: eip155:53"

**@walletconnect/ethereum-provider**
 - Client: js
 - Version 2.4.8

**Expected behavior**
Reject on error

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: firefox
 - Version: last

**Additional context**
1. Where can i find supported chains - if some chains are not supported (ETH based chains) - as error mentions about that.

**Comment by ganchoradkov** [comment]
Hey @winter38, the issue is happening because we (rpc.walletconnect.com) only support the major mainnets currently.
If you wish to use testnets, you should provide your own rpc provider using the `rpcMap` constructor param e.g.
```
...,
rpcMap: {
  53: 'https://testnet-rpc.coinex.net'
}
```
