### ISSUE TITLE
dApp automatically redirects to https://app.zerion.io/wc

### ISSUE THREAD

**Issue by xthang** [WalletConnect/walletconnect-monorepo#2094]
**Describe the bug**
Since today, when sending a request from a dApp to a wallet, the dApp immediately automatically redirects to https://app.zerion.io/wc

**To Reproduce**
1. Send a request from dApp to wallet
2. See error

**Comment by JesseKuntz** [comment]
@xthang I think I'm running into the same issue, but a couple of questions:
1. Desktop or Mobile?
2. Which request?
3. Which version of WC?

**Comment by kunj77** [comment]
I am facing the same issue. It happens as soon as I complete a connection to wallet. I am using @walletconnect/universal-provider v2.7.0. @xthang were you able to get around this issue?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
