### ISSUE TITLE
Does anyone know how to properly set Content Security Policy for Web3Modal?

### ISSUE THREAD

**Issue by hskang9** [WalletConnect/walletconnect-monorepo#2097]
### Discussed in https://github.com/orgs/WalletConnect/discussions/2084

<div type='discussions-op-text'>

<sup>Originally posted by **hskang9** March 10, 2023</sup>
I need to figure out which image src they use to render networks so that I can add it in `img-src` CSP.</div>

**Comment by ganchoradkov** [comment]
Hey @hskang9, I'm seeing that there's already a discussion going on so I'll go ahead and close the issue.
