### ISSUE TITLE
Dapp in mobile browser not connecting mobile wallet 

### ISSUE THREAD

**Issue by bejitono** [WalletConnect/walletconnect-monorepo#2099]
**Describe the bug**
We have an issue specifically related to connections coming from mobile browsers (Safari). When a user copies the WC url to clipboard and pastes the url in the mobile wallet, the wallet handles it and ultimately receives a confirmation that a connection has been established. But upon returning, the Dapp won't connect to the wallet. This issue doesn't occur 100% of the time but happens quite consistently.

**SDK Version (if relevant)**
 - Client: Swift

**To Reproduce**
1) On the Dapp (e.g. Zora) open the WC modal, select "QR code", and then copy to clipboard

2) Go back to the wallet and paste the URL. The wallet handles the request and establishes a connection through `func server(_ server: Server, shouldStart session: Session, completion: @escaping (Session.WalletInfo) -> Void)` by passing back the wallet info. 

3) We receive a confirmation that the connection has been established through `func server(_ server: Server, didConnect session: Session)`

4) Move back to the Dapp and the connection hasn't been established on the Dapp.

**Expected behavior**
Expecting the Dapp to have dismissed the WC modal and established a connection.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro 
 - OS: Latest iOS 
 - Browser: Safari

**Comment by tim-eucalyptus** [comment]
We think we might also be experiencing this issue.

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
