### ISSUE TITLE
react native: no authorized pop-up window

### ISSUE THREAD

**Issue by NicholasJupiter** [WalletConnect/walletconnect-monorepo#2101]
**Describe the bug**

When I call provider.enable(), it will redirect to the open popup and jump to click on the wallet application, but the authorization popup will not appear. However, connector.connect() can pop up the authorization popup. It's very strange.

**SDK Version (if relevant)**
 - Client: [e.g. JS, Swift, Kotlin]
 - "react-native": "0.71.3"
 - "@walletconnect/web3-provider": "^1.8.0"
 - "@walletconnect/react-native-dapp": "^1.8.0"
 - "@walletconnect/react-native-compat": "^2.4.9"

**To Reproduce**

**Expected behavior**

**Screenshots**
APP.jsx
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/34204576/225069975-c4123b57-6db1-4d5e-89e0-b1e9c8277af7.png">

wallet.jsx
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/34204576/225070638-7a1c9f06-d441-46da-ad83-b9793c7c9f7d.png">

<img width="796" alt="image" src="https://user-images.githubusercontent.com/34204576/225069916-ae4a8d00-3cff-4cb5-b0ba-2e97327cb67f.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - iphone XS

**Additional context**

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
