### ISSUE TITLE
@walletconnect/ethereum-provider: @web3modal/standalone should be in peerDependencies

### ISSUE THREAD

**Issue by nhardy** [WalletConnect/walletconnect-monorepo#2102]
**Describe the bug**
`@walletconnect/ethereum-provider` currently depends on `@web3modal/standalone`. Web3Modal, however, behaves as a singleton. If different versions are resolved in an application, this can cause subtle issues.

Should `@web3modal/standalone` be moved to the `peerDependencies` of `@walletconnect/ethereum-provider`?

I also note that Web3Modal has released breaking changes on minor version bumps. Does the dependency version need to be specified more precisely?

**Comment by xzilja** [comment]
`@walletconnect/ethereum-provider` with 2.5.0 was just published that makes this change 👍
