### ISSUE TITLE
Can only subscribe to a topic from one browser tab

### ISSUE THREAD

**Issue by klassare** [WalletConnect/walletconnect-monorepo#2104]
**Describe the bug**
Can only subscribe to a given topic from one browser tab at a time. Initiating a new client in a new browser tab will kill the subscription for the previous client that is still active in the other tab.

**SDK Version (if relevant)**
 - Client: JS
 - Version 2.4.5

**To Reproduce**
1. Go to the [example dapp](https://react-app.walletconnect.com)
2. Click on `Ethereum Goerli` and then `Connect`
3. Copy the URI into the clipboard
4. Open the [example wallet](https://react-wallet.walletconnect.com/walletconnect) in a new tab (**A**)
5. Paste the uri into the textbox and click `Connect`.
6. Approve the session proposal.
7. Click `personal_sign` from the dapp and see how the message show up in the wallet as expected.
8. Open the example wallet in a new tab (**B**), so you now have two active clients subscribing to the same topic.
9. Click on `personal_sign` and observe how the message will show up in tab **B**, but not **A**.
10. Close tab **B**.
11. Click `personal_sign` once again and observe that the message will not show up in the wallet (tab **A**).

**Expected behavior**
With a publish-subscribe pattern it is expected that multiple clients should be able to subscribe to the same topic.

That it's possible to get into a situation where the user have both the dapp and wallet open, but no messages will be received (as in step 11) is problematic. In a situation like this the user will assume that something is broken. Additionally, a user might have a web wallet open in multiple tabs and find it cumbersome to find out which tab received the message. Best would be if all wallet tabs could receive the messages.

**Comment by kantorcodes** [comment]
heyo, was this ever investigated?
