### ISSUE TITLE
TypeError: Cannot assign to read-only property 'error' (react native)

### ISSUE THREAD

**Issue by moseffect21** [WalletConnect/walletconnect-monorepo#2107]
**Describe the bug**
TypeError: Cannot assign to read-only property 'error' when i try to init UniversalProvider (or SignClient)

**SDK Version (if relevant)**
 - Client: React Native
 - Version 0.71.4

**To Reproduce**
1. install `@walletconnect/react-native-compat` & `@walletconnect/universal-provider`
2. create initHook like in rn dapp example
![image](https://user-images.githubusercontent.com/52028340/225326345-035836c9-1fae-4cd5-bb4b-2d459f318508.png)
![image](https://user-images.githubusercontent.com/52028340/225326611-4186b394-5aa2-4513-909c-ad15a2160447.png)

3. Use this hook when app started
![image](https://user-images.githubusercontent.com/52028340/225326758-e60f534b-13bc-478e-8082-095e2ccdb231.png)

**Comment by rastajpa** [comment]
same issue, could you solve it?

**Comment by moseffect21** [comment]
> same issue, could you solve it?

no

**Comment by victorLee11** [comment]
same issue

**Comment by victorLee11** [comment]
It feels like this bug comes from pino. When I only execute pino(), this error will be reported. walletconnect/logger relies on pino

**Comment by victorLee11** [comment]
node_modules/@walletconnect/logger/node_modules/pino/browser.js:57

  const logger = Object.create(proto)
  =>
  const logger = {...proto}

works for me

**Comment by YutaSugimura** [comment]
I've updated the versions of `@walletconnect/react-native-compat` to `2.8.1` and `@walletconnect/web3wallet` to `1.8.0` in my GitHub issue. After doing so, the errors have been resolved.

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
