### ISSUE TITLE
Not matching key. expirer 

### ISSUE THREAD

**Issue by dannpr** [WalletConnect/walletconnect-monorepo#2122]
**Describe the bug**
I'm currently having a trouble on my console log when I'm connecting my wallet with you demo dapp. I receive this : 

```console  
browser.js:201 {context: 'client'}context: "client"[[Prototype]]: Object 'No matching key. session: c09f3769f322b2d78d1278105028480ec8876a12b9c7cba3734e54965d760cc2'
```

and after I connect and receive this : 
```console
Uncaught (in promise) Error: No matching key. session: a98ff930b280688efa4094669454f218a4447bc0ad98f5364493a2976015fe15
    at Ze.getData (index.ts:14:1)
    at Ct.update (index.ts:14:1)
    at Qe.onSessionSettleResponse (index.ts:14:1)
    at Qe.onRelayEventResponse (index.ts:14:1)
```

I think it's a bug because My wallet is connecting to the dapp so I don't understand why I see that. 
**SDK Version (if relevant)**
 - Client: JS
 - Version  
    "@walletconnect/core": "^2.5.1",
    "@walletconnect/web3wallet": "^1.2.0",

**Screenshots**
![Capture_decran_2023-03-17_a_01 35 52](https://user-images.githubusercontent.com/47109543/225999352-f6b53be7-c655-47f8-8ff6-b6e1a1379782.png)
![Capture_decran_2023-03-17_a_01 35 28](https://user-images.githubusercontent.com/47109543/225999385-e644077d-ca51-4003-bd34-131de33171fd.png)

**Comment by sash20m** [comment]
I have the same problem. It sometimes does works and sometimes is doesn't. Mine is `No matching key. Keychain: ...`. Often times when I try to sign a transaction, that message appears and I do not know if it's something on the wallet app or my dapp.

**Comment by dannpr** [comment]
https://github.com/dannpr/intu-manage that's my github

**Comment by msophanith** [comment]
This problem happen to my dapp as well.
My package: `"@walletconnect/ethereum-provider": "^2.6.1"
    "@web3modal/standalone": "^2.2.2"`

**Comment by ggaabe** [comment]
This is also referenced at #1772

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)

**Comment by FatirPixpel** [comment]
I'm also having these issues. Has anyone resolved these issues yet?

**Comment by danaugrs** [comment]
Also seeing "No matching key. expirer: ..." on latest version. Any known fix?

**Comment by hammeiam** [comment]
Also seeing this!
