### ISSUE TITLE
WalletConnect login flow

### ISSUE THREAD

**Issue by losnappas** [WalletConnect/walletconnect-monorepo#216]
Hi,

For a login flow, one only needs `provider.enable()`, and `personal.sign()`. I am using https://github.com/web3connect/web3connect , and there are two problems:

I don't need an infura connection, but the param for @walletconnect/web3-provider is marked "required", and if I provide something like `{infuraId: "NOT_USED"}`, it starts spamming requests to infura every second, they all end up with 401.

Second, the bundle size gets rather big from all the stuff that I don't need.

Is there an easy way of grabbing `enable` and `personal.sign` without including unnecessary features? I gave creating a small WalletConnectProvider a go myself, but then came across a bunch of errors and thought I'd ask before falling into that rabbit hole.

**Comment by pedrouid** [comment]
It's much easier to use the WalletConnect client directly if you dont plan to use web3.js

**Comment by pchy10** [comment]
I am having the same issue.
