### ISSUE TITLE
EthereumProvider's chainId and eth_chainId request response do not match

### ISSUE THREAD

**Issue by xthang** [WalletConnect/walletconnect-monorepo#2160]
**Describe the bug**
This request returns 137:
```
const c = provider?.request({
  method: 'eth_chainId',
  params: [],
})
```
while provider.chainId is 80001

**SDK Version (if relevant)**
 - Client: ReactJS
 - Version 2.5.1

**Expected behavior**
eth_chainId request's response should always matches that provider's chainId

** Fix suggestion: EthereumProvider.ts
```diff
  private setChainIds(chains: string[]) {
    const compatible = chains.filter((x) => this.isCompatibleChainId(x));
    const chainIds = compatible.map((c) => this.parseChainId(c));
    if (chainIds.length) {
      this.chainId = chainIds[0];
      this.events.emit("chainChanged", toHexChainId(this.chainId));
      this.persist();
+++   this.setHttpProvider(this.chainId);
    }
  }

```

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
