### ISSUE TITLE
I want to move to the installation link when Metamask is not installed on mobile.

### ISSUE THREAD

**Issue by siosio34** [WalletConnect/walletconnect-monorepo#2171]
**Describe the bug**
When metamask is not installed, it does not go to the installation link.

**SDK Version (if relevant)**
 - Client: [e.g. JS, Swift, Kotlin]

**To Reproduce**
go walletconnect example site
1. https://react-app.walletconnect.com/
2. delete metamask app in your mobile phone
3. select connect wallet button

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] android galaxy 21
 - Browser [e.g. stock browser, safari] chrome

**Additional context**

**Comment by ganchoradkov** [comment]
Hey @siosio34, is metamask appearing in the list of wallets for you?
They're not yet supporting v2 so incompatibility is expected
