### ISSUE TITLE
web3wallet.on is not a function

### ISSUE THREAD

**Issue by SatheeshKumar1997** [WalletConnect/walletconnect-monorepo#2184]
ERROR
web3wallet.on is not a function
TypeError: web3wallet.on is not a function
    at App (http://localhost:3002/main.eed69bd9f2f92997b57a.hot-update.js:42:14)
    at renderWithHooks (http://localhost:3002/static/js/bundle.js:52295:22)
    at mountIndeterminateComponent (http://localhost:3002/static/js/bundle.js:55581:17)
    at beginWork (http://localhost:3002/static/js/bundle.js:56877:20)
    at HTMLUnknownElement.callCallback (http://localhost:3002/static/js/bundle.js:41887:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3002/static/js/bundle.js:41931:20)
    at invokeGuardedCallback (http://localhost:3002/static/js/bundle.js:41988:35)
    at beginWork$1 (http://localhost:3002/static/js/bundle.js:61862:11)
    at performUnitOfWork (http://localhost:3002/static/js/bundle.js:61109:16)
    at workLoopSync `(http://localhost:3002/static/js/bundle.js:61032:9)`

In the above code I have imported all the necessary packages and methods in react App function component, while executing the function the error "web3wallet.on is not a function" is thrown. 

App.js:

import React, { useEffect } from "react";
import { Core } from "@walletconnect/core";
import { Web3Wallet } from "@walletconnect/web3wallet";

const core = new Core({
  projectId: process.env.PROJECT_ID,
});

function App() {
  const web3wallet = Web3Wallet.init({
    core, // <- pass the shared `core` instance
    metadata: {
      name: "Demo app",
      description: "Demo Client as Wallet/Peer",
      url: "www.walletconnect.com",
      icons: [],
    },
  });
  console.log("web3wallet",web3wallet);

  web3wallet.on("session_proposal", async (proposal) => {
    console.log("proposal", proposal)
    const session = await web3wallet.approveSession({
      id: proposal.id,
      namespaces: {
        "requiredNamespaces": {
          "eip155": {
            "chains": ["eip155:1", "eip155:137"],
            "methods": ["eth_sendTransaction", "eth_signTransaction", "eth_sign", "get_balance"],
            "events": ["accountsChanged", "chainChanged"]
          },
          "eip155:10": {
            "methods": ["get_balance"],
            "events": ["accountsChanged", "chainChanged"]
          },
          "cosmos": {}
        },
        "optionalNamespaces": {
          "eip155:42161": {
            "methods": ["eth_sendTransaction", "eth_signTransaction", "get_balance", "personal_sign"],
            "events": ["accountsChanged", "chainChanged"]
          }
        }
      },
    });
    console.log("session", session)
  });
  return (
    <div>
      <button>
        Session Approval
      </button>
    </div>)
};
export default App;

**Comment by jeffsampaul** [comment]
I am also getting the same error

**Comment by ganchoradkov** [comment]
Hey @SatheeshKumar1997, I think the issue happening because you're not awaiting the `Web3Wallet.init` promise.

const web3wallet = `await` Web3Wallet.init({
core, // <- pass the shared core instance
metadata: {
name: "Demo app",
description: "Demo Client as Wallet/Peer",
url: "www.walletconnect.com",
icons: [],
},
});

@jeffsampaul is your issue the same?

**Comment by SatheeshKumar1997** [comment]
Hi @ganchoradkov thank you for your response. Now am getting a response for "Web3Wallet.init" , then I stored it in variable "web3wallet". After, I called web3wallet.on function but couldn't get any response ,

`web3wallet.on("session_proposal", async (proposal) => {`
`console.log("proposal", proposal)`
`const session = await web3wallet.approveSession({`
`id: proposal.id,`
`namespaces:` {...............

**Comment by ric344** [comment]
have you resolved this issue?
