### ISSUE TITLE
Solana VersionedTransaction is not compatible with sing transaction

### ISSUE THREAD

**Issue by lexer** [WalletConnect/walletconnect-monorepo#2188]
**Describe the bug**
Current [sign transaction api](https://docs.walletconnect.com/2.0/advanced/rpc-reference/solana-rpc#solana_signtransaction) is not compatible with new Solana [VersionedTransactions](https://github.com/solana-labs/solana-web3.js/blob/master/packages/library-legacy/src/transaction/versioned.ts#L17).

I suggest to introduce new parameters:
- serializedTransaction: string (base64 encoded Uint8Array)
- transactionVersion: string ("legacy", "0")

**SDK Version (if relevant)**
 - Client: [JS, Swift, Kotlin]
 - Version [2.6.2]

**To Reproduce**
1. Download and install Spot wallet. https://www.spot-wallet.com/ (WalletConnect Solana wallet)
2. Open Jupiter V2 dApp in your browser. https://v2.jup.ag/
3. See warning that VersionedTransactions are not supported.

**Expected behavior**
Versioned transactions should be supported since it's the new standard that all new Solana dApps are following.

**Screenshots**
![screen_shot_2023-04-05_at_9 36 10_am_720](https://user-images.githubusercontent.com/108267/230443986-851a7313-bb06-4273-9f9e-9edea30f8821.png)

**Desktop (please complete the following information):**
 - OS: [iOS, Android]
 - Browser [chrome, safari]

**Smartphone (please complete the following information):**
 - Device: [iPhone 13 Mini]
 - OS: [iOS 16]

**Additional context**
This will also require to update Solana Wallet Adapter integration that Solana dApp are using

https://github.com/solana-labs/wallet-adapter/blob/master/packages/wallets/walletconnect/src/adapter.ts

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
