### ISSUE TITLE
QI Blockchain new chain request

### ISSUE THREAD

**Issue by QIBlockchain** [WalletConnect/walletconnect-monorepo#2223]
1. JSON-RPC spec for Wallets:
  Fully EVM compatible. https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   **GitHub Link**:
https://github.com/ChainAgnostic/namespaces/tree/main/eip155
3. **namespaces**:
eip:155
4. **chains**:
eip155:9731 - mainnet
eip155:9732 - testnet

5. **RPC endpoints**
   mainnet:

    1. https://rpc-main1.qiblockchain.online
    2. https://rpc-main2.qiblockchain.online
    3. https://rpc-main3.qiblockchain.online

   testnet:

    1. https://testnetrpc.qiblockchain.online

6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
60 0x8000003c ETH

**Additional context**
We are happy to make a deep integration between QiBlockchain and WalletConnect.

**Comment by QIBlockchain** [comment]
@bkrem Hello!
Any updates? Everything is fine with our request?

**Comment by bkrem** [comment]
Hi @QIBlockchain,

Could you outline some wallets and/or dapps that have integrated or are working on integrating Qi?

**Comment by QIBlockchain** [comment]
@bkrem Hi,
We are working on android/ios QIE wallet. We need WalletConnect primarily for in-app web3 browser, but also after it we will integrate wallet connect into our dapps as alternative login method. 
Our ecosystem here: https://qiblockchain.online/#/explore-dapps
Thank you!

**Comment by notrtx** [comment]
Hello, Google Play approved our app. Waiting for your response.
https://play.google.com/store/apps/details?id=com.qiewallet 

Thank you!

**Comment by bkrem** [comment]
Added to https://cloud.walletconnect.com 👍
