### ISSUE TITLE
Mina Blockchain - new chain request

### ISSUE THREAD

**Issue by halsaphi** [WalletConnect/walletconnect-monorepo#2233]
1. JSON-RPC spec for Wallets:
Not an EVM based blockchain, is a zkp based blockchain. No current support for JSON-RPC however can use graphQL or the Rosetta API

graphQL: https://docs.minaprotocol.com/node-developers/graphql-api 
Rosetta: https://docs.minaprotocol.com/node-operators/rosetta

2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   see - https://github.com/ChainAgnostic/namespaces/pull/91 

3. namespaces: Mina
 
4. chains:
 Mina: Mainnet    - mainnet
 Mina: Devnet     -  testnet
 Mina: Berkeley   -  testnet

5. GraphQL endpoint
https://graphql.minaexplorer.com/
 
REST API
https://api.minaexplorer.com
https://docs.minaexplorer.com/rest-api/ref

6. [SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type:

12586 | 0x8000312a | MINA

**Additional context**
Please contact for additional information

Mina: Mainnet    - mainnet
https://docs.minaexplorer.com/minaexplorer/explore

Mina: Devnet     -  testnet
https://docs.minaexplorer.com/minaexplorer/testnet

Mina: Berkeley   -  testnet
https://docs.minaexplorer.com/minaexplorer/berkeley-testnet
https://api.minascan.io/node/berkeley/v1/graphql

**Comment by bkrem** [comment]
Hi @halsaphi,

Submission looks good in general but there doesn't seem to be a namespace spec in CASA:

> Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
> TBD

This is a requirement for us to continue with any chains in the Mina ecosystem.

**Comment by halsaphi** [comment]
hi @bkrem - will ping you once we have created the PR for the CASA namespace.

**Comment by bkrem** [comment]
@halsaphi bump on this if you still want to move forward 🙏

**Comment by halsaphi** [comment]
hi @bkrem, we would still like to move forward, just finalising our PR for the CASA namespace

**Comment by halsaphi** [comment]
hi @bkrem - just submitted the PR for the CASA namespace - https://github.com/ChainAgnostic/namespaces/pull/91

**Comment by bkrem** [comment]
> hi @bkrem - just submitted the PR for the CASA namespace - [ChainAgnostic/namespaces#91](https://github.com/ChainAgnostic/namespaces/pull/91)

Hi @halsaphi,

We need the spec to be merged before we can accept new namespaces/ecosystems in Cloud to avoid broken/incorrect configurations in the scenario where the spec ends up changing.

Please re-ping us here once the CASA spec is merged and we'll look into getting Mina added 👍

**Comment by bkrem** [comment]
Looks like the spec is close to merging here (cc @bumblefudge). Keeping this open.

**Comment by halsaphi** [comment]
hi @bkrem - the Mina CAIPs namespace spec has now been merged and is now available here : https://github.com/ChainAgnostic/namespaces/tree/main/mina
