### ISSUE TITLE
Add support for XRPL

### ISSUE THREAD

**Issue by antondalgren** [WalletConnect/walletconnect-monorepo#2249]
1. **JSON-RPC spec for Wallets**:
    https://github.com/TowoLabs/walletconnect-docs/commit/4a53d09226335f481d6aa33856b4c9c255a2049f
2. **CASA namespace**:
    https://github.com/ChainAgnostic/namespaces/tree/main/xrpl
3. **Namespaces**:
   `xrpl`
4. **Chains**:
   `xrpl:0` - livenet
   `xrpl:1` - testnet
   `xrpl:2` - devnet
    https://github.com/ChainAgnostic/namespaces/blob/main/xrpl/caip2.md#test-cases
5. **RPC endpoints**:
   https://xrplcluster.com/
   https://s2.ripple.com:51234/
   [More public RPC nodes](https://xrpl.org/public-servers.html)
7. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
   144

**Additional context**
Flare Network's StateConnector for cross-chain interoperability and use-cases such as [cross-chain NFT purchases](https://twitter.com/FlareNetworks/status/1628393124405075968) requires WalletConnect support for XRPL.

**Comment by antondalgren** [comment]
https://github.com/WalletConnect/walletconnect-docs/pull/634

**Comment by bkrem** [comment]
Thank you for the full spec for XRPL @antondalgren 🙏 

We've prepped this on our side and will have it on Cloud prod tomorrow once the rest of the team has returned from the public holiday (May Day) today.

**Comment by bkrem** [comment]
Added to https://cloud.walletconnect.com/ ✅
