### ISSUE TITLE
Add HBIT Blockchain

### ISSUE THREAD

**Issue by HashBitorg** [WalletConnect/walletconnect-monorepo#2256]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

JSON-RPC: https://rpc.hashbit.org
EXPLORER: https://explorer.hashbit.org
EIP-155
Name: HashBit Blockchain
Symbol: HBIT
ChainID: 11119

**Comment by bkrem** [comment]
Thanks for your submission, looks like there are still some data points missing here.

Please follow the template as shown here: https://github.com/WalletConnect/walletconnect-monorepo/issues/new?assignees=&labels=type%3A+new+chain+request&template=new_chain_to_explorer.md&title=

**Comment by bkrem** [comment]
Closing this as stale. If relevant please reopen with adherence to the template as noted above.
