### ISSUE TITLE
Add Razor Schain 

### ISSUE THREAD

**Issue by yohanelly95** [WalletConnect/walletconnect-monorepo#2274]
Adding a new chain to the Explorer
To get a new chain added to the Explorer, you will need to submit the following:

JSON-RPC spec for Wallets - Skale Chain has their implementation of rpc proxy.
GitHub Link: https://github.com/skalenetwork/skale-proxy

Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
GitHub Link: TBD

namespaces: eip:155
chains:
Razor Schain Testnet: eip155:1517929550
Razor Schain: eip155:278611351
RPC endpoints
1517929550: https://staging-v3.skalenodes.com/v1/staging-aware-chief-gianfar
278611351: https://mainnet.skalenodes.com/v1/turbulent-unique-scheat

[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type:
TBD

**Comment by bkrem** [comment]
Closing as stale
