### ISSUE TITLE
cors error when connect to wallet connect v2

### ISSUE THREAD

**Issue by lbhsot** [WalletConnect/walletconnect-monorepo#2276]
**Describe the bug**
There's a cors error when connect to wallet connect v2.

**To Reproduce**
1. use the wallet connect wallet example https://react-wallet.walletconnect.com/walletconnect and https://react-app.walletconnect.com/
2. select a chain, and copy the qrcode string in https://react-app.walletconnect.com/
3. paste to https://react-wallet.walletconnect.com/walletconnect to connect. 

**Expected behavior**
connect success

**Screenshots**
<img width="952" alt="image" src="https://user-images.githubusercontent.com/10987739/235101055-4fab3df0-c6a0-409a-8056-28c8c8a3ab00.png">

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [chrome]

**Additional context**
In my localhost there's same issue. And this morning I can connect to wallet connect v2 but now i cannot

**Comment by ganchoradkov** [comment]
Hey, this issue should be solved
