### ISSUE TITLE
IOS : RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by dingsq820** [WalletConnect/walletconnect-monorepo#2296]
code: `core.pairing.pair({ uri: wcuri })`

When pair to the dapp,an error was reported on IOS. Android is fine.
`ERROR  {"context": "core"} {"context": "core/relayer"} [RangeError: Maximum call stack size exceeded.]`

It seems that if the [walletconnect/core] package is v2.7.1, this error will be reported.

**Comment by dingsq820** [comment]
It happend even in sample wallet project.

https://github.com/WalletConnect/react-native-examples/tree/main/wallets/rn_cli_wallet_068_5

Reproduction:

Delete the content about "@walletconnect/xxx" in yarn.lock
Execute yarn install command to automatically obtain the latest version
Start the iOS app
When pairing, the console will prompt the following error
`ERROR  {"context": "core"} {"context": "core/relayer"} [RangeError: Maximum call stack size exceeded.]`

**Comment by Cali93** [comment]
Can you try to clear the storage of your device ?
I was facing the same issue but then I cleared the storage of the device on my emulator and it fixed the issue.

**Comment by dingsq820** [comment]
@Cali93 
I have tried to clear the device's storage, but this error still occurs

**Comment by dingsq820** [comment]
https://github.com/WalletConnect/react-native-examples/tree/main/wallets/rn_cli_wallet_068_5
Removing【BigInt】 from the following code provided in the example will not report this error
```
const TextEncodingPolyfill = require('text-encoding');
const BigInt = require('big-integer');

Object.assign(global, {
  TextEncoder: TextEncodingPolyfill.TextEncoder,
  TextDecoder: TextEncodingPolyfill.TextDecoder,
  BigInt,
});
```
