### ISSUE TITLE
Domain verification error

### ISSUE THREAD

**Issue by averytt** [WalletConnect/walletconnect-monorepo#2301]
### Discussed in https://github.com/orgs/WalletConnect/discussions/2294

<div type='discussions-op-text'>

<sup>Originally posted by **averytt** May  3, 2023</sup>
Hello,
Getting error on the dashboard: 

`Not found - DNS TXT verification record not found.`

We have confirmed the DNS record does exist on our domain for the last 14 days. 

Example:
`host -t TXT wallet-connect-dns-verification.thetatoken.org`

Returns (masked):
`wallet-connect-dns-verification.thetatoken.org descriptive text "5eebef4IS_THIS_SAFE_TO_SHARE_739d62a5f3"`

Thank you.</div>

**Comment by Cali93** [comment]
Resolved in https://github.com/orgs/WalletConnect/discussions/2294
