### ISSUE TITLE
Support subdomains for localhost in Allowed Domains

### ISSUE THREAD

**Issue by dev-bjoern** [WalletConnect/walletconnect-monorepo#2330]
**Is your feature request related to a problem? Please describe.**
In Wallet Connect Domain management settings we can add domains to allow wallet connect to connect to. localhost is allowed by default. However we use domains like `http://mainnet.localhost` in our local dev environment. Currently they do not work. We get an: `WebSocket connection closed abnormally with code: 3000 (Authorization error: Unauthorized: origin not allowed)` error.

**Describe the solution you'd like**
We would like subdomains to work with localhost on Allowed Domains.

**Additional context**
We use subdomains in localhost for local development because we use [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware#router-objectfunction) where this is encouraged.

Thank you for looking into it!

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
