### ISSUE TITLE
Add Maya Protocol

### ISSUE THREAD

**Issue by GiMa-Maya** [WalletConnect/walletconnect-monorepo#2345]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
   **GitHub Link**: 
https://docs.walletconnect.com/2.0/advanced/rpc-reference/cosmos-rpc
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   **GitHub Link**:
Cosmos
3. **namespaces**:
   _\*known chain namespaces (e.g. eip:155 for Ethereum/EVM-based chains, solana, ...)_
Cosmos

4. **chains**:
   _\*known chains, where the primary key is a compound key composed of namespace + reference (e.g. ETH mainnet is eip155:1)._
   _Please provide labels for each chain (e.g. mainnet, testnet, devnet, ...)_

mayachain-mainnet-v1
mayachain-stagenet-v1

5. **RPC endpoints**
   _\*list of common/canonical RPC endpoints for the chain(s)_
https://mayanode.mayachain.info/mayachain/doc Raw blockchain data provided by the MAYAChain state machine. MAYAChain wallets and block explorers will query MAYAChain-specific information here.
https://tendermint.mayachain.info/ The Tendermint RPC allows Tendermint consensus information to be returned.
https://midgard.mayachain.info/v2/doc Consumer information relating to swaps, pools, and volume. Dashboards will primarily interact with Midgard.
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
   _\* slip44 coin type used in the namespace_

931 - Maya Protocol uses the same coin type as THORChain.

**Additional context**
Maya Protocol is the 2nd multi-chain DEX in the market: a decentralized liquidity protocol forked from THORChain that coordinates asset movement, including processing swaps, stakes, and more, without the need to peg or wrap assets. Additionally, it is open-source, so it is community-owned and protected by code you can audit.
https://www.mayaprotocol.com
https://linktr.ee/mayaprotocolassets

**Comment by bkrem** [comment]
Added to https://cloud.walletconnect.com 👍
