### ISSUE TITLE
Module not found: Error: Can't resolve 'react-native' 

### ISSUE THREAD

**Issue by RivetParallel** [WalletConnect/walletconnect-monorepo#2351]
**Describe the bug**
Module not found: Error: Can't resolve 'react-native' in "node_modules/@walletconnect/universal-provider/dist" when i build application

**SDK Version (if relevant)**
    "@web3modal/ethereum": "^2.4.1",
    "@web3modal/react": "^2.4.1",
    "react-scripts": "^5.0.1",

**Comment by ValiKTHD** [comment]
Was just about to open the same issue.

**Comment by arakelovd** [comment]
Duplicate of or related to this issue:

https://github.com/WalletConnect/walletconnect-monorepo/issues/2313

**Comment by bkrem** [comment]
Thanks @virtuaone, consolidating discussion into #2313
