### ISSUE TITLE
Error: Relay Protocol not supported: undefined in React Native app

### ISSUE THREAD

**Issue by iGroza** [WalletConnect/walletconnect-monorepo#2358]
## Issue Summary

When attempting to connect to the https://example.walletconnect.org demo using the Web3Wallet SDK package in my React Native application, I encounter the following error:

```
 {"context": "core"} {"context": "core/relayer"} {"context": "core/relayer/subscription"} [Error: Relay Protocol not supported: undefined]
```

## Environment

The following versions of the WalletConnect SDK are being used in my React Native app:

```
"@walletconnect/core": "2.7.2",
"@walletconnect/sign-client": "2.7.2",
"@walletconnect/utils": "2.7.2",
"@walletconnect/web3wallet": "1.7.0",
"@walletconnect/react-native-compat": "2.7.2"
```

My code of WalletConnect part in my React Native app is identical to the example in this repository: https://github.com/WalletConnect/web-examples/blob/main/wallets/react-web3wallet/src/utils/WalletConnectUtil.ts

To test my WalletConnect setup, I have used both https://example.walletconnect.org (v1) and https://react-app.walletconnect.com (v2).

## Expected behavior

I expect to be able to connect to the https://example.walletconnect.org demo without encountering any errors.

## Actual behavior

When attempting to connect to https://example.walletconnect.org, I encounter the error described above.

## Reproduction Steps

1. Open the [WalletConnectUtil.ts](https://github.com/WalletConnect/web-examples/blob/main/wallets/react-web3wallet/src/utils/WalletConnectUtil.ts) file from the WalletConnect web-examples repository
2. Copy the code and paste it into a React Native app that is using the  Web3Wallet SDK versions listed above
3. import `@walletconnect/react-native-compat` shims at main index.js file
4. Attempt to connect to the https://example.walletconnect.org demo using the app
5. Observe the error

## Additional Information

The repository mentioned above has a working web application at https://react-wallet.walletconnect.com/walletconnect, where both examples, https://example.walletconnect.org/ (v1) and https://react-app.walletconnect.com/ (v2), work without any errors. How can I achieve the same result in my React Native app?

**Comment by ganchoradkov** [comment]
Hey @iGroza , as mentioned by @ignaciosantise in this comment
https://github.com/WalletConnect/react-native-examples/issues/49#issuecomment-1538468720
you're trying to pair v1 with v2 which is not possible. Please test with https://react-app.walletconnect.com/
