### ISSUE TITLE
Module not found: Error: Can't resolve 'react-native'

### ISSUE THREAD

**Issue by mr-new-0509** [WalletConnect/walletconnect-monorepo#2361]
Hello, ladies and gentlemen. :D

This is the source.
https://github.com/mr-new-0509/scotty-the-ai-swap

I tried to build the project but faced this error.
`Module not found: Error: Can't resolve 'react-native' in 'D:\...\scotty-the-ai-swap\node_modules\@walletconnect\universal-provider\dist'`

Could you let me know how to fix this?

Thank you.

**Comment by bkrem** [comment]
Duplicate of #2351
