### ISSUE TITLE
Add support for Koinos blockchain

### ISSUE THREAD

**Issue by roaminro** [WalletConnect/walletconnect-monorepo#2370]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets:
The Koinos blockchain uses Bitcoin legacy addresses and so "wallets" are free to create and the process is done offline (without any JSON-RPC call). The link below is used to describe all the available JSON-RPC specs:
   **Link**: https://docs.koinos.io/rpc/json-rpc/
3. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   **GitHub Link**: https://github.com/ChainAgnostic/namespaces/tree/main/koinos
4. **namespaces**:
   `koinos`
5. **chains**:
    - Mainnet: `koinos:EiBZK_GGVP0H_fXVAM3j6EAuz3-B-l3e` 
    - Harbinger (testnet): `koinos:EiAAKqFi-puoXnuJTdn7qBGGJa8yd-dc`
6. **RPC endpoints**
    - Mainnet: `https://api.koinos.io`
    - Harbinger (testnet): `https://harbinger-api.koinos.io`
7. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
    | Coin type  | Path component (`coin_type'`) | Symbol  | Coin                              |
    | ---------- | ----------------------------- | ------- | --------------------------------- |
    | 659        | 0x80000293                    | KOIN    | Koinos                            |

 **Additional context**
https://koinos.io/
https://koinos.io/unified-whitepaper/
https://koiner.app/ecosystem

**Comment by roaminro** [comment]
Hello!

Could you let me know if you need anything else from me in order to move this request forward?

Thanks!

**Comment by bkrem** [comment]
Hey @roaminro,

Just reviewed, think we're ready to go here 👍 Will notify here again and close once it's been added to Cloud (likely Monday).

FYI the docs link you posted above seems to 404 but I'm assuming it was supposed to be this https://docs.koinos.io/rpc/json-rpc/

**Comment by roaminro** [comment]
The Koinos team changed the docs last week and I indeed forgot to come here and update the link, thanks for pointing that out!

This is very exciting, thanks for your help @bkrem!

**Comment by bkrem** [comment]
Added to https://cloud.walletconnect.com/ 👍
