### ISSUE TITLE
Add BeanEco SmartChain

### ISSUE THREAD

**Issue by briannichols0702** [WalletConnect/walletconnect-monorepo#2389]
Mainnet
BeanEco SmartChain
Chain ID: 535037 - 0x829FD
RPC : https://mainnet-rpc1.bescscan.io/
https://mainnet-rpc.bescscan.io/
Symbol: BESC 
Explorer : https://bescscan.io 

Graph Node : https://thegraph.bescscan.io
Staking : https://staking.bescscan.io  
Status : https://status.bescscan.io
BOT API : https://bot.bescscan.io
Docs : https://docs.bescscan.io    
   
TESTNET
Chain ID: 892272 - 0xD9D70
RPC : https://testnet-rpc.bescscan.io 
Explorer : https://testnet-explorer.bescscan.io 
Faucet : https://faucet.bescscan.io

DEX INFO BESC

Factory- 0x1CF1AFbD46A9bB1e584Da39A9205193169A7A2c7

Router- 0xB2cD91b79df296ea181AA5f6d729E5136e1853A4

Main Dex: https://BeanSwap.finance/swap

**Comment by briannichols0702** [comment]
Does this look right to add our chain it’s audited by certik as well

**Comment by Cali93** [comment]
Please use and follow our [template issue](https://github.com/WalletConnect/walletconnect-monorepo/issues/new?assignees=&labels=type%3A+new+chain+request&template=new_chain_to_explorer.md&title=) when requesting to add a chain.

**Comment by bkrem** [comment]
Closing as stale.

Please update in line with the template as indicated above and we'll reopen or open a new request following the template.
