### ISSUE TITLE
Add THORChain

### ISSUE THREAD

**Issue by GiMa-Maya** [WalletConnect/walletconnect-monorepo#2391]
**Adding a new chain to the Explorer**
Adding a new chain to the Explorer
To get a new chain added to the Explorer, you will need to submit the following:

JSON-RPC spec for Wallets (only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist). For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
GitHub Link:
https://docs.walletconnect.com/2.0/advanced/rpc-reference/cosmos-rpc

Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
GitHub Link:
Cosmos

namespaces:
*known chain namespaces (e.g. eip:155 for Ethereum/EVM-based chains, solana, ...)
Cosmos

chains:
*known chains, where the primary key is a compound key composed of namespace + reference (e.g. ETH mainnet is eip155:1).
Please provide labels for each chain (e.g. mainnet, testnet, devnet, ...)

thorchain-mainnet-v1
thorchain-stagenet-v1

RPC endpoints
*list of common/canonical RPC endpoints for the chain(s)
https://thornode.thorswap.net/thorchain/doc Raw blockchain data provided by the THORChain state machine. THORChain wallets and block explorers will query THORChain-specific information here.
https://rpc.thorswap.net/ The Tendermint RPC allows Tendermint consensus information to be returned.
https://midgard.thorswap.net/v2/doc Consumer information relating to swaps, pools, and volume. Dashboards will primarily interact with Midgard.
[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type:
* slip44 coin type used in the namespace
931 

Additional context
THORChain is a decentralised cross-chain liquidity protocol that allows users to add liquidity or swap over that liquidity. It does not peg or wrap assets. Swaps are processed as easy as making a single on-chain transaction. 
THORChain works by observing transactions to its vaults across all the chains it supports. When the majority of nodes observe funds flowing into the system, they agree on the user's intent (usually expressed through a memo within a transaction) and take the appropriate action.

https://thorchain.org

**Comment by bkrem** [comment]
Added to https://cloud.walletconnect.com/ 👍
