### ISSUE TITLE
`qrcode_modal_1.default.open is not a function` on latest web3-provider

### ISSUE THREAD

**Issue by everettwho** [WalletConnect/walletconnect-monorepo#240]
Hi there,

We recently upgraded `@walletconnect/web3-provider` in our app from `1.0.0-beta.37` to `1.0.0-beta.64`, but are now getting the following error upon calling `provider.enabled()`: `qrcode_modal_1.default.open is not a function`, which prevents the QR modal from popping up.

Reverting the package back to the older version solves this issue.

**Comment by pedrouid** [comment]
Hey @everettwho, I've experienced this yesterday, it looks like it started happening with beta.63 so you could downgrade to either beta.62 or keep using the latest stable version beta.47

**Comment by pedrouid** [comment]
Actually can you give beta.65 a try instead? I just pushed a fix for it

**Comment by everettwho** [comment]
@pedrouid Thank you! Just updated to `beta.65` and the modal works perfectly now
