### ISSUE TITLE
Issues running nodejs example

### ISSUE THREAD

**Issue by rhlsthrm** [WalletConnect/walletconnect-monorepo#241]
I'm trying to run a basic node.js example of WalletConnect using the [quickstart](https://docs.walletconnect.org/quick-start/dapps/node).

Seeing this [issue](https://github.com/WalletConnect/walletconnect-monorepo/issues/229) I decided to use the @next version of walletconnect.

I saved it as a `.ts` file and I'm trying to run it using `ts-node` so that the transpiling works out of the box.

First try, I get the following error:

```
TSError: ⨯ Unable to compile TypeScript:
src/wctest.ts:15:7 - error TS2322: Type '{ description: string; url: string; icons: string[]; name: string; ssl: boolean; }' is not assignable to type 'IClientMeta'.
  Object literal may only specify known properties, and 'ssl' does not exist in type 'IClientMeta'.

15       ssl: true
         ~~~~~~~~~
```

If I remove the SSL option, I get another error:

```
ts-node src/wctest.ts

/Users/rahul/dev/repos/moloch/moloch-bot/node_modules/@walletconnect/qrcode-modal/lib/webpack:/WalletConnectQRCodeModal/Users/pedrogomes/_walletconnect/walletconnect-monorepo/node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js:93
  var style = document.createElement('style');
```

If I comment out the open model part of the code and simply try to console log the URI, I get another error:

```
ReferenceError: window is not defined
    at new NetworkMonitor (/Users/rahul/dev/repos/moloch/moloch-bot/node_modules/@walletconnect/socket-transport/src/network.ts:11:50)
    at new SocketTransport (/Users/rahul/dev/repos/moloch/moloch-bot/node_modules/@walletconnect/socket-transport/src/index.ts:39:43)
    at new Connector (/Users/rahul/dev/repos/moloch/moloch-bot/node_modules/@walletconnect/core/src/index.ts:146:7)
```

Am I doing something wrong? I was under the impression I could run this example in a node environment.

**Comment by rhlsthrm** [comment]
I was able to get around this particular issue by using this library: https://github.com/tgorka/node-window-polyfill.

I got the URI to print using this polyfill, however I can't do anything with the printed URI since it's something like: wc:9fb341f8-a815-4b10-911d-3f042dec7f7f@1?bridge=https%3A%2F%2Fbridge.walletconnect.org&key=0ebea55343db02bc0481558c4e29ca45cd2ae6e715ea7259e1d9ef31a5819ed6.

Any ideas on how I can open this in a browser? Basically what I want to do is generate a QR for a user to connect (they can paste the URL into their own browser) from a Node program. When the QR is scanned, their account should be connected.

**Comment by rhlsthrm** [comment]
I think I got it working by copying some of the code I needed from the QR libs. I'll leave this open as a note to update the docs unless you think it's better I close it @pedrouid.

**Comment by pedrouid** [comment]
Thanks, this needs to be fixed urgently. Neither of these issues should exist:
* ssl param should be removed from documentation
* qrcode-modal bundling issue needs to be fixed
* window is not defined should never block node client

**Comment by pedrouid** [comment]
This has been improved but still having issues with the qrcode-modal bundle which is blocking this. Will try to fix this within the next couple of weeks

**Comment by pedrouid** [comment]
Fixed!
