### ISSUE TITLE
Web3Modal doesn't work on live server but works locally;

### ISSUE THREAD

**Issue by mavenharry1** [WalletConnect/walletconnect-monorepo#2424]
### Discussed in https://github.com/orgs/WalletConnect/discussions/2423

<div type='discussions-op-text'>

<sup>Originally posted by **mavenharry1** May 19, 2023</sup>
I get an error when trying to interact with any contract once I push my code to live server. this happens for all contracts and I see this error message.

<img width="524" alt="Screenshot 2023-05-19 at 1 49 36 PM" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/75600248/727ce5c1-db42-4487-9d2b-30ab6869aea9"></div>

**Comment by ganchoradkov** [comment]
Hey @mavenharry1 closing the issue here to keep the conversation in the discussion
