### ISSUE TITLE
Can't see accept button in the mobile wallet after scan qr code to connect walletconnect connector.

### ISSUE THREAD

**Issue by tiger-525** [WalletConnect/walletconnect-monorepo#2426]
## Describe the bug
When I scan QR code to connect walletconnect connector in the iPhone's metamask app, I can't receive any response from the walletconnect server in the iPhone's metamask app.
So I can't see the accept button in the iPhone's metamask app

## SDK Version 
 - Client: [react.js]
 - Version [wagmi@0.12.12]

## Install package
npm install wagmi@0.12.12

## react code
import { mainnet } from 'wagmi';
import { WalletConnectConnector, useConnect } from 'wagmi/connectors/walletConnect';

const walletConnectConnector = new WalletConnectConnector({
    chains: [mainnet],
    options: {
        projectId: 'WALLETCONNECT_PROJECTID',
        isNewChainsStale: false
    }
});
const {connect} = useConnect();
...
function connectToWalletConnect() {
   connect({connector: walletConnectConnector });
}

## To Reproduce
1. When I implement walletconnect connection by using above code, qr code was shown.
![Screenshot_1](https://github.com/WalletConnect/walletconnect-monorepo/assets/55833057/5a956ef4-db5d-49e8-b3c0-367528b2d439)

2. when I scan this qr code in the iPhone's metamask app, I can't receive any response from walletconnect server in the iphone metamask app. I can't see the accept button in the iPhone's metamask app.

I think that walletconnect server does not response or response with incorrect format

**Comment by hernandoagf** [comment]
I'm having the same issue. The problem seems to be only with MetaMask as I tested with the Ledger iPhone app and it works well

**Comment by heebaebang** [comment]
[Metamask support in v2 is scheduled for June 15.](https://medium.com/walletconnect/weve-reset-the-clock-on-the-walletconnect-v1-0-shutdown-now-scheduled-for-june-28-2023-ead2d953b595)
You can also check the list of v2 supported wallets at the [link](https://walletconnect.com/explorer?version=2).
For now, only v1 supports metamasks.

**Comment by ganchoradkov** [comment]
as @hernandoagf pointed out, Metamask doesn't support v2 in prod yet.
