### ISSUE TITLE
@walletconnect/core cannot run in the background of ChromeExtension.

### ISSUE THREAD

**Issue by PaDuckk** [WalletConnect/walletconnect-monorepo#2437]
**Describe the bug**

Currently, WalletConnect's "@walletconnect/core" cannot run in the background of ChromeExtension. The reason seems to be that the background runtime is a service worker. I can run it in the popup UI, but I have to click on the Chrome Extension icon to keep the window open to receive post-connect requests. Is there any way to receive post-connect messages in the background of the Chrome Extension?

**To Reproduce**

```tsx
// run in serviceworker
const core = new Core({
  projectId: process.env.PROJECT_ID,
})
```

// {context: 'core'} {context: 'core/relayer' } TypeError: socket.on is not a function

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- Macos chrome

**Smartphone (please complete the following information):**

**Additional context**
Chrome web extension 

I don't think the core module should necessarily run in the background of the chrome extension, but if there is an alternative to solve my problem, I would appreciate it.

**Comment by ganchoradkov** [comment]
Hey @PaDuckk, it's possible to run WalletConnect in a service worker albeit a bit tricky.
1.   You have to build your service worker `.js` file that imports WalletConnect deps with webpack (i've used webpack, other packagers should work fine as well)
2. setup listeners so the service worker can communicate with your popup

Example flow sending requests **from** your extension:
1. generate the requests in your popup.js
2. send the requests to your service worker
3. once received by the service worker, send it with the WalletConnect SDK 


Example flow sending requests **to** your extension:
- subscribe for incoming WalletConnect requests in your service worker
- once a request is received, send it to your popup.js

If your extension is a wallet, you have to make sure to keep your service worker active for the socket connection. Iirc Chrome kills it every ~5 mins to save resources. One way to do it is to inject a js file to the webpage to listen for your service worker `disconnect` so you can reboot it

I've used this approach successfully in the past and hope it will help you.

Closing the issue but feel free to comment if you have any questions.

**Comment by jonandgon** [comment]
@ganchoradkov do you have an example of what importing deps in webpack would look like? I'm using vite and I imagine it's similar.
