### ISSUE TITLE
Handshake failure in Trust Wallet

### ISSUE THREAD

**Issue by AiFreeWay** [WalletConnect/walletconnect-monorepo#244]
Hello! I try to implement walletconnect in my dapp website like in this quide: https://docs.walletconnect.org/quick-start/dapps/web3-provider. 
I display QR code in the dapp and try scan it with TrustWallet for initialize session, but I get "Handshake failure". Whats wrong? 
I use "@walletconnect/web3-provider": "^1.0.0-beta.47", and init Dapp with default infuraId: "27e484dcd9e3efcfd25a83a78777cdf1"

**Comment by pedrouid** [comment]
This is new. Thanks for reporting, I will try to get it reproduced

**Comment by AiFreeWay** [comment]
Pedro, tell me please is WalletConnect work correctly now, I mean server side?

**Comment by gabmontes** [comment]
Happened to me too. After a few retries, it worked 🤷‍♂️
