### ISSUE TITLE
Ethereum provider bad error handling

### ISSUE THREAD

**Issue by Benjythebee** [WalletConnect/walletconnect-monorepo#2449]
**Describe the bug**
Inside EthereumProvider.ts, method `initialize` has a try catch around the following code:
```
const {Web3Modal}  = await import("@web3modal/standalone");
          this.modal = new Web3Modal({
            walletConnectVersion: 2,
            projectId: this.rpc.projectId,
            standaloneChains: this.rpc.chains,
            ...this.rpc.qrModalOptions,
          });
```
and the catch will throw an error that will say `To use QR modal, please install @web3modal/standalone package`

However, this error naively assumes the error is with the import, and not the class instancing;

I've found this bug when using another web3 library that nerfed `crypto.randomUUID` and therefore `new Web3Modal()` would instantly fail and would spit out this error saying my import was bad, it really did not help in debugging.

**SDK Version (if relevant)**
 - Client: JS
 - Version 2.0

**Expected behavior**
Error `To use QR modal, please install @web3modal/standalone package` should be appearing when the import fails; not when the instancing fails;

**Comment by bkrem** [comment]
Closing since related PR #2450 has been merged and released.
