### ISSUE TITLE
NativeScript client

### ISSUE THREAD

**Issue by tahpot** [WalletConnect/walletconnect-monorepo#246]
I see there is a React Native client, however we are looking to use a Vue.js + Nativescript tech stack.

Is there plans for a NativeScript client or is it easy enough to use the `core` client out of the box?

**Comment by pedrouid** [comment]
Hey @tahpot, there isn't a plan currently to build a NativeScript client but you could definitely use the `core` client to build one! You can see that there are helper libraries to compose the required libraries for crypto which is basically the only thing that is platform-dependent.

Let me know if this is helpful!

**Comment by tahpot** [comment]
Thanks @pedrouid, I'm trying to piece this together so please bear with me :)

Are you able to give me a built more detail on how to go about this?

Is it a case of creating a NativeScript version of this file?

https://github.com/WalletConnect/walletconnect-monorepo/blob/next/packages/clients/react-native/src/index.ts

If so, I see that file is basically just using Node's `crypto` module which I believe NativeScript also supports. As such, the react native implementation should likely work in NativeScript as well?

**Comment by pedrouid** [comment]
In that case, I believe it should be able to work if it uses NodeJS crypto modules

**Comment by tahpot** [comment]
Thanks. I'll let you know how we get on.
