### ISSUE TITLE
Urgent: Wallect Connect V2 has significant design issues

### ISSUE THREAD

**Issue by metabaseex** [WalletConnect/walletconnect-monorepo#2467]
**Is your feature request related to a problem? Please describe.**
The V2 version relies too heavily on @web3modal/standalone,wagmi while managing dependency packages, resulting in other non-React language development packages being forced to adapt to the React language environment, causing numerous problems. This is very unscientific and does not conform to loosely coupled design. The V1 version is very good on this issue.

**Describe the solution you'd like**
Like @wallectconnect/web3-provider, **V2's ethereum provider can be designed just a basic protocol for wallet-connect,no web3modal,no wagmi.**
because i don't want to use them of all. Thanks.

**Comment by ganchoradkov** [comment]
hey @metabaseex, v2's `ethereum-provider` can be used without web3modal-standalone, you just need to set `showQrModal` to `false`. Also wagmi, doesn't come bundled with standalone afaik
https://www.npmjs.com/package/@web3modal/standalone?activeTab=dependencies
