### ISSUE TITLE
[Serious]V2 API is designed so unscientific for using a lot of third libs

### ISSUE THREAD

**Issue by metabaseex** [WalletConnect/walletconnect-monorepo#2474]
**Is your feature request related to a problem? Please describe.**
V2 API is designed so unscientific for using a lot of third libs.This is very unfriendly to non-react language.
A lot of problems.

**Describe the solution you'd like**
Ethereum API must be a basic protocol,not full function sdk.
please remove @web3modal,wagmi....

**Comment by ganchoradkov** [comment]
Hey @metabaseex, you can use v2 without any UI e.g. in node. 
If there is a specific issue you're facing with the implementation, please create an issue and we'll help.
