### ISSUE TITLE
Support multiple languages in QR code modal

### ISSUE THREAD

**Issue by xiaowheat** [WalletConnect/walletconnect-monorepo#248]
Does wallet connect support multiple languages in QR code modal?

**Comment by pedrouid** [comment]
Great idea, I should've done this a long time go 👍 Thanks for opening this issue

**Comment by pi0neerpat** [comment]
Looking forward to that v1.1.0 !!!

**Comment by finessevanes** [comment]
Closing issue since this has been completed.
