### ISSUE TITLE
Add <Ella the heart> chain

### ISSUE THREAD

**Issue by xxsl** [WalletConnect/walletconnect-monorepo#2488]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

- namespaces:
> eip:155

- chains:
> eip155:7027 (mainnet)

- RPC endpoints
> https://rpc.ella.network (mainnet)

**Additional context**
- See https://ella.network for more details.
- Listed by https://github.com/ethereum-lists/chains

**Comment by Cali93** [comment]
Hello,

Can you also provide the [SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type ?

**Comment by xxsl** [comment]
Hi @Cali93 ,
Sure, I opened a pull request there [https://github.com/satoshilabs/slips/pull/1566](https://github.com/satoshilabs/slips/pull/1566)

slip-0044.md:
| Coin type  | Path component (`coin_type'`) | Symbol  | Coin                              |
| ---------- | ----------------------------- | ------- | --------------------------------- |
| 7027       | 0x80001b73                    | ELLA    | Ella the heart                    |

**Comment by xxsl** [comment]
Hello @Cali93 

Got merged there now

Regards,
