### ISSUE TITLE
Project switch form web3 provider to ethereum provider, newtwork ChainId is not follow the app current one

### ISSUE THREAD

**Issue by windatang** [WalletConnect/walletconnect-monorepo#2491]
package.json version is 
```json
    "@walletconnect/ethereum-provider": "2.7.4",
    "@walletconnect/universal-provider": "2.7.4",
    "@web3modal/standalone": "^2.3.7",
```
register event is 
```ts
   provider.on("connect", _onAccountChange);
    provider.on("session_update", _onAccountChange);
    provider.on("chainChanged", _onAccountChange);
    provider.on("session_delete", onDisconnect);
    provider.on("disconnect", onDisconnect);
    provider.on('message', onMessage)
```
Problem:
When My iMtoken  wallet is on `Abitrum` or `Goerli ` the connect chain Id should change to `5` or other, but it alway keeping on `1`
Also when I call the `getChainId()` method the return value is `1` does't matter it is sync or async
Which the chain Id can changed follow the mobile app session sync one.

Another question is allow ethereum-provider change to own served relay.  `wss://MYHOST.com/relay`

**Comment by glitch-txs** [comment]
v2 is multichain, you need to connect to all required chains at the same time on first connection, then the wallet doesn't need to switch chains because it's already connected. You do set/change the default chain from the dapp though, you can call the usual `wallet_switchEthereumChain` method with the provider

**Comment by windatang** [comment]
but how web sync with app， double way， mobile -> i web & web -> mobile

**Comment by windatang** [comment]
but how web sync with app， double way， mobile -> i web & web -> mobile

**Comment by glitch-txs** [comment]
mobile is already sync-ed to all chains you connected to in first place

**Comment by windatang** [comment]
> mobile is already sync-ed to all chains you connected to in first place
But what you mean mobile should response all chain:
- case 1: web app support two network, `Ethereum Mainnet` & `Arbitrum Internal`.  a Mobile app wish to connect it But it only response, then connection will failed
- case 2: follow the case 1 even if the Mobile app like  `imtoken` support both network. when user change Network, the ChainId keep on at first network from array like [1(`Ethereum Mainnet`),5]
- case 3: follow the case 1 if Mobile app on some other network like `Bian` it allow connection, but mobile keep on `Bian` , web still get response on at first network from array like [1(`Ethereum Mainnet`),5]
- case 4:  follow the case 1 web ask to change network, how to info the app it should be changed network (sync to app). for now only can ask disconnect, do reconnect again
- case 5: one QR code for one network , but mobile app like iMtoken on different network, no feed back it's not on same network....
please give a user friendly case to cover those case. because app or web can not user all match product from other side. for same company we can ask for follow the some rule... but for market we need sync information to know how to feedback to customer

**Comment by windatang** [comment]
How web can make sure wish connect app support networks is match web listed,[]; most of case we only want app to switch to the network current website on, so that mean web only can ask for one chain, but app should answer or give the feedback it's on this network or can switch to or can not

**Comment by glitch-txs** [comment]
The trick is on the tx you send to the mobile. Even if the user "switches" on mobile when you send a tx it will be for the default chain the dapp selects.

For case one you can use optional chains/namespaces if the wallet doesn't support them it will only connect to the required ones.

**Comment by liubin595338764** [comment]
@glitch-txs  I have also encountered the same problem. Could you please advise on how to use the `wallet_switchEthereumChain` method?

I know that V2 can simultaneously connect to multiple chains, but if I am unable to switch chains successfully, transactions will still be executed on the old chain.

**Comment by glitch-txs** [comment]
@liubin595338764 if you're using MetaMask there're some issues with it atm 
https://github.com/MetaMask/metamask-mobile/issues/6655

Otherwise switching with v2 will actually set a chain as default, if you use `eth_chain` method you can check what's the current default chain.

**Comment by Dellybro** [comment]
IDK if you figured out the answer but my problem was that my onClick function was calling open like so:

`onClick={open}`

the open function seems to take parameters and if you do it like that it sends the button click event.

so what you want to do is

`onClck={() => open()}`
