### ISSUE TITLE
Event monitoring is not effective. The user is modifying the network or changing their account, and the event cannot monitor user behavior. Only the disconnect event is effective

### ISSUE THREAD

**Issue by Daudxu** [WalletConnect/walletconnect-monorepo#2510]
provider.on("chainChanged", handler);
// accounts changed
provider.on("accountsChanged", handler);
// session established
provider.on("connect", handler);
// session event - chainChanged/accountsChanged/custom events
provider.on("session_event", handler);
// connection uri
provider.on("display_uri", handler);

Event monitoring is not effective. The user is modifying the network or changing their account, and the event cannot monitor user behavior. Only the disconnect event is effective

**Comment by Daudxu** [comment]
https://www.npmjs.com/package/@walletconnect/ethereum-provider
@walletconnect/ethereum-provider

**Comment by ganchoradkov** [comment]
Hey @Daudxu , which wallet are you using? May be we can raise the issue with them as most likely they're not sending `session_event` to the dapp. 
 `accountsChanged/chainChanged` are emitted after the provider receives `session_event`. If the wallet is not emitting it, there is no way for the provider to detect the state update.

**Comment by Daudxu** [comment]
> Hey @Daudxu , which wallet are you using? May be we can raise the issue with them as most likely they're not sending `session_event` to the dapp. `accountsChanged/chainChanged` are emitted after the provider receives `session_event`. If the wallet is not emitting it, there is no way for the provider to detect the state update.

I am using imToken

**Comment by Daudxu** [comment]
> Hey @Daudxu , which wallet are you using? May be we can raise the issue with them as most likely they're not sending `session_event` to the dapp. `accountsChanged/chainChanged` are emitted after the provider receives `session_event`. If the wallet is not emitting it, there is no way for the provider to detect the state update.

I see that all the functions of their wagmi are intact, and event monitoring is also possible.
