### ISSUE TITLE
error trying to make a change on a submission  https://cloud.walletconnect.com/app/project?uuid=6620aef8-7cd1-4623-958b-a1ed4d4d7431

### ISSUE THREAD

**Issue by neri-ripio** [WalletConnect/walletconnect-monorepo#2517]
### Discussed in https://github.com/orgs/WalletConnect/discussions/2506

<div type='discussions-op-text'>

<sup>Originally posted by **neri-ripio** May 30, 2023</sup>
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/129459236/937f79eb-508b-428e-aa2c-095988d60312)
</div>

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
