### ISSUE TITLE
Server-side rendering bug, plus CDN needed

### ISSUE THREAD

**Issue by alexanderatallah** [WalletConnect/walletconnect-monorepo#252]
Hello! Noticed that `@walletconnect/web3-provider@1.0.0-beta.47` requires a `document` to be defined, which isn't true during server-side rendering.

We wouldn't have this problem if a CDN were available, which is useful for other reasons. That way we can easily defer the loading of the web3 provider, which is very large (see https://bundlephobia.com/result?p=@walletconnect/web3-provider@1.0.0-beta.47).

**Comment by pedrouid** [comment]
Hey @alexanderatallah, we do have bundled javascript in our releases page

https://github.com/WalletConnect/walletconnect-monorepo/releases
