### ISSUE TITLE
Is not possible to specify Mobile Wallet and Injected Wallet on the same submission

### ISSUE THREAD

**Issue by neri-ripio** [WalletConnect/walletconnect-monorepo#2527]
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/129459236/3754ff2a-02ba-4642-89ec-077f1f5af5fe)

The interface should allow you to select both (injected and mobile) in case of a wallet that has the 2 available versions (e.g. metamask)

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue :)
