### ISSUE TITLE
[sign-client v2] Question about disconnecting and throwing an error

### ISSUE THREAD

**Issue by finessevanes** [WalletConnect/walletconnect-monorepo#2529]
### Discussed in https://github.com/orgs/WalletConnect/discussions/1810

<div type='discussions-op-text'>

<sup>Originally posted by **juliancwirko** December 26, 2022</sup>
Hello, could someone please explain why an error is thrown when disconnecting? I mean, `No matching key. session or pairing topic doesn't exist: {topic}`. I would like to understand the purpose of throwing that error on each disconnection. Is it because there is no other way to signal it differently using `ping`? (I mean that this was the manual disconnection for a purpose, and there is no need to throw an error). Thanks.

I saw that it is also tested here: https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/sign-client/test/sdk/client.spec.ts#L71. </div>

**Comment by marcuspuchalla** [comment]
I also have this problem and don't see any viable solution in the discussion. The worst thing is you cannot catch this error as it seems. Or am I missing something here?

Any solution would be greatly appreciated.
