### ISSUE TITLE
Handling browsers not supporting localStorage

### ISSUE THREAD

**Issue by pacwoodson** [WalletConnect/walletconnect-monorepo#253]
In some cases, browsers block localStorage. 

Checking something like `window.localStorage !== undefined` throws an Error like 
`Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document`

This happens in Brave browser on cross domain embedded sites, or when chrome setting 'Block third-party cookies and site data' is enabled.

To solve this, the check must be done inside of a try/catch. Here's the problematic code: 
https://github.com/WalletConnect/walletconnect-monorepo/blob/4f5f543a70867acf6561b6f98d758098dead538e/packages/clients/core/src/storage.ts#L8

**Comment by pedrouid** [comment]
Fix included in v1.0.0-beta.81
