### ISSUE TITLE
404 error clicking published wallet

### ISSUE THREAD

**Issue by neri-ripio** [WalletConnect/walletconnect-monorepo#2536]
### Discussed in https://github.com/orgs/WalletConnect/discussions/2535

<div type='discussions-op-text'>

<sup>Originally posted by **neri-ripio** June  2, 2023</sup>
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/129459236/1424805f-c827-44f7-80f2-335a0ef4c6ee)

https://walletconnect.com/explorer/ripio-portal-mobile-wallet</div>

**Comment by neri-ripio** [comment]
https://cloud.walletconnect.com/app/project?uuid=afe3f7ae-22be-4f09-b511-75ba4c33db81

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few weeks.

Please reopen if you still encounter this issue :)
