### ISSUE TITLE
Infura + Polling errors on any network

### ISSUE THREAD

**Issue by jeffscottward** [WalletConnect/walletconnect-monorepo#256]
Getting two strange errors with
`POST https://mainnet.infura.io/v3/d5e29c9b9a9d4116a7348113f57770a8 net::ERR_BLOCKED_BY_CLIENT`
`Uncaught Error: Could not find block`

Steps to recreate:
GOTO https://reactdemo.blocknative.com/
SELECT Wallet Connect
CLICK Wallet Checks button
SCAN Qr Code
CHECK Console

I was getting this error with all Wallets on my phone that have WC.

**Comment by pedrouid** [comment]
Fixed! Please update to latest
