### ISSUE TITLE
personal_sign request not resolved on mobile devices

### ISSUE THREAD

**Issue by finessevanes** [WalletConnect/walletconnect-monorepo#2566]
### Discussed in https://github.com/orgs/WalletConnect/discussions/2384

<div type='discussions-op-text'>

<sup>Originally posted by **RuggeroCino** May 15, 2023</sup>
When trying to sign a message using WalletConnect v2 on a mobile browser (Chrome or Safari), the request is successfully sent to the wallet (on TrustWallet for instance I get the "confirm-sign-message" dialog) but the dApp does not receive the signed message. The issue can be replicated on your [React test app](https://react-app.walletconnect.com/) by opening it on a mobile device, connecting the app to a wallet and clicking on the `personal_sign` button.</div>

**Comment by finessevanes** [comment]
Testing sign functionality.

iOS 16.5
Trust v8.7
https://github.com/WalletConnect/walletconnect-monorepo/assets/44731696/481068a6-1962-410c-b18a-56966e677ae4

**Comment by finessevanes** [comment]
This has been fixed in v8.8

**Comment by AdemKao** [comment]
Hi there,
I found it only support  signing message one time,
If I click sign message again, the trust wallet will show session is closed.

IOS:16.5
Trust wallet: 8.8
