### ISSUE TITLE
No pubkey in response

### ISSUE THREAD

**Issue by faboweb** [WalletConnect/walletconnect-monorepo#2568]
**Describe the bug**

Hi,
when I try to get an account the pubkey is an empty string.

```
signClient.request({
      topic: session.topic,
      chainId: 'cosmos:cosmoshub-4',
      request: {
        method: 'cosmos_getAccounts',
        params: {}
      }
    })
  ```
Do I need to config somewhere that the protocol sends the pubkey?

**SDK Version (if relevant)**
 - Client: [e.g. JS, Swift, Kotlin]

```
    "@walletconnect/sign-client": "^2.7.2",
    "@walletconnect/types": "^2.7.2",
    "@walletconnect/utils": "^2.7.2",
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few weeks.

Please reopen if you still encounter this issue :)
