### ISSUE TITLE
Support in ISessionStorage methods promises

### ISSUE THREAD

**Issue by desfero** [WalletConnect/walletconnect-monorepo#257]
At the moment `ISessionStorage` methods do not support returning session data asynchronously.

It would be good if the implementation can be updated to also allow return Promises with session data as otherwise in react-native it's not possible to provide custom `sessionStorage` as the default `AsyncStorage` in RN is asynchronous by nature.

If that sounds good let me know I can push an update to the codebase.

**Comment by pedrouid** [comment]
Sounds reasonable, I can make this improvement.

However be aware that ISessionStorage is designed to only store one session at a time. Which in most cases is undesirable in a mobile app. ISessionStorage was designed for browser usage since localStorage is seperated by host

**Comment by desfero** [comment]
But anyway to support multiple session you still need to initiate multiple WalletConnect instances passing session manually. 

If we allow to pass `sessionStorage` and also allow having async methods for `get/set/removeSession` we can greatly simplify the logic around handling session (setting/clearing) storage manually given storage-related methods are already implemented properly in the `Connector`. It seems that handling the` session` manually is just a duplication of the code that's already implemented.

PS. One session at the time is still useful for the case when you implement a wallet that will just connect with your DAPP (not a general-purpose wallet) given that we also provide a custom implementation of a bridge to support heartbeats and timeouts.

**Comment by pedrouid** [comment]
Good point 👍 I will publish a version with this on the `next` tag for you to test in a bit

**Comment by pedrouid** [comment]
Damn I just looked through it and there is a breaking change with this feature which will break how sessions are currently recovered from the connector constructor which needs to be synchronous

I would totally make this change if it didn't break existing integrations. 

You can however still implement it on top where you can store WalletConnect sessions mapped by the clientId or peerId (both are unique per session). Here is the example for our react-native demo app.

https://github.com/WalletConnect/walletconnect-demo-app/blob/master/src/helpers/asyncStorage.ts#L44

**Comment by desfero** [comment]
that's what I'm doing at the moment with mapping. Thanks for your help. Given that it's gonna be a breaking change (as to make session storage async probably some factory to create connector instance is needed or an `init` async method) I'm closing the issue.

**Comment by pedrouid** [comment]
Yeah exactly it would require a static async init method, I intend to include a lot of breaking changes with v2.0 so I will make sure to make store async
