### ISSUE TITLE
m.getBigIntRpcId is not a function

### ISSUE THREAD

**Issue by xwartz** [WalletConnect/walletconnect-monorepo#2576]
**Describe the bug**

When I integrate the latest version of @walletconnect/web3wallet SDK and scan the QR code, the following error occurs.

```
{"context": "core"} {"context": "core/relayer"} {"context": "core/relayer/publisher"} [TypeError: m.getBigIntRpcId is not a function. (In 'm.getBigIntRpcId()', 'm.getBigIntRpcId' is undefined)]
```

**SDK Version (if relevant)**
 - Client: RN
 - Version 1.7.6

**To Reproduce**
1. Go to https://react-dapp-v2-with-ethers.vercel.app/
2. Click on `Ethereum Goerli`
3. Scan the QR code using a wallet

**Expected behavior**
the connection is successful without any errors, then everything is working correctly.

**Screenshots**
no

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]
 - Version [13.4]

**Smartphone (please complete the following information):**
 - Device: [iPhone 14 Pro Max]
 - OS: [iOS 16.2]

**Additional context**
no

**Comment by ganchoradkov** [comment]
Hey @xwartz, seems like you're using outdated dependencies.
If you have explicit declarations of these 2 utils, please make sure they're at least on these versions or up
```
"@walletconnect/jsonrpc-provider": "1.0.11",
"@walletconnect/jsonrpc-utils": "^1.0.7",
