### ISSUE TITLE
Check if the session you persisted is still valid 

### ISSUE THREAD

**Issue by desfero** [WalletConnect/walletconnect-monorepo#258]
Is there a way to deterministically know if the persisted session is still valid? 

From what I found after you create a new `WalletConnect` instance with a `session` param subscription to the topic is done under the hood. If the session is not active anymore then the `disconnect` event is triggered (which anyway seems to be not true as you never had a connect event trigger for `WalletConnect` created from existing `session). 
But if the session is active no even seems to be triggered.

**Comment by pedrouid** [comment]
Sessions shouldn't be persisted until `approved` so you should check for that boolean on the `ISessionParams`

**Comment by desfero** [comment]
ok, but after it's persistend and then after refresh how would i know if the session is still valid (not disconnected by the web app or mobile app)?

**Comment by pedrouid** [comment]
The WalletConnect instance will decide this so you would need instantiate all the persisted sessions and listen for the `disconnect` event

I would recommend to subscribe to these events at all times and always delete sessions whenever the `disconnect` event is triggered

**Comment by desfero** [comment]
yes, but is it possible to trigger also connect event? For e.g. imagine the use case where I want to show the modal `You have been connected to your existing session (some session details)` and after it's disconnected the modal should be with `You have been disconnected from (some session details)`. Right now I don't see any way to implement it without manually waiting whether the `disconnect` event was triggered or no to show the connected modal.

**Comment by pedrouid** [comment]
Unfortunately there is no way to tell if the session is valid before instantiating the client, the websocket connection when initiated will receive all the pending payloads that were published while offline, this will include the disconnect requests.

I would advise you to always instantiate all the sessions on app load and triggered these notifications for each event.

**Comment by desfero** [comment]
ok, sounds reasonable, thanks.
