### ISSUE TITLE
Explorer API: Network connection reset

### ISSUE THREAD

**Issue by basemain** [WalletConnect/walletconnect-monorepo#2580]
main.js:31     GET https://explorer-api.walletconnect.com/w3m/v1/getDesktopListings?projectId=ismyid&page=1&entries=9&version=1 net::ERR_CONNECTION_RESET

**Comment by eliomain** [comment]
explorer-api.walletconnect.com/v3/prices?projectId=&take=ETH&currency=USD:1     Failed to load resource: net::ERR_CONNECTION_RESET

**Comment by ganchoradkov** [comment]
hey @eliomain, the url you shared works great for me. Are you using some kind of VPN that might prevent connection?

**Comment by eliomain** [comment]
Yes @ganchoradkov Is have any another reserve uri?

**Comment by basemain** [comment]
I don't think that should rely too much on external links.

**Comment by bkrem** [comment]
@eliomain could you provide a way to consistently reproduce the issue you're seeing please?
