### ISSUE TITLE
Web3Wallet.init is not working

### ISSUE THREAD

**Issue by ric344** [WalletConnect/walletconnect-monorepo#2581]
**Describe the bug**
Web3Wallet.init is not working.

**SDK Version (if relevant)**
 - Client: [e.g. JS, Swift, Kotlin]

**To Reproduce**

**Expected behavior**
It should work.
**Screenshots**
ERROR  {"context": "core"} undefined is not a function
 ERROR  {"context": "client"} undefined is not a function
 ERROR  {"context": "core"} undefined is not a function
 LOG  web3wallet: undefined
WARN  Possible Unhandled Promise Rejection (id: 1):
TypeError: Cannot read property 'core' of undefined
TypeError: Cannot read property 'core' of undefined
    at ?anon_0_ (http://10.103.233.19:19000/src/utils/WalletConnectUtils.bundle?platform=android&hot=false&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:83:35)
    at next (native)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I am using this code:
try {
        web3wallet = await Web3Wallet.init({
            core: new Core({
                projectId: process.env,// using correct ID
            }),
            metadata: {
                name: "My Wallet",
                description: "My Wallet",
                url: "https://walletconnect.com/",
                icons: ["https://avatars.githubusercontent.com/u/37784886"],
            },
        });
    } catch (e) {
        console.log(e);
    }
    console.log("web3wallet:", web3wallet);

Dependencies:
"@ethersproject/shims": "^5.7.0",
    "@json-rpc-tools/utils": "^1.7.6",
    "@react-native-async-storage/async-storage": "^1.18.2",
    "@walletconnect/react-native-compat": "^2.7.8",
    "@walletconnect/web3wallet": "^1.7.6",
    "ethers": "5.4",
    "expo": "~48.0.18",
    "expo-status-bar": "~1.4.4",
    "fast-text-encoding": "^1.0.6",
    "react": "18.2.0",
    "react-native": "0.71.8",
    "react-native-dotenv": "^3.4.8",
    "react-native-get-random-values": "^1.9.0"

**Comment by ganchoradkov** [comment]
Hey, could you share a minimal repo where we could reproduce it?
From your code snippets, I'm not seeing anything out of the ordinary.

**Comment by ric344** [comment]
sure, I can share the code to you for reproduce.

```
import "@walletconnect/react-native-compat";
import "@ethersproject/shims";
import { Core } from "@walletconnect/core";
import { ICore } from "@walletconnect/types";
import { Web3Wallet, IWeb3Wallet } from "@walletconnect/web3wallet";

export let web3wallet: IWeb3Wallet;
export let core: ICore;
export let currentETHAddress: string;

import { useState, useCallback, useEffect } from "react";
import { createOrRestoreEIP155Wallet } from "./EIP155Wallet";

async function createWeb3Wallet() {
    console.log(2)
    // Here we create / restore an EIP155 wallet
    const { eip155Addresses } = await createOrRestoreEIP155Wallet();
    currentETHAddress = eip155Addresses[0];
    console.log("currentETHAddress", currentETHAddress)

    console.log("core:", core);

    // Edit the metadata to your preference
    try {
        web3wallet = await Web3Wallet.init({
            core: new Core({
                projectId: process.env,
                relayUrl: 'wss://relay.walletconnect.com',
            }),
            metadata: {
                name: "My Wallet",
                description: "My Wallet",
                url: "https://walletconnect.com/",
                icons: ["https://avatars.githubusercontent.com/u/37784886"],
            },
        });
    } catch (e) {
        console.log(e);
    }
    console.log("web3wallet:", web3wallet);
}

// Initialize the Web3Wallet
export default function useInitialization() {
    const [initialized, setInitialized] = useState(false);

    const onInitialize = useCallback(async () => {
        try {
            await createWeb3Wallet();
            setInitialized(true);
        } catch (err: unknown) {
            console.log("Error for initializing", err);
        }
    }, []);

    useEffect(() => {
        if (!initialized) {
            onInitialize();
        }
    }, [initialized, onInitialize]);

    return initialized;
}

export async function web3WalletPair(params: { uri: string }) {
    console.log("1");
    return await web3wallet.core.pairing.pair({ uri: params.uri });
}
```
Above is my walletconnect utils file and I am calling useInitialization() in my APP.jsx

**Comment by bkrem** [comment]
@ignaciosantise could you take a look pls and see if you can spot something off? 🙏

**Comment by luanccp** [comment]
I am having the same issue

**Comment by peterferguson** [comment]
@ric344 

you need to actually specify your projectId 

```js
 projectId: process.env,
 ```
 
 should probably be something like 
 
 ```js
 projectId: process.env.projectId,
 ```

**Comment by Mostafatalaat770** [comment]
same here, it doesn't init randomly

**Comment by ignaciosantise** [comment]
@ric344 I've just used your code snippet in our [wallet example](https://github.com/WalletConnect/react-native-examples/tree/main/wallets/rn_cli_wallet) and the SDK is initializing as expected. Can you create an example repo for me to reproduce the bug?

**Comment by ignaciosantise** [comment]
@ric344 did you add `import '@walletconnect/react-native-compat';` in the root file of your app?

**Comment by ric344** [comment]
On your web3wallet tutorial repo I am getting this error. After some debugging I found it was showing error on creating wallet with the help of createRandom function. While consoling mnemonic was undefined so web3wallet init is not initializing.

**Comment by ignaciosantise** [comment]
@ric344 sorry for the delay. Here's a similar issue: https://github.com/WalletConnect/react-native-examples/issues/79

Are you using expo 48? If so, try adding the custom-shim provided [here](https://github.com/WalletConnect/react-native-examples/issues/79)

**Comment by neoanurag** [comment]
hi Team i am getting the same kind of error, would you please provide any solution for this. Project Id is correct.

 ERROR  {"context": "core"} System random byte generator is not available.
 ERROR  {"context": "client"} System random byte generator is not available.
 ERROR  {"context": "core"} System random byte generator is not available.
 LOG  called setRates
 WARN  Possible Unhandled Promise Rejection (id: 0):
Error: System random byte generator is not available.
Error: System random byte generator is not available.


Code Snippet:

       const core = new Core({
           projectId: globalThis.walletConnectProjectId,
       });
      console.log("core", core)
      const web3walletRes = await Web3Wallet.init({
        core,
        metadata: metadata,
      });

**Comment by ganchoradkov** [comment]
@neoanurag could you share your package.json?

**Comment by neoanurag** [comment]
> @neoanurag could you share your package.json?

<img width="446" alt="Screenshot 2023-09-20 at 1 02 55 PM" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/51991025/cd228b56-9381-451c-884e-f1f183d42f7c">

Here is my package.json

**Comment by ganchoradkov** [comment]
Seems like you're missing `@walletconnect/react-native-compat` which is a required package for RN environments as per the docs https://docs.walletconnect.com/2.0/web3wallet/about?platform=react-native#installation
Please install it and try again

**Comment by neoanurag** [comment]
> Seems like you're missing `@walletconnect/react-native-compat` which is a required package for RN environments as per the docs https://docs.walletconnect.com/2.0/web3wallet/about?platform=react-native#installation Please install it and try again

Updated the dependencies, still getting the same error.

**Comment by ganchoradkov** [comment]
Could you please provide a minimal example repo where we could reproduce the issue

**Comment by neoanurag** [comment]
```
import React, {useEffect} from 'react';
import {SafeAreaView, StatusBar, useColorScheme} from 'react-native';
import {Colors, Header} from 'react-native/Libraries/NewAppScreen';
import {Core} from '@walletconnect/core';
import {ICore} from '@walletconnect/types';
import {Web3Wallet, IWeb3Wallet} from '@walletconnect/web3wallet';

export let web3wallet: IWeb3Wallet;
export let core: ICore;

function App(): JSX.Element {
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  useEffect(() => {
    createWeb3Wallet();
  }, []);

  const createWeb3Wallet = async () => {
    try {
      const metadata = {
        description: globalThis.walletConnectMetaDataDescription,
        url: globalThis.walletConnectMetaDataURL,
        icons: globalThis.walletConnectMetaDataIcons,
        name: globalThis.walletConnectMetaDataName,
      };
      const web3wallet = await Web3Wallet.init({
        core: new Core({
          projectId: globalThis.walletConnectProjectId,
        }),
        metadata: metadata,
      });
      console.log('web3walletadress', web3wallet)
    } catch (e) {
      console.log(e);
    }
  };

  async function web3WalletPair(params: {uri: string}) {
    return await web3wallet.core.pairing.pair({uri: params.uri});
  }

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar
        barStyle={isDarkMode ? 'light-content' : 'dark-content'}
        backgroundColor={backgroundStyle.backgroundColor}
      />
      <Header />
    </SafeAreaView>
  );
}

export default App;

```

**Comment by ignaciosantise** [comment]
@neoanurag can you try adding `import '@walletconnect/react-native-compat';` before web3wallet import?

**Comment by glitch-txs** [comment]
This should be fixed in the latest versions, please update all packages and let us know if the issue still persists.

**Comment by GouthamJM** [comment]
I am still getting this issue - my deps in package.json 
```
 "dependencies": {
    "@covalenthq/client-sdk": "^0.7.0",
    "@ethersproject/bytes": "^5.7.0",
    "@ethersproject/transactions": "^5.7.0",
    "@expo/vector-icons": "^13.0.0",
    "@react-native-async-storage/async-storage": "^1.19.4",
    "@react-native-community/netinfo": "^8.3.0",
    "@react-native-firebase/app": "^18.7.3",
    "@react-native-firebase/auth": "^18.7.3",
    "@react-native-google-signin/google-signin": "^10.0.0",
    "@react-navigation/drawer": "^6.6.6",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.9.17",
    "@shopify/flash-list": "1.4.3",
    "@silencelaboratories/react-native-duo-sdk": "^0.0.4",
    "@silencelaboratories/react-native-two-party-ecdsa": "^1.0.1",
    "@silencelaboratories/react-native-two-party-eddsa": "^1.0.3",
    "@tamagui/animations-react-native": "latest",
    "@tamagui/config": "^1.77.1",
    "@tamagui/core": "^1.77.1",
    "@tamagui/font-inter": "latest",
    "@tamagui/linear-gradient": "^1.76.0",
    "@tamagui/lucide-icons": "latest",
    "@tamagui/react-native-media-driver": "latest",
    "@tamagui/shorthands": "latest",
    "@tamagui/themes": "latest",
    "@tamagui/toast": "latest",
    "@tanstack/react-query": "^5.14.1",
    "@walletconnect/react-native-compat": "2.10.4",
    "@walletconnect/types": "^2.11.0",
    "@walletconnect/utils": "^2.11.0",
    "@walletconnect/web3wallet": "1.9.3",
    "base-64": "^1.0.0",
    "buffer": "^6.0.3",
    "burnt": "^0.12.1",
    "dayjs": "^1.11.10",
    "expo": "^49.0.21",
    "expo-barcode-scanner": "~12.5.3",
    "expo-clipboard": "~4.3.1",
    "expo-crypto": "~12.4.1",
    "expo-document-picker": "~11.5.4",
    "expo-file-system": "~15.4.5",
    "expo-font": "~11.4.0",
    "expo-image": "~1.3.5",
    "expo-linear-gradient": "~12.3.0",
    "expo-linking": "~5.0.2",
    "expo-local-authentication": "~13.4.1",
    "expo-router": "^2.0.0",
    "expo-secure-store": "~12.3.1",
    "expo-sharing": "~11.5.0",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-system-ui": "~2.4.0",
    "expo-web-browser": "~12.3.2",
    "fastestsmallesttextencoderdecoder": "^1.0.22",
    "get-random-values-polypony": "^1.0.0",
    "jotai": "^2.5.0",
    "lodash": "^4.17.21",
    "lottie-react-native": "^6.5.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.6",
    "react-native-aes-crypto": "^3.0.1",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-qrcode-svg": "^6.2.0",
    "react-native-reanimated": "3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-securerandom": "^1.0.1",
    "react-native-svg": "^13.2.0",
    "react-native-timeline-flatlist": "^0.8.0",
    "react-native-web": "~0.19.6",
    "tamagui": "^1.77.1",
    "viem": "^1.19.9",
    "zustand": "^4.4.7"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@tamagui/babel-plugin": "latest",
    "@tamagui/build": "latest",
    "@types/base-64": "^1.0.2",
    "@types/jsonwebtoken": "^9.0.5",
    "@types/lodash": "^4.14.202",
    "@types/react": "~18.2.14",
    "@types/react-native": "^0.72.8",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "babel-plugin-module-resolver": "^5.0.0",
    "babel-plugin-transform-inline-environment-variables": "^0.4.4",
    "eslint": "^8.54.0",
    "eslint-config-universe": "^12.0.0",
    "jest": "^29.2.1",
    "jest-expo": "~49.0.0",
    "prettier": "^3.1.0",
    "react-test-renderer": "18.2.0",
    "typescript": "^5.3.2"
  },
```

**Comment by ignaciosantise** [comment]
@GouthamJM can you open a new issue and provide an example project with the reproducible issue? 

Thanks!
