### ISSUE TITLE
Web3 provider never resolves eth.getBlockNumber() calls.

### ISSUE THREAD

**Issue by fubhy** [WalletConnect/walletconnect-monorepo#259]
Hey there,

Checking in from https://github.com/avantgardefinance/melon-terminal/issues/435. I tried again using the latest beta npm package today and it now seems that calls to eth_blockNumber never resolve at all. Is this still something you are working on or is there a workaround for it? Note: We are using web3 version `^2.0.0-alpha.1` for the TypeScript definitions.

I looked at the code today a bit to try and resolve it and saw that you are using web3-provider-engine quite extensively. Is there a reason for that or would it be possible to implement a custom provider without web3-provider-engine to reduce the big trail of dependencies pulled in by this package. Ideally, I'd like to not include web3-provider-engine in our setup at all as it proved quite problematic for various reasons for us in the past. I am also wondering about the low level requirements for rolling a custom provider for WalletConnect As we are currently in the process switching to ethers.js anyways and would eventually want to directly integrate with WalletConnect instead of running through the ethers.js web3 compatibility layer. If you could point me in the right direction I would be happy to take a stab at that myself.

**Comment by pedrouid** [comment]
I haven't debugged the eth_blockNumber issue yet, it has also been recently reported on #256. This seems to be Infura-specific and needs to be handled in the provider somewhere.

Regarding the use of web3-provider-engine, I've tried many times to move away from it and it's been quite difficult. You can see that there is actually a different provider called `eth-provider` which doesn't rely on it but it's very unstable in comparison so I've stopped developing it.

I will try to fix the issue with eth_blockNumber but removing the web3-provider-engine dependency will be a long-term goal

**Comment by fubhy** [comment]
Great, thanks for the heads up. 

Just to clarify I wasn't asking / demanding for you to remove it here (that would be quite condescending) but rather asking for pointers for how we could build our own provider e.g. also for ethers.js in the future. I just thought I'd mention that after re-reading my original comment and disliking the tone of my own question ;-)

**Comment by pedrouid** [comment]
Fixed with latest release
