### ISSUE TITLE
I want you to register my blockchain network.

### ISSUE THREAD

**Issue by kangjuhyup** [WalletConnect/walletconnect-monorepo#2606]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs]

["personal_sign", "eth_sign", "eth_signTypedData", "eth_sendTransaction", "eth_signTransaction", "eth_sendRawTransaction"]

2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.

eip155:47

3. **namespaces**:
 
eip155

4. **chains**:

eip155:47
devnet

5. **RPC endpoints**

https://karam.carrieverse.com

6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:

1 , 0x80000001 , Testnet (all coins)

**Additional context**
Add any other context here.

**Comment by Cali93** [comment]
Please provide specific information about your RPC endpoints, [SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type and a chain ID that is not conflicting with [Acria IntelliChain](https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-47.json).

Kind regards.

**Comment by Cali93** [comment]
Marking this request as stale. Feel free to re-open when you have the requested information.
