### ISSUE TITLE
GET https://example.walletconnect.org/null 404

### ISSUE THREAD

**Issue by miohtama** [WalletConnect/walletconnect-monorepo#261]
When visiting the demo app, connect to the wallet with WalletConnect (using Trust Wallet). Then you get a flood of error messages in the JavaScript console.

![image](https://user-images.githubusercontent.com/49922/80952256-b1591580-8df9-11ea-84c1-714ef303eee8.png)

GET https://example.walletconnect.org/null 404 over hundreds of times, many times per second.

**Comment by pedrouid** [comment]
Fixed on example-dapp
