### ISSUE TITLE
Add Arthera Testnet

### ISSUE THREAD

**Issue by artheraone** [WalletConnect/walletconnect-monorepo#2615]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

 **namespaces**:
eip:155

4. **chains**:
eip155:10243 (testnet)

5. **RPC endpoints**
https://rpc-test.arthera.net

6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
| 7028       | 0x80001b74                    | AA      | Arthera                           |

**Additional context**
https://docs.arthera.net

**Comment by JT-ITStation** [comment]
+1

**Comment by mostaruk** [comment]
+1

**Comment by davidtacer** [comment]
+1

**Comment by valknut94** [comment]
+1

**Comment by bkrem** [comment]
Thanks for submitting 🙏 

Added to https://cloud.walletconnect.com/

**Comment by lperello** [comment]
Hello @bkrem Thanks you so much for your reactivity
