### ISSUE TITLE
Can not connect to trust wallet with @walletconnect/ethereum-provider (v2) but without using @walletconnect/modal

### ISSUE THREAD

**Issue by congminh090800** [WalletConnect/walletconnect-monorepo#2617]
**Describe the bug**
I am having trouble to show the connection pop up of trust wallet when using @walletconnect/ethereum-provider (walletconnect v2) while set showQrModal as false.
I successfully open the trust wallet app with deep link trust://wc?uri=wc:46dad54ebde8bee1c011f2df71db734b57d8af7526495ed7076a7a451b3d9570@2?relay-protocol=irn&symKey=33b1080a6b13a5cd31d475064ee08ad9c936e9d058d3a294e95738fdb20cb593.
But the trust wallet not showing the connect popup. It show "WalletConnect session was disconnected...." after a while ( I assumed it was timed out).
Note: The connect popup will show if I use showQrModal as true.
Note: The trust wallet app will not open if I use unversal link: https://link.trustwallet.com
Note: I used ngrok to host my frontend app so that I can test on my mobile.

Here is my code right now:
```<template>
  <div class="test-2-page">
    <a-button @click="(e) => connect(1)">Connect</a-button>
    <pre>{{ data }}</pre>
    <a-button @click="(e) => disconnect()">Disconnect</a-button>
  </div>
</template>

<script>
import { EthereumProvider } from '@walletconnect/ethereum-provider';
import { CHAIN_INFO } from '@/constants/chains.constant';

export default {
  name: 'test-2-page',
  data() {
    return {
      provider: null,
      data: null,
    };
  },
  methods: {
    async connect(chain) {
      this.provider = await EthereumProvider.init({
        projectId: 'a0ae3cabc36c22bf1e9977082287d8e5',
        rpcMap: {
          [chain]: CHAIN_INFO[chain].rpcUrl,
        },
        chains: [chain],
        showQrModal: false,
      });
      this.provider.on('display_uri', (uri) => {
        console.log('uri', uri);
        const deepLinkUri = `trust://wc?uri=` + uri;
        console.log(deepLinkUri);
        window.location.href = deepLinkUri;
      });
      this.provider.on('connect', async (error, payload) => {
        if (error) {
          console.error(error);
          return;
        }
        console.log(JSON.stringify(payload, null, 4));
      });
      this.provider.on('error', (error) => {
        console.error(error);
      });
      await this.provider.enable();
    },
    async disconnect() {
      await this.provider.disconnect();
    },
  },
};
</script>
```
**SDK Version (if relevant)**
walletconnect/ethereum-provider@^2.8.0,
vue@^2.6.11
node 14

**Expected behavior**
Show popup connect to correct chain

**Smartphone (please complete the following information):**
 - Device: Iphone 12

**Comment by fayaz898** [comment]
Bug
