### ISSUE TITLE
Mobile WalletConnect to MetaMask do not connects

### ISSUE THREAD

**Issue by RomualdH** [WalletConnect/walletconnect-monorepo#2622]
**Describe the bug**
WalletConnect to MetaMask on Mobile redirects to MetaMask App but not asking for connection, connects, or redirects to dApp.

**SDK Version (if relevant)**
 - Client: JS - Web3Modal - HTML - Wagmi
 - Version: `web3modal@^1.9.4`, `@wagmi/core@^1.1.1`, `@web3modal/ethereum@^2.4.5`, `@web3modal/html@^2.4.5`.

**To Reproduce**
1. Go to https://app.betswirl.com on a mobile browser.
2. Click on top right "Connect wallet".
3. Click on "Select Wallet" in the Web3Modal's WalletConnect section.
4. Select MetaMask App.
5. It redirects to MetaMask... but nothing pops up.

**Expected behavior**
MetaMask should ask for permission, or it should redirects to the dApp browser if connected.

**Additional context**
- I experience the same issue on [Web3Modal Laboratory - With Wagmi](https://lab.web3modal.com/with-wagmi/react)
- It's working on https://web3modal.com

**Comment by 70nyIT** [comment]
same situation for me (on a different App I'm working on). With v1 no issues. When changing to v2, MetaMask App is not reading the QRCode (while Rainbow, for instance, does). Since v2 switch is now extremely close, and MetaMask App is widely adopted, I'm guessing what can be a workaround.

Tested with MetaMask App for Android - v. 6.6.0 (1114)

**Comment by 70nyIT** [comment]
ref to - https://github.com/WalletConnect/walletconnect-monorepo/issues/2622

Seems same behavior. But now we're very close to switch off of v1. Guess if the most adopted wallet hasn't integrated v2 yet, well, that doesn't sound so good

**Comment by finessevanes** [comment]
MetaMask does not yet support v1, which means that if you attempt to scan a v2 QR code with MetaMask on mobile, it will not function properly. We are collaborating with the MetaMask team internally to ensure their readiness by June 28.

**Comment by 70nyIT** [comment]
@finessevanes, since June 28th is in 7 days, and Metamask is an App distributed on thousands of mobile wallets, from my mobile dev experience I will expect a big portion of apps to be not-updated by June 28th.

This means that a big amount of Metamask Apps won't be compatible with your v2 version. Any suggestions as workaround? Any way an error could be automatically shown to users to inform they have to update their App (maybe directly in Metamask App)?

**Comment by tech271** [comment]
same problem here, customers can't connect because of this, 28th is coming fast , what will happen ?
we had to switch back to v1, no other solution for now.

**Comment by 70nyIT** [comment]
I think this shift has been **deeply** underestimated by Metamask. Walletconnect could mitigate it by sharing a simple roadmap, with dates and steps on when Metamask thinks >90% of their users will have App migrated. That will help lots of developers.

**Comment by tech271** [comment]
still no news about this issue ? it's only in 2 days !

**Comment by 70nyIT** [comment]
Metamask has forced an update to all Android users. On iOS I think the app needs to be updated

**Comment by dokocat** [comment]
This is the case with metamask, Trust wallet and zerion. How can this be an issue for so long? 50% of our traffic is from mobile and those users can use the app. How the hell isn't this fixed? This software is always so buggy and disappointing.

**Comment by Adomas202** [comment]
Any news on this one as today is the cut off day?
We see that on our app, at least with Trust wallet you can login, but user has to press "resend signature" in order to get redirected to have signature request on Trust wallet.

**Comment by dokocat** [comment]
Is there a paid version of walletconnect v2 we can use that actually works? Happy to pay for something! Please!

**Comment by dokocat** [comment]
Hi, this still doesnt work.

**Comment by lrudolph333** [comment]
Same, very frustrating.

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few weeks.

Please reopen if you still encounter this issue :)

**Comment by JonathanBaudoin** [comment]
I still have the issue, I tried a lot of code from your doc but it never works.

The button asks me to select a wallet, when I chose Metamask, it opens but doesn't ask me to validate the connection.

**Comment by Dhonina** [comment]
Rab, 20 Sep 2023 pukul 21.25 Jonathan Baudoin ***@***.***>
menulis:

**Comment by glitch-txs** [comment]
@JonathanBaudoin could you go through [issues & discussion guide](https://github.com/orgs/WalletConnect/discussions/3457) so we can help you on this?

Also make sure both the library and wallet versions are up to date. Thanks!

**Comment by damdafayton** [comment]
I still have the same problem.
wagmi: 1.4.13
@web3modal/wagmi-react-native: 1.2.0

Also in documentation [here](https://docs.walletconnect.com/web3modal/react-native/about), there is `enableAnalytics` option for `createWeb3Modal ` but `@web3modal/wagmi-react-native@1.2.0` doesnt have such key.

**Comment by 124maa** [comment]
> **Describe the bug** WalletConnect to MetaMask on Mobile redirects to MetaMask App but not asking for connection, connects, or redirects to dApp.
> 
> **SDK Version (if relevant)**
> 
> * Client: JS - Web3Modal - HTML - Wagmi
> * Version: `web3modal@^1.9.4`, `@wagmi/core@^1.1.1`, `@web3modal/ethereum@^2.4.5`, `@web3modal/html@^2.4.5`.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to https://app.betswirl.com on a mobile browser.
> 2. Click on top right "Connect wallet".
> 3. Click on "Select Wallet" in the Web3Modal's WalletConnect section.
> 4. Select MetaMask App.
> 5. It redirects to MetaMask... but nothing pops up.
> 
> **Expected behavior** MetaMask should ask for permission, or it should redirects to the dApp browser if connected.
> 
> **Additional context**
> 
> * I experience the same issue on [Web3Modal Laboratory - With Wagmi](https://lab.web3modal.com/with-wagmi/react)
> * It's working on https://web3modal.com

**Comment by 0xForkHunter** [comment]
Same issue as @124maa using: `@web3modal/wagmi@4.1.0` and `wagmi@2.5.7`
I get redirected to MM, but nothing happens.
