### ISSUE TITLE
There is an exception when user closes WalletConnect dialog with QR-code

### ISSUE THREAD

**Issue by Lizusha** [WalletConnect/walletconnect-monorepo#263]
I'm using WalletConnect with Web3Connect

Here is my code:
web3Connect.connect(). then(provider => { resolve(provider) }). catch(err =>{ reject(err) })

If user closes WalletConnect dialog with QR-code without scannig I receive exception:
"Unhandled Rejection (Error): User closed WalletConnect modal"

  300 | .then(() => {
  301 |   if (this.qrcode) {
  302 |     WalletConnectQRCodeModal.open(wc.uri, () => {
*> 303 |       reject(new Error('User closed WalletConnect modal'))
      | ^  304 |     })
  305 |   }
  306 |   wc.on('connect', (error, payload) => {

And this exception appears on browser screen, catch does not catch it.

Web3Connect team said that this needs to be fixed on the WalletConnect side, so I'm creating issue here.

**Comment by pedrouid** [comment]
Hey @Lizusha, actually I was just receiving a report from this and there is been a fix on Web3Modal for catching this error. Please try web3modal v1.6.2

**Comment by Lizusha** [comment]
Hey @pedrouid, yes, now it's ok, thank you!

**Comment by Iftikhar708** [comment]
> I'm using WalletConnect with Web3Connect
> 
> Here is my code: web3Connect.connect(). then(provider => { resolve(provider) }). catch(err =>{ reject(err) })
> 
> If user closes WalletConnect dialog with QR-code without scannig I receive exception: "Unhandled Rejection (Error): User closed WalletConnect modal"
> 
> 300 | .then(() => { 301 | if (this.qrcode) { 302 | WalletConnectQRCodeModal.open(wc.uri, () => { *> 303 | reject(new Error('User closed WalletConnect modal')) | ^ 304 | }) 305 | } 306 | wc.on('connect', (error, payload) => {
> 
> And this exception appears on browser screen, catch does not catch it.
> 
> Web3Connect team said that this needs to be fixed on the WalletConnect side, so I'm creating issue here.

resolve this issue within try-catch

try {
const provider = new WalletConnectProvider({
infuraId: 'c4f79cc821944d9680842e34466bfbd',
});
await provider.enable();
} catch (error) {
console.log(error);
}
