### ISSUE TITLE
Trouble establishing connection from iOS mobile wallet

### ISSUE THREAD

**Issue by eukevin** [WalletConnect/walletconnect-monorepo#2638]
**Describe the bug**
When opening a dApp page in a mobile browser on an iOS device and then attempting to connect a wallet on the same device, the connection is slow to establish or fails completely. This behavior is not observed on Android devices, nor when dApp and wallet are opened on separate iOS devices. We have done extensive testing to rule out a bug in the wallet or flutter SDK.

**To Reproduce**
1. Open a dApp page on an iOS device (eg. https://www.wizardsarena.net/)
2. Copy WC link from QR code
3. Paste in wallet on same device (eg. Koala Wallet)
4. Observe connection is slow to establish or never established

**Expected behavior**
As on other devices, connection should establish within a few seconds

**Smartphone (please complete the following information):**
 - Device: iPhone 8 plus
 - OS: iOS 16.5
 - Browser: Safari
 - Wallet: Koala Wallet 1.3.7
 - WalletConnect SDK: walletconnect_flutter_v2 2.0.9
 - dApps: https://www.wizardsarena.net, https://swap.ecko.finance, https://www.arkade.fun, https://farm.kdamining.club, https://www.kdswap.exchange

**Additional context**
Log of a failed connection attempt:
[WalletConnect.WaitTime.txt](https://github.com/WalletConnect/walletconnect-monorepo/files/11749872/WalletConnect.WaitTime.txt)

Corresponding DB entries showing dApp not responding to sent events:
![wc_connection_log](https://github.com/WalletConnect/walletconnect-monorepo/assets/104494914/c3274220-f1b8-4ceb-a4ff-7f03b1e87f4a)

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few weeks.

Please reopen if you still encounter this issue :)

**Comment by BigTorro** [comment]
I'm having the same issue, is really slow to connect to wallets or fails. Any suggestion?

**Comment by glitch-txs** [comment]
@Tias84 which wallet?

**Comment by BigTorro** [comment]
I'm using an iPhone and trying to connect to Metamask. I tried also Trust Wallet and Rainbow and both were more fast than Metamask wich is really slow (>1m)

**Comment by glitch-txs** [comment]
you should contact MetaMask instead since it's on their end
