### ISSUE TITLE
EIP712 eth_signTypedData method expects params in the reverse order.

### ISSUE THREAD

**Issue by kimpers** [WalletConnect/walletconnect-monorepo#264]
Library version: `@walletconnect/web3-provider@^1.0.0-beta.93`

When implementing meta transactions with the `eth_signTypedData` RPC method for WalletConnect I noticed that the library expects the params array in reverse order.

The [docs](https://docs.walletconnect.org/json-rpc/ethereum) specify the `eth_signTypedData`  request data as 
```javascript
// Request
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_signTypedData",
  "params": ["0x9b2055d370f73ec7d8a03e965129118dc8f5bf83", typedData],
}
```

The expectation is then that the below code will work:
```typescript
const response: string = await web3Provider.send('eth_signTypedData', [address, typedData]);
```
But that leads to this error
![image](https://user-images.githubusercontent.com/5450545/81177154-8233d700-8fa6-11ea-9eb7-6022b6246f08.png)

Swap the params order to
```typescript
const response: string = await web3Provider.send('eth_signTypedData', [typedData, address]);
```
and the call succeeds.

**Comment by pedrouid** [comment]
Is this still an issue with the latest release?

**Comment by kimpers** [comment]
I'm having some difficulties testing this due to external factors. I will get back to you as soon as possible.

**Comment by finessevanes** [comment]
Hey @kimpers, is this still an issue?

**Comment by kimpers** [comment]
> Hey @kimpers, is this still an issue?

I think this was fixed ages ago, sorry for not closing the issue previously! Closing now 🙏
