### ISSUE TITLE
WalletConnect v2 does not work with some supported chains

### ISSUE THREAD

**Issue by ksamarin90** [WalletConnect/walletconnect-monorepo#2643]
**Describe the bug**
According to https://docs.walletconnect.com/2.0/advanced/multichain/chain-list following chains should be supported by WalletConnect V2: Klaytn Mainnet Cypress, xDAI Chain, Moonbeam, Moonriver.

While trying to connect to them via scanning QR code with TrustWallet and instantiating EthereumProvider like so:
```
const provider = await EthereumProvider.init({
	projectId: 'xxx',
	chains: [8217, 100, 1284, 1285],
	showQrModal: true,
});
```
following error occurs: ```Error: Requested chains are not supported```.

**To Reproduce**
See above.

**Expected behavior**
Connection to supported chains Klaytn Mainnet Cypress, xDAI Chain, Moonbeam, Moonriver should be established without error.

**Comment by bkrem** [comment]
Hi @ksamarin90,

> According to [docs.walletconnect.com/2.0/advanced/multichain/chain-list](https://docs.walletconnect.com/2.0/advanced/multichain/chain-list) following chains should be supported by WalletConnect V2: Klaytn Mainnet Cypress, xDAI Chain, Moonbeam, Moonriver.

Correct, but more specifically this list shows chains that have indicated that they can be used with WalletConnect v2.

> While trying to connect to them via scanning QR code with TrustWallet...following error occurs: Error: Requested chains are not supported.

This means that Trust as the wallet (currently) does not have support for some of these chains, WalletConnect itself is agnostic to the chains being specified.
