### ISSUE TITLE
[EthereumProvider] Expose `relayUrl` in options for `EthereumProvider.init`

### ISSUE THREAD

**Issue by bkrem** [WalletConnect/walletconnect-monorepo#2645]
**Is your feature request related to a problem? Please describe.**

- UniversalProvider takes in [`relayUrl` as an option](https://github.com/WalletConnect/walletconnect-monorepo/blob/feat/mobile_detect/providers/universal-provider/src/types/misc.ts#L7)
- This option isn't exposed one level above, in the [EthereumProvider config options](https://github.com/WalletConnect/walletconnect-monorepo/blob/feat/mobile_detect/providers/ethereum-provider/src/EthereumProvider.ts#L175)
- This creates an unnecessary complication in setting `relayUrl` when using EthereumProvider

**Describe the solution you'd like**

- Expose `relayUrl` as an optional parameter in EthereumProvider
- Forward the value through to `UniversalProvider` if defined

**Comment by bkrem** [comment]
cc @ganchoradkov

**Comment by windatang** [comment]
has same problem.  because wish keep on use 1.0 relay

**Comment by windatang** [comment]
another question is 
when do  `await EthereumProvider.init()` <w3m-modal> will create a instance. 
If user close the w3m-modal , we use `disconnect ` call but `w3m-modal` is no way to clear.
User do another connection it will run `await EthereumProvider.init()` again ... then another `w3m-modal` be created, how to clean the w3m-modal instance when disconnect
