### ISSUE TITLE
Relay protocol not supported

### ISSUE THREAD

**Issue by luanccp** [WalletConnect/walletconnect-monorepo#2654]
**Describe the bug**
My app is trying to connect to [1inch](https://app.1inch.io/#/1/simple/swap/ETH/DAI) and [Uniswap]( https://app.uniswap.org/#/swap) but keep giving me this error:

```
Error: Walletconnect Relay protocol not supported
```

**SDK Version**
 - Client: **JS (react-native-0.70.8)**
 - packages:
```json    
@walletconnect/core": "2.7.0",
@walletconnect/encoding": "1.0.2",
@walletconnect/react-native-compat": "2.7.0",
@walletconnect/web3wallet": "1.5.1",
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS ventura 13.0]

**Smartphone (please complete the following information):**
 - Device: [iPhone 14]
 - OS: [iOS 16.2]

**Additional context**
Here is my connection snnippet:

```tsx
const createWeb3Wallet = useCallback(async () => {
    try {
      const { eip155Addresses } = await createOrRestoreEIP155Wallet()
      setCurrentETHAddress(eip155Addresses[0])

      const core = new Core({
        projectId: 'xxxxx',
      })

      return await Web3Wallet.init({
        core,
        metadata: {
          name: 'XXXX',
          description: 'xxxxx | Buy and sell cryptocurrency',
          url: 'https://xxxxx.io',
          icons: [
            'https://app.xxxxx.com/logo/xxxxx--logo__light.png',
          ],
        },
      })
    } catch (error) {
      console.error('createWeb3 : ', error)
    }
  }, [web3WalletRef])
```

Everything looks ok, but when I try to pair wallet with:

```tsx
core.pairing.pair({ uri })
```

I got the error:

```
Error: Walletconnect Relay protocol not supported
```
**Note:**

I tried to pair with wallets here (https://react-app.walletconnect.com/) and it works but when I go to real examples, it breaks.

**Comment by ganchoradkov** [comment]
Hey @luanccp, this error is thrown when you try to pair v2 wallet with v1 URI. The behaviour is expected as v1 & v2 are not compatible

**Comment by flashedcode** [comment]
bro-

**Comment by waheedshe** [comment]
when i connect my wallet with any site shows eror i.e Relay protocol not supported #2654 ( wc:9cd950c37333e85d19282029b4e2d1d301283cfb52d0f10f6414b18eb3f7239b@2?relay-protocol=irn&symKey=92e0a0a3511a3190893073aa703050ef938e4e75c033af067fce9082d4f27312 ) how to solve this issue plz guide

**Comment by bilalkhanswatim** [comment]
https://npo.manta.network/calamari/sbt/projects/zkReadON

**Comment by Idria05** [comment]
Tmbh ke wab

**Comment by ahmed522005** [comment]
wc:2b30404e87960fc7a08575eb55c95aff750980e747564fee6c4c3711bc9cd6fd@2?relay-protocol=irn&symKey=fc67ca8a593dad695c322400c0678bbd5075be548b1e176d49186ac81addefab&expiryTimestamp=1768914417

**Comment by qaisarshabir** [comment]
0xE1Fc3973CAf49e63B4c4e61C700b182879145E53
