### ISSUE TITLE
Add LikeCoin chain

### ISSUE THREAD

**Issue by williamchong** [WalletConnect/walletconnect-monorepo#2658]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets 
   cosmos-rpc
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   cosmo
3. **namespaces**: 
  `cosmos`
4. **chains**:
  mainnet: `cosmos:likecoin-mainnet-2`
  testnet: `cosmos:likecoin-public-testnet-5`
   
5. **RPC endpoints**
  https://mainnet-node-rpc.like.co
   
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
 118

**Additional context**

LikeCoin is an application-specific blockchain on decentralized publishing built on Cosmos SDK. LikeCoin provides open source products ranging from infrastructure to publishing tools for creators on board to Web3.

Official Site: https://like.co/
Application: https://liker.land
CMC listing: https://coinmarketcap.com/currencies/likecoin/
Explorer: https://mintscan.io/likecoin
Github: https://github.com/likecoin

**Comment by bkrem** [comment]
Thanks for submitting 🙏 

Added to https://cloud.walletconnect.com/
