### ISSUE TITLE
Wallet Connect does not show any balance using RYO cloud as an RPC

### ISSUE THREAD

**Issue by pimato** [WalletConnect/walletconnect-monorepo#266]
Hey guys,

seems like there are issues with Wallet Connect if a dapp is using `https://mainnet.eth.cloud.ava.do`. You can check the dapp out on Dxtest.eth.link.

The console log:
<img width="2021" alt="Screenshot 2020-05-09 at 14 32 33" src="https://user-images.githubusercontent.com/5337809/81476329-be1ea480-9211-11ea-98d7-18537a004970.png">

**Comment by miohtama** [comment]
Is this a WalletConnect issue or DXDao issue? Is there a something you want change in WalletConnect? I am trying to understand if there is something WalletConnect maintainers can do here.

**Comment by pimato** [comment]
> Is this a WalletConnect issue or DXDao issue? Is there a something you want change in WalletConnect? I am trying to understand if there is something WalletConnect maintainers can do here.

There is a high chance that it seems to be an issue of either the avado rpc, or wallet connect as the local version seems to have no issue at all.

Also, connecting works without any problems. But seeing no balances seems like an issue not related to the dapp.

There is a chance that wallet-connect has issues with ryo cloud nodes.

**Comment by pimato** [comment]
The codebase is: https://github.com/levelkdev/BC-DAPP/tree/master/src

**Comment by pimato** [comment]
For example you could test if this rpc: `https://mainnet.eth.cloud.ava.do` works with your demo application.

**Comment by pedrouid** [comment]
I've just tested this on the Web3Modal example using the provided RPC url from RYO and I can confirm I get the same result with the 415 (Unsupported Media Type) error message

<img width="1920" alt="Screenshot 2020-05-12 17 51 37" src="https://user-images.githubusercontent.com/10136079/81716228-6edaad00-9479-11ea-9eee-b1d730b5e384.png">

Inspecting the Network tab on the browser we can see this payload is a JSON-RPC POST request with method `eth_blockNumber`

<img width="1031" alt="Screenshot 2020-05-12 17 52 56" src="https://user-images.githubusercontent.com/10136079/81716332-8fa30280-9479-11ea-94d1-5b3f667dd5be.png">

This however doesn't happen with other RPC endpoints I've tested (Infura and MyCrypto). We should share this information with the RYO team

cc @sponnet

**Comment by pedrouid** [comment]
Fixed prior to v1.0.0
