### ISSUE TITLE
Always console.log the QR code contents

### ISSUE THREAD

**Issue by miohtama** [WalletConnect/walletconnect-monorepo#268]
This makes it easier to connect to your dApp with test.walletconnect.org when developing the app. This is useful for diagnosing any issues.

**Comment by miohtama** [comment]
@pedrouid What do you think about this?

**Comment by pedrouid** [comment]
I think the whole monorepo needs proper logging with Winston-like logLevels...

But let's log the URI on the qrcode-modal for now
