### ISSUE TITLE
throw error when calling the eth_sendTransaction method 

### ISSUE THREAD

**Issue by CSSE-WZ** [WalletConnect/walletconnect-monorepo#2686]
throw error when calling the eth_sendTransaction 
![image](https://github.com/WalletConnect/web-examples/assets/22407879/6a538a78-b88a-45e5-aa3b-83fa60fef7c5)

Because I have the same error in the project, I would like to ask what is the reason for this error.

**Comment by crypblizz8** [comment]
Hey there, do you have funds in your account to `sendTransaction`?

**Comment by CSSE-WZ** [comment]
> Hey there, do you have funds in your account to `sendTransaction`?

I have some in my account, although not much.

**Comment by crypblizz8** [comment]
Please provide more reproduction steps 

1) Version of the package you are using
2) Reproducible code via a codeBox
3) Which wallet (platform and version) you used to get to this error
4) Do you get the errors on https://react-web3wallet.vercel.app/

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few weeks.

Please reopen if you still encounter this issue :)
