### ISSUE TITLE
Add ZORA Network

### ISSUE THREAD

**Issue by iainnash** [WalletConnect/walletconnect-monorepo#2696]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
   ethereum-rpc
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   ethereum
3. **namespaces**:
  eip:155
4. **chains**:
  eip155:7777777
  zora mainnet
5. **RPC endpoints**
   * https://rpc.zora.co/
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
   60

**Additional context**
Add any other context here.

**Comment by bkrem** [comment]
Thanks for submitting 🙏 

Added to https://cloud.walletconnect.com/
