### ISSUE TITLE
WalletConnect V2 not working 

### ISSUE THREAD

**Issue by GouthamJM** [WalletConnect/walletconnect-monorepo#2700]
**Describe the bug**
- Unable to establish a connection , Client initialisation failing sometimes and even if it is initialised unable to connect session 

SDK Version
 - Client: @web3modal/standalone - 2.4.3,
 - @walletconnect/sign-client : 2.8.0

**To Reproduce**
1. Go to https://react-app.walletconnect.com/
2. Connect chains
3. Use any wallet connection v2 supported apps to connect like trust wallet , frontier or zerion 
4. You will be unable to establish a connection 

**Expected behavior**
Should be able to establish a connection from Dapp to wallet

**Screenshots**
![Screenshot 2023-06-21 at 12 29 50 PM](https://github.com/WalletConnect/walletconnect-monorepo/assets/67677902/b1d2413f-87b7-4d7d-a6b2-057e8c82a195)
![Screenshot 2023-06-21 at 12 30 02 PM](https://github.com/WalletConnect/walletconnect-monorepo/assets/67677902/0a79b70c-54b9-4cb5-846f-0b31cc02d254)
![Screenshot 2023-06-21 at 12 37 46 PM](https://github.com/WalletConnect/walletconnect-monorepo/assets/67677902/c26c9341-5dc0-484d-80e0-d7712be829dc)
![Screenshot_2023-06-21-12-37-32-31_49da22c4849f102aab27d809a7dc57cc](https://github.com/WalletConnect/walletconnect-monorepo/assets/67677902/ada86183-7914-4295-bc06-101c8892c332)

Desktop:
 - OS: Mac OS Ventura 13.4
 - Browser: Chrome 
 - Version: 114.0.5735.133 (Official Build) (arm64)

**Additional context**
- you can also check here https://web-v2-git-feat-walletconnectv2-frontier.vercel.app/

**Comment by ganchoradkov** [comment]
Hey, are you using a VPN that might be causing issues connecting with the relay?
On my side, everything is working fine.
I tested the vercel link you've shared and noticed in the session proposal as required methods you've set
```
eth_sendTransaction, 
ETH_SEND_TRANSACTION, 
wallet_switchEthereumChain, 
SWITCH_CHAIN, 
wallet_addEthereumChain, 
ADD_CHAIN
``` 

This connection would be auto rejected by most wallets as I suspect they won't be supporting `ADD_CHAIN,SWITCH_CHAIN` methods. is there documentation on these?
As per CAIP25 spec, proposal containing `required` methods that are unsupported by the wallet would be auto rejected

**Comment by aminhdev** [comment]
I got the same problem "Wallet Connect V2 not working", everything is working fine this morning, the problem occurred  2hours ago

**Comment by ghost** [comment]
I got the same problem, I cannot connect to WalletConnect now. Even with the React app [page](https://react-app.walletconnect.com/ ) 
Check the video: https://www.awesomescreenshot.com/video/18508784?key=1706a45beb3cad7b522b6ac160c60c65
Please help to check!

**Comment by li8061** [comment]
This morning can still be successfully matched, now the pairing is not responding, can you be professional?

**Comment by aminhdev** [comment]
Finally walletconnect status is updated => https://status.walletconnect.com

**Comment by GouthamJM** [comment]
> Hey, are you using a VPN that might be causing issues connecting with the relay? On my side, everything is working fine. I tested the vercel link you've shared and noticed in the session proposal as required methods you've set
> 
> ```
> eth_sendTransaction, 
> ETH_SEND_TRANSACTION, 
> wallet_switchEthereumChain, 
> SWITCH_CHAIN, 
> wallet_addEthereumChain, 
> ADD_CHAIN
> ```
> 
> This connection would be auto rejected by most wallets as I suspect they won't be supporting `ADD_CHAIN,SWITCH_CHAIN` methods. is there documentation on these? As per CAIP25 spec, proposal containing `required` methods that are unsupported by the wallet would be auto rejected

- I am not using any VPN
- even after I removed `wallet_switchEthereumChain` and `wallet_addEthereumChain` and retried I got the same issue

**Comment by tuahear** [comment]
https://status.walletconnect.com/ seems normal now

**Comment by boidushya** [comment]
Further clarity: [Partial Relay Outage in the Southeast Asia Region](https://status.walletconnect.com/incidents/r57h5rplk20t)

Closing this issue, since this should be resolved and behaviours should be back to normal.

**Comment by VictorBlockchain** [comment]
these folks don't give a F... moving on to metamask
