### ISSUE TITLE
 This morning can still be successfully matched, now the pairing is not responding, can you be professional?

### ISSUE THREAD

**Issue by li8061** [WalletConnect/walletconnect-monorepo#2705]
This morning can still be successfully matched, now the pairing is not responding, can you be professional?

**Comment by boidushya** [comment]
Duplicate of #2700

Further clarity: [Partial Relay Outage in the Southeast Asia Region](https://status.walletconnect.com/incidents/r57h5rplk20t)

Closing this issue, since this should be resolved and behaviours should be back to normal.
