### ISSUE TITLE
Add MEVerse mainnet and testnet Chain

### ISSUE THREAD

**Issue by judasowelu** [WalletConnect/walletconnect-monorepo#2716]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).

[ "net_version", "web3_clientVersion", "eth_feeHistory", "eth_chainId", "eth_blockNumber", "eth_getBlockByNumber", "eth_getBlockByHash", "eth_getBalance", "eth_gasPrice", "eth_estimateGas", "eth_getCode", "eth_sendRawTransaction", "eth_getTransactionCount", "eth_getTransactionReceipt", "eth_getTransactionByHash", "eth_getBlockTransactionCountByNumber", "eth_getTransactionByBlockNumberAndIndex", "eth_call", "eth_getLogs", "web3_clientVersion", "eth_clientVersion", "debug_traceCall", "debug_traceTransaction" ]

2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.

mainnet: eip155:7518
testnet: eip155:4759

3. **namespaces**:

eip155

4. **chains**:

mainnet: eip155:7518
testnet: eip155:4759

5. **RPC endpoints**

mainnet: https://rpc.meversemainnet.io
testnet: https://rpc.meversetestnet.io

6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
   _\* slip44 coin type used in the namespace_

mainnet: | 7518 | 0x80001d5e | MEV | MEVerse | 
testnet: | 1 | 0x80000001 |  | Testnet (all coins) |

**Additional context**
Add any other context here.

**Comment by judasowelu** [comment]
https://www.meverse.sg/
https://meversedex.gitbook.io/meverse-dev-docs/

**Comment by bkrem** [comment]
Added to [cloud.walletconnect.com](https://cloud.walletconnect.com/) 👍
