### ISSUE TITLE
invalid content type, only application/json is supported

### ISSUE THREAD

**Issue by deacix** [WalletConnect/walletconnect-monorepo#273]
Wallet connect sent json encoded data with -H 'content-type: text/plain;charset=UTF-8'..

**Comment by pedrouid** [comment]
What payload method was sent with this content-type?

There has been a previous issue with a payload being sent with a non-json content-type that was from web3-provider-engine

Wondering if this needs to be fixed there instead

**Comment by pedrouid** [comment]
Fixed prior to v1.0.0
