### ISSUE TITLE
[Core] Expand tests to cover possible regressions around storage alloc

### ISSUE THREAD

**Issue by bkrem** [WalletConnect/walletconnect-monorepo#2737]
**Is your feature request related to a problem? Please describe.**

- Our [`persistence`](https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/sign-client/test/sdk/persistence.spec.ts) and [`client lifecycle`](https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/sign-client/test/sdk/client.spec.ts) test suites currently do not exhaustively cover checks on storage growth over time.

**Describe the solution you'd like**

- In order to detect possible regressions early, particularly ones that are hard to spot in lower level `core` storage keys, we should add assertions to check e.g. whether:
	- all storage keys after multiple restarts are in the same state
	- all storage keys are in the expected state after multiple pairing connects/disconnects
	- all storage keys are in the expected state after multiple session connects/disconnects
	- the testDB is growing beyond a certain expected benchmark after a series of user flows

**Comment by JonathanConn** [comment]
> * all storage keys are in the expected state after multiple session connects/disconnects

@bkrem Relay dis/connects or subscription un/subs?
Might be good to test both

**Comment by JonathanConn** [comment]
Ran into an issue with inconsistent results due to other test suites using the same `test.db`
Switched tests in `persistence` group to use separate db's to make test results consistent

Is there a better approach for this?
It would be nice to keep using `test.db` for the fourth bullet point

**Comment by bkrem** [comment]
> > * all storage keys are in the expected state after multiple session connects/disconnects
> 
> @bkrem Relay dis/connects or subscription un/subs? Might be good to test both

Not sure I understand:
* Relay dis/connects should be covered by `all storage keys after multiple restarts are in the same state`, i.e. given the same storage does initialising the client itself add to storage for some reason even though no state has changed?
* Leakage in `subscriptions` should be exposed by creating and disconnecting pairings and/or sessions since each new pairing/session creates a new subscription and should unsubscribe it/clean it up on delete

I think what's particularly of interest is checking that the lower level storage keys aren't accumulating garbage over time, i.e. when a session is deleted (see https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/sign-client/src/controllers/engine.ts#L418), do we:
* unsubscribe from the topic as expected (`subscriptions` key)
* clean up in `keychain` properly
* clean up in the `expirer` properly
* etc

Similarly for whenever we do a session request (https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/sign-client/src/controllers/engine.ts#L475), we create a history record. Can we trace that and make sure that all records created (`history` + others) are cleaned up properly when the result/response for that request is received?

**Comment by bkrem** [comment]
> Ran into an issue with inconsistent results due to other test suites using the same `test.db` Switched tests in `persistence` group to use separate db's to make test results consistent
> 
> Is there a better approach for this? It would be nice to keep using `test.db` for the fourth bullet point

Can you put up a draft PR so it's easier for myself and Gancho to help out with possible roadblocks or tweaks to the test DB setup? 

May well be that we need to set those test DBs up in a different way or create a dedicated test suite for this with the needed behaviour.
