### ISSUE TITLE
[EthereumProvider]: Wrong RPC gets used

### ISSUE THREAD

**Issue by THOUSAND-SKY** [WalletConnect/walletconnect-monorepo#2753]
**Describe the bug**
RPC does not match the network that is in wallet.

**SDK Version (if relevant)**
 - Client: `"@walletconnect/ethereum-provider": "^2.8.2",`

**To Reproduce**

```ts
const wc = await EthereumProvider.init({
      projectId: '...',
      chains: [SupportedNetworkIDs.Mainnet],
      optionalChains: [SupportedNetworkIDs.Local, SupportedNetworkIDs.Mumbai],
      rpcMap: {
        [SupportedNetworkIDs.Mainnet]: 'https://polygon-rpc.com/',
        [SupportedNetworkIDs.Mumbai]: 'https://rpc-mumbai.maticvigil.com/',
        [SupportedNetworkIDs.Local]: 'http://localhost:8545/',
      },
      showQrModal: true,
    })
await wc.enable()
```

Mobile Metamask is on Mumbai network, however when I connect I see rpc requests going to `polygon-rpc.com`. With the old `@walletconnect/web3-provider`, this was not the case. Is that intentional?

Having more than 1 chain id in `chains` immediately fails with "Unexpected chains" error.

This means I can't get e.g. user balances reliably.

**Expected behavior**
Should use the network that is active in the wallet.

**Desktop (please complete the following information):**
 - Browser Firefox
 - Version latest stable

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy s8
 - OS: Android

**Comment by crypblizz8** [comment]
Hey @THOUSAND-SKY, thanks for the ticket here.

`Is that intentional?` Nope, this is being fixed on the MM side to allow for better handling of switching at the moment. Will update this thread when resolved
