### ISSUE TITLE
Bundle in cdn duplicating dependencies 

### ISSUE THREAD

**Issue by octavioamu** [WalletConnect/walletconnect-monorepo#276]
seems https://unpkg.com/@walletconnect/web3-provider@1.0.0-beta.98/dist/umd/index.min.js and previews versions have some repeated libs with diff versions 
example 
[js-sha3]{@link https://github.com/emn178/js-sha3%7D is being injected to times to diff versions
@version 0.5.7  and @version 0.8.0

Also there is a ref to `_where":"/Users/pedrogomes/_walletconnect/walletconnect-monorepo/node_modules/secp256k1","author":{"name":"Fedor Indutny","email":"fedor@indutny.com"},"bugs":` generating an fallback error when sending eth

**Comment by octavioamu** [comment]
Seems eccrypto-js use "js-sha3": "0.8.0",
![image](https://user-images.githubusercontent.com/1358093/83439331-50812500-a419-11ea-9874-27144b25cef6.png)
but then ethersproject/keccak256 use "js-sha3": "0.5.7"
![image](https://user-images.githubusercontent.com/1358093/83439340-56770600-a419-11ea-80aa-d91b0e8d876e.png)

**Comment by pedrouid** [comment]
Fixed prior to v1.0.0
