### ISSUE TITLE
Add SanR chain

### ISSUE THREAD

**Issue by mqklin** [WalletConnect/walletconnect-monorepo#2786]
**Adding a new chain to the Explorer**

1. JSON-RPC: ethereum-rpc  https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc
2. CASA namespace spec: eip155 https://github.com/ChainAgnostic/namespaces/tree/main/eip155
3. namespaces: eip155
4. chains:
  mainnet: eip155:11888
  testnet: eip155:48991
5. RPC endpoints:
      https://sanrchain-node.santiment.net/
      https://sanrchain-node-stage.santiment.net/
6. seems like 60 but we use "SAN" name because we have bridge from our ERC20 token in ethereum mainnet (https://etherscan.io/token/0x7c5a0ce9267ed19b22f8cae653f198e3e8daf098) to our internal chain coin with exchange one to one

**Comment by mqklin** [comment]
@finessevanes @pedrouid hey guys, could you check this? 7h till shutdown and our dApp won't work without SanR chain WC support

**Comment by bkrem** [comment]
Added to [cloud.walletconnect.com](https://cloud.walletconnect.com/) 👍 

> 7h till shutdown and our dApp won't work without SanR chain WC support

To be clear, having a chain be discoverable via WalletConnect Cloud/Explorer _does not impact_ the actual usability of that chain. A dapp can still request any chain as required/optional and its up to the actual wallet to signal support for it.

In Cloud/Explorer, wallets and dapps can signal support for specific chains to aid with filtering and sorting for e.g. which dapps/wallets support Solana. Example: https://walletconnect.com/explorer

**Comment by mqklin** [comment]
@bkrem why I had `description:"We don't support the chainId you provided: eip155:11888"` error then? I believe it was triggered by WalletConnect

**Comment by mqklin** [comment]
I mean, some of requests to walletconnect bridge returned this error

**Comment by bkrem** [comment]
This means that that is what the peer (presumably a wallet) returned. WalletConnect is simply the transport layer which is agnostic to what the content of any specific request is, it simply relays the request to the peer (wallet/dapp).

**Comment by mqklin** [comment]
@bkrem I'm even more frustrated now. I created this issue because https://github.com/orgs/WalletConnect/discussions/2778 here [finessevanes](https://github.com/finessevanes) pointed me to create it. I still get this error on the same request: 
```
Request URL: https://rpc.walletconnect.com/v1?chainId=eip155:11888&projectId=cc8aef5fad63985030ea3e2e9eb0eb38
Request Method: POST
Status Code: 400 Bad Request
Request payload: 
id: "1687958299561519360"
jsonrpc: "2.0"
method: "eth_call"
params: [{data: "0x921276ea", to: "0x5bde1a89bb7667b443866d51582ace737a8c09bd"}, "latest"]
Response: {
    "status": "FAILED",
    "reasons": [
        {
            "field": "chainId",
            "description": "We don't support the chainId you provided: eip155:11888"
        }
    ]
}
```

(Now I see that there is `v1` path, despite I use `web3modal` and `wagmi` latest versions... will investigate further)

**Comment by bkrem** [comment]
Ah this isn't WalletConnect the protocol, this is the RPC proxy, which may indeed not have current support for this chain if none of the providers we proxy support it, cc @Rakowskiii

**Comment by mqklin** [comment]
@bkrem please describe my further steps to make it work

**Comment by mqklin** [comment]
@bkrem @Rakowskiii @finessevanes guys please let me know what to do next? Create another issue? And link this issue there?

**Comment by mqklin** [comment]
@bkrem @Rakowskiii @finessevanes guys please let me know, did you fix this? Because now I don't see that error, and IDK why.

**Comment by mqklin** [comment]
Now i'm getting it again. I get it, or I get `TypeError: Cannot read properties of undefined (reading 'length')` error. Not sure what is casing it - WC or MM (iOS).
