### ISSUE TITLE
Add SKALE Network Chains (EVM Compatible)

### ISSUE THREAD

**Issue by TheGreatAxios** [WalletConnect/walletconnect-monorepo#2787]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
   **Link**: https://docs.skale.network/technology/json-rpc-interface
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   eip155
3. **namespaces**:
   _\*known chain namespaces (e.g. eip:155 for Ethereum/EVM-based chains, solana, ...)_
eip:155
4. **chains**:
   _\*known chains, where the primary key is a compound key composed of namespace + reference (e.g. ETH mainnet is eip155:1)._
   _Please provide labels for each chain (e.g. mainnet, testnet, devnet, ...)

**Mainnet Chains (Mainnet)**

SKALE Europa Hub
eip155:2046399126

SKALE Calypso Hub
eip155:1564830818

SKALE Nebula Hub
eip155:1482601649

SKALE Titan Hub
eip155:1350216234

CryptoBlades Chain
eip155:1026062157

Human Protocol Chain
eip155:1273227453

**Testnet Chains (Testnet)**

SKALE Europa Hub
eip155:476158412

SKALE Calypso Hub
eip155:344106930

SKALE Nebula Hub
eip155:503129905

SKALE Titan Hub
eip155:1517929550

SKALE Chaos Testnet
eip155:1351057110

5. **RPC endpoints**
   _\*list of common/canonical RPC endpoints for the chain(s)_

   **Mainnet Chains (Mainnet)**
SKALE Europa Hub
rpc: https://mainnet.skalenodes.com/v1/elated-tan-skat
wss: wss://mainnet.skalenodes.com/v1/ws/elated-tan-skat

SKALE Calypso Hub
rpc: https://mainnet.skalenodes.com/v1/honorable-steel-rasalhague
wss: wss://mainnet.skalenodes.com/v1/ws/honorable-steel-rasalhague

SKALE Nebula Hub
rpc: https://mainnet.skalenodes.com/v1/green-giddy-denebola
wss: wss://mainnet.skalenodes.com/v1/ws/green-giddy-denebola

SKALE Titan Hub
rpc: https://mainnet.skalenodes.com/v1/parallel-stormy-spica
wss: wss://mainnet.skalenodes.com/v1/ws/parallel-stormy-spica

CryptoBlades Chain
rpc: https://mainnet.skalenodes.com/v1/affectionate-immediate-pollux
wss: wss://mainnet.skalenodes.com/v1/ws/affectionate-immediate-pollux

Human Protocol Chain
rpc: https://mainnet.skalenodes.com/v1/wan-red-ain
wss: wss://mainnet.skalenodes.com/v1/ws/wan-red-ain

**Testnet Chains (Testnet)**

SKALE Europa Hub
rpc: https://staging-v3.skalenodes.com/v1/staging-legal-crazy-castor
wss: wss://staging-v3.skalenodes.com/v1/ws/staging-legal-crazy-castor

SKALE Calypso Hub
rpc: https://staging-v3.skalenodes.com/v1/staging-utter-unripe-menkar
wss: wss://staging-v3.skalenodes.com/v1/ws/staging-utter-unripe-menkar

SKALE Nebula Hub
rpc: https://staging-v3.skalenodes.com/v1/staging-faint-slimy-achird
wss: wss://staging-v3.skalenodes.com/v1/ws/staging-faint-slimy-achird

SKALE Titan Hub
https://staging-v3.skalenodes.com/v1/staging-aware-chief-gianfar
wss: wss://staging-v3.skalenodes.com/v1/ws/staging-aware-chief-gianfar

SKALE Chaos Testnet
https://staging-v3.skalenodes.com/v1/staging-fast-active-bellatrix
wss: wss://staging-v3.skalenodes.com/v1/ws/staging-fast-active-bellatrix

6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
60

**Additional context**
Add any other context here.

**Comment by bkrem** [comment]
@TheGreatAxios we're missing the SLIP-0044 coin type here, could you please specify (e.g. by default `60` for ETH) and we can then add the SKALE chains to be selectable for submissions in our Cloud/Explorer.

**Comment by TheGreatAxios** [comment]
Hey @bkrem 

Thanks for your response. I did some research into this and was a bit unsure. The chains are fully EVM compatible and support ERC-20 etc like ETH, however, the chains don't use ETH for gas, but sFUEL which is a value-less token. 

Is the SLIP value then 60 since it's compatible with Ethereum in that way? Or do different SLIPs need to be calculated? If so, can you provide guidance here as I went through all the docs but there is limited information on calculating slips coin ids. 

Thank you!

**Comment by bkrem** [comment]
Thanks for following up here @TheGreatAxios.

> Thanks for your response. I did some research into this and was a bit unsure. The chains are fully EVM compatible and support ERC-20 etc like ETH, however, the chains don't use ETH for gas, but sFUEL which is a value-less token.

 I think `60` ETH is a sensible default if sFUEL doesn't have its own SLIP-044 value 👍 

FYI we batch process these requests every Friday so this one will be included for this Friday's round.

**Comment by TheGreatAxios** [comment]
Thank you!

**Comment by TheGreatAxios** [comment]
Hey @bkrem 

Checking in to see when this will be added as it was not done this past Friday - thanks!

**Comment by bkrem** [comment]
@TheGreatAxios indeed, apologies for the wait. Cloud team got busy with other priorities end of last week.

Change is rolled out on staging. Will go live on https://cloud.walletconnect.com EU morning tomorrow

**Comment by TheGreatAxios** [comment]
Thank you and no worries - we are excited to have this available on SKALE!

**Comment by bkrem** [comment]
Added to https://cloud.walletconnect.com 👍
