### ISSUE TITLE
Add HOME Verse chain

### ISSUE THREAD

**Issue by musclemikiya** [WalletConnect/walletconnect-monorepo#2790]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [[one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc)](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [[JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/)](https://ethereum.org/en/developers/docs/apis/json-rpc/).
**GitHub Link**: https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc
2. Write a [[CASA namespace spec](https://github.com/ChainAgnostic/namespaces)](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
**GitHub Link**: https://github.com/ChainAgnostic/namespaces/tree/main/eip155
3. **namespaces**: 
eip155
4. **chains**:
HOME Verse mainnet: eip155: 19011
HOME Verse testnet: eip155: 40875
5. **RPC endpoints**
19011: https://rpc.mainnet.oasys.homeverse.games/
40875: https://rpc.testnet.oasys.homeverse.games/
6. **[[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
685: 0x800002ad

**Additional context**
Technical Document: https://dev-ml.gitbook.io/home-verse-tech-document/

**Comment by bkrem** [comment]
Added to [cloud.walletconnect.com](https://cloud.walletconnect.com/) 👍
