### ISSUE TITLE
Auto jump to `https://metamask.io/download/` when using EthereumProvider'sendAsync called eth_sign or personal_sign method.

### ISSUE THREAD

**Issue by T-Matrix** [WalletConnect/walletconnect-monorepo#2791]
**Describe the bug**
I use `@walletconnect/ethereum-provider` in my dapp. I initialed it with below code:
```
    const providerClient = await EthereumProvider.init({
        projectId: "******",
        showQrModal: true,
        optionalMethods: OPTIONAL_METHODS,
        optionalEvents: OPTIONAL_EVENTS,
        qrModalOptions: { 
          themeMode: "light",
        },
        chains: chainIds,
        rpcUrls: rpcUrls,
      });
```
Then, Connect it: 
```
await providerClient.connect()
const accounts = await providerClient.enable();
const addr = accounts[0];
```
And then, using Trust wallet app to scan QrCode to connect wallet. All of these is OK. 
After connect, I called `sign` method: 
```
    providerClient.sendAsync({
          method: "eth_sign",
          params: ["hello", addr]
      }, (err, res) => {
        console.log(res);
        debugger;
      });
```
Then, my dapp auto open `https://metamask.io/download/`. And the same time, trust wallet popup sign request window.

**SDK Version (if relevant)**
"@walletconnect/ethereum-provider": "2.8.3",
"@walletconnect/modal": "^2.5.4",

**Screenshots**
1: my dapp
<img width="415" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/111719095/147344b5-0909-4d64-8022-f19abe6413e6">

2: Using my mobile Trust to scan qrcode to connect:
<img width="377" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/111719095/ca2421f7-188f-4464-b0a6-a92b500bd29b">

3: Then call `eth_sign`, but my dapp website auto jump to `https://metamask.io/download/`
<img width="623" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/111719095/b243abce-5539-4e29-84b2-d41c3edbf71d">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 114.0.5735.133 

**Smartphone (please complete the following information):**
 - Device: iPhone14
 - OS: iOS 16.5.1
 - Trust wallet app

**Comment by glitch-txs** [comment]
Hi could you share a minimal reproducible example repo?

Also, one small detail, when you call `enable` function you are calling `connect` + requesting accounts, so if you call `enable` you don't need to call `connect`

**Comment by glitch-txs** [comment]
Also could you try using "personal_sign" instead?

**Comment by T-Matrix** [comment]
“personal_sign” has same issue

**Comment by T-Matrix** [comment]
The issue has solved. When I make a repo. I re-run my demo dapp. And I change the code : 
```
await provider.connect()
await provider.enable()
```
to 
```
await provider.enable()
```
The issue solved. Thank you @glitch.txs . The answer you reply is correct. I should try it more earlier.
