### ISSUE TITLE
Cannot stop listening for new session when I close QR modal

### ISSUE THREAD

**Issue by ptsayli** [WalletConnect/walletconnect-monorepo#28]
`listenSessionStatus` returns promise not `listnerObject`. That would be great if we have an option to stop listening with `listnerObject.stop()`

**Comment by pedrouid** [comment]
Following on Discord discussion, let’s add method `cancel()` or maybe even `stop()` for Promises like the implementation that Bluebird uses

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pedrouid** [comment]
Check out PR #30
