### ISSUE TITLE
web3-provider `Cannot read property 'bridge' of undefined` error

### ISSUE THREAD

**Issue by Velenir** [WalletConnect/walletconnect-monorepo#280]
Starting with version `beta.88` when I do `provider.enable()`, it breaks with `Cannot read property 'bridge' of undefined` error

You can check in this [sandbox](https://codesandbox.io/s/proud-microservice-t5eu7?file=/src/App.tsx)

**Comment by pedrouid** [comment]
Is this issue also present in beta.100?

**Comment by Velenir** [comment]
Yes, all versions ≥beta.88

**Comment by pedrouid** [comment]
I was able to run it in the example however...

https://github.com/WalletConnect/walletconnect-monorepo/blob/next/example/public/web3-provider.js

**Comment by Velenir** [comment]
> I was able to run it in the example however...
> 
> https://github.com/WalletConnect/walletconnect-monorepo/blob/next/example/public/web3-provider.js

That one uses a minified bundle with all dependencies already there at proper version
But when installing locally #281 was happening
Now resolved with `rc.0` release :clap:
