### ISSUE TITLE
Ledger Live not sending a correct signature when it executes personal_sign

### ISSUE THREAD

**Issue by valeriivanchev** [WalletConnect/walletconnect-monorepo#2803]
1. The signature provided from Ledger Live after signing a message is not a valid signature. We use ethereum provider 2.8.0 and walletconnect/modal 2.4.5. The decoding works for every other wallet except Ledger Live. 
2. When personal sign is executed separately Ledger Live opens WalletConnect v1.

Steps to reproduce the first issue:
1. Connect with WalletConnect v2
3. Send a message
4. Sign message
5. Decode signature

Steps to reproduce the second issue:
1. Open [https://react-dapp-v2-with-ethers.vercel.app/](url) 
1. Connect with WalletConnect v2 to Ledger Live
3. Press personal_sign

**Expected behavior for the first issue**
To send a valid signature

**Expected behavior for the second issue**
To open and sign with WalletConnect v2

**Comment by JonathanConn** [comment]
@valeriivanchev Thanks for reaching out and letting us know!
We have noticed some discrepancies across ledger live on different platforms 
Which platform and version are you using?

**Comment by valeriivanchev** [comment]
@JonathanConn I am on MacOS and using Ledger Live v2.60.0

**Comment by JonathanConn** [comment]
@valeriivanchev perfect, that is the latest and greatest from ledger

For the first issue, I was unable to reproduce it on my end, could you clarify what you mean by the signature is invalid

As for the second issue, ledger had some temporary routing set up over the past few weeks due to the WC v1 -> v2 migration. It should no longer be an issue as they removed v1 entirely earlier today, could you check again for me? Thank you

**Comment by valeriivanchev** [comment]
@JonathanConn the issue regarding the wallectConnect v1 redirect is fixed and the incorrect signing as well, but now we saw that WalletConnect v2 creates two session into ledger live and it only happens with ledger we tried Metamask and checked the session and there is only one. Because of the two session any request we send is handled somehow from the other session and we don't get the response(e.g. personal_sign request).

**Comment by c-py** [comment]
We are also experiencing personal_sign hanging between the Wallet Connect v2 ethereum provider (v2.8.5) and Ledger Live.

I have tried to attach event listeners to the provider, to see if anything comes back, but have yet to find a response.

**Comment by JonathanConn** [comment]
@valeriivanchev @c-py 
I tested personal sign using our example app [here](https://react-app.walletconnect.com/) and it worked

Could you both provide more details about your provider configuration and or how you are sending the sign request? 

Please try it using the example app above. Once you are connected you can select send a personal sign easily

Let me know!

**Comment by c-py** [comment]
> Could you both provide more details about your provider configuration and or how you are sending the sign request?

We initialise the EthereumProvider like so, where `POLYGON_CHAIN_ID` is `137`.

```ts
const provider = await EthereumProvider.init({
  chains: [CONFIG.POLYGON_CHAIN_ID],
  projectId: CONFIG.WALLETCONNECT_PROJECT_ID,
  showQrModal: true,
  qrModalOptions: {
    themeVariables: { "--wcm-z-index": "1100" }, // Ensures modal appears above splash
  },
});

await provider.enable();
```

In order to make the request to personal sign, we use web3js like so:

```ts
cost web3 = new Web3(provider);
const signature await web3.eth.personal.sign("hello world", account, "");
```

I have also tested without web3js using the following code which had the same result:

```ts
const message = `0x${Buffer.from("hello world", "utf8").toString("hex")}`;
await provider.request({
  method: "personal_sign",
  params: [message, account]
});
```

It seems both methods are hanging for us.

> Please try it using the example app above. Once you are connected you can select send a personal sign easily

I have tested using the sample app, which has the same behavior and hangs.

**Comment by JonathanConn** [comment]
@c-py thanks for the super detailed comment, helps a lot 🙏

I tried a few different configs, ex apps, methods, ledger wallets, but I couldn't reproduce it

I've asked another team member with a ledger to test it

Could you send me your project ID so I can look into it more? 

The provider code looks good to me, I will try to reproduce it with a sandbox tomorrow

@bkrem Any thoughts?

**Comment by c-py** [comment]
> Could you send me your project ID so I can look into it more?

Interestingly, in my most recent tests, I was able to get past the hanging sometimes.

After further testing, it appears within ledger live, if I first exit the wallet connect screen after connecting it works. When I initiate personal_sign, it automatically navigates me back to the wallet connect screen and all of these signatures have been successful so far.

I'm going to ask the others to test using this flow as well, to sanity check this theory 😄

**Comment by valeriivanchev** [comment]
@JonathanConn also tested with the example app. Still the same issue. I am testing with Ledger Nano S.

**Comment by JonathanConn** [comment]
Another team member tested it and was unable to reproduce it
I passed this thread over to Ledger to see if they have any known issues with personal_sign
I will update you as soon as they respond, likely within 24hrs, cheers <3 

@c-py @valeriivanchev

**Comment by JonathanConn** [comment]
@valeriivanchev @c-py Ledger did not find any issues on their end, everything works as expected
If you make a min repro sandbox for me to debug further, I will open this back up
Sorry but there isnt much more I can do if my team cant reproduce it, best of luck!
