### ISSUE TITLE
Add HAQQ Network

### ISSUE THREAD

**Issue by olegshilov** [WalletConnect/walletconnect-monorepo#2806]
The issue aims to include HAQQ Network chains in the supported network list of WalletConnect, facilitating seamless connectivity and integration for users.

1. **JSON-RPC**: supported
2. **CASA namespace spec**: ---
3. **Namespace**: eip:155
4. **Chains**:
   - HAQQ Mainnet: eip155:11235
   - HAQQ Testedge 2: eip155:54211
5. **RPC endpoints**
   - HAQQ Mainnet: https://rpc.eth.haqq.network
   - HAQQ Testedge 2: https://rpc.eth.testedge2.haqq.network
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**: 1348

**Comment by bkrem** [comment]
Added to [cloud.walletconnect.com](https://cloud.walletconnect.com/) 👍

**Comment by Dundubus** [comment]
How do I connect

**Comment by vincenko** [comment]
Good
