### ISSUE TITLE
Depndencies range resolves to old version

### ISSUE THREAD

**Issue by Velenir** [WalletConnect/walletconnect-monorepo#281]
At least locally, when I install `@walletconnect/web3-provider@1.0.0-beta.100` or `@walletconnect/web3-provider@next` it pulls in its `@walletconnect/*` dependencies of version `1.0.0-next.0`.
Happens because `^1.0.0-beta.100` range in package.json seems to cover `1.0.0-next.0` and considers that higher
You can check with:
```sh
> $ npx semver 1.0.0-next.0 1.0.0-beta.100 1.0.0-beta.102 1.0.0-beta.101 -r "^1.0.0-beta.100"
1.0.0-beta.100
1.0.0-beta.101
1.0.0-beta.102
1.0.0-next.0

> $ npx semver 1.0.0-next.0 1.0.0-beta.100 1.0.0-beta.102 1.0.0-beta.101 -r ">1.0.0-beta.100"
1.0.0-beta.101
1.0.0-beta.102
1.0.0-next.0
```
or at https://semver.npmjs.com/
It might be a good idea to unpublish `1.0.0-next.0`

**Comment by pedrouid** [comment]
It's not possible to unpublish it but you can see on NPM that it's deprecated

https://www.npmjs.com/package/@walletconnect/web3-provider

**Comment by Velenir** [comment]
Oops, you're right, can't unpublish

Then maybe providing exact dependency versions would be good. Or a range like `^1.0.0-beta.100 <1.0.0-next`

**Comment by pedrouid** [comment]
I've started publishing packages with `1.0.0-rc.x` so this should be fixed now
