### ISSUE TITLE
[EthereumProvider]: Session update event validation fails when used in JS

### ISSUE THREAD

**Issue by MajdajkD** [WalletConnect/walletconnect-monorepo#2821]
**Describe the bug**
I have a project, which must compile into plain JavaScript and be able to handle different providers.
Everything works fine, (sending tx, signature, etc.), except detecting account changes (switch wallet).

**Version (if relevant)**
-@walletconnect/ethereum-provider: 2.8.4
-@walletconnect/modal: 2.5.4
-latest version of alphawallet

**To Reproduce**
1, Make a simple project with the following 3 files:
Index.html:

    <!DOCTYPE html>

    <html lang="en">

    <head>

      <title>TEST</title>

    </head>

    <body>

    <div class="container">

	<button onclick="clicked()">Connect</button>

    </div>

    <script src="dist/index.js"></script>

    <script>

    	localStorage.clear();

    	function clicked() {

    	    modaltest.connect();

    	} 

    </script> 

    </body> 

    </html> 

src.js:  (fill the projectId)

    import { EthereumProvider } from "@walletconnect/ethereum-provider";  
    window.modaltest =
    {
    	connect: async function () {
    		var ethereumProvider = await EthereumProvider.init({
    			projectId: '<FILL ME>',
    			showQrModal: true,
    			qrModalOptions: { themeMode: "light" },
    			chains: [97],
    			metadata: {
    			name: "My Dapp",
    			description: "My Dapp description",
    			url: "https://my-dapp.com",
    			icons: ["https://my-dapp.com/logo.png"],
    			},
    		});
    		
    		// chain changed
    		ethereumProvider.on('chainChanged', (e) => { alert('chainChanged') })
    		// accounts changed
    		ethereumProvider.on('accountsChanged', (e) => { alert('accountsChanged') })
    		// session established
    		ethereumProvider.on('connect', (e) => { alert('connect') })
    		// session event - chainChanged/accountsChanged/custom events
    		ethereumProvider.on('session_event', (e) => { alert('session_event') })
    		// connection uri
    		ethereumProvider.on('display_uri', (e) => { alert('display_uri') })
    		// session disconnect
    		ethereumProvider.on('disconnect', (e) => { alert('disconnect') })
    
    		await ethereumProvider.enable();
    	}
    }

package.json:

    {
      "name": "test",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "dependencies": {
        "@walletconnect/ethereum-provider": "^2.8.4",
        "@walletconnect/modal": "^2.5.4"
      },
      "devDependencies": {
        "webpack": "^5.88.0",
        "webpack-cli": "^5.1.4"
      },
      "scripts": {
        "build": "webpack --mode=development ./src.js --output-filename ./index.js"
      },
      "author": "",
      "license": "ISC"
    }

2, run:  "npm i"
3, run: "npm run-script build"
4, open index.html
5, click the button and connect alphawallet
6, change wallet (lower right corner-> settings/"Change/Add Wallet" option)
7, observe the lack of browser alert and the error on the console:

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/10176488/eecd6d7a-6f26-4396-8521-5d2b1d4f149f)

**Expected behavior**
"accountsChanged" event called.

**Comment by glitch-txs** [comment]
This should be fixed in the latest versions, please update all packages and let us know if the issue still persists.
