### ISSUE TITLE
"Internal error" exception instead of a proper "Unknown network [network_id]" exception

### ISSUE THREAD

**Issue by compojoom** [WalletConnect/walletconnect-monorepo#2825]
**Describe the bug**
Here is a sandbox: https://codesandbox.io/s/crazy-mahavira-vzjnjl?file=/src/App.vue

First delete your Optimism network in Metamask. After that connect with metamask to the app. Try to use the "select a network" dropdown to switch to Optimism. In the console you'll see the following exception:

```
Object { code: -32603, message: "Internal error" }
```

Switching to an unknown network should trigger a "Unknown network" or something of that sort, instead of an "internal error"

**SDK Version (if relevant)**
    "@walletconnect/ethereum-provider": "^2.8.4",
    "@walletconnect/modal": "^2.4.7",
    "@ethersproject/providers": "^5.5.2"

**To Reproduce**
Read the description above

**Expected behavior**
I would expect that switching to an unknown to a wallet network would trigger an "unknown network [network_id]" error. Triggering an "internal error" makes it hard to catch the exception and react to it.

**Desktop (please complete the following information):**
 - OS: MacOS ventura
 - Browser Firefox
 - Version 115.0b9 (64-bit)

**Smartphone (please complete the following information):**
 - Device: Iphone 13
 - Metamask 7.0.1 (1126)
 -

**Comment by crypblizz8** [comment]
Thanks @compojoom, wanted to confirm this ticket is around error messaging and the `unknown network [network_id]` error came from the wallet?

**Comment by compojoom** [comment]
No, I don't know what is coming from the wallet, but in v1 we were catching a message like this "Unrecognized chain ID", now we are getting an "internal error" from walletconnect/core.

**Comment by crypblizz8** [comment]
Thanks for the feedback.

Actually looks like it is from MM side to improve their error messaging. Will communicate to them.

**Comment by compojoom** [comment]
Awesome! 
It seems that you guys have a direct communication channel with MM and if that is the case also please forward this.

The sandbox also shows another problem - switching chains doesn't always work. 
After establishing a session - the first request to change chain always works. You get a prompt in Metamask to switch to that chain. Then when you switch to a different chain and try to switch back - metamask doesn't open a prompt. 
The response from
```
await this.web3Provider.send('wallet_switchEthereumChain', [{ chainId: newChainIdHex }]);
```
is null, which according to the EIP: https://eips.ethereum.org/EIPS/eip-3326 means that the active chain was switched, but that is not reflected in MM.

Now if you try to make a transaction you won't get a confirmation popup in metamask. 

Also, if you are establishing a connection and let's say that in MM you are on Optimism. Once you've connected when you try to switch chain to Mainnet - this never works.

**Comment by liubin595338764** [comment]
I have also encountered the same problem. Could you please advise on how to use the `wallet_switchEthereumChain` method? 

I know that V2 can simultaneously connect to multiple chains, but if I am unable to switch chains successfully, transactions will still be executed on the old chain.

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few weeks.

Please reopen if you still encounter this issue :)
