### ISSUE TITLE
QR code not showing up.

### ISSUE THREAD

**Issue by yann300** [WalletConnect/walletconnect-monorepo#2828]
**Describe the bug**
Can't see the QR code.

**To Reproduce**
Connect to metamak with wallet connect.
Disconnect, the modal shows a "loading" icon instead of the QR code.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome 110.0.5481.100

**Comment by crypblizz8** [comment]
Hey, thanks for reporting that. More than happy to help however can you please provide us with more detailed reporting:

1) Version of the package you are using
2) Reproducible code via a codeBox
3) Which wallet (platform and version) you used to get to this error

**Comment by aryanarcilia** [comment]
HI @yann300 , I have same issue with you.
I try to clear all local storage, session storage, cookies and reload page then issue was fixed. You can try to do this.

Hope this help.

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few weeks.

Please reopen if you still encounter this issue :)
