### ISSUE TITLE
closeTransport called before connection was established & MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 session_connect listeners added

### ISSUE THREAD

**Issue by jaan1025** [WalletConnect/walletconnect-monorepo#2830]
**Describe the bug**
I encountered several issues that prevented me from connecting to WalletConnect V2.

1. closeTransport called before connection was established

2. MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 session_connect listeners added
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/22076610/185e0094-5bb3-4c48-8a8b-639cea58b129)

Most of the time, I can successfully connect on localhost. However, in the testing environment, I consistently encounter the aforementioned problem, and it appears randomly.

Project ID: b7ad19852a93c14123be76ac79dab659

**SDK Version (if relevant)**
 "@walletconnect/ethereum-provider": "^2.7.7",
 "@web3modal/standalone": "^2.4.3",

**Comment by ganchoradkov** [comment]
Hey, @jaan1025 does your testing environment runs any proxies/VPNs that might prevent the client to connect with the relay?

**Comment by jaan1025** [comment]
> Hey, @jaan1025 does your testing environment runs any proxies/VPNs that might prevent the client to connect with the relay?

I used a VPN on my Mac. and I'm from China. Will the region affect the connection?

**Comment by ganchoradkov** [comment]
Yes. `walletconnect.com` is blocked in China. Could try setting `relayUrl: wss://relay.walletconnect.org` in the init params?

**Comment by jaan1025** [comment]
Let me give it a try

**Comment by jaan1025** [comment]
sry... I'm using @walletconnect/ethereum-provider, how to set `relayUrl` ? 
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/22076610/d46082fd-2dd1-4bfb-8bc9-2c84aefcca3b)

**Comment by ganchoradkov** [comment]
Please update to latest as the param was just recently added

**Comment by crypblizz8** [comment]
@jaan1025 please let us know if all resolved and we can close this issue

**Comment by jaan1025** [comment]
> @jaan1025 please let us know if all resolved and we can close this issue

It works for me, thank you very much.
