### ISSUE TITLE
Switching between multiple chains

### ISSUE THREAD

**Issue by amy8023** [WalletConnect/walletconnect-monorepo#2837]
I have a question , about  the function  'await provider.connect({ chains: ['56']})', if the arguments chains.length >1 ,why I can't to connect the wallet 'tokenpoket' , How can I switch between multiple chains

**Comment by amy8023** [comment]
does the v2 walletConnect always suporrt the  the wallet tokenpoket

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
