### ISSUE TITLE
Uncaught (in promise) TypeError: EthereumProvider.init is not a function

### ISSUE THREAD

**Issue by oxSaturn** [WalletConnect/walletconnect-monorepo#2845]
**Describe the bug**

Say I have a `index.mjs` file with the following code:

```
const {
    default: x,
    EthereumProvider,
} = await import('@walletconnect/ethereum-provider')

console.log(x, x.init, EthereumProvider.init);
```
And here's the `dependencies` of `package.json`:

```
  "dependencies": {
    "@walletconnect/ethereum-provider": "^2.8.4"
  }
```

Running `node index.mjs` would return:

```
node index.mjs
{
  EthereumProvider: [class g],
  OPTIONAL_EVENTS: [ 'message', 'disconnect', 'connect' ],
  OPTIONAL_METHODS: [
    'eth_accounts',
    'eth_requestAccounts',
    'eth_sendRawTransaction',
    'eth_sign',
    'eth_signTransaction',
    'eth_signTypedData',
    'eth_signTypedData_v3',
    'eth_signTypedData_v4',
    'wallet_switchEthereumChain',
    'wallet_addEthereumChain',
    'wallet_getPermissions',
    'wallet_requestPermissions',
    'wallet_registerOnboarding',
    'wallet_watchAsset',
    'wallet_scanQRCode'
  ],
  REQUIRED_EVENTS: [ 'chainChanged', 'accountsChanged' ],
  REQUIRED_METHODS: [ 'eth_sendTransaction', 'personal_sign' ],
  default: [class g]
} undefined [AsyncFunction: init]
```
As you can see above, `default.init` is undefined.

I.e., I can't use `const {default: EthereumProvider} = await import('@walletconnect/ethereum-provider')` to use `EthereumProvider.init` method.

**Comment by kringt06** [comment]
next-dev.js:20 initAccount Error: TypeError: Cannot read properties of undefined (reading 'init')

**Comment by oxSaturn** [comment]
Would love to share that code like `const {default: EthereumProvider} = await import('@walletconnect/ethereum-provider')` is a misuse, it imports the `exports` object from a commonjs module, not destructuring the `exports` object.

So the generated commonjs code like `exports.default` is misleading IMO.

Read more here https://stackoverflow.com/a/76580524/22148155

**Comment by sophialittlejohn** [comment]
also looking for a solution to the same error. I'm using the library [web3-react](https://docs.uniswap.org/sdk/web3-react/overview) which imports `@walletconnect/ethereum-provider` like this:
```js
import('@walletconnect/ethereum-provider').then(async (ethProviderModule) => {
      const provider = (this.provider = await ethProviderModule.default.init({
        ...this.options,
        chains,
        rpcMap: await rpcMap,
      }))
```

Setup is React with Vite.

Any help is appreciated!

**Comment by 4Alpha2Hunt0** [comment]
i have this same issue
