### ISSUE TITLE
wallet_addEthereumChain got 'Invalid params'

### ISSUE THREAD

**Issue by jaan1025** [WalletConnect/walletconnect-monorepo#2863]
**Describe the bug**
I got this error when I try to add a chain
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/22076610/4a89d6b5-7a0a-4ac9-b4e0-7a2d4a806045)

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/22076610/ea4051d2-5044-4665-aaf7-95d00f364b0a)

params as follow:
`{
    "chainId": "0xa",
    "blockExplorerUrls": [
        {
            "name": "Optimism Explorer",
            "url": "https://explorer.optimism.io"
        }
    ],
    "chainName": "Optimism",
    "nativeCurrency": {
        "name": "Ether",
        "symbol": "ETH",
        "decimals": 18
    },
    "rpcUrls": [
        "https://mainnet.optimism.io"
    ]
}`

**SDK Version (if relevant)**
"@walletconnect/ethereum-provider": "^2.8.5"

**Comment by MananTank** [comment]
@jaan1025 Which wallet where you connected to when you got this error?

**Comment by jaan1025** [comment]
> @jaan1025 Which wallet where you connected to when you got this error?

metamask

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few weeks.

Please reopen if you still encounter this issue :)
