### ISSUE TITLE
Resolve promise when qr modal is closed

### ISSUE THREAD

**Issue by nicholasmueller** [WalletConnect/walletconnect-monorepo#287]
Using package `@walletconnect/web3-provider": "^1.0.0-rc.2`

I do this...
```
const provider = new WalletConnectProvider({
  rpc: { 1: config.rpcProxy }
});
const result = await this.provider.enable();
```

Calling `enable()` triggers the modal. But if the user closes the modal without scanning the qr code, this promise never resolves. 

It would be very helpful to either have a rejection of the promise to indicate that the modal was closed, or resolve with a boolean indicating the state of the action.

**Comment by pedrouid** [comment]
Great catch 👌 Published a fix with `@walletconnect/web3-provider": "^1.0.0-rc.3`

**Comment by nicholasmueller** [comment]
Great thanks! Confirmed fixed in `1.0.0-rc.3`

**Comment by GabrielBuragev** [comment]
I am facing this issue with `"@walletconnect/ethereum-provider": "^2.3.2"`.

**Comment by GabrielBuragev** [comment]
For whoever is facing the same issue.
As a workaround i am using the following pattern to achieve control over the resolution of the promise:
```
import { EthereumProvider as WalletConnectV2 } from '@walletconnect/ethereum-provider';

new Promise((resolve) => {
    (async () => {
     // ...
      const provider = await WalletConnectV2.init({
        chains,
        projectId: <project_id>,
        rpcMap,
      });

      provider.modal?.subscribeModal(async (newState) => {
        if (!newState.open && !provider.session) {
          resolve(undefined);
        }
      });

      await provider.enable();

      if (provider.connected) {
        return resolve(provider);
      }

      resolve(undefined);
    })();
  });
  ```
