### ISSUE TITLE
add Scroll Alpha network

### ISSUE THREAD

**Issue by dghelm** [WalletConnect/walletconnect-monorepo#2879]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
   ethereum-rpc
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   ethereum
3. **namespaces**:
   eip:155
4. **chains**:
   _\*known chains, where the primary key is a compound key composed of namespace + reference (e.g. ETH mainnet is eip155:1)._
   Scroll Alpha Testnet: eip155:534353
5. **RPC endpoints**
   https://alpha-rpc.scroll.io/l2
   https://scroll-alphanet.public.blastapi.io
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
  60

**Additional context**
Add any other context here.

**Comment by OrestTa** [comment]
Yay! :)

**Comment by OrestTa** [comment]
This was fast, thanks! Is there an ETA for the deployment, @Cali93 ?
