### ISSUE TITLE
Build fails even though project ID defined, Error: No projectId found. Every dApp must now provide a WalletConnect Cloud projectId to enable WalletConnect v2

### ISSUE THREAD

**Issue by basememara** [WalletConnect/walletconnect-monorepo#2883]
**Describe the bug**
I have a monorepo that has a root `.env` shared across all apps using `dotenv-cli`. My project ID variable is populated with an `.env` variable but only works if the `.env` is in the same location as the app's `package.json` file. Something seems to be hard coded when looking for the project ID in the `.env` file because now it can't find it when not located in the app's root directory but resides in the monorepo root directory.

**SDK Version (if relevant)**
 - Client: JS
 - Version 2.8.6

**To Reproduce**
1. Create yarn monorepo
2. Create `.env` in root directory
3. Declare project ID variable with `process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID`
4. Use wagmi or Rainbow kit to create providers
5. Use `dotenv-cli` to build project apps
6. See error: No projectId found. Every dApp must now provide a WalletConnect Cloud projectId to enable WalletConnect v2

**Expected behavior**
Build should not fail like previous versions.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 13.4.1

**Comment by yugansharora01** [comment]
Did you find any solution to this?

**Comment by basememara** [comment]
Unfortunately no, I had to put an .env file local to the project with the project id in there, even though it wasn't use for development or production (because it uses the root .env in both cases).

**Comment by glitch-txs** [comment]
This should be fixed in the latest versions, please update all packages and let us know if the issue still persists.

**Comment by Max-OSSoftware** [comment]
Still an issue, has anyone found a cure, i included a NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=************ in .env file. and the browser responds with. 
No projectId found. Every dApp must now provide a WalletConnect Cloud projectId to enable WalletConnect v2.

**Comment by johnashu** [comment]
Still an issue here as well..
