### ISSUE TITLE
How long does it take to review my project?

### ISSUE THREAD

**Issue by pctsvn** [WalletConnect/walletconnect-monorepo#2891]
### Discussed in https://github.com/orgs/WalletConnect/discussions/2890

<div type='discussions-op-text'>

<sup>Originally posted by **pctsvn** June 30, 2023</sup>
I have a live website using WalletConnect.
I have submitted review for my app.
My app is live so it's urgent for me to have my project published ASAP.
Could you please assist? 
Thanks!</div>

**Comment by chadyj** [comment]
Closing as a duplicate.
Answered in the other thread.
