### ISSUE TITLE
Ethereum provider issue with WalletConnect v2

### ISSUE THREAD

**Issue by aimxhaisse** [WalletConnect/walletconnect-monorepo#2898]
Using the latest version of the wallet connect provider (2.8.6) with no default RPC provider set, we get the following error after connecting the wallet:

```
8650-1139a77496f54fe8.js:1     POST https://rpc.walletconnect.com/v1/?chainId=eip155:1&proect_id...  net::ERR_NAME_NOT_RESOLVED
```

Seems like this was working fine yesterday; this is defined here:

https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/providers/ethereum-provider/src/constants/values.ts#L5

Looks like this endpoint is not reachable anymore.

**Comment by ganchoradkov** [comment]
https://status.walletconnect.com/

**Comment by aimxhaisse** [comment]
Makes sense, thanks!

**Comment by ironistdmi** [comment]
still no work
