### ISSUE TITLE
Adding Linea mainnet & testnet networks

### ISSUE THREAD

**Issue by Akaryatrh** [WalletConnect/walletconnect-monorepo#2900]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
ethereum-rpc compatible
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
eip155 specs
3. **namespaces**:
eip155
4. **chains**:
- **Linea mainnet:** eip155:59144
- **Linea testnet:** eip155:59140 
5. **RPC endpoints**
- **Linea mainnet:**
  - https://rpc.linea.build
  - wss://rpc.linea.build
- **Linea testnet:** eip155:59140 
  - https://rpc.goerli.linea.build
  - wss://rpc.goerli.linea.build
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
60

**Additional context**
RPC endpoints for mainnet will be available in the upcoming weeks 🙂

**Comment by Akaryatrh** [comment]
Side question, would you be ok if **WalletConnect** was listed as part of Linea's ecosystem on [linea.build](https://linea.build/) website? If so, would you have a logotype to provide?

**Comment by bkrem** [comment]
Added to https://cloud.walletconnect.com/ 👍

**Comment by bkrem** [comment]
> Side question, would you be ok if **WalletConnect** was listed as part of Linea's ecosystem on [linea.build](https://linea.build/) website? If so, would you have a logotype to provide?

cc'ing @abeyjoy and @witterswhat regarding this

**Comment by abeyjoy** [comment]
@Akaryatrh sure, we can provide the logotype. 
- can you share on which part of the linea website will this list show up? 
- which file format do you prefer for the logo?

**Comment by Akaryatrh** [comment]
> * can you share on which part of the linea website will this list show up?

This will be listed on a page presenting the Linea's ecosystem. So far the page is not published yet and its content can not be unveiled for now, really sorry!

> * which file format do you prefer for the logo?  

Well, i guess that png should do the job fine 🙂 

BTW, thanks a lot for support, that's highly appreciated 👍

**Comment by abeyjoy** [comment]
[](url)
![Lockup-black](https://github.com/WalletConnect/walletconnect-monorepo/assets/133121416/4a0303f7-ac16-4893-8242-bfe7b6e7d28a)
![Lockup-white](https://github.com/WalletConnect/walletconnect-monorepo/assets/133121416/2ff7417a-4536-4133-ac18-4bd2ade0d193)

@Akaryatrh Here you go! Logo lockup in black and white options (cant see the white one here, but it's there :) )
It would be great if you could share the page with us (when it's live) just for us to have a look at it and to do a quick check :)

**Comment by Akaryatrh** [comment]
Perfect, thx a lot! For sure we'll tell you when it will be live 👍

**Comment by bkrem** [comment]
Thanks for jumping in here @abeyjoy 🙏 

Closing this since the original chain data related issue is now resolved. Let's follow up on internal/Slack comms regarding the branding topic :)

**Comment by Akaryatrh** [comment]
FYI You guys are now listed here 🙂 https://linea.build/apps (filter by "dev tools")
