### ISSUE TITLE
[EthereumProvider] provider.connect() method resolves to a "wrong" chain ID connexion

### ISSUE THREAD

**Issue by paro-paro** [WalletConnect/walletconnect-monorepo#2905]
**Describe the bug**
Hey guys, I am having quite some trouble trying to migrate from the web3-provider to the new ethereum-provider and I am not sure If the behaviour I am experiencing is the expected behaviour or not.

So, triggering the connexion:

```
const provider = await EthereumProvider.init({
  projectId: '...',
  chains: [1], // mainnet
  optionalChains: [42220], // celo
  showQrModal: true,
  rpcMap: {
          1: `https://mainnet.infura.io/v3/${process.env.VUE_APP_PROVIDER_INFURA_ID}`,
          42220: 'https://forno.celo.org',
        }
})

await provider.connect() // same applies when using provider.enable()
  
const chain = await provider.request({ method: 'eth_chainId' })
console.log('chain', chain) // always 1 
```

The first thing that I do not understand is why you cannot pass more than one chain ID to the chains option array. You get an `'Unsupported chains.'` error if you do. 

But the main problem I am facing is that `await provider.connect()` always resolves to a provider connected to the default chain set when initialization, not a provider connected to the network of the targeted wallet. 

I have tried setting up the callbacks for the `connect` and `chainChanged` events and It behaves the same way: the callbacks are triggered logging the wrong chain ID.

```
provider.on('connect', (c) => {
   console.log('connect', c)
})

provider.on('chainChanged', (chainId) => {
   console.log('chainChanged', chainId)
})
```

If the targeted wallet is connected to, lets say, the CELO network or any other chain, both the `connect` and the `chainChanged` callbacks are triggered... but always logging mainnet (0x1) and then (after a few seconds) triggering the `chainChanged` event again (for some reason, three times) and logging the right network received from the wallet (check screenshots).
 
Is this how is supposed to work? Maybe a problem from the targeted wallet implementation? Or, of course, is just that I am not understanding something.

In any case, any help or clarification will be highly appreciate.

**Expected behavior**
I will expect to get the chain ID of the paired wallet that we are trying to connect to the dapp once the `provider.connect()` method is resolved. 

That was the behaviour from the web3-provider package making the connexion flow way more intuitive IMHO. 

**SDK Version**
"@walletconnect/ethereum-provider": "^2.8.6",
"@walletconnect/modal": "^2.5.9",

**screenshots**
Trying to connect metamask mobile wallet while connected to Celo network (first) and the Goerli network:

<img width="350" alt="Screenshot 2023-06-30 at 14 07 19" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/43136874/6c800d13-73ea-4dfb-917f-1163aa1817d1">

Thanks in advanced.

**Comment by ganchoradkov** [comment]
Hey @paro-paro 

>The first thing that I do not understand is why you cannot pass more than one chain ID to the chains option array. You get an 'Unsupported chains.' error if you do.

this is a custom behaviour of Metamask where they reject any proposal containing more than 1 required chain. With other wallets, requesting more chains should work fine given they support all of them

>If the targeted wallet is connected to, lets say, the CELO network or any other chain, both the connect and the chainChanged callbacks are triggered... but always logging mainnet (0x1) and then (after a few seconds) triggering the chainChanged event again (for some reason, three times) and logging the right network received from the wallet (check screenshots).

this is again custom behavior to MM. Their app automatically switches to the active wallet chain after the connection is established. Its done because they have a bug where they don't acknowledge any requests for a different chain than the wallet's active one. We're working with their team to resolve asap.

**Comment by gelatorema** [comment]
i am having problem with my wallet connet it does not connect to wallet sincce thee version 2 upgrade on the 28th 
below is my code:


const providerOptions = {
    walletconnect: {
      package: WalletConnectProvider,
      options: {
  
        infuraId: "80841a07db35478ea84b214a793e0abc",
        rpc: {
           56: "https://bsc.publicnode.com",
           137: "https://polygon-rpc.com/",
          },
      }
    },
  };

  web3Modal = new Web3Modal({
    network: "mainnet",
    cacheProvider: false,
    providerOptions, 
    disableInjectedProvider: true, 
  });

  console.log("Web3Modal instance is", web3Modal);
}

**Comment by gelatorema** [comment]
> Hey @paro-paro
> 
> > The first thing that I do not understand is why you cannot pass more than one chain ID to the chains option array. You get an 'Unsupported chains.' error if you do.
> 
> this is a custom behaviour of Metamask where they reject any proposal containing more than 1 required chain. With other wallets, requesting more chains should work fine given they support all of them
> 
> > If the targeted wallet is connected to, lets say, the CELO network or any other chain, both the connect and the chainChanged callbacks are triggered... but always logging mainnet (0x1) and then (after a few seconds) triggering the chainChanged event again (for some reason, three times) and logging the right network received from the wallet (check screenshots).
> 
> this is again custom behavior to MM. Their app automatically switches to the active wallet chain after the connection is established. Its done because they have a bug where they don't acknowledge any requests for a different chain than the wallet's active one. We're working with their team to resolve asap.


i am having problem with my wallet connet it does not connect to wallet sincce thee version 2 upgrade on the 28th 
below is my code:


const providerOptions = {
    walletconnect: {
      package: WalletConnectProvider,
      options: {
  
        infuraId: "80841a07db35478ea84b214a793e0abc",
        rpc: {
           56: "https://bsc.publicnode.com",
           137: "https://polygon-rpc.com/",
          },
      }
    },
  };

  web3Modal = new Web3Modal({
    network: "mainnet",
    cacheProvider: false,
    providerOptions, 
    disableInjectedProvider: true, 
  });

  console.log("Web3Modal instance is", web3Modal);
}

**Comment by paro-paro** [comment]
@ganchoradkov thanks for clarifying since Metamask behaviour was driving me nuts... All good for now!

**Comment by davidsx** [comment]
Hi, I got this issue when connecting with polygon mumbai network. 
My dapp requested to connect with polygon mumbai network while the metamask wallet active chain is polygon mainnet. 
Turns out the chain Id retrieved from metamask is mumbai but actually it is not.
When refreshing the dapp with auto connect feature implemented, the network returned correctly as mainnet.

Any updates from the mm team?
