### ISSUE TITLE
Add Arbitrum Nova and Arbitrum Goerli

### ISSUE THREAD

**Issue by chrstph-dvx** [WalletConnect/walletconnect-monorepo#2909]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
   ethereum-rpc compatible
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   eip155 specs
3. **namespaces**:
   eip155 
4. **chains**:
   Arbitrum Nova mainnet: eip155:42170
   Arbitrum Goerli Rollup Testnet: eip155:421613
5. **RPC endpoints**
   Arbitrum Nova mainnet: https://nova.arbitrum.io/rpc
   Arbitrum Goerli Rollup Testnet: https://goerli-rollup.arbitrum.io/rpc
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
   60

**Additional context**
Add any other context here.

**Comment by Cali93** [comment]
Arbitrum chains have been added to the list of options in WalletConnect Cloud.
