### ISSUE TITLE
"session_event" and "session_delete"

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/walletconnect-monorepo#2932]
**Describe the bug**
1. "session_event" does not trigger when user is connected, could we add this? or is there any event I can subscribe to when user accepts a session?

2. "session_delete" is triggered when user disconnects from wallet (tested on Trust Wallet Android) but not if disconnected from provider.disconnect function.

**SDK Version (if relevant)**
 - universal-provider

Repo: https://github.com/glitch-txs/universal-provider-modal

**Comment by ganchoradkov** [comment]
hey @glitch-txs 
>1. "session_event" does not trigger when user is connected, could we add this? or is there any event I can subscribe to when user accepts a session?

When calling `provider.connect()`, it will resolve with a `session` object that was just created.
This line https://github.com/glitch-txs/universal-provider-modal/blob/main/hooks/useConnect.tsx#L15
can be updated to
```
const session =  await provider.connect(namespaces).catch(console.error)
// user connected after the `connect` resolved
// do something with the session object
```
>2. "session_delete" is triggered when user disconnects from wallet (tested on Trust Wallet Android) but not if disconnected from provider.disconnect function.

this is intentionally done. Is there a use case that is not covered or you're unable to achieve?
