### ISSUE TITLE
WalletConnectV2 ReactNative => Authorization error: Unauthorized: origin not allowed

### ISSUE THREAD

**Issue by anietieasuquo** [WalletConnect/walletconnect-monorepo#2934]
**Describe the bug**
I integrated WalletConnect V2 with ReactNative using `WalletConnectModal` but for some reason when the app starts I see loads of WebSocket errors in the console.
`{"context": "core"} {"context": "core/relayer"} [Error: WebSocket connection closed abnormally with code: 3000 (Authorization error: Unauthorized: origin not allowed)]`.
The Allowed domains list contains my deep link as well as Metro URL.

Below his how it's used;

```
<WalletConnectModal
      projectId="<project id>"
      providerMetadata=<provider meta data>
      sessionParams=<session params>
      onCopyClipboard=<copy handler>
/>
```

Can someone provide some insight into this?

**SDK Version (if relevant)**
 - Client: ReactNative, TypeScript (@walletconnect/modal-react-native)
 - Version: 1.0.0-rc.3

**To Reproduce**
1. Integrate with `@walletconnect/modal-react-native`

**Expected behavior**
Wallet should be connected, and web socket connection should be established.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Version: 16.5.1

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 16
 - Version: 16.5.1

**Additional context**

**Comment by ganchoradkov** [comment]
Hey @anietieasuquo, do you have any `allow lists` set for your projectId? 
This error means you're trying to connect from `Unauthorized origin`.
You can check your settings from https://cloud.walletconnect.com/

**Comment by anietieasuquo** [comment]
@ganchoradkov  Yes, I'm developing a React Native app and connecting via Metro. I added the metro URL (`192.168.*.*`) to the `allow list` and also added `localhost` but still didn't work. What should be the URL to be added to the `allowed list` for a ReactNative app running on `dev` mode?

**Comment by anietieasuquo** [comment]
@ganchoradkov any ideas about this?

**Comment by anietieasuquo** [comment]
@ganchoradkov see image below.
<img width="856" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/10789251/1ccb3cfa-0f42-46f3-8ad1-65490bfcad0f">

**Comment by anietieasuquo** [comment]
What should be the `Client ID` and where should it be specified?

**Comment by anietieasuquo** [comment]
@ignaciosantise, @ganchoradkov do you have any ideas about this? I'm also having the same issue when running the example project: https://github.com/WalletConnect/react-native-examples/blob/main/dapps/v2Explorer

So my question is; for a react native app, what should be the content of the allowed domains that would authenticate the app to work?

**Comment by glitch-txs** [comment]
Do you have the same error on localhost?

 Have you tried generating a new project ID?

**Comment by anietieasuquo** [comment]
@glitch-txs Yes the issue is happening when running the app both on an iOS emulator and on an iOS device (is that what you mean by "localhost").
And yes I generated a new project ID but still no luck.
You said HTTP URLS are blocked, so what should be the allowed URL for a ReactNative app? 
How did you test the v2Explorer example app? What did you add to the allowed domains?

**Comment by glitch-txs** [comment]
I take that back, just tested [the example](https://github.com/WalletConnect/react-native-examples/tree/main) and works fine on my end. Have you tried setting a new Project ID with empty whitelisted domains?

**Comment by anietieasuquo** [comment]
@glitch-txs I just tried with empty whitelisted domains and it works, thanks a lot 👍

**Comment by SohaibMushtaq1243** [comment]
@glitch-txs can you give me a screenshot where is i should apply because I am having a same issue
