### ISSUE TITLE
Add Reef chain to the Explorer

### ISSUE THREAD

**Issue by boo-0x** [WalletConnect/walletconnect-monorepo#2954]
**Add Reef chain to the Explorer**

1. **JSON-RPC spec for Wallets**:
https://github.com/reef-chain/reef-rpc-api/tree/main#readme

2. **CASA namespace spec**:
https://github.com/ChainAgnostic/namespaces/pull/75/files

3. **namespaces**: reef

4. **chains**:
- Mainnet: `reef:7834781d38e4798d548e34ec947d19de`
- Testnet: `reef:b414a8602b2251fa538d38a932239150`

5. **RPC endpoints**
- Mainnet: https://rpc.reefscan.com
- Testnet: https://rpc-testnet.reefscan.com

6. **SLIP-0044 coin type**: 819

**Comment by bkrem** [comment]
Hi @boo-0x,

Appreciate you already have the PR open on the CASA namespaces repo, but we require that spec to be settled before we consume this namespace + chainId configuration in WalletConnect Cloud.

Feel free to ping here once the PR is merged and we'll get Reef added 🙏

**Comment by boo-0x** [comment]
Hi @bkrem

Our PR has been merged: https://github.com/ChainAgnostic/namespaces/tree/main/reef

Let me know if anything else is required.

**Comment by Cali93** [comment]
Your chain has been added in the list of options in WalletConnect Cloud.
