### ISSUE TITLE
MagicEden.io

### ISSUE THREAD

**Issue by Talhaali00** [WalletConnect/walletconnect-monorepo#2964]
**Describe the bug**
The dapp MagicEden.io is still running the v1 bridge.

**URL to page**
https://magiceden.io/

**Reported by**
Reported by the Flutter SDK developer Sterling

**Comment by crypblizz8** [comment]
Hey @TalhaAli00, they are on V2 relay, just on the old UI version. Working with them to update to a new modal shortly.!

Copied from their clipboard
```wc:bfc2fceaeaf76a8156d3029471903200b27e44a981df970e6cf1acbdb03dcd76@2?relay-protocol=irn&symKey=ed0903faaedb5b9e8606ef30c4bd61a1dddca28ab932ea6b1253f11b17ac0b3a```
