### ISSUE TITLE
WC v2 Proposal namespaces with respect of smart contract wallets

### ISSUE THREAD

**Issue by finessevanes** [WalletConnect/walletconnect-monorepo#2965]
### Discussed in https://github.com/orgs/WalletConnect/discussions/2733

<div type='discussions-op-text'>

<sup>Originally posted by **niallkh** June 23, 2023</sup>
More users currently are starting using smart contract wallets multichain, especially safe multisig. Smart contract wallet can be deployed selectively on specific chain. Current implementation of [@walletconnect/ethereum-provider](https://docs.walletconnect.com/2.0/web/providers/ethereum#initialization) doesn't respect this and sends ethereum mainnet as required network. See ` chains, // REQUIRED chain ids`. Dapp should work equally on different chains without specifying required network. Because smart contract wallet may be not deployed on required chain, but deployed on optional chains. Wallet can't continue working with dapp because it violates wallet connect protocol [2.4. Session Namespaces MUST contain at least one account in requested chains.](https://docs.walletconnect.com/2.0/specs/clients/sign/namespaces#24-session-namespaces-must-contain-at-least-one-account-in-requested-chains)

Dapp should be able to send proposal without required chains and not empty optional chains.
From dapp development perspective I think that required chains make sense in rare cases, for instance, if dapp's contracts are deployed only on one chain. When dapp works on several chains it doesn't make sense to provide them as required because wallet may be deployed only in part of them, they should be provided as optional.

According to CAIP-25 required chains are optional. [The requiredScopes array MUST contain 1 or more scopeObjects, if present.
](url)

**References:**
https://github.com/wagmi-dev/references/issues/330
https://github.com/orgs/WalletConnect/discussions/2383

**Steps to reproduce:**
1. Suppose that we have Smart Contract Wallet on polygon.
2. Open https://app.uniswap.org/
3. Choose polygon network in chain selector
4. Connect WC v2

**Expected:**
Wallet receives proposal with required polygon or with empty required chains. Wallet approves session.
**Actual:**
Wallet receives ethereum as required and polygon as optional. Wallet rejects session as it's not deployed on ethereum.

1. Open https://app.safe.global/ -> deploy wallet on gnosis
2. Use WalletConnect
3. Open https://layer3.xyz/ in other tab
4. Sign in -> WalletConnect
5. Copy WC uri -> insert in safe

**Expected:** 
Continue work with layer3, sign personal message on gnosis.
**Actual:** 
error - "Connection refused: Incompatible chain detected. Make sure the Dapp uses Gnosis Chain to interact with this Safe." </div>

**Comment by SpiritusDeos** [comment]
I have the same issue, we have a huge base of clients using wallet connect through web3-onboard, do we have any idea when it can be resolved ? (and same for the connection with Zengo ?)

**Comment by jierlich** [comment]
We're experiencing the same thing at Den as a UI built on Safe. Our workaround has been to respond to session proposals with all of our supported networks, but this is not ideal as we're now doing additional validation on our end that the request is for the correct network. We've also found that this results in some dapps sending requests for mainnet even if the contract call displayed on their UI is for a different chain.

**Comment by Sednaoui** [comment]
@SpiritusDeos @jierlich walletconnect pushed the [latest version](https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.9.0) to allow for empty chain list in the required namespace. If the dapp is using wagmi then the issue will still persist, it's wagmi's turn to bump.  Tracking here https://github.com/wagmi-dev/references/issues/330

**Comment by glitch-txs** [comment]
Been testing the update setting empty chains to ethereum-provider

https://github.com/glitch-txs/walletconnect-safe

works in this example: https://react-wallet.walletconnect.com/

it doesn't work in this example: https://react-web3wallet.vercel.app/

Tested on Android

Works in: Trust Wallet

Doesn't work in: MetaMask, Rainbow

I think this might be a solution for Safe and Smart Wallets but it breaks interoperability with other wallets

**Comment by HatimPatwa** [comment]
@finessevanes Hey there, 

Fellow developer here. Have you implemented smart accounts with walletconnect,
I am kinda stuck on the signing part of walletconnect i.e personal_sign, would like to connect with you if you have any input how to do that.
