### ISSUE TITLE
Suddenly I've got "No matching key" error

### ISSUE THREAD

**Issue by mqklin** [WalletConnect/walletconnect-monorepo#2969]
**Describe the bug**
I've got it one time, but I think it's important to report it here: `Error: No matching key. pairing: ***`

**SDK Version (if relevant)**
 "@web3modal/ethereum": "^2.4.7",
 "@web3modal/react": "^2.4.7",

**Screenshots**
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/9456433/4f900cd7-c7ad-4c9a-9b97-3978c10329de)

**Smartphone (please complete the following information):**
- Device: iPhone 12 mini
- OS: iOS 16.5.1
- App Version: 7.0.1

**Comment by Metallistener** [comment]
The same problem but with @walletconnect/web3wallet. As I understand it happens because of WC's localStorage cache but don't know how to fix this error

**Comment by Arthurgallina1** [comment]
Same here, seems related to localStorage but haven't been able to fix nor do a workaround for this.

**Comment by roadmanfong** [comment]
Same here. The error go away after I uninstall my wallet app and install again. 
Is there any better way to handle this

**Comment by wangyue168git** [comment]
same here

**Comment by glitch-txs** [comment]
This should be fixed in the latest versions, please update all packages and let us know if the issue still persists.

**Comment by GitDeluxe** [comment]
suppress cache and cookies  fix the problem for me

**Comment by shin101004** [comment]
@GitDeluxe do you mean delete all cache and cookies ?
