### ISSUE TITLE
{context: 'core/relayer'}: socket stalled  at eval

### ISSUE THREAD

**Issue by mqklin** [WalletConnect/walletconnect-monorepo#2970]
**Describe the bug**
`open` function call from `useWeb3Modal()` just caused `{context: 'core/relayer'}: socket stalled` error.

**SDK Version (if relevant)**
"@web3modal/ethereum": "^2.4.7",
"@web3modal/react": "^2.4.7",

**To Reproduce**

**Smartphone (please complete the following information):**
- Device: iPhone 12 mini
- OS: iOS 16.5.1
- App Version: 7.0.1 (MetaMask)
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/9456433/33549157-c6fd-4e21-b8a8-3c87a098ce50)

**Comment by ganchoradkov** [comment]
Hey @mqklin this error means the client can't establish a connection with the relay. 
Are you using some VPN or proxy that might be causing this?

**Comment by mqklin** [comment]
Hey @ganchoradkov 
no I don't. 
I just tested WC2 the whole day today, and got this error 2 times.

**Comment by ric344** [comment]
{"context": "core"} {"context": "core/relayer"} [Error: WebSocket connection failed for URL: wss://relay.walletconnect.com?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtpajZ5WE1IYzdaSnhWdjd1QW5ENzdWb3Myc1ZDaUc2M05EM1d3Y29iZXptWiIsInN1YiI6ImI2ZmE2OWRiMzM1OGY5OGE2Y2VlZjdiYzlkNGU2NGI2OWI1MjBhZDE0NTZjMzQwOGNjMWJmM2NjNjNjMGNmOGIiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTY4ODUwNjc4OSwiZXhwIjoxNjg4NTkzMTg5fQ.BvTRkiCVmeyi-HBs5ufdAA4NS4bF0B-ahg4jQaF53x8ermz69IjiHVNuAgkFJYSU2UL_hXeGX4e8NV4nb-8cBQ&projectId=761c84c077c0d977b8f4e20fbd4eae64&ua=wc-2%2Fjs-y%2Funknown-%2Freact-native&useOnCloseEvent=true]

**Comment by roman-utila** [comment]
I've started receiving this error a few days ago, after updating to the lates wallet connect versions, same error: `Error: Socket stalled when trying to connect to wss://relay.walletconnect.org`.

Any way to go around this?

**Comment by kdenhartog** [comment]
I believe this can be closed now that #3230 is merged
