### ISSUE TITLE
After successfull Txn not able to send back request to the Dapp

### ISSUE THREAD

**Issue by ric344** [WalletConnect/walletconnect-monorepo#2973]
**Describe the bug**
I have integrated walletconnect V2 in my wallet and able to establish a connection between Dapp and Wallet. 
I am using https://react-app.walletconnect.com/ this as a reference for connecting wallet. After doing eth_sendTransaction not able to get the return response on Dapp side. 
Getting this error in responsSessionRequest: {"context": "client"} Missing or invalid. respond() response: undefined
 ERROR  {"context": "core"} Missing or invalid. respond() response: undefined

**SDK Version (if relevant)**
     "@walletconnect/core": "^2.4.9",
    "@walletconnect/jsonrpc-types": "^1.0.3",
    "@walletconnect/react-native-compat": "^2.8.2",
    "@walletconnect/web3wallet": "^1.8.2",
    "@web3auth/core": "4.0.0",

**To Reproduce**
```
const transactionResponse = await walletSigner.sendTransaction(
              requestParamsMessage3,
              {
                gasLimit,
                maxFeePerGas: maxFeePerGas,
                maxPriorityFeePerGas: maxPriorityFeePerGas,
              },
            );
            await transactionResponse.wait();
            console.log('transactionResponse:', transactionResponse);
            const response_3 = {
              id,
              result: transactionResponse,
              jsonrpc: '2.0',
            };
            console.log('topic', topic);
            console.log('response_3', response_3);

            // respond to the dapp request with the response and topic
            **const res3 = await web3wallet.respondSessionRequest({
              topic,
              response_3,
            });**
            // Above is not triggered

```
**Expected behavior**
Transaction is successfull and I got Txn hash but it is not refelcted on Dapp side

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ganchoradkov** [comment]
Hey @ric344 this seems to be caused by `response` param not being set as indicated by the error message
```
            **const res3 = await web3wallet.respondSessionRequest({
              topic,
              response_3, -> this should be replaced with `response: response_3`
            });**
```

**Comment by blockchain5992** [comment]
But I am able to get response: 
**response_3 {"id": 1688546119206292, "jsonrpc": "2.0", "result": "0x663d455c217e77609f59155c3c674c635ba6f29679fea0e558dbb4ceb375a6eb"}**
