### ISSUE TITLE
Add Oasys chain

### ISSUE THREAD

**Issue by tak1827** [WalletConnect/walletconnect-monorepo#2976]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
ethereum-rpc compatible
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
  eip155 specs
3. **namespaces**:
eip155
4. **chains**:
Oasys Mainnet: eip155: 248
Oasys Testnet: eip155: 9372
5. **RPC endpoints**
Oasys Mainnet: https://rpc.mainnet.oasys.games
Oasys Testnet: https://rpc.testnet.oasys.games
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
685: 0x800002ad

**Additional context**
Technical Document: https://docs.oasys.games/docs/staking/rpc-endpoint/1-1-rpc-endpoint

**Comment by bkrem** [comment]
Added to https://cloud.walletconnect.com 👍
