### ISSUE TITLE
"No matching key. session:" error appears in devtools console

### ISSUE THREAD

**Issue by Metallistener** [WalletConnect/walletconnect-monorepo#2983]
When I try to create or disconnect session via web3wallet then I get error like **"Error: No matching key. session: ecc7d1a335b0219ddc2499789e938843c1c76e56514197c5393bf924dcee6485"**. As I undestand it has something to do with WC's localStorage cache but still don't know how to fix this error. Is it bug or just something wrong on my side?

<img width="599" alt="Снимок экрана 2023-07-04 в 17 09 10" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/33493261/31e0dd50-8c28-4957-ab0d-6499c618b980">

 **"@walletconnect/utils": "^2.8.6",
 "@walletconnect/web3wallet": "^1.8.5",**

**Comment by BitHighlander** [comment]
+1 I see this a lot too but doesn't seem to affect my sessions

**Comment by ylmin** [comment]
+1

**Comment by afcharliekong** [comment]
Posted this issue on the discussion, haven't got a reply from the team. 

https://github.com/orgs/WalletConnect/discussions/2682

This also happens after a transaction goes through for the first time and if I were to reload the page and attempt to transact again.

**Comment by Metallistener** [comment]
This errors appear on wallet side as well as on dApp side, so I think that there is a problem on WC 2.0 side

**Comment by ganchoradkov** [comment]
Hey @Metallistener, could you share a small repo where we can reproduce the error?

**Comment by arkwinta** [comment]
We're also intermittently seeing this issue in one of our remote environments (haven't seen locally yet). It does result in about 1000 console errors and is drastically impacting the performance of the site. Not tied to any action as far as we're aware, but the same `{context: 'core/expirer'}context: "core/expirer" 'No matching key. expirer: id:1688664079540455'`  
Does appear intermittently, upon refresh sometimes it has the errors, sometimes no console errors

**Comment by Metallistener** [comment]
> 

Hi, yes I've prepared test code on playground for you.
https://codesandbox.io/embed/competent-hamilton-x87557?fontsize=14&hidenavigation=1&theme=dark
You can test connecting wallet to dApp using https://pancakeswap.finance/?chain=goerli.
I want to warn you that errors do not always appear so you may need many attempts to catch error 

**Example of catched errors on playground:**
<img width="1728" alt="Снимок экрана 2023-07-13 в 12 52 09" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/33493261/c19c5b1e-1165-4c32-8112-269ea7cd84d4">

**@walletconnect/utils: 2.9.0
@walletconnect/web3wallet: 1.8.6**

**Comment by mqklin** [comment]
+1: +1: `{context: 'core'} {context: 'core/expirer'} 'No matching key. expirer: topic:5394b64a82e83fba31731fb270c5c251aa9c993cc46d875e4a8fa60470b18a9b'`

**Comment by amiryadid-fb** [comment]
Experiencing the same (I see it happening on a lot of objects, including session, proposal, expirer and also history)
i.e: `No matching key. history: 1689247562130838`

**Comment by Metallistener** [comment]
> Experiencing the same (I see it happening on a lot of objects, including session, proposal, expirer and also history) i.e: `No matching key. history: 1689247562130838`

Can you show your code? May be I can help you how to fix this problem.

**Comment by amiryadid-fb** [comment]
> > Experiencing the same (I see it happening on a lot of objects, including session, proposal, expirer and also history) i.e: `No matching key. history: 1689247562130838`
> 
> Can you show your code? May be I can help you how to fix this problem.

Nothing fancy, it happens upon calling `Web3Wallet.disconnectSession({ topic, reason })`

Did you managed to fix it on your end?

**Comment by Metallistener** [comment]
> > > Experiencing the same (I see it happening on a lot of objects, including session, proposal, expirer and also history) i.e: `No matching key. history: 1689247562130838`
> > 
> > 
> > Can you show your code? May be I can help you how to fix this problem.
> 
> Nothing fancy, it happens upon calling `Web3Wallet.disconnectSession({ topic, reason })`
> 
> Did you managed to fix it on your end?

Yeah, after some refactoring my code these errors disappeared.
Can you show your full code where you initialized Core and Web3Wallet constructors?

**Comment by amiryadid-fb** [comment]
>  Yeah, after some refactoring my code these errors dissapeared

Could you detail further on what did you refactor / change that managed to avoid the problem?
Or what bad practices were there before in your code that we might've practiced over at our end?

**Comment by Metallistener** [comment]
> > Yeah, after some refactoring my code these errors dissapeared
> 
> Could you detail further on what did you refactor / change that managed to avoid the problem? Or what bad practices were there before in your code that we might've practiced over at our end?

In my case I tried to initialized Web3Wallet and SignClient at the same time and my Core was initialized out of Web3Wallet scope. I just moved Core inside Web3Wallet scope and removed SignClient, just leave Web3Wallet. So after that errors disappeared. I am not sure that this was a reason of errors but as I see this changes fixed this problem.

```
const initWeb3WalletFx = createEffect(async () => {
  const core = new Core({
    projectId: '*********************',
  });
  return await Web3Wallet.init({
    core,
    metadata: {
      name: '*****',
      description: '***************',
      url: '',
      icons: [],
    },
  });
});
```
**"@walletconnect/utils": "2.9.0",
"@walletconnect/web3wallet": "1.8.6",**

**Comment by afcharliekong** [comment]
I tried initialising the `Core` within `Web3Wallet` like so, but I'm still facing the same issue.

```
createWeb3Wallet = async () => {
    this.web3wallet = await Web3Wallet.init({
      core: new Core({
        projectId: DEFAULT_PROJECT_ID,
        relayUrl: DEFAULT_RELAY_URL,
      }),
      metadata: DEFAULT_APP_METADATA,
    });

    if (this.web3wallet === undefined) {
      throw new Error("Failed to init Web3Wallet");
    }

    // init listeners
    this.web3wallet.on("session_proposal", this.evtOnSessionProposal);
    this.web3wallet.on("session_request", this.evtOnSessionRequest);
    this.web3wallet.on("session_delete", this.evtOnSessionDelete);
  };
```

**Comment by TimDaub** [comment]
I think whatever it causes, walletconnect should not throw this error https://github.com/WalletConnect/walletconnect-monorepo/blob/0d9f4f3256daf89c02eb2b4c6b34c7b2637d9415/packages/core/src/controllers/history.ts#L160 all the way through to the user for handling. It is clearly an error emitted from a private function and so it should be caught and handled internally

**Comment by afcharliekong** [comment]
Seems like this PR is supposed to solve the issue? 

https://github.com/WalletConnect/walletconnect-monorepo/pull/3137

**Comment by SamerZen** [comment]
+ Having the same issue when trying to initiate an action from the connected dapp (such as personal_sign) . 
I got the same error and the same "session key" from multiple different dapps. 
Could it be related to core storage ?

**Comment by ganchoradkov** [comment]
Given that @Metallistener has resolved his issue, I'm going to go ahead and close this one.
FYI, we're patching most of the `No matching key.` errors and if you encounter any errors/behavior that blocks the client from operating normally feel free to open a new issue 💯

**Comment by mqklin** [comment]
@ganchoradkov what do you mean by "patching most of"? Does it mean we should ignore that error?

**Comment by ganchoradkov** [comment]
@mqklin some error cases are valid and should be taken into account e.g. when you try to ping or send a request to `non-existent-topic`, you will still get `no matching key. session: non-existent-topic`. 
I was referring to the internal async errors that you have no direct control over capturing/handling

**Comment by kantorcodes** [comment]
Noting that this is still very much relevant - are there any known fixes?
