### ISSUE TITLE
METAMASK AND TRUST WALLET NOT CONNECTING TO MY DAPP

### ISSUE THREAD

**Issue by gelatorema** [WalletConnect/walletconnect-monorepo#2987]
i am having problem with my wallet connet it does not connect to wallet since the version 2 upgrade on the 28th 
below is my code:

const providerOptions = {
    walletconnect: {
      package: WalletConnectProvider,
      options: {
  
        infuraId: "80841a07db35478ea84b214a793e0abc",
        rpc: {
           56: "https://bsc.publicnode.com",
           137: "https://polygon-rpc.com/",
          },
      }
    },
  };

  web3Modal = new Web3Modal({
    network: "mainnet",
    cacheProvider: false,
    providerOptions, 
    disableInjectedProvider: true, 
  });

  console.log("Web3Modal instance is", web3Modal);
}

**Comment by boidushya** [comment]
Could you mention the version of Web3Modal you're using? If you're on WalletConnect v1, we have [shut down v1](https://medium.com/walletconnect/walletconnect-v1-0-has-now-been-shut-down-ff9baec96690) in favor of v2.
Here's the [migration docs](https://docs.walletconnect.com/2.0/advanced/migration-from-v1.x/dapps/)

**Comment by gelatorema** [comment]
I tried to use the documentation but it is not working when i input it in my code

**Comment by gelatorema** [comment]
i am on wallet connect version 1 standalone

**Comment by King7474** [comment]
they should let v1 keep working ad let v2 optional 
i have tried a lot of time to upgrade to v2 but its critical
