### ISSUE TITLE
"Octal literal in strict mode" error from qrcode-terminal module

### ISSUE THREAD

**Issue by everettwho** [WalletConnect/walletconnect-monorepo#299]
Hi there,

We're upgrading from `@walletconnect/web3-provider@^1.0.0-beta.65` to the latest `1.0.8` and are now seeing this error on our builds: 

In `./node_modules/qrcode-terminal/lib/main.js`:
![image](https://user-images.githubusercontent.com/6676379/85332238-7041c100-b48c-11ea-96da-64185bb993c8.png)

It looks like `qrcode-terminal` was added in this commit 2 months ago to allow QR codes to be generated in the terminal through node: https://github.com/WalletConnect/walletconnect-monorepo/commit/9fe9771710463573421e53b97617982c18231919. 

I'm wondering why this addition was necessary into the `qrcode-modal` package and if it makes sense to remove it. A quick change in the `qrcode-terminal` library to update the `0` escape to `0o` would also fix this problem.

Either way, looking for the solution here as we'd love to be able to upgrade. Thanks!

**Comment by pedrouid** [comment]
Great catch! That `qrcode-terminal` package looks unmaintained for a couple of years so it makes sense tor replace it. Just found that `qrcode` package could serve both browser and nodejs environment thus replacing both `qrcode-terminal` and `qr-image`

**Comment by everettwho** [comment]
Fantastic, please let me know whenever those changes are made so we can upgrade!

**Comment by pedrouid** [comment]
Hey @everettwho, just published 1.0.9 with the new `qrcode` libraries. Could you test it again?

**Comment by pedrouid** [comment]
Fixed on 1.0.9
