### ISSUE TITLE
Add BitciChain Mainnet and Testnet

### ISSUE THREAD

**Issue by emrbli** [WalletConnect/walletconnect-monorepo#3006]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
   ethereum-rpc compatible
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   eip155 specs
3. **namespaces**:
      eip155
4. **chains**:
   BITCI Main Network: eip155:1907
   BITCI Test Network: eip155:1908
5. **RPC endpoints**
   BITCI Main Network: https://rpc.bitci.com
   BITCI Test Network: https://testnet.bitcichain.com
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
   60

**Additional context**
Website: https://www.bitcichain.com/en

**Comment by bkrem** [comment]
Added to https://cloud.walletconnect.com 👍
