### ISSUE TITLE
SIgnClient.update does not working 

### ISSUE THREAD

**Issue by kyuuuK** [WalletConnect/walletconnect-monorepo#3013]
Hello everyone,
Thank you for creating such an awesome library.
I'm reaching out because I encountered an error while developing a Dapp that connects to walletConnect v2 and uses Client.sessionUpdate. The error message I received is as follows:

`{context: 'client'} 'Cannot convert undefined or null to object`

Here is the code snippet where the error occurs:

```
import SignClient from "@walletconnect/sign-client";
import { SessionTypes } from "@walletconnect/types";

export interface UpdateSessionRequest {
  client: SignClient;
  session: SessionTypes.Struct;
}

export const updateSession = async (props: UpdateSessionRequest) => {

  const { client, session } = props;
  
  const newNamespace = {
    eip155: {
      accounts: [
        "eip155:5:0xa5762B96134C0a2978a1D560025b361042188837",
        "eip155:137:0xa5762B96134C0a2978a1D560025b361042188837",
      ],
      methods: [
        "eth_sendTransaction",
        "eth_signTransaction",
        "eth_sign",
        "personal_sign",
        "eth_signTypedData",
      ],
      events: ["chainChanged", "accountsChanged"],
    },
  };
  await client.update({ topic: session.topic, namespaces: newNamespace })
};

```

I referred to the following 
`https://docs.walletconnect.com/2.0/specs/clients/sign/session-events#session_update`
while writing this code. 
If I'm using it incorrectly, please let me know. Thank you.

**Comment by ganchoradkov** [comment]
Hey @kyuuuK, in your code snippet, everything looks normal.
Could you share please a small reproducible demo?

Also, we have a variety of tests regarding `session update` you can reference
https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/sign-client/test/sdk/client.spec.ts#L246

**Comment by kyuuuK** [comment]
@ganchoradkov 

Thank you for your response.
Here is the GitHub link to the demo code I created.

https://github.com/kyuuuK/wcdemo.git

The test scenario is as follows:

1. Click the connectWC - eth button to complete walletConnect.
2. Click the connectWC - pol button to perform sessionUpdate.

**Comment by glitch-txs** [comment]
hey have you check cleaning up localStorage? I'm also unable to run your project 🤔
