### ISSUE TITLE
Add Flare Testnet Coston2

### ISSUE THREAD

**Issue by jO-Osko** [WalletConnect/walletconnect-monorepo#3019]
I would like to propose a new chain to be added

`Coston2` is the testnet for `Flare` chain.
The specifications are practically the same as for Flare, Songbird and Coston (testnet for Songbird).

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
   No custom spec, we reuse the Ethereum RPC.
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
  None
3. **namespaces**:
   eip:155
4. **chains**:
   Flare Testnet Coston2: eip155:114
5. **RPC endpoints**
   https://coston2-api.flare.network/ext/C/rpc
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
   60

**Additional context**
```
{
    name: "Flare Testnet Coston2",
    shortName: "Coston2",
    chain: "C2FLR",
    rpcUrls: ["https://coston2-api.flare.network/ext/C/rpc"],
    blockExplorerUrls: ["https://coston2-explorer.flare.network"],
    nativeCurrency: {
      name: "Coston2 Spark",
      symbol: "C2FLR",
      decimals: 18,
    },
    chainId: 114,
    networkId: 114,
  },
``` 

Coston (testnet for Songbird) is already available and listed as `Flare Testnet Coston`.

**Comment by bkrem** [comment]
Added to https://cloud.walletconnect.com 👍
