### ISSUE TITLE
No wagmi config found. Ensure you have set up a config

### ISSUE THREAD

**Issue by francesco-gaglione** [WalletConnect/walletconnect-monorepo#3025]
### Discussed in https://github.com/orgs/WalletConnect/discussions/3014

<div type='discussions-op-text'>

<sup>Originally posted by **francesco-gaglione** July  6, 2023</sup>
Hi all,
I'm opening this discussion since I tried a lot of solutions but at this point, I think there is something strange in the libraries. Let me explain. 

Probably my case is an edge case but... I have a turborepo monorepo that includes a next.js v13 app and a custom react components library. I'm trying to create a sort of WalletConnect wrapper and this should be easy, just create a wrapper component. I did it and it works into the monorepo using the wagmi version 1.3.3. 

Then I published the react library (private repo) installed in a strach next.js app and this works, installed again into a new next.js app does not work. 

In the meanwhile, some other releases of wagmi were done and I really need that fix for some known issue but changing the wagmi version to >=1.3.4 errors happened into the monorepo too.

The error were 2:
* wagmi does not accept the w3mconnector anymore
* no wagmi config found

I tried to:
* @ts-ignore on config error
* disable SSR in the _app.ts file of next.js
* useMemo()
* react Context
* try to use a custom singleton instead of useMemo or react Context

With these solutions, something changed:

* of course the ts-ignore pass the library build but don't know if it would work and I can't solve it since it is wagmi/walletconnect libraries problem (so please consider to open a priority issue)
* disabling SSR no wagmi config error disappear in compilation time but still present at runtime
* using useMemo, Context and Singleton (I did it because I noticed that the wrapper were initialized more time, and it is strange) but even if the config doesn't change the error is still there

I cannot share the original repo for reproduction, but, I replicated the issue in a new repo with the original status, so no SSR disable, no memo and no Singleton.

Here the repo: https://github.com/francesco-gaglione/replicate

Please can you help to understand what is happening? I think there is something borderline to be solved in the libraries. (the config issue of course, but something else too)
</div>

**Comment by j5h46bd** [comment]
I'm having a similar issue, absolutely broken

**Comment by j5h46bd** [comment]
In my case, I downgraded to:
    "viem": "1.0.0",
    "wagmi": "1.3.2",
this is enough to at least connect and use account, but several other modules are broken. For example, if I try to switch network by including useSwitchNetwork from "wagmi", as soon as my app attempts to declare const { switchNetwork } = useSwitchNetwork(), the app is broken and all I get is the error message `useConfig` must be used within `WagmiConfig`

**Comment by glitch-txs** [comment]
Please update al dependencies to their latest version including wagmi and viem. Closing for now, please reopen if you're still facing this issue.

**Comment by Iamknownasfesal** [comment]
> Please update al dependencies to their latest version including wagmi and viem. Closing for now, please reopen if you're still facing this issue.

I am using latest version of wagmi, while trying to use getWalletClient, i get No wagmi config found, i wrap all my application in with WagmiConfig(obv creating a config before too)

**Comment by glitch-txs** [comment]
@Iamknownasfesal could you provide a [MRE](https://github.com/orgs/WalletConnect/discussions/3457)?

**Comment by Iamknownasfesal** [comment]
> 
Removing cache from localStorage and removing node_modules worked for me.

**Comment by deww400** [comment]
I am having the same issue. I am using Turborepo and the packages (components that are imported with workspaces) are unable to read from the wagmi config provider that wraps the main app (despite being able to read all the other providers). Any solution yet?

**Comment by brian-backend** [comment]
When I use useContractWrite, encountered same issue.
Current version wagmi 1.3.9 viem: 1.4.1
I wrapped all my application with wagmi config.

**Comment by ganchoradkov** [comment]
hey guys, please open a new issue & provide a small repo example where we could reproduce the bug

**Comment by kizzx2** [comment]
No offense but are those bot generated responses that tell people to open an MRE? @francesco-gaglione specifically did the whole thing in the first message (disclaimer: I did not try to run the MRE but if there are issues with it, shouldn't the specifics be at least mentioned?)

**Comment by glitch-txs** [comment]
@kizzx2 OP repo is not up to date in term of versions + a MRE means something that's minimal and we can easily run to spot the issue. Moreover, this issue is fixed by updating dependencies.
