### ISSUE TITLE
Callback was already called error when using web3-provider

### ISSUE THREAD

**Issue by dmytrobaida** [WalletConnect/walletconnect-monorepo#303]
Hi all.
I have an error when using walletconnect web3 provider of `1.0.11` version.
After successful connection I can't sign transaction.

I'm using it this way

`import WalletConnect from "@walletconnect/web3-provider";`
`this._provider = new WalletConnect({
                chainId: 4,
                rpc: {
                    4: RPC_URL,
                },
                qrcode: false,
            });`
`this._provider.enable();`
`this._web3 = new Web3(this._provider);`
`const rawTransaction = await this._web3.eth.signTransaction(transaction); // Error occurs here`

And I have this kind of error
`
Uncaught (in promise) Error: Callback was already called.
    at onlyOnce.js:9
    at hooked-wallet.js:491
    at hooked-wallet.js:556
    at WalletConnectProvider._callee$ (index.ts:84)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at fulfilled (tslib.es6.js:68)
`

Do you know what is the problem or I'm doing something wrong? Previously I used `1.0.0-beta.46` version and everything was fine

**Comment by dmytrobaida** [comment]
@pedrouid I'm using it together with Razzle. Maybe it's somehow related to typescript runtime?

**Comment by pedrouid** [comment]
Most wallets dont support eth_signTransaction unfortunately... I would recommend using eth_sendTransaction instead

**Comment by santiac89** [comment]
@dmytrobaida have you solved this issue somehow? Or the answer is that we can simply not do it? I'm having the same issue.

**Comment by AlfieDarko** [comment]
Has anyone resolved this issue yet?

**Comment by finessevanes** [comment]
Hey @dmytrobaida, @santiac89, @AlfieDarko are you still experiecing this issue or did using `eth_sendTransaction` solve your issue?
