### ISSUE TITLE
eth_chainId returns incorrect chain immediately after enable (on MetaMask mobile)

### ISSUE THREAD

**Issue by payton** [WalletConnect/walletconnect-monorepo#3031]
**Describe the bug**

Setup:
* The EthereumProvider is initialized with `chains: [1]` and `optionalChains` to include Goerli.
* MetaMask on mobile (iOS or Android) is set to Goerli.

Immediately after calling `EthereumProvider.enable()`, I send an `eth_chainId` request, which resolves to `1`. It should be `5`. Shortly after, a `chainChanged` event is received that updates the chain to `5` (goerli).

The problem is that the first `eth_chainId` request is incorrect.

**SDK Version (if relevant)**
 - Client: @walletconnect/ethereum-provider
 - Version: 2.8.6

**To Reproduce**
1. In MetaMask mobile, change the chain to non-Ethereum
2. Start a new Wallet Connect session via QR code
3. Immediately call `eth_chainId`

**Expected behavior**
The first call to `eth_chainId` will be `5` to reflect MetaMask's chain state.

**Desktop (please complete the following information):**
 - OS: macOs Monterey
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone 12 and Pixel 6
 - OS: iOS and Android
 - Browser: MetaMask mobile
 - Version: 7

**Additional context**
I'm reporting this here because I am unsure if this is a MetaMask bug or if this is a bug with how WalletConnect is optimistically inferring `eth_chainId` after enabling a provider.

**Comment by ganchoradkov** [comment]
Hey, this happens because your MM wallet is a different active chain than the required one in the session proposal. 
The session must be settled first before updating to the active chain thus the delay in switching. We're still ironing out this behavior with MM's team.
One way to solve it would be to switch your wallet active chain to the intended network you wish to use.

**Comment by payton** [comment]
Thanks @ganchoradkov! Correct me if I'm wrong, but given that there is no way to know what chain the end wallet app is on, that method does not seem like a valid approach.

> The session must be settled first before updating to the active chain thus the delay in switching

Why does Wallet Connect return the incorrect chain instead of raising an error or hanging?
