### ISSUE TITLE
Add Mantle L2 Network

### ISSUE THREAD

**Issue by ericvanderwal** [WalletConnect/walletconnect-monorepo#3056]
Request for support for Wallet Connect V1 & V2 ~

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
ethereum-rpc compatible

2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
eip155 specs

3. **namespaces**:
eip:155

4. **chains**:
Mantle Mainnet
ChainID: eip155:5000
Mantle Testnet
ChainID: eip155:5001

5. **RPC endpoints**
Mantle Mainnet
https://rpc.mantle.xyz/
Mantle Testnet
https://rpc.testnet.mantle.xyz/

6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
60

**Additional context**
LFG !

**Comment by looter** [comment]
@bkrem fyi was notified that the Mantle L2 network will be going to mainnet in 7 days and wanted to make sure they were good on that end.

**Comment by bkrem** [comment]
@looter LGTM, doing a batch of new chain requests before EOD including this one 👍

**Comment by bkrem** [comment]
Rolled out on staging. Will go live on https://cloud.walletconnect.com EU morning tomorrow

**Comment by bkrem** [comment]
Added to https://cloud.walletconnect.com 👍
