### ISSUE TITLE
Can't receive session request in Vite

### ISSUE THREAD

**Issue by liam-safulet** [WalletConnect/walletconnect-monorepo#3064]
**Describe the bug**
In project created by Vite, after pair, no session requests received, online example:
https://stackblitz.com/edit/vitejs-vite-auyeaq?file=src%2FApp.tsx&terminal=dev

This only happens in Vite dev mode, but works fine in production mode

**SDK Version (if relevant)**
 - Client: JS
 - Version 1.8.6

**To Reproduce**
1. Pair wallet connect uri
2. Nothing happens

**Expected behavior**
'session_proposal' should be received after paring

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few weeks.

Please reopen if you still encounter this issue in the latest version :)

**Comment by liam-safulet** [comment]
please open it as this issue still exists

**Comment by indytheoracle** [comment]
bumping this thread and linking another thread that is ultimately the same issue [link](https://github.com/orgs/WalletConnect/discussions/3711)

**Comment by indytheoracle** [comment]
got it working at https://github.com/indytheoracle/vite-template-react-walletconnect
