### ISSUE TITLE
Our QA team and sentry summarize the issues that occur while using walletconnect

### ISSUE THREAD

**Issue by siosio34** [WalletConnect/walletconnect-monorepo#3065]
**Describe the bug**
Our QA team and sentry summarize the issues that occur while using walletconnect.

1. switchChain does not work properly in mobile browser using walletconnect. Similar issues include:
https://github.com/MetaMask/metamask-mobile/issues/6655
https://github.com/wagmi-dev/references/issues/393

2. To use QR modal, please install @walletconnect/modal package 
-The QR module appears properly, but the error seems to occur intermittently.
- As a result of tracking through sentry, it mostly occurred in IOS 16 or higher.

3. Attempt to connect to relay via `transportOpen` has stalled. Retrying...
- The error below occurs intermittently and gets caught by the sentry, and I don't know when or why it happens.

4. WebSocket connection failed for URL
- The error below occurs intermittently and gets caught by the sentry, and I don't know when or why it happens.

**SDK Version (if relevant)**
 - Client: JS, metamask
 - Version
walletconnect - 2.8.4
wagmi - 1.3.2
viem - 1.0.0

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zhy023** [comment]
The same problem happened to me...

**Comment by imaksp** [comment]
Is this metamask app issue or walletconnect?

**Comment by siosio34** [comment]
@imaksp 
I'm not sure exactly what the problem is.

However, it does not happen in the Metamask Chrome extension extension, and it seems that the bugs occur when connecting Metamask Mobile through Wallet Connect.

**Comment by N3ST3DLabs** [comment]
having the same problem with Metamask on chrome and brave ....... Viem has been a nightmare upgrade .........Even bugs in   usereadContract Allowance function returns ON instead of a UINT256 .  :(  i guess moving back to old version with ether is much better

**Comment by frankye23** [comment]
> 3. Attempt to connect to relay via transportOpen has stalled. Retrying...

I also run into this error. In my case, in order to reproduce, i have to send multiple request to my own api. And the error randomly show in developer console. But i wonder why axios request will be stalled by wc socket stalled.

**Comment by kdenhartog** [comment]
I believe this can be closed now that #3230 has been merged

**Comment by glitch-txs** [comment]
1. These are MetaMask related issues. They are being worked on atm.
2. So far I've seen this issue and was related to code implementation. The error message seems off though.

For the rest please provide a minimal reproducible example of each issue so we can track them individually. I think we could do it on separated issues for better organization.

Thanks a lot for sharing this QA 🙏

Closing for now, feel free to reopen if you find it necessary 👍

**Comment by imaksp** [comment]
MM 7.4 is released with switch chain fix so this needs retesting.
