### ISSUE TITLE
Signing Transaction not creating request in client

### ISSUE THREAD

**Issue by saitejach127** [WalletConnect/walletconnect-monorepo#307]
The signing of Transaction is not creating confirm or reject request in the mobile client.
Sign in using QR code is working
We are using quorum as our RPC. and using Metamask app as our Walletconnect Client
Initialising of connector works but signing doesnt work
Whereas in send transaction it creates an unknown error of Error : [object Object]

All information with code can be found at this gist
https://gist.github.com/saitejach127/9794f4d3622bd65bd9d14f14ba1a93ff

**Comment by pedrouid** [comment]
Looking at your gist, it looks like you are using a deprecated version of the client.

You should be using the new client with the latest version published on NPM, for more instructions please follow the quick start for the standalone cline on our documentation

https://docs.walletconnect.org/quick-start/dapps/client

**Comment by pedrouid** [comment]
Here is more informations about the migration between `@walletconnect/node` and `@walletconnect/client` 

https://docs.walletconnect.org/legacy-clients#migrating-from-nodejs-client

**Comment by saitejach127** [comment]
We have tried using newer client with 
` "@walletconnect/browser": "^1.0.0-beta.47",
    "@walletconnect/client": "^1.0.11",
    "@walletconnect/node": "^1.0.0",
 `
We tried using all these versions but are facing the same problem 

We tried using our own bridge server but no use using that too

**Comment by finessevanes** [comment]
Hey @saitejach127, are you still have this issue?
