### ISSUE TITLE
Snapshot <> Ambire connection: doesn't open wallet in a new tab, can't receive signed message response

### ISSUE THREAD

**Issue by Ivshti** [WalletConnect/walletconnect-monorepo#3072]
**Describe the bug**
When connecting wallet.ambire.com to https://snapshot.org/

**To Reproduce**
1. Go to snapshot in a new tab: snapshot.org
2. In Snapshot, chose Desktop and connect to Ambire; so far, so good - Ambire is open in a new tab and is connected
3. In snapshot, try to vote for a proposal to sign a message; upon clicking Sign, you're redirected to ambire but in the same tab
4. now, when you sign on ambire, it's signed successfully and sent to walletconnect but snapshot can't receive it
5. opening snapshot back or going back to it doesn't help because the dapp is not expecting the signed message

**NOTE:** the easiest way to create an ambire account is to open wallet.ambire.com and connect it to metamask beforehand; a new ambire account authorized by your metamask will be created

**Expected behavior**
Open Ambire in a new tab so snapshot can await and receive the message

**Desktop:**
- OS: any
- browser: any

**Additional context**
N/A

**Comment by Ivshti** [comment]
here's a related (identical?) issue https://github.com/WalletConnect/walletconnect-monorepo/issues/2303 and the PR that's fixing it https://github.com/WalletConnect/walletconnect-monorepo/pull/2869

**Comment by arein** [comment]
Can you reproduce this on the [lab.web3modal.com](https://lab.web3modal.com/with-wagmi/react) dapp ?

**Comment by arein** [comment]
This works with our sample wallet on https://react-wallet.walletconnect.com/ just fine. This means this is an Ambire wallet issue.

This should help you when resolving this issue.

I suggest you try to further narrow down for instance:
1. Can you sign messages on https://lab.web3modal.com/with-wagmi/react - if not it's easier for us to help guide what's broken on your end

**Comment by Ivshti** [comment]
> Can you reproduce this on the [lab.web3modal.com](https://lab.web3modal.com/with-wagmi/react) dapp ?

yes, the same thing happens unfortunately

**Comment by Ivshti** [comment]
@arein any chance the sample wallet has a deep link? the issue appears for wallets which don't have a deep link

**Comment by arein** [comment]
> @arein any chance the sample wallet has a deep link? the issue appears for wallets which don't have a deep link

The code is open source. Please familiarize yourself with it: https://github.com/WalletConnect/web3modal

**Comment by Ivshti** [comment]
@arein Ambire works just fine with Uniswap, so this leads me to believe that the sample dapp hasn't deployed this fix yet https://github.com/WalletConnect/walletconnect-monorepo/pull/2869/files

can you verify if the sample dapp has implemented that fix?

**Comment by Ivshti** [comment]
- sample dapp works following this workaround: `delete localStorage.WALLETCONNECT_DEEPLINK_CHOICE`
![Screenshot 2023-07-10 at 12-43-16 https __lab web3modal com](https://github.com/WalletConnect/walletconnect-monorepo/assets/1247629/0fdee5c6-6f27-4ebc-b700-ccb0892d8221)
- uniswap works

In conclusion, it is the same issue and Snapshot needs to update

The question is, why is the sample wallet working and how can we make it work for Ambire too without having dapps update

**Comment by Ivshti** [comment]
@arein confirming the sample wallet doesn't have this issue; judging by the description of #2869, this can be fixed wallet-side by setting a deep link; can we set a dummy unused deep link for ambire to get this fixed? @arein

**Comment by Ivshti** [comment]
@arein setting a deep link for ambire doesn't fix the issue for dapps that appear to be pre-2.8.6

The sample wallet is working for the sample dapp - at this moment I can't explain why

The sample dapp is working with the hack (`delete localStorage.WALLETCONNECT_DEEPLINK_CHOICE`) but not working (opening ambire in the same tab) without the hack, suggesting it's also pre-2.8.6. I can't be sure of this (dep chain is tough to follow) but it appears WAGMI updated to the fixed version on Jun 30 https://github.com/wagmi-dev/references/commit/2eec1a8b8662d5e09c543ae0b114ed2b6c1ef702 while the last update of the sample app happened on the 29th https://github.com/WalletConnect/web3modal/commit/a27dd8330db435dee5bfe8388d900c3f6f6393b2

**Comment by bkrem** [comment]
@0xAsimetriq based on @Ivshti's feedback above, is it possible that the lab deployments don't have the redirect fix in place?

**Comment by Ivshti** [comment]
> @0xAsimetriq based on @Ivshti's feedback above, is it possible that the lab deployments don't have the redirect fix in place?

it seems that, based on the version reported in the websocket is uses 2.8.4, which is pre-fix

**Comment by arein** [comment]
I'll close this now. We're kicking off a campaign urging dapps to upgrade this week. We are in touch with Snapshot too for an upgrade
