### ISSUE TITLE
ethereum-provider disconnects after refreshing the page

### ISSUE THREAD

**Issue by SumiBisht** [WalletConnect/walletconnect-monorepo#3089]
I am using ethereum-provider latest version to connect to wallet connect with web3modal,
whenever i connect with any wallet using new modal after refreshing the page it gets disconnected and i have to reconnect manually how can i keep my session, or connect to existing sessions.
`async function InitializeProviderClient() {
    // console.log('Initializing client');
    if(providerClient === undefined){ 
    const ethereumProvider = await EthereumProvider.init({
      projectId,
      showQrModal: true,
      qrModalOptions: { themeMode: 'light' },
      chains: [1,56],
      methods: ['eth_sendTransaction', 'personal_sign'],
      events: ['chainChanged', 'accountsChanged'],
      metadata: {
        name: 'app.expand.network',
        description: 'GUI for expandAPIs',
        url: 'https://app.expand.network',
        icons: [''],
      },
    });
    console.log('InitP');
    setProviderClient(ethereumProvider);
  }
  }`
`const connectToWalletV2 = async () => {
    try {
      setLoading(true);
      // checkIfExtensionIsAvailable();
      if (providerClient) {
        // console.log("connecting to v2");
        await providerClient.connect();
        console.log('connectTowalletV2')
        //  console.log('connected: ',providerClient);
        const library = new ethers.providers.Web3Provider(providerClient);
        await subscribeProvider(providerClient);
        //  console.log('subscribed');
        setLibrary(library);
        setWalletAddress(library);
        setLoading(false);
        setProvider(providerClient);
      }
    } catch (error) {
      setLoading(false);
      console.log(
        error,
        ' Client not set got this error on connectToWallet catch block while connecting the wallet'
      );
    }
  };`

**Comment by ganchoradkov** [comment]
Hey, after `EthereumProvider.init` the active session would be available at `ethereumProvider.session` so you could sync your state. You don't need to connect again if the session is present

**Comment by SumiBisht** [comment]
Hey @ganchoradkov please can you guide me how i can reconnect without opening the modal?
