### ISSUE TITLE
Add ADIL Chain

### ISSUE THREAD

**Issue by anhntbap** [WalletConnect/walletconnect-monorepo#3104]
**Adding a new chain to the Explorer**

1. **JSON-RPC:** ethereum-rpc https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc
2. **CASA namespace spec:** eip155 https://github.com/ChainAgnostic/namespaces/tree/main/eip155
3. **Namespaces:** eip155
4. **Chains**:
- Mainnet: eip155:7576
- Testnet: eip155:7575
- Devnet: eip155:123456
5. **RPC endpoints**
- Mainnet: https://adilchain-rpc.io
- Testnet: https://testnet.adilchain-rpc.io
- Devnet: https://devnet.adilchain-rpc.io
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**: 7576
I'm requesting addition to slip-0044 https://github.com/satoshilabs/slips/pull/1575

**Comment by Cali93** [comment]
Thanks for your chain submission, let us know when https://github.com/satoshilabs/slips/pull/1575 has been merged to move forward.

**Comment by tuananhht94** [comment]
> Thanks for your chain submission, let us know when [satoshilabs/slips#1575](https://github.com/satoshilabs/slips/pull/1575) has been merged to move forward.

Dear @Cali93,

I've been waiting for more than 1 week but it hasn't merged yet.
So I want to change our chain coin type to 60.
Please add our chain to https://cloud.walletconnect.com

Thank you and best regards,

**Comment by anhntbap** [comment]
> Thanks for your chain submission, let us know when [satoshilabs/slips#1575](https://github.com/satoshilabs/slips/pull/1575) has been merged to move forward.

Dear @Cali93,

I've been waiting for more than 1 week but it hasn't merged yet.
So I want to change our chain coin type to 60.
Please add our chain to https://cloud.walletconnect.com

Thank you and best regards,

**Comment by anhntbap** [comment]
@Cali93 This is urgent. Please help me. Thanks.

**Comment by Cali93** [comment]
Sorry for the confusion, this request is to add your chain on the list of options in our explorer.
So that wallets and dapps built on your chain can mark support for it.
It's purely informational and is separate from the WalletConnect protocol which supports any EVM chain by default.
dApps and wallets built on your chain should already be compatible with WalletConnect so there's no rush.

That said, we will try to add your chain Friday even if the SLIP PR still hasn't been merged.

**Comment by anhntbap** [comment]
@Cali93 
Could you tell me when our chain is added to https://cloud.walletconnect.com?
Thanks.

**Comment by Cali93** [comment]
Thanks for your patience, you chain has been added to the list of options on WalletConnect Cloud.
