### ISSUE TITLE
Add a Chain: XANAChain

### ISSUE THREAD

**Issue by SalmanNoborderz** [WalletConnect/walletconnect-monorepo#3108]
1. All JSON-RPC methods mentioned in (https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) are present in XANAChain's rpc. For more details (https://docs.avax.network/apis/avalanchego/apis)

2. **GitHub Link**: eip:155 for Ethereum/EVM-based chains

3. **namespaces**: eip155

4. **chains**:
Mainnet
ChainId: 8888
https://chainlist.org/chain/8888

5. **RPC endpoints**:
Mainnet
https://mainnet.xana.net/rpc
wss://mainnet.xana.net/ws

6. coin type**: 60

**Additional context**
XANAChain is subnet deployed on Avalanche Mainnet.

**Comment by pysingh09** [comment]
Could you please speed up this integration? We have to start the staking from tomorrow and at the end moment we got to know our chain is not supported.

**Comment by SalmanNoborderz** [comment]
@bkrem can you please look into this?

**Comment by Cali93** [comment]
Sorry for the confusion, this request is to add your chain on the list of options in our explorer. So that wallets and dapps built on your chain can mark support for it. 
It's purely informational and is separate from the WalletConnect protocol which supports any EVM chains by default.
