### ISSUE TITLE
CSP oversight.

### ISSUE THREAD

**Issue by joshstevens19** [WalletConnect/walletconnect-monorepo#311]
Hey, we are super strict with our CSP on our website, it seems on your mobile views you add full links to raw GitHub files

aka: https://raw.githubusercontent.com/WalletConnect/walletconnect-monorepo/next/packages/helpers/mobile-registry/logos/wallet-metamask.png

https://github.com/WalletConnect/walletconnect-monorepo/blob/9e80461d6d9dceb47c29200c5c20ba6c3ca95ce8/packages/helpers/mobile-registry/registry.json

This means it violates our CSP for our img-src and we really don't want to open that domain up on our website as anything can be put on `https://raw.githubusercontent.com` domain by anyone including malicious JS files etc this scares us a lot.

Could you not have those images pulled in from the package itself as an SVG or png and this would mean people would not have to whitelist scary domains to their CSP. 

We can get around it by replacing that file on compile-time but that's far from ideal. 

This proposal would not be a breaking change for the package either.

**Comment by pedrouid** [comment]
Actually this is a great suggestion and honestly it was just initially designed to allow people to import logos from different sources which then resulted in all logos to live inside Github.

I will make sure to include this in the next release

**Comment by joshstevens19** [comment]
Great. When do you expect the next release to be?

**Comment by pedrouid** [comment]
Just published a fix for this with v1.0.17
