### ISSUE TITLE
[BUG] TRON Network. TypeError: Cannot read properties of undefined (reading 'signature')

### ISSUE THREAD

**Issue by hyrbi** [WalletConnect/walletconnect-monorepo#3118]
I have just tried to integrate the TRON network into my multi-chain wallet and have some problems with the last step:

 ```
await web3wallet.engine.respondSessionRequest({
    topic: topic,
    response: formatJsonRpcResult(id, data),
  });
```
When I send data to WalletConnect Dapp for example [https://react-app.walletconnect.com/](url) I see this error:

`valid false
result TypeError: Cannot read properties of undefined (reading 'signature')`

**SDK Version (if relevant)**
 - Client: React Native, TS
 - Version 0.68

**To Reproduce**
I can't share my code to you, sorry :'(

**Additional context**
If you can share with me RPC spec. for TRON network (I didn't find it in the WalletConnect docs or in Dapps/Wallets examples), it will be very helpful for me.

**Comment by belovbelov** [comment]
I also have the same problem

**Comment by Ghosterbeef** [comment]
+1

**Comment by DamperX** [comment]
The same issue

**Comment by Anton-Kartashev** [comment]
Same error, please fix

**Comment by tolianius** [comment]
OMG! I think I am the only one who faced this problem,I also have this issue.

**Comment by vivanenko-itpelag** [comment]
Confirm this issue. It doesn't work on React Native

**Comment by bkrem** [comment]
@hyrbi Assuming that `data` is simply a signature string, could you please try passing it as an object like so `{ signature: string }` instead?

The way TRON RPC functionality was added to the sample dapp, it seems to expect an object as the result value:
https://github.com/WalletConnect/web-examples/blob/main/dapps/react-dapp-v2/src/contexts/JsonRpcContext.tsx#L1157

I'm also having a hard time finding the proper TRON RPC spec in general. @myzykj since you implemented the original PR for the example using this approach, could you please point people to a public spec for `tron_signTransaction` etc?

**Comment by myzykj** [comment]
Hi @hyrbi @beIov @Ghosterbeef @DamperX @Anton-Kartashev @tolianius @vivanenko-itpelag, 

We need to use tronweb to sign the tron transaction. Here is the example wallet  [https://react-wallet.walletconnect.com/](https://react-wallet.walletconnect.com/ ), and the source code is here [https://github.com/WalletConnect/web-examples/tree/main/wallets/react-wallet-v2](https://github.com/WalletConnect/web-examples/tree/main/wallets/react-wallet-v2)

I also created a Tron Wallet based on Web3Wallet today, [https://github.com/myzykj/tron-walletconnect-examples/tree/Web3Wallet-tron/wallets/react-web3wallet](https://github.com/myzykj/tron-walletconnect-examples/tree/Web3Wallet-tron/wallets/react-web3wallet), it works too.

You can try to use like these examples, any problem please let me know, thank you very much.

Thanks for @bkrem 's mention

**Comment by hyrbi** [comment]
> Hi @hyrbi @beIov @Ghosterbeef @DamperX @Anton-Kartashev @tolianius @vivanenko-itpelag,
> 
> We need to use tronweb to sign the tron transaction. Here is the example wallet https://react-wallet.walletconnect.com/, and the source code is here https://github.com/WalletConnect/web-examples/tree/main/wallets/react-wallet-v2
> 
> I also created a Tron Wallet based on Web3Wallet today, https://github.com/myzykj/tron-walletconnect-examples/tree/Web3Wallet-tron/wallets/react-web3wallet, it works too.
> 
> You can try to use like these examples, any problem please let me know, thank you very much.
> 
> Thanks for @bkrem 's mention

Hi @myzykj! Thank you for your answer and very fast example project with tron, but my question was about ReactNative, not React. So the non-castodial variant of transaction sending doesn't help me. If you can share RPC spec. for tron transaction to approve it on your side, I think it will help me. I just tried to put txId of transaction to RPC, but nothing helps :(

Thanks @bkrem for attention about this problem!

upd:
I think something like this spec can help me (it's eip155 rpc example from your doc):

```
// Request
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_signTransaction",
  "params":[{see above}],
}

// Result
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": "0xe670ec64341771606e55d6b4ca35a1a6b75ee3d5145a99d05921026d1527331"
}
```

**Comment by myzykj** [comment]
Hi @hyrbi ,

Tron is a separate blockchain platform from Ethereum and has its own transaction format and protocol, which is different from Ethereum. Therefore, Tron does not support EIP-155 as it is a specific Ethereum Improvement Proposal that only applies to the Ethereum network.

Tron Json PRC support these methods: [https://developers.tron.network/reference/json-rpc-api-overview](https://developers.tron.network/reference/json-rpc-api-overview)

If you want to use integrate the TRON network in your wallet, you can't use eip155 method, you need to write the sign method in your wallet

**Comment by hyrbi** [comment]
> Tron is a separate blockchain platform from Ethereum and has its own transaction format and protocol, which is different from Ethereum. Therefore, Tron does not support EIP-155 as it is a specific Ethereum Improvement Proposal that only applies to the Ethereum network.
> 
> Tron Json PRC support these methods: https://developers.tron.network/reference/json-rpc-api-overview
> 
> If you want to use integrate the TRON network in your wallet, you can't use eip155 method, you need to write the sign method in your wallet

@myzykj I know that I can't send Json RPC from eip155 spec. to TRON network, I asked you, for example, Json RPC response for a successful transaction to send it to your dapp. In the preview message I just sent what I wanted to see - an example of TRON transaction request/response.

**Comment by hyrbi** [comment]
@myzykj @bkrem Thank you for help, I just fixed my problem by this:
```
case SUPPORTED_METHODS.TRON_SIGN_TRANSACTION:
      return {
        result: {
          ...request.params.request.params.transaction.transaction,
          signature: response.signature,
        },
      };
```
Sorry for the misunderstanding, but I did not have a signature in the request and did not understand where to get it. After some research, I found the answer to my question in the TRON docs. Thanks for the help once again <3

**Comment by DamperX** [comment]
Yes, it's works properly!
