### ISSUE TITLE
Add EthereumPoW mainnet & testnet networks ⭐️

### ISSUE THREAD

**Issue by darkdx** [WalletConnect/walletconnect-monorepo#3125]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).

ethereum-rpc

2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.

eip155 specs

3. **namespaces**:

eip155

4. **chains**:

- Mainnet: EthereumPoW
	- ChainID: eip155:10001

- Testnet: EthereumPoW Testnet
	- ChainID: eip155:10003

5. **RPC endpoints***\*list of common/canonical RPC endpoints for the chain(s)*

- Mainnet: EthereumPoW
	- RPC: https://mainnet.ethereumpow.org

- Testnet: EthereumPoW Testnet
	- RPC: https://ethw-testnet.camelark.com

6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:

60

**Additional context**

```
// Mainnet: EthereumPoW
{
  id: 10001,
  name: "EthereumPoW",
  network: "EthereumPoW",
  nativeCurrency: {
    decimals: 18,
    name: "ETHW",
    symbol: "ETHW",
  },
  rpcUrls: {
    default: {
      http: ["https://mainnet.ethereumpow.org"],
    },
    public: {
      http: ["https://mainnet.ethereumpow.org"],
    },
  },
  blockExplorers: {
    default: { name: "Explorer", url: "https://www.oklink.com/en/ethw" },
  },
}
```

**Comment by topazdx** [comment]
We require this urgently!
We require this urgently!
We require this urgently!
