### ISSUE TITLE
Add DX Chain mainnet ✨

### ISSUE THREAD

**Issue by darkdx** [WalletConnect/walletconnect-monorepo#3127]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).

ethereum-rpc

2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.

eip155 specs

3. **namespaces**:

eip155

4. **chains**:

- Mainnet: DX Chain
	- ChainID: eip155:36

5. **RPC endpoints***\*list of common/canonical RPC endpoints for the chain(s)*

- Mainnet: DX Chain
	- RPC: https://mainnet.dxchain.com

6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:

60

**Additional context**

```
// Mainnet: DX Chain
{
	id: 36,
  name: "DX Chain",
  network: "DX Chain",
  nativeCurrency: {
    decimals: 18,
    name: "DX",
    symbol: "DX",
  },
  rpcUrls: {
    default: {
      http: ["https://mainnet.dxchain.com"],
    },
    public: {
      http: ["https://mainnet.dxchain.com"],
    },
  },
  blockExplorers: {
    default: { name: "DxScan", url: "https://dxscan.io" },
  },
}
```

**Comment by topazdx** [comment]
We require this urgently!
We require this urgently!
We require this urgently!
