### ISSUE TITLE
[React-Native / Android] Unable to communicate with relay server with socket

### ISSUE THREAD

**Issue by dev2rick** [WalletConnect/walletconnect-monorepo#3132]
**Describe the bug**
I am creating a wallet using React Native, but there seems to be a problem with websocket's JWT.
The strange thing is that it only happens on Android, and it works fine on iOS.
Same goes for the walletconnect example program. [react-native-example](https://github.com/WalletConnect/react-native-examples/tree/main/wallets/rn_cli_wallet_068_5)
All functions such as session proposal / request do not work because there is a problem with the socket.

**SDK Version (if relevant)**
 - Client: JS
 - Version: 2.8.4 / 2.7.0

**Node Version**
- 18.16.1

**To Reproduce**
1. Initializing Web3Wallet instance
2. Check console error message like below

```bash
{"context": "core"} {"context": "core/relayer"} [Error: WebSocket connection closed abnormally with code: 3000 (Authorization error: JWT validation error: JWT Token is expired: Some(1689089648))]
```

**Expected behavior**
Socket communication must be possible, and connection and information transmission with DApp must be possible.

**Screenshots**
<img width="1771" alt="스크린샷 2023-07-13 오후 4 20 19" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/135318619/d974ecc5-335d-4cef-8b3e-6c41d94698a8">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: safari
 - Version 13.4.1(22F82)

**Smartphone (please complete the following information):**
 - Device: Pixel_4_XL 
 - OS: Android 12
 - Browser Chrome

**Comment by ganchoradkov** [comment]
Hey, are you modifying your environment date settings? 
The JWT has an expiration of current time + 1 day. 
If your date time is artificially moved forward might cause this issue.

**Comment by dev2rick** [comment]
@ganchoradkov 
The emulator was set to 3 days ago.
Changing the date works fine.
Thanks.
