### ISSUE TITLE
Large Message Size Limitations in WalletConnect

### ISSUE THREAD

**Issue by seeden** [WalletConnect/walletconnect-monorepo#3150]
**Describe the bug**
When trying to send messages over WalletConnect that exceed a size of 71kb, the DApp does not receive these messages. No error is reported on the sender side, leading us to believe that WalletConnect may be ignoring or dropping these messages. This becomes a significant problem when our commands naturally produce messages larger than the aforementioned limit. Additionally, when message size exceeds 2MB, we hit the localStorage limit for a single item which cannot be changed.

**SDK Version (if relevant)**
 - Client: JS
 - Version 2.9.0

**To Reproduce**
Implement a command which produces a large message (over 71kb in size).
Try to send this message via WalletConnect to the DApp.
Notice that the DApp does not receive the message.
Also notice that there is no error reported on the sender side.

**Expected behavior**
I expected WalletConnect to successfully transmit messages of all sizes to the DApp without any loss. If a size limit does exist, we expected a clear error message. 
For messages with size > 2MB we should be able to use different storage instead of localStorage.

**Desktop (please complete the following information):**
 - OS: mac osx
 - Browser safari, electron
 - Version safari 16.5.2, electron: 25.1.1

**Comment by sharife3** [comment]
Any progress here - also experiencing same issue - it appears the history key in the local storage for WC is causing a break in our production application

**Comment by glitch-txs** [comment]
This should be fixed in the latest versions, please update all packages and let us know if the issue still persists.

**Comment by jonandgon** [comment]
@glitch-txs what is the size limit for messages? It's still not clearly defined anywhere. I am getting the following error when sending a response message from wallet to dApp:

`Failed to process request: Payload size limit exceeded. Maximum size for tag 1109 is 98304`, but it's not clear at all where 98304 comes from.
