### ISSUE TITLE
How I can connect to my AA wallet using WalletConnect, provided the owner of AA wallet is mine EOA

### ISSUE THREAD

**Issue by aditya-passbird** [WalletConnect/walletconnect-monorepo#3151]
**Describe the bug**

**SDK Version (if relevant)**
 - Client: [e.g. JS, Swift, Kotlin]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ganchoradkov** [comment]
please open GH discussion for implementation questions
