### ISSUE TITLE
[bug] MetaMask deeplink

### ISSUE THREAD

**Issue by pi0neerpat** [WalletConnect/walletconnect-monorepo#316]
Not sure it this is a bug or was never supposed. Clicking the button to deep link (eg. not scanning the qr code) will open the MM app, but doesn't make any prompts to connect.

@walletconnect/web3-provider v1.0.13
Android/firefox

Side note, I cannot get any method to open their browser I tried

- universal link "https://metamask.app.link/dapp/mysite.com"  Only prompts to open app in Chrome
- deep link "ethereum:mysite.com"
- EIP 1710 "dapp:1@mysite.com"

**Comment by pedrouid** [comment]
Are you trying to connect with WalletConnect or opening your dapp inside Metamask Mobile?

**Comment by pi0neerpat** [comment]
I want to be able to use the dapp in the default mobile browser, not MetaMask browser.

So if they unlock / sign a transaction, it prompts them to confirm the request via metamask. 

Being locked into MM, or any wallet browser is a bad experience imo. And it prevents me from using PWA

**Comment by pi0neerpat** [comment]
Have you been able to reproduce this issue?

Android firefox > Click "Connect" in wallet connect > Metamask opens but nothing happens.

It seems their deeplinks are in a state of flux now, however they are unresponsive https://github.com/MetaMask/metamask-mobile/issues/1761

**Comment by finessevanes** [comment]
Hey @pi0neerpat, I'm a Developer Advocate for WalletConnect. Are you still experiencing this bug?

**Comment by pi0neerpat** [comment]
Its old enough that I don't remember :)
