### ISSUE TITLE
Methods and Events missing - Ethereum Provider

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/walletconnect-monorepo#3161]
**Describe the bug**

There's now an option to set empty chains, this will remove the required methods and events from config

```ts
    const requiredMethods = requiredChains.length ? opts?.methods || REQUIRED_METHODS : [];
    const requiredEvents = requiredChains.length ? opts?.events || REQUIRED_EVENTS : [];
    const optionalMethods = opts?.optionalMethods || [];
    const optionalEvents = opts?.optionalEvents || [];
```

I suggest adding `"eth_sendTransaction", "personal_sign"`  and `"chainChanged", "accountsChanged"` in the [OPTIONAL_METHODS  and OPTIONAL_EVENTS arrays respectively](https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/providers/ethereum-provider/src/constants/rpc.ts)

**Comment by ganchoradkov** [comment]
Hey @glitch-txs, we're actually already doing that here
https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/providers/ethereum-provider/src/EthereumProvider.ts#L164
