### ISSUE TITLE
[React-Native / Android] The connection is intermittent.

### ISSUE THREAD

**Issue by Rick-ahnlabio** [WalletConnect/walletconnect-monorepo#3166]
**Describe the bug**
I'm making a wallet with React-Native. I'm trying to connect to DApp in emulator, but intermittently the connection fails and there's no response. It's not even being caught in the catch block. This error occurs only on Android, and is working fine on iOS. It doesn't work as well in practical devices for Android as well. I attached a log video of debugging mode.

**SDK Version (if relevant)**
 - Client: JS
 - Version:
 ```json
    "@walletconnect/client": "^1.8.0",
    "@walletconnect/legacy-types": "^2.0.0",
    "@walletconnect/react-native-compat": "^2.9.0",
    "@walletconnect/sign-client": "^2.7.0",
    "@walletconnect/utils": "^2.7.0",
    "@walletconnect/web3wallet": "^1.8.6",
 ```

**To Reproduce**
1. Access the DApp site from a browser on your device. (Uniswap, Opensea, 1inch ...)
2. Attempt to connect to WalletConnect V2.
3. The browser automatically opens the wallet app using wcuri.
4. Run `await signClientV2.core.pairing.pair({uri})`

**Expected behavior**
The connection should be good, otherwise it should be captured with an error message in the catch block.

**Screenshots**

https://github.com/WalletConnect/walletconnect-monorepo/assets/119639587/b8d54e5e-c855-4713-8f7c-8a27d3dd94f1

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: Ventura 13.4.1 (c)

**Smartphone (please complete the following information):**
 - Device: Pixel_3a_API_33
 - OS: Android
 - Browser Chrome
 - Version: Android 13

**Comment by glitch-txs** [comment]
This should be fixed in the latest versions, please update all packages and let us know if the issue still persists.
