### ISSUE TITLE
Adding Evmos to Chainlist

### ISSUE THREAD

**Issue by sandoche** [WalletConnect/walletconnect-monorepo#3179]
**Adding a new chain to the Explorer**

1. JSON-RPC spec for Wallets: Same as [ethereum](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc), more details [here](https://docs.evmos.org/develop/api/ethereum-json-rpc/methods).
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces): eip155
3. **namespaces**: eip155
4. **chains**:
- Mainnet: eip155: 9001
- Testnet: eip155: 9000
5. **RPC endpoints**
- Mainnet: https://eth.bd.evmos.org:8545
- Testnet: https://eth.bd.evmos.dev:8545
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**: 60

**Comment by Cali93** [comment]
Your chain has been added in the list of options in WalletConnect Cloud.
