### ISSUE TITLE
Bug - Cannot complete transfer on Android Metamask

### ISSUE THREAD

**Issue by chiraagshah-qa** [WalletConnect/walletconnect-monorepo#318]
Currently cannot complete any transactions using MetaMask.

Authorisation prompt to complete transfer does not appear in Metamask.

**Comment by estebanmino** [comment]
hey @FunFair-chiraagshah, I'm Esteban from MetaMask. What version of the app are you using? Thank you.

**Comment by estebanmino** [comment]
also from what dapp are you triggering the call, thank you

**Comment by chiraagshah-qa** [comment]
Hi @estebanmino,

I am using v0.2.19(32) of the app.
Triggering call from wallet.funfair.io (from our dev environment)

**Comment by miohtama** [comment]
Closing this issue as we cannot help with MetaMask Mobile issues. Those issues should go to MetaMask issue tracker.
