### ISSUE TITLE
provider.request doesn't work with eth_sendTransaction

### ISSUE THREAD

**Issue by Velenir** [WalletConnect/walletconnect-monorepo#319]
Now that **Web3@1.2.11** supports and [prefers calling `provider.request`](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-core-requestmanager/src/index.js#L182-L187) instead of `sendAsync|send`, there is a problem with `@walletconnect/web3-provider` with write requests `eth_sendTransaction|eth_sign|etc.`
These requests [get rerouted to `handleReadRequests`](https://github.com/WalletConnect/walletconnect-monorepo/blob/next/packages/providers/web3-provider/src/index.ts#L251-L252) and on to **HttpConnection**, when they need to go to `web3-provider-engine`. Before it was not a problem as **Web3** would call `senAsync(payload, callback)` directly.

Another problem is when **Web3** waits for a transaction to be mined. It sends a `eth_getTranscationRequest` for a tx hash, and check on interval until receipt is not null.
But [`provider.send` throws if `res.result is falsy`](https://github.com/WalletConnect/walletconnect-monorepo/blob/next/packages/providers/web3-provider/src/index.ts#L194-L200)

A reproduction as well as proposed changes can be seen in this [sandbox](https://codesandbox.io/s/7j7mq?file=/src/App.js)

**Comment by pedrouid** [comment]
Fixed with [v1.2.0](https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/1.2.0)
