### ISSUE TITLE
No matching keychain

### ISSUE THREAD

**Issue by SumiBisht** [WalletConnect/walletconnect-monorepo#3191]
I am getting this whenever i switch my network
<img width="824" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/40060905/23799580-b352-4ccc-8906-e8d243385b53">
Please help me out

**Comment by glitch-txs** [comment]
hi, could you provider more information?
- Packages you're using, 
- a minimal reproducible example repo
- does this happen on dev or prod env?
- which wallet are you using?

Thanks!

**Comment by glitch-txs** [comment]
Aswered [here](https://github.com/orgs/WalletConnect/discussions/3291). Seems to be an issue on the Wallet side.
