### ISSUE TITLE
Verify attestation error when you try to get session_request

### ISSUE THREAD

**Issue by Metallistener** [WalletConnect/walletconnect-monorepo#3196]
Sometimes when you expect to get event response from **session_request** you get 404 error of **https://verify.walletconnect.com/attestation/37a7f591eb293e32ac31213f1d587e4e3c0537b2c56b5d93319f72670120bd71**. 
Can someone say how to fix this problem? How to avoid this error?

<img width="546" alt="Снимок экрана 2023-07-18 в 15 03 43" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/33493261/aab63db1-772e-449e-ad3e-75461ecede34">

**Comment by ganchoradkov** [comment]
Hey @Metallistener, this is an expected behavior, if the dapp you're using doesn't have Verify API enabled.
You can safely disregard the error

**Comment by mr-zwets** [comment]
I disabled the 'Verify API' in project settings, yet still get the same error.
Does the change take a while to take effect?

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/53938059/fbc4bd07-923f-4388-a545-399928ef0845)

**Comment by rnbrady** [comment]
The reason for the fallback to an HTTP request which fails with 404 is that JWT verification has failed. See #7176 for one possible explanation.
