### ISSUE TITLE
Error Throwing after a few minutes on opening WC modal

### ISSUE THREAD

**Issue by rajathongal** [WalletConnect/walletconnect-monorepo#3198]
### Discussed in https://github.com/orgs/WalletConnect/discussions/3192

<div type='discussions-op-text'>

<sup>Originally posted by **rajathongal** July 18, 2023</sup>
`Failed to execute 'setItem' on 'Storage': Setting the value of 'wc@2:core:0.3//messages' exceeded the quota.`</div>

**Comment by osmanthustonx** [comment]
same issue

**Comment by rajathongal** [comment]
@0xAsimetriq

**Comment by xzilja** [comment]
Your localStorage is full it seems

**Comment by jonandgon** [comment]
I'm having the same issue after a dApp has been connected for a long time. Our wallet wallet continues to send updates to the dApp as the wallet state updates. I think old messages should be discarded automatically by walletconnect. There's no need for 1000+ messages to be stored by default.

**Comment by rajathongal** [comment]
> I'm having the same issue after a dApp has been connected for a long time. Our wallet wallet continues to send updates to the dApp as the wallet state updates. I think old messages should be discarded automatically by walletconnect. There's no need for 1000+ messages to be stored by default.

yes I feel the same it is an issue with WC

**Comment by jonandgon** [comment]
@0xAsimetriq @finessevanes Is there any planned work to address this? My dApp's console log is full of errors anytime data is sent because of this bug. The only good solution I could come up with myself is to clear the `wc@2:core:0.3//messages` item in local storage once it gets too big. This obviously isn't ideal, and could mess up any ongoing requests.

**Comment by jonandgon** [comment]
Here's an idea of what my console logs look like... it's a sea of red :(

<img width="1352" alt="CleanShot 2023-08-25 at 18 55 03@2x" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/75697675/6d2f1723-9ee7-4caf-87f3-5ed3d12f1671">

**Comment by xzilja** [comment]
> Here's an idea of what my console logs look like... it's a sea of red :(
> 
> 
> 
> <img width="1352" alt="CleanShot 2023-08-25 at 18 55 03@2x" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/75697675/6d2f1723-9ee7-4caf-87f3-5ed3d12f1671">
> 

We already made improvements here in latest versions of modal and walletconnect dependencies, make sure to update. Meanwhile we are investigating index db as alternative to localStorage (issue you see is due to limit of data allowed to be stored there which index db expands uppon)

**Comment by jonandgon** [comment]
@0xAsimetriq The library I'm using hasn't been updated since last month. Can you update the dependencies for it? Thanks!

https://www.npmjs.com/package/@walletconnect/modal-sign-react

**Comment by glitch-txs** [comment]
This should be fixed in the latest versions, please update all packages and let us know if the issue still persists.

**Comment by OkponkoXchange** [comment]
I'm going to be in town this mode today
