### ISSUE TITLE
The web page will automatically redirect to the homepage of 'ME'

### ISSUE THREAD

**Issue by Jlp18** [WalletConnect/walletconnect-monorepo#3207]
**Describe the bug**
When I click 'ME' application on the desktop section, then back to scan the QR code and connect, If I send a request such as 'eth_sendTransaction', the web page will automatically redirect to the homepage of 'ME'.

**SDK Version (if relevant)**
 - "@walletconnect/ethereum-provider": "^2.8.3",
 - "@walletconnect/modal": "^2.5.4",

**To Reproduce**
1. Open the modal and click 'ME' on desktop section.
2. Back to the QR code and scan to connect.
3. Send a transcation.
4. The page will be redirected. 

**Expected behavior**
It should be possible to send transactions normally. The web page should keep on my website.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser :chrome

**Smartphone (please complete the following information):**
 - Device: iPhone13
![20230719-105732](https://github.com/WalletConnect/walletconnect-monorepo/assets/32257090/b4001c30-d0a0-42fe-a80d-be1f8ed1ecf7)

**Comment by glitch-txs** [comment]
This should be fixed in the latest versions, please update all packages and let us know if the issue still persists.
