### ISSUE TITLE
walletconnect cannot listen disconnect events while refresh page

### ISSUE THREAD

**Issue by hawx1993** [WalletConnect/walletconnect-monorepo#321]
```js
 public walletConnectInit = async () => {
    // bridge url
    const bridge = "https://bridge.walletconnect.org";

    // create new connector
    const connector = new WalletConnect({ bridge, qrcodeModal: QRCodeModal });

    await this.setState({ connector });

    // check if already connected
    console.log("connector", connector);
    if (!connector.connected) {
      // create new session
      await connector.createSession();
    }

    // subscribe to events
connector.on('disconnect', () => {})
  };

```

just follow this example: 

https://example.walletconnect.org/

https://github.com/WalletConnect/walletconnect-example-dapp

while the user refresh the page,  and disconnect wallet from app, the disconnect callback will not be execute.

but if not refresh the page, the callback can work.

**Comment by sprguillen** [comment]
+1 for this, I also have the same issue. I hope the package author addresses the issue.

**Comment by finessevanes** [comment]
Hey @hawx1993 and @sprguillen are either of you still experiencing this issue?
