### ISSUE TITLE
Can not use Walletconnect V2 to EthereumPoW

### ISSUE THREAD

**Issue by 0xStarry** [WalletConnect/walletconnect-monorepo#3212]
**Describe the bug**
Hello, I have already added support for WalletConnectV2 to EthereumPoW on GitHub and have added it to the supported chain list. However, I am still unable to connect to EthereumPoW using WalletConnectV2. What could be the problem?I am using the Rainbowkit plugin.

**SDK Version (if relevant)**
"@rainbow-me/rainbowkit": "^1.0.5",

**To Reproduce**
1.Add ethwchain info
`export const ethwChain: Chain = {
  id: 10001,
  network: "EthereumPoW",
  name: "EthereumPoW",
  nativeCurrency: {
    name: "ETHW",
    symbol: "ETHW",
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ["https://mainnet.ethereumpow.org"],
    },
    public: {
      http: ["https://mainnet.ethereumpow.org"],
    },
  },
  iconUrl: "https://s2.coinmarketcap.com/static/img/coins/64x64/21296.png",
  blockExplorers: {
    default: {
      name: "Explorer",
      url: "https://mainnet.ethwscan.com/",
    },
  },
  testnet: false,
};`
2. config ethwchain
`const { chains, publicClient, webSocketPublicClient } = configureChains(
  [
    mainnet,
    // polygon,
    // optimism,
    // arbitrum,
    // zora,
    ethwChain,
    ...(process.env.NEXT_PUBLIC_ENABLE_TESTNETS === "true" ? [goerli] : []),
  ],
  [publicProvider()]
);`

**Comment by bkrem** [comment]
Hi @0xStarry,

This likely means that the wallet(s) you're attempting to connect to are not approving EthereumPoW as a chain they support.

Adding a given chain to WalletConnect Cloud does not influence wallet or dapp support for the chain in any way, it simply let's a wallet/dapp signal their support for that chain in the future. See the info box here for more context: https://docs.walletconnect.com/2.0/advanced/multichain/overview#register-chain-with-the-explorer
