### ISSUE TITLE
Error: invalid account - Problems with creating Universal Provider - it take last connected wallet

### ISSUE THREAD

**Issue by tobob** [WalletConnect/walletconnect-monorepo#3223]
**Describe the bug**
When creating UniversalProvider to sign the contract method I'm not able to switch between sessions
Inside my SignClient I see all of them when calling (there are two MetaMask and Rainbow):

```
client.session.getAll()
```

My code is something like this:

```
import SignClient from "@walletconnect/sign-client";
import { UniversalProvider } from "@walletconnect/universal-provider";


      const client = await SignClient.init({
        projectId: Config.WALLET_CONNECT_PROJECT_ID,
        metadata: providerMetadata,
      });

.....

      const universalProvider = await UniversalProvider.init({
        projectId: Config.WALLET_CONNECT_PROJECT_ID,
        metadata: providerMetadata,
        client,
        disableProviderPing: true,
      });
      universalProvider.session = session;
      await universalProvider.connect({
        skipPairing: true,
        namespaces: {
          eip155: {
            methods,
            chains,
            events,
          },
        },
        pairingTopic: session.pairingTopic, //<- this actually does nothing
      });
      const walletConnectProvider = new ethers.BrowserProvider(
        universalProvider,
        "mainnet"
      );
      const accounts = await walletConnectProvider.listAccounts();
      console.log({accounts})
      const signer = await walletConnectProvider.getSigner(walletAdress); // <-here it fails with Error: invalid account

```

**SDK Version (if relevant)**
 - JS - 2.9.0 - react-native

**Expected behavior**
UniversalAccount should have all the addresses with corresponding sessions

I was trying switch default SignClient session without any ease

**Comment by ganchoradkov** [comment]
Hey @tobob, please update to latest as your version is quite outdated, and try again. 
If the issue persists, please provide a minimal repo where we can reproduce the bug, thank you.

**Comment by tobob** [comment]
@ganchoradkov Sorry, I did enter the wrong version, I have the latest version, and I will try to reproduce this, basically problem is when I have more then one session, in that case UniversalProvider is initialized with the last connected wallet

I will try to create sample repo to reproduce

**Comment by tobob** [comment]
@ganchoradkov there is a repo to reproduce issue: https://github.com/tobob/wallet-connect-session-issue

maybe I'm doing something wrong, but after adding additional session app work like a mess

**Comment by tobob** [comment]
resolved this by preparting payload to sign and then reqiesting client with this params (with `populateTransaction`)

```
const usdcContractAddress = USDC_contractAddress[1];
      const amountInHex = ethers.parseUnits(value, 6);
      const usdcContract = new ethers.Contract(usdcContractAddress, usdcAbi);

      usdcContract.transfer
        .populateTransaction(to, amountInHex)
        .then(async (tx: any) => {
          try {
            redirectToWalletCallback();
            const result = await client.request<string>({
              topic: session.topic,
              chainId: "eip155:1",
              request: {
                method: "eth_sendTransaction",
                params: [
                  {
                    ...tx,
                    from: address,
                    nonce: nonceDecoded,
                    gasPrice: 26000,
                  },
                ],
              },
            });
            successCallback();
```

**Comment by glitch-txs** [comment]
This should be fixed in the latest versions, please update all packages and let us know if the issue still persists.
