### ISSUE TITLE
QR Code Modal doesn't show which wallets a users can use

### ISSUE THREAD

**Issue by p0s** [WalletConnect/walletconnect-monorepo#323]
### Issue

Our imToken wallet user gave us the feedback that not all WalletConnect-supporting DApps show which wallets are actually working with WalletConnect during the 'Connect with WalletConnect' QR code modal.

### Possible solution

The goal: Let people know about the many wallets that support WalletConnect inside the DApp, right next to the QR code

The lower picture shows one solution. Maybe there's a more beautiful one that can also be integrated into the [Web3Modal](https://github.com/Web3Modal/web3modal/)

![image](https://user-images.githubusercontent.com/23061820/88519361-95de5f00-d024-11ea-90a4-c86daafbb93a.png)

### User stories

As a user who opens the WalletConnect QR code on [any WalletConnect-supported DApp]. I would like to see which wallet app I can actually use with to scan that QR can, in order to use this DApp with the wallet app I like most.

As a complete noob without any wallet, I want to know which wallet I can use with WalletConnect after the WalletConnect QR code pops up, so that I can install this wallet app and get going.

**Comment by Kundn-lal** [comment]
Unable to open QR modal Wallet  Connect
my code : 

  const provider = new WalletConnectProvider({
            infuraId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        });

        await provider.enable();

        // @ts-ignore
        this.web3 = new Web3(provider);

previously same code working but i checked again it is not working...

getting this log :  

ZoneAwarePromise {__zone_symbol__state: null, __zone_symbol__value: Array(0)}

any help !

**Comment by finessevanes** [comment]
@Kundn-lal if you're still having an issue, please create it's separate issue.

**Comment by finessevanes** [comment]
Closing this because this feature is done in v2. 
<img width="380" alt="image" src="https://user-images.githubusercontent.com/44731696/204964374-09faf34b-4c3b-4e3b-b2e7-8c4db20d9a62.png">
