### ISSUE TITLE
Android Wallet Connect V2 Big Int Bug in React Native

### ISSUE THREAD

**Issue by ajtraxler** [WalletConnect/walletconnect-monorepo#3235]
**Describe the bug**

I am using Wallet Connect V2 for react native mobile log in.  It is working perfectly for iOS but I am running into an issue with Android that prevent users from logging in.

The issue I am running into for Android is "Can't find variable: BigInt" within node_modules/@walletconnect/jsonrpc-utils/dist/esm/format.js

**SDK Version (if relevant)**
 -     "@walletconnect/modal-react-native": "^1.0.0-rc.6",

**To Reproduce**
I followed the Docs for React Native for log-in: https://docs.walletconnect.com/2.0/reactnative/walletconnectmodal/dapp-usage

**Screenshots**

<img width="832" alt="Screenshot 2023-07-20 at 11 18 40 AM" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/89072624/9eb4caa5-0437-4dad-a9e0-1ee9745a453d">

**Smartphone (please complete the following information):**
Android v13

**Additional context**
Thank you for your help!

**Comment by ignaciosantise** [comment]
hey @aoniatraxler what version of RN are you using?

If you have react native < 0.70, you need to polyfill BigInt. 
1. Run `yarn add big-integer`
2. Add `if (typeof BigInt === 'undefined') global.BigInt = require('big-integer')` at the top of your root file, before importing the modal SDK
