### ISSUE TITLE
Excuse me, how to obtain the parameters behind wc, why the key and public id I applied for are very different from yours

### ISSUE THREAD

**Issue by fftwaunj** [WalletConnect/walletconnect-monorepo#3242]
Excuse me, how to obtain the parameters behind wc, why the key and public id I applied for are very different from yours

_Originally posted by @kurt-2018 in https://github.com/WalletConnect/walletconnect-monorepo/discussions/2947#discussioncomment-6494696_

**Comment by fftwaunj** [comment]
would like to know too

**Comment by ganchoradkov** [comment]
Hey @fftwaunj , do you mean how to parse the uri?
