### ISSUE TITLE
Add Algorand(non-EVM) To Walletconnect(v2) Explorer

### ISSUE THREAD

**Issue by kcelestinomaria** [WalletConnect/walletconnect-monorepo#3251]
###  **JSON-RPC spec for Wallets:**
 Algorand does not have a JSON-RPC Spec specifically dedicated for Wallets. Algorand developers and projects primarily use a REST API to interact with the network with varied wallet integrations as well as dapps. So, the spec for interacting with an Algorand Node Provider is: ``https://<algorand-node-host>:<algorand-node-port>``, popular node providers include Purestake, Algod, Tatum, Quicknode, Blockdaemon among many others. 
See example: Purestake's Algorand Node Endpoint URL - ``https://mainnet-algorand.api.purestake.io/ps2 [ MAINNET ]``

JSON Request Format is:
```

{
  "id": <request-id>, // a unique ID for the request. Integer or String is accepted
  "jsonrpc": "2.0",
  "method": "<method-name>", // The name of the method you want to call on the Algorand node.
  "params": [<params>] //*An array containing the parameters required for the method. Remains empty if not required 
}
```

For example, here is how you get an Algorand Account, see:

```
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "algod.account_info",
  "params": [
    "<algorand-address>"
  ]
}

```

 ### **Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.**
Please find Algorand's CASA namespace spec here: https://github.com/ChainAgnostic/namespaces/tree/main/algorand 

Namespace prefix/identifier is ``algorand``

**Namespaces:**
Examples could be:
- Key Generation:
``algorand_keygen``: Generate a new Algorand account (address and private key).
- Transaction Signing:
``algorand_signTx``: Sign an Algorand transaction with a given private key.
- Address Validation:
``algorand_isValidAddress``: Validate the format of an Algorand address.
- Transaction Serialization:
``algorand_serializeTx``: Serialize an Algorand transaction to its binary representation.
- Transaction Encoding/Decoding:
``algorand_encodeTx``: Encode an Algorand transaction to its base64 representation for broadcasting.
``algorand_decodeTx``: Decode a base64-encoded Algorand transaction back to its binary representation.
- Asset Management:
``algorand_createAsset``: Create a new Algorand asset (Algorand Standard Asset - ASA).
``algorand_modifyAsset``: Modify an existing Algorand asset (e.g., change asset name, total supply).
``algorand_optInToAsset``: Opt-in to an existing Algorand asset.
- Blockchain Data Retrieval:
``algoand_getBlock``: Get information about a specific Algorand block.
``algorand_getTransaction``: Get information about a specific Algorand transaction by its ID.
``algorand_getAsset``: Get information about a specific Algorand asset by its ID.
- Account Information:
``algorand_getAccount``: Get information about an Algorand account, including its balance and assets.
- Chain Information:
``algorand_getNetwork``: Get the network information, including the network ID and name.

### **Chains:**
Just ``algorand`` , or for more detail(testnet/mainnet, algod/indexer) we have:
- ``algorand-testnet-algod``
- ``algorand-mainnet-algod``
- ``algorand-testnet-indexer``
- ``algorand-mainnet-indexer``

### **RPC endpoints for the chain:**
  Using Tatum API Service Provider, we can get JSON-RPC Endpoints for Algorand. 
Many other node service providers only have REST format endpoints, so I picked Tatum for this case.
*See Tatum Node API Service Provider(https://apidoc.tatum.io/tag/Node-RPC#operation/NodeJsonRpcGetDriver)
- ``https://api.tatum.io/v3/blockchain/node/algorand-mainnet-algod/{xApiKey}/{rpcPath}``
- ``https://api.tatum.io/v3/blockchain/node/algorand-mainnet-indexer/{xApiKey}/{rpcPath}``

Request Format still remains the same:
```

{
  "id": <request-id>, // a unique ID for the request. Integer or String is accepted
  "jsonrpc": "2.0",
  "method": "<method-name>", // The name of the method you want to call on the Algorand node.
  "params": [<params>] //*An array containing the parameters required for the method. Remains empty if not required 
}

```
For example, here is how you get Chain Information on Algorand, see:
```

{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "algorand_getNetwork",
  "params": [
    "<algorand-address>"
  ]
}
```

### **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
 -  SLIP-0044 for Algorand: 283

**Additional context**

**Comment by Cali93** [comment]
Hey @kcelestinomaria,

Algorand chains are already available in the list of option on WalletConnect Cloud.

**Comment by kcelestinomaria** [comment]
Hi @Cali93 , thank you so much for your reply. Yes, on the docs it says Algorand chains are available, but there is so little information on its chain id, its namespace methods, and rpc-reference, like how we have the same for Solana, Ethereum, NEAR, Cosmos etc. This makes it seem like its not actually integrated fully. Can you help point me to where those details are for Algorand? We have a wallet we are integrating walletconnect for, and we have been stuck for the 2nd week just trying to figure this out, this is why we even raised this as an issue.

Many thanks & kind regards
