### ISSUE TITLE
Mixin Virtual Machine

### ISSUE THREAD

**Issue by jadeydi** [WalletConnect/walletconnect-monorepo#3253]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **Same as [ethereum](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc)**.
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) : eip155
3. **namespaces**: eip155
4. **chains**:
    - Mainnet: eip155: 73927
5. **RPC endpoints**
   - https://geth.mvm.dev/
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**: 60

**Comment by bkrem** [comment]
Thanks for your submission 🙏 

Mixin Virtual Machine is already available on https://cloud.walletconnect.com
