### ISSUE TITLE
Reconnecting to a dapp, after disconnecting gives error on dapp end

### ISSUE THREAD

**Issue by fareed945** [WalletConnect/walletconnect-monorepo#3254]
**Describe the bug**
I'm not able to reconnect to a dapp, after disconnecting from it once and trying to do a new pairing.
I'm using the latest release of both, the Sample react dapp and my wallet with the latest release made few days ago.

**To Reproduce**
1) As usual, pair with the dapp by calling the pair method. Works fine.
2) Now disconnect from the dapp like this 

```
export async function disconnectSession() {
  let sessions: any = getActiveSessions();
  sessions.forEach(async ({ topic }) => {
    await web3wallet.disconnectSession({
      topic,
      reason: walletconnectUtils.getSdkError("USER_DISCONNECTED"),
    });
  });

  // Disconnect all pairings and sessions
  let pairings = getActivePairings();

  pairings.forEach(async ({ topic }) => {
    await web3wallet.disconnectSession({
      topic,
      reason: walletconnectUtils.getSdkError("USER_DISCONNECTED"),
    });

    await web3wallet.core.relayer.unsubscribe(topic);
    web3wallet.core.expirer.del(topic);
  });

  
}
```
3) Do a new pair request again, by taking the new code from the dapp, gives me error like this:
```
_app-34b8e6c7f6529fc3.js:163 Uncaught (in promise) Error: No matching key. history: 1690181392521029

```

**Expected behavior**
The dapp should connect successfully as this is a new pairing.

**Screenshots**

![Screenshot from 2023-07-24 12-38-04](https://github.com/WalletConnect/walletconnect-monorepo/assets/64576027/4dfc9009-bfbb-49e9-a173-b5d6f20e3669)

**Comment by ganchoradkov** [comment]
Hey @fareed945, which wallet are you using to connect?
Also, is the second connecting working besides the errors?

**Comment by fareed945** [comment]
Hey @ganchoradkov , this is our custom wallet where we've integrated with walletconnect v2, no the second connection doesn't work. It just doesn't do anything (dapp).
I don't get back the session proposal  as well.
Am I disconnecting in a right way ? thoughts?

**Comment by ganchoradkov** [comment]
Could you share an example repo where I can see your implementation?
I'm failing to reproduce the issue using our example dapp/wallet.
https://react-app.walletconnect.com/
https://react-wallet.walletconnect.com/
Does it happen with every wallet you're using or just your custom one?

**Comment by ganchoradkov** [comment]
btw, seeing your code snippet, all of the pairing disconnect/cleanup is not needed as its done internally. 
Doing it yourself might be contributing to the issue
```
  // Disconnect all pairings and sessions
  let pairings = getActivePairings();

  pairings.forEach(async ({ topic }) => {
    await web3wallet.disconnectSession({
      topic,
      reason: walletconnectUtils.getSdkError("USER_DISCONNECTED"),
    });

    await web3wallet.core.relayer.unsubscribe(topic);
    web3wallet.core.expirer.del(topic);
  });
```

**Comment by fareed945** [comment]
Ok, let me try removing this part and get back.

**Comment by fareed945** [comment]
Hey @ganchoradkov , that did the trick, the actual problem, was multiple listeners being added, my bad :(. 
Thanks for your support
