### ISSUE TITLE
Using walletConnect to connect another blockchain(rainbowKit) while enabling walletConnect in use-Wallet cause error of `Failed to execute 'define' on 'CustomElementRegistry': the name "wcm-button" has already been used with this registry`

### ISSUE THREAD

**Issue by jingxuan98** [WalletConnect/walletconnect-monorepo#3256]
**Describe the bug**
I am using walletConnect to connect another blockchain via (rainbowKit with wallet-connect option) while enabling walletConnect in use-Wallet for algorand (https://github.com/TxnLab/use-wallet) as well

**SDK Version (if relevant)**
    "@walletconnect/modal-sign-html": "2.5.9", // tried 2.6.0 but still same using 2.5.9 because wagmi using 2.5.9 for modal
    "wagmi": "^1.3.9",
    "@rainbow-me/rainbowkit": "^1.0.7",

**To Reproduce**
1. Setup rainbowkit
2. Setup another wallet library using wallet-connect, eg. use-Wallet for algorand
3. start the dev web

**Expected behavior**
Should be able to wallet-connect on both chains successfully

**Screenshots**
![Screenshot 2023-07-24 at 6 00 17 PM](https://github.com/WalletConnect/walletconnect-monorepo/assets/43902263/4a94afb6-9e4c-49b3-bacd-766ef9132385)

**Additional context**

**Comment by glitch-txs** [comment]
Hi, make sure you set up the SDK configuration outside the react comoponents. I think they have already an example on their repo :)
