### ISSUE TITLE
Unable to use Paymaster with WalletConnect

### ISSUE THREAD

**Issue by equalogix** [WalletConnect/walletconnect-monorepo#3269]
**Describe the bug**
I'm trying to sign and send a type 113 transaction using MetaMask mobile. I can send a transaction without out any problems when it is sent using the MetaMask Browser, but when trying to send it from the default browser using Walletconnect it fails. The strange thing is that with WC it get's to the MM submit pop-up, but when you click submit the transaction fails. When using MM-Browser you get the exact same transaction that pop-ups and when one submits it, it succeeds.

I'm trying to send the transaction on zkSync-Era chain using a Paymaster, and my guess is that the Paymaster is causing the problem. If remove the paymaster from the transaction, that is I don't include the `customData` prop in the `overrides`, then the transaction is sent normally. When eliminating the paymaster from the transaction, the transaction that is sent is not type 113.

When the transaction fails the error is: `Internal JSON-RPC error`.

**SDK Version (if relevant)**
 - @walletconnect/ethereum-provider v2.9.1
 - MetaMask Mobile v7.3.0, on Android

**To Reproduce**
Note due to the use of the paymaster it is complicated to create an easily accessible environment where one could reproduce this error. I do have dev environment where this can be tested but it is not open to public.

**Expected behavior**
When the transaction pop-up appears in Metamask and you click submit the transaction should be submitted.

**Screenshots**
Here is a screen cap of the transaction pop-up from MM.
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/16868716/4f11574e-a1a1-46c6-80c8-8f30d069251f)

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
 - Device: Samsung S20 Ultra
 - OS: Android / Latest version [13]
 - Browser: Google Chrome
 - Version 114.05753.196

**Comment by equalogix** [comment]
I should also mention that  I was using the paymaster with WC without any issue when I was using WCv1, this is a bug/side-effect that was introduced with the switch to V2.

**Comment by ganchoradkov** [comment]
Please raise the issue with the Metamask team as WalletConnect is used to transmit the payload between dapp <-> wallet which per your comment succeeds. Their handling of the payload could potentially be problematic and we have no control over that part
