### ISSUE TITLE
Unable to use Paymaster on iOS with WalletConnect

### ISSUE THREAD

**Issue by equalogix** [WalletConnect/walletconnect-monorepo#3285]
**Describe the bug**
This issue may appear to be similar to another issue I created #3269 but I assure you it is not. This issue is specific to iOS.

According to the WC docs in order to be able to interact with a smart contract from an iOS device one must use `contract.populateTransaction` and `signer.sendUncheckedTransaction`. The problem is that when using `sendUncheckedTransaction` the transaction is sent but it ignores the inclusion of a paymaster and as result the gas fees must be paid from the senders wallet as opposed to by the paymaster.

At present paymaster technology is not widely used. But this technology is critical for the advancement and wide adoption of web3 as it has to ability to eliminate some of the major friction points that prevent onboarding of new non-crypto native users.

WC docs regarding iOS:
https://docs.walletconnect.com/2.0/ios/guides/mobile-linking#ios-app-link-constraints

Ethers.js docs for `sendUncheckedTransaction`
https://docs.ethers.io/v5/api/providers/jsonrpc-provider/#JsonRpcSigner-sendUncheckedTransaction

**Smartphone (please complete the following information):**
 - Device: iPhones / iPad any iOS device
 - OS: iOS
 - Browser Safari or any Safari based browser
 - Version latest

**Comment by glitch-txs** [comment]
This should be fixed in the latest versions, please update all packages and let us know if the issue still persists.
