### ISSUE TITLE
[bug] qrcodeModalOptions ignored in client

### ISSUE THREAD

**Issue by tms1337** [WalletConnect/walletconnect-monorepo#329]
I supply package.json and relevant code in the snippet below

https://gist.github.com/tms1337/daaf24e36ef19fe980bb55eff4655f1a

Even tho I specify 3 wallets, I still get all of them

![image](https://user-images.githubusercontent.com/8905560/89407196-a1b1db80-d71e-11ea-9661-6564eae683ca.png)

**Comment by slimjimrim** [comment]
bump

**Comment by finessevanes** [comment]
Hey @tms1337, @seungjoonrim are either one of you still experiencing this issue?
