### ISSUE TITLE
Unsupported ChainID error eventhough chain is in the chainlist

### ISSUE THREAD

**Issue by veyselozkahraman** [WalletConnect/walletconnect-monorepo#3299]
**Describe the bug**
Dexalot testnet(432201) and mainnet(432204) are added to the chainlist but I still see this error on browser.

```
description: "We don't support the chainId you provided: eip155:432201"
```

I am using MetaMask to connect to dApp with WalletConnect, does anyone has any idea what might be the problem?

You can see that dexalot subnet chains, both testnet and mainnet, are added to the chainlist.
https://docs.walletconnect.com/2.0/advanced/multichain/chain-list

This is how initialize the walletconnect provider
```
        const walletConnectProvider = await EthereumProvider.init({
            projectId: PROJECT_ID,
            chains: [43113, 432201],
            showQrModal: true,
        })

        // 43113 is avalanche fuji, 432201 dexalot subnet testnet
```

When I do not add the 432201 to the chains, connection does not fail and I can send transactions when I am connected with the avalanche fuji, but when I add the dexalot subnet testnet to the `chains` field, Connection fails with this
```
Error: Unsupported chains.
```

**Comment by ganchoradkov** [comment]
Hey @veyselozkahraman, Metamask accepts connections with only 1 required chain thats why the proposal is rejected.
Please move the other chains to `optionalChains: []` param and it would work

**Comment by veyselozkahraman** [comment]
Hello,

I have tried that, but unsupported chain error is still there
```
[{field: "chainId", description: "We don't support the chainId you provided: eip155:432201"}]
```

This is the request
```
https://rpc.walletconnect.com/v1/?chainId=eip155:432201&projectId=0e780d86141d85695a05e43d3d00403f
```

This is the payload
![Screen Shot 2023-07-28 at 18 23 23](https://github.com/WalletConnect/walletconnect-monorepo/assets/28571773/a7f85413-ec14-4c9b-989f-8bc2521e0eee)


Also, this is the request from a fuji transaction request and it works
```
https://rpc.walletconnect.com/v1/?chainId=eip155:43113&projectId=0e780d86141d85695a05e43d3d00403f
```
