### ISSUE TITLE
@walletconnect/ethereum-provider not working for metamask

### ISSUE THREAD

**Issue by leon-do** [WalletConnect/walletconnect-monorepo#3302]
**Describe the bug**
`@walletconnect/ethereum-provider` works for all wallets EXCEPT for MetaMask.

Metamask ❌
Argent ✅
MEW ✅
Rainbow ✅
Trust ✅

**SDK Version (if relevant)**
 - Client: NodeJS
 - WC Version 2.9.1
 - MetaMask Version 7.3.0

**To Reproduce**

```js
import { EthereumProvider } from "@walletconnect/ethereum-provider";

init();
async function init() {
  const provider = await EthereumProvider.init({
    projectId: process.env.WC_PROJECT_ID,
    chains: [1],
    showQrModal: false,
  });

  provider.on("display_uri", async (baseUri) => {
    console.log(baseUri);
  });

  provider.enable().then((accounts) => {
    console.log(accounts);
  });
}
```

Scan the QR code

Error

```bash
{"level":50,"time":1690562086828,"pid":71194,"hostname":"Leons-MacBook-Pro-16.local","err":{"type":"Error","message":"User rejected methods.","stack":"Error: User rejected methods.\n    at /Users/leon/Desktop/wc/node_modules/@walletconnect/ethereum-provider/dist/index.cjs.js:1:3717\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async i (/Users/leon/Desktop/wc/node_modules/@walletconnect/ethereum-provider/dist/index.cjs.js:1:3537)"},"msg":"User rejected methods."}
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: User rejected methods.
    at /Users/leon/Desktop/wc/node_modules/@walletconnect/ethereum-provider/dist/index.cjs.js:1:3717
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async i (/Users/leon/Desktop/wc/node_modules/@walletconnect/ethereum-provider/dist/index.cjs.js:1:3537)

Node.js v18.16.0
```

**Expected behavior**
Able to log `accounts`

**Screenshots**

**Desktop (please complete the following information):**
 - OSX
 - Server Side

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - Browser: Chrome

**Additional context**

**Comment by glitch-txs** [comment]
Your config seems right, are you able to reproduce this issue on labs? 
https://lab-walletconnect-modal.pages.dev/with-ethereum-provider

**Comment by chris13524** [comment]
@glitch-txs I tested your link with MetaMask and wasn't able to reproduce the issue. However, when running @leon-do's code above in Node.js I was able to reproduce the issue. Even when providing the same `methods` and `events` from the [lab](https://github.com/WalletConnect/modal/blob/81e1b5c4d05708a05f4a11ce2c67c02127a2c79c/laboratory/src/pages/with-ethereum-provider/index.tsx#L21):

```javascript
methods: ['eth_sendTransaction', 'personal_sign'],
events: ['connect', 'disconnect'],
```

**Comment by leon-do** [comment]
> @glitch-txs I tested your link with MetaMask and wasn't able to reproduce the issue. However, when running @leon-do's code above in Node.js I was able to reproduce the issue. Even when providing the same `methods` and `events` from the [lab](https://github.com/WalletConnect/modal/blob/81e1b5c4d05708a05f4a11ce2c67c02127a2c79c/laboratory/src/pages/with-ethereum-provider/index.tsx#L21):
> 
> ```js
> methods: ['eth_sendTransaction', 'personal_sign'],
> events: ['connect', 'disconnect'],
> ```

Thank you for looking into this. I got the same results. Is this something on walletconnect for metamask?

**Comment by glitch-txs** [comment]
@leon-do could you try adding the metadata in the init function?

```ts
  const provider = await EthereumProvider.init({
    projectId: process.env.WC_PROJECT_ID,
    chains: [1],
    showQrModal: false,
    metadata: {
      name: 'myApp',
      description: 'my app',
      url: 'https://mywebsite.com/',
      icons: [''],
    }
  });
```

**Comment by leon-do** [comment]
> ```ts
>     metadata: {
>       name: 'myApp',
>       description: 'my app',
>       url: 'https://mywebsite.com/',
>       icons: [''],
>     }
> ```

This did it @glitch-txs . Would be awesome to have this listed in the docs. Feel free to close!

**Comment by clawxmtp** [comment]
export const connectWalletConnect = async (dispatch, chain) => {

  
  const projectId = "ee3eb58830962303cfb40f35f42dc28fbc";

  // 1. Create a new EthereumProvider instance
  const providers = await EthereumProvider.init({
    projectId,
    chains: [324],
    methods: ["personal_sign", "eth_sendTransaction"],
    optionalMethods: ['eth_signTypedData', 'eth_signTypedData_v4', 'eth_sign'],
    showQrModal: true,
    qrModalOptions: {
      themeMode: "light",
    },
  });
    console.log("kasto k  xa", providers)
    await providers.enable();
    wallet = providers;
    

    provider = new ethers.providers.Web3Provider(providers, "any");
    console.log("omm ", provider)
    batchProvider = new Web3(provider);
    setWallet("walletconnect");
    return connectWallet(dispatch);
  
} can some one please explain this.Uncaught (in promise) Error: provider must implement eip-1193

**Comment by kreatorland** [comment]
can some one please explain this.Uncaught (in promise) Error: provider must implement eip-1193

**Comment by glitch-txs** [comment]
@kreatorland can you update to the latest version? 2.11.1

**Comment by lollobene** [comment]
Hi everyone, I jump here because I'm trying to use this provider to connect with metamask, but the modal is not showing metamsk at all. 
If go here https://lab-walletconnect-modal.pages.dev/with-ethereum-provider, this is the result I get

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/38067715/1cd6afed-f8f3-4459-8fd5-7daa690319d1)

**Comment by glitch-txs** [comment]
@lollobene you should use Web3Modal instead: https://docs.walletconnect.com/web3modal/about
