### ISSUE TITLE
TypeError this.events.getMaxListeners is not a function

### ISSUE THREAD

**Issue by alexwalchli** [WalletConnect/walletconnect-monorepo#3304]
**Describe the bug**
Intermittently our users were experiencing the error "TypeError this.events.getMaxListeners is not a function" which appears to originate from:

`… onrpc-http-connection@1.0.7/node_modules/@walletconnect/jsonrpc-http-connection/dist/esm/http.js in HttpConnection.register at line 74:1`

**SDK Version (if relevant)**
We are using WAGMI with Dynamic.xyz. While good to provide I think, based on the stack trace below, I don't think these libraries are involved in this issue.
 "@dynamic-labs/sdk-react": "^0.17.23",
 "@dynamic-labs/wagmi-connector": "^0.17.23",
 "@wagmi/core": "0.10.6",
 "@wagmi/core": "0.10.6",

**To Reproduce**
It's very intermittent but is stopping a user from executing a transaction, these are the steps:
1. User connects successfully via Dynamic.xyz using Wallet Connect connected to a Fireblocks wallet
2. User signs in with ethereum successfully via Dynamic.xyz
3. User attempts a transaction, gets the above error. However, a similar transaction we were able to get through. But the 2nd time around, even after disconnecting/reconnecting the Fireblocks web3 connection, refreshing the browser, and reconnecting, we get this error.

**Expected behavior**
This error does not occur and the user can transact with our contracts.

**Screenshots**
<img width="800" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/2604072/33b8ea38-eba4-4b2e-9135-9d270e874cd6">

**Desktop (please complete the following information):**
 - OS: Windows >= 10
 - Browser: Chrome 113.0.0

**Additional context**
Looks like this may have been an issue in the past https://github.com/WalletConnect/walletconnect-monorepo/issues/1799

**Comment by alexwalchli** [comment]
I am able to reproduce this error myself pretty easily when connecting to a Fireblocks wallet through Wallet Connect V2:
<img width="749" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/2604072/d8d92a0e-697f-4de8-addb-15f494f05211">

**Comment by dsshap** [comment]
+1

**Comment by alexwalchli** [comment]
I was able to resolve this by upgrading all my libraries. That said, while it doesn't seem to affect interacting with wallets, I am seeing https://github.com/WalletConnect/walletconnect-monorepo/issues/3334 from time to time.

Closing.
