### ISSUE TITLE
"@walletconnect/web3-subprovider" - Error in getWalletConnector after connecting

### ISSUE THREAD

**Issue by aleksa95** [WalletConnect/walletconnect-monorepo#331]
Hello, I have used the example from the projects description and am having an issue when trying to get accounts

```
import Web3 from "web3";
import ProviderEngine from "web3-provider-engine";
import WalletConnectSubprovider from "@walletconnect/web3-subprovider";
 
const engine = new ProviderEngine();
 
// Add other subproviders
engine.addProvider(...);
 
engine.addProvider(
  new WalletConnectSubprovider({
    bridge: "https://bridge.walletconnect.org" // Required
  })
);
 
engine.start();
 
const web3 = new Web3(engine);
```

After initializing everything, I call ```web3.eth.getAccounts()``` then the QR modal pops up, I have tried scanning it with the MM mobile wallet and the Trust wallet and after that this err comes up

```
Uncaught (in promise) TypeError: this.updateState is not a function
    at Object.eval [as callback] (index.js?6620:154)
    at eval (events.js?6e35:40)
    at Array.forEach (<anonymous>)
    at EventManager.trigger (events.js?6e35:34)
    at WalletConnect._handleSessionResponse (index.js?0a8b:673)
    at Object.eval [as callback] (index.js?0a8b:744)
    at eval (events.js?6e35:40)
    at Array.forEach (<anonymous>)
    at EventManager.trigger (events.js?6e35:34)
    at WalletConnect.eval (index.js?0a8b:727)
```

I have narrowed the issue down to the ```walletconnect-monorepo/packages/providers/web3-subprovider/src/index.ts``` file line 166.
I am not sure from where it should inherit ```updateState``` because it is not found anywhere in the repo or the "web3-provider-engine" and "web3" libraries  which are supposed to use this. Furthermore, ```this.emit("connect");``` is also undefined.

I have managed to get it to work by deleting lines 164 to 169, but just don't know if those lines are important or just outdated.

**Comment by sterlu** [comment]
Seems to be referencing updateState from the `@walletconnect/web3-provider` package: https://github.com/WalletConnect/walletconnect-monorepo/blob/next/packages/providers/web3-provider/src/index.ts#L368

EDIT: Also noticed a similar issue issue when connecting with a wallet, with the subprovider calling `this.emit`.

If you're not relying on the events being dispatched, I guess it's safe enough to ignore. I hacked around it by adding 
```js
WalletConnectSubprovider.prototype.updateState = () => {};
WalletConnectSubprovider.prototype.emit = () => {};
```

**Comment by finessevanes** [comment]
Hey @aleksa95 are you still experiencing this issue?
