### ISSUE TITLE
not getting metamask connected in android using wallet connect v2

### ISSUE THREAD

**Issue by SumiBisht** [WalletConnect/walletconnect-monorepo#3317]
Using the latest packages but not getting connected to meta mask in mobile and earlier it was getting connected but not anymore it opens the metamask app but no request on the app.
<img width="355" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/40060905/ea562e8e-9a8a-4792-8510-eee843af4d0e">
@glitch-txs

**Comment by glitch-txs** [comment]
Hi, could you provider a minimal reproducible example of the issue?
Also, are you able to connect on labs? 
https://lab-walletconnect-modal.pages.dev/with-ethereum-provider
