### ISSUE TITLE
clientMeta doesn't detect "meta" tags ("name" and "description")

### ISSUE THREAD

**Issue by remy115** [WalletConnect/walletconnect-monorepo#333]
`<meta name="name" content="some name here" />`
Walletconnect _clientMeta_ can't detect and use this _meta_ tag.

It keeps getting "name" _clientMeta_ prop from _title_ tag.
The same for "description", it can't detect "description" _meta_ tag and it's always empty string.

Walletconnect Version: 1.2.0
Browser: Chrome Version 84.0.4147.105 (Official Build) (64-bit)

**Comment by wliu6v** [comment]
Same problem , don't know how to solve it. 
I put the article title in <title> tag, but I want to use my site's name in WalletConnect. Don't know what I can do.

**Comment by finessevanes** [comment]
Hey @remy115, @wliu6v are either of you still experiencing this issue?
