### ISSUE TITLE
Add a chain: Rollux Testnet

### ISSUE THREAD

**Issue by DevElCuy** [WalletConnect/walletconnect-monorepo#3338]
1. JSON-RPC spec for Wallets (only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist). For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
ethereum-rpc

1. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
eip155 specs

1. namespaces:
eip155

1. chains:
Testnet: Rollux
ChainID: eip155:57000

1. RPC endpoints
Mainnet: Rollux Testnet
Endpoint: https://rpc-tanenbaum.rollux.com/

1. [SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type:
60

Additional context
Network Name: Rollux Tesnet
RPC URL: https://rpc-tanenbaum.rollux.com
ChainID: 57000
Symbol: TSYS
Block Explorer URL: https://rollux.tanenbaum.io/

**Comment by bkrem** [comment]
Thank you for your submission 🙏 

It has been added to https://cloud.walletconnect.com ✅
