### ISSUE TITLE
Safe.global WalletConnect connection failing

### ISSUE THREAD

**Issue by alexroan** [WalletConnect/walletconnect-monorepo#3346]
**Describe the bug**

Attempting to connect the Beanstalk app to Safe via Walletconnect is failing.

Browser console:
```
index.ts:82 WebSocket connection to 'wss://w.bridge.walletconnect.org/?env=browser&host=apps-portal.safe.global&protocol=wc&version=1' failed: 
value @ index.ts:82
```

**SDK Version (if relevant)**
 - Client: [e.g. JS, Swift, Kotlin]

**To Reproduce**
1. Go to [Beanstalk](https://app.bean.money/)
2. In Safe.global, open Safe WalletConnect app
3. Paste or use QR code from Beanstalk "Connect Wallet" (using WalletConnect), into the "QR Code or connection link" field.
4. Once loading has finished, nothing happens, error print in console

**Expected behavior**
The Safe wallet should connect to the Beanstalk app

**Screenshots**
Safe App:
![Screenshot 2023-08-02 at 12 09 34](https://github.com/WalletConnect/walletconnect-monorepo/assets/6523673/b6c00767-9ede-49f2-b11d-1518d8ede4b0)

![Screenshot 2023-08-02 at 12 12 51](https://github.com/WalletConnect/walletconnect-monorepo/assets/6523673/e88f8935-c6a8-4478-8c1a-fc1bd0a16c40)

**Desktop (please complete the following information):**
 - OS: Mac OS (M2 chip)
 - Browser: chrome
 - Version: 114.0.5735.248

**Additional context**

**Comment by ganchoradkov** [comment]
@alexroan, the connection is failing because Beanstalk is still on v1 which was sunset a month ago. Please raise the issue with them to upgrade to v2

**Comment by alexroan** [comment]
Thanks @ganchoradkov, being tracked here: https://github.com/BeanstalkFarms/Beanstalk/issues/580
