### ISSUE TITLE
westend asset hub and rococo asset hub chains aren't supported

### ISSUE THREAD

**Issue by VadimSaveljev** [WalletConnect/walletconnect-monorepo#3353]
I've tried to send these chains
```
  chainIds: [
    'polkadot:68d56f15f85d3136970ec16946040bc1', // polkadot asset hub
    'polkadot:48239ef607d7928874027a43a6768920', // kusama asset hub
    'polkadot:67f9723393ef76214df0118c34bbbd3d', // westend asset hub
    'polkadot:7c34d42fc815d392057c78b49f2755c7', // rococo asset hub
  ],
```
after scanning QR code with Nova Wallet app, on connection to the wallet window it said that
only polkadot asset hub and kusama asset hub are supported (and only reject button was available)
Is it possible to add support for westend asset hub and rococo asset hub?
Would help in development

**Comment by bkrem** [comment]
WalletConnect as a protocol is completely chain-agnostic has no influence over which chains are supported by a respective dapp/wallet.

Please contact the Nova Wallet team regarding further steps here.
