### ISSUE TITLE
add Scroll Sepolia network

### ISSUE THREAD

**Issue by dghelm** [WalletConnect/walletconnect-monorepo#3356]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
   ethereum-rpc
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   ethereum
3. **namespaces**:
  eip:155
4. **chains**:
   _\*known chains, where the primary key is a compound key composed of namespace + reference (e.g. ETH mainnet is eip155:1)._
   _Please provide labels for each chain (e.g. mainnet, testnet, devnet, ...)_
Scroll Sepolia Testnet: eip155:534351
5. **RPC endpoints**
https://sepolia-rpc.scroll.io/
_Please note that this URL and chain aren't live yet but will be soon._
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
 60

**Additional context**
Adds support for Scroll's upcoming testnet. It will be our LTS testnet that lives alongside Mainnet. Scroll Alpha Testnet (currently supported by WalletConnect) will be deprecated and brought offline after the Mainnet launch.

**Comment by bkrem** [comment]
Thank you for your submission 🙏 

It has been added to https://cloud.walletconnect.com ✅
