### ISSUE TITLE
WalletConnectProvider not working with Web3.js

### ISSUE THREAD

**Issue by hoonsubin** [WalletConnect/walletconnect-monorepo#336]
I was following the code written in here https://docs.walletconnect.org/quick-start/dapps/web3-provider
But it seems that the Web3 class cannot be initialized with the WalletConnectProvider class or any of its properties from what I can see.

```
Argument of type 'WalletConnectProvider' is not assignable to parameter of type 'provider'.
  Type 'WalletConnectProvider' is not assignable to type 'string'
```

I'm using `web3 ^1.2.11` and `@walletconnect/web3-provider ^1.2.1` on TypeScript.
Is the doc outdated or is there something that I am missing?

**Comment by crypto-yang** [comment]
Same

web3@1.3.0
@walletconnect/web3-provider@1.3.1

This code below is not working as suggested by https://docs.walletconnect.org/quick-start/dapps/web3-provider

```js
  const walletConnect = new WalletConnectProvider({
    infuraId: infuraToken // Required
  });

  await walletConnect.enable();

  setWeb3(walletConnect);
```

**Comment by miohtama** [comment]
Here is more:

https://github.com/ethereum/web3.js/issues/3790

**Comment by sanjuraj85** [comment]
Hello Expert, need your help, while installing "npm i @walletconnect/web3-provider" getting error :

npm WARN deprecated rpc-payload-id@1.0.0: Packaged deprecated in favor of @json-rpc-tools/utils
npm WARN deprecated safe-event-emitter@1.0.1: Renamed to @metamask/safe-event-emitter
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/ethereumjs/ethereumjs-abi.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

Can some one please helop?

**Comment by dzek69** [comment]
@sanjuraj85 it looks like you don't have `git` installed and some postinstall script tries to run it? just a wild guess

**Comment by MrToxy** [comment]
> I was following the code written in here https://docs.walletconnect.org/quick-start/dapps/web3-provider
> But it seems that the Web3 class cannot be initialized with the WalletConnectProvider class or any of its properties from what I can see.
> 
> ```
> Argument of type 'WalletConnectProvider' is not assignable to parameter of type 'provider'.
>   Type 'WalletConnectProvider' is not assignable to type 'string'
> ```
> 
> I'm using `web3 ^1.2.11` and `@walletconnect/web3-provider ^1.2.1` on TypeScript.
> Is the doc outdated or is there something that I am missing?

I'm having exactly the same issue.

`"web3": "^1.3.5"`
`"@walletconnect/web3-provider": "^1.4.1"`

```

**Comment by limcheekin** [comment]
I have the same issue with the following versions:
```
"web3": "^1.5.2",
"@walletconnect/web3-provider": "^1.6.4"
```

I found the following workaround might be helpful to someone having the issue in the future:
```typescript
import WalletConnectProvider from "@walletconnect/web3-provider"
import { JsonRpcPayload, JsonRpcResponse } from 'web3-core-helpers';
import { AbstractProvider } from 'web3-core/types'

export declare class WalletConnectWeb3Provider extends WalletConnectProvider implements AbstractProvider {
  sendAsync(payload: JsonRpcPayload, callback: (error: Error | null, result?: JsonRpcResponse) => void): void;
}

// then in your code
const provider = new WalletConnectProvider({
  infuraId: "[YOUR_INFURA_ID]",
});

await provider.enable()

const web3 = new Web3(provider as WalletConnectWeb3Provider)
```

Hope this help.

**Comment by finessevanes** [comment]
@hoonsubin, @crypto-yang, @limcheekin are either on of you still experiencing this issue?
