### ISSUE TITLE
Allow creating a Desktop Wallet listing without providing a native link

### ISSUE THREAD

**Issue by PeterBenc** [WalletConnect/walletconnect-monorepo#3378]
**Describe the bug**
Registering a new project as "Desktop wallets" fails if native link is not provided, even thou as web wallets, we do not have a native link, yet we are a desktop wallet. This previously worked and form allowed the native link to be empty.

**To Reproduce**
1. Try adding a new project listing, 
2. Choose a Desktop wallets
3. Try saving
4. It will fail and require you to add native link

**Expected behavior**
 - native link is not required

**Comment by Cali93** [comment]
Hey @PeterBenc, sorry for the late reply.
We recently added a Web Wallets category. You should be able to submit your listing by using that category as it doesn't require a native desktop link.
<img width="942" alt="Capture d’écran 2023-10-18 à 10 46 56" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/32299095/458072ef-234d-42bd-8135-837b39ad5195">
