### ISSUE TITLE
wallet Connect passes on sendTransaction instead of sendRawtransaction

### ISSUE THREAD

**Issue by ghost** [WalletConnect/walletconnect-monorepo#338]
![Screenshot_2020-08-28_at_09](https://user-images.githubusercontent.com/37011004/91544297-e8e25500-e8f5-11ea-8ff6-7098f6f9df60.png)

steps to reproduce the error:
ygov.finance
click stake
click wallet
click wallet connect
scan and confirm connect
click open (governance v2)
click stake tokens

**Comment by pedrouid** [comment]
Please update to v1.2.0 or greater to fix this
