### ISSUE TITLE
WalletConnect V2 Flutter documentation not available

### ISSUE THREAD

**Issue by Aastha9018** [WalletConnect/walletconnect-monorepo#3393]
### Discussed in https://github.com/orgs/WalletConnect/discussions/3392

<div type='discussions-op-text'>

<sup>Originally posted by **Aastha9018** August  8, 2023</sup>
Hey, I have tried really hard but there's no proper documentation for the flutter app integration with wallet Connect v2. Can you please help me with some of the links.
Also the documentation present on the official website is just screenshots of snippets which aren't really healpful and then when i try tp google some bugs that I'm facing, there's no material for that as well. Please help me.

LAstly can you help me to any documentation maybe flutter/react-native or any other where the event handling is metioned for `wallet_addEthereumChain`.</div>

**Comment by glitch-txs** [comment]
hey, let's follow up on there :)
