### ISSUE TITLE
Add opBNB Chain network

### ISSUE THREAD

**Issue by 0x0077** [WalletConnect/walletconnect-monorepo#3409]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC: https://opbnb-testnet-rpc.bnbchain.org/
2. namespaces: eip:155
3. chains: eip155:5611

BNB Chain L2 Network - opBNB
This is BNB Chain L2 Network

**Comment by JonathanConn** [comment]
Older dup issue, working on newer issue currently ( #3484 )
