### ISSUE TITLE
Passing eth_getBalance on methods or optionalMethods

### ISSUE THREAD

**Issue by hlopes-ledger** [WalletConnect/walletconnect-monorepo#3411]
**Describe the bug**

If we pass eth_getBalance on methods or optionalMethods to ethereum-provider's init(), the request to that method will not work. The only way it works is by not passing it at all, which is does not make much sense. Users have also reported the same problem with the eth_call method.

We've created a demo app to test the three scenarios: not passing it, passing it on methods and passing it on optionalMethods. These are the results that we get when using our Ledger Live app (mobile or desktop), you can see which parameters are being passed in the `init options are` line on the browser console when connecting

1. if we don't pass eth_getBalance, neither in methods or optionalMethods, it works, the request is made and returns a response
2. if we pass eth_getBalance on methods, it seems the request is made, at least we don't get any error, but no response is returned
3. if we pass eth_getBalance on optionalMethods, we get the error `'Missing or invalid. request() method: eth_getBalance'`

When connecting using the Trust wallet mobile app scenario 3 behaves like scenario 2, so I don't know how much this depends on the wallet implementation.

**SDK Version (if relevant)**

 - Client: JS
 - ethereum-provider version 2.9.2

**To Reproduce**

1. Go to https://direct-integration-hlopes-ledger.vercel.app/ and open the browser console
2. Click on the 'WalletConnect gB in optionalMethods' button, which passes eth_getBalance to ethereum-provider's init() in the optionalMethods property, you can see it on `init options are` on the browser console
3. Accept the connection in the wallet
4. If using Ledger Live you'll see `'Missing or invalid. request() method: eth_getBalance'`, if you're using for e.g. Trust mobile app it shows no error but you get no balance back

**Expected behavior**

To get a balance back when you call eth_getBalance and that method is passed to the ethereum-provider's init() function in either the methods or optionalMethods property.

Maybe to get the error if eth_getBalance is not passed in either methods or optionalMethods, but not when it is.

**Screenshots**

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/106091551/784bfc5a-4e5f-4c81-9a36-21d298127805)

**Comment by ganchoradkov** [comment]
@hlopes-ledger hey, in optionalMethods (or even in required) you can set any method you wish.
It's up to the wallet to approve what they support.  

I've tested your dapp with our [example wallet](https://react-wallet.walletconnect.com/walletconnect) & I'm able to receive the `get_balance` request
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/43912948/b7130c4f-5ef9-432b-bfe5-5c498efafafb)

I guess Trust Wallet doesn't handle this method, hence the no response. 
For Ledger Live, they have to approve this method to be able to receive requests for it

Closing as the protocol sends the request correctly as expected. It's up to wallets to decide which and how to handle different methods.
