### ISSUE TITLE
Safe Wallet compatibility issues with the latest WalletConnect v2 upgrade

### ISSUE THREAD

**Issue by bl4ckh401** [WalletConnect/walletconnect-monorepo#3436]
### Discussed in https://github.com/orgs/WalletConnect/discussions/3320 Any progress yet? This issue was opened 2 weeks ago but no response.

<div type='discussions-op-text'>

<sup>Originally posted by **jejebl** July 31, 2023</sup>
I tried to connect my Safe Wallet to my DApp via the WalletConnect QR Code but I got this error:
"We were unable to create a connection due to compatibility issues with the latest WalletConnect v2 upgrade. We are actively working with the WalletConnect team and the dApps to get these issues resolved. Use Safe Apps instead wherever possible."
Does anyone know how to help me?</div>

**Comment by glitch-txs** [comment]
Hi we're currently working on this, we don't have an ETA but a fix is coming soon, sorry for the incovenients in the meanwhile.

**Comment by ptqa** [comment]
I have the same issue, but what is interesting I only have it on Optimism/Arbitrum networks. It works fine on Ethereum main net.

**Comment by philostler** [comment]
Seeing Safe Wallet support re-enabled is a priority on my list atm. Is there a ETA for this being fixed? Many thanks

**Comment by steoniy** [comment]
Any update? Having same issue for about a week

**Comment by bl4ckh401** [comment]
Any updates yet? I have tokens in the Safe but I can't connect to any other dapp. When might this be ready?

**Comment by Nuc1earDragon** [comment]
is there are some news?
I still can't connect Safe to Wallet Connect =(

**Comment by fabrice-quadrata** [comment]
+1 - adding for visibility

**Comment by glitch-txs** [comment]
We're working on this, expect a full fix soon

**Comment by cristpereirag** [comment]
Any updates? I'm experiencing the same issue and need to use my Safe Wallet with Uniswap on Celo urgently!

**Comment by gogoneriel** [comment]
any news ?i have this problem when connecting on uniswap but sushi swap works fine, someone knows what is happening ?

**Comment by PikWikHV** [comment]
Is there any update to this, its been a month since we could connect our wallet to Camelot to get a distribution

**Comment by maKarolis** [comment]
ETC?

**Comment by justanhy** [comment]
+1 - facing this bug on Arbitrum. Works fine on Ethereum

**Comment by chad-js** [comment]
+1 on this, seeing this error as well on Arbitrum. Is there any suggested work around atm for safe users?

**Comment by justanhy** [comment]
Contact the dApp support to check if they have an implementation with Safe's SDK - if so you can add the dApp as a custom Safe app as a temporary work around this issue for now. 

This works with radiant capital which is the dApp I was having issues with.

**Comment by glitch-txs** [comment]
Hi everyone, this took more than expected as some wallets weren't supporting this configuration but we've finally fishined the roadmap, we are encouraging both Wallet and Dapps to support this new configuration that's UX frinedly for smart contract wallets. Please follow the docs below. Thanks!

https://docs.walletconnect.com/advanced/migration-from-v1.x/namespaces 

Closing...!
