### ISSUE TITLE
Deeplinks are opened when an application is connected using the connection link

### ISSUE THREAD

**Issue by Sparragus** [WalletConnect/walletconnect-monorepo#3437]
**Describe the bug**
When a user selects an application from the app catalog, a value is set in local storage for `WALLETCONNECT_DEEPLINK_CHOICE`. This value is checked whenever there is a request. If it exists, then the request is routed through that application. See https://github.com/WalletConnect/walletconnect-monorepo/blob/fa8a19afe62ae0cd167792b2bd1e7075f19a7d30/packages/sign-client/src/controllers/engine.ts#L350-L354

If you disconnect and then reconnect using the connection link (the one you copy and paste in another app), any subsequent requests will be sent to two destinations: the app connected through the connection link and the external application referenced in the deeplink.

Although it doesn't prevent the user from sending the request through the connected app, it is definitely an inconvenience: a browser dialog will open asking the user to:

<img width="597" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/80982/be4c3417-3a7d-4af6-9a21-71f8aded04a4">

It's not a big deal to dismiss this once. However, this becomes very bothersome when there are multiple call requests, before a transaction is actually sent. For each call, the same dialog will open. For the transaction, too.

**To Reproduce**
1. Go to https://3fsjnm.csb.app/ (Source code: https://codesandbox.io/s/confident-pike-3fsjnm?file=/src/App.tsx)
2. Click on the connect button
3. Select an app from the app catalog. Ledger, for example.
4. Dismiss the prompt dialog. (Click Cancel)
5. Click the Back arrow
6. Click the copy connection link button
7. Paste in the the dapp (I used a Safe Wallet)
8. Click the Send Transaction button (it sends 0 value to the connected address. You don't need to execute the transaction. Only valid chains are Goerli and Sepolia. Read the source code for details)
9. It will open the "Open Ledger Live.app?" confirmation dialog.
10. It will also submit the tx to the connected dapp.

**Expected behavior**
Because the connection was made using the link, the requests should only be routed through the connected app. It should not attempt to open any external application.

**Screenshots**

https://github.com/WalletConnect/walletconnect-monorepo/assets/80982/6df3dbe3-fcf3-4d0e-9f03-4983572733dc

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 115.0.5790.170

**Additional context**
Happy to help debug and fix this. Will just need some guidance.

**Comment by glitch-txs** [comment]
This should be fixed in the latest versions, please update all packages and let us know if the issue still persists.
