### ISSUE TITLE
web3modal integrates with wagmi's ethers adapter and changes web3's ethers

### ISSUE THREAD

**Issue by QianDuoDuo-web** [WalletConnect/walletconnect-monorepo#3467]
### Discussed in https://github.com/orgs/WalletConnect/discussions/3278

<div type='discussions-op-text'>

<sup>Originally posted by **QianDuoDuo-web** July 26, 2023</sup>
web3modal integrates with wagmi's ethers adapter and changes web3's ethers
Work needs, you need to provide code snippets to help</div>

**Comment by glitch-txs** [comment]
Hi, we'll add support for web3js on web3modal v3 :)
