### ISSUE TITLE
Can't get valid signatures for signMessage for web3-provider

### ISSUE THREAD

**Issue by Voronchuk** [WalletConnect/walletconnect-monorepo#347]
I can't get a verifiable signature when I use web3 provider like `ethers`, direct usage of connector works fine.

This works (with direct connector usage): https://codesandbox.io/s/unruffled-benz-9ubn6?file=/src/App.vue

This doesn't work: https://codesandbox.io/s/gallant-banach-z7svg?file=/src/App.vue the same code works for direct MetaMask usage as a browser extension.

I was also testing with wrappers like: 

```
const rawMessageLength = new Blob([rawMessage]).size
let message = ethers.utils.toUtf8Bytes("\x19Ethereum Signed Message:\n" + rawMessageLength + rawMessage)
message = ethers.utils.keccak256(message)
```

They don't help as well.

This topic was also discussed here: https://stackoverflow.com/questions/63793873/sign-and-verifiy-message-on-ethereum-using-wallet-connect-not-working/63817084#63817084

**Comment by miohtama** [comment]
As this in an issue, do you propose a solution?

**Comment by Voronchuk** [comment]
@miohtama currently I use the following hack:

```
var rawMessage = "Hello World";
var rawMessageLength = new Blob([rawMessage]).size
var message = ethers.utils.toUtf8Bytes("\x19Ethereum Signed Message:\n" + rawMessageLength + rawMessage)
message = ethers.utils.keccak256(message)
var params = [
    await this.signer.getAddress(),
    message
]
this.signature = await this.wc.connector.signMessage(params);
this.verified = ethers.utils.verifyMessage(rawMessage, this.signature);
```

Do you wish me to make a PR with a fix for that?

**Comment by miohtama** [comment]
It would be awesome.

**Comment by pacwoodson** [comment]
Same issue here. Signing with metamask works and from mobile wallet through wallet connect resolves to wrong address.

**Comment by pacwoodson** [comment]
UP as this breaks login with WalletConnect for apps that needs signature. @pedrouid 

> @miohtama currently I use the following hack:
> 
> ```
> var rawMessage = "Hello World";
> var rawMessageLength = new Blob([rawMessage]).size
> var message = ethers.utils.toUtf8Bytes("\x19Ethereum Signed Message:\n" + rawMessageLength + rawMessage)
> message = ethers.utils.keccak256(message)
> var params = [
>     await this.signer.getAddress(),
>     message
> ]
> this.signature = await this.wc.connector.signMessage(params);
> this.verified = ethers.utils.verifyMessage(rawMessage, this.signature);
> ```
> 
> Do you wish me to make a PR with a fix for that?

@Voronchuk can you explain a little bit what you are doing here, where the problem is coming from and how this solves the issue ?

Do we need to call specifically `this.wc.connector.signMessage`, or we can call the usual ethers provider `signMessage` with something like your encoding ?

**Comment by Voronchuk** [comment]
@pakokrew this code is very simple, it prepares the message for signing according to Ethereum rules. Then we use the current WalletConnect connector (ethers/web3) to sign the message, then I use the same library (ethers.js in my example) to verify the signature.

I'll try to make a proper PR to fix this on weekend.

**Comment by pacwoodson** [comment]
> @pakokrew this code is very simple, it prepares the message for signing according to Ethereum rules. Then we use the current WalletConnect connector (ethers/web3) to sign the message, then I use the same library (ethers.js in my example) to verify the signature.
> 
> I'll try to make a proper PR to fix this on weekend.

Alright, but I wanted to know specifically what is causing trouble when signing through walletconnect and how this snippet solves the problem. 
Waiting for the PR then :)

**Comment by Voronchuk** [comment]
@pakokrew I don't have a fix in form of PR, but here is a quick solution

```
const provider = new ethers.providers.Web3Provider(wcProvider)
        const signer = provider.getSigner(address)

        const rawMessageLength = new Blob([rawMessage]).size
        let message = ethers.utils.toUtf8Bytes("\x19Ethereum Signed Message:\n" + rawMessageLength + rawMessage)
        message = ethers.utils.keccak256(message)

        return signer.signMessage(ethers.utils.arrayify(message))
```

The core of the issue is on ethers `JsonRpcProvider` which hexlify the message, even if it's hex already, arrayify fixes this double conversion.

**Comment by Voronchuk** [comment]
Will putting this business logic to `processMessage` of WC's Web3Provider be a proper solution? 

As a safer solution for backward compatibility, I would just add an utility function like:

```
const prepareEthersPayloadForSigning = (message) => {
    const rawMessageLength = new Blob([rawMessage]).size
    let message = ethers.utils.toUtf8Bytes("\x19Ethereum Signed Message:\n" + rawMessageLength + rawMessage)
    message = ethers.utils.keccak256(message)
    return ethers.utils.arrayify(message)
}
```

And then call it like: `signer.signMessage(utils.prepareEthersPayloadForSigning(message))`

**Comment by pacwoodson** [comment]
Thank you very much @Voronchuk for these details, I'll try this out !

However, with this, will signature will continue to work with other providers than WalletConnect ?

**Comment by pacwoodson** [comment]
I confirm that breaks signature for other providers

**Comment by pacwoodson** [comment]
Here's my workaround that works for window.ethereum and wallet connect, with ethers:

```ts
async function signMessage(provider: ethers.providers.Web3Provider, rawMessage: string) {
  if(provider.provider instanceof WalletConnectProvider) {
    const rawMessageLength = new Blob([rawMessage]).size
    const message = ethers.utils.toUtf8Bytes("\x19Ethereum Signed Message:\n" + rawMessageLength + rawMessage)
    const signer = provider.getSigner();
    const address = await signer.getAddress();
    const keccakMessage = ethers.utils.keccak256(message);

    const wc = provider.provider as WalletConnectProvider;
    const signature = await wc.connector.signMessage([
      address.toLowerCase(),
      keccakMessage,
    ]);
    return signature;
  } else {
    const signer = provider.getSigner();
    return await signer.signMessage(rawMessage);
  }
}
```

**Comment by Voronchuk** [comment]
Looks good to me

**Comment by dysbulic** [comment]
I think this workaround may no longer be viable. I've been playing with a [CodeSandbox](https://codesandbox.io/s/ethers-sig-verification-6191y) that tests different methods for creating a signature, and I'm getting decidedly mixed results.

This is a screenshot from running against Argent using WalletConnect. The addresses in green should match the signer, and the ones in red shouldn't. For Argent none of the addresses match the signer.

<img src="https://user-images.githubusercontent.com/181523/111042794-1bc0e600-840d-11eb-805e-2ebb8a3fcaea.png" width="300"/>

I ran the same script using WalletConnect and Trust Wallet. In this case `web3.eth.sign` of the hash of the message prefaced with the "Signed Message" header worked, and `web3.eth.private.sign` did as well, but `signer.signMessage` did not.

<img src="https://user-images.githubusercontent.com/181523/111042857-680c2600-840d-11eb-9be2-af41178fdc7a.png" width="300"/>

For reasons I don't understand Metamask is hanging on `modalProvider.request` *after* it requests the signature. It happens on both mobile and desktop. It was completing all the test successfully, and now it won't run…

Opera dies on `web3Modal.connect()`. Brave won't even call `load` when clicking the button to start.

All in all, it seems as though each wallet has it's own vagaries that have to be explored and mapped out.

**Comment by pacwoodson** [comment]
> All in all, it seems as though each wallet has it's own vagaries that have to be explored and mapped out.

I spent a fair amount of time trying to understand what's going on with signatures and wallet, and the response is that it's just a jungle. 

What I found:
- One should not use ethers.js(v5) for signing messages, it doesn't work in lot of situations.
- Metamask receives parameters in reverse order as others wallets
- Signing messages with Contract wallets (as Argent) has to be handled differently and [spec is still draft](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1271.md)

Check this: 
https://github.com/mooni/mooni/blob/master/app/src/lib/eth.ts#L130
I don't support contract wallets

**Comment by StillFantastic** [comment]
@pakokrew I also ran into this situation, do you know whether the `sign` method in `web3.js` works?

**Comment by ming436534** [comment]
> Here's my workaround that works for window.ethereum and wallet connect, with ethers:
> 
> ```ts
> async function signMessage(provider: ethers.providers.Web3Provider, rawMessage: string) {
>   if(provider.provider instanceof WalletConnectProvider) {
>     const rawMessageLength = new Blob([rawMessage]).size
>     const message = ethers.utils.toUtf8Bytes("\x19Ethereum Signed Message:\n" + rawMessageLength + rawMessage)
>     const signer = provider.getSigner();
>     const address = await signer.getAddress();
>     const keccakMessage = ethers.utils.keccak256(message);
> 
>     const wc = provider.provider as WalletConnectProvider;
>     const signature = await wc.connector.signMessage([
>       address.toLowerCase(),
>       keccakMessage,
>     ]);
>     return signature;
>   } else {
>     const signer = provider.getSigner();
>     return await signer.signMessage(rawMessage);
>   }
> }
> ```
@pakokrew 
I tried this method, can sign the message, and verify the result, but the message showed in the confirmation dialog is unreadable(hex string). Is there a way to display the message in readable form? Thank you.

**Comment by Xaber20110202** [comment]
The method below you can try, and you can see the full raw message (not hex) on the client side

```ts
import { Signer, utils, providers } from 'ethers'

const signMessageAsync = async (signer: Signer, address: string, message: string): Promise<string> => {
  const messageBytes = utils.toUtf8Bytes(message)
  if (signer instanceof providers.JsonRpcSigner) {
    try {
      const signature = await signer.provider.send('personal_sign', [
        utils.hexlify(messageBytes),
        address.toLowerCase()
      ])
      return signature
    } catch (e) {
      if (e.message.includes('personal_sign')) {
        return await signer.signMessage(messageBytes)
      }
      throw e
    }
  } else {
    return await signer.signMessage(messageBytes)
  }
}
```


#### reference from [zkSync](https://github.com/matter-labs/zksync)

1. change message string to Utf8Bytes
	1. [zkSync utils getSignedBytesFromMessage call](https://github.com/matter-labs/zksync/blob/812dc00da085d894547b966288b8130b91c746f6/sdk/zksync.js/src/signer.ts#L333)
	2. [zkSync utils getSignedBytesFromMessage](https://github.com/matter-labs/zksync/blob/812dc00da085d894547b966288b8130b91c746f6/sdk/zksync.js/src/utils.ts#L449)
2. use provider to send personal_sign call
	1. [zkSync utils signMessagePersonalAPI call](https://github.com/matter-labs/zksync/blob/812dc00da085d894547b966288b8130b91c746f6/sdk/zksync.js/src/signer.ts#L334)
	2. [zkSync utils signMessagePersonalAPI](https://github.com/matter-labs/zksync/blob/812dc00da085d894547b966288b8130b91c746f6/sdk/zksync.js/src/utils.ts#L462)

**Comment by sambacha** [comment]
```js
            // For signing the message you use to have to restore proper behavior if using MetaMask
            // ethers will change eth_sign to personal_sign if it detects metamask (this is no longer the case)
            // https://github.com/ethers-io/ethers.js/blob/2a7dbf05718e29e550f7a208d35a095547b9ccc2/packages/providers/src.ts/web3-provider.ts#L33
            if (isMetamask) library.provider.isMetaMask = true

            const signer = await library.getSigner().getAddress()
            const signedPayload = await library.getSigner().signMessage(id(body))

            // Restore back behavior
            if (isMetamask) library.provider.isMetaMask = false
```

now its just using `_legacySignMessage` see https://github.com/ethers-io/ethers.js/commit/8947fd405e3aea07f6db958d89a3ad39abe3a25a

This is true now for any provider, not just Metamask, so this should affect walletconnect as well

**Comment by carmen0208** [comment]
I upgraded to current version: `1.7.5` and the issue was resolved, **signMessage** works for me.

**Comment by finessevanes** [comment]
Hey @Voronchuk are you still experiencing this issue?
