### ISSUE TITLE
Addition of a try catch block needed here or at least how to handle "Pairing already exists" error

### ISSUE THREAD

**Issue by michaelessiet** [WalletConnect/walletconnect-monorepo#3478]
https://github.com/WalletConnect/walletconnect-monorepo/blob/7aec2dd30a52e1ee63cdf2a43b260bcc0a2607a7/packages/web3wallet/src/controllers/engine.ts#L32C1-L32C1

**Comment by Arthurgallina1** [comment]
Any updates on this issue?
