### ISSUE TITLE
Add opBNB Mainnet and opBNB Testnet

### ISSUE THREAD

**Issue by 0x0077** [WalletConnect/walletconnect-monorepo#3484]
Adding a new chain to the Explorer
To get a new chain added to the Explorer, you will need to submit the following:

JSON-RPC spec for Wallets (only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist). For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
ethereum-rpc compatible

Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
eip155 specs

namespaces:
eip155

chains:
opBNB Mainnet: eip155: 204
opBNB Testnet: eip155: 5611

RPC endpoints
*list of common/canonical RPC endpoints for the chain(s)
Mainnet: https://opbnb-mainnet-rpc.bnbchain.org/
Testnet: https://opbnb-testnet-rpc.bnbchain.org/

[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type:
60

Additional context
Add any other context here.

Please note:

Registering a chain with the Explorer does not impact or improve the ability for wallets and dapps to support your chain. It is simply a way for users to discover wallets and dapps that support your chain by:

Browsing the [Chains List](https://github.com/WalletConnect/walletconnect-monorepo/issues/chain-list.md)
Filtering results programmatically via the [Explorer API](https://github.com/WalletConnect/cloud/explorer.md)
It is still up to wallets and dapps to provide concrete support for your chain once it is listed as part of the Explorer.

 I have read and understood the above clarification

**Comment by JonathanConn** [comment]
Closes #3409
