### ISSUE TITLE
wc@2:core:0.3//history breaks local storage

### ISSUE THREAD

**Issue by mqklin** [WalletConnect/walletconnect-monorepo#3513]
With every connection `wc@2:core:0.3//history` localStorage item grows, finally localStorage becomes unusable because of "exceeded the quota" error.
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/9456433/7fbb733b-d900-4ca0-86eb-3fdca5cb8100)

**Comment by mqklin** [comment]
Same for `pairing` item, but it grows not so fast. 
Searching through github, found this: https://github.com/altaga/Polkasend-APAC-Hackathon/blob/4127289ebf6250a1522430543dd0bf795833376e/WALLET_RN/src/screens/setups.js#L303
Maybe there are others items with the same problem, as that code cleans lots of storage items.

**Comment by ganchoradkov** [comment]
Hey, if you're creating new pairings, as indicated by your second comment, it's normal and expected for `history` & `pairings` datastores to grow. Pairings, if not responded to, expire after 5mins so they're self-cleaning. History, on the other hand, is used as a store for pending requests and is cleared when a request is responded to or expires.

**Comment by mqklin** [comment]
Thank you for the answer. IDK why it grows so fast. I use web3modal. Maybe problem is on their side. Maybe on MetaMask side.
