### ISSUE TITLE
ERC4337 Smart Wallet connection with DApps

### ISSUE THREAD

**Issue by lienhage** [WalletConnect/walletconnect-monorepo#3524]
We have faced an issue when using WalletConnect with a Smart Contract Wallet based on ERC4337 Account Abstraction.

When we swap some MATIC for USDT in Uniswap (DApp) we are sending the UserOperation with transaction data to the Bundler. The transaction is executed by the EntryPoint contract and the Smart Contract calls related to swap are executed as internal transactions.

When we submit the transactionHash returned by the UserOperation to UniSwap, it failed to validate the transactionHash by displaying a "Swap Failed" message.

If we do this transaction from an EOA wallet like Metamask there won't be any issues and UniSwap is able to validate the transactionHash

We would like to know what can we do in this scenario to submit the correct transactionHash for Uniswap (DApp)

**Comment by glitch-txs** [comment]
Hi, is this still an existing issue? are you able to connect the wallet successfully?

**Comment by Jircs1** [comment]
I say do it!

**Comment by arein** [comment]
Which WalletConnect product are you using?

**Comment by MetaMask-Support-io** [comment]
> We have faced an issue when using WalletConnect with a Smart Contract Wallet based on ERC4337 Account Abstraction.
> 
> When we swap some MATIC for USDT in Uniswap (DApp) we are sending the UserOperation with transaction data to the Bundler. The transaction is executed by the EntryPoint contract and the Smart Contract calls related to swap are executed as internal transactions.
> 
> When we submit the transactionHash returned by the UserOperation to UniSwap, it failed to validate the transactionHash by displaying a "Swap Failed" message.
> 
> If we do this transaction from an EOA wallet like Metamask there won't be any issues and UniSwap is able to validate the transactionHash
> 
> We would like to know what can we do in this scenario to submit the correct transactionHash for Uniswap (DApp)

NEED HELP @lienhage ??  Send us a message about you issues with MetaMask or contact us via email for quick responsed 
(meta.mask.help@mail.com) “Start a Conversation” 

We never DM. NEVER share your Secret Recovery Phrase with any site or person. Verify links are legitimate. Contact us now
( meta.mask.help@mail.com)
