### ISSUE TITLE
Cordova compatibility

### ISSUE THREAD

**Issue by ASHKARAN** [WalletConnect/walletconnect-monorepo#3525]
I'm using WalletConnect in my Quasar application, and everything works fine. 
However, yesterday, I exported my app to Android using Cordova. 
Everything seems to be okay, but I'm facing an issue with connecting my wallet.
When I tap on the "Connect Wallet" button, the WalletConnect dialog prompts me to select a wallet.
However, after tapping "Select Wallet," nothing happens.
In the browser, after this step, all possible wallets prompt, and users can choose their desired wallet. But in the Cordova export, nothing happens.

![photo_2023-08-23_15-05-28](https://github.com/WalletConnect/walletconnect-monorepo/assets/10007827/1da88795-f3df-4026-89b0-089b07171172)

**Comment by ganchoradkov** [comment]
Hey @ASHKARAN, are there any error logs that we could use to isolate the issue?

**Comment by ASHKARAN** [comment]
unfortunately no, there are no errors, simply just select wallet button does not work

**Comment by glitch-txs** [comment]
This should be fixed in the latest versions, please update all packages and let us know if the issue still persists.

**Comment by ASHKARAN** [comment]
i updated my source code to the latest version of wallet connect
but the problem still exists...
