### ISSUE TITLE
Mobile App - After sign user not redirecting back to the app

### ISSUE THREAD

**Issue by dijinslate** [WalletConnect/walletconnect-monorepo#3543]
npm `@walletconnect/sign-client`

React native app. The issue happening in both iOS & Android. Started seeing this issue with latest MetaMask app update

1. The sign method ( personal_sign ) triggers the sign popup inside metamask. After confirming, the redirection back to our App is not happening. This was working fine, but with the recent Metamask update, it's breaking.
But getting a successful callback. If the user switches the app manually everything works fine. But auto redirection after the sign not happening.

**Code**
```
const signMessage = message => {
    signClient
        .request({
            topic: signClientTopic,
            chainId: constants.web3_wallets.chain,
            request: {
                method: 'personal_sign',
                params: [message, walletId]
            }
        })
        .then(signature => {
            onSignSuccess(signature)
        })
        .catch(e => {
            onSignFailure(e)
        })

    Linking.openURL(wallet.url_prefix)
        .then(() => { })
        .catch(() => { })
}
```

**System Info**
```
System:
    OS: macOS 13.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 35.09 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.7.2 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2023.07.24.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/dijinrajh/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 25, 28, 29, 30, 31, 33
      Build Tools: 25.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-23 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-32 | Google APIs Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.6 => 0.68.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by ignaciosantise** [comment]
hey @dijinslate can you provide a public example repo to reproduce the error? It's probably an issue on Metamask side, as they handle the redirection internally.

Also, does the redirection works in other wallets?

**Comment by dijinslate** [comment]
@ignaciosantise It is working on other wallets.
In Metamask also, it was working fine, I think it's breaking from the latest Metamask app update.

**Comment by glitch-txs** [comment]
Hi, make sure to update all WalletConnect dependencies as well as MetaMask wallet. Let's us know if this issue still persists, closing for now, thanks!

**Comment by damdafayton** [comment]
Same issue persists for me:
"@web3modal/wagmi-react-native": "^1.2.0"
"wagmi": "1.4.13"
"@walletconnect/react-native-compat": "^2.11.2"
MetaMask iOS: v7.16.0(1265)

**Comment by glitch-txs** [comment]
this doesn't work on iOS 17 please read: https://docs.walletconnect.com/web3wallet/mobileLinking#installation-example
