### ISSUE TITLE
Cannot create a new project in Wallet Connect, I receive an error. 

### ISSUE THREAD

**Issue by 1brahimsaid** [WalletConnect/walletconnect-monorepo#3559]
**Describe the bug**
Cannot create a new project in Wallet Connect. Receive this error - ```new row violates row-level security policy for table``` 

Check your discord everyone is dealing with this!

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/86809275/0d67f0fa-b8c8-4b93-a7b9-f1dd7760ff5e)

**To Reproduce**
1. Go to 'https://cloud.walletconnect.com/'
2. Click on New project.
3. Choose title.

**Expected behavior**
Should just create a project and provide an ID.

**Screenshots**
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/86809275/64a5a4a2-447b-4517-8cad-23f041ff8a26)
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/86809275/3daa1b6d-df8b-4034-a41f-4424a06558ba)

**Desktop:**
 - Browser chrome

**Comment by ByteHunterTeam** [comment]
------
plz fix it!!!

**Comment by glitch-txs** [comment]
Please try again, should be fixed
