### ISSUE TITLE
Universal Provider is not initializing

### ISSUE THREAD

**Issue by devon-n** [WalletConnect/walletconnect-monorepo#3575]
**Describe the bug**
getBlockchainContract() uses the provider to get a contract for the user to interact with
If the user connects with Wallet Connect:
We connect the user with sign client
Try to pair universal provider with their instance (Using pairingTopic) to use with ethers
The code below UniversalProvider.init() does not run

**SDK Version (if relevant)**
 - React
 - UniversalProvider 2.9.2
 - SignClient 2.10.0 (Works Perfectly)

**To Reproduce**
Connect wallet through wallet connect SignClient
Reload page so universal provider is used with ethers

**Expected behavior**
UniversalProvider should initialise and the code below where it initialises should run

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS + Linux Mint
 -  Chrome

**Smartphone (please complete the following information):**
All devices

**Additional context**
```

async function getProvider() {

    let provider = window.ethereum

    if (isMetaMaskProvider()) {
        //Make sure to get metamask provider
        if (window.ethereum?.providers?.length) {
            provider = window.ethereum.providers.find((provider) => provider.isMetaMask);
        }
    } else if (isWalletConnectProvider()) {
        provider = await UniversalProvider.init({
            projectId: process.env.REACT_APP_WALLET_CONNECT_PROJECT_ID,
            relayUrl: 'wss://relay.walletconnect.com',
            logger: 'info',
            namespaces: {
                eip155: {
                    methods: ['personal_sign'],
                    chains: [chainId],
                    events: ['chainChanged', 'accountsChanged']
                }
            }
        });
        await provider.connect({
            topic: walletContext.walletProvider.split('/')[2],
            namespaces: {
                eip155: {
                    methods: ['personal_sign'],
                    chains: [chainId],
                    events: ['chainChanged', 'accountsChanged']
                }
            }
        })
        await provider.enable();
        provider.on("session_delete", ({ id, topic }) => {
            walletContext.clearPgWallet()
        });
    } else if (isCoinBaseWalletProvider()) {
        provider = cbEthereum;
    }

    return provider;
}


export const getBlockchainContract = async (contractAddress, abi) => {
    try {
        let provider = await getProvider();

        let prov = new ethers.providers.Web3Provider(provider);

        let sign = prov.getSigner();

        return new ethers.Contract(contractAddress, abi, sign);
    } catch (err) {
        console.error("Blockchain Contract error: " + err);
    }
}
```

Update: I haven't changed anything with the code and now the wallet connect is initializing but it is not running the next line .connect()

Update 2: If I comment out provider.connect() and provider.enable() and interact with a contract it sends a web3 request but fails with 'Cannot read properties of undefined (reading 'includes')' 
<img width="755" alt="Screen Shot 2023-08-31 at 4 50 56 pm" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/65629705/cefd15f6-d995-4c16-8d8f-096c88754a47">

Update 3: I updated the package to 2.10.0 and now I get this error with the above commented out as well
<img width="759" alt="Screen Shot 2023-08-31 at 4 59 51 pm" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/65629705/0048eb6d-03e3-47a7-93a1-153e38a9efb7">

**Comment by glitch-txs** [comment]
Hi, thanks for reporting! Could you provide a [MRE](https://github.com/orgs/WalletConnect/discussions/3457)?

**Comment by devon-n** [comment]
Unfortunately I cannot as its a private repo. Is there anything else that can help?

**Comment by ganchoradkov** [comment]
Could you try to replicate the issue in a new example repo where we could reproduce it reliably?

**Comment by glitch-txs** [comment]
Thanks for reporting, we've been unable to reproduce the issue, please feel free to reopen it providing an [MRE](https://github.com/orgs/WalletConnect/discussions/3457).
