### ISSUE TITLE
Error attempting to sign a message after connecting via MetaMask and changing accounts

### ISSUE THREAD

**Issue by ccummings** [WalletConnect/walletconnect-monorepo#3582]
After connecting to MetaMask and changing accounts, signing a message does not work.

**To Reproduce**

Can be replicated in the lab environment following these steps:

- Visit https://lab-walletconnect-modal.pages.dev/with-ethereum-provider
- Connect via MetaMask
- Change account in MetaMask
- Click "Sign Message"

The error in the console is `{"code":-32602,"message":"Invalid parameters: must provide an Ethereum address."}`

**Expected behavior**

Sign message action should be initiated with the newly switched to account

**Desktop (please complete the following information):**

Mac with Chrome and Brave

**Smartphone (please complete the following information):**

Android and iOS

**Additional context**

Stepping through the code it appears that the array of accounts the provider maintains never changes order like other providers.

i.e I connect with 0x1 then 0x2, the account array is `['0x1', '0x2']`

Whereas, Metamask lists the account that is currently connected first. So connecting with 0x1 then 0x2 results in an account array of `['0x2', '0x1']`

This is important because the address for signing is retrieved using this.getAddress() which takes the first address from the accounts array.

**Comment by ganchoradkov** [comment]
Hey, we investigated the issue, and is actually a bug within the example app itself and not the SDKs or the protocol.
We'll resolve it and meanwhile feel free to test with these additional example apps:

- https://react-app.walletconnect.com/ -> uses sign-client
- https://se-sdk-dapp.vercel.app/  -> uses ethereum-provider
