### ISSUE TITLE
Closing the QR modal results in error and unable to re-prompt QR modal.

### ISSUE THREAD

**Issue by Enigmatic331** [WalletConnect/walletconnect-monorepo#359]
On the Etherscan writeContract feature, when we select WalletConnect, prompt the QR modal, and decide to close the modal without establishing a connection, an error "Uncaught (in promise) Error: user closed modal" would appear in console, and subsequent attempts to launch the WalletConnect QR modal wouldn't work.

The error itself:
![image](https://user-images.githubusercontent.com/28551011/93999045-ecb7a900-fdc7-11ea-8fe5-04b0b6052dff.png)

Example Steps:
Go to https://etherscan.io/address/0xc00e94cb662c3520282e6f5717214004a7f26888#writeContract, click "Connect to Web3", select WalletConnect, close the QR modal. Click "Connect to Web3" and select WalletConnect again.

We are currently using the web3-provider package (https://www.npmjs.com/package/@walletconnect/web3-provider).
Perhaps it's something I might be missing? Cheers.

**Comment by finessevanes** [comment]
Hey @Enigmatic331, are you still experiencing this issue?
