### ISSUE TITLE
Add Palette Chain Mainnet

### ISSUE THREAD

**Issue by ko-syun** [WalletConnect/walletconnect-monorepo#3592]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
ethereum-rpc compatible
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
eip155 specs
3. **namespaces**:
eip155
4. **chains**:
Palette Chain Mainnet: eip155:1718
5. **RPC endpoints**
https://palette-rpc.com:22000
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
60

**Additional context**
Add any other context here.

---

**Please note:**

**Registering a chain with the Explorer does not impact or improve the ability for wallets and dapps to support your chain.** It is simply a way for users to discover wallets and dapps that support your chain by:

- Browsing the [Chains List](./chain-list.md)
- Filtering results programmatically via the [Explorer API](../../cloud/explorer.md)

**It is still up to wallets and dapps to provide concrete support for your chain once it is listed as part of the Explorer.**

- [x] I have read and understood the above clarification

**Comment by ko-syun** [comment]
@JonathanConn Could you kindly check this issue?

**Comment by JonathanConn** [comment]
Your rpc seems a little off.....

**Comment by ko-syun** [comment]
> Your rpc seems a little off.....

@JonathanConn 
Could you share us the detail about "a little off" ?

**Comment by JonathanConn** [comment]
For sure, your rpc looked off to me, so I tried to access it
It then automatically downloaded a file to my pc
This was viewed as rather malicious
Which is why your chain was not added

**Comment by ko-syun** [comment]
@JonathanConn
Sorry. No malicious intended. I will look into why the files are now being downloaded. Palette Chain has the same RPC as the other EVM chains, so I would appreciate your can add it.

**Comment by JonathanConn** [comment]
It's okay, it happens, ping me when it's fixed and I can take a look
