### ISSUE TITLE
"no matching keys" issue and no possibility to receive request from the dapp

### ISSUE THREAD

**Issue by dannpr** [WalletConnect/walletconnect-monorepo#3606]
**Describe the bug**
On client create I already have a strange error/warning about verifying some iframe

When I enter an URI then submit session_proposal it apparently works (I can fetch the sessions from WalletConnect) but it also generates a lot of errors/warnings about non matching session key.

When I receive anything to sign (session_request, in example confirm a connection on OpenSea or Rarible) it raises an error instead of opening the WC modal: it says that the session topic does not exist. We have double-checked that the session topic is changing and that the storage was cleaned for every test. 

**SDK Version**
 - Client:  JS
    "@walletconnect/core": "^2.9.1",
    "@walletconnect/types": "^2.9.1",
    "@walletconnect/utils": "^2.9.1",
    "@walletconnect/web3wallet": "^1.8.8"

![Capture d’écran 2023-09-07 à 10 40 35](https://github.com/WalletConnect/walletconnect-monorepo/assets/47109543/36823a5d-f983-4831-a2fa-cc92e012f736)

![Capture d’écran 2023-09-07 à 10 41 14](https://github.com/WalletConnect/walletconnect-monorepo/assets/47109543/f3f59ea5-0a8e-48a4-bcd3-1e0ce011a04b)

![Capture d’écran 2023-09-07 à 10 42 39](https://github.com/WalletConnect/walletconnect-monorepo/assets/47109543/d1c33a26-7ce5-4fc6-b0c8-fcf5389de831)

**Comment by ganchoradkov** [comment]
Hey @dannpr, could you update to latest - core/utils `2.10.0` & web3wallet - `1.9.0` and try it again please as the issue could be resolved
if it persists, could you provide a minimal repo where we could reproduce your exact case, thanks!

**Comment by dannpr** [comment]
Hi we still have the same issue even if we upgraded it, it don't change we'll provide you a minimal repo !

**Comment by dannpr** [comment]
Hi we still have the same issue even if we upgraded it, it don't change we'll provide you a minimal repo !

**Comment by dannpr** [comment]
hey @ganchoradkov , thanls for your responce this is my mini repo : https://github.com/dannpr/intu-manage

**Comment by ganchoradkov** [comment]
Hey @dannpr thanks for the example repo. I managed to find the issue and it's happening because the `useEffect` calls `createClient` twice thus clearing duplicate/conflicting instance of Web3Wallet where the session is missing that results in the `No matching key Error`
https://github.com/dannpr/intu-manage/blob/main/src/App.js#L205
Once you fix the `createClient` to be called just once, errors disappear
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/43912948/a245f27e-ca89-4697-9e15-e5c01cac9bd8)
