### ISSUE TITLE
Empty message session request timeout error caused by missing await 

### ISSUE THREAD

**Issue by Sinu5oid** [WalletConnect/walletconnect-monorepo#3607]
**Describe the bug**
* Missing await in session request respond methods of WC engine seems to break interaction flow between React Native wallet and React Native dapp, as the wallet could not send request in the background, and it is in the background state during the transport request.
  * (consequently,) all session requests that were not handled by the wallet side are rejected with `new Error(undefned)`, which leads to indistinguishable error being catched at caller side

**SDK Version (if relevant)**
 - Client: JavaScript
 1. React Native + wagmi core + WalletConnectConnector -> EthereumProvider -> UniversalProvider
 1. Vue.js + wagmi core + ... (same)
 - Version: 2.10.0

**To Reproduce**
The issue seems to be intermittent, yet it frequently appears on a large user base
Actors (same device):
* Mobile DApp
* Mobile Wallet

General direction of reproduction steps:
* Mobile DApp establishes a session with Mobile Wallet via WC
* Mobile wallet registers deeplink presence (and a need to perform goBack action upon response)
* Mobile DApp sends a session request (e.g. `personal_sign` with arbitrary data) to the connected wallet
* (dapp side) delayed promise with expiration is created: [createDelayedPromise(expiry)](https://github.com/WalletConnect/walletconnect-monorepo/blob/0401bfc50c7256e252116a21694d5a6053f67105/packages/sign-client/src/controllers/engine.ts#L348)
* Wallet prompts user to give their permission to perform an action
* Wallet successfully / unsuccessfully performs an action
* Wallet sends success / error payload with [respondSessionRequest()](https://github.com/WalletConnect/walletconnect-monorepo/blob/0401bfc50c7256e252116a21694d5a6053f67105/packages/web3wallet/src/client.ts#L97) -> ... -> [sendResult](https://github.com/WalletConnect/walletconnect-monorepo/blob/0401bfc50c7256e252116a21694d5a6053f67105/packages/sign-client/src/controllers/engine.ts#L381) / sendError -> [publish without await (result)](https://github.com/WalletConnect/walletconnect-monorepo/blob/0401bfc50c7256e252116a21694d5a6053f67105/packages/sign-client/src/controllers/engine.ts#L575C21-L575C21) / [publish without await (error)](https://github.com/WalletConnect/walletconnect-monorepo/blob/0401bfc50c7256e252116a21694d5a6053f67105/packages/sign-client/src/controllers/engine.ts#L588)
* Wallet awaits for returned promise (but not the publish one, rather history resolve)
* Wallet executes navigation actions (typically, this would be goBack, which leads to intent/activity losing foreground context, so react native requests are forcefully dropped)
* (dapp side) delayed promise is not fulfilled in time (never received, as wallet did never finish publishing the payload), so it rejects with `new Error(undefined)`
* wc error log appears as `{ context: 'client' } ` (no error message, as `(new Error(undefined)).message would return ''`
* Dapp's caller receives an Error with empty message without any explanation

**Expected behavior**
* `await respondSessionRequest()` should ensure that the response payload is sent (if it's undesirable to throw errors, related to publish -- silently catch them)
* `createDelayedPromise` should have an optional error message (or a message should be provided by the caller), therefore the timeout error would have a message

**Screenshots**
![error captured in Sentry](https://github.com/WalletConnect/walletconnect-monorepo/assets/13100095/b4bf21e5-b094-44d2-aa52-e5abe7ab165a)

**Desktop (not really relevant, as is hard to reproduce (see Additional context)):**
 - OS: Windows 11 Professional
 - Browser: Chrome
 - Version: 116.0.5845.142

**Smartphone:**
 - Device: Xiaomi Mi 9T Pro
 - OS: Android 11
 - Browser: Chrome
 - Version 116.0.5845.163

**Additional context**
This issue can be reproduced on desktop + mobile wallet stand, but the faulty actions happen on the mobile wallet side only (primarily with wallets that use deeplink handling & back action)
These changes will help in a mobile dapp - mobile wallet use case a lot

**Comment by ganchoradkov** [comment]
Hey @Sinu5oid, this scenario should not happen as of `2.10.0` version and I guess you're experiencing it on wallets that haven't yet updated to latest. 

Now, we're awaiting the publish + additional ACK from the relay to confirm the payload was received before releasing the promise https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/sign-client/src/controllers/engine.ts#L381
The `throwOnFailedPublish` flag indicates that

**Comment by Sinu5oid** [comment]
Hey @ganchoradkov, thanks for reply
It seems that the wallets we are testing on did not upgrade to the 2.10.0 yet, I see [2.9.2](https://github.com/rainbow-me/rainbow/blob/65369dacb2b15bb7f7dd787489e4d3125444a849/yarn.lock#L5640) in rainbow wallet's most recent release, and [2.9.0](https://github.com/MetaMask/metamask-mobile/blob/d3cd54feadc8ee694a88836dc7c136123421bbc3/yarn.lock#L7164) in MetaMask. We should probably wait a bit for them to upgrade

Could you please also comment on the empty message issue?
- [createDelatedPromise<T>(expiry)](https://github.com/WalletConnect/walletconnect-monorepo/blob/0401bfc50c7256e252116a21694d5a6053f67105/packages/sign-client/src/controllers/engine.ts#L348) - does not explicitly specify the second argument (error message)
- [export function createDelayedPromise<T>(expiry: number = FIVE_MINUTES, expireErrorMessage?: string)](https://github.com/WalletConnect/walletconnect-monorepo/blob/0401bfc50c7256e252116a21694d5a6053f67105/packages/utils/src/misc.ts#L227) - `expireErrorMessage` is an optional string, as it don't receives a value, and no default value is defined, `expireErrorMessage` is `undefined`
- [promiseReject(new Error(expireErrorMessage))](https://github.com/WalletConnect/walletconnect-monorepo/blob/0401bfc50c7256e252116a21694d5a6053f67105/packages/utils/src/misc.ts#L237) - `promiseReject(new Error(undefined))` throws an error which has `.message` equal to ` ` (empty string)
  - could be replicated in Node / Browser environment simply by running `console.log((new Error(undefined).message)`
