### ISSUE TITLE
There are some missing paths in the exports for the ethereum-provider

### ISSUE THREAD

**Issue by richtera** [WalletConnect/walletconnect-monorepo#3617]
**Describe the bug**
When compiling the package using esbuild it internally tries to import 
./dist/types/EthereumProvider.d.ts, but that file is not defined in the exports.
There is also a ./dist/types/constants folder with the same problems.

I quickly patched the npm by adding
"./dist/types/*": "./dist/types/*.d.ts"
into the exports section, but this probably get fixed.

**SDK Version (if relevant)**
 - Client: node
 - Version  16.16.0 but I was able to reproduce it using vite/esbuild with v20
This is a build time problem.

**To Reproduce**
1. Setup vite project and run vite dev
2. It should build but then complain about the import not being available.
The rest of the code will work fine since it's just a .d.ts file

**Expected behavior**
The error should not be there and disappears with the patch

**Screenshots**
<img width="883" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/708186/162b1bcf-e9cf-4eb8-9845-0acf5be361a0">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome (but this error is on the build machine)
 - Version  116.0.5845.140 

**Additional context**
It started happening all of a sudden because a full vite build works fine because it doesn't need to compile any of the node modules all the time.

**Comment by glitch-txs** [comment]
This should be fixed in the latest versions, please update all packages and let us know if the issue still persists.
