### ISSUE TITLE
Replace unmaintained dependency

### ISSUE THREAD

**Issue by o-az** [WalletConnect/walletconnect-monorepo#3619]
**Is your feature request related to a problem? Please describe.**
`lokijs` is used in [@walletconnect/sign-client](https://github.com/WalletConnect/walletconnect-monorepo/blob/0401bfc50c7256e252116a21694d5a6053f67105/packages/sign-client/package.json#L56) however it's not maintained.

The last update to `lokijs` [is a year ago](https://github.com/techfort/LokiJS/commits/master/)
The last published version on npm is [2 years ago](https://www.npmjs.com/package/lokijs)

**Describe the solution you'd like**
Replace unmaintained dependency with a maintained one. Good alternative:

**`unstorage`**: https://github.com/unjs/unstorage (https://unstorage.unjs.io)

**Describe alternatives you've considered**
`unstorage`: https://github.com/unjs/unstorage (https://unstorage.unjs.io)

**Additional context**

**Comment by ganchoradkov** [comment]
@o-az thank you for the suggestion 💯 will discuss it with the team.

**Comment by ganchoradkov** [comment]
resolved with https://github.com/WalletConnect/walletconnect-utils/pull/142
