### ISSUE TITLE
provider.close() error

### ISSUE THREAD

**Issue by lnbc1QWFyb24** [WalletConnect/walletconnect-monorepo#363]
Package: `"@walletconnect/web3-provider": "^1.2.2"`

When calling `provider.close()` to end the session and disconnect the provider, the following error gets thrown:
<img width="549" alt="Screen Shot 2020-09-29 at 2 00 20 pm" src="https://user-images.githubusercontent.com/29873495/94511377-75b56100-025c-11eb-9f64-9123f16e6840.png">

The `web3-provider-engine` also continues to poll on the `eth_blocknumber` request:
<img width="478" alt="Screen Shot 2020-09-29 at 2 00 43 pm" src="https://user-images.githubusercontent.com/29873495/94511428-a4cbd280-025c-11eb-8f53-143853dd1bd3.png">

**Comment by brunomenezes** [comment]
Hi @pedrouid, is any of the new releases after `"@walletconnect/web3-provider": "^1.6.2"` addressing this issue?

**Comment by finessevanes** [comment]
Hey @aaronbarnardsound, @brunomenezes is this still an issue?

**Comment by brunomenezes** [comment]
> Hey @aaronbarnardsound, @brunomenezes is this still an issue?

Hi @finessevanes, I have been using the web3-onboard v2. At the moment, when I end a wallet connection done with wallet-connect, I can't see it polling for the `eth_blockNumber` (so it does not look like a problem anymore). Not sure if @aaronbarnardsound has a different experience.
