### ISSUE TITLE
Aleo: Add to WalletConnect

### ISSUE THREAD

**Issue by jonandgon** [WalletConnect/walletconnect-monorepo#3638]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://developer.aleo.org/testnet/getting_started/overview/).
   **GitHub Link**: https://developer.aleo.org/testnet/getting_started/overview/
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   **GitHub Link**: https://github.com/ChainAgnostic/namespaces/pull/90
3. **namespaces**:
  aleo
4. **chains**:
  aleo:3
5. **RPC endpoints**
  A list of RPC endpoints can be found here: https://developer.aleo.org/testnet/public_endpoints/latest_height. 
  The URL for the endpoint is `vm.aleo.org/api/`
   
7. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
   _\* slip44 coin type used in the namespace_
https://github.com/satoshilabs/slips/pull/1599

**Additional context**
Aleo is currently only in testnet (testnet3), however they have announced plans for a mainnet end of 2023 / beginning of 2024. There are many devs that are building dApps using [Puzzle Wallet](https://docs.puzzle.online/). Puzzle Wallet is built using WalletConnect, but since Aleo is not yet in mainnet, we cannot fully use WalletConnect sdks such as the [Notify API](https://docs.walletconnect.com/2.0/api/notify/usage#managing-subscriptions). It would be great if WalletConnect somehow supported testnet-only chains so devs don't have to scramble to get features in once mainnet is released. 

If WalletConnect will not consider adding this chain, I hope they will consider making their APIs fully usable for non-supported chains. It could be in some limited way, but just so devs can actually test/properly implement the APIs.

---

**Please note:**

**Registering a chain with the Explorer does not impact or improve the ability for wallets and dapps to support your chain.** It is simply a way for users to discover wallets and dapps that support your chain by:

- Browsing the [Chains List](./chain-list.md)
- Filtering results programmatically via the [Explorer API](../../cloud/explorer.md)

**It is still up to wallets and dapps to provide concrete support for your chain once it is listed as part of the Explorer.**

- [x] I have read and understood the above clarification

**Comment by JonathanConn** [comment]
We need the namespace PR to be merged before we can support your chain, I left a note on the PR letting them know
Ping me when it is merged and we can get your chain added
Thank you -Jon

**Comment by JonathanConn** [comment]
> It would be great if WalletConnect somehow supported testnet-only chains so devs don't have to scramble to get features in once mainnet is released

We support testnets  
You can submit a request to add your testnet chain
Do whatever testing or integrations you need
Then submit a request to add your mainnet chain

**Comment by bkrem** [comment]
Looks like we're close to merging the CASA spec here (cc @bumblefudge). Keeping this open.

**Comment by jonandgon** [comment]
@bkrem the CASA spec has been merged.

Also, how are the optional/required namespace methods/events defined? It's not done in the CASA work.

**Comment by bumblefudge** [comment]
Is that what you're looking for, @jonandgon ?
https://docs.walletconnect.com/web3wallet/wallet-usage#namespace-builder

**Comment by jonandgon** [comment]
Sort of, I was thinking that there's some central location where all possible methods/events are defined for a given chain/wallet, instead of dApp developers needing to fill out that information each time. Like where are `eth_sendTransaction` and `personal_sign` defined in walletconnect for `eip155` in WalletConnect? And how do eip155 wallets agree that these are methods they should be implementing?

I may be mistaken in thinking that these are defined anywhere in WalletConnect, if so, you can disregard :)

**Comment by bumblefudge** [comment]
oh!  well, i think eip107 and eip191 respectively defined those two methods initially, but since they're mandatory for all EVM nodes the most canonical reference is probably:
https://github.com/ethereum/execution-apis
do you think it would be helpful to make this more explicit in a CAIP-25 profile for eip155, i.e., PR a `caip25.md` into this folder:
https://github.com/ChainAgnostic/namespaces/tree/main/eip155
?
Happy to do so if you can provide review on the PR (and point out whatever else would have made this more intuitive)

**Comment by jonandgon** [comment]
Gotcha, I think our issue is slightly different then since dApps can't get much info about accounts via a node since Aleo is a private network. Most information will need to be decrypted and come directly from an Aleo wallet in our case.

Since the Aleo Nodes are mostly only used by wallets and not by dApps, the interface between node and wallet is different.

Also, there are methods that are specific to our wallet that may not yet be implemented by other Aleo wallets, such as `importSharedState` and `createSharedState`. But methods like `getBalance` and `getAccount` will need to be implemented by all wallets. 

I was just using `eip155` as an example, but I will do a CAIP-25 for `Aleo` if:
1. It doesn't delay the merging of this PR. Mainnet is planned for mid Feb and I _really_ want this PR in before then.
2. [Our own docs](https://docs.puzzle.online/sdk-free/overview/) are not sufficient enough on their own. 
3. I get a template for caip25. I don't see one in use, and the [spec here](https://chainagnostic.org/CAIPs/caip-25#links) seems slightly out of step with what Walletconnect is using for Pairing/Session creation.

Thanks!

**Comment by bumblefudge** [comment]
1. Of course!  No pressure.  Also totally fine to reference the Puzzle SDK docs non-normatively for now, and update the link if a more permanent/aleo-wide reference get published later? Whatever you think will help clarify all this for devs after launch!
2. You could think of the namespace profiles as implementer guidance-- wherever possible nothing new should be specified in them, just summaries of (and links to) canonical docs elsewhere. If nothing is canonical yet, just say as much in the text of the profile! 
3. That's totally fair-- I should make one for Eip155 and ping you here when I have.  WalletConnect implemented a slightly earlier version of CAIP-25, so the abstraction is a little divergent, but the differences are fairly superficial, and the messages over the wire (within WC) can be deterministically translated to and from CAIP-25-conformant messages, AFAIK! Any input on deeper incompatibilities I might be overlooking (or translation pitfalls) would be helpful in opening an `eip155/caip25` for you as template, so warmly appreciated!

**Comment by jonandgon** [comment]
ok great, I will hold off for now on implementing the CAIP-25 for Aleo until the one for EIP155 is made. I'll try to communicate with Aleo directly to see if they're willing to define a reference for the required methods/events, but this will probably take some time. 

Feel free to add me as a collaborator for that `eip155/caip25` PR and I will happily take a look

**Comment by bkrem** [comment]
Thanks for your getting everything tied up here @jonandgon! This has now been added to https://cloud.walletconnect.com/ ✅
