### ISSUE TITLE
WebSocket connection pending && qrcode modal could not show up

### ISSUE THREAD

**Issue by sarufarr** [WalletConnect/walletconnect-monorepo#364]
I'm developing a Dapp which using ```"@walletconnect/web3-provider": "^1.2.2"``` to connect with Ethereum(both mainnet and kovan).

In my project(```"react": "^16.13.1"```)
code like this
```
import WalletConnectProvider from '@walletconnect/web3-provider'

const tmpWalletConnectProvider = new WalletConnectProvider({
        qrcode: true,
        qrcodeModalOptions: {
          mobileLinks: ['metamask'],
        },
})
tmpWalletConnectProvider.enable().then(() => {}).catch(() => {})
```

After wallet-connect has been booted by user interface, the WebSocket request of ```wss://bridge.walletconnect.org/``` is keeping ```pending``` 
or only receive  one message 
![image](https://user-images.githubusercontent.com/14183804/94984067-bbcf3500-057a-11eb-8e46-e0c4fecef603.png)

And after all those situations,  there is no qrcode modal showed up.

The same problem appears among PC browser(```chrome 86.0.4240.55```) website &  Dapp browser in imToken App(``` v2.6.3.989 cp40 & Android 10```)

**Comment by acharl** [comment]
experiencing the same issue of pending WebSocket requests when trying to establish a wallet side connection as per https://docs.walletconnect.org/quick-start/wallets/react-native#initiate-connection

**Comment by finessevanes** [comment]
Hey @sarufarr @acharl are you still experiencing this issue?
