### ISSUE TITLE
window.addEventListener isn't available for react native apps

### ISSUE THREAD

**Issue by cstoneham** [WalletConnect/walletconnect-monorepo#3649]
**Describe the bug**
The [subscribeToBrowserNetworkChange](https://github.com/WalletConnect/walletconnect-monorepo/blob/d65f32e1e7c7f0799bfbeb6c4feb06835c5c0c51/packages/utils/src/network.ts#L60) function in the utils package calls window.addEventListener. This package is pulled into @walletconnect/web3wallet and thus throws an error in React Native.

**SDK Version (if relevant)**
 - Client: TS, React Native, Expo
 - Version 1.9.1

**To Reproduce**
1. Follow the installation steps for React Native: https://docs.walletconnect.com/2.0/web3wallet/about
2. Start the app
3. Look in your console.

**Expected behavior**
The @walletconnect/react-native-compat should prevent this unavailable window function from being called.

**Screenshots**

<img width="1227" alt="Screenshot 2023-09-14 at 1 56 36 PM" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/13357705/fb3cc81e-355a-4d0d-b0e1-ebe0959d723c">

**Desktop (please complete the following information):**
 - OS: MacOS venture 13.4.1
 - Browser Brave
 - Version 1.57.47

**Smartphone (please complete the following information):**
 - Device: iPhone 10
 - OS: iOS 16.6.1
 - Browser N/A
 - Version N/A

**Additional context**
N/A

**Comment by ganchoradkov** [comment]
Hey, thanks for the report. I'm not sure why this error is thrown as it's safeguarded by [`isBrowser()`](https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/utils/src/network.ts#L61) util and I'm not receiving the error on my RN setup. Could you provide a minimal repro example that I can debug? Maybe there are some polyfills that are causing the issue.
