### ISSUE TITLE
Unable to sign transaction in custom RPC using walletconnect

### ISSUE THREAD

**Issue by pranjal1127** [WalletConnect/walletconnect-monorepo#365]
As per documentation, I am using walletconnect with customRPC 

[https://docs.walletconnect.org/quick-start/dapps/web3-provider#custom-rpc-url](https://docs.walletconnect.org/quick-start/dapps/web3-provider#custom-rpc-url)

I am sharing some snippets  to connect it with our custom provider called 'eraswap'

```
import WalletConnectProvider from "@walletconnect/web3-provider";
import { providers } from "ethers"



export async function loadWallet() {
  //  Create WalletConnect Provider
  const walletConnectProvider = new WalletConnectProvider({
    rpc : { 5196 : 'https://testnet.eraswap.network'},
    infuraId: "b81341e3ab894360a84f3fa640ab985e" ,
    qrcode: true
  }); 
  await walletConnectProvider.enable();
  const provider = new providers.Web3Provider(walletConnectProvider)
  console.log(provider.getSigner())
  const wallet = await provider.getSigner()
  return wallet;
}
```

but I am getting these error
![image](https://user-images.githubusercontent.com/45527699/94997886-bbab5580-05cb-11eb-84f6-700256fc6b31.png)

I am using modified version of [https://test.walletconnect.org/](https://test.walletconnect.org/)  in which eraswap RPC network also exist  

mention code is for added data in Ichaindata

```
{
    name: "Eraswap Testnet",
    short_name: "esn",
    chain: "ESN",
    network: "testnet",
    chain_id: 5196,
    network_id: 5196,
    rpc_url: "https://testnet.eraswap.network",
    native_currency: {
      symbol: "ES",
      name: "Eraswap",
      decimals: "18",
      contractAddress: "",
      balance: "",
    },
  },

```

the updated version of test wallet is [https://esnwallet.vercel.app/](https://esnwallet.vercel.app/).
[https://github.com/pranjal1127/eswallet/blob/master/src/constants/chains.ts#L4-L19](https://github.com/pranjal1127/eswallet/blob/master/src/constants/chains.ts#L4-L19)

I have also tried all instructions of this following discussion 
[https://github.com/ethers-io/ethers.js/issues/775](https://github.com/ethers-io/ethers.js/issues/775)

**Comment by pedrouid** [comment]
Interesting, could you try to remove the infuraId? This might causing conflicts with Ethereum RPC being relayed incorrectly.

Also could you share a Dapp example using Eraswap Testnet as well

**Comment by pranjal1127** [comment]
Well I have tried this after remove InfuraID. but it didn't effect anything


you can use it as a demo although it is in production  but you can test it using with google console
[https://certi-dapp-react.vercel.app/survey](https://certi-dapp-react.vercel.app/survey)

1. click on the button named (wallet connect) and connect it with test wallet [https://esnwallet.vercel.app/]
2. now signer will store in  global window  
3. use this commands in google console 
`await window.surveyInstance.connect(window.wallet).addSurvey("QmWUUB7tpJVs1HxFSNXkJi4P2JUTLFMneN6cyNCvygaZkZ",1631334200000,true)`

In above snipet surveyInstance holds smart contract  types and window.wallet holds jsonRPCSigner .

=> SmartContractTS.connect(Signer).method([args])

**Comment by pranjal1127** [comment]
any updates ... ?

**Comment by asad97290** [comment]
const provider = new WalletConnectProvider({
rpc: {
56: "https://bsc-dataseed.binance.org",
},
});

trying to connect to the bsc main net but failed getting this error in the browser
POSThttps://mainnet.infura.io/v3/
[HTTP/2 401 Unauthorized 1193ms]

**Comment by ericHgorski** [comment]
Still experiencing this issue in 2022! Attempting to use a polygon RPC provider. Is there a fix in the works?

**Comment by vernonjohnson** [comment]
Big issue, needs to be fixed. Walletconnect is pretty much unusable on Polygon at this point

**Comment by bigbizze** [comment]
running into this issue as well

**Comment by finessevanes** [comment]
Hey @ericHgorski , @vernonjohnson , and @bigbizze are you all still experiencing this issue?
