### ISSUE TITLE
Error if third party cookies are blocked by the browser and the app is in an iframe

### ISSUE THREAD

**Issue by koskotheim** [WalletConnect/walletconnect-monorepo#3650]
**Describe the bug**
An error is thrown and (in our case) the app crashes if it is accessed from within an iframe in a browser that blocks 3rd party cookies.

The error is:
DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

**SDK Version (if relevant)**
- We are using version 2.7.0 of @wagmi/connectors, which depends on version 2.8.2 of @walletconnect/ethereum-provider
- It is also reproducible on the wallet connect example app at example.walletconnect.org

**To Reproduce**

Here is a minimal example to demonstrate: 
https://wallet-connect-embed-example.web.app/

```html
<!DOCTYPE html>
<html>
  <body>
    <iframe
      src="https://example.walletconnect.org/"
      style="position: absolute; top: 0; left: 0; width: 100vw; height: 100vh"
    >
    </iframe>
  </body>
</html>

``` 

The above site will work fine until you go into browser preferences and disable third party cookies. Then it will not work and will throw that error about local storage. 

**Expected behavior**

I would expect that access to local storage would be wrapped in a try / catch block so that it does not throw an unrecoverable error if local storage is unavailable. 

**Screenshots**

![Screen Shot 2023-09-14 at 9 12 53 PM](https://github.com/WalletConnect/walletconnect-monorepo/assets/98971550/44018460-f0e7-445c-8cf2-1b88b11f36bc)

**Additional context**

We have tried detecting this situation and using a global proxy for local storage on the window object to try / catch any calls on local storage. That fixes this particular issue but breaks other things that do handle but expect an error if local storage is not available. 

This is also described in [this issue](https://github.com/WalletConnect/walletconnect-monorepo/issues/289), but since it has been closed for a while I thought I would open a new one. Feel free to reference this or close it if it would be better to re-open the previous issue which described the same problem.

**Comment by glitch-txs** [comment]
hi, the example given is using v1 which is deprecated

**Comment by koskotheim** [comment]
@glitch-txs is there an example that uses the latest version to try this on? I have not found a site that implements wallet connect, or a library that depends on wallet connect, where this is not an issue. But it would be helpful if it was known that this is only an issue on older versions. I would try it with walletconnect.com but it seems that it detects + does not allow being loaded in an iframe.

**Comment by glitch-txs** [comment]
I'll close this one since we have a iframe issue open, we'll try to support iframe integration in the short future
