### ISSUE TITLE
Support sign_arbitrary for cosmosis

### ISSUE THREAD

**Issue by happyeric77** [WalletConnect/walletconnect-monorepo#3653]
## **Is your feature request related to a problem? Please describe.**

My project is using the sign message feature to do auth in multi-chain. We use `personal_sign` method for eth chain.
We now have a growing demand for Cosmos chain, but I believe walletConnect still does not yet support `signArbitrary`. Now users can only use the service through the browser [browser-embedded walletProvider solution](https://docs.keplr.app/api/#request-signature-for-arbitrary-message). 

However, It would be great if walletConnect supports the `sign arbitrary` method for Cosmos chain so that the users can also have a much better experience by using their mobile phone.

## **Describe the solution you'd like**

Currently, we only have the following [methods](https://docs.walletconnect.com/2.0/advanced/rpc-reference/cosmos-rpc) for Cosmos. Do we have a plan to add `sign arbitrary`?
- cosmos_getAccounts
- cosmos_signDirect
- cosmos_signAmino

**Comment by ganchoradkov** [comment]
Hey, WalletConnect v2 is chain/method agnostic so you could send requests for any method as long as they're approved by the wallet for the given session. Just make sure you add the `sign_arbitrary` method in your proposal.
