### ISSUE TITLE
Can't Sign Up or Log In

### ISSUE THREAD

**Issue by kevin-ethos** [WalletConnect/walletconnect-monorepo#3658]
**Describe the bug**

**To Reproduce**
JWT Issued At error: 

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/119427821/a79f0711-cafa-4824-8ce1-8dcade038b72)

**Expected behavior**
Able to log in

**Screenshots**
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/119427821/e9ca3279-2785-477a-a5f6-580553fdb16c)

**Desktop (please complete the following information):**
 - Chrome and Brave

**Smartphone (please complete the following information):**
 - MacOS
 
**Additional context**
Can't sign up or log in with either username and password OR Wallet Connect

**Comment by glitch-txs** [comment]
We'll look into this, thanks for reporting

**Comment by glitch-txs** [comment]
should be fixed by now!
