### ISSUE TITLE
Domain verification error - [DNS] The verification code on the text file is invalid

### ISSUE THREAD

**Issue by ravisriv** [WalletConnect/walletconnect-monorepo#3662]
Please refer to the discussion linked below. The new verification code does not work when a TXT record is created in the DNS. There is a difference between the documentation and the verification code that is generated on the Walletconnect website. (The key in the new code is different from what's mentioned in the documentation for DNS verification.) So, it is confusing. But if the DNS verification code is cut and pasted in a TXT record for the domain that is to be verified, then the following error is returned:
"[DNS] The verification code on the text file is invalid"
I have verified the TXT record through the mxtoolbox and the correct TXT record is returned. This also shows that the TXT record in the DNS has already propagated.
Not sure what I need to do for domain verification but looks like this is an issue in the Walletconnect DNS verification software.

### Discussed in https://github.com/orgs/WalletConnect/discussions/3343

<div type='discussions-op-text'>

<sup>Originally posted by **MickaelNeves** August  2, 2023</sup>
I added the TXT to vercel but still getting error when trying to validate domain
![Screenshot 2023-08-02 at 12 49 24](https://github.com/WalletConnect/walletconnect-monorepo/assets/20476271/986c4246-c033-4f4f-ab7e-4529f6490cd4)
![Screenshot 2023-08-02 at 12 38 33](https://github.com/WalletConnect/walletconnect-monorepo/assets/20476271/c5c5b8db-f316-4408-b3e9-8920a1dabeef)
</div>

**Comment by Cali93** [comment]
Thanks for pointing out that the documentation is out of date.
You need to copy the **entire code** that is generated and paste it as the value for the TXT record.
Please give it some time to propagate as it can take up to 72 hours.

We updated our docs to reflect the latest flow. Please let us know if you're still facing any issue.
https://docs.walletconnect.com/2.0/cloud/verify

**Comment by ravisriv** [comment]
Hi Cali93,

NO. THIS IS NOT A DOCUMENTATION ISSUE, though documentation was confusing. 

It is probably a "Verify" software bug at the walletconnect dashboard side. So, it is not verifying correctly. See the output of mxtoolbox below:

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/62220449/108629c0-9702-49d6-8050-0b40933f8ad5)

The TXT record returned by mxtoolbox matches exactly the TXT code that is generated on the walletconnect website, which is as below:
d4586bab-1182-4c6d-b542-161dff9d1af2=e42097bbb73614b1dc095c048042a629828a2e654825d6a16df39822d2c06f15

But still the domain verification fails. 
Thanks.

**Comment by ravisriv** [comment]
Here is further information on this bug and a workaround.

**ISSUE**
This bug will appear if you had previously verified your domain using the old string with wallet-connect-dns-verification as part of the verification string.

If you had a verified domain and you made any changes to the project and if you tried to reverify, it will not work. (You should not re-verify unless you have made changes to the domain name. But by mistake if you tried to re-verify and lost your verification, then you'll run into this bug.)

**WORKAROUND**
Delete the project from Walletconnect and create another project. Follow the outlined process to verify your domain and it will work. It is a pain since you'll need to upgrade your project id, etc. but currently there is no other way.

**Comment by ganchoradkov** [comment]
Hey @ravisriv glad you've resolved it. I think @Cali93's comment meant that you must paste the whole code including the `wallet-connect-dns-verification=`

**Comment by ravisriv** [comment]
@ganchoradkov Hi mon ami, I did not resolve the issue. Verify is still broken. What I did was that I provided an ugly and painful workaround. A workaround is not a solution but a way to get around a bug in the software. In order to understand the issue, please read the entire thread as well as my posting under a previous thread (link displayed at the top of this thread). @Cali93 did a pretty nice job of cleaning up the documentation but he did not resolve the bug in the Verify software.

For anyone who is trying to understand the issue, I'm going to briefly recap the software bug in Verify below:

**SOFTWARE BUG DESCRIPTION**: If a user had previously verified their domain and they make changes in their profile and try to re-verify their domain, the domain verification will fail with an error "[DNS] The verification code on the text file is invalid".

The issue mentioned above is unresolved.

The workaround is to delete the project from Walletconnect dashboard (cloud.walletconnect.com) and create another project with the same domain and then verify it again. But this is an ugly solution since it will require changing the project id and project secrets. Depending upon the software such changes could be at multiple places and may require a new release. Ugh!

Since you closed an unresolved issue, I'll create a new issue.

**Comment by Cali93** [comment]
Thanks for reporting the issue @ravisriv. 
We will investigate the issue and keep you updated as soon as it's resolved.

**Comment by Cali93** [comment]
@ravisriv We investigated the issue and found the bug and fixed it. More context [here](https://github.com/orgs/WalletConnect/discussions/3343#discussioncomment-7058175).
There are only 2 ways of verifying your domain. Please follow our detailed guide https://docs.walletconnect.com/2.0/cloud/verify and give it some time (it can take up to 72 hours for your DNS record to propagate) also make sure that the TTL of previous/stale records isn't too long.

**Comment by ravisriv** [comment]
Hi @Cali93 - The changes you made in the last 24 hours have resolved this issue. I did not make any changes at my end. I logged in and just clicked on the "Verify" button. I was happy to see the green message that the domain was successfully verified. Finally, it is working. Thank you!

**Comment by Vt2049** [comment]
k
