### ISSUE TITLE
My React Native wallet doesn't listen for session proposals on the first launch. However, after reloading the app, the listener starts working automatically.

### ISSUE THREAD

**Issue by adnansudozai** [WalletConnect/walletconnect-monorepo#3668]
When i run my react native app on first time this return an error after pairing is success but before pairing return this error 

![Screenshot 2023-09-18 at 7 05 04 PM](https://github.com/WalletConnect/walletconnect-monorepo/assets/45669092/a519f4a0-e106-4e01-9ec3-8a926c63e029)

{context: 'core'} {context: 'core/relayer'} TypeError: this.events.off is not a function
    at JsonRpcProvider.off (provider.js:26:21)
    at ot.unregisterProviderListeners (index.cjs.js:1:38935)
    at ot.<anonymous> (index.cjs.js:1:37342)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:24)
    at _next (asyncToGenerator.js:22:9)
    at asyncToGenerator.js:27:7
    at web3.min.js:2:581704
    at new t (web3.min.js:2:581768)
    at ot.<anonymous> (asyncToGenerator.js:19:12)

**Comment by adnansudozai** [comment]
![Screenshot_20230918-205805](https://github.com/WalletConnect/walletconnect-monorepo/assets/45669092/d8fd94b6-86a7-4410-80ab-49c0ed1c8d4b)

@ignaciosantise 
on my react native app show this when I rerun my app its working fine

**Comment by ganchoradkov** [comment]
Hey @adnansudozai, could you provide a small repo where we could reproduce the error?
Most likely you have some polyfills of `EventEmitter` that is causing issues as it should be available by default

**Comment by adnansudozai** [comment]
@ganchoradkov 
Thanks
My problem is solve when i downgrade my wallet connect version to 
 "@walletconnect/utils": "2.9.2",
     "@walletconnect/react-native-compat": "2.9.2",
 "@walletconnect/core": "2.9.2",
 
 I don't now whats the problem on latest version wit react native version
     "react-native": "^0.70.0",
         "react": "18.1.0",

**Comment by niklasnatter** [comment]
Hey everybody, we encountered a similar issue today and summarised how we solved it here: https://github.com/WalletConnect/walletconnect-monorepo/issues/4064#issuecomment-2072629887
