### ISSUE TITLE
sign-client always prompts users to open their wallet in the mobile browser

### ISSUE THREAD

**Issue by darrenkel** [WalletConnect/walletconnect-monorepo#3738]
**Describe the bug**
When on my dApp in the mobile browser, I am always prompted to open the wallet after making a session request. This behaviour is not ideal because the dApp immediately sends a session request after a session approval, so the user processes both the session proposal and session request in the same flow. When they go back to the dApp they are prompted to open the wallet even though the request has been processed

**SDK Version (if relevant)**
 - @walletconnect/sign-client
 - 2.10.1

**To Reproduce**
1. Send a session request from a dApp immediately after the session is accepted (without user interaction)

**Expected behavior**
The prompt should be optional

**Screenshots**

<img width="675" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/107671032/d3c634f6-caa3-4617-a454-63d4d9b5bd6b">

**Desktop (please complete the following information):**
 - Browser: Safari 
 - Version: iOS 17

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 17
 - Browser: Safari
 - Version: 17

**Additional context**
Adding an optional `promptWallet` in the request may help

```typescript
signClient.request({
  topic,
  chainId,
  request: {
    method: 'myMethod',
    params: [...],
  },
  promptWallet: false
})
   ```

**Comment by glitch-txs** [comment]
This should be fixed in the latest versions, please update all packages and let us know if the issue still persists.
