### ISSUE TITLE
add Scroll network

### ISSUE THREAD

**Issue by dghelm** [WalletConnect/walletconnect-monorepo#3748]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
   ethereum-rpc
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   ethereum
3. **namespaces**:
  eip:155
4. **chains**:
   _\*known chains, where the primary key is a compound key composed of namespace + reference (e.g. ETH mainnet is eip155:1)._
   _Please provide labels for each chain (e.g. mainnet, testnet, devnet, ...)_
Scroll: eip155:534352
5. **RPC endpoints**
https://rpc.scroll.io/
_Please note that this URL and chain aren't live yet but will be soon._
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
 60

**Additional context**
Adds support for Scroll's upcoming mainnet.

---

**Please note:**

**Registering a chain with the Explorer does not impact or improve the ability for wallets and dapps to support your chain.** It is simply a way for users to discover wallets and dapps that support your chain by:

- Browsing the [Chains List](./chain-list.md)
- Filtering results programmatically via the [Explorer API](../../cloud/explorer.md)

**It is still up to wallets and dapps to provide concrete support for your chain once it is listed as part of the Explorer.**

- [x] I have read and understood the above clarification

**Comment by JonathanConn** [comment]
Added to the PR, will be reviewed and merged soon

I was surprised Scroll hasn't been added yet, I had to look up Scroll's RPC to make sure this was real
 
I'm a big fan of Scroll, so welcome! @dghelm
