### ISSUE TITLE
@walletconnect/web3-provider not rejecting the promise on eth_sendTransaction when user deny it

### ISSUE THREAD

**Issue by wighawag** [WalletConnect/walletconnect-monorepo#375]
@walletconnect/web3-provider is not rejecting the request promise on `eth_sendTransaction` when the user deny it on its mobile wallet (tested on metamask)
Instead the promise never resolve. leaving the app to decide what to do.

This is unfortunate as this force the app to make the user decline the tx twice, once on its wallet and once again in the app.

It would be better if walletconnect web3-provider reject the promise when the user deny the tx on its wallet

**Comment by miohtama** [comment]
Here is my old code to detect the rejection. Though I think I ever tested this with MetaMask desktop. I have not tested this with the latest wallet versions.

https://gist.github.com/miohtama/a91a5edabac6bf66de860a444fc13206#file-transaction-helper-component-ts-L344

Please tell me if it is helpful or not working - if the behavior is different with MetaMask desktop we need to find a way to address this.

**Comment by wighawag** [comment]
hmm, I am referring to user rejecting "pressing cancel" 
it should reject the promise on  @walletconnect/web3-provider  side
and so I do not even expect a tx hash

**Comment by miohtama** [comment]
Yep, so this is how I handled with MetaMask desktop back in the day. You get the thrown error and then you need to figure out from crappy JavaScript exceptions that do not have a class what kind of an error this was. But if you are not getting an error in the first place then that's an issue.

**Comment by wighawag** [comment]
Yes exactly, the issue is that the promise never resolve, nor reject

**Comment by swkim109** [comment]
It has to be noted that [EIP-1193](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md) exists. This standard says when user rejects request, the Provider should return the status code of 4001. It seems like MetaMask desktop follows this standard.

**Comment by wighawag** [comment]
Any update on this?
This is an issue for user experience and would be great if wallet connect followed EIP-1193 in that regard as @swkim109 mentioned.

**Comment by kamapcrazy** [comment]
same issue on my side.
When user scan qr-code to connect wallet.
And then, they somehow decide to cancel. We cannot catch any errors from client-side in order to take action on it.

**Comment by trylovetom** [comment]
@kamapcrazy same here

**Comment by insky** [comment]
Any updates?

**Comment by finessevanes** [comment]
Hey @kamapcrazy ,@trylovetom ,@insky, @wighawag  are either of you still experiencing this issue?

**Comment by insky** [comment]
> Hey @kamapcrazy ,@trylovetom ,@insky, @wighawag are either of you still experiencing this issue?

Looks like fixed
