### ISSUE TITLE
 {"context": "core"} base64Decode is not a function (it is Object)

### ISSUE THREAD

**Issue by Topdeveloper777** [WalletConnect/walletconnect-monorepo#3752]
"react-native": "0.72.5",
"@walletconnect/jsonrpc-types": "^1.0.3", 
"@walletconnect/react-native-compat": "^2.10.1",
"@walletconnect/web3wallet": "^1.9.1",
I am using that version.
I am getting  `Error for initializing [TypeError: base64Decode is not a function (it is Object)] ` in react native app.
Can you please help me?

**Comment by ganchoradkov** [comment]
hey @Topdeveloper777, please try importing `@walletconnect/react-native-compat` before importing `web3wallet`.
It should apply the correct polyfills
