### ISSUE TITLE
Error: Verify iframe failed to load 

### ISSUE THREAD

**Issue by borderlessdev** [WalletConnect/walletconnect-monorepo#3764]
**Describe the bug**
So, i'm trying to use the Beacon Wallet from Tezos, but it gives me 2 errors, and i can't use any function from Beacon Wallet.
The error occurs when the page is loaded, so i can't do nothing. I already seen another people with the same problem, but i was unable to find the solution to it.
The error is: 
`{context: 'core/verify-api'} 'Verify iframe failed to load: https://verify.walletconnect.org'`
and
`{context: 'core/verify-api'}context: "core/verify-api"[[Prototype]]: Object 'verify iframe load timeout'
`
I already make the verification from this guide: https://docs.walletconnect.com/cloud/verify, but still the same problem.

**Screenshots**

![error](https://github.com/WalletConnect/walletconnect-monorepo/assets/143446000/d27589be-406d-4dbb-bbac-ca06e4641d04)

**Additional context**
I'm building a Bubble.io plugin. I webpacked the @taquito/beacon-wallet and i'm using by `<script>` tag on Bubble. I know the lib is working fine because i can console.log the lib and shows all functions, but no one works because the error.

**Comment by glitch-txs** [comment]
They need to update WalletConnect dependency as this has already been fixed on our end

**Comment by borderlessdev** [comment]
> They need to update WalletConnect dependency as this has already been fixed on our end

Ok, thanks!
