### ISSUE TITLE
Can't make changes to project explorer on https://cloud.walletconnect.com/

### ISSUE THREAD

**Issue by muratogat** [WalletConnect/walletconnect-monorepo#3784]
Peoject ID: 5f1c1da74b0d79b63c3e5e22e95af92c

When I try to make changes here and click "Create Draft", I get an error.

<img width="792" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/1083315/168c6c64-9262-4e8a-9db3-f3b9e1101a4a">

"new row violates row-level security policy for table \"registry_submission\""

**Comment by Cali93** [comment]
Hey @muratogat, we recently fixed some bugs related to that error.
We were able to convert your listing to a draft. Please re-open this issue to let us know if you're facing any issue.
Sorry for the inconvenience.

**Comment by muratogat** [comment]
When I try to modify and save something in the draft, I still get the error below
<img width="444" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/1083315/4de9ad28-f437-4650-a1a2-b3972b1f80c0">

**Comment by Cali93** [comment]
Hey @muratogat,
We found and fixed the bug, everything should work as expected in our latest deployment.
Thanks for your patience.

**Comment by muratogat** [comment]
Thanks! Working fine now.
