### ISSUE TITLE
OnBoarding  WOOOOCHAIN

### ISSUE THREAD

**Issue by Mr-zohaibkhalid** [WalletConnect/walletconnect-monorepo#3796]
Adding a new chain to the Explorer
To get a new chain added to the Explorer, you will need to submit the following:

JSON-RPC spec for Wallets (only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist). For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
ethereum-rpc compatible
Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
eip155 specs
namespaces:
eip155
chains:
GMBL Main Network: eip155:2064
RPC endpoints
WOOOCHAIN Main Network: https://dataseed.woooo.world/
[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type:
60
Additional context
Website: https://block.woooo.world/

**Comment by JonathanConn** [comment]
@Mr-zohaibkhalid I need more info from you on this, please go over our requirements again

You can use these [completed PR's](https://github.com/WalletConnect/walletconnect-monorepo/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3A%22type%3A+new+chain+request%22+is%3Aclosed) as reference

**Comment by Mr-zohaibkhalid** [comment]
Hi, Thanks for your response, I updated the information kindly review it again.

**Comment by bkrem** [comment]
Above URLs are either 404'ing or not resolving at all. Closing.
