### ISSUE TITLE
An uncaught exception when pairing with a WC v1 URI

### ISSUE THREAD

**Issue by katspaugh** [WalletConnect/walletconnect-monorepo#3813]
When calling `web3Wallet.core.pairing.pair({ uri })` with a v1 URI, it throws an uncaught excpetion even if the `pair` call itself is caught.

<img width="1250" alt="Screenshot 2023-10-23 at 11 10 32" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/381895/04f5b909-10a9-44e4-891c-fe90accff56a">

This can be reproduced when connecting for example to 1inch with their v1 link.

I realize v1 isn't supported but this error should be probably handled properly. Please let me know if I'm missing something, maybe this exception can be caught on our side.

**Comment by katspaugh** [comment]
My bad, the error is propagated by the SDK correctly.

**Comment by amiryadid-fb** [comment]
Hey @katspaugh ,
I'm not from the WC team, but I'm pretty sure V1 is deprecated and can no longer be used using WC bridge

**Comment by katspaugh** [comment]
I know that but it shouldn't throw an uncaught exception. The promise returned by `web3Wallet.core.pairing.pair` should be rejected instead.
