### ISSUE TITLE
Wallet connect inside an iframe

### ISSUE THREAD

**Issue by manish252488** [WalletConnect/walletconnect-monorepo#3816]
### Discussed in https://github.com/orgs/WalletConnect/discussions/3793

<div type='discussions-op-text'>

<sup>Originally posted by **manish252488** October 17, 2023</sup>
I have integrated a wallet connected inside an iframe. when the iframe is launched in ios, Wallet Connect is not able to detect any wallet that's installed in the mobile. it shows the cross origin error 
Blocked a frame with origin "https://my-iframe.domain.net" from accessing a frame with origin "https://verify.walletconnect.com" Protocols, domains, and ports must match.
</div>

**Comment by manish252488** [comment]
@janus @julien51 @bpierre @miohtama can someone help on this.

**Comment by ZeroTimeDrift** [comment]
I'm having similar issues with the iFrame integration where iOS deeplinks are failing but no console errors on clicks. I've assigned perms to iFrame sandbox attribute to allow scripts etc but still facing the same issue

**Comment by ganchoradkov** [comment]
@manish252488, the SDK works fine in an iframe but that depends on the user's browser settings. If 3rd party cookies are disabled, the SDK can't store any data. 
One way to approach this is by implementing custom storage and communication channel between the main window and the iframe instance where SDK stores and retreaves data from the main (parent window) and thus provide persistence. 

We'll look into ways to make it easier though. 
Closing as not planned for now

**Comment by ZeroTimeDrift** [comment]
@ganchoradkov 
I am using Rainbowkit which utilises WC2, from WC side, how would I go about getting the data needed to store / building custom storage unit? I have access to the parent
