### ISSUE TITLE
Error: Socket stalled when trying to connect to wss://relay.walletconnect.com

### ISSUE THREAD

**Issue by ZeroTimeDrift** [WalletConnect/walletconnect-monorepo#3817]
**Describe the bug**
Getting Error: Socket stalled when trying to connect to wss://relay.walletconnect.com when pressing WalletConnect option in Rainbowkit modal

Project ID is being defined in the query params, running Chrome, no proxy / server or firewall blocking requests. 

The app is a nextjs app running wagmi v1.4.5, rainbowkit v1.1.3 and walletconnect v2

**Comment by ZeroTimeDrift** [comment]
Update to this issue, seems to be working on safari, also on chrome incognito mode - but does not work on my main chrome instance - similar issue experienced with others who have multiple wallets

**Comment by ganchoradkov** [comment]
hey @ZeroTimeDrift do you have any VPN extensions or something like that? This error means the SDK has trouble connecting to the relay

**Comment by ZeroTimeDrift** [comment]
@ganchoradkov not at all. Weirdly enough, the modal appears on Safari / Brave but comes up with a separate issue of postMessage 

`Unable to post message to https://verify.walletconnect.com. Recipient has origin https://wallet.moongate.one.`

**Comment by devsone** [comment]
Have the same problem here on all browsers. (definitely it's my network issue)
And you are right @ganchoradkov, the issue is SDK cannot connect to the relay.
The thing is it's breaking the whole app which is not good I believe, maybe it's possible to add an onError function, so we can take care of errors on our side.
right now if it's not possible for SDK to connect to the relay server, the whole app crashes and there is nothing you can do to prevent it (like the screenshot)

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/24278830/5316590c-fe81-4812-9db4-ba5e3b994eda)

**Comment by ganchoradkov** [comment]
hey @devsone, you can catch this error when initializing the SDK with `.init()`

**Comment by yucheng-Li** [comment]
> Have the same problem here on all browsers. (definitely it's my network issue) And you are right @ganchoradkov, the issue is SDK cannot connect to the relay. The thing is it's breaking the whole app which is not good I believe, maybe it's possible to add an onError function, so we can take care of errors on our side. right now if it's not possible for SDK to connect to the relay server, the whole app crashes and there is nothing you can do to prevent it (like the screenshot)
> 
> ![image](https://private-user-images.githubusercontent.com/24278830/280011978-5316590c-fe81-4812-9db4-ba5e3b994eda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NjkwNTksIm5iZiI6MTcxNzQ2ODc1OSwicGF0aCI6Ii8yNDI3ODgzMC8yODAwMTE5NzgtNTMxNjU5MGMtZmU4MS00ODEyLTlkYjQtYmE1ZTNiOTk0ZWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDAyMzkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNDBiMTgxOTRjMTlkMzhiNTg4NjdmNzE1OTI5M2I2MDU3ZTRmMzk0MjM0YWVlYjE4MzZmZTM0YzAwYWUyNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eZ3nmJwlkcBvCktLhSoG0PQgQLVZXlW0PWxJuKFVZHk)

Thank you your advice, i change  "@walletconnect/react-native-compat" version  2.9.0 -> 2.11.0, it work. It's not breaking the whole app now.
