### ISSUE TITLE
Sintayew333

### ISSUE THREAD

**Issue by Inatiye33** [WalletConnect/walletconnect-monorepo#3824]
### Discussed in https://github.com/orgs/WalletConnect/discussions/3742

<div type='discussions-op-text'>

<sup>Originally posted by **rony-arnac** October  5, 2023</sup>
Hey,

I set my Web3Wallet 

```
    core = new Core({
      // @notice: If you want the debugger / logs
      // logger: 'debug',
      projectId: Config.ENV_PROJECT_ID,
      relayUrl: Config.ENV_RELAY_URL,
    });
    
    web3wallet = await Web3Wallet.init({
      core,
      metadata: {
        ...
      },
    });
```

and I call pair using

```
core.pairing.pair({ uri: params.uri });
```

When I try to connect to walletconnect v1, which is of course not supported, I see the error in metro

```
 ERROR  {"context": "core"} {"context": "core/relayer"} {"context": "core/relayer/subscription"} [Error: Relay Protocol not supported: undefined]
 WARN  Possible Unhandled Promise Rejection (id: 12):
Error: Relay Protocol not supported: undefined
Error: Relay Protocol not supported: undefined
...
```

but I can't find a way to catch this error and indicate that the DApp is using an old version of welletconnect.

How can I catch those errors? 
Tried wrapping both initialization and pairing with `try {} catch {}`, but it didn't help.

Thanks!</div>

**Comment by Inatiye33** [comment]
Duplicate of #

**Comment by glitch-txs** [comment]
The fix is in the comments of that discussion
