### ISSUE TITLE
using @walletconnect/web3-provider‘s setup that throw a error -->this.send is not a function

### ISSUE THREAD

**Issue by ShowPenZ** [WalletConnect/walletconnect-monorepo#384]
hello there!
my @walletconnect/web3-provider version: 1.3.1
       web3  version: 1.3.0

I ran @walletconnect/web3-provider using the example provided in the  documentation and found an error
![image](https://user-images.githubusercontent.com/25929987/98901722-36329380-24ef-11eb-9937-9fbbd61638c9.png)
![image](https://user-images.githubusercontent.com/25929987/98901759-434f8280-24ef-11eb-9cae-75bc74696934.png)
I followed the steps provided in the diagram and got an error.
![image](https://user-images.githubusercontent.com/25929987/98901907-8a3d7800-24ef-11eb-831b-55a7c81b5b2e.png)
I hope to hear from you.
respectfully !

**Comment by shendel** [comment]
hard temp fix
window.send = (e,t) => { return provider.send(e,t) }

**Comment by davidp94** [comment]
It seems the issue is coming from `util.callbackify` and the `this` binding of `this.request()` function

By changing  https://github.com/WalletConnect/walletconnect-monorepo/blob/next/packages/providers/web3-provider/src/index.ts#L176-L178

to 

```
  request = async (payload: any): Promise<any> => {
    return this.send(payload);
  }
```

It fixed the problem.

**Comment by ShowPenZ** [comment]
> hard temp fix
> window.send = (e,t) => { return provider.send(e,t) }

thx bro!

**Comment by ShowPenZ** [comment]
> It seems the issue is coming from `util.callbackify` and the `this` binding of `this.request()` function
> 
> By changing https://github.com/WalletConnect/walletconnect-monorepo/blob/next/packages/providers/web3-provider/src/index.ts#L176-L178
> 
> to
> 
> ```
>   request = async (payload: any): Promise<any> => {
>     return this.send(payload);
>   }
> ```
> 
> It fixed the problem.

got it! thx bro!

**Comment by miohtama** [comment]
Here is a detailed explanation of web3.js change that causes the issue https://github.com/ethereum/web3.js/pull/3649#issuecomment-695200876

Here is a link to open web3.js bug regarding this https://github.com/ethereum/web3.js/issues/3790

**Comment by pedrouid** [comment]
is this still an issue?

**Comment by shendel** [comment]
@pedrouid 
if you look at the code from this comment (https://github.com/WalletConnect/walletconnect-monorepo/issues/384#issuecomment-726708434) - then I think yes ...

for example, in my project I still use this crutch (https://github.com/WalletConnect/walletconnect-monorepo/issues/384#issuecomment-726705538)

**Comment by pedrouid** [comment]
Thanks @shendel I will include a fix for this in the next release on Monday 👍

**Comment by 8bu** [comment]
> 
> 
> It seems the issue is coming from `util.callbackify` and the `this` binding of `this.request()` function
> 
> By changing https://github.com/WalletConnect/walletconnect-monorepo/blob/next/packages/providers/web3-provider/src/index.ts#L176-L178
> 
> to
> 
> ```
>   request = async (payload: any): Promise<any> => {
>     return this.send(payload);
>   }
> ```
> 
> It fixed the problem.

Bro pls make a PR to resolve this pain in the ass

**Comment by finessevanes** [comment]
@shendel was this issue resolved?
