### ISSUE TITLE
Errors in Incognito Mode around requireLocalStorage 

### ISSUE THREAD

**Issue by cryptoKevinL** [WalletConnect/walletconnect-monorepo#3846]
I have an issue which I think is stemming from WalletConnect in Incognito mode.

Example application/integration of our iFrame based WalletChat widget: 

https://gooddapp.org/#/swap

1) connect wallet to main website
2) click on the chat widget in lower right
3) sign-in (only uses SIWE - no gas)

This works fine in Brave, Chrome, etc...but in Incognito mode it does not.  I get this error:

```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://staging.walletchat.fun/assets/index-72f363dd.js:1525:8605
    at requireLocalStorage (https://staging.walletchat.fun/assets/index-72f363dd.js:1525:8781)
    at https://staging.walletchat.fun/assets/index-72f363dd.js:1525:9865
 ```
 
 Upon further investigation, we have no functions/code with this function _requireLocalStorage_ in it.  Not even within node_modules.  Its only after build/packing this function exists, and it appears its around code regarding _safe_json_utils_, which seems to be a **WalletConnect** repo: 

https://github.com/pedrouid/safe-json-utils

Also searching for _requireLocalStorage_ in all of GitHub code mainly returns results in WalletConnect repos.

I'm wondering if there are any known issues using WalletConnect in this way, if this "requireLocalStorage" function is part of WalletConnect in some way, and how we can get some try/catch error handling around this so the site doesn't simply crash when using this in incognito mode.

**Comment by cryptoKevinL** [comment]
@glitch-txs tagging per your request in Discord.

**Comment by glitch-txs** [comment]
hi @cryptoKevinL could you try [here](https://web3modal.com/)? I'm able to connect in incognito, I think this is not related to WalletConnect

**Comment by cryptoKevinL** [comment]
> hi @cryptoKevinL could you try [here](https://web3modal.com/)? I'm able to connect in incognito, I think this is not related to WalletConnect

I can see that same error doesn't happen there, but there is no iFrame in play in that website.  I'm wondering if WC is blocking anything when it comes to an iFrame.  

Secondly, you see no reason that "requireLocalStorage" comes from WC or a WC imported module?

If not you can close the issue, but I can't see where this code is coming from.

**Comment by glitch-txs** [comment]
Seems to be related to the browser's configuration, we use localStorage as well as wagmi does
https://stackoverflow.com/questions/30481516/iframe-in-chrome-error-failed-to-read-localstorage-from-window-access-deni

**Comment by cryptoKevinL** [comment]
Yeah, I understand its likely because we have an iFrame which is trying to read its own local storage (not cross-domain), but also things like WalletConnect getting loading in an iFrame would have the same effect, but I can't tell if your source or things WC pulls in have try/catch around localStorage access attempts (it appears it does not, which is why we are having the issue).  

The hard part is that any localStorage access we use are wrapped in try/catch and this `requireLocalStorage` is getting pulled in only after a VITE build.  Its packed near safeJsonUtils which seemed like a WalletConnect thing?  

Do you have any examples of projects using WC within an iFrame?

If not, go ahead and close the issue.  Thanks for the help.

**Comment by ganchoradkov** [comment]
@cryptoKevinL you can solve the issue by enabling `Block third-party cookies in Incognito mode` for the time being. We're looking into other long term solutions with the team
