### ISSUE TITLE
No internet connection detected. Please restart your network and try again

### ISSUE THREAD

**Issue by jaan1025** [WalletConnect/walletconnect-monorepo#3855]
**Describe the bug**
<img width="566" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/22076610/6984e1e0-67ac-4eae-b4e9-1c5dfca708ef">
<img width="761" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/22076610/934f58fb-947a-4899-9a33-486217372443">
<img width="593" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/22076610/6b358959-1820-4d63-8676-86a527d32e5f">

**SDK Version (if relevant)**
 - Client: JS
 - "@walletconnect/ethereum-provider": "^2.8.5"
 - "@walletconnect/modal": "^2.5.6"

**Comment by ganchoradkov** [comment]
hey @jaan1025, this error is thrown when the browser's navigator says you're offline. Please update the ethereum provider to latest and try again
