### ISSUE TITLE
Error 1009 for Ukraine \ Modal 

### ISSUE THREAD

**Issue by Soniachniy** [WalletConnect/walletconnect-monorepo#3856]
**Describe the bug**
A walletconnect.com isn't accessible from Ukraine
Ray ID: 81eb14cc7d8d24b6 • 2023-10-31 10:05:43 UTC

<img width="1749" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/26657914/2a386d8e-7ad8-4696-98c3-17eab4cafecd">

**Expected behavior**
Working fine

**Wallet connect**
- walletconnect.com is not working
- V2 modal on the site isn't working at all, there is a lot of errors in console (we are using viem and wagmi and seems that request are failed because of that.)
- V3 modal works fine, but have some errors 

For v2 I see next errors
<img width="1322" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/26657914/e3721883-e477-432c-8cce-aa67bce38f51">
<img width="1320" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/26657914/930cb8d5-f6f8-4cd7-b7df-26181a96e6ab">

For v3 just 
<img width="1208" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/26657914/06db644f-07ee-452e-bf3c-fa41f952e199">

**Comment by glitch-txs** [comment]
Please read here
https://github.com/orgs/WalletConnect/discussions/3862
