### ISSUE TITLE
"Failed to execute 'setItem' on 'Storage'" [bug]

### ISSUE THREAD

**Issue by alexanderpehlivanov** [WalletConnect/walletconnect-monorepo#3860]
### Link to minimal reproducible example

// Libraries import { useWeb3Modal, useWeb3ModalState } from "@web3modal/wagmi/react"; import { useAccount } from "wagmi";   const { open } = useWeb3Modal();   const { open: isOpen } = useWeb3ModalState();

### Summary

{context: 'client'}
 "Failed to execute 'setItem' on 'Storage': Setting the value of 'wc@2:core:0.3//keychain' exceeded the quota."

app-index.js:31 Error: Failed to execute 'setItem' on 'Storage': Setting the value of 'wc@2:core:0.3//keychain' exceeded the quota.
    at eval (webpack-internal:///(terminal/app-pages-browser)/./node_modules/@walletconnect/ethereum-provider/dist/index.es.js:14:3433)
    at async n (webpack-internal:///(terminal/app-pages-browser)/./node_modules/@walletconnect/ethereum-provider/dist/index.es.js:14:3253)

DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'wagmi.store' exceeded the quota.
    at Object.setItem (webpack-internal:///(app-pages-browser)/./node_modules/@wagmi/core/dist/chunk-TSH6VVF4.js:423:19)
    at setItem (webpack-internal:///(app-pages-browser)/./node_modules/zustand/esm/middleware.mjs:483:20)
    at api.setState (webpack-internal:///(app-pages-browser)/./node_modules/zustand/esm/middleware.mjs:491:10)
    at Config.setState (webpack-internal:///(app-pages-browser)/./node_modules/@wagmi/core/dist/chunk-TSH6VVF4.js:539:16)
    at connect (webpack-internal:///(app-pages-browser)/./node_modules/@wagmi/core/dist/chunk-TSH6VVF4.js:744:13)
    at async Object.connectWalletConnect (webpack-internal:///(app-pages-browser)/./node_modules/@web3modal/wagmi/dist/esm/src/client.js:68:17)
window.console.error @ app-index.js:31
console.error @ hydration-error-info.js:45
overrideMethod @ console.js:213
setItem @ chunk-TSH6VVF4.js:350
setItem @ middleware.mjs:474
api.setState @ middleware.mjs:482
setState @ chunk-TSH6VVF4.js:464
connect @ chunk-TSH6VVF4.js:669
await in connect (async)
connectWalletConnect @ client.js:58
connectWalletConnect @ ConnectionController.js:24
initializeConnection @ index.js:39
initializeConnection @ index.js:69
setInterval (async)
W3mConnectingWcView @ index.js:20
_clone @ lit-html.js:665
_commitTemplateResult @ lit-html.js:970
_$setValue @ lit-html.js:826
_update @ lit-html.js:718
_commitTemplateResult @ lit-html.js:966
_$setValue @ lit-html.js:826
render @ lit-html.js:1432
update @ lit-element.js:122
performUpdate @ reactive-element.js:836
scheduleUpdate @ reactive-element.js:751
__enqueueUpdate @ reactive-element.js:724
await in __enqueueUpdate (async)
requestUpdate @ reactive-element.js:687
set @ reactive-element.js:308
onViewChange @ index.js:87
await in onViewChange (async)
eval @ index.js:20
eval @ utils.mjs:10
eval @ vanilla.mjs:242
Promise.then (async)
listener @ vanilla.mjs:239
eval @ vanilla.mjs:66
notifyUpdate @ vanilla.mjs:66
set @ vanilla.mjs:173
push @ RouterController.js:14
onConnectWallet @ index.js:209
eval @ index.js:178
handleEvent @ lit-html.js:1300
Show 1 more frame
Show less

### List of related npm package versions

"@web3modal/wagmi": "^3.2.0"
"wagmi": "^1.4.5"
"viem": "^1.18.0"

**Comment by tommasini** [comment]
Same error here, it was working and then that error began to appear.

I'm not using wagmi, I'm using `@web3modal/ethers5/react`

**Comment by petermazzocco** [comment]
Recently experiencing the same issue as well. I think the common factor is related to wagmi not getting along with TanStack/React Query. Are you using it in your application?

Here is a similar bug via wagmi: [https://github.com/wagmi-dev/wagmi/issues/2182](url)

**Comment by ganchoradkov** [comment]
Hey, this issue is resolved in https://github.com/WalletConnect/walletconnect-utils/pull/142 as is pending release. We're moving away from localStorage to indexDB. Additionally, to resolve your current situation, please wipe out localstorage
