### ISSUE TITLE
We don't support the chainId you provided: eip155:5611

### ISSUE THREAD

**Issue by zwht** [WalletConnect/walletconnect-monorepo#3871]
opBNB Test could not connect with error:
We don't support the chainId you provided: eip155:5611

Request URL:https://rpc.walletconnect.com/v1/?chainId=eip155:5611&projectId=8f3db6c2aa7bfda5ae6b943d8bf904c1
Request Method:POST
Status Code:400 Bad Request
Remote Address:127.0.0.1:7890
Referrer Policy:strict-origin-when-cross-origin

**Comment by glitch-txs** [comment]
Can you add more information? Which library are you using?
