### ISSUE TITLE
May be you are fix this and merge changes to master before close???

### ISSUE THREAD

**Issue by shendel** [WalletConnect/walletconnect-monorepo#389]
I'm at a loss
you have a clear error in your code
you wrote a solution
but haven't made changes to your repo

https://github.com/WalletConnect/walletconnect-monorepo/issues/384

**Comment by shendel** [comment]
@pedrouid

**Comment by shendel** [comment]
@pmprete , I apologize, the author closed the issue, but you probably did not see him, please make changes

**Comment by shendel** [comment]
@pedrouid , I apologize, the author closed the issue, but you probably did not see him, please make changes

**Comment by miohtama** [comment]
Please use Discord for discussion. This is an issue tracker, not a discussion medium.

**Comment by miohtama** [comment]
Also "clear error in your code" is not an error in WalletConnect code, so please cool down your head before starting a discussion.
