### ISSUE TITLE
Unable to list NFT on Blur marketplace via using WalletConnect on MetaMask app

### ISSUE THREAD

**Issue by nggg4** [WalletConnect/walletconnect-monorepo#3893]
Unable to list NFT on Blur via using WalletConnect on MetaMask app

**To Reproduce**
1. Go to blur.io website
2. Connect via using WalletConnect
3. Scan QR login via my MetaMask App
4. Head to portfolio and list my NFT
5. Result in USER REJECTED error message, **_note: buying item, accepting bid, withdrawal and deposit blur pool balance are working fine._**

**Expected behavior**
Hoping the team can look into it.

**Screenshots**
I have video recording ready, how can I send it?

**Desktop (please complete the following information):**
 - OS: Windows and Mac
 - Browser: chrome
 - Version 118.0.5993.117 (Official Build) (arm64)

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: Latest as of writing
 - Browser MetaMask App

**Additional context**
NA

**Comment by nggg4** [comment]
Placing trait bid will not jump to any MetaMask wallet prompts as well (error).

**Comment by glitch-txs** [comment]
Please forward this to Blur support, we need some code implementation to be able to look into it. Thanks! 👍
