### ISSUE TITLE
Need help with failed transaction on Polygon PoS v3

### ISSUE THREAD

**Issue by pavel-bilous** [WalletConnect/walletconnect-monorepo#3897]
### Discussed in https://github.com/orgs/WalletConnect/discussions/3896

<div type='discussions-op-text'>

<sup>Originally posted by **pavel-bilous** November  9, 2023</sup>
Hi,

I have initiated swap to get SUSHI coins but for some reason transaction got stuck and I no longer have original coins nor SUSHI coins. Can someone look into this?

Here are the two transactions in question:

MetaMask wallet has status of Dropped for both:
0x8fda4f94a65f2d31a5fb090a9b5571242cd9842bb4d2c17f56e33ee66b9af38f
0x3d2dee4124ec5d3f7842716e4954934ed8fae702fa9690fedf8276d3e3186329

And here are the original failed one from the MetaMask:
0x21291eacf592c055ca30ab4d859123b6694cd7d18911734ad43a98354af31846

From the transaction history on AAVE:
https://polygonscan.com/tx/0x6a1b6b264712d770964f279644f3314b43a4b4d225c1d2719b0e13734c643b9a
https://polygonscan.com/tx/0x6f5e2658f19e163a34a2d41ea862a42167d0221966b40f5e7386540601e0625a

Thank you</div>

**Comment by ganchoradkov** [comment]
closing as we don't have any control over how transactions are submitted to the blockchain. The issue should be raised with the dapp used - that prepared the transaction payload & the signing wallet
