### ISSUE TITLE
Add Ergo blockchain

### ISSUE THREAD

**Issue by gagarin55** [WalletConnect/walletconnect-monorepo#3905]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
   **GitHub Link**: https://github.com/ergoplatform/ergo/blob/master/src/main/resources/api/openapi.yaml
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   **GitHub Link**:https://github.com/ChainAgnostic/namespaces/pull/98
3. **namespaces**:
   ergo
4. **chains**:
   `ergo:b0244dfc267baca974a4caee06120321 ` - mainnet
   `ergo:e7553c9a716bb3983ac8b0c21689a1f3 ` - testnet
5. **RPC endpoints**
   https://docs.ergoplatform.com/dev/Integration/guide/#node
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
   429

**Additional context**
Add any other context here.

---

**Please note:**

**Registering a chain with the Explorer does not impact or improve the ability for wallets and dapps to support your chain.** It is simply a way for users to discover wallets and dapps that support your chain by:

- Browsing the [Chains List](./chain-list.md)
- Filtering results programmatically via the [Explorer API](../../cloud/explorer.md)

**It is still up to wallets and dapps to provide concrete support for your chain once it is listed as part of the Explorer.**

- [x] I have read and understood the above clarification

**Comment by bkrem** [comment]
Thanks for your submission 🙏 

We need the CASA namespace spec to be accepted & merged before we can add the namespace + its chains to the Cloud app.

Please re-ping us here once this is the case and we will continue here 👍

**Comment by bkrem** [comment]
Looks like we're close on merging the CASA spec here? cc @bumblefudge
