### ISSUE TITLE
Double session proposal event

### ISSUE THREAD

**Issue by aditbisa** [WalletConnect/walletconnect-monorepo#3906]
**Describe the bug**
We use `SignClient` from backend and store the session proposal to our database.
We rely on `session_proposal` event for this.

But the `session_proposal` event called twice on new pairing.

Fortunately, our Dapp add `sessionProperties` into the proposal.
And we are able to identify the culprit of this double `session_proposal` event.
Its this [`onPairingCreated` function](https://github.com/WalletConnect/walletconnect-monorepo/blob/124a174d2dd905560b80e8a2c21bf27421482d4b/packages/sign-client/src/controllers/engine.ts#L1099C32-L1099C32) where it call `onSessionProposeRequest` with imitation data from the relay.

Our `session_proposal` handler receive 2 data:
1. From the relay with custom `sessionProperties`
2. From `onPairingCreated` without it

**SDK Version (if relevant)**
 - Client: JS
 - Version: 2.10

**To Reproduce**
1. From Wallet SignClient, listen `session_proposal` and dump the data.
2. Connect new Dapp
3. See double data from `session_proposal` handler

**Expected behavior**
`onPairingCreated` should not compose the proposal by itself.

**Screenshots**
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/16781093/f6699d5c-5fd1-4def-8ddc-d5b35f4c1e21)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: NodeJs

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ganchoradkov** [comment]
resolved with https://github.com/WalletConnect/walletconnect-monorepo/pull/3944
