### ISSUE TITLE
this.events.off is not a function (it is undefined) after two minutes

### ISSUE THREAD

**Issue by earthflower** [WalletConnect/walletconnect-monorepo#3913]
In react-native `this.events.off is not a function (it is undefined)` bug is coming randomly and usually after 2 minute after connecting `core.pairing.pair`.

**SDK Version (if relevant)**
 - Client: React Native
 - Version 
 ```
    "@walletconnect/core": "2.10.4",
    "@walletconnect/encoding": "^1.0.2",
    "@walletconnect/jsonrpc-types": "^1.0.3",
    "@walletconnect/react-native-compat": "2.10.4",
    "@walletconnect/utils": "2.10.4",
    "@walletconnect/web3wallet": "^1.9.3", 
```

**To Reproduce**
Install a new react native app from wallet connect demo app from wallet connect official repo(https://github.com/WalletConnect/react-native-examples) and wait for two minutes.

**Expected behavior**
Wallet connect should provide option to retry connection in case of any known error like this

**Screenshots**
<img width="467" alt="Screenshot 2023-11-13 at 10 36 02 AM" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/85003405/65516886-3001-4e82-9752-702009ba8997">

**Comment by ganchoradkov** [comment]
hey @earthflower are you importing `react-native-compat` before any other `@walletconnect` package as per the docs? Its required so all RN polyfills can be applied

**Comment by earthflower** [comment]
Yes! I am importing `react-native-compat` on line 1 of react native expo prebuild application. The wallet connections and sign request are working with demo [apps](https://react-app.walletconnect.com/) But, the mentioned issue with screenshot comes around 2 minutes after keeping the react native app open.

**Comment by ignaciosantise** [comment]
Hey @earthflower 👋 i wasn't able to reproduce the issue. Could you provide a public repo with the reproducible issue?

**Comment by earthflower** [comment]
Sure. Will get back

**Comment by dohooo** [comment]
> Sure. Will get back

The same problem but I just removed this import then everything works well.

Some extra information: I imported the `@walletconnect/react-native-compat` package to follow the other package's instructions then I can't sign in with any wallet.

**Comment by peterpeterparker** [comment]
I've got the same issue when I connect my local dev environment (SvelteKit application). The issue does not occurs on mainnet. 

As a workaround, I dowgraded `@walletconnect/web3wallet` from 1.9.5 to 1.9.1 to resolve the issue.
Seems that I also face the issue with 1.9.3.

**Comment by glitch-txs** [comment]
Hi everyone, please provide a minimal reproducible example so we can test the issue, closing for now for lack of information. Feel free to reopen with a MRE. Thanks!

**Comment by peterpeterparker** [comment]
I have provided a minimal sample repo to reproduce the issue and opened a new issue to share my findings: https://github.com/WalletConnect/walletconnect-monorepo/issues/4064

**Comment by shan-c** [comment]
Hi @earthflower. Im facing the same issue. Did you find any fix or workaround for this ?

**Comment by peterpeterparker** [comment]
@glitch-txs you reopened and then completed the task without any link to a PR or commit. Out of curiosity, how did you resolved the issue?

**Comment by earthflower** [comment]
Still looking for fix for this. I am trying to catch when this.events.off message comes to auto-reconnect. But, I am not able to catch the error using `try catch` js methods

**Comment by niklasnatter** [comment]
Hey everybody, we encountered a similar issue today and summarised how we solved it here: https://github.com/WalletConnect/walletconnect-monorepo/issues/4064#issuecomment-2072629887
