### ISSUE TITLE
Walletconnect v2 does not work on Firefox, indicating that the wss cannot be established

### ISSUE THREAD

**Issue by wlasd4622** [WalletConnect/walletconnect-monorepo#3922]
https://react-wallet.walletconnect.com/walletconnect

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/14228049/c4ed5515-f9b0-49c4-8ebb-47a0720e70fb)

**Comment by ganchoradkov** [comment]
hey @wlasd4622, do you have any VPNs running that might be preventing the connection?

**Comment by afagdrawer1** [comment]
No
