### ISSUE TITLE
Add BXN (both testnet and mainnet)

### ISSUE THREAD

**Issue by BlackFortGroup** [WalletConnect/walletconnect-monorepo#3923]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

3. **namespaces**:
   _\*known chain namespaces (e.g. eip:155 for Ethereum/EVM-based chains, solana, ...)_
   eip:155
   
4. **chains**:
   _\*known chains, where the primary key is a compound key composed of namespace + reference (e.g. ETH mainnet is eip155:1)._
   _Please provide labels for each chain (e.g. mainnet, testnet, devnet, ...)_
   eip155:4777 (BXN Testnet)
   eip155:4999 (BXN Mainnet)
   
5. **RPC endpoints**
   _\*list of common/canonical RPC endpoints for the chain(s)_
   https://testnet.blackfort.network/rpc (for testnet)   
   https://mainnet.blackfort.network/rpc (for mainnet)
   
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
   _\* slip44 coin type used in the namespace_
   
   0x80001387 (for mainnet)
   0x80000001 (for testnet)

**Additional context**
Add any other context here.

---

**Please note:**

**Registering a chain with the Explorer does not impact or improve the ability for wallets and dapps to support your chain.** It is simply a way for users to discover wallets and dapps that support your chain by:

- Browsing the [Chains List](./chain-list.md)
- Filtering results programmatically via the [Explorer API](../../cloud/explorer.md)

**It is still up to wallets and dapps to provide concrete support for your chain once it is listed as part of the Explorer.**

- [x] I have read and understood the above clarification

**Comment by BlackFortGroup** [comment]
Hello @JonathanConn, I see you're responsible for verifying network requests, please check ours. It has been waiting for a week already

**Comment by JonathanConn** [comment]
~~I will take a look today for you 👍~~
 
 Did not have time yesterday, the team will handle this today instead @BlackFortGroup

**Comment by bkrem** [comment]
Thanks for your submission :pray:

The chains have been added to https://cloud.walletconnect.com/
