### ISSUE TITLE
Mobile deeplinking keeps selected wallet

### ISSUE THREAD

**Issue by pacwoodson** [WalletConnect/walletconnect-monorepo#394]
When using the mobile deeplinking, WalletConnect seems to store the mobile wallet selected, but doesn't allow for changing it.

It means that once a mobile wallet is selected from the qrcode-modal, we cannot ever use another wallet again. 
I would suggest to first disable this feature, as a user may want to connect to different wallets on differents apps. 
In a second step, think about a better UX for allowing users to reset/change that stored parameter.

https://github.com/WalletConnect/walletconnect-monorepo/blob/e003b44333ea519d40897aba6c9c2d931b3c5f72/packages/helpers/qrcode-modal/src/browser/components/MobileLinkDisplay.tsx#L26

**Comment by pacwoodson** [comment]
Up here @pedrouid, after seeing #444 

It is impossible to switch to another wallet once we selected one in the wallet connect mobile modal.

The only workaround I found for now in my app is to clear all users local storage, which is not super convenient.

Could you please either disable this feature, or allow to clear the choice.

**Comment by shmuel-web** [comment]
@pedrouid 
same here
I cant switch the account

at the very least give us a warning in the docs ;)

**Comment by Knaackee** [comment]
@pakokrew good information!

Since it is almost silent here and the problem seems to still exist, i digged a little deeper and there are actually two settings that get stored in local storage. 
So the workaround for me is to delete these two from local storage before connect. 
With this, off course, the other information stored in local storage still exists.

```
window.localStorage.removeItem('walletconnect');

window.localStorage.removeItem(
  'WALLETCONNECT_DEEPLINK_CHOICE'
);
```

**Comment by finessevanes** [comment]
Is this still an issue? @pakokrew @shmuel-web
