### ISSUE TITLE
WalletConnect Safe App doesn't resolve when sending transactions

### ISSUE THREAD

**Issue by xaler5** [WalletConnect/walletconnect-monorepo#3942]
**Describe the bug**

Gnosis Safe native WalletConnect App doesn't resolve the `eth_sendTransaction` if there's more than one signer or if the unique signer does the sign and the execute in two separate steps.

I'm testing using `ethereum-provider` subpackage on its latest version and injecting it through ethersjs.

Notice that the transaction trough Safe Wallet it is executed and works well, the only thing not working is that WalletConnect doesn't resolve, making any app to just hang on the response.

**To Reproduce**
1. Go to testnet on Uniswap (I tried on Sepolia) and connect with wallet connect to a Gnosis Safe 
2. Trade any amount of any token and submit the tx. This will open a modal in Uniswap that will wait for the tx to resolve (wallet connect to answer back)
3. Tx is received on the Safe, sign without executing
4. Execute on a separate step (after signing) 
5. Tx is executed but Uniswap just hangs there forever

**Expected behavior**

Uniswap should resolve. Issue is not on Uniswap as I'm experiencing the same issue on my local development. WalletConnect should clearly resolve the call.

**Screenshots**

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/20795374/88c1386d-cd73-4dbe-b6dd-198a71cee4f9)

**Additional context**

Notice that if there's only one signer and the tx is signed and executed in one step, WalletConnect will resolve correctly.

**Comment by ganchoradkov** [comment]
hey @xaler5, thanks for the report. The default request expiry is 5 minutes. Meaning that if it takes longer than 5 minutes to sign a transaction, the wallet will be unable to respond. How long it takes you to sign it with multiple signers?

>Uniswap just hangs there forever

if its longer than 5 minutes, uniswap should show the rejection of the request. Is that not the case?

**Comment by xaler5** [comment]
Hey @ganchoradkov 

I didn't know about the 5 minutes expiration, but I wonder if that's enough considering that a multisig might require several signers.

Anyway in this case the 5 minutes limitation is not the case as it can be reproduced in less than one minute by having just one signer doing sign and execute in two steps. 

I still think it has to do with the two different cases, if the sign and execution is done in two steps it seems that WalletConnect gets lost in resolving.

**Comment by xaler5** [comment]
Update:

I just repeated the test. 

In under 2 mins I:
- Triggered a swap
- Signed it in Gnosis Safe
- Execute it in Gnosis Safe Queue
- Waited it for it to be confirmed and indexed in Gnosis Safe

Uniswap was still hanging after this so I waited 3 more mins to see if at the end Uniswap suceeds in reverting and it didn't. It just hangs forever.

Cc. @ganchoradkov @glitch-txs

**Comment by xaler5** [comment]
It's been a week, is there any news about debugging this? Can I help debugging somehow?  Happy to do so

**Comment by glitch-txs** [comment]
this seems to be on Safe side, could you open an issue in there repo? Thanks!

**Comment by katspaugh** [comment]
It's not a bug on either side. With Safe, until you fully sign and execute a transaction, it isn't submitted to the blockchain and there's no tx hash. So naturally a dapp (Uniswap in this case) cannot immediately recieve a tx hash via WalletConnect.

**Comment by Sidharth1013** [comment]
Hey, I have been facing a similar issue with safe wallet when connected via wallet connect. Is there any solution to this issue or any patch to the wallet-connect package to make it work?
