### ISSUE TITLE
Add Klaytn network

### ISSUE THREAD

**Issue by bokuhe** [WalletConnect/walletconnect-monorepo#3948]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
   **GitHub Link**:

ethereum-rpc

2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   **GitHub Link**:

ethereum

3. **namespaces**:
   _\*known chain namespaces (e.g. eip:155 for Ethereum/EVM-based chains, solana, ...)_

eip:155

4. **chains**:
   _\*known chains, where the primary key is a compound key composed of namespace + reference (e.g. ETH mainnet is eip155:1)._
   _Please provide labels for each chain (e.g. mainnet, testnet, devnet, ...)_

klaytn: eip:155:8217
baobab(testnet): eip:155:1001

5. **RPC endpoints**
   _\*list of common/canonical RPC endpoints for the chain(s)_

klaytn: https://public-en-cypress.klaytn.net
baobab: https://public-en-baobab.klaytn.net

6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
   _\* slip44 coin type used in the namespace_

8217 (0x80002019)

**Additional context**
Add any other context here.

---

**Please note:**

**Registering a chain with the Explorer does not impact or improve the ability for wallets and dapps to support your chain.** It is simply a way for users to discover wallets and dapps that support your chain by:

- Browsing the [Chains List](./chain-list.md)
- Filtering results programmatically via the [Explorer API](../../cloud/explorer.md)

**It is still up to wallets and dapps to provide concrete support for your chain once it is listed as part of the Explorer.**

- [x] I have read and understood the above clarification

**Comment by bkrem** [comment]
Thanks for your submission :pray: both of these chains are already available on https://cloud.walletconnect.com, closing.

<img width="363" alt="Screenshot 2023-11-22 at 15 18 44" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/8663099/430bf14d-cc11-4e43-afa2-91558a9f1524">
