### ISSUE TITLE
Add Dodao.dev appchain

### ISSUE THREAD

**Issue by makinghappen** [WalletConnect/walletconnect-monorepo#3949]
1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
   Ethereum RPC compatible, see [baseline-evm-template](https://docs.tanssi.network/learn/tanssi/included-templates/#baseline-evm-template) and [EVM backbone of Polkadot](https://github.com/paritytech/frontier)
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   [**eip:155 namespace**:](https://github.com/ChainAgnostic/namespaces/blob/main/eip155/README.md)
3. **namespaces**:
   eip:155
4. **chains**:
   eip155:855456 testnet
5. **RPC endpoints**
wss://fraa-dancebox-3041-rpc.a.dancebox.tanssi.network
https://fraa-dancebox-3041-rpc.a.dancebox.tanssi.network

6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
   1

[dodao.dev](docs.dodao.dev) is a decentralized and permissionless marketplace for tech talents and art creators

---

**Please note:**

**Registering a chain with the Explorer does not impact or improve the ability for wallets and dapps to support your chain.** It is simply a way for users to discover wallets and dapps that support your chain by:

- Browsing the [Chains List](./chain-list.md)
- Filtering results programmatically via the [Explorer API](../../cloud/explorer.md)

**It is still up to wallets and dapps to provide concrete support for your chain once it is listed as part of the Explorer.**

- [x] I have read and understood the above clarification

**Comment by bkrem** [comment]
Hi @makinghappen,

Couple of issues I see here:
* Seems like you've listed two coin types `60` and `1284`. We can only accept one as the primary token for a given chain
* You've labelled the chain as mainnet, but looking at https://docs.dodao.dev/docs/intro it seems to mention testnet-only, mainnet coming soon. Could you provide some more context on this please?

**Comment by bkrem** [comment]
Closing as stale since no response for a month. We can reopen once the above questions have been resolved.

**Comment by makinghappen** [comment]
hi @bkrem, thank you for your comments, have corrected the points you have mentioned! Sorry for a long reply, can you please reopen?
