### ISSUE TITLE
Add ShimmerEVM

### ISSUE THREAD

**Issue by MarkNerdi** [WalletConnect/walletconnect-monorepo#3961]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
   **GitHub Link**:
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   **GitHub Link**:
3. **namespaces**:
    - `eip:155`
4. **chains**:
   - ShimmerEVM Mainnet: `eip155:148`
   - ShimmerEVM Testnet: `eip155:1073`
5. **RPC endpoints**
   Mainnet: `https://json-rpc.evm.shimmer.network`
   Testnet: `https://json-rpc.evm.testnet.shimmer.network`
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
   4219

**Additional context**
Add any other context here.

---

**Please note:**

**Registering a chain with the Explorer does not impact or improve the ability for wallets and dapps to support your chain.** It is simply a way for users to discover wallets and dapps that support your chain by:

- Browsing the [Chains List](./chain-list.md)
- Filtering results programmatically via the [Explorer API](../../cloud/explorer.md)

**It is still up to wallets and dapps to provide concrete support for your chain once it is listed as part of the Explorer.**

- [x] I have read and understood the above clarification

**Comment by bkrem** [comment]
Thanks for your submission :pray:

The chains have been added to https://cloud.walletconnect.com/

**Comment by MarkNerdi** [comment]
Thanks for the quick reply!
