### ISSUE TITLE
Build Failing: we need PR status checks from Travis

### ISSUE THREAD

**Issue by pedrouid** [WalletConnect/walletconnect-monorepo#4]
Build is failing after merging PR #2, we should add status check requirements for PRs from Travis builds to ensure it works before merging

**Comment by jdkanani** [comment]
It's already there - https://travis-ci.org/WalletConnect/walletconnect-monorepo/builds/423311734

I will try to remove Travis cache and restart build.

**Comment by pedrouid** [comment]
My bad! I had to do it on the settings under Branch Protection
