### ISSUE TITLE
Uncaught (in promise) TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by miguelmota** [WalletConnect/walletconnect-monorepo#4019]
**Describe the bug**
WallConnect QRCode not showing and error in console

```js
index.mjs:151 Uncaught (in promise) TypeError: Object(...) is not a function
    at index.mjs:151:1
    at async _.getItem (browser.js:8:1)
    at async O (browser.js:8:1)
```

**SDK Version (if relevant)**
 - Client: JS
 - Version `"@web3-onboard/walletconnect": "2.5.1"`

**To Reproduce**
1. Visit https://app.hop.exchange/
2. Click on Connect a Wallet
3. Click on WalletConnect
4. See WalletConnect hang and error in console

**Expected behavior**
WalletConnect QRCode to show

**Screenshots**

![DeepinScreenshot_select-area_20231206183115](https://github.com/WalletConnect/walletconnect-monorepo/assets/168240/c589715a-a731-48c9-9d11-ec689befc80a)

Similar issue (QRCode not showing and console error) on web3-onboard demo page

![DeepinScreenshot_select-area_20231206182419](https://github.com/WalletConnect/walletconnect-monorepo/assets/168240/c0ffb766-2b2b-4937-b281-fdd62c8be915)

**Desktop (please complete the following information):**
 - OS: Windows, Mac, Linux
 - Browser Chrome
 - Version latest

**Additional context**

https://github.com/blocknative/web3-onboard/issues/2019

**Comment by glitch-txs** [comment]
We'll get in touch with them, if you think this issue is on our side please provide a minimal reproducible example using one of our SDKs. Thanks! Closing for now

https://docs.walletconnect.com/web3modal/about
