### ISSUE TITLE
[Urgently needed]When using @walletconnect/sign-client with ethers.js, an error occurs.

### ISSUE THREAD

**Issue by liubin595338764** [WalletConnect/walletconnect-monorepo#4026]
**Describe the bug**
When using @walletconnect/sign-client with ethers.js, an error occurs when generating the provider.

**SDK Version (if relevant)**
 - "ethers": "^6.8.1",
 - "@walletconnect/sign-client": "2.10.0",

**code**
···
const provider = new ethers.BrowserProvider(session);
const networkInfo = await provider.getNetwork()
// The code encountered an error here.
Error: could not coalesce error (error={ "message": "ethereum.request is not a function" }, payload={ "id": 1, "jsonrpc": "2.0", "method": "eth_chainId", "params": [  ] }, code=UNKNOWN_ERROR, version=6.8.1)
···

**Expected behavior**
@walletconnect/sign-client can generate a provider for use with ethers.js normally.

**Screenshots**
<img width="647" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/5274428/79e0e1f1-6b12-4db1-9e83-a2757658047c">

**Desktop (please complete the following information):**
 - OS: [MAC]
 - Browser [chrome]
   - Version [Chrome/120.0.0.0]

**Comment by glitch-txs** [comment]
Sign client doesn't work with ethers, you can use ethereum-provider instead

https://docs.walletconnect.com/advanced/providers/ethereum

**Comment by liubin595338764** [comment]
@glitch-txs Hello, Thank you for your response. my application needs to support both Ethereum and Tron simultaneously.

I noticed that https://react-app.walletconnect.com/ uses @walletconnect/sign-client.

If the Sign client cannot be used, how can I support Ethereum and Tron at the same time?

**Comment by glitch-txs** [comment]
For multi-chain you can use Universal Provider

**Comment by glitch-txs** [comment]
We have a multi-chain example here 🫡
https://github.com/WalletConnect/web-examples/tree/main/dapps%2Freact-dapp-v2-with-ethers
