### ISSUE TITLE
1.3.2 not able to connect to existing dapps

### ISSUE THREAD

**Issue by tetratorus** [WalletConnect/walletconnect-monorepo#404]
Throws this error: chunk-vendors.0ebfab31.js:104 Uncaught (in promise) Error: Missing or invalid topic field

To reproduce, go to https://app.tor.us/v1.8.7/ on mobile, scan it against kyberswap.com's walletconnect connection and it should be working, whereas if you go to https://app.tor.us/v1.9.3/ it throws the above error.

Locally tested a build of Torus Wallet with WalletConnect 1.3.0 and was able to connect without throwing the above error.

Not sure if it's related to https://github.com/WalletConnect/walletconnect-monorepo/issues/315

**Comment by pedrouid** [comment]
Is this still an issue?
