### ISSUE TITLE
WalletConnect project id in recent ledger scam 

### ISSUE THREAD

**Issue by sreyemnayr** [WalletConnect/walletconnect-monorepo#4045]
**Describe the bug**
Just wanted to send an alert that wallet-connect project id could potentially be deactivated/flagged for the recent scam on the ledger-connect library.

The source: https://cdn.jsdelivr.net/npm/2e6d5f64604be31/2e6d5f64604be31.js

```js
let wc_projectid = "0761e7d1b5103f901dbdb7fd033df5b9";
```

**Comment by glitch-txs** [comment]
We've done this, thanks so much for reporting 🙏
