### ISSUE TITLE
Hedera - update chain ids

### ISSUE THREAD

**Issue by hgraphql** [WalletConnect/walletconnect-monorepo#4068]
1. JSON-RPC spec for Wallets: **GitHub Link**:

- https://github.com/WalletConnect/walletconnect-specs/blob/main/docs/blockchain-rpc/hedera-rpc.md

2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.

- https://github.com/ChainAgnostic/namespaces/tree/main/hedera

3. **namespaces**:

- `hedera`
- `eip155`

4. **chains**:

Native Hedera functionality (https://hips.hedera.com/hip/hip-30#specification):

- `hedera:mainnet` (Hedera Mainnet)
- `hedera:testnet` (Hedera Testnet)
- `hedera:previewnet` (Hedera Previewnet)

_a fourth chain `hedera:devnet` does not need to be included as it refers to a local network for
a developer_

Ethereum JSON-RPC capability layer (https://hashio.io/):

- `eip155:295` (Hedera Mainnet Ethereum JSON-RPC relay - limited functionality)
- `eip155:296` (Hedera Testnet Ethereum JSON-RPC relay - limited functionality)
- `eip155:297` (Hedera Previewnet Ethereum JSON-RPC relay - limited functionality)

5. **RPC endpoints**

The following RPC endpoints are for the eip155 namespace only. There are not JSON-RPC endpoints for the `hedera` namespace.

- https://mainnet.hashio.io/api
  (https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-295.json)
- https://testnet.hashio.io/api
  (https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-296.json)
- https://previewnet.hashio.io/api
  (https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-297.json)

6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:

- _Coin type_: 3030
- _Path component (coin_type)_ :0x80000bd6
- _Symbol_: HBAR
- _Coin_: Hedera HBAR

**Additional context**:

There are 2 namespaces available to interact with the Hedera netork - the `hedera` namespace offers native Hedera functionality.

The `eip155` namespace provides a JSON-RPC API interface, on top of Hedera’s native API transactions, that offers a familiar Ethereum-like API. The `eip155` JSON-RPC relay implementation is in beta, offers limited functionality today, and intended for developers. <https://swirldslabs.com/hashio/>

The current dropdowns in WalletConnect cloud have the following chains which need to be updated:

- add `Hedera Previewnet (eip155:297)`
- change `Hedera Mainnet (hedera:295)` -> `Hedera Mainnet (hedera:mainnet)`
- change `Hedera Testnet (hedera:296)` -> `Hedera Testnet (hedera:testnet)`
- add `Hedera Previewnet (hedera:previewnet)`

---

**Please note:**

**Registering a chain with the Explorer does not impact or improve the ability for wallets and
dapps to support your chain.** It is simply a way for users to discover wallets and dapps that
support your chain by:

- Browsing the [Chains List](./chain-list.md)
- Filtering results programmatically via the [Explorer API](../../cloud/explorer.md)

**It is still up to wallets and dapps to provide concrete support for your chain once it is
listed as part of the Explorer.**

- [ √] I have read and understood the above clarification

**Comment by bkrem** [comment]
Added and updated ✅
