### ISSUE TITLE
Switch chain error - ethereum-provider

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/walletconnect-monorepo#4089]
# Description

There are two bugs with wallet_switchEthereumChain and wallet_addEthereumChain.

## First Bug - unresolved promise:

When calling `wallet_addEthereumChain` and `wallet_switchEthereumChain` subsequently, the switch chain request will hang without resolving

See related issue: https://github.com/wevm/wagmi/issues/3350

### Steps to reproduce:

1. Run the following repo: https://github.com/glitch-txs/switch-chain-error
2. Connect to MetaMask 
3. Open the console (All processes are tracked in console)
4. Call "Add chain & Switch" button
5. Switching chain never resolves.

## Second Bug `Cannot set properties of undefined (setting 'defaultChain')`

Sometimes, when calling switch chain, this error appears

```sh
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'defaultChain')
    at _lr.onChainChanged (@walletconnect_ethereum-provider.js?v=004ae9bc:17584:141)
    at EventEmitter3.<anonymous> (@walletconnect_ethereum-provider.js?v=004ae9bc:17546:12)
    at EventEmitter3.emit (@walletconnect_ethereum-provider.js?v=004ae9bc:112:9)
    at jg.setDefaultChain (@walletconnect_ethereum-provider.js?v=004ae9bc:16968:112)
    at jg.handleSwitchChain (@walletconnect_ethereum-provider.js?v=004ae9bc:17017:12)
    at jg.request (@walletconnect_ethereum-provider.js?v=004ae9bc:16958:27)
    at _lr.request (@walletconnect_ethereum-provider.js?v=004ae9bc:17393:39)
    at _v.request (@walletconnect_ethereum-provider.js?v=004ae9bc:17651:30)
    at switch_chain (main.ts:81:43)
    at HTMLButtonElement.<anonymous> (main.ts:88:45)
```

See related issue: https://github.com/wevm/wagmi/issues/3347

### Steps to reproduce

1. Run the following repo: https://github.com/glitch-txs/switch-chain-error
2. Connect to MetaMask 
3. Open the console (All processes are tracked in console)
4. Press "Switch Chain" button
5. Error show in console.

NOTE: The second issue happened to me randomly with Rainbow wallet as well, not only MetaMask, when trying to switch to a different chain.

**Comment by Hugo-Oh** [comment]
got exactly same error when using WalletConnectV2 with metamask and call SwitchNetwork from useSwitchNetwork Hook from wagmi, any progress yet?

**Comment by hubagaspar91** [comment]
+1 
Happened while switching chains using WalletConnectV2 connected to Rainbow wallet.

**Comment by YuriiChikhrai** [comment]
Same.

I figure out, that Issue is in this line: https://github.com/WalletConnect/walletconnect-monorepo/blob/0715a49e6250abe58f9bf6f732a9018f66193ad6/providers/universal-provider/src/UniversalProvider.ts#L474

For some reason `this.namespaces` is empty object so there must be some check or issue is why namespaces is empty...

**Comment by siosio34** [comment]
hello. Has this issue been fixed yet?

**Comment by kolirt** [comment]
same issue

**Comment by glitch-txs** [comment]
The second issue is on our side and we're currently working on a fix which should be implemented early next week.

You can test the possible fix by adding this into your package.json + doing a fresh install

```
  "resolutions": {
    "@walletconnect/ethereum-provider": "2.11.0-canary-up-patch"
  }
```

**Comment by glitch-txs** [comment]
fix: https://github.com/WalletConnect/walletconnect-monorepo/pull/4202#pullrequestreview-1863530859

**Comment by glitch-txs** [comment]
fixed in:
ethereum-provider: v2.11.1
Wagmi v2: https://github.com/wevm/wagmi/pull/3569
Wagmi v1: https://github.com/wevm/wagmi/pull/3570
Web3Modal + ethers: v4
