### ISSUE TITLE
Add user rejected request error to sdk

### ISSUE THREAD

**Issue by amiryadid-fb** [WalletConnect/walletconnect-monorepo#4094]
Per the documentation there is an SDK error (in adherence to EIP-1193) to symbolize an error resulting from a user rejecting the method request.
It exists in the mobile development SDKs but not in the monorepo.

I suggest adding the error to the `SDK_ERRORS` object so it can be used with `getSdkError`.

```
  /* ----- USER REJECTED REQUEST (EIP-1193) ----- */
  USER_REJECTED_REQUEST: {
    message: "User rejected request.",
    code: 4001,
  },
```

Also, is there an error code to represent an internal server error during rpc method requests? (Saw `SESSION_SETTLEMENT_FAILED` but wanted to make sure it's relevant for session requests also and not only session proposal settlements)

**Comment by ganchoradkov** [comment]
Hey, for `user rejected` errors we already have https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/utils/src/errors.ts#L50C1-L53C5 which is intended to be used when the user rejects any generic request such as session requests
