### ISSUE TITLE
Error: invalid transaction key: gas

### ISSUE THREAD

**Issue by iPriyaranjan** [WalletConnect/walletconnect-monorepo#4098]
### Description

I'm encountering errors when users try to transfer or buy NFTs: 
**Possible unhandled promise rejection (id: 0): Error: invalid transaction key: gas**

### SDK Version
 - react-native: 0.73.1
 - @walletconnect/web3wallet: 1.10.0

**Steps to Reproduce** 
1. Run the following repo: https://github.com/iPriyaranjan/WalletConnectExample.git
2. Connect this with PanCakeSwap (https://pancakeswap.finance/).
3. In the NFT section you can try to transfer or buy NFTs.
4. Once you get the confirmation modal in the Wallet app, you have to click on the “Accept” button.

**Expected behavior**
NFTs should be transferred/purchased without any issues

**Additional context**
Initially i'm getting "TypeError: Cannot read property 'rpc' of undefined", for this I have added BSC chain in [EIP155.tsx](https://github.com/iPriyaranjan/WalletConnectExample/blob/main/src/data/EIP155.tsx#L43) file. After this I am getting the mentioned issue in my wallet.
![gasError](https://github.com/WalletConnect/walletconnect-monorepo/assets/112841974/056adf6b-33d8-4a6d-88a2-be9fb5069127)

**Comment by ganchoradkov** [comment]
Hey, WalletConnect protocol is only transmitting the data and not modifying the transaction payloads. The error you're receiving is rejection from the library `ethers`, please check out this report https://github.com/ethers-io/ethers.js/discussions/1674 as it looks similar. It might help you resole it
