### ISSUE TITLE
I am following the NextJS Wagmi getting started guide (https://docs.walletconnect.com/web3modal/nextjs/about).

### ISSUE THREAD

**Issue by Tura187** [WalletConnect/walletconnect-monorepo#4102]
I am following the NextJS Wagmi getting started guide (https://docs.walletconnect.com/web3modal/nextjs/about).
I have a `<w3m-button />` that opens the modal to select wallet and connect.

Each time I delete the cache and reload the page, the web app tries to connect automatically to MetaMask.
I want the connection to MetaMask to happen after the user opens the  `<w3m-button />` modal, not as soon as the web page loads.
I know that disabling auto-connect would mean that after each reload the user would have to open the modal but I prefer it rather than having the metamask popup open as soon as the home page first loads.

The only thing I found is this issue: https://github.com/WalletConnect/web3modal/pull/1515. 

Am I missing something?

_Originally posted by @ale-ben in https://github.com/WalletConnect/walletconnect-monorepo/discussions/4014_
```[tasklist]
### Tasks
- [x] Kill all transactions imediatley
```

**Comment by glitch-txs** [comment]
Please update to 3.4.5 version, this was fixed there

**Comment by aminpsycho** [comment]
ok
