### ISSUE TITLE
Add zKatana Testnet

### ISSUE THREAD

**Issue by Maar-io** [WalletConnect/walletconnect-monorepo#4107]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
   ethereum-rpc
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   ethereum
3. **namespaces**:
   eip:155
4. **chains**:
Testnet eip155:1261120

5. **RPC endpoints**
https://rpc.startale.com/zkatana
https://rpc.zkatana.gelato.digital

6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
   60

**Additional context**
This is testnet for Astar zkEVM network, built on Polygon zkEVM CDK

---

**Please note:**

**Registering a chain with the Explorer does not impact or improve the ability for wallets and dapps to support your chain.** It is simply a way for users to discover wallets and dapps that support your chain by:

- Browsing the [Chains List](https://docs.walletconnect.com/advanced/multichain/chain-list)
- Filtering results programmatically via the [Explorer API](https://docs.walletconnect.com/cloud/explorer)

**It is still up to wallets and dapps to provide concrete support for your chain once it is listed as part of the Explorer.**

- [x] I have read and understood the above clarification

**Comment by bkrem** [comment]
Thanks for your submission, added to https://cloud.walletconnect.com 🤝
