### ISSUE TITLE
Mobile not show popup dialog in wallet end after configuring Allowed Domains and Application IDs

### ISSUE THREAD

**Issue by hamberluo** [WalletConnect/walletconnect-monorepo#4112]
**Describe the bug**
Mobile wallet not show popup dialog after DApp configuring Allowed Domains and Application IDs.

**SDK Version (if relevant)**
 - Client: [Flutter]
 - Version [2.1.11]

**To Reproduce**
1. Go to cloud.walletconnect.com
2. Configure allowed domains
3. Configure Mobile Application IDs.

**Expected behavior**
Wallet Connect normally connected.

**Comment by ganchoradkov** [comment]
Hey, this most likely means the dapp's configured allowed domains are blocking the relay connection, please open the developer console in the dapp and monitor for any error messages
