### ISSUE TITLE
walletconnect/web3-providers error undefined ls-remote -h -t https://github.com/ethereumjs/ethereumjs-abi.git

### ISSUE THREAD

**Issue by sanjuraj85** [WalletConnect/walletconnect-monorepo#412]
Getting error while installing npm i @walletconnect/web3-providers

npm WARN deprecated rpc-payload-id@1.0.0: Packaged deprecated in favor of @json-rpc-tools/utils
npm WARN deprecated safe-event-emitter@1.0.1: Renamed to @metamask/safe-event-emitter
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/ethereumjs/ethereumjs-abi.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by pedrouid** [comment]
Can you upgrade to v1.3.4 and see if the issue still persists?

**Comment by jeromevvb** [comment]
@pedrouid I'm having this issue with v1.4.1.
```
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/ethereumjs/ethereumjs-abi.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

By the way ethereumjs-abi is deprecated .
