### ISSUE TITLE
Failed to execute 'setItem' on 'Storage' with latest walletconnect version

### ISSUE THREAD

**Issue by drinksbydrew** [WalletConnect/walletconnect-monorepo#4125]
Related issues that did not fix my problem:
- https://github.com/WalletConnect/walletconnect-monorepo/issues/3198
- https://github.com/WalletConnect/walletconnect-monorepo/issues/3860
- https://github.com/wevm/wagmi/discussions/1584
- https://github.com/wevm/wagmi/issues/2182

Hi, I am using walletconnect in my app (connecting to a safe), and after a little bit of usage, my localstorage on the safe side is full and I get the error `Failed to execute 'setItem' on 'Storage': Setting the value of 'wc@2:core:0.3//request'` exceeded the quota. I've googled the issue and I saw some suggestions to update to newer versions of walletconnect. My app is currently using the latest version of @walletconnect/ethereum-provider (2.11.0), @walletconnect/modal (2.6.2) and their dependencies. I'm using these through wagmi. (I have also tried downgrading versions of walletconnect but still have the same issue.)

I suspect the issue might be that I'm connecting my app to a safe which is using an older version of walletconnect. I looked at my localstorage on the safe side and saw that the key `wc@2:core:0.3//messages` is the one taking up almost all of the localstorage space. (`wc@2:core:0.3//history` also seems to grow without shrinking, but it's smaller.)

The version of safe-wallet-web that I'm connecting with is [1.19.1](https://github.com/safe-global/safe-wallet-web/releases/tag/v1.19.1). The yarn.lock file for that version is [here](https://github.com/safe-global/safe-wallet-web/blob/b7287acb23fdf594eb5505c5e494ae5acaa7649e/yarn.lock). The relevant @walletconnect dependencies are these:

```    
    "@walletconnect/client" "^1.8.0"
    "@walletconnect/ethereum-provider" "^2.10.1"
    "@walletconnect/modal" "2.6.2"
    "@walletconnect/qrcode-modal" "^1.8.0"
```
    
    
Are there any known issues with walletconnect version mismatches that cause excessive growth in the `wc@2:core:0.3//messages` key? (Maybe `@walletconnect/client`, since on the Safe side it's v1?)

Since I don't control the safe-wallet-web, what can I do to make sure that my app doesn't have this issue? (I've connected my safe to another app with walletconnect, and I don't experience this issue with that app.)

**Comment by ganchoradkov** [comment]
hey, sorry you're experiencing these issues, The issue was resolved in [2.10.5](https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.10.5) where we moved to indexedDb as our main storage. 
The current remedy for your issue is to wipeout your localstorage for that dapp

**Comment by drinksbydrew** [comment]
> Contributor

hey @ganchoradkov thanks for your reply. My app is using 2.11.0, which is newer than 2.10.5. However, as I mentioned above, I use the safe with another dapp that doesn't have the same issue, so it seems like there is some remedy that doesn't require the safe package version (which I have no control over) to be upgraded. I'm wondering what that dapp is doing differently from me. Do you have any ideas?

**Comment by TomasCImach** [comment]
hey @ganchoradkov @drinksbydrew joining the issue as I have the same problem.
I'm trying to set up walletconnect v2, installed core, ethereum-provider and utils with version 2.11.0 and modal with version 2.6.2.

this is the error on the console:
```
index.mjs:151 Uncaught (in promise) TypeError: Object(...) is not a function
    at index.mjs:151:1
    at async _.getItem (validators.ts:40:1)
    at async O (validators.ts:40:1)
```

**Comment by xivic-homium** [comment]
I have the same issue

Uncaught (in promise) TypeError: Object(...) is not a function
    at index.mjs:151:1
    at async _.getItem (validators.ts:40:1)
    at async O (validators.ts:40:1)
    
     "@walletconnect/ethereum-provider": "^2.11.0",
    "@walletconnect/universal-provider": "^2.11.0",

**Comment by ganchoradkov** [comment]
hey @TomasCImach, @xivic-homium could you please provide more info about your enviroments and idealy a MRE repo that we can see whats wrong exactly?

**Comment by TomasCImach** [comment]
The issue was solved when upgrading `react-scripts` to the latest version.
