### ISSUE TITLE
Add Rari Mainnet and Testnet

### ISSUE THREAD

**Issue by MYKatz** [WalletConnect/walletconnect-monorepo#4177]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
   Uses Ethereum rpc spec
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   Already exists
3. **namespaces**:
   EIP155
4. **chains**:
   RARI testnet: eip155:1918988905
  RARI mainnet: eip155:1380012617
5. **RPC endpoints**
   Same as Ethereum
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
  Ethereum (60)

**References**
To ensure timely processing of your request, please provide the following references:

- [x] Source of RPC endpoints (e.g. RPC docs): https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-eth)

**Additional context**
Add any other context here.

Arbitrum Orbit chain

---

**Please note:**

**Registering a chain with the Explorer does not impact or improve the ability for wallets and dapps to support your chain.** It is simply a way for users to discover wallets and dapps that support your chain by:

- Browsing the [Chains List](https://docs.walletconnect.com/advanced/multichain/chain-list)
- Filtering results programmatically via the [Explorer API](https://docs.walletconnect.com/cloud/explorer)

**It is still up to wallets and dapps to provide concrete support for your chain once it is listed as part of the Explorer.**

- [x] I have read and understood the above clarification

**Comment by Cali93** [comment]
Your chain has been added to our registry 🎉
