### ISSUE TITLE
Unable to list NFT on Blur marketplace via using WalletConnect on Trust Wallet

### ISSUE THREAD

**Issue by cgr4y** [WalletConnect/walletconnect-monorepo#4178]
When I try to list an NFT I am met with the error 'User Rejected'. When I first tried the gas fee was taken but I received that message. Now it won't give me a transaction preview on Trust Wallet and I still receive the error message

**To Reproduce**
1. Go to blur.io
2. Connect Trust Wallet with WalletConnect
3. List NFT through normal channel
4. Receive error message 'user rejected'

**Expected behavior**
Gas fee to be taken and NFT to be listed for sale

**Screenshots**
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/157771636/0006ce36-8ec5-468e-b66f-62d71ffebc97)

**Smartphone**
 - Device: Samsung S22
 - OS: Android Version 12
 - Browser: Samsung Internet 
 - Version: 23.0.1.1

**Comment by 124maa** [comment]
Ok

**Comment by glitch-txs** [comment]
Please report this to Blur support team
