### ISSUE TITLE
"Request expired. Please try again." error received by the dapp while the wallet can still sign

### ISSUE THREAD

**Issue by yomarion** [WalletConnect/walletconnect-monorepo#4181]
**Describe the bug**
When the user does not take action on transaction confirmation for 1-5 minutes, WC lets the dapp think that the transaction request has expired with the error "Request expired. Please try again.". The dapp is led to think that the transaction should be submitted again, which may confuse the user and possibly lead him to send the same transaction twice in a row.

**To Reproduce**
1. From a dapp showing WC errors
2. Initiate a transaction
3. From the connected wallet, do not validate nor decline, just wait for 1-5 minutes
4. The dapp shows the Wallet Connect error: "Request expired. Please try again."
5. The user can approve the transaction nevertheless

We managed to reproduce this same issue with 3 different wallets: mobile (Metamask mobile on Android), multisig dapp (Safe) and multisig MPC (Fireblocks).

**Comment by ganchoradkov** [comment]
thanks for the report, this has been fixed in https://github.com/WalletConnect/walletconnect-monorepo/pull/4159 and is pending release

**Comment by skrakibmia20-wq** [comment]
###
