### ISSUE TITLE
Casper Network onboarding

### ISSUE THREAD

**Issue by davidatwhiletrue** [WalletConnect/walletconnect-monorepo#4193]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets.
   **GitHub Link**: https://github.com/WalletConnect/walletconnect-docs/pull/1377
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   **GitHub Link**: https://github.com/ChainAgnostic/namespaces/pull/100
3. **namespaces**:
  `casper`
4. **chains**:
  Mainnet: `casper:casper`
  Testnet: `casper:casper-test`
5. **RPC endpoints**
  Mainnet: `http://34.224.191.55:7777/rpc`
  Testnet: `http://52.35.59.254:7777/rpc`
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
  506

**References**
To ensure timely processing of your request, please provide the following references:

- [X] Source of RPC endpoints (e.g. RPC docs): https://github.com/WalletConnect/walletconnect-docs/pull/1377
- [X] Source of namespace (if non-EIP155) chain information (particularly chainIds): https://github.com/ChainAgnostic/namespaces/pull/100

**Additional context**
Add any other context here.

---

**Please note:**

**Registering a chain with the Explorer does not impact or improve the ability for wallets and dapps to support your chain.** It is simply a way for users to discover wallets and dapps that support your chain by:

- Browsing the [Chains List](https://docs.walletconnect.com/advanced/multichain/chain-list)
- Filtering results programmatically via the [Explorer API](https://docs.walletconnect.com/cloud/explorer)

**It is still up to wallets and dapps to provide concrete support for your chain once it is listed as part of the Explorer.**

- [X] I have read and understood the above clarification

**Comment by hudabiaabbas** [comment]
Gubchnkcdvjncssvb

**Comment by bkrem** [comment]
Hi @davidatwhiletrue,

Thanks for submitting the chain onboarding request!

Tagging @bumblefudge here as an FYI, since we first need the CASA spec to be agreed and merged before we can proceed 🙏

**Comment by davidatwhiletrue** [comment]
Hi @bkrem , just writing to tell that CASA spec for Casper network has been merged today. Let me know if we can do anything to continue with the onboarding in WalletConnect Explorer API. Thanks for your support.

**Comment by bkrem** [comment]
Thanks @davidatwhiletrue, support for the Casper chains has been added to https://cloud.walletconnect.com/ 🎉

**Comment by davidatwhiletrue** [comment]
That is great news. Thanks a lot @bkrem . 
Can you take a look to [this PR](https://github.com/WalletConnect/walletconnect-docs/pull/1377) for RPC documentation? Or do you know who to tag to ask for a review?

**Comment by bkrem** [comment]
Tagged the right folks for the docs PR 👍
