### ISSUE TITLE
Add support for Unreal testnet

### ISSUE THREAD

**Issue by veljkoTNFT** [WalletConnect/walletconnect-monorepo#4206]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
   **GitHub Link**: https://ethereum.org/en/developers/docs/apis/json-rpc ethereum-rpc
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   **GitHub Link**: https://github.com/ChainAgnostic/namespaces/tree/main/eip155 ethereum eip155
3. **namespaces**:
   _\*known chain namespaces (e.g. eip:155 for Ethereum/EVM-based chains, solana, ...)_
eip:155
4. **chains**:
   _\*known chains, where the primary key is a compound key composed of namespace + reference (e.g. ETH mainnet is eip155:1)._
unreal eip155:18231
   _Please provide labels for each chain (e.g. mainnet, testnet, devnet, ...)_

5. **RPC endpoints**
   _\*list of common/canonical RPC endpoints for the chain(s)_
https://rpc.unreal.gelato.digital/
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
   _\* slip44 coin type used in the namespace_
60

**References**
To ensure timely processing of your request, please provide the following references:

- [x] Source of RPC endpoints (e.g. RPC docs): [[link](https://raas.gelato.network/rollups/details/public/unreal)]

**Additional context**
Add any other context here.

---

**Please note:**

**Registering a chain with the Explorer does not impact or improve the ability for wallets and dapps to support your chain.** It is simply a way for users to discover wallets and dapps that support your chain by:

- Browsing the [Chains List](https://docs.walletconnect.com/advanced/multichain/chain-list)
- Filtering results programmatically via the [Explorer API](https://docs.walletconnect.com/cloud/explorer)

**It is still up to wallets and dapps to provide concrete support for your chain once it is listed as part of the Explorer.**

- [x] I have read and understood the above clarification

**Comment by veljkoTNFT** [comment]
Hi @bkrem can you review my request, and see if I'm missing anything from the data?

**Comment by bkrem** [comment]
Hi @veljkoTNFT,

Looking good generally speaking but we're missing some context/references here:
* I'm assuming this the testnet from Unreal Finance? https://testnet.unreal.finance/beginner/discounted-assets
* I can't find a reference to the chainId `18231`, could you provide one please
* Should this be labelled as `Unreal Finance Testnet` or `Unreal Testnet`

**Comment by veljkoTNFT** [comment]
Hi @bkrem ,

No it is not that :D Unreal is testnet of our future chain called re.al, I don't know what that is, that Unreal finance. 
Our public info is available right here https://raas.gelato.network/rollups/details/public/unreal
In the upcomming days, I'll probably have a commit for supporting the re.al which will be mainnet. Both on zkEvm
If possible, it should be just  unreal. If you have some policies, then unreal testnet (we are marketing both under lowercase, especially re.al )

**Comment by 124maa** [comment]
Ok
