### ISSUE TITLE
Support more coins

### ISSUE THREAD

**Issue by newnya** [WalletConnect/walletconnect-monorepo#422]
Is it possible for this protocol to be multi-crypto?
So that a website can request payments also in BTC, BCH, etc.

**Comment by pedrouid** [comment]
We are working on the v2.0 protocol, you can track the progress here:

https://github.com/WalletConnect-Labs/walletconnect-v2-monorepo/

And read more about in techniical detail here:

https://docs.walletconnect.org/v/v2.0.0-alpha/tech-spec
