### ISSUE TITLE
Socket hang up - read ECONNRESET

### ISSUE THREAD

**Issue by kvnschlndt** [WalletConnect/walletconnect-monorepo#4228]
Wallet crashes with this errors:

`2024-02-14T14:21:57+01:00	{"level":50,"time":1707916917488,"pid":1,"hostname":"api-756469476b-zff5t","context":"core","context":"core/relayer","err":{"type":"Error","message":"read ECONNRESET","stack":"Error: read ECONNRESET\n    at WsConnection.emitError (/app/node_modules/@walletconnect/jsonrpc-ws-connection/dist/cjs/ws.js:151:39)\n    at WebSocket.<anonymous> (/app/node_modules/@walletconnect/jsonrpc-ws-connection/dist/cjs/ws.js:109:33)\n    at WebSocket.emit (node:events:513:28)\n    at emitErrorAndClose (/app/node_modules/@walletconnect/jsonrpc-ws-connection/node_modules/ws/lib/websocket.js:895:13)\n    at ClientRequest.<anonymous> (/app/node_modules/@walletconnect/jsonrpc-ws-connection/node_modules/ws/lib/websocket.js:752:5)\n    at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketErrorListener (node:_http_client:494:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)"},"msg":"read ECONNRESET"}`

`2024-02-14T14:21:57+01:00	{"level":50,"time":1707916917488,"pid":1,"hostname":"api-756469476b-zff5t","context":"core","context":"core/relayer","err":{"type":"Error","message":"read ECONNRESET","stack":"Error: read ECONNRESET\n    at WsConnection.emitError (/app/node_modules/@walletconnect/jsonrpc-ws-connection/dist/cjs/ws.js:151:39)\n    at WebSocket.<anonymous> (/app/node_modules/@walletconnect/jsonrpc-ws-connection/dist/cjs/ws.js:109:33)\n    at WebSocket.emit (node:events:513:28)\n    at emitErrorAndClose (/app/node_modules/@walletconnect/jsonrpc-ws-connection/node_modules/ws/lib/websocket.js:895:13)\n    at ClientRequest.<anonymous> (/app/node_modules/@walletconnect/jsonrpc-ws-connection/node_modules/ws/lib/websocket.js:752:5)\n    at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketErrorListener (node:_http_client:494:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)"},"msg":"read ECONNRESET"}`

`2024-02-14T14:21:57+01:00	{"level":50,"time":1707916917337,"pid":1,"hostname":"api-756469476b-zff5t","context":"core","context":"core/relayer","err":{"type":"Error","message":"socket hang up","stack":"Error: socket hang up\n    at WsConnection.emitError (/app/node_modules/@walletconnect/jsonrpc-ws-connection/dist/cjs/ws.js:151:39)\n    at WebSocket.<anonymous> (/app/node_modules/@walletconnect/jsonrpc-ws-connection/dist/cjs/ws.js:109:33)\n    at WebSocket.emit (node:events:513:28)\n    at emitErrorAndClose (/app/node_modules/@walletconnect/jsonrpc-ws-connection/node_modules/ws/lib/websocket.js:895:13)\n    at ClientRequest.<anonymous> (/app/node_modules/@walletconnect/jsonrpc-ws-connection/node_modules/ws/lib/websocket.js:752:5)\n    at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketOnEnd (node:_http_client:518:9)\n    at TLSSocket.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"},"msg":"socket hang up"}`

What is the issue here? 
Its happening on connect to dApp.

**Comment by glitch-txs** [comment]
Hi, could you provide more information?

- What SDK + version are you using
- A minimal reproducible example
- steps to reproduce

Closing in the meantime. Thanks! 🙏
