### ISSUE TITLE
I can not get the result of web3.eth.getAccounts();

### ISSUE THREAD

**Issue by fengyh13** [WalletConnect/walletconnect-monorepo#423]
// Create WalletConnect Provider
  const provider = new WalletConnectProvider({
    infuraId: "xxxxx",
    bridge: "https://bridge.walletconnect.org",
  });

  // Enable session (triggers QR Code modal)
  await provider.enable();

  const web3 = new Web3(provider);
  // Th result above is right. but can not get the result of web3.eth.getAccounts();
  let gasPrice = await web3.eth.getAccounts();

**Comment by Loque18** [comment]
I am having a similar issue, how did you manage this to work ?
