### ISSUE TITLE
Safe App throws errors when connecting via Web3Modal

### ISSUE THREAD

**Issue by serenae-fansubs** [WalletConnect/walletconnect-monorepo#4240]
**Describe the bug**
Using Ethereum Mainnet

When connecting from (formerly named Gnosis Safe) Safe App via WalletConnect and Web3Modal, this exception always seems to occur:

```
Unhandled Runtime Error
Error: No matching key. session topic doesn't exist: 464e813cba28bdd9f02ac6725a91e930778fcab70931a5e758aa13008255d188

Call Stack
ds.isValidSessionTopic
node_modules/@walletconnect/sign-client/dist/index.es.js (1:30438)
ds.isValidEmit
node_modules/@walletconnect/sign-client/dist/index.es.js (1:27204)
ds.onSessionEventRequest
node_modules/@walletconnect/sign-client/dist/index.es.js (1:21682)
ds.processRequest
node_modules/@walletconnect/sign-client/dist/index.es.js (1:15394)
ds.processRequestsQueue
node_modules/@walletconnect/sign-client/dist/index.es.js (1:14756)
ds.onRelayEventRequest
node_modules/@walletconnect/sign-client/dist/index.es.js (1:14319)
EventEmitter.eval
node_modules/@walletconnect/sign-client/dist/index.es.js (1:28885)
```

Sometimes when connecting, I also get this additional error:

```
Unhandled Runtime Error
Error: Please call connect() before request()

Call Stack
lr.request
node_modules/@walletconnect/universal-provider/dist/index.es.js (27:27672)
v.request
node_modules/@walletconnect/ethereum-provider/dist/index.es.js (1:2509)
v.switchEthereumChain
node_modules/@walletconnect/ethereum-provider/dist/index.es.js (1:4941)
v.setChainId
node_modules/@walletconnect/ethereum-provider/dist/index.es.js (1:5471)
EventEmitter.eval
node_modules/@walletconnect/ethereum-provider/dist/index.es.js (1:4078)
EventEmitter.emit
node_modules/events/events.js (153:0)
EventEmitter.eval
node_modules/@walletconnect/universal-provider/dist/index.es.js (27:32454)
EventEmitter.emit
node_modules/events/events.js (153:0)
ds.onSessionEventRequest
node_modules/@walletconnect/sign-client/dist/index.es.js (1:21710)
ds.processRequest
node_modules/@walletconnect/sign-client/dist/index.es.js (1:15394)
ds.processRequestsQueue
node_modules/@walletconnect/sign-client/dist/index.es.js (1:14756)
ds.onRelayEventRequest
node_modules/@walletconnect/sign-client/dist/index.es.js (1:14319)
EventEmitter.eval
node_modules/@walletconnect/sign-client/dist/index.es.js (1:28885)
```

**SDK Version (if relevant)**
 - I am not sure of the client/version, but this can be reproduced today using the demos on either https://web3modal.com/ or https://lab.web3modal.com/library/wagmi/
 - The first page looks like it is using Web3Modal 3.5.6.

**To Reproduce**
1. Go to either https://web3modal.com/ or https://lab.web3modal.com/library/wagmi/
2. Click on Connect Wallet
3. Choose WalletConnect, and copy link
4. In the Safe App, click on WalletConnect and paste the link, then approve the connection
5. Back on the Web3Modal page, the wallet appears to connect, but you will see these errors in the browser console:

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/95138671/6505d83f-4bca-494f-9fe8-33835e56e0b8)

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/95138671/cd91db5a-18dc-4465-ba00-7546a3daac2b)

**Expected behavior**
The "no matching key" and "please call connect before request" errors should not be seen in the browser console.

**Screenshots**
When running a react app in dev mode, you can see the errors pop up right there on the page:
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/95138671/6c90ce3c-ad04-4a3f-b3bb-560d31ab040a)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Tried Brave, Edge, and Firefox
 - Version: All latest versions

**Additional context**
https://github.com/rainbow-me/rainbowkit/discussions/1772

**Comment by glitch-txs** [comment]
I'm not able to repro on https://lab.web3modal.com/library/wagmi/

could you check again? if this persists I think it would be better to open the issue in the Safe repository.

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/66949816/e0be0951-1816-4c8d-b820-32b2e91893d4)
