### ISSUE TITLE
Module exports { default, __esModule }

### ISSUE THREAD

**Issue by hazae41** [WalletConnect/walletconnect-monorepo#425]
Related to https://github.com/postui/esm.sh/issues/17

> it has to do with the fact that WalletConnect isn't shipping ES modules and instead they are using Webpack + TS to convert their ES source code into CJS which is published. This causes `export default` to be transformed to `exports.default` which isn't actually a proper conversion though.

It seems CJS adds an extra "default" to the exported module object; any way to prevent this?

**Comment by johnson86tw** [comment]
I have the same problem. I think Walletconnect web3-provider(v1) or ethereum-provider(v2) should be friendly to ES module.
- https://github.com/chnejohnson/vue-dapp/issues/3
