### ISSUE TITLE
It seems like universal-provider filtering string before it didn't

### ISSUE THREAD

**Issue by ksheyon123** [WalletConnect/walletconnect-monorepo#4265]
**Describe the bug**
Before I have used walletconnect v2.7.4 and recently I changed it to v2.11.0. And then accountsChanged event not working properly. I mean it doesn't return accounts.

And I found it that there is array chk filter on Universal-Provider. 

**please chk the 363 line.**

https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/providers/universal-provider/src/UniversalProvider.ts 

Also, One of our coworker try to change application to send array but mobile library not supporting send array. 

Is this change intended(Because it also doesn't return error)? And would you please chk this issues for us including mobile universal-provider library? 

**SDK Version (if relevant)**
 - Client: JS
 - Version 2.11.0

**Desktop (please complete the following information):**
 - Browser : Chrome, Safari

**Comment by ganchoradkov** [comment]
Hey @ksheyon123, per [EIP-1193](https://eips.ethereum.org/EIPS/eip-1193#events-1), the payload of accountsChanged must be `string[]` so any other payload is to be considered invalid. Which wallet are you interacting with?
