### ISSUE TITLE
Uncaught (in promise) Error: No RPC Url available for chainId: 100

### ISSUE THREAD

**Issue by garyng2000** [WalletConnect/walletconnect-monorepo#427]
When trying to connect to metamask mobile(which has xDai selected as active network, i.e. networkId 100), I get this error which cannot be try/catch or use the .catch(...)

I noticed that there are a number of very similar error reported before for different conditions occurred inside walletconnect.

What is the proper way to catch this or is it something that must be fixed insider the @walletconnect/web3-provider package itself ?

**Comment by RobertoSnap** [comment]
When constructing WalletConnectWeb3Provider you should set an RPC endpoint for that chainID

```
const provider = new WalletConnectWeb3Provider({
      rpc: {
        100: "https://someEndpoint.com",
      },
    });
```

**Comment by garyng2000** [comment]
yes that is what I do. but this is not a good solution. I cannot tell what the wallet is using so can't pre-code it

**Comment by RobertoSnap** [comment]
I think (don't know) that you are looking at this wrong. You "should" probably just support the chains you know will be used in dAapp and setup an RPC endpoints for those chains.

If you just want to use the RPC endpoint coming from whatever wallet, I strongly belive this is not supported in WalletConnectWeb3Provider.

**Comment by garyng2000** [comment]
and that is exactly what I said. I don't want to support whatever coming from the wallet but if it is something that I don't know, I got an exception in the dApp which I can't handle.

**Comment by dvcrn** [comment]
I think a better question wold be: How do you handle the exception that gets thrown when a unsupported chain gets connected? 

Wrapping initialization into a try/catch didn't do it for me.

**Comment by ghost** [comment]
```javascript
function handleErrorEvent (error) {
  console.log(error.message)
}

provider.on('error', handleErrorEvent)
```

**Comment by finessevanes** [comment]
@garyng2000, did @xavierlupin answer work for you?
