### ISSUE TITLE
Not getting events

### ISSUE THREAD

**Issue by gulerias284** [WalletConnect/walletconnect-monorepo#4271]
In my app I am not recieving events properly .Like when I disconnect session from app side it disconnects on both app and dapp side but when I am disconnecting from dapp side I dont recieve any events in app. Using versions

 "react-native": "0.68.2",
 "@walletconnect/jsonrpc-types": "^1.0.3",
 "@walletconnect/react-native-compat": "^2.11.2",
 "@walletconnect/utils": "^2.9.2",
 "@walletconnect/web3wallet": "^1.8.8",

**Comment by ganchoradkov** [comment]
Hey, please provide an example implementation how you're triggering the disconnects from the dapp side

**Comment by gulerias284** [comment]
I am not working on dapp side . when I connect with any dapp I dont receive any event on disconnect.

**Comment by ganchoradkov** [comment]
Are you subscribed to `web3wallet.on('session_delete', ...` to be able to receive delete events?
Which dapp are you testing with? It's possible that the dapp doesn't emit events correctly as well

**Comment by gulerias284** [comment]
> Are you subscribed to `web3wallet.on('session_delete', ...` to be able to receive delete events?
> Which dapp are you testing with? It's possible that the dapp doesn't emit events correctly as well

Yes I have subscribed to the event but not recieving the events. I have tested with multiple dapss

**Comment by ganchoradkov** [comment]
We're not aware of any issues with events emitting. 
I'm failing to reproduce with our example [dapp](https://react-app.walletconnect.com/) & [wallet](https://react-wallet.walletconnect.com/). The wallet receives the disconnect correctly. 
I saw that you're on  `"@walletconnect/web3wallet": "^1.8.8",` which is pretty outdated, please update to latest - currently `1.10.2`

**Comment by gulerias284** [comment]
Okay I will do the needful
