### ISSUE TITLE
Refused to frame 'https://verify.walletconnect.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors https://*.****.com https://*****.com".

### ISSUE THREAD

**Issue by damianlluch** [WalletConnect/walletconnect-monorepo#4277]
Hi, I'm getting this error.
Any suggestions?

I have configured the projectID.

```Refused to frame 'https://verify.walletconnect.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors https://*.****.com https://*****.com".```

**Comment by ganchoradkov** [comment]
Hey @damianlluch thanks for the report.
>"frame-ancestors https://*.****.com https://*****.com".

does this log comes from your cloud allowlist settings?

**Comment by wighawag** [comment]
I am having the same issue when testing locally

**Comment by bananaspliff** [comment]
i have the same issue
Refused to frame 'https://verify.walletconnect.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors

walletconnect not working

**Comment by AusPrinzip** [comment]
Same here

**Comment by deadeagle63** [comment]
@ganchoradkov any indication whether this is an actual issue or if this is a red herring?

**Comment by glitch-txs** [comment]
Fixed for localhost, if you're seeing this on production you need to:
- Verify your domain in the Cloud dashboard
- Make sure the `metadata.url` in your code is correct.
