### ISSUE TITLE
IOS Crashes When Using this package with react-native-webview

### ISSUE THREAD

**Issue by Martin2037** [WalletConnect/walletconnect-monorepo#4288]
**Describe the bug**
The IOS application crashes without any error messages when I click the connect button after installing both the Wallet-Connect and react-native-webview packages.

**SDK Version (if relevant)**
 - Client: [react-native]
 - Version ["@web3modal/wagmi-react-native": "1.2.0"]

**To Reproduce**
1. Install both **react-native walletconnect package** and **react-native-webview**
2. Click on the connect button
3. crashed with no error

**Expected behavior**
NO crash

**Screenshots**
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/63692237/b06ceefd-1e00-46d3-b70c-bc54d1828518)

**Desktop (please complete the following information):**
 - OS: [iOS 17.3.1]

**Smartphone (please complete the following information):**
 - Device: [iPhone14 Pro Max]
 - OS: [IOS 17.3.1]

**Additional context**
I create a repo for it
https://github.com/Martin2037/rn-modal-crash

**Comment by ignaciosantise** [comment]
Closing as its duplicated. We'll continue with the issue here https://github.com/WalletConnect/web3modal-react-native/issues/150
