### ISSUE TITLE
Invalid `WALLETCONNECT_DEEPLINK_CHOISE` value storing in the local storage

### ISSUE THREAD

**Issue by DtechLabs** [WalletConnect/walletconnect-monorepo#430]
Saved value in the local storage with key `WALLETCONNECT_DEEPLINK_CHOISE`is invalid.

Case: 
On a mobile device choice any wallet from `registry.json` on page 2 and next. 

Expected result:
 In the local storage has been saved the selected wallet

Actual result:
 In the local storage has been saved wallet from the first page with the selected position.

**Comment by aminhdev** [comment]
I have the same problem

**Comment by finessevanes** [comment]
@DtechLabs is this still an issue?
