### ISSUE TITLE
Unsupported wc_ method. wc_sessionPropose

### ISSUE THREAD

**Issue by Elysium-app** [WalletConnect/walletconnect-monorepo#4315]
**Describe the bug**
Unsupported wc_ method. wc_sessionPropose error when establishing a pairing.

**SDK Version**
 - @walletconnect/auth-client":  ^2.1.2

**To Reproduce**
Open the modal -> Scan QR code -> The modal shows Connection declined, then failed to connect wallet
An error message also prints on console: Unsupported wc_ method. wc_sessionPropose

**Expected behavior**
Successful connection

**Desktop (please complete the following information):**
 - Ubuntu
 - Chrome

![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/111016244/85672669-b762-4c8d-ac22-b0a4a0b3f723)

**Comment by wadguk** [comment]
Same here... Working on Typescript
It seems that the project example (wallet) which is given here, experiencing the same problem. Tried with Opensea and other dapps...

Using the latest version of viem.
@glitch-txs

**Comment by sweetmantech** [comment]
same issue

any updates from wallet connect team?

**Comment by glitch-txs** [comment]
Auth API was deprecated in favor of One-Click Auth in >=v2.5

https://docs.walletconnect.com/walletkit/features/one-click-auth
