### ISSUE TITLE
Remove `better-sqlite3` dependency

### ISSUE THREAD

**Issue by geigerzaehler** [WalletConnect/walletconnect-monorepo#433]
`@walletconnect/client` has a transitive dependency on `better-sqlite3` through
~~~
@walletconnect/utils -> @json-rpc-tools/utils -> @json-rpc-tools/types -> keyvaluestorage -> better-sqlite3
~~~
Since this just seems to be a dependency on types and since `better-sqlite3` takes quite some time to compile it would be great if this dependency could be eliminated or made optional.

**Comment by pedrouid** [comment]
solved since 1.3.5
