### ISSUE TITLE
@walletconnect/ethereum-provider bug

### ISSUE THREAD

**Issue by xqingWong** [WalletConnect/walletconnect-monorepo#4334]
**Describe the bug**
Using the @walletconnect/ethereum-provider plugin, version 2.11.2
Create the provider:
EthereumProvider.init({
...
methods: ['eth_sendTransaction', 'personal_sign', 'wallet_switchEthereumChain']
})
But when calling the wallet_switchEthereumChain method, I get the error 'w5.startsWith is not a function'

**SDK Version (if relevant)**
 - Client: [vue3+ts]
 - Version [2.11.2]

**Desktop (please complete the following information):**
 - OS: [window]
 - Browser [chrome]

**Additional context**
Can't quite figure out what's wrong.

**Comment by xqingWong** [comment]
Modified to:
EthereumProvider.init({
...
optionalMethods: ['eth_sendTransaction', 'personal_sign', 'wallet_switchEthereumChain']
})

Calling the wallet_switchEthereumChain method gives an error: w4.startsWith is not a function

**Comment by rouzwelt** [comment]
I get the same error, did you figure out anything? @xqingWong

**Comment by glitch-txs** [comment]
please share a minimal reproducible example + steps to reproduce. Thanks!

**Comment by xqingWong** [comment]
@glitch-txs

**Comment by xqingWong** [comment]
demo:

**Comment by xqingWong** [comment]
demo:
import { ref } from 'vue'
import { EthereumProvider } from '@walletconnect/ethereum-provider'

const provider = ref()
async function getProvider () {
    provider.value = await EthereumProvider.init({
        projectId: 'you projectId',
        showQrModal: true,
        optionalChains: [
            11155111, 421611, 42161, 1
        ],
        optionalMethods: ['eth_sendTransaction', 'personal_sign', 'wallet_switchEthereumChain']
    })
}
getProvider()

async function changeChain () {
    try {
        await provider.value.request({
            method: 'wallet_switchEthereumChain',
            params: [{ chainId: 1 }]
        })
        console.log('success')
    } catch (err) {
        console.log('err:', err)
    }
}

setTimeout(() => {
    changeChain()
}, 60000)

Please run the demo to check the issue. The changeChain function needs to be executed after establishing the WalletConnect connection  @glitch-txs

**Comment by xqingWong** [comment]
@rouzwelt 
await provider.value.request({
method: 'wallet_switchEthereumChain',
params: [{ chainId: ’0x1‘ }]
})  
Use the hexadecimal chain ID of the blockchain.
