### ISSUE TITLE
Wallet Connect Not Appear on Synthetix x Optimistic Collaboration

### ISSUE THREAD

**Issue by mehranhydary** [WalletConnect/walletconnect-monorepo#434]
Hi there! I used a non-Metamask wallet to send some SNX from L1 to L2. I want to mint some sUSD on L2 but I can't since Wallet Connect is not working on https://l2.mintr.synthetix.io/ yet. Is this the right place to open a ticket?

Thanks!

**Comment by pedrouid** [comment]
Not really... since it's up to projects to support WalletConnect. I would advise to tweet tag them or reach out to these teams on Discord directly
