### ISSUE TITLE
Angular 10 project, multiple Can't resolve XXXX errors

### ISSUE THREAD

**Issue by REPTILEHAUS** [WalletConnect/walletconnect-monorepo#435]
Trying to use WalletConnectProvider with in an project using ethersJS, simply adding the following lines causes all the errors below, project is an `Angular 10.1.3` one

Seems vaguely related to this issue https://github.com/WalletConnect/walletconnect-monorepo/issues/308

and using version `"@walletconnect/web3-provider": "^1.3.5",`

```
  [ng] ERROR in ./node_modules/xhr2-cookies/dist/xml-http-request.js
  [ng] Module not found: Error: Can't resolve 'http' in '/PATH/TO/PROJECT/node_modules/xhr2-cookies/dist'
  [ng] ERROR in ./node_modules/xhr2-cookies/dist/xml-http-request.js
  [ng] Module not found: Error: Can't resolve 'https' in '/PATH/TO/PROJECT/node_modules/xhr2-cookies/dist'
  [ng] ERROR in ./node_modules/xhr2-cookies/dist/xml-http-request.js
  [ng] Module not found: Error: Can't resolve 'os' in '/PATH/TO/PROJECT/node_modules/xhr2-cookies/dist'
  [ng] ERROR in ./node_modules/cipher-base/index.js
  [ng] Module not found: Error: Can't resolve 'stream' in '/PATH/TO/PROJECT/node_modules/cipher-base'
  [ng] ERROR in ./node_modules/keccak/lib/api/shake.js
  [ng] Module not found: Error: Can't resolve 'stream' in '/PATH/TO/PROJECT/node_modules/keccak/lib/api'
  [ng] ERROR in ./node_modules/keccak/lib/api/keccak.js
  [ng] Module not found: Error: Can't resolve 'stream' in '/PATH/TO/PROJECT/node_modules/keccak/lib/api'  
```

**Comment by imaksp** [comment]
yes it won't work if you add it using yarn/npm, you will need to include prebuilt version.
See another issue here: https://github.com/WalletConnect/walletconnect-docs/issues/44

**Comment by pedrouid** [comment]
I've replied on that issue on walletconnect-docs....

All packages have been distributed with CJS and UMD bundles which are available either through a CDN like `unpkg.com`

Alternatively you can download the latest minified files from the releases page:

https://github.com/walletconnect/walletconnect-monorepo/releases

**Comment by finessevanes** [comment]
@REPTILEHAUS @aksdevac is this still an issue?

**Comment by imaksp** [comment]
It (v1) still does not work out of the box with Angular CLI, it logs error like this so might require custom webpack config:
```
node_modules/cipher-base'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }
```

but I am using bundled js & loading it using defer so not a major issue,  also importing is directly will increase the bundle size significantly.

**Comment by finessevanes** [comment]
Since v1 will be deprecated soon, I'm going to close this issue since you were able to find a solution. Thank you.
