### ISSUE TITLE
MeatMask doesnt redirect back on iOS: I still have the same problem.

### ISSUE THREAD

**Issue by damdafayton** [WalletConnect/walletconnect-monorepo#4350]
I still have the same problem.
wagmi: 1.4.13
@web3modal/wagmi-react-native: 1.2.0

Also in documentation [here](https://docs.walletconnect.com/web3modal/react-native/about), there is `enableAnalytics` option for `createWeb3Modal ` but `@web3modal/wagmi-react-native@1.2.0` doesnt have such key.

_Originally posted by @damdafayton in https://github.com/WalletConnect/walletconnect-monorepo/issues/2622#issuecomment-1966021994_

WalletConnect closed this discussion. Are you not interested in solving this bug?

**Comment by glitch-txs** [comment]
Hello, this is a MetaMask issue and you should contact them instead
