### ISSUE TITLE
Do not reopen modal when using disconnect()

### ISSUE THREAD

**Issue by hazae41** [WalletConnect/walletconnect-monorepo#436]
Hey, when I call disconnect(), the modal reopens; any way to disable this?
I want to fully disconnect and use the app as a guest/unknown user

**Comment by jrhender** [comment]
@hazae41 Are you using the walletconnect web3-provider?

**Comment by hazae41** [comment]
Yes

**Comment by jrhender** [comment]
I might be seeing the same issue. What seems to be happening in my case is that after calling `WalletConnectProvider.close()`, `WalletConnectProvider.handleRequest` is called again which in turn calls `getWalletConnector` which triggers a new call to the connector's `createSession`. Is that what seems to be happening in your case?

**Comment by hazae41** [comment]
I don't know, it just reopens when I call .disconnect()

**Comment by joeandrews** [comment]
+1

**Comment by jrhender** [comment]
Implemented a workaround of extending `WalletConnect` to override `createSession` https://github.com/energywebfoundation/iam-client-lib/commit/42ee4391701a66161d1a3a2c8cbac5e5aaf143d4#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26

**Comment by pxr64** [comment]
+1

**Comment by hazae41** [comment]
The only workaround I had is to use the standalone client and use my own Web3 layer 
https://docs.walletconnect.org/quick-start/dapps/client

**Comment by anastasiosna** [comment]
+1 This is still an issue for me in web3-provider v1.7.1.  Thanks for your help @jrhender .

**Comment by steviesocks** [comment]
+1

**Comment by 0xSzeth** [comment]
+1

**Comment by swaxtic** [comment]
+1

**Comment by Shilza** [comment]
+1

**Comment by pawelmiklas** [comment]
+1

**Comment by ivanhdzd** [comment]
+1 in v1.7.8

**Comment by allisonle** [comment]
+1

**Comment by luca992** [comment]
> The only workaround I had is to use the standalone client and use my own Web3 layer https://docs.walletconnect.org/quick-start/dapps/client

what do you mean by your `own Web3 layer`? How are you getting a provider instance from the standalone client?

**Comment by hazae41** [comment]
> > The only workaround I had is to use the standalone client and use my own Web3 layer https://docs.walletconnect.org/quick-start/dapps/client
> 
> 
> 
> what do you mean by your `own Web3 layer`? How are you getting a provider instance from the standalone client?

Even better, I'm gonna build my own client and modal.

![image](https://user-images.githubusercontent.com/4405263/188885966-25df88b7-7377-4add-ba0d-2b846edd8974.jpeg)

**Comment by finessevanes** [comment]
@hazae41 is this still an issue?
