### ISSUE TITLE
jsonrpcprovider events undefined in web3wallet 1.10.3

### ISSUE THREAD

**Issue by sirpy** [WalletConnect/walletconnect-monorepo#4364]
**Describe the bug**
unable to start web3wallet pairing
an error is thrown that jsonrpcprovider.events.on is undefined

**SDK Version (if relevant)**
 - Client: JS
 - Version 1.10.3

doesnt happen in previous versions

**Comment by glitch-txs** [comment]
please share a minimal reproducible example + steps to reproduce. Thanks!
