### ISSUE TITLE
unable to pass capitalized wallet names to `mobileLinks`

### ISSUE THREAD

**Issue by shrugs** [WalletConnect/walletconnect-monorepo#437]
because we lowercase the wallet name key before comparing it, but don't also lowercase the comparison key

https://github.com/WalletConnect/walletconnect-monorepo/blob/b2cfd26b5648cf0fb884b8115a288977701d5116/packages/helpers/qrcode-modal/src/browser/components/MobileLinkDisplay.tsx#L33

solution: '.includes(name.toLowerCase())'

**Comment by pedrouid** [comment]
good catch I will push a release today for this

**Comment by pedrouid** [comment]
Fixed with v1.3.6
