### ISSUE TITLE
Transaction signing with walletconnect-tron

### ISSUE THREAD

**Issue by KrashheR** [WalletConnect/walletconnect-monorepo#4378]
Hello everyone! 
I have a problem with transactionsigning when using walletConnect-TRON through the adapter from TronWeb  `@tronweb3/walletconnect-tron`

When I try to submit a transaction using the adapter for signature, the notification from walletconnect to the mobile app doesn't always come, and if it does, nothing happens after confirmation. In addition, the following error appears in the console:

`{context: 'client'} 'No matching key. keychain: {someKeyChain}'
at vt.get (index.es.js:1:16678)
    at It.getSymKey (index.es.js:1:19474)
    at It.decode (index.es.js:1:18740)
    at EventEmitter.<anonymous> (index.es.js:1:25051)
    at EventEmitter.emit (events.js:158:1)
    at Ot.onMessageEvent (index.es.js:1:37303)
`

Has anyone encountered this error? And how did you fix it?
Maybe there are other ways to confirm transaction via walletconnect for tron?

Any help would be greatly appreciated, thank you!
</div>

**Comment by glitch-txs** [comment]
Hello, that's not a pacakge maintained by us, you should contact their maintainers instead 🙌
