### ISSUE TITLE
{context: 'core'} {context: 'core/relayer'}  Error: WebSocket connection closed abnormally with code: 3000 (JWT validation error: JWT Token is not yet valid)

### ISSUE THREAD

**Issue by yellowCrimsonGator** [WalletConnect/walletconnect-monorepo#4391]
**Describe the bug**
It takes a while for wallet connect modal to appear when executing `openWeb3Modal ` from web3modal package
If you take a look ath the console you can see the following errors appear

```
{context: 'core'} {context: 'core/relayer'} 
Error: WebSocket connection closed abnormally with code: 3000
(JWT validation error: JWT Token is not yet valid): basic.iat: 1712137804, now + time_leeway: 1712137786, time_leeway: 120)
```

**SDK**
```
"@web3modal/ethereum": "2.6.2",
"@web3modal/react": "2.6.2",
```
**To Reproduce**
1. Go to [aurora.plus](https://aurora.plus/)
2. Click on 'Connect Wallet' and maybe it ll be reproduced

**Expected behavior**
Modal should appear on first click 

**Screenshots**
<img width="994" alt="Screenshot 2024-04-03 at 14 30 23" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/112893988/5b5ab0ae-afc6-4469-959e-b7c29a9c55c7">

**Desktop (please complete the following information):**
 - OS: Mac Sonoma 14.1.1 (23B81)
 - Browser Firefox/Chrome

**Comment by yellowCrimsonGator** [comment]
![Uploading Screenshot 2024-04-05 at 19.18.57.png…]()

**Comment by yellowCrimsonGator** [comment]
<img width="717" alt="Screenshot 2024-04-05 at 19 18 57" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/112893988/e7bdf6cd-02c7-43a0-bc4e-53769aec046a">

**Comment by yellowCrimsonGator** [comment]
Maybe we should bump the dependencies or smth like that

**Comment by VigM-Figure** [comment]
This is very likely due to your system time being incorrect.  Check your computer settings.  I can recreate if I set my time into the future, and it is solved when the time is correctly set back to sync.
