### ISSUE TITLE
ability to switch theme light/dark when user changes the theme, without needing to reinstantiate the ethereumProvider

### ISSUE THREAD

**Issue by rouzwelt** [WalletConnect/walletconnect-monorepo#4394]
**Is your feature request related to a problem? Please describe.**
currently there is no way to switch the theme without reinstantiating the EthereumProvider

**Describe the solution you'd like**
A hook or a function that can easily switch theme on demand

**Comment by glitch-txs** [comment]
We have this in [Web3Modal](https://docs.walletconnect.com/web3modal/react/hooks#useweb3modaltheme)

have you check the modal object from WalletConnectModal? That UI was deprecated and we'll build a new one base on Web3Modal eventually
