### ISSUE TITLE
EthereumProvider `wallet_switchEthereumChain` request only redirects to the wallet the first request, and doesnt redirect anymore requests.

### ISSUE THREAD

**Issue by rouzwelt** [WalletConnect/walletconnect-monorepo#4398]
**Describe the bug**
EthereumProvider `wallet_switchEthereumChain` request only redirects to the wallet the first request, and doesnt redirect anymore requests.
so the first time the request is made from the app, it successfully redirects to the wallet (in this case metamask) and by clicking ok everything works fine, after that switching to another network from the app, will not redirect the request to the wallet anymore, however lookslike ti resolves in success silently in the backgoround without user noticing anything on their wallet.

**SDK Version (if relevant)**
 - Client: JS
 ```
"@walletconnect/ethereum-provider": "^2.11.3",
"@walletconnect/modal": "^2.6.2",
```

**To Reproduce**
1. init the `EthereumProvider` and connect with a mobile wallet (like metamask mobile) to the app
2. try switching the chain with:
```js
await walletconnectProvider?.request({
        method: "wallet_switchEthereumChain",
        params: [{ chainId: chainid.toString(16) }],
});
```
3. accept the request on the wallet
4. try switching the network again like above and this time no request is redirected to the user wallet

**Expected behavior**
Any switch network request from the dapp should be redirected to the user wallet

**Desktop (please complete the following information):**
 - OS: macOS v13.0.1
 - Browser safari v16.1 (webkit - tauri app)

**Comment by glitch-txs** [comment]
Hi, this is being addressed on the MetaMask side and will be fix. Thanks!
