### ISSUE TITLE
generatePlatformLogger vite vercel error

### ISSUE THREAD

**Issue by ersanyakit** [WalletConnect/walletconnect-monorepo#4402]
RollupError: node_modules/@walletconnect/core/dist/index.es.js (5:101): "generatePlatformLogger" is not exported by "node_modules/@walletconnect/logger/dist/esm/index.js", imported by "node_modules/@walletconnect/core/dist/index.es.js".

**Comment by glitch-txs** [comment]
Please try to add a description of the issue with more information, steps to reproduce and a minimal reproducible example. Thanks! 🙏
