### ISSUE TITLE
Webpack Error

### ISSUE THREAD

**Issue by ochikov** [WalletConnect/walletconnect-monorepo#441]
Hello,
Since a few days ago, this error start to encounter and I cannot use the package anymore:

```
ERROR in ./~/eth-json-rpc-filters/~/pify/index.js
Module parse failed: /ProjectPath/node_modules/eth-json-rpc-filters/node_modules/pify/index.js Unexpected token (44:2)
You may need an appropriate loader to handle this file type.
|               errorFirst: true,
|               promiseModule: Promise,
|               ...options
|       };
| 
 @ ./~/eth-json-rpc-filters/log-filter.js 8:11-26
 @ ./~/eth-json-rpc-filters/index.js
 @ ./~/web3-provider-engine/subproviders/filters.js
 @ ./~/@walletconnect/web3-provider/dist/cjs/index.js
 @ ./src/layouts/app-layout/AppLayout.js
 @ ./src/routes/index.js
 @ ./src/main.js
 @ multi ./src/main webpack-hot-middleware/client.js?path=/__webpack_hmr
```

**Comment by justinGrosvenor** [comment]
I'm getting the same error

**Comment by cjoshi85** [comment]
I am getting the same issue. Can you please let me know how to solve it?

**Comment by shayelbaz1** [comment]
Same Here....

**Comment by ochikov** [comment]
You just need to load a proper plugin in webpack, that works with destructuring.

**Comment by michjun** [comment]
Does anyone know how to solve this

**Comment by florinbardosi** [comment]
Any solution for this?

**Comment by florinbardosi** [comment]
> You just need to load a proper plugin in webpack, that works with destructuring.

Can you provide us more info ?

**Comment by 505969733** [comment]
how to fix ?

**Comment by Daudxu** [comment]
Any solution for this?

**Comment by ShevaShen** [comment]
The issue is with the Object spread operator since javascript es6, `pify/index.js` is using it.

Depends on your `webpack` configuration, you will have to do something to compile it. e.g. for `babel-loader` user, can look into a lib like this https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread

**Comment by Bommer2078** [comment]
> 问题在于对象扩展运算符，因为 javascript es6`pify/index.js`正在使用它。
> 
> 取决于您的`webpack`配置，您将不得不做一些事情来编译它。例如对于`babel-loader`用户，可以查看这样的库https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread



> 你好， 从前几天开始出现这个错误，我不能再使用这个包了：
> 
> ```
> ERROR in ./~/eth-json-rpc-filters/~/pify/index.js
> Module parse failed: /ProjectPath/node_modules/eth-json-rpc-filters/node_modules/pify/index.js Unexpected token (44:2)
> You may need an appropriate loader to handle this file type.
> |               errorFirst: true,
> |               promiseModule: Promise,
> |               ...options
> |       };
> | 
>  @ ./~/eth-json-rpc-filters/log-filter.js 8:11-26
>  @ ./~/eth-json-rpc-filters/index.js
>  @ ./~/web3-provider-engine/subproviders/filters.js
>  @ ./~/@walletconnect/web3-provider/dist/cjs/index.js
>  @ ./src/layouts/app-layout/AppLayout.js
>  @ ./src/routes/index.js
>  @ ./src/main.js
>  @ multi ./src/main webpack-hot-middleware/client.js?path=/__webpack_hmr
> ```

Hi have you fixed this bugs?

**Comment by Bommer2078** [comment]
> 

Did you find way? please help me

**Comment by sijinglei** [comment]
这个问题还没有人解决吗？

**Comment by finessevanes** [comment]
@ochikov @Bommer2078 is this still an issue?
