### ISSUE TITLE
Sequence Redirection on Mobile Issue

### ISSUE THREAD

**Issue by YapCaiFu** [WalletConnect/walletconnect-monorepo#4413]
### Discussed in https://github.com/orgs/WalletConnect/discussions/4412

<div type='discussions-op-text'>

<sup>Originally posted by **YapCaiFu** April  8, 2024</sup>
const { open } = useWeb3Modal()
When I used localhost to try the open() in mobile device, and select Sequence Wallet, the own ReactJs website will be auto replaced by sequence app website (https://sequence.app/connect) for login authentication, and there is no way to return back to own website after login successful. 

I am the beginner on using this, any advice on how to control this? Thanks in advance.
![ewallet](https://github.com/WalletConnect/walletconnect-monorepo/assets/26355257/2a9b4c64-d509-403a-a198-707f326971e6)
![ewallet2](https://github.com/WalletConnect/walletconnect-monorepo/assets/26355257/3d083484-b50f-4e30-ae1d-bdf63c2b7aa9)
![ewallet3](https://github.com/WalletConnect/walletconnect-monorepo/assets/26355257/61d06166-c978-4f7d-a079-c21a19504bd1)
</div>

**Comment by glitch-txs** [comment]
Let's follow up on the discussion. Thanks for reporting!
