### ISSUE TITLE
Reconnecting a session

### ISSUE THREAD

**Issue by skzap** [WalletConnect/walletconnect-monorepo#4437]
Hello

I am working on a mobile wallet app, and I am wondering how to re-open past sessions after the app has been restarted, and get the new session_request events from the session opened previously.

Please help, I could not find relevant information in the docs at https://docs.walletconnect.com/web3wallet/wallet-usage

Suggestion: give us a function to reconnect a session based on the topic id

**Comment by ganchoradkov** [comment]
Hey @skzap sorry for the late response. 
Sessions are re-connected automatically. The client persists all session data and when your app is launched again, it should connect all sessions in its storage without you having to do doing anything extra
