### ISSUE TITLE
Is there a way to connect Binance Smart Chain ?

### ISSUE THREAD

**Issue by sujithsomraaj** [WalletConnect/walletconnect-monorepo#445]
I'm using something like 
```
                       const web3Provider = new WalletConnectProvider({
                        rpc : {
					97 : 'https://data-seed-prebsc-1-s1.binance.org:8545/'
				}
                         });      
			await web3Provider.enable()
```

Still it's connecting to chain_id : 1, which is ethereum mainnet

**Comment by pedrouid** [comment]
You are configuring correctly but it's the wallet that controls the active chain. You need to prompt the user to switch to BSC chain

**Comment by sujithsomraaj** [comment]
Hello,

It didn't work with chain id 97 which is BSC testnet, but works fine with chain id 56 which is BSC mainnet. So I'm closing the issue here.

Thanks
