### ISSUE TITLE
relay.walletconnect.com websocket connection is opened even though there is no action and no topic subscriptions

### ISSUE THREAD

**Issue by chris13524** [WalletConnect/walletconnect-monorepo#4450]
**Describe the bug**
A WebSocket connection is opened in an private browser window before I even open the modal. It was described that the WebSocket connection isn't needed unless there is a subscribed topic. However it will still open the connection initially but then close it without any messages going through it.

[Slack conversation](https://walletconnect.slack.com/archives/C03RR5C0F7X/p1712773092221239?thread_ts=1712767993.823029&cid=C03RR5C0F7X)

**SDK Version (if relevant)**
latest

**To Reproduce**

1. Go to [https://lab.web3modal.com/library/wagmi/](https://lab.web3modal.com/library/wagmi/)
2. Observe a WebSocket connection is opened to [relay.walletconnect.com](http://relay.walletconnect.com)
3. WebSocket connection is then closed

**Expected behavior**
A WebSocket isn't opened until an action is performed that requires it (e.g. generating the QR code).

**Screenshots**

![image](https://uploads.linear.app/53158a94-cce0-42f0-a185-428db7e671e5/0038730e-8677-4f63-a632-7f49efdc354c/68b05690-55a2-4f6e-8cf4-fe8b7e1adeb7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUzMTU4YTk0LWNjZTAtNDJmMC1hMTg1LTQyOGRiN2U2NzFlNS8wMDM4NzMwZS04Njc3LTRmNjMtYTYzMi03ZjQ5ZWZkYzM1NGMvNjhiMDU2OTAtNTVhMi00ZjZlLThjZjQtZmU4YjdlMWFkZWI3IiwiaWF0IjoxNzEzMzYxMDUxLCJleHAiOjMzMjgzOTIxMDUxfQ.9E732ksjo6LnrWqWEzwBEzarEFN5Pk9YENQ3QxyiHZQ)

**Comment by ganchoradkov** [comment]
Hey @chris13524 this is done by design. The websocket is opened on client init to validate that the connection can actually be established. Think of the cases where `projectid` is missing/invalid, jwt is invalid etc. It would only be caught when user tries to interact with the client and might mislead devs into thinking that since client inits, all is good while that isn't the case
