### ISSUE TITLE
React Native Push Notification Not working

### ISSUE THREAD

**Issue by aabdullah29** [WalletConnect/walletconnect-monorepo#4465]
**web3wallet React Native Push Notification Not working**

I am facing some issues with push notifications in React Native. I developed a custom wallet and used Web3Wallet to connect with a DApp. I need to receive push notifications from the DApp whenever a session is created and then take action accordingly. Although I implemented the push notification configuration provided in the mobile app, I'm not receiving any notifications. I followed the instructions outlined in this [link](https://docs.walletconnect.com/web3wallet/push-notifications?platform=react-native)

Web3Wallet only gets my FCM token, not my Firebase Server Key, I am wondering that how I get a push notification without the Firebase Server Key.

**Comment by aabdullah29** [comment]
I'm waiting for a response regarding this issue. Can you clarify that I've configured push notifications in React Native for the handling of notifications automatically coming from the DApp's side, or does it require any additional configurations on the DApp's end as well?

**Comment by chris13524** [comment]
Hey @aabdullah29 ! Looks like our docs have a gap here. There is another guide you need to follow to setup your FCM API key in WalletConnect Cloud. This does not require any configuration from the dApp. Instructions here: https://docs.walletconnect.com/advanced/push-server

**Comment by aabdullah29** [comment]
Thanks for helping me out.

**Comment by chris13524** [comment]
Glad to help!
