### ISSUE TITLE
Can't resolve 'pino-pretty' when installing `@walletconnect/ethereum-provider` with pnpm

### ISSUE THREAD

**Issue by joaquim-verges** [WalletConnect/walletconnect-monorepo#4466]
**Describe the bug**
installing `@walletconnect/ethereum-provider` with pnpm results in the following error at runtime:

```
Module not found: Can't resolve 'pino-pretty' in '/Users/joaquim/Work/templates/account-abstraction/node_modules/.pnpm/pino@7.11.0/node_modules/pino/lib'

Import trace for requested module:
./node_modules/.pnpm/pino@7.11.0/node_modules/pino/lib/tools.js
./node_modules/.pnpm/pino@7.11.0/node_modules/pino/pino.js
./node_modules/.pnpm/@walletconnect+logger@2.1.2/node_modules/@walletconnect/logger/dist/index.es.js
./node_modules/.pnpm/@walletconnect+universal-provider@2.11.3/node_modules/@walletconnect/universal-provider/dist/index.es.js
./node_modules/.pnpm/@walletconnect+ethereum-provider@2.11.3_@types+react@18.0.0_react@18.0.0/node_modules/@walletconnect/ethereum-provider/dist/index.es.js
```

It looks like the `pino-pretty` dependency is not declared properly, resulting in a missing module.

**SDK Version (if relevant)**
 - `@walletconnect/ethereum-provider`
 - 2.12.2

**To Reproduce**
1. `pnpm install @walletconnect/ethereum-provider`
2. run the application

**Expected behavior**
no runtime errors

**Comment by glitch-txs** [comment]
Where are you installing it? Is it Next.js? Same issue in version 2.11?

**Comment by joaquim-verges** [comment]
yes this was on a next.js project - have not tried 2.11 but seems related to https://github.com/WalletConnect/walletconnect-monorepo/issues/1908

**Comment by glitch-txs** [comment]
Could you try this: https://docs.walletconnect.com/web3modal/nextjs/about#extra-configuration

**Comment by diegosano** [comment]
> Could you try this: https://docs.walletconnect.com/web3modal/nextjs/about#extra-configuration

I had the same problem and this worked 🚀

**Comment by artemis-prime** [comment]
> > Could you try this: https://docs.walletconnect.com/web3modal/nextjs/about#extra-configuration
> 
> I had the same problem and this worked 🚀

What's the "this" you're trying?  Has the url chqanged?

**Comment by ga-reth** [comment]
@artemis-prime and anyone else seeing this issue, the fix is:

```
// Path: next.config.js
const nextConfig = {
  webpack: config => {
    config.externals.push('pino-pretty', 'lokijs', 'encoding')
    return config
  }
}
```

the URL had changed https://docs.reown.com/appkit/next/core/installation#extra-configuration
