### ISSUE TITLE
Domain verification is incorrectly generated for `.it.com` TLD

### ISSUE THREAD

**Issue by raviriley** [WalletConnect/walletconnect-monorepo#4471]
### Discussed in https://github.com/orgs/WalletConnect/discussions/4451

<div>

When adding a domain with the `.it.com` TLD, the Verify API looks for the DNS record at [it.com](https://get.it.com). This is broken and needs to be fixed.

</div>

**Comment by raviriley** [comment]
This is currently preventing anyone with a .it.com domain from using WalletConnect. Any chance a patch can be pushed ASAP similar to how .co.uk behaves?

**Comment by raviriley** [comment]
@Cali93 @bkrem @glitch-txs any chance this can be patched this month? 🙏

**Comment by Cali93** [comment]
@raviriley Thanks for raising this. We will ship a fix in the upcoming days.

> This is currently preventing anyone with a .it.com domain from using WalletConnect

Just as a clarification, it's preventing them from using Verify API, not the whole WalletConnect Protocol.

**Comment by raviriley** [comment]
Awesome! You're right, thanks for the clarification 👌

**Comment by Cali93** [comment]
Hey @raviriley,

We updated our implementation and TLDs like `.it.com` are now parsed correctly.

Thanks for your patience 🙏

**Comment by raviriley** [comment]
Awesome, thanks @Cali93 🥳
