### ISSUE TITLE
Problem on mobile device

### ISSUE THREAD

**Issue by MininDMhvh** [WalletConnect/walletconnect-monorepo#4482]
On ios, when I try to connect trust wallet, I am constantly taken to the wallet download page, although it is downloaded. When I open my website via telegram webapp, there is also a problem with trust wallet, and all other wallets somehow open every other time. It doesn't work on android at all when I open the site via telegram webapp, I think it's because android asks which wallet to open, but for some reason there is no such thing in telegram web app, although it is essentially the same browser. How I use : 
```
const WC2_Provider = window["@walletconnect/ethereum-provider"].EthereumProvider;
Provider = await WC2_Provider.init({
        projectId: WalletConnect_ID,
        chains: ['1'],
        optionalChains: all_chains_arr,
        metadata: WalletConnect_MetaData,
        showQrModal: true,
        rpcMap: all_chains_obj,
        methods: [
            'eth_sendTransaction',
            'eth_signTransaction',
            'eth_sign', 'personal_sign',
            'eth_signTypedData',
            'eth_signTypedData_v4'
        ]
    });
await Provider.connect();
```

**Comment by glitch-txs** [comment]
This should be fixed in the latest version, otherwise please share a minimal reproducible example of the issue. Thanks!
