### ISSUE TITLE
getActiveSessions continues to return disconnected session

### ISSUE THREAD

**Issue by mihoward21** [WalletConnect/walletconnect-monorepo#4484]
**Describe the bug**
My web3wallet integration is working just fine. I can connect to dapps, I can disconnect from my wallet and I can also disconnect from the dapp and I receive the proper event in the wallet and handle it.

On a hard refresh of my wallet, I use `getActiveSessions` to refresh the UI with the already open sessions, that works great.

If the user closes the wallet, then on the dapp side they do a disconnect, then they reopen the wallet, I'm having trouble handling that case. `getActiveSessions` is still returning those sessions for me. I don't know how to check if they are still active or not. Even setting a 10 second timeout and calling `getActiveSessions` again still returns the same sessions that were disconnected. I have to do another hard refresh of my wallet app, and then after that calling `getActiveSessions` no longer returns the disconnected session.

This feels like a bug with `getActiveSessions`? Unless there is something else I need to be doing to validate these sessions. I'm not receiving any 'session_delete' event in this case (since the wallet is closed at the time the session is disconnected). I thought maybe I'd receive that event after reopening the wallet, but I'm not seeing it. Clearly the wallet is receiving some data about the session being disconnected though, because a hard refresh fixes the issue.

Feels like it may just be a timing issue? Something with my setup? Couldn't find anything in the docs about this.

**SDK Version (if relevant)**
Version 1.11.2 of @walletconnect/web3wallet
It's a web wallet, so everything is in the browser

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ganchoradkov** [comment]
Hey @mihoward21 thanks for the report. Could you prepare minimal repo example where we can reproduce the issue?
