### ISSUE TITLE
Error for initializing [TypeError: Cannot read property 'Core' of undefined]

### ISSUE THREAD

**Issue by YudaAdiPratama** [WalletConnect/walletconnect-monorepo#4487]
**Describe the bug**
Error for initializing [TypeError: Cannot read property 'Core' of undefined]

**SDK Version (if relevant)**
 - Client: [e.g. Typescript, React Natvie]
 - Version [
    "@walletconnect/react-native-compat": "^2.12.2",
    "@walletconnect/web3wallet": "^1.11.2",
    "@walletconnect/jsonrpc-types": "^1.0.3",
   ]

**Additional context**
```
 LOG  Web3WalletSDK initialized: false
 LOG  WARNING: Missing strong random number source
 LOG  Error for initializing [Error: no secure random source avaialble (operation="crypto.getRandomValues", code=UNSUPPORTED_OPERATION, version=random/5.7.0)]
 LOG  null

```

**Comment by ganchoradkov** [comment]
Hey @YudaAdiPratama could you please try to explicitely declare `@walletconnect/core` in your package.json. In some cases the app builder might not build all required deps unless explicitely declared

**Comment by ganchoradkov** [comment]
also make sure `@walletconnect/react-native-compat` is imported at the top of your files before any other `@walletconnect` deps
