### ISSUE TITLE
QR code modal showing error while closing the modal 

### ISSUE THREAD

**Issue by avinashbuddana** [WalletConnect/walletconnect-monorepo#449]
When i am clicking to close the modal in react it is generating error ×
Unhandled Rejection (Error): User closed modal

![Screenshot from 2021-02-22 18-09-35](https://user-images.githubusercontent.com/13912798/108710896-a911c880-753a-11eb-85e0-1bec5fc1d30e.png)

**Comment by jest-games** [comment]
Same issue here.

**Comment by 0xKurt** [comment]
surround with try and catch

**Comment by ghost** [comment]
Same issue here.
How can I surround with try and catch?
could you attach the sample code?

**Comment by Iftikhar708** [comment]
try {
        const provider = new WalletConnectProvider({
          infuraId: 'c4f79cc821944d9680842e34466bfbd',
        });
        await provider.enable();
      } catch (error) {
        console.log(error);
      }

**Comment by Iftikhar708** [comment]
> Same issue here. How can I surround with try and catch? could you attach the sample code?

resolve this issue within try-catch

import WalletConnectProvider from "@walletconnect/web3-provider";

 try  {
        const provider = new WalletConnectProvider({
          infuraId: 'c4f79cc821944d9680842e34466bfbd',
        });
        await provider.enable();
      } catch (error) {
        console.log(error);
      }

**Comment by finessevanes** [comment]
@avinashbuddana is this still an issue?
