### ISSUE TITLE
Polling Timeout not handled

### ISSUE THREAD

**Issue by digitaldonkey** [WalletConnect/walletconnect-monorepo#45]
If you start listening for confirmation via QR code after some while the session times out and walletConnect stops polling the bridge server. 

in my current approach I wrap that in a try catch block and provide a retry button.

https://github.com/digitaldonkey/web3ready/blob/7623a475ebbdb2c7f89e866876f6e4b9ef0c3244/src/components/signerDialogs/WalletConnect.vue#L104-L116

You might want to handle that in the QR code app too. 

It would also be great to override the timeout settings in listenSessionStatus(POLL_INTERVAL, TIMEOUT).

**Comment by pedrouid** [comment]
> If you start listening for confirmation via QR code after some while the session times out and walletConnect stops polling the bridge server. in my current approach I wrap that in a try catch block and provide a retry button.

Good point! Going to add that really quick to handle the timeout better. 

> It would also be great to override the timeout settings in listenSessionStatus(POLL_INTERVAL, TIMEOUT)

Regarding this last comment, is currently fixed, update to the lastest version

**Comment by pedrouid** [comment]
I've looked at these issues and they are working. Timeout's are catched when Error is thrown and timeout arguments are passed
