### ISSUE TITLE
Desktop Wallets

### ISSUE THREAD

**Issue by sk91** [WalletConnect/walletconnect-monorepo#450]
Hi, 

You have multiple popular wallets listed in your integrations https://walletconnect.org/wallets

But all of them are mobile wallets. Is there a specific reason why desktop wallets are not there or is just because lack of candidates?

**Comment by pedrouid** [comment]
well technically there are desktop wallets supporting it even if they are only one or two

I've started a new registry that will make these distinctions so that it can be reflected on the website too

https://github.com/WalletConnect/walletconnect-registry

**Comment by sk91** [comment]
@pedrouid 

```
"app": {
      "browser": "",
      "ios": "",
      "android": ""
    },
    "mobile": {
      "native": "mathwallet:",
      "universal": "https://www.mathwallet.org"
    },
```

for desktop apps based on electron, should the browser entry be used in this repository?

Also, on the client if you try to use wallet connect, you automatically get the qr code. Are there plans to add options for desktop wallets as well? 

<img width="1149" alt="Screenshot 2021-03-03 at 14 16 46" src="https://user-images.githubusercontent.com/1021965/109804723-3f28ab80-7c2b-11eb-9a52-bdc2deee9aaf.png">


We have implemented a custom connection for our desktop wallet in selfkey, based on wallet connect protocol, but it would be amazing if we can register it natively on the wallet connect library

<img width="502" alt="Screenshot 2021-03-03 at 14 18 44" src="https://user-images.githubusercontent.com/1021965/109804885-739c6780-7c2b-11eb-86d3-7556c71de35d.png">

**Comment by pedrouid** [comment]
actually I should update that registry to include also `mac`, `windows` and `linux` entries

Therefore your electron app should be included in the platforms that you support

Also Im noticing in these screenshots that you used Coinbase Wallet logo next to WalletConnect, could you change these?

**Comment by sk91** [comment]
> Also Im noticing in these screenshots that you used Coinbase Wallet logo next to WalletConnect, could you change these?

sure, will report it to the devs of this app

**Comment by pedrouid** [comment]
I have also updated the registry to a more broad schema that will take Desktop wallets into consideration

```typescript
  export interface AppEntry {
    name: string;
    logo: string;
    homepage: string;
    type: string;
    chains: string[];
    app: {
      browser: string;
      ios: string;
      android: string;
      mac: string;
      windows: string;
      linux: string;
    };
    mobile: {
      native: string;
      universal: string;
    };
    desktop: {
      native: string;
      universal: string;
    };
  }
```
