### ISSUE TITLE
After connecting on mobile Safari and then signing with AlphaWallet on iOS, the example.walletconnect.org dapp redirects to Math Wallet

### ISSUE THREAD

**Issue by hboon** [WalletConnect/walletconnect-monorepo#454]
<img width='200' src='https://user-images.githubusercontent.com/56189/110274346-93f06b80-8009-11eb-8516-ec5cbcdc927f.PNG'>

1. Visit https://example.walletconnect.org with Mobile Safari
2. Connect with AlphaWallet
3. Tap one of the sign buttons
4. The overlay to sign appears briefly in Safari

Expected:

5. Switches to AlphaWallet to sign

Observed:

5. Safari navigates to https://mathwallet.org/wc/en/ instead

**Comment by vladyslav-iosdev** [comment]
visiting https://example.walletconnect.org triggers aw and shows sign screen for me.

**Comment by hboon** [comment]
Great. Closing it then.
