### ISSUE TITLE
Add Bitlayer Testnet

### ISSUE THREAD

**Issue by 307590317** [WalletConnect/walletconnect-monorepo#4566]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
   **GitHub Link**: https://docs.bitlayer.org/docs/BitlayerNetwork/Json-RPC
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
```json
{
  "name": "Bitlayer Testnet",
  "chain": "Bitlayer",
  "rpc": [
    "https://testnet-rpc.bitlayer.org",
    "wss://testnet-ws.bitlayer.org",
    "https://testnet-rpc.bitlayer-rpc.com",
    "wss://testnet-ws.bitlayer-rpc.com",
    "https://rpc.ankr.com/bitlayer_testnet"
  ],
  "faucets": ["https://www.bitlayer.org/faucet"],
  "nativeCurrency": {
    "name": "BTC",
    "symbol": "BTC",
    "decimals": 18
  },
  "infoURL": "https://docs.bitlayer.org/",
  "shortName": "btrt",
  "chainId": 200810,
  "networkId": 200810,
  "slip44": 1,
  "icon": "bitlayer",
  "explorers": [
    {
      "name": "bitlayer testnet scan",
      "url": "https://testnet.btrscan.com",
      "standard": "EIP3091"
    }
  ]
}
```
3. **namespaces**:
   eip155
4. **chains**:
   eip155:200810
5. **RPC endpoints**
    https://testnet-rpc.bitlayer.org
    https://testnet-rpc.bitlayer-rpc.com
    https://rpc.ankr.com/bitlayer_testnet
    wss://testnet-ws.bitlayer-rpc.com
    wss://testnet-ws.bitlayer.org
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
    1

**References**
To ensure timely processing of your request, please provide the following references:

- [x] Source of RPC endpoints (e.g. RPC docs): https://docs.bitlayer.org/docs/BitlayerNetwork/Networks/
- [x] Source of namespace (if non-EIP155) chain information (particularly chainIds): EIP155 compliant

**Additional context**
faucet:https://www.bitlayer.org/faucet
network docs:https://docs.bitlayer.org/docs/Introduction
blockExplorer:https://testnet.btrscan.com
---

**Please note:**

**Registering a chain with the Explorer does not impact or improve the ability for wallets and dapps to support your chain.** It is simply a way for users to discover wallets and dapps that support your chain by:

- Browsing the [Chains List](https://docs.walletconnect.com/advanced/multichain/chain-list)
- Filtering results programmatically via the [Explorer API](https://docs.walletconnect.com/cloud/explorer)

**It is still up to wallets and dapps to provide concrete support for your chain once it is listed as part of the Explorer.**

- [x] I have read and understood the above clarification

**Comment by Cali93** [comment]
Hey @307590317, Bitlayer testnet and mainnet are available in the chain list of our explorer since June 6.
Sorry for the delayed update here.
