### ISSUE TITLE
`@walletconnect/sign-client` v2.13.0 type error

### ISSUE THREAD

**Issue by HeesungB** [WalletConnect/walletconnect-monorepo#4569]
**Describe the bug**
I'm migrating to version `2.13.0` of `@walletconnect/sign-client` and I'm getting a typescript error.
This is the situation I saw when doing a `tsc build`.
It is okay on `v2.12.2`

```
../../node_modules/@walletconnect/core/dist/types/controllers/relayer.d.ts(13,5): error TS2416: Property 'provider' in type 'Relayer' is not assignable to the same property in base type 'IRelayer'.
  Type 'import("/Users/aa/bb/node_modules/@walletconnect/jsonrpc-types/dist/cjs/provider").IJsonRpcProvider' is not assignable to type 'import("/Users/aa/bb/node_modules/@walletconnect/types/node_modules/@walletconnect/jsonrpc-types/dist/types/provider").IJsonRpcProvider'.
    Property 'setConnection' is protected but type 'IJsonRpcProvider' is not a class derived from 'IJsonRpcProvider'.
```

**SDK Version (if relevant)**
 - Client: React(v18.2.0), Typescript(v5.0.4)

**Comment by glitch-txs** [comment]
Hi, could you share your package.json file?

**Comment by HeesungB** [comment]
@glitch-txs You can see below link

https://github.com/chainapsis/keplr-wallet/pull/1128


The body of the error.
```
Error: ../../node_modules/@walletconnect/sign-client/node_modules/@walletconnect/core/dist/types/controllers/relayer.d.ts(13,5): error TS2416: Property 'provider' in type 'Relayer' is not assignable to the same property in base type 'IRelayer'.
  Type 'import("/home/runner/work/keplr-wallet/keplr-wallet/node_modules/@walletconnect/jsonrpc-types/dist/cjs/provider").IJsonRpcProvider' is not assignable to type 'import("/home/runner/work/keplr-wallet/keplr-wallet/node_modules/@walletconnect/types/node_modules/@walletconnect/jsonrpc-types/dist/types/provider").IJsonRpcProvider'.
    Property 'setConnection' is protected but type 'IJsonRpcProvider' is not a class derived from 'IJsonRpcProvider'.

lerna ERR! yarn run build exited 2 in '@keplr-wallet/wc-qrcode-modal'
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
Error: Process completed with exit code 2.
```

**Comment by ganchoradkov** [comment]
hey @HeesungB, I think this error is caused by out-of-date util dependencies. Please update all `@walletconnect/` deps to their latest and the build should work correctly

**Comment by HeesungB** [comment]
@ganchoradkov I think it that occurred by different version of `@walletconnect/jsonrpc-utils` between `sign-client` and `types`

https://github.com/WalletConnect/walletconnect-monorepo/blob/d624dfc9f9fd8bd81fca50bfa96aba15416a9cfd/packages/sign-client/package.json#L44

https://github.com/WalletConnect/walletconnect-monorepo/blob/d624dfc9f9fd8bd81fca50bfa96aba15416a9cfd/packages/types/package.json#L32

**Comment by glitch-txs** [comment]
Could you run `npm ls @walletconnect/sign-client`?

**Comment by glitch-txs** [comment]
I see you're probably right, in the meantime you can use "overrides" or "resolutions" If you're using yarn.

**Comment by Maliksb11** [comment]
Happy 😁
