### ISSUE TITLE
Web3Wallet.init  It takes more than ten seconds to return

### ISSUE THREAD

**Issue by xiao0502** [WalletConnect/walletconnect-monorepo#4577]
const REGIONALIZED_RELAYER_ENDPOINTS = [
    {
        value: "wss://relay.walletconnect.com",
        label: "Default",
    },
    {
        value: "wss://us-east-1.relay.walletconnect.com",
        label: "US",
    },
    {
        value: "wss://eu-central-1.relay.walletconnect.com",
        label: "EU",
    },
    {
        value: "wss://ap-southeast-1.relay.walletconnect.com",
        label: "Asia Pacific",
    },
];

const core = new Core({
      projectId: NEXT_PUBLIC_PROJECT_ID,
      relayUrl: REGIONALIZED_RELAYER_ENDPOINTS[0].value
  });

const web3wallet = await Web3Wallet.init({
    core
});
 
 ---------
 
 
 No matter which RELAYER is used, it takes more than ten seconds for web3wallet to respond. Can you shorten the time

**Comment by glitch-txs** [comment]
Could you please share a minimal reproducible example?
