### ISSUE TITLE
ETH Contract tx events

### ISSUE THREAD

**Issue by ziyi-zhang-1130** [WalletConnect/walletconnect-monorepo#458]
Hi all, I connected to metamask mobile app via walletconnect and I made a token transfer using an ETH contract and `web3.eth.Contract.methods.xxxMethod.send()`. After the tx was made, I could not listen to any [tx events](https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#methods-mymethod-send) but "transactionHash". Is this expected? Thanks!

**Comment by finessevanes** [comment]
@ziyi-zhang-1130 is this still an issue?

**Comment by ziyi-zhang-1130** [comment]
It's good now, thanks for your reply!
