### ISSUE TITLE
Error with react-native-compat + Expo Go crashes on iOS when trying to create a Web3Wallet instance

### ISSUE THREAD

**Issue by Patryqss** [WalletConnect/walletconnect-monorepo#4586]
**Description**

I'm trying to use a Web3Wallet library in my app. I followed the documentation presented [here](https://docs.walletconnect.com/web3wallet/about) and [here](https://docs.walletconnect.com/web3wallet/wallet-usage) and I have two issues:

First, the import of `@walletconnect/react-native-compat` throws an error: `react-native-compat: Application module is not available`
While searching for similar problems, I only found one example but [it was not solved](https://stackoverflow.com/questions/78479229/react-native-compat-application-module-is-not-available)

Second, if I try to run the app on iOS Simulator or an iPhone, running `Web3Wallet.init` (clicking on the button in the Reproducer example) crashes my Expo Go app without even throwing a single log. It may be somehow connected to the first issue but I'm not sure since it works fine on an Android device

**Steps to reproduce**
Clone this repo and follow the readme file -> https://github.com/Patryqss/Test-Expo-and-Web3Wallet

**Expected behavior**
It's expected to work, not crash and not throw any error

**Screenshots**
https://github.com/WalletConnect/walletconnect-monorepo/assets/53139396/6064a7ce-d52b-488c-92bb-628b775fdfbb

**Desktop:**
 - OS: macOS 14.4.1

**Smartphone:**
 - Device: iPhone SE 2020 and iPhone 15 Simulator
 - OS: iOS 16.0 (20A362)

**Comment by ignaciosantise** [comment]
Hey @Patryqss 👋 

can you try installing `expo-application` package?

That might solve the issues

**Comment by Patryqss** [comment]
Thank you! You're right, it solved both issues

**Comment by itsZain1** [comment]
Hey @ignaciosantise👋

I encountered an error after installing expo-application. I am following this link to integrate walletConnect in my react native app https://docs.walletconnect.com/web3modal/react-native/about?platform=wagmi1. Can you help me resolve it?

<img width="1175" alt="Screenshot 2024-06-10 at 12 13 49 PM" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/131389712/2b90ed5c-25f2-4f55-a0e2-8e9b6f136981">

**Comment by ignaciosantise** [comment]
hey @itsZain1 👋 This seems not related to expo-application. Please open a new issue in https://github.com/WalletConnect/web3modal-react-native with more info, and a minimal reproducible example

**Comment by itsZain1** [comment]
@ignaciosantise I have created an issue here: https://github.com/WalletConnect/web3modal-react-native/issues/172
