### ISSUE TITLE
eth_sign JSON RPC call non standard

### ISSUE THREAD

**Issue by ligi** [WalletConnect/walletconnect-monorepo#46]
the params need to contain the address - see this specification:

https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sign

currently I am getting:

`{"data":{"id":1542983039187449,"jsonrpc":"2.0","params":["My email is john@doe.com - 1537836206101"],"method":"eth_sign"}}
`

**Comment by pedrouid** [comment]
This is a big issue currently, the SDK is too barebones right now. I need to add checks to make JSON RPC requests complaint with the spec (including the examples given on the README)

**Comment by pedrouid** [comment]
Fixed on `0.7.27`
