### ISSUE TITLE
Cant get payload while "Subscribe to session requests"

### ISSUE THREAD

**Issue by ghost** [WalletConnect/walletconnect-monorepo#461]
I cant get payload till I change app_state from ACTIVE to BACKGROUND || INACTIVE. Both Platform iOS & Android
Please support me!
Thanks. @pedrouid

**Comment by Sotatek-HieuDuong** [comment]
@pedrouid

**Comment by finessevanes** [comment]
@Sotatek-HieuDuong is this still an issue?
