### ISSUE TITLE
Does not receive any callback after signing message.

### ISSUE THREAD

**Issue by iserifith** [WalletConnect/walletconnect-monorepo#462]
Im trying to sign simple message using ethers, wallet connect and metamask app on android.

```js
      const provider = new WalletConnectProvider({
        infuraId: '--', // replace infuraId
      });
      await provider.enable();
      const web3 = new providers.Web3Provider(provider);
      const signer = web3.getSigner();
      const signature = await signer.signMessage('Hello World');
      console.log('ok')
      console.log(signature);
```

It did prompt on my phone to sign but I didnt receive any callback from it. This method works well for other providers such as fortmatic and metamask.

**Comment by roheat** [comment]
Facing the same issue here.
I am using the web3-react connector `@web3-react/walletconnect-connector": "^6.1.9"`
Ethers version: `"@ethersproject/experimental": "^5.0.5"`

**Comment by StillFantastic** [comment]
Same issue.
Both `ethers.js` or directly using the connector's `signMessage` method don't work.

**Comment by StillFantastic** [comment]
Can confirm this low-level way works.

```javascript
if (connector instanceof WalletConnectConnector) {
  const messageLength = new Blob([rawMessage]).size
  const message = toUtf8Bytes(
    "\x19Ethereum Signed Message:\n" + messageLength + rawMessage
  )
  const hashedMessage = keccak256(message)
  connector.walletConnectProvider.connector.signMessage([account.toLowerCase(), hashedMessage])
    .then(response => {
      console.log(response)
    })
    .catch(error => {
      console.log(error)
    })
} else {
  // original way
```

**Comment by rashiq-ddc** [comment]
Same issue here. able to sign transaction from the android app. couldn't get any confirmation message on Dapp UI

**Comment by wslyvh** [comment]
Same issue.

Trying to get this to work in combination with web3Modal. It seems like the connector isn't exposed from there? 
Or maybe I'm missing something? Is there a way to get the connector from web3Modal?

**Comment by wslyvh** [comment]
Here's another workaround (if you're using web3Modal)

```
// configure web3Modal 
const web3 = await web3Modal.connect();
const provider = new providers.Web3Provider(web3);
const signer = provider.getSigner()
const address = await signer.getAddress();

let signedMessage;
if (web3.wc) {
    signedMessage = await provider.send(
        'personal_sign',
        [ ethers.utils.hexlify(ethers.utils.toUtf8Bytes(rawMessage)), address.toLowerCase() ]
    );
}
else { 
    signedMessage = await signer.signMessage(rawMessage)
}
```

**Comment by RiccardoBiosas** [comment]
I'm using ```@walletconnect/web3-provider": "^1.4.1``` and I'm facing the same issue. None of the solutions reported here worked

**Comment by nigeon** [comment]
Same here, none of the solutions working :(

**Comment by ming436534** [comment]
> Can confirm this low-level way works.
> 
> ```js
> if (connector instanceof WalletConnectConnector) {
>   const messageLength = new Blob([rawMessage).size
>   const message = toUtf8Bytes(
>     "\x19Ethereum Signed Message:\n" + messageLength + rawMessage
>   )
>   const hashedMessage = keccak256(message)
>   connector.walletConnectProvider.connector.signMessage([account.toLowerCase(), hashedMessage])
>     .then(response => {
>       console.log(response)
>     })
>     .catch(error => {
>       console.log(error)
>     })
> } else {
>   // original way
> ```
I finally used the above method to sign the message successfully, but the message displayed in the confirm dialog is unreadable(hex string), may I ask how to fix this? Thank you.

**Comment by StillFantastic** [comment]
@ming436534 
```javascript
    if (connector instanceof WalletConnectConnector) {
      const message = hexlify(toUtf8Bytes(messageToSign))

      connector.walletConnectProvider.connector
        .signPersonalMessage([message, account.toLowerCase()])
        .then(response => {
         ...
        })
        .catch(error => {
          ...
        })
    } else {
```

**Comment by ming436534** [comment]
@StillFantastic It works! Thank you very much!

**Comment by Anandhu5** [comment]
I have the same issue while signing personal message. Not returning control to promise. Observed this more in IOS, android app has lesser compared to IOS.

````
import { useWalletConnect } from '@walletconnect/react-native-dapp';

  const connector = useWalletConnect();
  if(connector.connected){
       connector
      .signPersonalMessage([textMessage, connector.accounts[0]])
      .then(async data => {
        console.log('Success ---', data);
      })
      .catch(err => {
        console.log('Error ---', err);
      });
}
````

I have used MetaMask and trust wallet. MetaMask has connection issue . Its showing return to the browser toast on MetaMask app but the connector.connected is always false.

**Comment by mightymatth** [comment]
Is there anyone here to address this issue?

**Comment by Harasz** [comment]
I had the same problem. The problem is described in this issue https://github.com/WalletConnect/walletconnect-utils/issues/3.
I patched it using `patch-package`. 
@pedrouid Could you take a look on that?

**Comment by platocrat** [comment]
@pedrouid any updates on this issue?

**Comment by jack75015** [comment]
It should be a prior issue
WalletConnect is a more and more use protocol and simple action like sign a message looks like an adventure

**Comment by Gaspachow** [comment]
> Here's another workaround (if you're using web3Modal)
> 
> ```
> // configure web3Modal 
> const web3 = await web3Modal.connect();
> const provider = new providers.Web3Provider(web3);
> const signer = provider.getSigner()
> const address = await signer.getAddress();
> 
> let signedMessage;
> if (web3.wc) {
>     signedMessage = await provider.send(
>         'personal_sign',
>         [ ethers.utils.hexlify(ethers.utils.toUtf8Bytes(rawMessage)), address.toLowerCase() ]
>     );
> }
> else { 
>     signedMessage = await signer.signMessage(rawMessage)
> }
> ```

Thank you so much @wslyvh , adapted this version for web3-react and the result is one function which works with MetaMask, WalletConnect and Coinbase Wallet (haven't tested more).

Here is the `web3-react` version:

```js
const { account, library } = useWeb3React();
let signedMessage;
try {
      signedMessage = await library.send(
        'personal_sign', 
        [ ethers.utils.hexlify(ethers.utils.toUtf8Bytes(rawMessage)), account?.toLowerCase() ]);
} catch (error) {
      window.alert(`Failure!${error && error.message ? `\n\n${error.message}` : ''}`);
    }
```

**Comment by steven-tey** [comment]
@Gaspachow thanks a lot – that worked for me! :)

**Comment by malaDev** [comment]
seems this issue affecting all transaction that needs to be signed, not only peronal_sign method. i tried with send_transaction and facing to same issue actually. any thoughts on root cause or any workaround?

**Comment by Harasz** [comment]
@malaDev In our project we fixed it using those [patches](https://github.com/energywebfoundation/iam-client-lib/tree/develop/patches) and apply them using [patch-package](https://www.npmjs.com/package/patch-package).

**Comment by irzhywau** [comment]
thank you @Harasz, you saved my day!
I think the missing tweak was the one for `@walletconnect/jsonrpc-provider`

**Comment by Harasz** [comment]
@iserifith why did you close this issue? I think error still persist.

**Comment by jack75015** [comment]
Yes please reoppen the issue and try to fix it :)

**Comment by aminpsycho** [comment]
989213313165

**Comment by xiaoshengaimm** [comment]
we can receive sign confirm message sometimes, but sometimes can not.
Any one help on this issue?

**Comment by StillFantastic** [comment]
@xiaoshengaimm As far as I know it's an issue on metamask end, the only way you can try for now is to restart the app.
