### ISSUE TITLE
QRcode Modal stopped appearing

### ISSUE THREAD

**Issue by dykthemonkey** [WalletConnect/walletconnect-monorepo#463]
Hello, I'm trying to connect my mobile wallet to a smart contract deployed to the ropsten network. I'm using create-react-app just to test things out. I'm fairly new to frontend.

It seemed to work as intended at first; the qrcode modal opened up just fine, and I was able to connect the browser dapp with my mobile phone. Then, after a reload the modal stopped appearing altogether.

This is essentially how I implemented everything:

```
import './App.css';
import React, { Component } from 'react';

import WalletConnectProvider from "@walletconnect/web3-provider";
import { providers } from "ethers";
import { ethers } from "ethers";

class App extends Component {
  async componentDidMount() {
    const provider = new WalletConnectProvider({
      rpc: {
        3: //custom ropsten rpc,
        // ...
      },
    });
    await provider.enable();  

    //  Wrap with Web3Provider from ethers.js
    const web3Provider = new providers.Web3Provider(provider);
    const signer = web3Provider.getSigner();
  }

  render() {
    return (
      <div className="App">
        <header className="App-header">
          <p>
            //Stuff here
          </p>
        </header>
      </div>
    );
  };
}

export default App;
```

**Comment by StillFantastic** [comment]
For me, I have to close previous connection for QR code to show up again.

**Comment by dykthemonkey** [comment]
@StillFantastic Thx. That worked.

**Comment by Nitish157** [comment]
I am also trying to use my smart contract function but I am getting an error.
Due to this QR Model is not triggering.
Could you please help it is important and urgent to be solved.
I am using "@walletconnect/web3-provider": "^1.6.6",

[Error: document is not defined in Window]
This error occurs when I try to use

await provider.enable()
