### ISSUE TITLE
How To Use Web3Modal With Matic PoS Client

### ISSUE THREAD

**Issue by cryptoganges** [WalletConnect/walletconnect-monorepo#469]
I am trying to use Matic Proof of Stake SDK, which requires two simultaneous providers. One for ETH mainnet and one for Matic network.  How can I use web3modal with walletconnect or metamask providers and get back two unlocked providers capable of signing transaction on both networks?

**Comment by finessevanes** [comment]
@cryptoganges is this still an issue?
