### ISSUE TITLE
package ethereumjs-abi deprecated 

### ISSUE THREAD

**Issue by jeromevvb** [WalletConnect/walletconnect-monorepo#472]
Hello,

Thanks for this amazing library!
I have seen https://www.npmjs.com/package/ethereumjs-abi is deprecated.
Are you guys considering using a different ABI encoder in the future?

Thanks

**Comment by Migaroez** [comment]
I am even getting an npm error when trying to install

```
npm install @walletconnect/web3-provider
npm WARN deprecated @walletconnect/mobile-registry@1.4.0: Deprecated in favor of dynamic registry available from: https://github.com/walletconnect/walletconnect-registry
npm WARN deprecated safe-event-emitter@1.0.1: Renamed to @metamask/safe-event-emitter
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/ethereumjs/ethereumjs-abi.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

**Comment by jeromevvb** [comment]
@Migaroez  You need to install git

**Comment by Migaroez** [comment]
@jeromevvb Could you elaborate how to do this on windows?
I use a git client(fork) that uses git for windows underneath, but that doesn't seem to be sufficient?

**Comment by scryptoking** [comment]
Having the same issue

**Comment by edilsalvador** [comment]
Having the same issue as well

**Comment by SpokieKid** [comment]
Having the same issue x3

**Comment by nikkwong** [comment]
+1

**Comment by finessevanes** [comment]
@jeromevvb @scryptoking @edilsalvador @SpokieKid @nikkwong are you still having this issue?
