### ISSUE TITLE
Connecting to matic network ?

### ISSUE THREAD

**Issue by lucas-goldner** [WalletConnect/walletconnect-monorepo#473]
Hey I am trying to connect to the matic newtwork using the provider, but the web3 object is not printing.
I followed this config of matic: https://docs.matic.network/docs/develop/metamask/config-matic/#:~:text=To%20add%20Matic's%20Mainnet%2C%20click,Network%20field%2C%20click%20on%20Save.

Also is there a way of already specifing the account like with a private key or something ?
```
  const provider = new WalletConnectProvider({
    rpc: {
      137: "https://rpc-mainnet.maticvigil.com/",
    },
    qrcode: false,
  });
  await provider.enable();
  const web3 = new Web3(provider);
  
    console.log(web3);
  ```

**Comment by finessevanes** [comment]
@lucas-goldner are you still have this issue?
