### ISSUE TITLE
Keep getting "Deeplink is not supported" notification [React-native] [IOS]

### ISSUE THREAD

**Issue by GarfDev** [WalletConnect/walletconnect-monorepo#474]
I'm generating a dapp from the `create-react-native-dapp` boilerplate and want to sign a transaction (with metamask) before sending it with web3. But when redirect to metamask, there no sign popup appears but a modal with content `Deeplink is not supported`.

![Behaviour](https://i.imgur.com/uQnOvbw.png)

```typescript
    const contractData = contract.methods
      // .name()
      .claimNewWatch(33, "Rolex Datejust 116189PAVEL", "116189PAVEL")
      .encodeABI();

    const response = await connector
      .signTransaction({
        from: connector.accounts[0],
        to: Luxurify.contract_address,
        nonce: web3.utils.toHex(nonce),
        value: "0x00",
        data: contractData,
      })
      .catch((err) => {
        setSmth(err);
      });

```

**Comment by romannick** [comment]
I am also experiencing the same issue. Anyone got it sorted?

**Comment by finessevanes** [comment]
@GarfDev @romannick are you still having this issue?

**Comment by RustyReact** [comment]
Same Issue
