### ISSUE TITLE
ERROR:Quick Start For Dapps using React-Native  Access failure

### ISSUE THREAD

**Issue by alitong** [WalletConnect/walletconnect-monorepo#475]
error: SyntaxError:  Unexpected token, expected "," (10:29)

   8 |             redirectUrl={Platform.OS === 'web' ? window.location.origin : 'yourappscheme://'}
   9 |             storageOptions= {{
> 10 |                 asyncStorage AsyncStorage,
     |                              ^
  11 |             }}>
  12 |             <>{/* awesome app here */}</>
  13 |         </WalletConnectProvider>

**Comment by daihovey** [comment]
It's a typo, should be `asyncStorage: AsyncStorage`.
