### ISSUE TITLE
truffle-provider doesn't work

### ISSUE THREAD

**Issue by drortirosh** [WalletConnect/walletconnect-monorepo#479]
tried to use the truflfe-provider from command-line.
it does prompt for QR code and I can connect my metamask mobile - but nothing else happen.
neither "truffle migrate" doesn't install anything, and "truffle console" doesn't open a console prompt.

**Comment by snollygolly** [comment]
+1 Tried to get truffle-provider to work with no luck at all.

**Comment by korkey128k** [comment]
+1 Bump. This is still an issue

**Comment by finessevanes** [comment]
@drortirosh @snollygolly @Korkey128k is this still an issue?
