### ISSUE TITLE
We need the ability to close the socket connection without killing the session

### ISSUE THREAD

**Issue by samhv** [WalletConnect/walletconnect-monorepo#481]
What do we need?
We need the ability to close the socket connection without killing the session.

Why do we need it?
If a user has two accounts in my wallet app, account A and account B. When the user logs out from account A and then log in with account B, we have to close socket connections from account A without killing the session (no killSession), because if the user logs in again with account A, we want to be able to connect to their last walletconnect sessions.

How we solve it?
Let's create a new method transportClose that closes the transport but doesn't kill the session. We'll call transportClose when a user logs out from our wallet app.

**Comment by samhv** [comment]
this PR implements a solution for it
#480

**Comment by angrywasp** [comment]
This is already possible and i do it in a mobile wallet i am developing. In normal operation you send a disconnect message which is basically `wc_sessionUpdate` with approved being false and close the websocket connection and it terminates the session. You can close the websocket directly without sending the `wc_sessionUpdate` message and the session will be kept alive to reconnect later.

You then reconnect by connecting the websocket to the bridge url and submitting a subscription to the wallet topic and you will receive any pending messages and be reconnected
