### ISSUE TITLE
Module not found: @walletconnect/client 

### ISSUE THREAD

**Issue by iafhurtado** [WalletConnect/walletconnect-monorepo#482]
i am trying to run the scaffold-eth but fail to compile due to an anbiguous and unsound call to the wallet connect tslib.

C:/Users/jaibo/scaffold-eth/.yarn/cache/@walletconnect-client-npm-1.3.1-6d57d78cd3-3e4d93b9eb.zip/node_modules/@walletconnect/client/dist/cjs/index.js Module not found: @walletconnect/client tried to access tslib, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

This makes my yarn start to fail at compiling, any ideas on how I can fix this?
Thanks in advance

**Comment by pedrouid** [comment]
your developer environment should have detected that tslib is required and install it automatically

given that didn't happen you should install it yourself as a dependency to your project

**Comment by nissoh** [comment]
Hello @pedrouid, this is a yarn V2 PnP module resolution issue, i think `tslib` is somehow incompatible

`@walletconnect/relay-server` uses `tslib` as package dependency but i don't see any reference to it within the code.
Perhaps some dependancies cleaning is needed, it could resolve this issue and make yarn 2 viable

Edit: i tried upgrading into `2.0.0-beta.0` all good 👍

**Comment by finessevanes** [comment]
@iafhurtado @nissoh is this still an issue?

**Comment by iafhurtado** [comment]
No longer an issue @finessevanes , thanks for following up and all the best
