### ISSUE TITLE
Could not open URL

### ISSUE THREAD

**Issue by Amazing1974** [WalletConnect/walletconnect-monorepo#486]
I installed the @walletconnect/react-native-dapp package ^1.4.1

But getting below error on android when I click on connect button.
![image](https://user-images.githubusercontent.com/51259135/115905171-a0b40c00-a45d-11eb-8c6c-b82054f68ed9.png)

I also share my code.
![image](https://user-images.githubusercontent.com/51259135/115905498-161fdc80-a45e-11eb-8d57-5ad5d5fcc75a.png)

This issue is driving me crazy
Please help me
Thanks

**Comment by cawfree** [comment]
Hey, apologies for the delay. 🙏

It seems like there’s no wallet installed that’s registered to listen a
WalletConnect URI; do you have any wallets installed on the test device?

**Comment by Amazing1974** [comment]
@cawfree 
Thanks for your quick reply.
Actually I am new with this library so can you let me know how to register wallet to listen a WalletConnect URI?

**Comment by cawfree** [comment]
@Amazing1974 No problem 😊

WalletConnect helps you connect your application to other wallets, but it's not a wallet itself. This means that a WalletConnect compatible application such as [Rainbow](https://rainbow.me) needs to be installed on the device. When you attempt to initialize the connector, the library will ask to open any wallets that are installed and compatible.

You can find the list of compatible wallets [here](https://walletconnect.org/wallets).

**Comment by saber-yy** [comment]
Hello, I also encountered this problem, but there are som wallet will have this prompt, such as imToken, TokenPocket .  and  i did installed this wallet(imToken,TokenPockt)，what is your solution to resolve this problem.
