### ISSUE TITLE
Uncaught TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by asoltani927** [WalletConnect/walletconnect-monorepo#499]
Hi. What's the problem? I can't use walletconnect/web3-provider!
```
import Vue from "vue";
import Web3 from "web3";
import WalletConnect from "@walletconnect/client";
import QRCodeModal from "@walletconnect/qrcode-modal"
import WalletConnectProvider from "@walletconnect/web3-provider";

const connector = new WalletConnect({
            bridge: "https://bridge.walletconnect.org", // Required
            qrcodeModal: QRCodeModal,
        });

        //  Create WalletConnect Provider
        const provider = new WalletConnectProvider({
            infuraId: "27e484dcd9e3efcfd25a83a78777cdf1",
        });

        await provider.enable();

```

Error is:
> 
> Uncaught TypeError: Class extends value undefined is not a constructor or null
>     at module.exports (app.js:142944)
>     at module.exports (app.js:142908)
>     at Object../node_modules/keccak/js.js (app.js:142893)
>     at __webpack_require__ (app.js:304757)
>     at Object../node_modules/ethereum-cryptography/keccak.js (app.js:117905)
>     at __webpack_require__ (app.js:304757)
>     at Object../node_modules/ethereumjs-util/dist/hash.js (app.js:123613)
>     at __webpack_require__ (app.js:304757)
>     at Object../node_modules/ethereumjs-util/dist/account.js (app.js:123222)
>     at __webpack_require__ (app.js:304757)

**Comment by Jonas121** [comment]
Hi,
Same problem with me:
keccak.js:3 Uncaught TypeError: Class extends value undefined is not a constructor or null
    at module.exports (keccak.js:3)
    at module.exports (index.js:5)
    at eval (js.js:1)
    at Object../node_modules/keccak/js.js (bundle.js:2)
    at __webpack_require__ (bundle.js:2)
    at eval (keccak.js:4)
    at Object../node_modules/ethereum-cryptography/keccak.js (bundle.js:2)
    at __webpack_require__ (bundle.js:2)
    at eval (index.js:5)
    at Object../node_modules/ethereumjs-util/dist/index.js (bundle.js:2)

**Comment by Jonas121** [comment]
Problem was with webpack config. Now provider v. 1.4.1. is working. Solved installing missing node modules and adding to webpack config file:
  plugins: [
    new webpack.ProvidePlugin({
      Buffer: ['buffer', 'Buffer'],
    })    
    ],

  resolve: {
    fallback :{
      "os": require.resolve("os-browserify/browser"),
      "https": require.resolve("https-browserify"),
      "http": require.resolve("stream-http"),
      "stream": require.resolve("stream-browserify"),
      "assert": require.resolve("assert/"),
      "crypto": require.resolve("crypto-browserify"),
    }
  },

Good luck

**Comment by liaoqifeng** [comment]
how to solve this question if use Vite framework?

> Problem was with webpack config. Now provider v. 1.4.1. is working. Solved installing missing node modules and adding to webpack config file:
> plugins: [
> new webpack.ProvidePlugin({
> Buffer: ['buffer', 'Buffer'],
> })
> ],
> 
> resolve: {
> fallback :{
> "os": require.resolve("os-browserify/browser"),
> "https": require.resolve("https-browserify"),
> "http": require.resolve("stream-http"),
> "stream": require.resolve("stream-browserify"),
> "assert": require.resolve("assert/"),
> "crypto": require.resolve("crypto-browserify"),
> }
> },
> 
> Good luck

how to solve this question if use Vite framework??

**Comment by mattcasey** [comment]
In case someone else using next.js ends up here, I fixed this error by just deleting node_modules, the package-lock.json, and re-installing.
