### ISSUE TITLE
Does not work with trust wallet on Matic bridge, dumps error to wallet

### ISSUE THREAD

**Issue by EncryptShawn** [WalletConnect/walletconnect-monorepo#506]
I would say this could be a trust wallet issue but I have had similar issues across multiple wallets.

When wallet connect theirs to auth the transaction on trust, trust throws "java.lang.illegalStateException: Expected BEGIN_OBJECT but was STRING at path $[1]

I ended up using walletlink with coinbase wallet and was able to use the bridge with that.

**Comment by finessevanes** [comment]
@EncryptShawn is this still an issue?
