### ISSUE TITLE
Wallectconnect having issues with multi-transaction auth, black-holing additional auth req's

### ISSUE THREAD

**Issue by EncryptShawn** [WalletConnect/walletconnect-monorepo#507]
I had a similar issue on the matic bridge as well. If you try to do a transaction on the Ocean Protocol marketplace using wallet connect, the first transaction is authorized but it never asks for future transaction auths and the whole process takes around 6 auths to complete. I tried multiple wallets, I tried on mainnet which your app blackholed my transactions and lost about $100 in ETH and I tried tirelessly on on Rinkeby testnet and every time, further transaction requests are blackholed and I am never prompted so the process is help up indefinitely.

You can easily recreate this issue on Rinkeby >https://market.oceanprotocol.com/publish

I tried 2 windows machines, one ubuntu machine, 3 browsers (firefox, chrome, opera), 3 wallets. All the same results when using Wallet Connect

As soon as I changed from my mobile metamask and used my local browser based metamask and removed wallet connect from the equation, everything worked perfectly. 

It appears that Wallet connect has issues with multi-transaction auth

**Comment by finessevanes** [comment]
@EncryptShawn is this still an issue?
