### ISSUE TITLE
Consider reducing sub-dependencies for @walletconnect/iso-crypto

### ISSUE THREAD

**Issue by vilsbole** [WalletConnect/walletconnect-monorepo#508]
When updating to @walletconnect/client `1.4.1` I noticed the introduction of new dependencies notably "@pedrouid/iso-crypto@^1.0.0, "@pedrouid/iso-random@^1.1.0".

@pedrouid would you consider placing these libraries under the organisation's namespace?
Even though we (the MyCrypto team) have entire confidence in you personally, we feel that your organisation could be more resilient to an eventual ATO and believe that having the repos under the WalletConnect namespace could help mitigate attacks.

**Comment by pedrouid** [comment]
Hi @vilsbole, thanks for sharing this. Given that you are not the first organization to mention this, I will definitely put it my roadmap for v1.5.0 and v2.0.0 releases next month.

**Comment by pedrouid** [comment]
I've published the first iteration of these utilities under a single monorepo:

https://github.com/WalletConnect/walletconnect-utils

I will include them as part of the v1.5.0 and v2.0.0 release candidates
