### ISSUE TITLE
User rejects session but no event or error was fired

### ISSUE THREAD

**Issue by fritzschoff** [WalletConnect/walletconnect-monorepo#512]
Hey, I'm trying to support the imToken provider over wallet connect. Everything works fine if the user connects or closes the modal. But if the user rejects the session in his imToken app, the modal closes but no error or event was fired. This makes it hard to react to such events. I tried to wrap the `enable()` in a try catch block but nothing happens... Is there an event for such cases?

**Comment by fritzschoff** [comment]
Also `wc_sessionRequest` doesn't seems to be fired?

**Comment by Pasha8914** [comment]
try
```
 provider.wc.on('disconnect', (error, payload) => {
    console.warn('Provider disconnect payload', { payload, error })
  })
