### ISSUE TITLE
chainChanged event not detected

### ISSUE THREAD

**Issue by RiccardoBiosas** [WalletConnect/walletconnect-monorepo#513]
When using metamask through walletconnect, if I change the network on metamask after successfully connecting to the dapp the client does not appear to detect the ```chainChanged``` event.
```
provider.on("chainChanged", (chainId: number) => {
  console.log(chainId);
})
```

**Comment by pedrouid** [comment]
I've just written tests for these and was not able to reproduce this. Also tested manually and it worked. 

<img width="692" alt="Screen Shot 2021-06-30 at 19 35 38" src="https://user-images.githubusercontent.com/10136079/124007739-ef40d200-d9db-11eb-905a-e013c45f30cb.png">


The wallet you are using must not be sending the updates through WalletConnect
