### ISSUE TITLE
Cors

### ISSUE THREAD

**Issue by djmbritt** [WalletConnect/walletconnect-monorepo#514]
So I'm getting the following cors error:

![image](https://user-images.githubusercontent.com/3985738/119139685-9593d200-ba43-11eb-9a5f-bd7a8d8b5e35.png)

With the following configuration:
```
const walletProvider = new WalletConnectProvider({
  chainId: 56, // For some reason chainID needs to be 1.
  rpc: {
    56: process.env.NUXT_ENV_BSC_RPC
  },
  bridge: "https://bridge.walletconnect.org", // redundant?
  qrcode: true, // redundant?
  qrcodeModal: QRCodeModal, //redundant?
  qrcodeModalOptions: {
    mobileLinks: ["metamask", "trust", "rainbow", "argent"]
  }
})
```

Any ideas what might be causing the error?

**Comment by pedrouid** [comment]
This is unrelated to WalletConnect. Please ask the Binance Smart Chain team
