### ISSUE TITLE
add Taiko  Network

### ISSUE THREAD

**Issue by swarna1101** [WalletConnect/walletconnect-monorepo#5198]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
ethereum-rpc
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   ethereum
3. **namespaces**:
   eip:155
4. **chains**:
   Taiko Mainnet: eip:155: 167000
   Taiko Hekla Testnet: eip:155: 167009
  
5. **RPC endpoints**:
Taiko Mainnet: https://rpc.mainnet.taiko.xyz
                        https://rpc.taiko.xyz
Taiko Hekla Testnet: https://rpc.hekla.taiko.xyz
                        
   
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**: 60
   

**Additional context**
Add any other context here.

---

**Please note:**

**Registering a chain with the Explorer does not impact or improve the ability for wallets and dapps to support your chain.** It is simply a way for users to discover wallets and dapps that support your chain by:

- Browsing the [Chains List](https://docs.walletconnect.com/advanced/multichain/chain-list)
- Filtering results programmatically via the [Explorer API](https://docs.walletconnect.com/cloud/explorer)

**It is still up to wallets and dapps to provide concrete support for your chain once it is listed as part of the Explorer.**

- [x] I have read and understood the above clarification

**Comment by swarna1101** [comment]
@Cali93 can you pls review and add this

**Comment by swarna1101** [comment]
@Cali93 any update on this, can pls get this done, so that we can list our bridge and other dapps in your explorer

**Comment by Cali93** [comment]
@swarna1101 Yes we will add it this week. Sorry for the delay.

**Comment by Cali93** [comment]
Your chain has been added. Thanks for your patience 🙏
