### ISSUE TITLE
After the wallet is successfully linked, the connected value obtained in the WalletConnectProvider is false

### ISSUE THREAD

**Issue by Yuaimin** [WalletConnect/walletconnect-monorepo#520]
After successfully linking the wallet through the WalletConnect constructor, calling the enable method with an instance of WalletConnectProvider will pop up the qrcode-modal again

**Comment by finessevanes** [comment]
@Yuaimin is this still an issue?

**Comment by Yuaimin** [comment]
Oh, My God! Our project has stopped maintenance.
