### ISSUE TITLE
web3-provider doesn't work with custom rpc

### ISSUE THREAD

**Issue by Shirikatsu** [WalletConnect/walletconnect-monorepo#522]
`"@walletconnect/web3-provider": "^1.4.1"`

Following the docs [here](https://docs.walletconnect.org/quick-start/dapps/web3-provider#setup) I attempted the following:

```typescript
import WalletConnectProvider from "@walletconnect/web3-provider";

...

const provider = new WalletConnectProvider({
    rpc: {  
        56: "https://bsc-dataseed.binance.org",
    },
});

await provider.enable();
```

The QR modal pops up and I scan using TrustWallet and I get errors:

```javascript
Unhandled Promise rejection: Callback was already called. ; Zone: <root> ; Task: Promise.then ; Value: Error: Callback was already called.
    at onlyOnce.js:9
    at createAsyncMiddleware.js:54
    at ZoneDelegate.invoke (zone-evergreen.js:372)
    at Zone.run (zone-evergreen.js:134)
    at zone-evergreen.js:1276
    at ZoneDelegate.invokeTask (zone-evergreen.js:406)
    at Zone.runTask (zone-evergreen.js:178)
    at drainMicroTaskQueue (zone-evergreen.js:582) Error: Callback was already called.
    at http://localhost:4200/vendor.js:165943:32
    at http://localhost:4200/vendor.js:97:11
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.js:1146:26)
    at Zone.run (http://localhost:4200/polyfills.js:908:43)
    at http://localhost:4200/polyfills.js:2050:36
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:1180:31)
    at Zone.runTask (http://localhost:4200/polyfills.js:952:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.js:1356:35)
```

and clear querying against infura mainnet even though a node url was provided:

<img width="615" alt="Screenshot 2021-06-03 at 17 43 06" src="https://user-images.githubusercontent.com/4716816/120681331-29798b00-c493-11eb-8cd3-73e45a349513.png">

What am I doing wrong?

**Comment by Shirikatsu** [comment]
Trying to interact with the chain by using the provider:

```typescript
const web3Provider = new ethers.providers.Web3Provider(provider);
const contract = new Contract(address, abi, web3Provider.getSigner());

const result = await contract.method();
```

returns error:

```javascript
core.js:6142 ERROR Error: Uncaught (in promise): Error: bad result from backend (method="call", params={"transaction":{"from":"0xdE04c469BcE5357B44Cda219F1Bafbb9494461fb","to":"0x00d540dec7ea96BE8c4208e97274380597AED4a8","data":"0x70a08231000000000000000000000000de04c469bce5357b44cda219f1bafbb9494461fb","accessList":null},"blockTag":"latest"}, result=undefined, error={}, code=SERVER_ERROR, version=providers/5.1.2)
Error: bad result from backend (method="call", params={"transaction":{"from":"0xdE04c469BcE5357B44Cda219F1Bafbb9494461fb","to":"0x00d540dec7ea96BE8c4208e97274380597AED4a8","data":"0x70a08231000000000000000000000000de04c469bce5357b44cda219f1bafbb9494461fb","accessList":null},"blockTag":"latest"}, result=undefined, error={}, code=SERVER_ERROR, version=providers/5.1.2)
    at Logger.makeError (index.js:166)
    at Logger.throwError (index.js:175)
    at Web3Provider.<anonymous> (base-provider.js:1017)
    at Generator.next (<anonymous>)
    at fulfilled (base-provider.js:5)
    at ZoneDelegate.invoke (zone-evergreen.js:372)
    at Object.onInvoke (core.js:28513)
    at ZoneDelegate.invoke (zone-evergreen.js:371)
    at Zone.run (zone-evergreen.js:134)
    at zone-evergreen.js:1276
    at resolvePromise (zone-evergreen.js:1213)
    at zone-evergreen.js:1120
    at rejected (tslib.es6.js:74)
    at ZoneDelegate.invoke (zone-evergreen.js:372)
    at Object.onInvoke (core.js:28513)
    at ZoneDelegate.invoke (zone-evergreen.js:371)
    at Zone.run (zone-evergreen.js:134)
    at zone-evergreen.js:1276
    at ZoneDelegate.invokeTask (zone-evergreen.js:406)
    at Object.onInvokeTask (core.js:28500)
```

Error is a `SERVER_ERROR` from what I can tell to be it attempting to call RPC API of an invalid node url because it's attempting to use Infura.

How does this figure out when not to use network `1` and use a different chainId for the network?

**Comment by ochikov** [comment]
> `"@walletconnect/web3-provider": "^1.4.1"`
> 
> Following the docs [here](https://docs.walletconnect.org/quick-start/dapps/web3-provider#setup) I attempted the following:
> 
> ```ts
> import WalletConnectProvider from "@walletconnect/web3-provider";
> 
> ...
> 
> const provider = new WalletConnectProvider({
>     rpc: {  
>         56: "https://bsc-dataseed.binance.org",
>     },
> });
> 
> await provider.enable();
> ```
> 
> The QR modal pops up and I scan using TrustWallet and I get errors:
> 
> ```js
> Unhandled Promise rejection: Callback was already called. ; Zone: <root> ; Task: Promise.then ; Value: Error: Callback was already called.
>     at onlyOnce.js:9
>     at createAsyncMiddleware.js:54
>     at ZoneDelegate.invoke (zone-evergreen.js:372)
>     at Zone.run (zone-evergreen.js:134)
>     at zone-evergreen.js:1276
>     at ZoneDelegate.invokeTask (zone-evergreen.js:406)
>     at Zone.runTask (zone-evergreen.js:178)
>     at drainMicroTaskQueue (zone-evergreen.js:582) Error: Callback was already called.
>     at http://localhost:4200/vendor.js:165943:32
>     at http://localhost:4200/vendor.js:97:11
>     at ZoneDelegate.invoke (http://localhost:4200/polyfills.js:1146:26)
>     at Zone.run (http://localhost:4200/polyfills.js:908:43)
>     at http://localhost:4200/polyfills.js:2050:36
>     at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:1180:31)
>     at Zone.runTask (http://localhost:4200/polyfills.js:952:47)
>     at drainMicroTaskQueue (http://localhost:4200/polyfills.js:1356:35)
> ```
> 
> and clear querying against infura mainnet even though a node url was provided:
> 
> <img alt="Screenshot 2021-06-03 at 17 43 06" width="615" src="https://user-images.githubusercontent.com/4716816/120681331-29798b00-c493-11eb-8cd3-73e45a349513.png">
> 
> What am I doing wrong?

I am able to run it as pass also a chainId param.

**Comment by Shirikatsu** [comment]
Thanks. This works.

Docs need updating. Had no idea this param existed.

**Comment by starlabs007** [comment]
@Shirikatsu Can you explain how you fixed it? I'm getting the same error.
I tried:
```
{
    rpc: {
        56: "https://bsc-dataseed.binance.org",
    },
    chainId: 56,
},
```
But that didn't work - it's still trying to connect to infura.

**Comment by happyeric77** [comment]
@Shirikatsu @starlabs007 @ochikov 
I am also facing exactly the same issue. I also tried what @starlabs007 has done. 
But still no luck.
Could you please let me know to do deal with it?

**Comment by happyeric77** [comment]
@starlabs007 
I have managed to solve it out. We need to use multi-coin wallet. My web3 setting is below FYI:
```
try {
    console.log("Log in with connect wallet")
    const provider = await new WalletConnectProvider({
        rpc: {
            56: "https://bsc-dataseed1.binance.org",
        },
        chainId: 56,
    });
    // provider.networkId = 56;
    await provider.enable();
    const web3 = await new Web3(provider);
    console.log(web3)
    resolve(web3)
} catch {
    console.log("Install metamask or use wallet connect")
}
```

**Comment by ochikov** [comment]
I am using it like this: 

```
this.web3Modal = new Web3Modal({
      cacheProvider: true,
      providerOptions: this.getProviderOptions(),
    });
```

```
providerOptions = {
        walletconnect: {
          package: WalletConnectProvider,
          options: {
            rpc: {
              56: 'https://bsc-dataseed.binance.org/',
            },
            network: 'binance',
            chainId: 56,
            infuraId: process.env.REACT_APP_INFURA_ID,
          },
        },
      };
```

**Comment by starlabs007** [comment]
@happyeric77 @ochikov Thanks guys, I got it to work. For me the key missing entry was `network: 'binance'`.
Once I added that, I was able to connect to the wallet and the network. Cheers!

**Comment by ochikov** [comment]
> @happyeric77 @ochikov Thanks guys, I got it to work. For me the key missing entry was `network: 'binance'`.
> Once I added that, I was able to connect to the wallet and the network. Cheers!

Perfect.

**Comment by happyeric77** [comment]
> ocess.env.REACT_APP_INFURA_ID,

@ochikov I see that you also put infura_ID inside, does it have any specific role in this situation? or it is not related to the issue here, just an option?
Furthermore, may I know where is the chain.ts located in its source, I cannot find it (see below). The reason why I want to check is that my code is working without network entry so that I would like to check if there is any potential risk in my code.
<img width="268" alt="Screen Shot 2021-06-14 at 11 08 54" src="https://user-images.githubusercontent.com/52155607/121830828-eaec9780-cd00-11eb-9772-b1550bc73a23.png">
What I can see about "network" in source code (web3-provider/dist/cjs/index) is like below:
<img width="1016" alt="Screen Shot 2021-06-14 at 11 19 22" src="https://user-images.githubusercontent.com/52155607/121831486-86323c80-cd02-11eb-8377-5fcbf472fd99.png">

**Comment by ochikov** [comment]
@happyeric77 Sorry for the chain.ts. I was confused with another library that is using this one and just confused myself. I also update my previous comment. About the INFURA ID, they marked it as required in the documentation and I gues they are using it somehow... 
https://docs.walletconnect.org/quick-start/dapps/web3-provider#required

**Comment by starlabs007** [comment]
@ochikov @happyeric77 The Infura ID isn't required if you specify RPC options. It's one or the other but not necessarily both, although in this case it looks like it doesn't flag an error if you specify both.

If you read the first line in the docs that @ochikov linked, it says this (my emphasis):
> In order to resolve non-signing requests you need to provide **_one_** of the following:
Infura ID
...
RPC URL Mapping
...

My options doesn't have an infura id entry and it still works:
```js
      providerOptions: {
        walletconnect: {
          package: WalletConnectProvider,
          options: {
            rpc: {
              56: "https://bsc-dataseed.binance.org",
            },
            network: 'binance'
          },
        },
```

**Comment by ochikov** [comment]
> @ochikov @happyeric77 The Infura ID isn't required if you specify RPC options. It's one or the other but not necessarily both, although in this case it looks like it doesn't flag an error if you specify both.
> 
> If you read the first line in the docs that @ochikov linked, it says this (my emphasis):
> 
> > In order to resolve non-signing requests you need to provide **_one_** of the following:
> > Infura ID
> > ...
> > RPC URL Mapping
> > ...
> 
> My options doesn't have an infura id entry and it still works:
> 
> ```js
>       providerOptions: {
>         walletconnect: {
>           package: WalletConnectProvider,
>           options: {
>             rpc: {
>               56: "https://bsc-dataseed.binance.org",
>             },
>             network: 'binance'
>           },
>         },
> ```

Yes, tried now without Infura ID, but with RPC options and it worked.

**Comment by happyeric77** [comment]
@starlabs007 @ochikov 
Thanks for sharing. 
I am still so wondering why my application is working even though I do not set "network" as "binanace".
Have you guys tried on your code not to set network option? Would it still be working?

**Comment by ochikov** [comment]
> @starlabs007 @ochikov
> Thanks for sharing.
> I am still so wondering why my application is working even though I do not set "network" as "binanace".
> Have you guys tried on your code not to set network option? Would it still be working?

Maybe because I am using walletConnect but with web3Modal on top, so the walletConnect is implemented in web3Modal and web3Modal is parsing params and etc to the walletConnect class. That's why I need it. Maybe it will work in your case without the "network" param.

**Comment by happyeric77** [comment]
@ochikov 
Thanks! It is very informative.

**Comment by happyeric77** [comment]
Hi all, I think I still have an issue with it.
I follow the setting and found out trust wallet is not correctly connected.
does anybody come across the same issue as I do?
My code is below:
```
const provider = await new WalletConnectProvider({
    rpc: {
        56: "https://bsc-dataseed1.binance.org",
    },
    chainId: 56,
    network: "binance",
    qrcode: true,
    qrcodeModalOptions: {
        mobileLinks: [
          "metamask",
          "trust",
        ]
    }
});
provider.networkId = 56;
await provider.enable();
```

**Comment by ochikov** [comment]
> finance
Can you change the network to "binance"

**Comment by happyeric77** [comment]
I realized it yesterday and changed it back to  "finance". But it does not work with Trust wallet. (Metamask is working fine through)

**Comment by pasevin** [comment]
@happyeric77 have you figured it out?

**Comment by happyeric77** [comment]
@pasevin In my case, I think it is caused by the old version (I was using 1.4.1). It is working fine now after upgrading to 1.5.2.

**Comment by moda20** [comment]
I ma still having the same Error of trying to connect to infura, i did set the chainId to something from my RPC list. but no luck ?
is musing the 1.6.6 version of walletconnect web3 provider here is what i am doing : 

```
this.WCprovider = new WalletConnectProvider({
                rpc: {
                    56: HTTP_PROVIDER,
                    1337: HTTP_PROVIDER
                },
                chainId: 56,
                infuraId: undefined
            });
            this.WCprovider.networkId = 56;

```

i tried different combinations of those parameters and it didn't work.

**Comment by yohanelly95** [comment]
> I ma still having the same Error of trying to connect to infura, i did set the chainId to something from my RPC list. but no luck ? is musing the 1.6.6 version of walletconnect web3 provider here is what i am doing :
> 
> ```
> this.WCprovider = new WalletConnectProvider({
>                 rpc: {
>                     56: HTTP_PROVIDER,
>                     1337: HTTP_PROVIDER
>                 },
>                 chainId: 56,
>                 infuraId: undefined
>             });
>             this.WCprovider.networkId = 56;
> ```
> 
> i tried different combinations of those parameters and it didn't work.

Same here, did you figure this out? How do we add multiple chainIds?

**Comment by yohanelly95** [comment]
> Hi all, I think I still have an issue with it. I follow the setting and found out trust wallet is not correctly connected. does anybody come across the same issue as I do? My code is below:
> 
> ```
> const provider = await new WalletConnectProvider({
>     rpc: {
>         56: "https://bsc-dataseed1.binance.org",
>     },
>     chainId: 56,
>     network: "binance",
>     qrcode: true,
>     qrcodeModalOptions: {
>         mobileLinks: [
>           "metamask",
>           "trust",
>         ]
>     }
> });
> provider.networkId = 56;
> await provider.enable();
> ```

This does work for me thank you! But any idea how to support multiple chainIds ? 

I am using web3Modal, but under the hood its the same implementation. 

``` const providerOptions = {
    walletconnect: {
      package: WalletConnectProvider,
      options: {
        rpc: {
          56: 'https://bsc-dataseed.binance.org/',
          80001: "https://7m3prrcccvpjjwlhk.usemoralis.com:2053/server",
        },
        chainId: [56, 80001],
        infuraId: "d452c5f789194e2e9a1055567a2fb41",
      }
    },
  };```

**Comment by romain130492** [comment]
any news about this...?
it doesnt switch to binance network when i tried any of the solution above..

**Comment by Da-Teach** [comment]
I was running into the same issue and for me the following seemed to have fixed it. In my case it was for polygon mumbai testnet:
```Typescript
    const provider = new WalletConnectProvider({
      rpc: {
        137: 'https://polygon-rpc.com',
        1337: 'http://localhost:8545',
        80001: 'https://matic-mumbai.chainstacklabs.com',
      },
      chainId: 80001
    });
    provider.updateRpcUrl(80001); // Don't think this one did anything
    await provider.enable();
    provider.updateRpcUrl(80001); // This one forces the switch 
```

From what I seem to notice is that after 'enable' the chainId goes back to 1 regardless of the provided chainId and it starts polling infura. The updateRpcUrl (after enable) switches it back to the actual requested chain and it'll stop the infura spam.

Sometimes you still get 1 or 2 polls to Infura though.

**Comment by hankdangerfield** [comment]
I am using vanilla js with web3 model and getting the following error when trying to use Binance RPC and WalletConnect.
![image](https://user-images.githubusercontent.com/91743546/190175263-a92584a3-81df-4942-a8a5-75ca84e45c10.png)


I have set my js up as follows...any ideas why I'm getting that error?
![image](https://user-images.githubusercontent.com/91743546/190175435-286717a9-079c-48a3-9f7f-6264bff9e15b.png)
