### ISSUE TITLE
Custom RPC return wrong chainId.

### ISSUE THREAD

**Issue by ochikov** [WalletConnect/walletconnect-monorepo#523]
Trying to connect to custom RPC returns wrong chainId.
I am calling the following method:

```
const provider = new WalletConnectProvider({
      bridge,
      qrcode,
      infuraId,
      rpc,
      chainId,
      qrcodeModalOptions
    });
```

with params:

```
bridge: "https://bridge.walletconnect.org"
chainId: 43113
infuraId: "INFURA_ID"
qrcode: true
qrcodeModalOptions: undefined
rpc: {43113: "https://api.avax-test.network/ext/bc/C/rpc"}
```

and the returned chainId in the provider is 1 (Mainnet).
Any suggestions how to connect? This is not happening with other networks, just the Avalanche.

**Comment by avadex** [comment]
any news on this?


can confirm. happens on android wallet. with metamask, alphawallet, tokenpocket

**Comment by Benjythebee** [comment]
Facing this issue too,
I think it's related to #513 .

Doing
```
walletconnect = new WalletConnectProvider({
    rpc: {
      1: 'https://mainnet.infura.io/v3/[id]',
      137: 'https://rpc-mainnet.maticvigil.com/',
    },
  })

walletconnect.on('chainChanged',...)
```
Connects to mainnet and `chainChanged` will not fire on changed chain .

Also, I'm not sure if `walletconnect.updateRpcUrl({chainId:137})` is supposed to change chain, but it seem to not do anything but change the rpc_url.

**Comment by pedrouid** [comment]
Wallets always control the chainId. The RPC map only exists to route requests that are not for signing. Please prompt users to change the chain on their wallet

**Comment by Benjythebee** [comment]
Thanks, that helps, I guess only metamask and WalletLink will have that functionality then. Regardless, the chainChanged listener doesn't seem to fire on chain changed by the user, as observed by @ochikov and @avadex ...

**Comment by ochikov** [comment]
> Wallets always control the chainId. The RPC map only exists to route requests that are not for signing. Please prompt users to change the chain on their wallet

If they change it, again the chainId written in the provider is wrong and no kind of transactions can be made.

**Comment by finessevanes** [comment]
@ochikov @Benjythebee @avadex is this still an issue?
