### ISSUE TITLE
Add Morph Holesky Chain & Ethereum Holesky

### ISSUE THREAD

**Issue by RedHorse823** [WalletConnect/walletconnect-monorepo#5239]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
 Ethereum RPC
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
 Ethereum
3. **namespaces**:
eip:155
4. **chains**:
 Morph Holesky Testnet: eip:155: 2810
 Ethereum Holesky Testnet: eip:155: 17000

5. **RPC endpoints**
   Morph Holesky Testnet: 
   https://rpc-quicknode-holesky.morphl2.io/ 
   https://rpc-holesky.morphl2.io/
   Ethereum Holesky Testnet: 
   https://ethereum-holesky-rpc.publicnode.com/
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**: 60

**Additional context**
Add any other context here.

---

**Please note:**

**Registering a chain with the Explorer does not impact or improve the ability for wallets and dapps to support your chain.** It is simply a way for users to discover wallets and dapps that support your chain by:

- Browsing the [Chains List](https://docs.walletconnect.com/advanced/multichain/chain-list)
- Filtering results programmatically via the [Explorer API](https://docs.walletconnect.com/cloud/explorer)

**It is still up to wallets and dapps to provide concrete support for your chain once it is listed as part of the Explorer.**

- [x] I have read and understood the above clarification

**Comment by RedHorse823** [comment]
@Cali93 Hey ser, can you please kindly check the PR so that we can list our bridge and other dapps on your explorer

**Comment by Cali93** [comment]
Hi @RedHorse823 sorry for the delay. Your chains have been added to our explorer.
