### ISSUE TITLE
Error sending transaction only through walletconnect

### ISSUE THREAD

**Issue by rafagalan** [WalletConnect/walletconnect-monorepo#525]
Hello everyone!

I've trying to make a transfer (ERC20) but walletConnect keeps throwing this error: intrinsic gas too low. The weird thing is that the gasLimit is set to the same number as metamask (making this transaction using metamask works fine). This is the transaction data:
```
{
  "data": "0xa9059cbb00000000000000000000000044165add1ce424fa1959edcec398bbd7059ba530000000000000000000000000000000000000000000000000000000000000000a",
  "to": "0x72901a086dee291446Ce3dD0D990E92ec095E790",
  "from": "0x44165aDd1CE424Fa1959EDceC398bBD7059bA530",
  "gasPrice": {
    "_hex": "0x3b9aca00",
    "_isBigNumber": true
  },
  "nonce": 630,
  "gasLimit": {
    "_hex": "0x7f19",
    "_isBigNumber": true
  },
  "chainId": 4
}
```
Is anyone facing the same problem?

**Comment by pedrouid** [comment]
This an ethers.js error. Unrelated to WalletConnect. Please ask the ethers team about it
