### ISSUE TITLE
Qr Code is too small to read 

### ISSUE THREAD

**Issue by esongur** [WalletConnect/walletconnect-monorepo#527]
![image](https://user-images.githubusercontent.com/8542511/121509140-04cf6700-c9ef-11eb-8f87-9043d792654d.png)
hello, when I try to provide a wallet connection with walletconnect, the qr code seems too small to be read in this way. I provide the link with the infura id

**Comment by esongur** [comment]
@pedrouid do you have any idea about this?

**Comment by pedrouid** [comment]
Never experienced this. Do you have any CSS stylesheet overriding it?
