### ISSUE TITLE
While installing on Ubuntu, "make deploy" executes successfully but server refuses connections

### ISSUE THREAD

**Issue by ravisriv** [WalletConnect/walletconnect-monorepo#528]
I have been successfully running an old version of node-walletconnect-bridge as a server for allowing mobile wallet connections through WalletConnect protocol. 

Recently, node-walletconnect-bridge was merged with walletconnect-monorepo.

I tried to deploy walletconnect-monorepo after taking care of all the dependencies on Ubuntu 20.04 LTS. I executed "make deploy" and the it executed successfully. However, it did not work when I tried https://{url}/hello. I checked docker logs of nginx by executing docker logs {id}. I noticed that certbot had failed to authenticate the server and generate SSL certificates, since http://{url}/.well-known/acme-challenge/{string} refused to connect. I tried removing, re-installing multiple times and each time certbot continued to fail to authenticate the docker container instance of nginx.

I had noticed a similar issue with the old walletconnect-bridge. However, I had worked around by manually generating the SSL certificates using DNS-01 and copying the certificates into the letsencrypt directory in the docker container. That trick did not work with walletconnect-monorepo.

Would really appreciate if someone could help me identify how to resolve this issue. I want to install walletconnect-bridge server included in the walletconnect-monorepo. Thank you very much!

**Comment by ravisriv** [comment]
Looking into the docker container I noticed that there is no nginx server configured. Clearly, this is causing certbot to fail.

**Comment by sbc64** [comment]
@ravisriv 

We recently stopped using nginx and switched to [caddy server](caddyserver.com/) mostly due to the automatic ssl management that Caddy provides.

Do you think you can try again with the latest from the v2.0 branch? Some requirements before you attempt this:
- Docker version: 20.10 is needed.
- Your DNS A records should point to the server in which you are making the deploy.
- If you don't want monitoring you can run the `make deploy-no-monitoring` command.

About nginx refusing connections, basically nginx is never excuted because the cerbot part of the entry script fails, so nginx is never started within the docker container.

**Comment by ravisriv** [comment]
Thank you very much @sbc64 
Your response was truly helpful. I purged certbot and after that I reinstalled walletconnect-monorepo using "make deploy". 

Prior to this I followed the instructions to install the following packages:
-     apt install docker.io
-     apt install git
-     apt install make

Next I ran "docker swarm init"

After that I deployed walletconnect-monorepo using "make deploy" and it worked flawlessly (To anyone reading it to install, please make sure that you have at least 10gb of space). I can clearly see that caddy server is running. I can telnet to port 80 and 443 but when I try "https://server-dns-name/hello", I get a "This page isn't working" error.

I have the DNS A record (server-dns-name) pointing to the server IP address. BTW, previous deploy script used to ask if I was using Cloudflare. This one does not give that option. Instead, this script directly asks for the Cloudflare API token. Therefore, I moved my DNS to Cloudflare and setup Cloudflare to direct to my server. After that I generated a Cloudflare API token and provided that to the deploy script. I don't think this is a Cloudflare issue. 

I'll do more debugging tomorrow. Appreciate all of you doing brilliant work to make wallets easier to use.

**Comment by ravisriv** [comment]
After a successful "make deploy" as described above, I'm getting "ERR_TOO_MANY_REDIRECTS" in Chrome browser when I try to connect to the domain. On further debugging I get the same error, "Exceeded maximum number of redirects." I'm suspecting this may be the issue with http redirecting to https and https having some issues with the SSL in the Caddy server. 

On closer inspection, here is what is going on. When I enter server-dns-name URL in the URL window of the browser, the browser reaches out to the Caddy server with a https request. In less than a second, the request changes to a http request in the browser window. Next second, the request changes again to a https request and then I get the ERR_TOO_MANY_REDIRECTS error. Looks like some ping-pong going on between http and https protocols between the caddy server and the backend. (Docker images for Caddy Server don't have "bash" or "sh" executable. Therefore, I don't know how I can go inside the container to check the configuration.)

Will appreciate any help. Thanks!

**Comment by newtmex** [comment]
How can the SSL Cert be renewed?

**Comment by ravisriv** [comment]
The only way you can get it renewed is if you are using Cloudflare. I could not find a way of renewing the certificate for caddy server without Cloudflare.

**Comment by ravisriv** [comment]
Caddy server will renew the server automatically, if you are using Cloudflare.

**Comment by newtmex** [comment]
I am running my server on a subdomain, the main domain is on Cloudflare. I wonder why it did not auto renew.

**Comment by newtmex** [comment]
Fixed the issue by cleaning up and deploying again

**Comment by finessevanes** [comment]
@ravisriv do you still have this issue?
