### ISSUE TITLE
Closing QR modal genarting error in react 

### ISSUE THREAD

**Issue by avinashbuddana** [WalletConnect/walletconnect-monorepo#531]
I am using @walletconnect/web3-provider for showing wallet conect QR code code .it generates error if user clicks on close button .
![Screenshot from 2021-02-22 18-09-35](https://user-images.githubusercontent.com/13912798/108709783-2fc5a600-7539-11eb-938e-c53355dc8148.png)

my code sample is :
```await walletConnectProvider.enable();
 web3 = new Web3(walletConnectProvider);
 ```

**Comment by finessevanes** [comment]
@avinashbuddana is this still an issue?
