### ISSUE TITLE
"Copy to clipboard" not working

### ISSUE THREAD

**Issue by grachyov** [WalletConnect/walletconnect-monorepo#532]
Steps to reproduce:

1. Open https://www.convexfinance.com in Safari on macOS.
2. Click Connect Wallet / WalletConnect.
3. Click "Copy to clipboard".

Result: pasteboard is not modified.

**Comment by pedrouid** [comment]
I've pushed a fix for this under v1.5.0-rc.4 which you can track on PR #526 

v1.5.0 is scheduled for Monday 5th June
