### ISSUE TITLE
transport reconnect but not re-subscribe(version 1.4.1)

### ISSUE THREAD

**Issue by garyng2000** [WalletConnect/walletconnect-monorepo#533]
While reading the socket code, I noticed that it has auto-reconnect in case of socket error. However, the following code makes in not able to 're-subscribe' its own topic(channel for peer to send message over). As the subscriptions list is empty after sub. I fixed this via hack but directly put back the clientId in case of socket error(listening on connector level). This however should be handled in the re-connect code.

After this change, I can pull down my relay server and restart and the communication is restored. Of course, this is only for transient issue, there still need upper level re-connect strategy for complicated scenarios.

  private _queueSubscriptions() {
    const subscriptions = this._subscriptions;

    subscriptions.forEach((topic: string) =>
      this._queue.push({
        topic: topic,
        type: "sub",
        payload: "",
        silent: true,
      }),
    );

    this._subscriptions = [];
  }

**Comment by finessevanes** [comment]
@garyng2000 is this still an issue?
