### ISSUE TITLE
Dapp Can't connect server

### ISSUE THREAD

**Issue by Xuxue1** [WalletConnect/walletconnect-monorepo#535]
<img width="1216" alt="截屏2021-06-22 上午9 16 54" src="https://user-images.githubusercontent.com/12817095/122849123-80111100-d33d-11eb-9a85-ba5da61745a1.png">

**Comment by rudolfs** [comment]
We're also experiencing intermittent connectivity issues when connecting a wallet to our app lately:
- Unexpected response code: `429`
```
index.js?ecbf:84 WebSocket connection to 'wss://bridge.walletconnect.org/?env=browser&host=&protocol=wc&version=1' failed: Error during WebSocket handshake: Unexpected response code: 429
```

- Unexpected response code: `403`:
```
index.js?ecbf:84 WebSocket connection to 'wss://bridge.walletconnect.org/?env=browser&host=&protocol=wc&version=1' failed: Error during WebSocket handshake: Unexpected response code: 403
```

**Comment by pedrouid** [comment]
There was an outage. Everything is back to operation. Sorry for the inconvenience
