### ISSUE TITLE
WebSocket connection ERROR

### ISSUE THREAD

**Issue by KayAlbertus** [WalletConnect/walletconnect-monorepo#536]
Hello Team Please may you assist we are seeing below ws:// response when trying to use wallet connect to connect to dapp
![wsError](https://user-images.githubusercontent.com/15343562/123105437-1aee1600-d438-11eb-8bc8-45a5902af3be.jpg)

We also receive Host Error Response 

https://bridge.walletconnect.org/info

**Comment by pedrouid** [comment]
There was an outage. Everything is back to operation. Sorry for the incovenience
