### ISSUE TITLE
Request redirects to the wrong app

### ISSUE THREAD

**Issue by mNizhurin** [WalletConnect/walletconnect-monorepo#539]
When I connect dapp to Unstoppable wallet everything works fine. After success connection I want to send tx but now dapp is opening Metamask instead of my connected app.

In attachment you can see how approve request opening Metamask instead of Unstoppable wallet

https://user-images.githubusercontent.com/1726387/124076181-bbab8980-da67-11eb-9c91-eb9f3674c62f.MP4

**Comment by mNizhurin** [comment]
any update?

**Comment by finessevanes** [comment]
@mNizhurin is this still an issue?
