### ISSUE TITLE
[feature request] Flutter implementation

### ISSUE THREAD

**Issue by j05u3** [WalletConnect/walletconnect-monorepo#540]
I have seen there is a react-native implementation. But no flutter implementation yet and flutter has a strong/growing community 😁

**Comment by pedrouid** [comment]
We are aware but we are only going to be implementing for v2.0... too late for v1.0

**Comment by j05u3** [comment]
> We are aware but we are only going to be implementing for v2.0... too late for v1.0

Thanks for your answer, I understand 👍, btw is this the correct repo to post this feature request then?

**Comment by PhamNgocPhi** [comment]
Hi, Flutter has been released to version 2.5.2, so I want to know if WalletConnect already supports Flutter? Thanks. I want to implement WalletConnect for my mobile app in flutter but I can't find anything

**Comment by nicoelzer** [comment]
We would also love to use it on Flutter – any chance Flutter support is coming soon?  🥰

**Comment by maxsap** [comment]
+1 for flutter, are there plans for it?

**Comment by j05u3** [comment]
Just to have a, maybe, useful link. This is what motivated me to open this issue:

https://stackoverflow.com/questions/68214773/problems-with-dapp-development-with-flutter-and-web3/68215593?noredirect=1#comment123884591_68215593

And I think Volodymyr Bilovus already found an implementation (check comments).

[edit] Sorry, the implementation mentioned in the stackoverflow comment is for building a wallet app, not for apps connecting to it.

**Comment by nhtlquan** [comment]
+1 for flutter

**Comment by HoangLotus** [comment]
Has anyone found a solution yet?

**Comment by Abdulhaseeb101** [comment]
Please provide a flutter implementation
