### ISSUE TITLE
column registry_with_chains_view.badge_type does not exist

### ISSUE THREAD

**Issue by mukkumayc** [WalletConnect/walletconnect-monorepo#5409]
**Describe the bug**
https://explorer-api.walletconnect.com/w3m/v1/getDesktopListings and 
https://explorer-api.walletconnect.com/w3m/v1/getInjectedListings methods return an error
```
{
  "error": "column registry_with_chains_view.badge_type does not exist"
}
```
**To Reproduce**
1. Go to https://react-app.walletconnect.com/

**Screenshots**
![image](https://github.com/user-attachments/assets/e48ebd7a-6acd-4001-9692-3e6eadf4ecfa)

**Comment by bkrem** [comment]
Hi, there was a temporary issue with the associated APIs that was flagged and reverted immediately. See our status page for context: https://status.reown.com/incidents/pm6tfkf94854
