### ISSUE TITLE
ethereumjs-api unable to access

### ISSUE THREAD

**Issue by CherishLY** [WalletConnect/walletconnect-monorepo#541]
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/ethereumjs/ethereumjs-abi.git
npm ERR! 
npm ERR! fatal: unable to access 'https://github.com/ethereumjs/ethereumjs-abi.git/': Encountered end of file
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitlab-runner/.npm/_logs/2021-07-02T08_02_23_759Z-debug.log

version: 1.4.1

**Comment by finessevanes** [comment]
@CherishLY is this still an issue?
