### ISSUE TITLE
Add Unichain Testnet Support

### ISSUE THREAD

**Issue by narangchirag** [WalletConnect/walletconnect-monorepo#5440]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).

   
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
  EIP-155 (EVM chain)
  
3. **namespaces**:
  EIP-155 (EVM chain)
  
4. **chains**:
testnet: eip155: 1301

5. **RPC endpoints**

testnet: https://sepolia.unichain.org/
testnet doc: https://docs.unichain.org/docs
testnet explorer: https://sepolia.uniscan.xyz/
   
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
testnet: 1 (testnet, all coins)

**References**
To ensure timely processing of your request, please provide the following references:

- [x] Source of RPC endpoints (e.g. RPC docs): [link](https://docs.unichain.org/docs/technical-information/network-information)
- [x] Source of namespace (if non-EIP155) chain information (particularly chainIds): [link]

**Additional context**
Add any other context here.

This request for integrating Unichain sepolia testnet, a dedicated defi L2 launched by Unsiwap. For mainnet we are expecting to have two phases
1/ Developer Mainnet: End of Oct 
2/ Open mainnet: Mid Nov (for end users)

We will update or raise a new issue for integrating mainnet.  Please let us know if you need any more information or we can help in any capacity. Would love to have you support us on testnet. 

**Please note:**

**Registering a chain with the Explorer does not impact or improve the ability for wallets and dapps to support your chain.** It is simply a way for users to discover wallets and dapps that support your chain by:

- Browsing the [Chains List](https://docs.walletconnect.com/advanced/multichain/chain-list)
- Filtering results programmatically via the [Explorer API](https://docs.walletconnect.com/cloud/explorer)

**It is still up to wallets and dapps to provide concrete support for your chain once it is listed as part of the Explorer.**

- [x] I have read and understood the above clarification

**Comment by saucepoint** [comment]
Unichain Sepolia, should be available on viem

https://github.com/wevm/viem/pull/2840
