### ISSUE TITLE
No matching pairing pending with topic，In version 2.0

### ISSUE THREAD

**Issue by zhangjinbiao746** [WalletConnect/walletconnect-monorepo#545]
I used the 2.0 version to connect the dapp and wallet. On the dapp, I initialized walletconnect and got a uri. When I used React-Native Client to initialize walletconnect and paired the uri, I got an error

![C2CE1B58-F85F-4b48-AA70-4C298A5B5B75](https://user-images.githubusercontent.com/29059279/124736935-12263580-df4a-11eb-909c-a0618afe6746.png)
On the dapp side, I will get the following error
![07B7D99B-0CEE-46d8-8D7B-691F0FCBDF2E](https://user-images.githubusercontent.com/29059279/124737124-400b7a00-df4a-11eb-814e-578965384dc3.png)
Below is the code on my dapp side
![94CA1AFB-877A-482b-956B-B1340B437671](https://user-images.githubusercontent.com/29059279/124737524-9d073000-df4a-11eb-8e84-aec50aedf72a.png)
Below is the code of my React-Native Client
![C8857401-08D4-4e4d-A7CB-AD430F250DE2](https://user-images.githubusercontent.com/29059279/124737896-fbcca980-df4a-11eb-99c0-bff086eb47de.png)
The screenshot is not truncated,I'm not sure what went wrong, please help me

**Comment by AlexeyGorbachevskiy** [comment]
Have the same issue. 
Steps to reproduce:
1. Scan qr code
2. Refresh client react app
3. Click login in wallet app
4. Refresh client react app again
Note: After refresh client react app againt (third time) - error is absent.

Actual Result:
![image](https://user-images.githubusercontent.com/37103509/125503573-bba07bf3-bd5b-42cf-abad-f0f6bfc40d88.png)

**Comment by finessevanes** [comment]
@jinbiao-bianjie is this still an issue?
