### ISSUE TITLE
Support for EIP712 array types

### ISSUE THREAD

**Issue by bonustrack** [WalletConnect/walletconnect-monorepo#546]
Signing a typed data message using EIP-712 with array type doesn't work well with WalletConnect. 

**Step to reproduce:**

- Go here: https://demo.snapshot.org/#/fabien.eth/proposal/0x9bb534d4e2394ea4512406a22f0a974ff86382b00b4597a5e2f34d3fa9e2cc3e
- Log in with WalletConnect (for example with Argent or Trust Wallet)
- Select "Alice" and "Bob" in the "Cast your vote" block
- Click "Vote", then "Vote" again in the confirmation modal.
- Vote will fail with a message "wrong signature". 

If i remove the array type from the EIP712 type here: https://github.com/snapshot-labs/snapshot.js/blob/686f578fd805b0d0ca207b06040d2580c143dbfa/src/sign/types.ts#L99 it will work

Array types was introduced in V4 of EIP-712 see: https://github.com/MetaMask/eth-sig-util#signtypeddata_v4-privatekeybuffer-msgparams or https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md#definition-of-encodedata

**Comment by vanya2h** [comment]
Does anyone have workaround for it?

**Comment by pauldemarco** [comment]
Here's the fix: https://github.com/MetaMask/metamask-mobile/pull/2990

**Comment by midgerate** [comment]
@pauldemarco It looks like your code was merged however there was a new method created for that. How are you able to call that method in walletconnect? https://github.com/MetaMask/metamask-mobile/pull/3020

I do not see this change in the develop branch of metamask-mobile https://github.com/MetaMask/metamask-mobile/blob/develop/app/core/WalletConnect.js

**Comment by midgerate** [comment]
@rickycodes I saw you reverted signTypedData_v4 from metamask. By looking at the latest implementation I see that signTypedData defaults to signTypedData_v3 which does not have support for typedArrays. At snapshot we use typed arrays and we need support for v4. When do you think the default can be changed to v4? 

cc @sethkfman

**Comment by addmorebass** [comment]
Was this ever addressed?

**Comment by midgerate** [comment]
@addmorebass yes, but it was soon reverted.

**Comment by addmorebass** [comment]
Our signature is not even reaching TrustWallet via WalletConnect, so I wonder if it is related.

**Comment by midgerate** [comment]
@addmorebass trustwallet via walletconnect works fine even with v4. They implemented it long ago. But this thread is about metamask mobile.

**Comment by finessevanes** [comment]
@bonustrack is this still an issue?

**Comment by hung-native** [comment]
not sure what's the best practice. just sharing how i did it, hash the array to bytes32 and sign on that.
