### ISSUE TITLE
Unhandled Rejection (Error): No matching session pending with topic (React). Wallet Connect version 2.0

### ISSUE THREAD

**Issue by alexeygorbachevsky** [WalletConnect/walletconnect-monorepo#549]
**You can reproduce this issue just by checking your examples (react app, react wallet)**

**Pre-steps**
1. Clear react app local storage.

**Steps to reproduce:**

0. Connect to Ethereum for ex. (it doesn't matter)
1. Copy URI to clipboard
2. Paste URI to react wallet (**Don't approve yet**)
3. Refresh client react app
4.  **Now Approve** logging in in react wallet
5. Refresh client react app again

Actual Result:
![image](https://user-images.githubusercontent.com/37103509/125506447-9f815574-eac3-4a9d-bc32-b1f9c4fa86cb.png)

**Note: After refresh client react app again (third time) - error is absent.**

The issue looks like https://github.com/WalletConnect/walletconnect-monorepo/issues/545

**Comment by finessevanes** [comment]
@alexeygorbachevskiy is this still an issue?
