### ISSUE TITLE
[@walletconnect/ethereum-provider V2] Gas sponsoring on ZKSyncEra network Intermittent Error: No matching key. on eth_sendTransaction requests

### ISSUE THREAD

**Issue by amedrontadora** [WalletConnect/walletconnect-monorepo#5493]
**Describe the bug**
When using the Safe wallet to connect to WalletConnect on the ZkSync network and sending transaction with the ZYFI Gas Sponsoring feature, an error occurs when sending a transaction. The error message is "No matching key. history: 1731258865148435."

```
No matching key. history: 1731258865148435
    at Lt.getRecord (http://localhost:3000/static/js/defaultVendors-node_modules_wagmi_core_node_modules_walletconnect_sign-client_dist_index_es_js.chunk.js:6837:13)
    at Lt.get (http://localhost:3000/static/js/defaultVendors-node_modules_wagmi_core_node_modules_walletconnect_sign-client_dist_index_es_js.chunk.js:6776:20)
    at Ut.onRelayEventResponse (http://localhost:3000/static/js/defaultVendors-node_modules_wagmi_core_node_modules_walletconnect_sign-client_dist_index_es_js.chunk.js:6582:38)
    at EventEmitter.<anonymous> (http://localhost:3000/static/js/defaultVendors-node_modules_wagmi_core_node_modules_walletconnect_sign-client_dist_index_es_js.chunk.js:6719:147)
```

**SDK Version (if relevant)**
 - Client: NodeJS
 - Version v18.18.0
 
Dependent packages and versions

"@wagmi/connectors": "^3.1.11"
"@web3modal/ethers5": "^5.1.11"

**To Reproduce**
1. Go to syncswap.xyz 
2. Click connect then click WalletConnect and copy pairing code
3. Go to https://app.safe.global/  click WalletConnect paste pairing code
4. Return to SyncSwap and click on the icon to the ETH token and balance display. In the pop-up window, select any token displayed as FREE; for this example, I will use USDC.
5. Execute any swap.
6.An error will appear on console as described above: 'Missing or invalid request() method: eth_sendRawTransaction'.

**Expected behavior**
Gas sponsoring with a Safe Wallet work well

**Screenshots**
![14cd774d6cb48adfcd6ed60125076494](https://github.com/user-attachments/assets/5d5c44e8-9154-42a6-aac7-701fb947d470)

**Desktop (please complete the following information):**
 - MacOS 15.0.1 (24A348)
 - Chrome 
 - 130.0.6723.92

**Comment by Annawoody** [comment]
it usually means there's an issue with the key or the transaction history.I'll have to refer you to the official support live chat with the ticket ID ZkS07638
Please see the link below to our dedicated support line:
[ ZkSync Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
@amedrontadora

**Comment by arein** [comment]
The error message says send raw transaction is not supported.

Unfortunately many wallets do not support that method. Clave wallet does. You should be able to intercept at connection time whether the wallet supports the RPC method.

More and more wallets are supporting ERC-7677 which is the EVM standard for gas sponsorship.
