### ISSUE TITLE
Cannot establish WalletConnect connection to some DApps via TOR

### ISSUE THREAD

**Issue by abdrasulov** [WalletConnect/walletconnect-monorepo#551]
When Tor is enabled socket connection with some Dapps cannot be established. For instance, 1inch (https://app.1inch.io). It fails with an error:

java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'

The response is as follows:

Response{protocol=http/1.1, code=403, message=Forbidden, url=https://walletconnect-bridge.1inch.exchange/}

At the same time, Uniswap (https://app.uniswap.org/) works well. When the socket connection is established its response looks as:

Response{protocol=http/1.1, code=101, message=Switching Protocols, url=https://uniswap.bridge.walletconnect.org/}

I checked it with a Trust Wallet. I used the orbot app to enable Tor in this case. The behavior is the same. 1inch.io fails and uniswap.org works well.

Could you please help us with it?

**Comment by finessevanes** [comment]
@abdrasulov is this still an issue?

**Comment by abdrasulov** [comment]
It turned out that 1inch has restrictions by IP https://help.1inch.io/en/articles/5778756-vp n-restricted-territory
