### ISSUE TITLE
Redirect if there is a callback before the method call

### ISSUE THREAD

**Issue by therockunderlying** [WalletConnect/walletconnect-monorepo#552]
Hello everyone, i can't figured out why when i call a method with provider, walletconnect keeps redirecting me in [https://link.trustwallet.com](https://link.trustwallet.com) instead of open me the app to approve the transaction. I've wrote the code for metamask and walletconnect and i used ethersjs to handle the provider. I've tried to remove the axios before the contract call and it worked. I can't figured out why if i put a setTimeout before or await for a response, webpage redirects me.

Here's code for connection

     const getBlockchain = (typew) =>
        new Promise(async (resolve) => {
          var provider;
          if(typew == "metamask"){
            if(window.ethereum) {
              await window.ethereum.enable();
              provider = new ethers.providers.Web3Provider(window.ethereum);
            }
          }
            
          if(typew == "walletconnect"){
              providerEth = new WalletConnectProvider({
                chainId: 56,
                rpc: {
                  56: "https://bsc-dataseed.binance.org",
                }
              });
      
              await providerEth.enable();
              provider = new ethers.providers.Web3Provider(providerEth); 
      
              provider.off("disconnect");
              provider.on("disconnect", () => {
                closeBlockhain();
              })
          }
          
          
          if(provider !== undefined){
            const signer = provider.getSigner();
            /* @ts-ignore */
            const signerAddress:any = await signer.getAddress();
      
            const contract = new Contract(
              Contract.networks[56].address,
              Contract.abi,
              signer
            );
      
            const contract_two = new Contract(
              Contract_two.networks[56].address,
              Contract_two.abi,
              signer
            );
      
            configConnections = {
              connected: true,
              provider,
              contract,
              contract_two,
              signerAddress: signerAddress
            }
      
            resolve(configConnections);
          }
        
        resolve(configConnections);
       });

Here's the code of calling method

        const onSubmit = async (values: FormValues) => {
		        if(configConnections.connected){
			        setDisabled(true);
			        await axios.post(API_ENDPOINTS.ORIGINAL+API_ENDPOINTS.CREATE, { values,image })
			        .then(async (res) => {
				        if(res.data !== false){
						        let takeOn = await configConnections.contract.awardItem(ethers.utils.formatBytes32String("1"),res.data.hash);
						        await takeOn.wait().then(function(x) {
							        console.log(x)
							        axios.post(API_ENDPOINTS.ORIGINAL+API_ENDPOINTS.UPDATEHASH, { tokenURI: res.data.hash, hash: x.blockHash })
							        .then(async upd => {
								        if(upd.data !== false){
									        setModalData({data: upd.data});
								        }
							        });
						        });
				        } else {
					        setDisabled(false);
				        }
			        })
		        }
	        };

Can't explain to myself why if i open the app on mobile and try to call method, the browser redirects me on other page not on the TrustWallet or Metamask App.

Thank you.

**Comment by therockunderlying** [comment]
I've tried Web3 and i've same problem. Tried wthout axios and works, but i need axios first.	


      const onSubmit = async (values: FormValues) => {
		if(configConnections.connected){
			setDisabled(true);
			//await axios.post(API_ENDPOINTS.ORIGINAL+API_ENDPOINTS.CREATE, { values,image })
			//.then(async (res) => {
				const res = {data: {hash: "qq"}};
				if(res.data !== false){
						let takeOn = await configConnections.contract.awardItem(ethers.utils.formatBytes32String("1"),res.data.hash);
						await takeOn.wait().then(function(x) {
							console.log(x)
							axios.post(API_ENDPOINTS.ORIGINAL+API_ENDPOINTS.UPDATEHASH, { tokenURI: res.data.hash, hash: x.blockHash })
							.then(async upd => {
								if(upd.data !== false){
									setModalData({data: upd.data});
								}
							});
						});
				} else {
					setDisabled(false);
				}
			//})
		}
	};

**Comment by luutrunghieu** [comment]
I face the same issue. I try signing right after connected with the trust wallet. The signing pop-up still pops in the trust wallet app but the web page already redirects to https://link.trustwallet.com so every callback I do after sign message doesn't work. Any updates?

**Comment by therockunderlying** [comment]
I've resetted the window-getters "WALLETCONNECT_DEEPLINK_CHOICE" and this. The only problem is that the user is not redirected to the site if he does not have the app installed. After all, if he doesn't have the app, he knows about it.

In browser-utils->dist->mobile.js (there are others files "mobile.js" inside @walletconnect, i can't remember which one was)

```
return entry.universalLink
        ? `${entry.universalLink}/wc?uri=${encodedUri}`
        : entry.deepLink
            ? `${entry.deepLink}${entry.deepLink.endsWith(":") ? "//" : "/"}wc?uri=${encodedUri}`
            : "";

```

To:

```
const isMobile = () => {
    return (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) ? true : false;
}

return !isMobile()
        ? `${entry.universalLink}/wc?uri=${encodedUri}`
        : entry.deepLink
            ? `${entry.deepLink}${entry.deepLink.endsWith(":") ? "//" : "/"}wc?uri=${encodedUri}`
            : "";

```

**Comment by finessevanes** [comment]
@therockunderlying @luutrunghieu is this still an issue?
