### ISSUE TITLE
How to select custom token in sendTransaction()

### ISSUE THREAD

**Issue by Amazing1974** [WalletConnect/walletconnect-monorepo#554]
const tx = {
        from,
        to,
        nonce,
        gasPrice,
        gasLimit,
        value,
        data
      };
const result = await connector.sendTransaction(tx);

when I call this function, I can see the popup in metamask.
but I can't see select token type.

I have two tokens.
![Screenshot 2021-07-19 at 11 34 01](https://user-images.githubusercontent.com/51259135/126129255-1111425d-d32b-4162-a060-74b94a01ae11.png)

**Comment by finessevanes** [comment]
@Amazing1974 is this still an issue?
