### ISSUE TITLE
137070

### ISSUE THREAD

**Issue by Mohamadjamalpoor** [WalletConnect/walletconnect-monorepo#5549]
**Describe the bug**

**SDK Version (if relevant)**
 - Client: [e.g. JS, Swift, Kotlin]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by enesozturk** [comment]
Missing info or possibly bot
