### ISSUE TITLE
nevermind

### ISSUE THREAD

**Issue by teacoat** [WalletConnect/walletconnect-monorepo#5552]

**Comment by kantorcodes** [comment]
We'd greatly appreciate some eyes on this

**Comment by teacoat** [comment]
was able to reproduce the issue when pairing with trace debugging on:
![image](https://github.com/user-attachments/assets/7e5c706e-1487-466d-88c7-9dce94b918f3)

**Comment by teacoat** [comment]
And trace logs for when receiving a request
![image](https://github.com/user-attachments/assets/e1d57621-764f-480e-95c5-76a2feb9c013)

**Comment by teacoat** [comment]
nevermind
