### ISSUE TITLE
Error: Subscribing failed

### ISSUE THREAD

**Issue by thegodfatherbeeearth** [WalletConnect/walletconnect-monorepo#5557]
Hello guys I am trying to use wallet connect for my Tron Dapp as per this guide: https://developers.tron.network/docs/walletconnect-tron.

However in 90% cases I am getting Error: Subscribing to 015203256240959be9aff74259c98a52f6397d84a648813a065b0b8591fd40b7 failed, please try again.

What am I doing wrong?

My config:

```typescript
import { WalletConnectWallet, WalletConnectChainID } from '@tronweb3/walletconnect-tron';
const walletConnect = new WalletConnectWallet({
    network: WalletConnectChainID.Mainnet,
    options: {
        relayUrl: 'wss://relay.walletconnect.com',
        projectId: 'b662a0e99d82c689fb43813449011579',
        metadata: {
            name: 'buytrx.org',
            description: 'buytrx.org WalletConnect',
            url: 'https://buytrx.org/',
            icons: ['https://buytrx.org/trx.svg']
        }
    },
    web3ModalConfig: {
        themeMode: 'dark',
        /**
         * Recommended Wallets are fetched from WalletConnect explore api:
         * https://walletconnect.com/explorer?type=wallet&version=2.
         * You can copy these ids from the page.
         */
        explorerRecommendedWalletIds: [
            '4622a2b2d6af1c9844944291e5e7351a6aa24cd7b23099efac1b2fd875da31a0'
        ],
    }
});
```

And I simply do `await walletConnect.connect()` when the user clicks "Connect Wallet".

My website is https://buytrx.org/. Screenshot:

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/60ece80c-6c9a-4543-9d85-8b479e444b2e" />

Thanks in advance for your help!

**Comment by ganchoradkov** [comment]
hey @nebolax, are you using some kind of VPN that might be preventing the sdk to connect with the relay?

**Comment by thegodfatherbeeearth** [comment]
> hey @nebolax, are you using some kind of VPN that might be preventing the sdk to connect with the relay?

Hmmmm this is an interesting hypothesis. I remember that after I posted this issue, after some time it just magically started working😄 Might be the VPN as it is sometimes on and sometimes off on my computer.

I am going to close the issue for now since currently all is good (at least on my machine), thank you for your reply! But I am curious then: wallet connect isn't meant to be used with VPNs ?!??! 👀

**Comment by ganchoradkov** [comment]
> But I am curious then: wallet connect isn't meant to be used with VPNs ?!??! 👀

It can be used with VPNs of course but it depends on how restrictive the VPN itself is and usually the experience is degraded
