### ISSUE TITLE
Pending Session isn't deleted after Reject. Need event for Reject action. (WC version 2.0) 

### ISSUE THREAD

**Issue by alexeygorbachevsky** [WalletConnect/walletconnect-monorepo#556]
**1.** No way to react (in client React app) on Reject event (when in wallet app user cancel log in for ex.) after refresh page if session is pending yet.

**2.** **Steps**:
1. Scan qr-code
2. Refresh client app
3. Click on **Reject** in wallet app

**Actual result**: Session is pending yet in local storage. No way to react on reject event if page was refreshed.

**Comment by finessevanes** [comment]
@alexeygorbachevskiy is this still an issue?
