### ISSUE TITLE
I use the latest source to build show me dependency error

### ISSUE THREAD

**Issue by GHChrisSu** [WalletConnect/walletconnect-monorepo#557]
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: request to https://registry.npmjs.org/fsevents failed: cache mode is 'only-if-cached' but no cached response available.

npm ERR! code ENOTCACHED
npm ERR! request to https://registry.npmjs.org/safe-json-utils/-/safe-json-utils-2.0.0-beta.0.tgz failed: cache mode is 'only-if-cached' but no cached response available.

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/nix-build-node-dependencies-_at_walletconnect_slash_relay-server-1.0.0.drv-0/.npm/_logs/2021-07-27T12_00_56_499Z-debug.log

builder for '/nix/store/8q6gwhznkwxfypjzgfn9jhslsfapvrl6-node-dependencies-_at_walletconnect_slash_relay-server-1.0.0.drv' failed with exit code 1
error: build of '/nix/store/8q6gwhznkwxfypjzgfn9jhslsfapvrl6-node-dependencies-_at_walletconnect_slash_relay-server-1.0.0.drv' failed
make: *** [build-relay-deps] Error 100

**Comment by finessevanes** [comment]
@GHChrisSu is this still an issue?
