### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'id' in ����D�f�9��p7ƃ0���ׇl[

### ISSUE THREAD

**Issue by GHChrisSu** [WalletConnect/walletconnect-monorepo#558]
Beta 10 version of walletconnect 2.0 appears some garbled

![image](https://user-images.githubusercontent.com/13779988/127161571-3cc50777-83e9-42bc-874e-71fb867a95e7.png)

**Comment by lf94** [comment]
I am having this exact issue. Did you figure it out?

**Comment by lf94** [comment]
This is happening in beta26. From what I can tell my setup is exactly as the cosmos example application, which also uses beta26 (but maybe is not deployed, I can't tell).

**Comment by lf94** [comment]
@pedrouid pinging so you get some visibility on this while I try and find the root cause...

**Comment by lf94** [comment]
This appears to be happening in Electron applications. In Chromium, the issue is not there. Any ideas?

**Comment by GHChrisSu** [comment]
@lf94 You should keep the version same both client and server. If you use your own server to deploy.

**Comment by GHChrisSu** [comment]
It's not happen now, maybe some version problem.

**Comment by lf94** [comment]
It is happening for me absolutely no matter the version. It has to do with the fact it's running in an Electron context.
