### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR when trying to run bridge server

### ISSUE THREAD

**Issue by mhorsley30896** [WalletConnect/walletconnect-monorepo#560]
I would like to run my own instance of the bridge server included in this repo. I had an old instance running but it is no longer working with some wallets via wallet connect.

I have my bridge domain DNS A record pointed at my server

I followed the following steps on my server:

- apt install docker
- apt install make
- apt install git
- git clone https://github.com/WalletConnect/walletconnect-monorepo.git
- make deploy

When asked for my domain and email I inputted it. When asked for cloudflare I just hit enter (left it blank) as I do not use cloudflare for my DNS.

When I try to connect to my dapp now, I get the following error:

`WebSocket connection to 'wss://bridge.mydomain.com/' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR`

What steps do I need to take to fix?

**Comment by mhorsley30896** [comment]
Update: I do not believe it is anything to do with Cloudflare as I set up cloudflare and pointed my domain at their name servers as per their instructions. The phrasing "please enter your cloudflare api" is ambiguous as you are presented with several different apis in the cloudflare portal. I tried each one and still get an ERR_SSL_PROTOCOL_ERROR after an apparently successful deployment.

**Comment by foxgem** [comment]
I got this same issue and fixed, please check my comment: https://github.com/WalletConnect/walletconnect-monorepo/issues/548#issuecomment-889749277

**Comment by sylvester19** [comment]
Any update on this ? Facing the same issue

**Comment by finessevanes** [comment]
Hey @sylvester19 @mhorsley30896 are you still have an issue? The comment @foxgem is referring to:
```
When I changed the provider to 1.5.x, the problem is gone. It is caused by the overload bridge server, the new version will select a server randomly.

My env: web3modal + walletconnect provider 1.5.1.
```
