### ISSUE TITLE
Local development using a VM

### ISSUE THREAD

**Issue by pi0neerpat** [WalletConnect/walletconnect-monorepo#561]
I usually run my apps in a VM, and interact with them using a browser on the host machine. So the domain is something like http://192.168.4.45:8910 instead of http://localhost:8910

This blocks testing with Wallet Connect, since the domain is not localhost, and some crypto features are only available via localhost or https. For example SubtleCrypto.importKey https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/importKey

Is there any solution for this? Would shims help? Do we care enough to fix this? Just wanted see what your thoughts are.

```
"webpack": "^4.41.5",
"@walletconnect/web3-provider": "^1.2.0-alpha.0",
also tested
"@walletconnect/web3-provider": "^1.5.1",
```

**Comment by finessevanes** [comment]
@pi0neerpat is this still an issue?

**Comment by pi0neerpat** [comment]
Looks like no one else has this problem so we can close it.

**Comment by 0xbuidler** [comment]
Hey @pi0neerpat would you mind re-open this issue ? I'm facing the same issue. 

In my setup, I'm using an Iphone on my local network, therefore it's not `localhost` either but something like `192.168.x.x`, is there anything I can do ? I don't wanna do the hustle of passing all my stack code to `https`.

I've seen other people mentioning this issue on other repo that have WalletConnect as dependency.

**Comment by pi0neerpat** [comment]
@sshmaxime ok! Could you please post your version here, and maybe link the issues from others facing this issue?
