### ISSUE TITLE
Random latency issues

### ISSUE THREAD

**Issue by h0ds** [WalletConnect/walletconnect-monorepo#562]
Has anyone had issues recently associated with delays? I'm not sure if this is WalletConnects fault or Infuras. But after I scan the QR code with a wallet app like Metamask or Rainbow, it can take 20/30 seconds sometimes for a connect request to popup, or sometimes it doesn't appear at all.

Any ideas whats going on?

To clarify, this is when using the WalletConnect provider via web3modal.

**Comment by foxgem** [comment]
If the version you are using is 1.4.x, you can check if my way works: https://github.com/WalletConnect/walletconnect-monorepo/issues/548#issuecomment-889749277 .

**Comment by finessevanes** [comment]
@gregjw are you still have this issue?

**Comment by h0ds** [comment]
The issue is from almost 18 months ago, I haven't touched WalletConnect since then.

**Comment by finessevanes** [comment]
@gregjw thanks for your feedback. I'm the DevRel at WalletConnect so just going through alll of the issues.
