### ISSUE TITLE
Connecting to WalletConnect on mobile redirects to app store listing

### ISSUE THREAD

**Issue by vernonjohnson** [WalletConnect/walletconnect-monorepo#563]
When connecting to WalletConnect from mobile (iOS) I'm redirected to the app store listing for the mobile wallets (Metamask, Rainbow).

<img src="https://user-images.githubusercontent.com/25010543/127751094-88b7a3de-140b-4466-a72a-90f3ec953723.PNG" width="200" height="400">
<img src="https://user-images.githubusercontent.com/25010543/127751098-cc770ff3-5434-41ac-befd-d7e394a5f078.PNG" width="200" height="400">

**Comment by hassantsyed** [comment]
I am experiencing similar issues on android. However, I get redirected to the website wallet registry.
I cannot connect my wallet. This is with version 1.5.2.

**Comment by kkaczynski** [comment]
The same on my side - Android is opening website wallet registry.

**Comment by tuomohopia** [comment]
I'm experiencing this too, have been with all the versions above `1.5.0`.

Having missed this, I submitted my own issue about it: https://github.com/WalletConnect/walletconnect-monorepo/issues/588

**Comment by tuomohopia** [comment]
@hassantsyed @kkaczynski @verminator23  I just found out how I'm able to solve this locally.

Please see https://github.com/WalletConnect/walletconnect-monorepo/issues/588#issuecomment-905034477 of how it resolves at least on my setup locally.

I haven't been able to identify yet what actually produces this code and how to solve this properly. Could use your help figuring this out if you're still experiencing this.

**Comment by ai-slave** [comment]
Same @ iOS, clicking 1inch redirects to another app strore listing (some other waller)

**Comment by finessevanes** [comment]
@ai-slave @vernonjohnson @tuomohopia @hassantsyed @cryptoexpert2000 is this still an issue?

**Comment by ai-slave** [comment]
Still opens App Store instead of wallet for me
