### ISSUE TITLE
When support EIP-1559?

### ISSUE THREAD

**Issue by chendatony31** [WalletConnect/walletconnect-monorepo#565]

**Comment by finessevanes** [comment]
There is support for EIP-1559 in v1.0.

v1.0 the Sign API had the specific Ethereum calls in the client which meant that when EIP-1559 was introduced, the Sign aPI was updated to make it compatible.

In v2.0 the Sign API has NO blockchain specific calls as it’s all abstracted by generic JSON-RPC calls and it’s the responsibility of blockchain libraries such as ethers.js or wagmi.js to support these EIPs.
