### ISSUE TITLE
"color" is undefined when selecting Desktop option in QR Modal

### ISSUE THREAD

**Issue by sammdec** [WalletConnect/walletconnect-monorepo#566]
Affected version:  1.5.2
Steps to repro:
* Specify mobileLinks array in WalletConnect constructor use value of just 'rainbow'
* Boot app open QR modal & click the Desktop toggle the modal will throw the exception

**Comment by ThaiBinh-13** [comment]
Is there any solutions for this issue?

**Comment by 8bu** [comment]
Is there any config to disable Desktop option?
Don't know what is it for..

**Comment by nuCodeIO** [comment]
This issue is effecting our project as well, when will this fix be merged and avaiable?

**Comment by finessevanes** [comment]
@sammdec @nucodeio is this still an issue?
