### ISSUE TITLE
Send request is not working.(connector.signTypedData is not a function)

### ISSUE THREAD

**Issue by dezzzus** [WalletConnect/walletconnect-monorepo#567]

**Comment by dezzzus** [comment]
Version: 1.5.2

I installed @walletconnect/react-native-dapp@1.5.2 and called signTypedData but got error like this.
`[TypeError: connector.signTypedData is not a function. (In 'connector.signTypedData([address, JSON.stringify(typedData)])', 'connector.signTypedData' is undefined)]`

Also connector.connected and connector.accounts are null.
connector.connect function is working well.

**Comment by inuyashaaa** [comment]
Something when wrong with 1.5.1 and 1.5.2. You should install 1.4.1

**Comment by finessevanes** [comment]
@dezzzus is this still an issue?
