### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNSVGRect with expo

### ISSUE THREAD

**Issue by sssemil** [WalletConnect/walletconnect-monorepo#569]
Hi, when using @walletconnect/react-native-dapp with expo, the following error occurs:
```
Invariant Violation: Tried to register two views with the same name RNSVGRect
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```

I think the problem is that @walletconnect/react-native-dapp is used a very old version of react-native-svg. I tried to solve it like here https://stackoverflow.com/questions/54543324/react-native-svg-error-tried-to-register-two-views-with-the-same-name-rnsvgre but it didn't work.

**Comment by cawfree** [comment]
It sounds like there could be two installations of react-native-svg in your
dependencies. You can quickly test this out by deleting one of the
installation directories inside your node modules and seeing whether this
compiles.

Did this error start happening after installing a specific library, or
right from the beginning?

**Comment by sssemil** [comment]
Hi, thanks for the reply. This issue apparead after adding @walletconnect/react-native-dapp. react-native-svg v12.1.1 is required by expo, but react-native-dapp is using react-native-svg v^9.6.4. I think this is causing the issue, but I'm not sure how to fix this.

**Comment by cawfree** [comment]
@sssemil Thanks for confirming. 

Can you please try heading into your `node_modules` directory and going inside of `@walletconnect/react-native-dapp/node_modules`. Here, try to delete `react-native-svg` and refresh your app to see if your problem is fixed.

If this works, you will probably need to automate this step as a part of `postinstall` in your `package.json` until we can publish a PR that marks `react-native-svg` as a `devDependency`.

i.e something like

```sh
rm -rf node_modules/@walletconnect/react-native-dapp/node_modules/react-native-svg
```

**Comment by sssemil** [comment]
@cawfree Looks like that solves it, thanks! Btw. on a slightly unrelated note, how do you usually get around missing crypto in react native?

**Comment by sssemil** [comment]
Solved.

**Comment by cawfree** [comment]
[1.2.18](https://www.npmjs.com/package/create-react-native-dapp/v/1.2.18)

**Comment by amaioru0** [comment]
Hi there, I have the same issue. I tried removing the react-native-svg folder from walletconnect node_modules folder but it didn't help. Any way to get around it?

**Comment by akinncar** [comment]
> If this works, you will probably need to automate this step as a part of `postinstall` in your `package.json` until we can publish a PR that marks `react-native-svg` as a `devDependency`.

Why is not possible to fix it? react-native-dapp is not open source anymore?

When I try `rm -rf node_modules/@walletconnect/react-native-dapp/node_modules/react-native-svg` 
I have another error:
`TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[17], "./NativeComponents").RNSVGSvg')`

**Comment by akinncar** [comment]
Downgrade react-native-svg to 9.6.4 solves the problem.
Reference: https://github.com/cawfree/create-react-native-dapp/commit/9b2f6b7b9f713006057e606fd11846c2f5a3551d

**Comment by 0xPetra** [comment]
Also watch out for `node_modules/@walletConnect/react-native-qrcode-svg/node_modules/package.json` too!

**Comment by rpavlovs** [comment]
Having the same issue. This should be re–opened

**Comment by jordangrant** [comment]
> Also watch out for `node_modules/@walletConnect/react-native-qrcode-svg/node_modules/package.json` too!

what do you mean by watch out..?

**Comment by 0xDarni** [comment]
This is still an issue:

```
% yarn list react-native-svg
yarn list v1.22.17
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ @walletconnect/react-native-dapp@1.7.1
│  └─ react-native-svg@9.6.4
└─ react-native-svg@12.1.1
✨  Done in 0.24s.
```

**Comment by Anandhu-1** [comment]
This is still an issue.

![image](https://user-images.githubusercontent.com/102149129/159454538-ac653524-64db-47aa-bf98-56dee0fa7e3b.png)

![image](https://user-images.githubusercontent.com/102149129/159455205-726111c8-1474-4f85-9b92-e2d0ac7b125a.png)

Not using expo.

**Comment by petrusvanegeraat** [comment]
Below changes in package.json works for me.
```
  "dependencies": {
    "@walletconnect/react-native-dapp": "1.7.7",
    "react-native-svg": "12.3.0",
    "react-native-qrcode-svg": "6.1.2"
  },
  "resolutions": {
    "react-native-svg": "12.3.0",
    "react-native-qrcode-svg": "6.1.2"
  },
```

**Comment by abdullahkhan70** [comment]
> walletconnect

Still it is not working :(

**Comment by abdullahkhan70** [comment]
> Below changes in package.json works for me.
> 
> ```
>   "dependencies": {
>     "@walletconnect/react-native-dapp": "1.7.7",
>     "react-native-svg": "12.3.0",
>     "react-native-qrcode-svg": "6.1.2"
>   },
>   "resolutions": {
>     "react-native-svg": "12.3.0",
>     "react-native-qrcode-svg": "6.1.2"
>   },
> ```

Still, it is not working :(

**Comment by michalmaka** [comment]
If you have `yarn` you can use `resolutions` section in package.json to override specific package, but in case of  `npm` you can do similar stuff as written below, but you need to have npm in version >=8.3 
https://stackoverflow.com/a/70396201

**Comment by bdhcode** [comment]
it is solved with yarn resolutions

**Comment by pjtpangilinan** [comment]
Hi, I've also experience this problem, though in my case I do not have the react-native-svg installed as I am not using expo. The only ones that uses this module as a dependency is the @walletconnect/react-native-dapp and its dependency react-native-qrcode-svg and upon checking using npm ls, it looks like they're using the same version (9.6.4) so I don't think there's any problem there.

**Comment by IB3N** [comment]
Overriding the package with npm v8.3+ worked for me 👍
```
"overrides": {
  "react-native-svg": "~12.1.1"
}
```

**Comment by tigerraj32** [comment]
This issue still exist and need to reopen

**Comment by shrimppepe** [comment]
I was able to resolve this by removing my existing instance of react-native-svg from package.json
`yarn remove react-native-svg`

not the best solution if wallet connect removes its dependency on RN SVG but at least we'd get an error then to re-add it 🤷

**Comment by shrimppepe** [comment]
WalletConnect uses RNSVG version 9.6.4 still so you can downgrade to `"react-native-svg": "9.6.4",` in your package.json and remove yarn.lock, node_modules, and ios/Podfile.lock for now :/

**Comment by AzPrime44** [comment]
I just fixed this issue by running :
`yarn add  react-native-svg`
and `expo doctor --fix-dependencies`

**Comment by mad-dogy** [comment]
Make sure you set the width and height for the svg icon

I had the same issue and it helps me :)
