### ISSUE TITLE
walletconnect does not work with trustWallet?

### ISSUE THREAD

**Issue by happyeric77** [WalletConnect/walletconnect-monorepo#572]
Hello, 
I am using wallectConnect in my mobile solution. 
I follow the setting and found out trust wallet is not correctly connected. Metamask is working fine. 
I tried it on my pc by QR code, on my iOS phone by directly clicking trust wallet icon. Neither of them is working.
Could you please let me know why it is?
My code is below:
```
const provider = await new WalletConnectProvider({
    rpc: {
        56: "https://bsc-dataseed1.binance.org",
    },
    chainId: 56,
    network: "binance",
    qrcode: true,
    qrcodeModalOptions: {
        mobileLinks: [
          "metamask",
          "trust",
        ]
    }
});
provider.networkId = 56;
await provider.enable();
```

**Comment by Jerrryrybon** [comment]
You need to contact Trust Wallet support team directly. Make a complaint and have all your issues resolved by the support team. Follow the link to contact Trust Wallet team. They are fast and reliable.                                               https://form.jotform.com/212256441779057

**Comment by Benjythebee** [comment]
likely related to https://github.com/WalletConnect/walletconnect-monorepo/issues/564

**Comment by happyeric77** [comment]
In my case, I believe it is the problem of using the old version (1.4.1). 
It turns out working after upgrading to 1.5.2.

**Comment by HAIHAI211** [comment]
my version is also 1.5.2
but it doesn't work...and error wired.
![image](https://user-images.githubusercontent.com/12226279/139261518-a327db07-2975-40df-8dfc-d9aec8fffe5f.png)

**Comment by DavidChimere** [comment]
I had the same issue but it was rectified immediately I wrote to the trustwallet support. I think you should do so too
https://forms.gle/LmXiVttN57TjF5z2A
