### ISSUE TITLE
Cannot deploy relay server on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by ravisriv** [WalletConnect/walletconnect-monorepo#573]
I have spent substantial time trying to install the relay server bundled with WalletConnect 2.0 monorepo. “make deploy” works perfectly and Caddyserver logs show it has correctly acquired the SSL certificates for the server. But when I try to connect to the server https://domain-name/hello using a browser, I get “TOO_MANY_REDIRECTS_ERR” error.

Caddyserver logs (in the docker container) are showing that the DNS config is correct. “docker ps” shows that all containers are running.

BTW, never had similar issues installing the walletconnect bridge server, which is now deprecated.

Would appreciate any help or documentation for setting up the relay server. Thanks!

**Comment by ravisriv** [comment]
Hi @pedrouid - I'd forever be grateful to you, if you could please help me with this one. Thank you!

**Comment by ravisriv** [comment]
Caddyserver appears to be failing to establish an SSL/TLS connection. Please see the screenshots of the log files:
![image](https://user-images.githubusercontent.com/62220449/128951953-3eb50579-50a2-4035-aafb-616ae7a7eb57.png)

**Comment by ravisriv** [comment]
Here is the docker container log of Caddyserver with (debug flag turned on) in the config file Caddyfile. It is showing TLS handshake errors. These are vanilla docker containers directly downloaded and deployed using "make deploy" command.

![image](https://user-images.githubusercontent.com/62220449/128952086-cd112efd-f58c-43b4-bf59-0e7ecc382531.png)

**Comment by ravisriv** [comment]
I'd be glad to provide any other information that is needed to resolve this issue. Thank you!!

**Comment by ravisriv** [comment]
For all,
Here is a resolution of the issues I was having regarding SSL:

1. You may not be able to setup the new Relay Server without Cloudflare. It just did not work for me after several tries.

2. You'll also need to change Cloudflare default configuration.

3. Make sure that you create a Cloudflare API token (Go into your Cloudflare profile and click on API tokens at the top) that has got read/create permissions on all resources. (It may work with less permissions but I did not try that.)

4. From Cloudflare dashboard, select the domain/server on which you are setting up the relay server and click on SSL/TLS icon at the top. Set SSL/TLS encryption mode to FULL (strict). Next click on Network icon and turn off HTTP/3 (QUIC). Also, turn off Onion routing (you won't need it). Make sure HTTP/2 and Websockests are on.

That's all to get the SSL/TLS configuration working.

I'm closing this issue now.

**Comment by yianding** [comment]
# wget https://ws.hayek.link
--2021-09-05 22:43:29--  https://ws.hayek.link/
Resolving ws.hayek.link (ws.hayek.link)... 104.21.85.36, 172.67.201.227, 2606:4700:3030::6815:5524, ...
Connecting to ws.hayek.link (ws.hayek.link)|104.21.85.36|:443... connected.
HTTP request sent, awaiting response... 525
2021-09-05 22:43:29 ERROR 525: (no description).
