### ISSUE TITLE
walletconnect.org & its subdomains are registry are down

### ISSUE THREAD

**Issue by imaksp** [WalletConnect/walletconnect-monorepo#577]
Hello, it seems walletconnect.org site is down currently 
also checked here:
https://www.isitdownrightnow.com/walletconnect.org.html

**Comment by jamesmorgan** [comment]
Ye seems to be broken for us to, none of our apps which use wallet cannot work - all fail due to DNS/outage issues from the look of it.

**Comment by lobotomoe** [comment]
Yeah, we are have this issue too.

**Comment by Simon0x** [comment]
Yes this seems to be an issue with the DNS records.
It seems to work fine in some parts of the world. 
https://www.whatsmydns.net/#A/walletconnect.org

**Comment by imaksp** [comment]
It is working now closing.
