### ISSUE TITLE
Local tests aren't successfully running - "make dev" possibly not deploying containers correctly

### ISSUE THREAD

**Issue by jiajames** [WalletConnect/walletconnect-monorepo#578]
I've been having issues running local tests on both my relay server and client (`make test-relay` and `make test-client`). 

All my tests are failing to connect to my local docker contains. For instance: `Error: connect ECONNREFUSED 127.0.0.1:5555`, and `Error: Unavailable WS RPC url at ws://localhost:5555`.

I know these errors are due to nothing running on port `5555` (based on `lsof -i:5555`), but I can't seem to figure out how to get my relay server to point towards this port. For context, I have ran `make dev` with no changes to the repo's master branch (v2.0).

Is this a problem on my local dev box, or in the master branch?

These findings are on my Macbook (Intel) running macOS 11.4.

**Comment by jaysonmald35** [comment]
Thanks

**Comment by 6thpath** [comment]
Having the same issue, any update on this?

**Comment by Quantmatic** [comment]
+1

**Comment by finessevanes** [comment]
@jiajames @6thpath @Quantmatic is this still an issue?
