### ISSUE TITLE
how to get result in approveRequest 

### ISSUE THREAD

**Issue by imhuy** [WalletConnect/walletconnect-monorepo#586]

**Comment by imhuy** [comment]
connector.approveRequest({
                    id: payload.id,
                    result: "xxxxxxxxxxxxxx"
                })
   Can someone tell me where result value is obtained? please

**Comment by artureg** [comment]
The same question. there is no information what should be stored in result:any 
@imhuy did you find solution?

**Comment by suyhuai** [comment]
https://pub.dev/packages/wallet_connect
I found the answer here, its a dart sdk doc. From number 9 point.
@imhuy @artureg

**Comment by finessevanes** [comment]
Did `signedDataAsHex` work for you @artureg @imhuy?
