### ISSUE TITLE
No events fired on send() method

### ISSUE THREAD

**Issue by bralemili** [WalletConnect/walletconnect-monorepo#590]
Using send() method on eth contract triggers the transaction dialog on WalletConnect on TrustWallet Android, but it does not give any event feedback (receipt or  error...) after accepting it.
Sometimes it returns txHash on transactionHash event

Also, if a user clicks the back icon on tx popup (as reject) it would not provide any feedback either.

Web3 1.5.1
@walletconnect/web3-provider 1.6.4

Any clue?

MetaMask with same code fires all events.

```
someContract.methods.someMethod().send(options)
            .on('receipt', function (receipt) {
                console.log(receipt)
            })
            .on('transactionHash', function (txHash) {
                console.log(txHash)
            })
            .on('error', function (error) {
                console.log(error)
              
            })
```

**Comment by bralemili** [comment]
After trying a few versions of Web3, version 1.2.11 is showing the callbacks now.
Hope it helps someone

**Comment by hoductrong** [comment]
Any update for this issues? Version 1.2.11 not working for me....

**Comment by finessevanes** [comment]
@bralemili @hoductrong is this still an issue?
