### ISSUE TITLE
enoent undefined ls-remote -h -t https://github.com/ethereumjs/ethereumjs-abi.git

### ISSUE THREAD

**Issue by fizyliftingdrnks** [WalletConnect/walletconnect-monorepo#592]
Error on "npm -i @walletconnect/web3-provider".  Error listed in title.

**Comment by YoungNK** [comment]
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/ethereumjs/ethereumjs-abi.git
Output:
fatal: unable to access 'https://github.com/ethereumjs/ethereu

**Comment by scryptoking** [comment]
Having the same issue when trying to install `@walletconnect/web3-provider`

**Comment by jamesmorgan** [comment]
Any ideas on this, also seeing it lots today and is failing some of out builds. Anyone know a solution?

**Comment by akivanc88** [comment]
same issue here too

Edit: actually I was running `sudo yarn install` when I saw this error.
But, when I run `yarn install` i.e. no `sudo`  then I don't see this problem

**Comment by finessevanes** [comment]
Running `yarn add @walletconnect/web3-provider` without any issues.
