### ISSUE TITLE
A bunch of Unauthorized pairing update request in console

### ISSUE THREAD

**Issue by GHChrisSu** [WalletConnect/walletconnect-monorepo#596]
It appears sometime, and I don't know specific reason for this
Not affect functionality 
Maybe I could get some help

![image](https://user-images.githubusercontent.com/13779988/131336851-3d3750e1-ccdc-4070-9b04-58af3b4a17b8.png)

**Comment by matthewcarlreetz** [comment]
I'm seeing this when using `'@walletconnect/client'` on React Native as soon as I call `WalletConnectClient.init`.

**Comment by matthewcarlreetz** [comment]
Are there any v2 docs for React Native? I'm wondering if I'm not killing sessions properly.

**Comment by GHChrisSu** [comment]
RN should be same to react, maybe check the example in repo?

**Comment by bkrem** [comment]
Thanks for the original report of this @GHChrisSu 🙏 

I'm going to close this and forward further discussion to #987 since investigation has already started there, to avoid duplication and parallel discussions on this issue.
