### ISSUE TITLE
Modal is useless in portrait orientation / on small screens

### ISSUE THREAD

**Issue by ai-slave** [WalletConnect/walletconnect-monorepo#597]
![image](https://user-images.githubusercontent.com/6696080/131663374-a9b3b285-290f-4404-997d-97b474163495.png)
![image](https://user-images.githubusercontent.com/6696080/131663351-38ab924c-79d4-4fd2-8928-24210dc70a6a.png)
No pagination is visible, QR code can't be scanned.

I can work on this issue, if this repo is still active and used by other parties.

**Comment by ai-slave** [comment]
Just fixed similar issue for ethereum.org. But this repo seems dead?

**Comment by finessevanes** [comment]
This issue has been fixed. 
<img width="575" alt="image" src="https://user-images.githubusercontent.com/44731696/209050782-85d48c89-8ebb-453c-ba20-3d8f2884c45c.png">
