### ISSUE TITLE
Pagination buttons are too close to each other

### ISSUE THREAD

**Issue by ai-slave** [WalletConnect/walletconnect-monorepo#598]
Before: you can easily misclick them with your thumb.
![image](https://user-images.githubusercontent.com/6696080/131669211-3d1e770e-acfe-4422-8549-ee0ebef88c9e.png)

After: you're happy since you can choose the right page.
![image](https://user-images.githubusercontent.com/6696080/131669229-ee9c07b6-40be-4299-8491-3661d8a63cf3.png)

I can implement this if it's still a working project.

**Comment by finessevanes** [comment]
Web3Modal v1 has been deprecated
