### ISSUE TITLE
walletconnect_caddy 2.4.3 image has an error

### ISSUE THREAD

**Issue by ravisriv** [WalletConnect/walletconnect-monorepo#600]
Hi @sbc64  - The latest caddyserver image (walletconnect_caddy) 2.4.3 that you uploaded on the Docker hub is giving the following error:

"run: reading config file: open /config/Caddyfile: no such file or directory"

Would deeply appreciate if you could please look into this. Thank you.

**Comment by ravisriv** [comment]
Two solutions:
Either change ops/docker-compose.yml to put Caddyfile in the right location ./Caddyfile:/config/Caddyfile 
or fix the walletconnect_caddy docker command line in the JSON file so that it is pointing at the right location. That should do it.

**Comment by sbc64** [comment]
Does `master` work for you now? https://github.com/WalletConnect/walletconnect-monorepo/commit/bafd2de7c1c8fb76809f90fd7694629cc1344a45

https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/ops/docker-compose.yml#L26

**Comment by Amencee** [comment]
> Two solutions: Either change ops/docker-compose.yml to put Caddyfile in the right location ./Caddyfile:/config/Caddyfile or fix the walletconnect_caddy docker command line in the JSON file so that it is pointing at the right location. That should do it.

Hi,do you know how to run  walletconnect/caddy:v2.4.3 image. I want to make deploy but I don't know how deal with caddy

**Comment by finessevanes** [comment]
@Ambince @ravisriv is this still an issue?
