### ISSUE TITLE
Send transaction with BNB using Trust Wallet.

### ISSUE THREAD

**Issue by developer-brightsoft** [WalletConnect/walletconnect-monorepo#601]
How can I send a transaction with BNB using Trust Wallet?

I want `ASSET` here to be BNB.

![Screenshot_2021-09-14-10-01-47-51_08800057d42e3b72e31ae4fd4c41ba57](https://user-images.githubusercontent.com/54013631/133187960-71bff0b7-bb5d-4dd5-abb6-316ec1122103.jpg)

I tried `updateSession` and added `common: {
        customChain: {
          name: "BNB",
          networkId: 56,
          chainId: 56,
        },
      }` to transaction data but it didn't work for me

` connector.updateSession({
      chainId: 56,
      networkId: 56,
      accounts: session.accounts,
      rpcUrl: "https://bsc-dataseed.binance.org/",
    });`

**Comment by finessevanes** [comment]
@developer-brightsoft are you still having an issue?
