### ISSUE TITLE
Can't get the QR modal to show after closing it once

### ISSUE THREAD

**Issue by Flawe** [WalletConnect/walletconnect-monorepo#604]
If I run `await provider.enable()` but then close the modal so it trigger the promise error, running `await provider.enable()` a second time doesn't show the QR modal again (the promise never returns). What's the best way to reset the state so the QR modal shows every time provider.enable() is called if the modal is closed?

**Comment by alona-daphna** [comment]
Did you launch the app on a mobile device? When I do `await provider.enable( )` it doesn't do anything. Can you perhaps share with me your code so far?

**Comment by hammadtariq98** [comment]
Still facing same issue here 
`
export const provider = new WalletConnectProvider({
    bridge: "https://bridge.walletconnect.org",
    chainId:[80001],
    network: "mumbai",
    rpc: {
        80001: "https://rpc-mumbai.maticvigil.com",
        // 80001: "https://matic-mumbai.chainstacklabs.com",
    },
    qrcode: true,
    qrcodeModalOptions: {
        mobileLinks: [
          "metamask",
          "trust",
        ]
    }
})
await provider.enable;
`

**Comment by Wathekkhlifi** [comment]
I found a solution ( I don't know if it is the best way ) which is to capture when user close the modal with catch() and re create the provider object,
this is an example code using react


```
const [myProvider, setMyProvider] = useState(
    new WalletConnectProvider({....... your settings   .......})
    )
const connectBTN = () => {
    myProvider
         .enable()
         .then(() => console.log("modal showed"))
         .catch((err) => {
            setMyProvider(
               new WalletConnectProvider({... your settings .... })
            );
         });
}
```

**Comment by finessevanes** [comment]
Hey, is this still an issue? @Flawe @Wathekkhlifi?
