### ISSUE TITLE
Connect to special wallet (MetaMask) instead of select from a list

### ISSUE THREAD

**Issue by huyta** [WalletConnect/walletconnect-monorepo#611]
Hello All,

Just wonder if I can connect to MetaMask with one click instead of select it from the popup list?
Note: using react-native-dapp

Thanks,
Huy

**Comment by Sirzs** [comment]
> Hello All,
> 
> Just wonder if I can connect to MetaMask with one click instead of select it from the popup list? Note: using react-native-dapp
> 
> Thanks, Huy

I have the same question

**Comment by raajnadar-cb** [comment]
Same question +1

**Comment by finessevanes** [comment]
Has this been resolved? @huyta @Sirzs @raajnadar-cb
