### ISSUE TITLE
Event chainChanged not triggered until account is changed

### ISSUE THREAD

**Issue by syedMohib44** [WalletConnect/walletconnect-monorepo#612]
Hi.. There is an issue with events I believe its stucking somewhere as when I signed to my webapp and after I change my chain it doens't trigger chainChanged event for mobile to change the chain I have to switch account which trigger both events the chainChanged and accountChanged. I don't have much for providing visuals but you can test it with these steps 
Please take this application for a test and try to connect with walletconnect [https://web3modal.com/](https://web3modal.com/)
Step 1: Login with metamask mobile via walletconnect.
Step 2: After siging change your chain you will not see the chain id changed on web app.

<img width="415" alt="Screen Shot 2021-09-27 at 11 19 30 AM" src="https://user-images.githubusercontent.com/36672373/134855279-674d40df-022a-43c4-9158-6015b7d444e9.png">

**Comment by nissoh** [comment]
stumbling upon the same issue ^^

**Comment by syedMohib44** [comment]
> stumbling upon the same issue ^^

Gone through their code but couldn't do much as it will take some time but the issue might be promise queue which stucks on account change really wierd.

**Comment by Jacob1248** [comment]
Im getting the same issue.

**Comment by syedMohib44** [comment]
@Jacob1248 I believe they will now focus on v2 which is still far from good but stay in touch with them via discord

**Comment by finessevanes** [comment]
Is this still an issue?
