### ISSUE TITLE
After I run make dev, I checked the log and found "Unavailable HTTP RPC url at http://waku.1:8545"

### ISSUE THREAD

**Issue by mccok** [WalletConnect/walletconnect-monorepo#614]
#  make relay-logs
[2021-09-29 09:21:41.632 +0000] ERROR:
    Provider Error: "Unavailable HTTP RPC url at http://waku.1:8545"
    context: "relay/network"
[2021-09-29 09:21:43.638 +0000] ERROR:
    Provider Error: "Unavailable HTTP RPC url at http://waku.1:8545"
    context: "relay/network"
[2021-09-29 09:21:45.633 +0000] ERROR:
    Provider Error: "Unavailable HTTP RPC url at http://waku.1:8545"
    context: "relay/network"
[2021-09-29 09:21:47.633 +0000] ERROR:
    Provider Error: "Unavailable HTTP RPC url at http://waku.1:8545"
    context: "relay/network"
[2021-09-29 09:21:49.633 +0000] ERROR:
    Provider Error: "Unavailable HTTP RPC url at http://waku.1:8545"
    context: "relay/network"
[2021-09-29 09:21:51.634 +0000] ERROR:
    Provider Error: "Unavailable HTTP RPC url at http://waku.1:8545"
    context: "relay/network"

And localhost is not listening on port 5555
I cannot take any next steps. Can someone help me?
Hot to use that？There is no detailed documentation and information for me to run and solve the problem

**Comment by finessevanes** [comment]
Is this still an issue?
