### ISSUE TITLE
When I was make dev on v2 beta.18 OOM happened

### ISSUE THREAD

**Issue by GHChrisSu** [WalletConnect/walletconnect-monorepo#615]
I use the m1 mac for run make dev command, and docker shows out of memory
whole stack is below

```
sed: setup: No such file or directory
mkdir -p build
mkdir -p .makeFlags
MAKE: Done with nix-volume

docker run --name builder --rm -v nix-store:/nix -v /Users/suhao/github/walletconnect-monorepo:/src -w /src nixos/nix nix-shell -p bash --run "nix-build --attr relayDeps"
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
GC Warning: Failed to expand heap by 402653184 bytes
GC Warning: Failed to expand heap by 262144 bytes
GC Warning: Failed to expand heap by 262144 bytes
GC Warning: Out of Memory! Heap size: 0 MiB. Returning NULL!
error: out of memory
make: *** [build-relay-deps] Error 1
```

**Comment by sbc64** [comment]
So this is interesting. The container used for the build pipeline and the build tool (`nix`) is `amd64`. I don't know how to solve the container architecture mismatch.

The `Makefile` detects whether you have the build tool installed. So if you have the binary `nix` installed on your M1 Mac you can probably get around the build container and use `nix` directly.

If you want try installing `nix` from https://nixos.org, then run the rule `make dev`

**Comment by GHChrisSu** [comment]
After I installed the nix, then run the `make dev`. Another error show up.

```
exec.c:336:16: error: variable has incomplete type 'struct stat64'

expand.c:1285:16: error: variable has incomplete type 'struct stat64'
```

Refer to https://trac.macports.org/ticket/62853, looks like M1 Mac removed the stat64, but exec.c and expand.c are not in project, so I don't know how to fix

**Comment by finessevanes** [comment]
@GHChrisSu are you still having issues?
