### ISSUE TITLE
make dev command not found

### ISSUE THREAD

**Issue by Amencee** [WalletConnect/walletconnect-monorepo#616]
version:2.0
hash: 7978251de8626937c3783e3d244750a79e2277f8 (HEAD -> v2.0, tag: 2.0.0-beta.18, origin/v2.0, origin/HEAD)
error:
docker run --name builder --rm -v nix-store:/nix -v /application/walletconnect/walletconnect-monorepo:/src -w /src nixos/nix nix-shell -p bash --run "-nix-build ./ops/waku-docker.nix --argstr wakuVersionTag v0.5.1 --argstr nixNimRepoSha256 108l12f7qyjb0rkzl3hd585s311ic0a9c8iqb0yrncbp99g6wmi5 && cp -r -f -L result build/build-img-waku && rm -rf result"
/tmp/nix-shell-1-0/rc: line 1: -nix-build: command not found
make: *** [Makefile:132: build-img-waku] Error 127
root@localhost:/application/walletconnect/walletconnect-monorepo# git log

**Comment by sbc64** [comment]
Thanks for the report. If you implement this fix: https://github.com/WalletConnect-Labs/walletconnect-v2-monorepo/commit/3a7c469a6938b8f2b214e0d828533206d9ee72bb

It will likely work.

**Comment by Amencee** [comment]
linux version:Linux version 4.19.0-16-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6))

docker version:Docker version 20.10.7, build f0df350

exe 'make dev',error log:


            /tmp/nix-build-nim-waku-0.5.1.drv-0/source/waku/v2/protocol/waku_relay.nim(66, 8) Warning: use {.base.} for base methods; baseless methods are deprecated [UseBase]
            /tmp/nix-build-nim-waku-0.5.1.drv-0/source/waku/v2/protocol/waku_relay.nim(81, 8) Warning: use {.base.} for base methods; baseless methods are deprecated [UseBase]
            /tmp/nix-build-nim-waku-0.5.1.drv-0/source/waku/v2/protocol/waku_relay.nim(87, 8) Warning: use {.base.} for base methods; baseless methods are deprecated [UseBase]
            /tmp/nix-build-nim-waku-0.5.1.drv-0/source/waku/whisper/whisper_types.nim(593, 11) Warning: Deprecated since v1.4; it was more confusing than useful, use `[]=`; add is deprecated [Deprecated]
            /tmp/nix-build-nim-waku-0.5.1.drv-0/source/waku/v2/node/wakunode2.nim(867, 24) template/generic instantiation of `load` from here
            /tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/nim-confutils/confutils.nim(787, 23) Warning: Cannot prove that 'result' is initialized. This will become a compile time error in the future. [ProveInit]
            Error: execution of an external program failed: 'gcc -c  -w -fmax-errors=3 -pthread -I/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/nim-libbacktrace -I/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/nim-libbacktrace/install/usr/include -I/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/nim-secp256k1/secp256k1_wrapper -I/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1 -I/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1/src -DHAVE_CONFIG_H -DHAVE_BUILTIN_EXPECT -I/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/nim-bearssl/bearssl/csources/src -I/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/nim-bearssl/bearssl/csources/inc -I/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/nim-bearssl/bearssl/csources/tools -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1  -DBR_amd64=1 -DBR_INT128=1 -I/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/nim-bearssl/bearssl/certs -I/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/nim-zlib/zlib/csources -I/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/nim-nat-traversal/vendor/miniupnp/miniupnpc -I/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/nim-nat-traversal/vendor/libnatpmp-upstream -DENABLE_STRNATPMPERR -march=native -O3 -fno-strict-aliasing -fno-ident   -I/nix/store/785207l5p3x7yc0lg3jgjbc4pqwgwvcf-nim-unwrapped-1.4.8/nim/lib -I/tmp/nix-build-nim-waku-0.5.1.drv-0/source/waku/v2/node -o nimcache/release/wakunode2/ec_p256_m31.c.o /tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/nim-bearssl/bearssl/csources/src/ec/ec_p256_m31.c'
            builder for '/nix/store/h5x9hi6fp3pk90g2g2w8birmlnkvg6rj-nim-waku-0.5.1.drv' failed with exit code 1
            cannot build derivation '/nix/store/g4js7hhpkf8qmqzj6cl5px3r7nzwm59i-closure.drv': 1 dependencies couldn't be built
            cannot build derivation '/nix/store/iicmrvhwpxn86cr3bgmpsj0rw7vs6va8-entry-script.sh.drv': 1 dependencies couldn't be built
            cannot build derivation '/nix/store/wrjfzmqyxpscnc1c6hmg2ixk7fhzbfpx-wakunode-customisation-layer.drv': 1 dependencies couldn't be built
            cannot build derivation '/nix/store/qlynxqky5jn4sx35j6fmsy5ns1qynh18-wakunode-conf.json.drv': 1 dependencies couldn't be built
            cannot build derivation '/nix/store/iy13grlxf89zvkhi91sr6b0ax45i7khc-stream-wakunode.drv': 1 dependencies couldn't be built
            cannot build derivation '/nix/store/axxc8jp16g0njmxg1c57c6iycnyw1fav-wakunode.tar.gz.drv': 1 dependencies couldn't be built
            error: build of '/nix/store/axxc8jp16g0njmxg1c57c6iycnyw1fav-wakunode.tar.gz.drv' failed
            make: *** [Makefile:132: build-img-waku] Error 100

**Comment by finessevanes** [comment]
@Ambince is this still an isue?
