### ISSUE TITLE
[React Native] @walletconnect/react-native-dapp can not find wallets on android 11. targetSdkVersion = 30

### ISSUE THREAD

**Issue by inuyashaaa** [WalletConnect/walletconnect-monorepo#618]
@walletconnect/react-native-dapp can not find wallets on android 11. targetSdkVersion = 30

**Comment by amaioru0** [comment]
I have the same issue

**Comment by goulart81** [comment]
I have the same issue, my phone has Android 10

**Comment by inuyashaaa** [comment]
@pedrouid Could you help to check it?. Google play store required targetSdkVersion=30, so we can not submit the app to the store if it is not fixed.

**Comment by amaioru0** [comment]
Hi sorry for the off topic @inuyashaaa I am wondering since you mentioned google play store, do you have any information regarding the policy around Ethereum mobile dapps? Like would they approve apps where you can sign in by signing a message, paying for gas to conduct operations within the app and how about revenue what if I would have a contract and users could benefit in the app from paying something through their mobile wallet?

**Comment by inuyashaaa** [comment]
@amaioru0 My app is the mobile version of this website: https://bunicorn.exchange. Which have swap, farm, NFT... feature and google play store is approved. I thinks dapps is easy to agree with by the google team.

**Comment by amaioru0** [comment]
@inuyashaaa , Hi there thanks so much for your reply. It's a relief to hear this~!

**Comment by Shazad0304** [comment]
if (!canOpenURL) {
                 Linking.openURL('https://walletconnect.org/wallets');
                 throw new Error('No wallets found.');
 }
           
 removing this from @walletconnect\react-native-dapp\dist\providers\WalletConnectProvider.js worked for me.

**Comment by AleeeKoi** [comment]
Using Android SDK >= 30 require to specify a configuration in the manifest, so the code reported by @Shazad0304 won't fail any more.

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example">
    [...]

    <queries>
      <intent>
          <action android:name="android.intent.action.VIEW" />
          <data android:scheme="http"/>
      </intent>
      <intent>
          <action android:name="android.intent.action.VIEW" />
          <data android:scheme="https"/>
      </intent>
    </queries>
</manifest>
```

**Comment by joshuacue** [comment]
My Solution that worked is when I created my own plugin, feel free to copy my solution, with expo prebuild, I was able to see the output of the AndroidManifest.xml, the built path is `android/app/src/main/AndroidManifest/xml`:

Then here is hows my plugin and affected files look like:

1. In project root, create a new file app.plugin.js file
```
const { withAndroidManifest } = require('@expo/config-plugins')

module.exports = function withMyCustomConfig(config) {
  return withAndroidManifest(config, async config => {
    // Modifiers can be async, but try to keep them fast.
    config.modResults = await setCustomConfigAsync(config, config.modResults);
    return config;
  });
};

// Splitting this function out of the mod makes it easier to test.
async function setCustomConfigAsync(
  config,
  androidManifest
){
  //this came from the original AndroidManifest.xml  name
  const myAppName = "com.xxx.xxx"
  const rest = androidManifest.manifest
  
  return {
    manifest: {
      ...rest,
      $: {
        "xmlns:android": "http://schemas.android.com/apk/res/android",
        "package": myAppName
      },
      queries:
        {
          intent:[{
            action: { 
              $: {
                "android:name": "android.intent.action.VIEW",
              },
            },
            data: {
              $: {
                "android:scheme": "http"
              }
            }
          },
          {
            action: { 
              $: {
                "android:name": "android.intent.action.VIEW",
              },
            },
            data: {
              $: {
                "android:scheme": "https"
              }
            }
          }
        ],
      }
    }
  };
}
```

2. add this file as plugins inside app.json:
```
  expo: {
     "plugins": ["./app.plugin"], //this line
  }
```

3. and this is my metro.config.js
```
const { getDefaultConfig } = require("metro-config");
const expoMetro = require("@expo/metro-config")
const { resolver: defaultResolver } = getDefaultConfig.getDefaultValues();
module.exports = {
  ...expoMetro,
  resolver: {
    ...expoMetro.resolver,
    ...defaultResolver,
    extraNodeModules: require("expo-crypto-polyfills"),
    sourceExts: [...defaultResolver.sourceExts, "cjs"],
  }
}
``` 

4. and finally do `expo prebuild`.

Note: Delete android and is before running another `expo prebuild`.

**Comment by therealharpaljadeja** [comment]
![image](https://user-images.githubusercontent.com/38040789/165918291-e06300a3-0632-487b-a06c-73be8eab6849.png)

`canOpenURL()` returns false for Android 11.

**Comment by finessevanes** [comment]
Is this still an issue?
