### ISSUE TITLE
Got a Unhandled Rejection error when open a local network page within mobile browser

### ISSUE THREAD

**Issue by iamgamelover** [WalletConnect/walletconnect-monorepo#622]
ENV: iOS 15.0.1
BROWSER: Safari, Chrome,  Firefox

Opened a local page in the mobile browser on 192.168.0.227:3000, and running the below code

```
//  Create WalletConnect Provider
const provider = new WalletConnectProvider({
  infuraId: "27e484dcd9e3efcfd25a83a78777cdf1",
});

//  Enable session (triggers QR Code modal)
await provider.enable();
```

Then got an error this. 

![image](https://user-images.githubusercontent.com/787620/136641426-645159bc-6a46-469f-aa6c-8d391292771d.png)

**Comment by HemaBabyDoge** [comment]
Hello, @iamgamelover Did you ever find a fix for this?

**Comment by R4k4210** [comment]
Run the app with HTTPS=true yarn start.
That should work.

**Comment by finessevanes** [comment]
Is this still an issue?
