### ISSUE TITLE
Custom RPC wants always to work with mainnet of Ethereum

### ISSUE THREAD

**Issue by 4skinSkywalker** [WalletConnect/walletconnect-monorepo#624]
Hi guys,

I'm trying to connect from TrustWallet with your scan feature on the Binance Smart Chain.

in your docs you have:
```js
import WalletConnectProvider from "@walletconnect/web3-provider";
//  Create WalletConnect Provider
const provider = new WalletConnectProvider({
    rpc: {
        1: "https://mainnet.mycustomnode.com",    
        3: "https://ropsten.mycustomnode.com",    
        100: "https://dai.poa.network",    
        // ...
    },
});
//  Enable session (triggers QR Code modal)
await provider.enable();
```

I've changed the code to just use Binance Mainnet, like follows:
```js
//  Create WalletConnect Provider
const provider = new WalletConnectProvider({
    rpc: {
        56: "https://bsc-dataseed.binance.org/"
    },
});
```

It looks like I can map whatever but if I only map Binance Mainnet (or really whatever except Ethereum Mainnet) it gives me the following error:
![image](https://user-images.githubusercontent.com/17194393/137810476-2a4497b1-03fa-418a-96e4-eb4efd553040.png)

It looks like it's forcing me to connect to Ethereum Mainnet for some reason, and I think it's complaining for the missing Infura API key.

I don't need to pass many RPCs, I would like to pass it just one and connect with that, how can I do it?

Thanks,
Fredo

**Comment by 4skinSkywalker** [comment]
I've fixed this by not only  providing the mapping but also the chainId:
```js
// Create WalletConnect Provider
let provider = new pkg({
    rpc: { ...RPCMapping },
    chainId
});
```
You docs should contain that too... I lost time by trying to make it work!

**Comment by developerfred** [comment]
@4skinSkywalker look -> https://github.com/sushiswap/sushiswap-interface/blob/91c32bc6da45c9d74f6c15afc6010921fd4092d9/src/connectors/index.ts

**Comment by olegabr** [comment]
Suffering from the same issue in the https://wordpress.org/plugins/ether-and-erc20-tokens-woocommerce-payment-gateway/ plugin. The solution suggested by @developerfred seems to work. Thank you Fred!
