### ISSUE TITLE
While Initiating  WalletConnect client with the relay server we are getting this error (react native client) wallet

### ISSUE THREAD

**Issue by rkrapidinnovation** [WalletConnect/walletconnect-monorepo#627]
const client = await WalletConnectClient.init({
          controller: true,
          relayProvider: 'wss://relay.walletconnect.com',
          metadata: {
            name: 'Test Wallet',
            description: 'Test Wallet',
            url: '#',
            icons: ['https://walletconnect.com/walletconnect-logo.png'],
          },
          storageOptions: {
            asyncStorage: AsyncStorage,
          },
        });
        console.log({client});

ExceptionsManager.js:179 TypeError: Cannot read property 'message' of undefined
    at parseConnectionError (error.js:50)
    at WsConnection.parseError (ws.js:117)
    at EventTarget.socket.onerror (ws.js:81)
    at EventTarget.dispatchEvent (event-target-shim.js:818)
    at WebSocket.js:260
    at RCTDeviceEventEmitter.emit (EventEmitter.js:189)
    at MessageQueue.__callFunction (MessageQueue.js:416)
    at MessageQueue.js:109
    at MessageQueue.__guard (MessageQueue.js:364)
    at MessageQueue.callFunctionReturnFlushedQueue (MessageQueue.js:108)

**Comment by Sirzs** [comment]
You are missing the apikey

**Comment by Sirzs** [comment]
I have another problem. Can you help me? #628

**Comment by ounie** [comment]
> You are missing the apikey

Where do you place the API key?

**Comment by mrosendin** [comment]
@ounie I think at initialization like

```javascript
WalletConnectClient.init({
  apiKey: "<apikey>",
  ...
})
```

**Comment by JulienKode** [comment]
How do we get the API Key ? 
I have the project id but not the API key on the dashboard

**Comment by buikhoa40** [comment]
Same issue here.

**Comment by finessevanes** [comment]
Is this still an issue?

**Comment by aydil45** [comment]
I'm also facing the same issue on the react native platform. Any solution?

**Code**
```
  async function createClient() {
    try {
      const signClientRes: any = await SignClient.init({
        projectId: '.............',
        relayUrl: 'wss://relay.walletconnect.com',
        metadata: {
          name: 'React Native Wallet',
          description: 'React Native Wallet for WalletConnect',
          url: 'https://walletconnect.com/',
          icons: ['https://avatars.githubusercontent.com/u/37784886'],
        },
      });
      console.log('RES => ', signClientRes);
    } catch (e) {
      console.log('Error ==> ', e);
    }
  }
```

**Error**
[Error: WebSocket connection failed for URL: wss://relay.walletconnect.com?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtvY1V3ZWI4czJzM2h6YVhmVEhUM3N0OGZvcmZvTE5idXJWaFRBbzZVRFFCWSIsInN1YiI6ImQ5MjJkYzU5ZTMwZjNhNWM5YWNiMjRjY2RlMDc3MmI5ODgyYzlhMzYzZGE4N2IzZjBjODUwMGRlYWUyNzMwMTQiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTY3NTk2MjYyMywiZXhwIjoxNjc2MDQ5MDIzfQ.J8755wsFAA2nxI-6xA9zLd0YoazwKlOezypeZISWKje0Xgc96EfsbnnWXbKYnhrvRHWBF11c-uhXSmyoPbiTBA&projectId=.............&ua=wc-2%2Fjs-2.4.0%2Funknown-%2Freact-native]

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
