### ISSUE TITLE
How do I use version 2.0 correctly in React Native

### ISSUE THREAD

**Issue by Sirzs** [WalletConnect/walletconnect-monorepo#628]
```
client.on(
    CLIENT_EVENTS.pairing.proposal,
    async (proposal: PairingTypes.Proposal) => {
        // uri should be shared with the Wallet either through QR Code scanning or mobile deep linking
        const { uri } = proposal.signal.params;
        Linking.openURL(uri)
    }
);
const session = await client.connect({
	permissions: {
		blockchain: {
			chains: ["eip155:1"],
		},
		jsonrpc: {
			methods: ["eth_sendTransaction", "personal_sign", "eth_signTypedData"],
		},
	},
});
```

The Metamask app was opened through the openURL method, But then nothing happened
I can not get the session

**Comment by Sirzs** [comment]
Can someone please help me? Thank you

**Comment by Sirzs** [comment]
@pedrouid Sorry for the direct message. Can you give me some guidance? I have no other choice

**Comment by raajnadar-cb** [comment]
+1 Even I am searching for this can someone help?

**Comment by raajnadar-cb** [comment]
It seems the docs is complete

`handleSessionUserApproval(approved, proposal); // described in the step 4`

**Comment by raajnadar-cb** [comment]
Try adding `logger: 'debug'` in you init method to find what is happening behind the scenes, And can you share your code? I am trying to open metamask app on a button click but unable to do it.

**Comment by alona-daphna** [comment]
@raajnadar-cb have you implemeted the button yet? If so, can you share your code?

**Comment by finessevanes** [comment]
@alona-daphna @Sirzs is this still an issue?
