### ISSUE TITLE
How to connect to metamask?

### ISSUE THREAD

**Issue by winston0410** [WalletConnect/walletconnect-monorepo#631]
I am using this package, and I cannot find any option for adding metamask into the wallet list. How can I do that?

https://www.npmjs.com/package/walletconnect

**Comment by lunnaholy** [comment]
https://medium.com/metamask/no-longer-injecting-web3-js-4a899ad6e59e

> In early 2021, MetaMask will no longer inject the web3.js API. You can still bring your own web3.js or similar library and use it with MetaMask. We will simply stop injecting a particular version of web3.js for you.

This means that to access metamask you must use a third-party library: web3 or ethers.js

**Comment by lunnaholy** [comment]
If you want a combined authorization option between WalletConnect and MetaMask, you can use [this](https://codepen.io/polats/embed/dyGXPOz)

**Comment by finessevanes** [comment]
@winston0410 are you still have an issue?
