### ISSUE TITLE
build beta.19 error happened

### ISSUE THREAD

**Issue by GHChrisSu** [WalletConnect/walletconnect-monorepo#632]
sed: can't read setup: No such file or directory
mkdir -p build
mkdir -p .makeFlags
MAKE: Done with nix-volume

docker run --name builder --rm -v nix-store:/nix -v /application/walletconnect-dev:/src -w /src nixos/nix nix-shell -p bash --run "nix-build --attr relayDeps"
/nix/store/7vif694iqh6qgiwbriab3zqiqawmld92-node-dependencies-_at_walletconnect_slash_relay-server-1.0.1
MAKE: Done with build-relay-deps

docker run --name builder --rm -v nix-store:/nix -v /application/walletconnect-dev:/src -w /src nixos/nix nix-shell -p bash --run "nix-build --attr relayApp"
/nix/store/d9wc5cw3sn0ppixvrahnr7hbqaiy28wp-_at_walletconnect_slash_relay-server-v1.0.1
MAKE: Done with build-relay-app

docker run --name builder --rm -v nix-store:/nix -v /application/walletconnect-dev:/src -w /src nixos/nix nix-shell -p bash --run "nix-build --attr relay --argstr githash 468148cb && cp -r -f -L result build/build-img-relay && rm -rf result"
/nix/store/8gnan4gcpr9g6382x71fpmr11adzypzn-relay-server.tar.gz
docker load -i build/build-img-relay | awk '{print $NF}' | tee build/build-img-relay-img
walletconnect/relay-server:v1.0.1
MAKE: Done with build-img-relay

docker run --name builder --rm -v nix-store:/nix -v /application/walletconnect-dev:/src -w /src nixos/nix nix-shell -p bash --run "nix-build https://github.com/WalletConnect-Labs/nix-caddy/archive/v2.4.3.tar.gz --attr docker && cp -r -f -L result build/build-img-caddy && rm -rf result"
unpacking 'https://github.com/WalletConnect-Labs/nix-caddy/archive/v2.4.3.tar.gz'...
/nix/store/wzn50grhwxigm5py1iqy0g6wzmy38jzz-caddy.tar.gz
docker load -i build/build-img-caddy | awk '{print $NF}' | tee build/build-img-caddy-img
caddy:4i9fk7b050yarq79086cy8k5m9f3079s
MAKE: Done with build-img-caddy

docker run --name builder --rm -v nix-store:/nix -v /application/walletconnect-dev:/src -w /src nixos/nix nix-shell -p bash --run "nix-build ./ops/waku-docker.nix --argstr wakuVersionTag v0.5.1 --argstr nixNimRepoSha256 0k55hw1wqcyrpf9cxchhxdb92p75mmskkpvfn1paivl1r38pyb4a && cp -r -f -L result build/build-img-waku && rm -rf result"
these derivations will be built:
  /nix/store/h5x9hi6fp3pk90g2g2w8birmlnkvg6rj-nim-waku-0.5.1.drv
  /nix/store/iicmrvhwpxn86cr3bgmpsj0rw7vs6va8-entry-script.sh.drv
  /nix/store/lxaj8qx8ryf82jabzbn9x7i4ddwqdvlr-wakunode-base.json.drv
  /nix/store/g4js7hhpkf8qmqzj6cl5px3r7nzwm59i-closure.drv
  /nix/store/865c590jh2i5dkqrjmmk03yf0rfbzzdk-closure-paths.drv
  /nix/store/wrjfzmqyxpscnc1c6hmg2ixk7fhzbfpx-wakunode-customisation-layer.drv
  /nix/store/qlynxqky5jn4sx35j6fmsy5ns1qynh18-wakunode-conf.json.drv
  /nix/store/iy13grlxf89zvkhi91sr6b0ax45i7khc-stream-wakunode.drv
  /nix/store/axxc8jp16g0njmxg1c57c6iycnyw1fav-wakunode.tar.gz.drv
building '/nix/store/h5x9hi6fp3pk90g2g2w8birmlnkvg6rj-nim-waku-0.5.1.drv'...
unpacking sources
unpacking source archive /nix/store/aprx2n83xgcwmimakvh8b3vxwhr8mxm7-source
source root is source
patching sources
configuring
fixing libtool script ./vendor/nim-libbacktrace/vendor/libbacktrace-upstream/ltmain.sh
no configure script, doing nothing
building
Building: install/usr/lib/libbacktrace.a
Building: install/usr/lib/libbacktracenim.a
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-eth-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-secp256k1-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-libp2p-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-stew-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nimbus-build-system-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-nat-traversal-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-libbacktrace-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-confutils-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-chronicles-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-faststreams-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-chronos-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-json-serialization-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-serialization-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nimcrypto-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-metrics-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-stint-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-json-rpc-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-http-utils-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/news-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-bearssl-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-sqlite3-abi-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-web3-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/rln-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-testutils-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-unittest2-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-websock-#head'
mkdir: created directory '/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/.nimble/pkgs/nim-zlib-#head'
/tmp/nix-build-nim-waku-0.5.1.drv-0/source/waku/v2/protocol/waku_relay.nim(66, 8) Warning: use {.base.} for base methods; baseless methods are deprecated [UseBase]
/tmp/nix-build-nim-waku-0.5.1.drv-0/source/waku/v2/protocol/waku_relay.nim(81, 8) Warning: use {.base.} for base methods; baseless methods are deprecated [UseBase]
/tmp/nix-build-nim-waku-0.5.1.drv-0/source/waku/v2/protocol/waku_relay.nim(87, 8) Warning: use {.base.} for base methods; baseless methods are deprecated [UseBase]
/tmp/nix-build-nim-waku-0.5.1.drv-0/source/waku/whisper/whisper_types.nim(593, 11) Warning: Deprecated since v1.4; it was more confusing than useful, use `[]=`; add is deprecated [Deprecated]
/tmp/nix-build-nim-waku-0.5.1.drv-0/source/waku/v2/node/wakunode2.nim(867, 24) template/generic instantiation of `load` from here
/tmp/nix-build-nim-waku-0.5.1.drv-0/source/vendor/nim-confutils/confutils.nim(787, 23) Warning: Cannot prove that 'result' is initialized. This will become a compile time error in the future. [ProveInit]
/nix/store/b39yxip6di5gq3q8513hfvmhfwz4yq77-stdenv-linux/setup: line 1342:  3431 Killed                  /nix/store/lm4yq6hybf4qn2gfsv8xacl5r8ysw4sp-x86_64-unknown-linux-gnu-nim-wrapper-1.4.8/bin/nim c --out:build/wakunode2 --debugger:native -d:chronicles_log_level=DEBUG --verbosity:0 --hints:off -d:release waku/v2/node/wakunode2.nim
builder for '/nix/store/h5x9hi6fp3pk90g2g2w8birmlnkvg6rj-nim-waku-0.5.1.drv' failed with exit code 137
cannot build derivation '/nix/store/g4js7hhpkf8qmqzj6cl5px3r7nzwm59i-closure.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/iicmrvhwpxn86cr3bgmpsj0rw7vs6va8-entry-script.sh.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/wrjfzmqyxpscnc1c6hmg2ixk7fhzbfpx-wakunode-customisation-layer.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/qlynxqky5jn4sx35j6fmsy5ns1qynh18-wakunode-conf.json.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/iy13grlxf89zvkhi91sr6b0ax45i7khc-stream-wakunode.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/axxc8jp16g0njmxg1c57c6iycnyw1fav-wakunode.tar.gz.drv': 1 dependencies couldn't be built
error: build of '/nix/store/axxc8jp16g0njmxg1c57c6iycnyw1fav-wakunode.tar.gz.drv' failed
make: *** [Makefile:132: build-img-waku] Error 100

**Comment by mohzourob** [comment]
@GHChrisSu Do u manage to fix this issue

**Comment by sbc64** [comment]
We have stopped supporting waku in this repository.

If you want to run the relay you can do so here: https://github.com/WalletConnect/relay
