### ISSUE TITLE
Session Update and Upgrade are not reflected in react app.

### ISSUE THREAD

**Issue by llbartekll** [WalletConnect/walletconnect-monorepo#635]
After updating (`wc_sessionUpdate`) or upgrading (`wc_sessionUpgrade`) session changes in permissions or accounts should reflected in react dapp.
note: js client is upgrading and updating correctly, just changes are not reflected in UI.

**Comment by finessevanes** [comment]
@llbartekll is this still an issue?

**Comment by llbartekll** [comment]
issue opened in ` Nov 4, 2021` I don't think so :D
