### ISSUE TITLE
Cannot handle approveRequest error

### ISSUE THREAD

**Issue by ilanolkies** [WalletConnect/walletconnect-monorepo#639]
https://github.com/WalletConnect/walletconnect-monorepo/blob/7aeb3fe5dd0ec6c8f52a5d19d1dc69246e0076be/packages/clients/core/src/index.ts#L760-L767

If you want to catch the error in `approveRequest` you cannot do it because `_send Response` is not returned.

**Comment by finessevanes** [comment]
@ilanolkies is this still an issue?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version

Thank you!
