### ISSUE TITLE
make[1]: *** [deploy] Error 1. |  this node is not a swarm manager.

### ISSUE THREAD

**Issue by Quantmatic** [WalletConnect/walletconnect-monorepo#642]
Seems that the caddy got built, any suggestions would be appreciated

`
caddy:4i9fk7b050yarq79086cy8k5m9f3079s
MAKE: Done with build-img-caddy

docker run --name builder --rm -v nix-store:/nix -v /Users/alpha/Documents/dapp/walletconnect-monorepo:/src -w /src nixos/nix nix-shell -p bash --run "nix-build ./ops/waku-docker.nix --argstr wakuVersionTag v0.5.1 --argstr nixNimRepoSha256 0k55hw1wqcyrpf9cxchhxdb92p75mmskkpvfn1paivl1r38pyb4a && cp -r -f -L result build/build-img-waku && rm -rf result"
/nix/store/614jqwxi9chddwhf6qa61629qf5ndvv2-wakunode.tar.gz
docker load -i build/build-img-waku | awk '{print $NF}' | tee build/build-img-waku-img
wakunode:rmxzg7d1wxz5cr1n4whxj8wbj2xq3d33
MAKE: Done with build-img-waku

touch .makeFlags/predeploy
bash ops/deploy.sh

Deploy command: docker stack deploy walletconnect -c ops/docker-compose.yml -c ops/docker-compose.prod.yml  -c ops/docker-compose.ci.yml

this node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again
make[1]: *** [deploy] Error 1
make: *** [dev] Error 2
`

**Comment by finessevanes** [comment]
Is this still an issue?
