### ISSUE TITLE
[React Native] Add acounts to account lsit manually

### ISSUE THREAD

**Issue by akinncar** [WalletConnect/walletconnect-monorepo#643]
Is it possible to add accounts to the account list returned from  connector.accounts?
I'm trying this but is not working:
```js
const connector = useWalletConnect();
connector.accounts = ['0x6C99A69537aA5F3A1e2d846b8b85573d46D45E45'];
```
or
```js
const connector = useWalletConnect();
connector.accounts(['0x6C99A69537aA5F3A1e2d846b8b85573d46D45E45'])
```

The usage is that I'm trying to use in a app on simulator on development instead of a physical device.

**Comment by finessevanes** [comment]
@akinncar is this still an issue?

**Comment by akinncar** [comment]
@finessevanes I did not try latest versions yet, but solved creating my own accounts array
we can re-open if I find the same problem on last versions
