### ISSUE TITLE
unable to trigger wallect connect using @walletconnect/web3-provider

### ISSUE THREAD

**Issue by Nitish157** [WalletConnect/walletconnect-monorepo#644]
I am also trying to use my smart contract function but I am getting an error.
Due to this QR Model is not triggering.
Could you please help it is important and urgent to be solved.
I am using "@walletconnect/web3-provider": "^1.6.6",

[Error: document is not defined in Window]
This error occurs when I try to use

await provider.enable()

**Comment by duonghanhbk** [comment]
Did you solve it? Could you show me the code if it doesn't solve yet?

**Comment by finessevanes** [comment]
@Nitish157 is this still an issue?
