### ISSUE TITLE
React-Native dapp auth issue?

### ISSUE THREAD

**Issue by nyousaf47** [WalletConnect/walletconnect-monorepo#645]
I am new to integrate WalletConnect in dapp. 
I created new app using [create-react-native-dapp](https://github.com/cawfree/create-react-native-dapp). I want to develop app and using Moralis backend. 
Followed this video. https://www.youtube.com/watch?v=FRilwynjW1c&ab_channel=MoralisWeb3 .

I run app on android and click on Authenticate Button and it showed modal with list of wallets. 
When i click on MetaMask, It open metamask , then open a browsers and 404 page and aut redirect to login page of wallet. 
I think something is wrong here.
`  if (Platform.OS === "android") {
       const canOpenURL = await Linking.canOpenURL(uri);
       if (!canOpenURL) {
          // Redirect the user to download a wallet.
          Linking.openURL("https://walletconnect.org/wallets");
          throw new Error("No wallets found.");
        }
        await Linking.openURL(uri);`
any one cal help in this issue?

**Comment by derekcsm** [comment]
Also having this issue, did you find a fix @nyousaf47 ?

**Comment by wiktrz** [comment]
Same issue... But not for all phones. It works fine on my all Iphones and on Mate 20 (android 10) but not on OnePlus Nord2 (android 11)

**Comment by finessevanes** [comment]
Is this still an issue? @wiktrz @derekcsm @nyousaf47
