### ISSUE TITLE
React-Native Android dApp issue with Metamask

### ISSUE THREAD

**Issue by jarrillaga** [WalletConnect/walletconnect-monorepo#648]
Hi All, we really need your help. 

I am using react-native-dapp ("^1.6.6") and I have some trouble when I try to connect with the wallet (metamask). In Android after select the Metamask Wallet from the modal, it redirects to the Metamask browser section with the following url: _https://walletconnect.com/wallets_. In iOS it's working as expected, Metamask displays the pop up to confirm the connection. 

Can somebody help me pls with this problem in Android?

**Comment by cichun** [comment]
Hi, 
had same problem, go to node_modules/@walletconnect/react-native-dapp/dist/providers/WalletConnectProvider.js

and comment lines # 25-28

```           
 if (!canOpenURL) {
                Linking.openURL('https://walletconnect.org/wallets');
                throw new Error('No wallets found.');
            }
```

A good idea is to use  [patch-package](https://github.com/ds300/patch-package) with patch
```
diff --git a/node_modules/@walletconnect/react-native-dapp/dist/providers/WalletConnectProvider.js b/node_modules/@walletconnect/react-native-dapp/dist/providers/WalletConnectProvider.js
index 190d3da..9d62beb 100644
--- a/node_modules/@walletconnect/react-native-dapp/dist/providers/WalletConnectProvider.js
+++ b/node_modules/@walletconnect/react-native-dapp/dist/providers/WalletConnectProvider.js
@@ -22,10 +22,11 @@ export default function WalletConnectProvider({ children, renderQrcodeModal: may
     const open = React.useCallback(async (uri, cb) => {
         if (Platform.OS === 'android') {
             const canOpenURL = await Linking.canOpenURL(uri);
-            if (!canOpenURL) {
-                Linking.openURL('https://walletconnect.org/wallets');
-                throw new Error('No wallets found.');
-            }
+            // if (!canOpenURL) {
+            //     Linking.openURL('https://walletconnect.org/wallets');
+            //     throw new Error('No wallets found.');
+            // }
             await Linking.openURL(uri);
         }
         setState({

```

**Comment by sssemil** [comment]
Same issue on my Android 11 device, but not on Android 10.

**Comment by Blackening999** [comment]
Same issue with Android 11

**Comment by w4-jake** [comment]
Same issue on my Android 11 AVD ... thankfully the workaround suggested by @cichun fixed the issue so thank you!
Are there any plans to fix the actual library though so there is no need to patch the package?

**Comment by therealharpaljadeja** [comment]
![image](https://user-images.githubusercontent.com/38040789/165918062-0c5dfbad-71cf-45cb-a829-ef47d64c216c.png)

From react native docs `canOpenURL()` returns false on Android 11

**Comment by finessevanes** [comment]
Is this still an issue?
