### ISSUE TITLE
MobileLinks when use web3-provider not working.

### ISSUE THREAD

**Issue by duonghanhbk** [WalletConnect/walletconnect-monorepo#652]
- I'm using **@walletconnect/web3-provider** (v1.6.6) with options **mobileLinks**, but Modal shows Qrcode instead of the list of wallets in my configs.
- Code below:
```
const provider = new WalletConnectProvider({
        rpc: {
            56: 'https://bsc-dataseed.binance.org/',
            97: 'https://data-seed-prebsc-1-s1.binance.org:8545/',
        },
        qrcodeModalOptions: {
            mobileLinks: ['metamask', 'trusk'],
        },
    });
    await provider.enable();
```
- Did I miss anything else?

**Comment by johnylawrence1987** [comment]
+1

Same issue here, `mobileLinks` not working on v1.8.0

**Comment by finessevanes** [comment]
@johnylawrence1987 @duonghanhbk  is this still an issue?
