### ISSUE TITLE
Connect event not fired for DApp running on iOS

### ISSUE THREAD

**Issue by pcibraro** [WalletConnect/walletconnect-monorepo#653]
The "connect" event is not fired when you connect WalletConnect in a Dapp running in  Opera with the mobile link in iOS. It works fine for QR Code, but not with the mobile link. This issue can not also be reproduced with your WalletConnect Dapp sample. This bug is a showstopper for implementing login with Ethereum on mobile devices.

**Comment by finessevanes** [comment]
Is this still an issue @pcibraro?

**Comment by AidenZuk** [comment]
It is fire in debug mode but missed in release

**Comment by finessevanes** [comment]
@AidenZuk can you elaborate on this please?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version  :)
