### ISSUE TITLE
WalletConnect not working for a Dapp running in Android when linking with mobile link

### ISSUE THREAD

**Issue by pcibraro** [WalletConnect/walletconnect-monorepo#654]
I am using Metamask and Chrome in Android. If you open a DApp in the mobile browser (Chrome), and try to link WalletConnect using the mobile link option, nothing happens. Android detects the callback (with the wc schema) and prompts me for an application to open the link, I select Metamask and nothing happens afterward. I am running Android 12 in a Nexus phone.

**Comment by finessevanes** [comment]
Is this still an issue?
