### ISSUE TITLE
Buffer is not defined | Vite

### ISSUE THREAD

**Issue by eikebartels** [WalletConnect/walletconnect-monorepo#655]
Hello, 

I'm facing an issue which I, after hours of trying, can not solve. 

![image](https://user-images.githubusercontent.com/767979/143621660-2a25bd97-5beb-41b1-bb3c-e9b10a52c186.png)

"@walletconnect/web3-provider": "^1.6.6",

making use of `rollup-plugin-polyfill-node` as suggested in some posts, does not work. Any idea how to solve this issue? 

I already make use of:

```
  <body>
    <!-- This is a hack to make web3 / walletconnect working with vite -->
    <script>window.global = window;</script>
    <script type="module">
        import process from "process";
        // import { Buffer } from "buffer";
        import { Buffer } from 'safe-buffer'
        import EventEmitter from "events";
        
        window.Buffer = Buffer;
        window.process = process;
        window.EventEmitter = EventEmitter;

        window.Buffer = window.Buffer || require('buffer').Buffer;

    </script>
    <div id="app" class="w-full bg-black"></div>

    <script type="module" src="/src/main.ts"></script>
  </body>
```

**Comment by indrajitsinh** [comment]
I am also having the same issue using Vite

**Comment by armgit5** [comment]
me too

**Comment by eikebartels** [comment]
and @indrajitsinh  || @armgit5  did you find a solution?

**Comment by eikebartels** [comment]
I got it :) 

That's how my config looks:
```
import * as path from 'path'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import pkg from './package.json'
import inject from '@rollup/plugin-inject'

export default defineConfig({
  server: {
    fs: {
      strict: false
    }
  },
  plugins: [
    vue({
      script: {
        refSugar: true,
      },
    }),
  ],
  optimizeDeps: {
    exclude: [
              'web3', 
            ] // <= The libraries that need shimming should be excluded from dependency optimization.
  },
  build: {
    sourcemap: true,
    commonjsOptions: {
      transformMixedEsModules: true,
    },
    rollupOptions: {
			plugins: [inject({ Buffer: ['Buffer', 'Buffer'] })],
		},
  },
  resolve: {
    alias: {
      process: "process/browser",
      stream: "stream-browserify",
      zlib: "browserify-zlib",
      util: 'util',
      '@': path.resolve(__dirname, './src'),
    },
  },
})
```

and my body: 

```
<body>
    <!-- This is a hack to make web3 / walletconnect working with vite -->
    <script>window.global = window;</script>

    <div id="app" class="w-full bg-black"></div>

    <script type="module" src="/src/main.ts"></script>
  </body>
```

**Comment by matevzStinjek** [comment]
@eikebartels Thank you! This is massive for me rn :)

**Comment by dan-hale** [comment]
Hey guys. I found another solution to this problem. I simply import wallet connect via:
`import WalletConnectProvider from '@walletconnect/web3-provider/dist/umd/index.min.js';`
and to get the types working, I made a d.ts file with:
`declare module '@walletconnect/web3-provider/dist/umd/index.min.js' {
  import WalletConnectProvider from '@walletconnect/web3-provider/dist/esm/index';
  export default WalletConnectProvider
}`

**Comment by baixiaoyu2997** [comment]
for nuxt3 user ,  there is a solution
https://github.com/nuxt/framework/discussions/4393

**Comment by toniengelhardt** [comment]
This solution worked for me with `nuxt-3.0.0` and `@wagmi/core`: 
https://stackoverflow.com/a/72978659/1384972

**Comment by rnbrady** [comment]
For anyone experiencing this recently, see https://github.com/WalletConnect/walletconnect-monorepo/issues/7176.
