### ISSUE TITLE
Walletconnect using SafePal as sign in method

### ISSUE THREAD

**Issue by LukeSamkharadze** [WalletConnect/walletconnect-monorepo#660]
Hello guys.

I'm using `Walletconnect` sign in. This is the code.

``` JS
  const walletConnectProvider = new WalletConnectProvider.default({
    rpc: {
      56: "https://bsc-dataseed1.binance.org/",
    },
  });

  await walletConnectProvider.enable();
  web3 = new Web3(walletConnectProvider);
```

When I try to chooce SafePal method on mobile chrome, I get this error on `SafePal`.

![image](https://user-images.githubusercontent.com/31849767/144582088-ec8aa8d7-d6ee-40a4-94bc-619bd97d4031.png)

I submited ticket on `SafePal` and also making this issue, just in case there is a problem on `Walletconnect`'s side.

Yes I have `BSC` wallet on `SafePal`

![image](https://user-images.githubusercontent.com/31849767/144582826-4e703c3d-eea7-4cce-9de4-391945944281.png)

If there are no problems is there something that I'm missing?

**Comment by LukeSamkharadze** [comment]
Yes I have `BSC` wallet on `SafePal`

![image](https://user-images.githubusercontent.com/31849767/144582826-4e703c3d-eea7-4cce-9de4-391945944281.png)

**Comment by finessevanes** [comment]
@LukeSamkharadze is this still an issue?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version  :)
