### ISSUE TITLE
evaluating '_walletconnect_environment__WEBPACK_IMPORTED_MODULE_0__["getSubtleCrypto"]().importKey'

### ISSUE THREAD

**Issue by SSzzPP** [WalletConnect/walletconnect-monorepo#661]
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating '_walletconnect_environment__WEBPACK_IMPORTED_MODULE_0__["getSubtleCrypto"]().importKey')

**Comment by alexanderMontague** [comment]
happens when you try to request not on https. I've seen success with disabling IOS' experimental feature `NSURLSessionWebsocket` but that ultimately didn't work for me. I just route my local server through an https tunnel. More here https://github.com/Web3Modal/web3modal/issues/334

**Comment by SSzzPP** [comment]
I have already solved this problem, HTTPS returns to Global.crypto.subtle because GetSubtlecrypto is returned and http in unsafe mode, which is undefined.

**Comment by BenjaminPiette** [comment]
If you use react or angular, you have to run your locally served dapp with SSL support (ng serve --ssl on angular).

**Comment by finessevanes** [comment]
This issue has been resolved by the OP.
