### ISSUE TITLE
sendTransaction doesn't resolve when using @walletconnect/ethereum-provider and testnet

### ISSUE THREAD

**Issue by haowang1013** [WalletConnect/walletconnect-monorepo#663]
Hi,

I noticed that when sending tx from a mobile wallet which is pre-configured to use testnet, `sendTransaction` will not resolve because it uses the wrong rpc when trying to get the tx receipt.

Here's a minimum reproduction
```
import WalletConnectProvider from "@walletconnect/ethereum-provider"
import Web3 from "web3"

const rpcs = {
    1: 'https://mainnet.infura.io/v3/...',
    4: 'https://rinkeby.infura.io/v3/...',
}

const provider = new WalletConnectProvider({
	rpc: rpcs
})

await provider.disconnect()
await provider.enable()

const web3 = new Web3(provider)
const accounts = await web3.eth.getAccounts()

if (false) {
    // the following 2 lines are workaround of this bug
    const chainId = provider.chainId
    provider.http = provider.setHttpProvider(chainId)
}

const tx = {
    from: accounts[0],
    gasPrice: ...,
    gas: ...,
    to: ...,
    value: ...,
    data: ""
}

const txHash = await web3.eth.sendTransaction(tx)
console.log(txHash)
```

I was running this code in a dekstop browser and connected it with my imtoken wallet on iOS (which has been pre-configured to use Rinkeby). The `sendTransaction` call never resolves for me.

After some debugging I realize that the WalletConnectProvider object was actually using the mainnet rpc url to get the tx receipt, which ofc will never work. What's causing this bug is that WalletConnectProvider assumes the chainId is 1 by default and only changes the http provider when the chainId changes - in my case the chainId is 4 to begin with and never changes.

A temp workaround is to add this line before sending the tx, to force the provider to use the correct url:
```
provider.http = provider.setHttpProvider(provider.chainId)
```

**Comment by alona-daphna** [comment]
How did you implement walletconnect deep linking. I'm having a hard time getting walletconnect to connect to metamask with a button click.

**Comment by cdc-Hitesh** [comment]
My working version @alona-daphna 

Make sure to `rn-nodeify` your project.

```import AsyncStorage from '@react-native-async-storage/async-storage';
import { useWalletConnect, withWalletConnect } from '@walletconnect/react-native-dapp';
import * as React from 'react';
import { Button } from 'react-native';

function App() {
  const connector = useWalletConnect();
  // const connector = useWalletConnectContext();


  if (!connector.connected) {
    /**
     *  Connect! 🎉
     */
    return <Button title="Connect" onPress={() => connector.connect()} />;
  }

  return <Button title="Kill Session" onPress={() => connector.killSession()} />;
}

export default withWalletConnect(App, {
  redirectUrl: Platform.OS === 'web' ? window.location.origin : 'wc://',
  storageOptions: {
    asyncStorage: AsyncStorage,
  },
});```

**Comment by finessevanes** [comment]
@haowang1013 is this still an issue?
