### ISSUE TITLE
query-string dependency can be removed in favor of native URLSearchParams

### ISSUE THREAD

**Issue by TimDaub** [WalletConnect/walletconnect-monorepo#667]
- https://caniuse.com/?search=URLSearchParams
- query-string makes 4.3% bundle size of 1.6.6 https://bundlephobia.com/package/@walletconnect/client@1.6.6

e.g. https://github.com/WalletConnect/walletconnect-monorepo/blob/7aeb3fe5dd0ec6c8f52a5d19d1dc69246e0076be/packages/helpers/utils/src/url.ts#L1

**Comment by finessevanes** [comment]
@TimDaub is this still an issue?
