### ISSUE TITLE
Cannot safe json parse value of type undefined 

### ISSUE THREAD

**Issue by LIAMCODE2022** [WalletConnect/walletconnect-monorepo#672]
When I run the react-wallet sample project, I got this error: 

`Cannot safe json parse value of type undefined `

It seems `client.pair` throw it

**Comment by dscrobonia** [comment]
I experienced this error when passing a V1 `uri` to the `client.pair({ uri })` function on the V2 client. Perhaps the sample dapp you're scanning is using the V1 `uri` format and you're using the V2 sample `react-wallet` ?

V1 `uri` format:

```
wc:bb9de4af-ba6e-48da-aa86-0cba34c6fce8@1?bridge=https%3A%2F%2Ft.bridge.walletconnect.org&key=19b93e126d3cfd654c0ec3d95b5750465078b581e4fc4e324c1d24ae78202e17
```

V2 `uri` format: 

```
wc:f3a47d82d88fe227f7dc76cd11f0aa3e2b410fae51943966156201d32dc88c77@2?controller=false&publicKey=1e641d2e8c2d00fc971df0550358f617813cae31c6d8c2fb58f98214b4356757&relay=%7B%22protocol%22%3A%22waku%22%7D
```

**Comment by saber-yy** [comment]
hi, i get this error too, did you have handle this problem？

**Comment by finessevanes** [comment]
@LIAMCODE2022 @saber-yy is still still an issue?
