### ISSUE TITLE
WalletConnect not opening mobile interface after clicking mint

### ISSUE THREAD

**Issue by naregkhodanian** [WalletConnect/walletconnect-monorepo#678]
I have added WalletConnect Provider successfully with VanillaJS. My issue is now when a person presses mint, they are not being prompted to open a window in metamask. Why is that? Connect does redirect them properly.

**Comment by alona-daphna** [comment]
Hey, I'm trying to use walletconnect provider for initial connection to wallet. Can you share how you did that?

**Comment by ahmedaisar** [comment]
Hello guys any news on this?

**Comment by finessevanes** [comment]
@ahmedaisar @alona-daphna @naregkhodanian is this still an issue?
