### ISSUE TITLE
Add wallet_addEthereumChain, wallet_watchAsset and wallet_switchEthereumChain to "signingMethods"

### ISSUE THREAD

**Issue by BenjaminPiette** [WalletConnect/walletconnect-monorepo#679]
Currently when dApps call wallet_addEthereumChain, wallet_watchAsset or wallet_switchEthereumChain commands while connected through WC on mobile, the wallet app doesn't come back to front. This is because only methods that are in @walletconnect/utils ' signingMethods array trigger the wallet app "bring to front" flow.

I suggest to simply add those3 methods to the signingMethods array. We have tried that and this works well. This way, dapps requesting to switch the active network can automatically show the wallet app.

**Comment by pedrouid** [comment]
Fixed on v1.7.1
