### ISSUE TITLE
On mobile: How to update the wallet the user can connect to?

### ISSUE THREAD

**Issue by romain130492** [WalletConnect/walletconnect-monorepo#680]
Hey
I dont my user to be able to connect with any wallet,
Instead i would like them to only `metamask`,
how can I do that?
thanks

**Comment by alona-daphna** [comment]
const provider = new WalletConnectProvider({
        qrcodeModalOptions: {
            mobileLinks: ['metamask''],
        },
    });
I think.

**Comment by sumeetm60** [comment]
same issue for iOS react native, even after providing the mobileLinks: ['metamask''], popup showing all the wallets. Please can anyone help me on this, am using @walletconnect/react-native-dapp

**Comment by johnylawrence1987** [comment]
+1

Same issue here, `mobileLinks` not working on v1.8.0

**Comment by finessevanes** [comment]
Is this still an issue?
