### ISSUE TITLE
This option should be optional since it is instantiated with a value in the class

### ISSUE THREAD

**Issue by mattxyzeth** [WalletConnect/walletconnect-monorepo#685]
All other options are optional except this one. Should it also be optional considering the class constructor handles an undefined situation?

https://github.com/WalletConnect/walletconnect-monorepo/blob/a22bee13df255ee59d338d600175250a3a0ef8aa/packages/ethereum-provider/src/index.ts#L66

**Comment by ganchoradkov** [comment]
While the `chainId` is handled internally to default `1` having it required reduces the chance of accidental connection to chain that is not intended
