### ISSUE TITLE
Way to serialize/restore session in the backend?

### ISSUE THREAD

**Issue by d13co** [WalletConnect/walletconnect-monorepo#687]
Hi all,

I'm using WalletConnect v1.7.0  from my backend (nodejs) and authorizing via the frontend (react). 

I am looking for a way to serialize and deserialize the wallet connections so that they can survive a server restart. 

I have tried saving the `walletConnector.session` object and restoring that after constructing the WalletConnect object, but it seems to create a "dead" connection - transactions do not go through it.

I also tried saving the URI from a previously authorized connection and reusing that in the WalletConnect constructor - hoping that it will be detected as an authorized session and trigger a `connect` event, but this doesn't seem to work either.

Is there an established pattern I can use for this?

**Comment by tasinet** [comment]
Figured it out: You can pass `.session` from a previous walletConnect object to a new WalletConnect constructor options object. 

```
const oldSession = walletConnect.session;
const new WalletConnect({ bridge: '', clientMeta: {}, session: oldSession });
```

It even fires a disconnect event if the wallet was disconnected while the server was offline.

**Comment by d13co** [comment]
Figured it out: You can save .session and pass it into the WalletConnect constructor:

```
const wC = new WalletConnect({ bridge: '', clientMeta: {}, session: sessionFromFile });
```
It even fires a disconnect event if the wallet was disconnected while the server was offline.

**Comment by ashconnell** [comment]
Is this a "recommended" way to serialise and deserialize sessions? 

I noticed that `WalletConnectProvider.provider.wc.session` is identical to the localStorage value of `walletconnect` so I assume it would be fine to use this?
