### ISSUE TITLE
Cannot read properties of undefined (reading 'importKey')

### ISSUE THREAD

**Issue by GnussonNet** [WalletConnect/walletconnect-monorepo#689]
I am running latest version of nextjs, @walletconnect/client and @walletconnect/qrcode-modal

When the button is pressed the modal shows but an error in developers tools shows

> "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'importKey')"

It works on development build but now production

``` JS
const connector = new WalletConnect({
  // Required
  bridge: 'https://bridge.walletconnect.org',
  qrcodeModal: QRCodeModal,
  // Required
  clientMeta: {
    description: 'My website description ',
    url: 'https://mywebsite.url',
    icons: ['../assets/svg/icon.svg'],
    name: 'My website name',
  },
});

const connect = () => {
  // Check if connection is already established
  if (!connector.connected) {
    // create new session
    connector.createSession();
  } else {
    connector.sess;
  }
};

// This is used to start login process with WalletConnect
<button onClick={connect}></button
```

**Comment by pasevin** [comment]
You most likely are not using SSL on your domain. This error appears if you open your website via http vs https.

**Comment by php4fan** [comment]
And you closed this???

1. If your code throws a "cannot read property of undefined" error from deep down in your functions, it's your bug. You must check that something is not undefined before reading properties from it
2. If the issue is that the website is being served over http and it is required that it is served over https, then check for that and throw an error that says so, possibly at a much earlier stage.

**Comment by rahujoshi** [comment]
> You most likely are not using SSL on your domain. This error appears if you open your website via http vs https.

My Website uses HTTPS still, I am getting this error.

**Comment by ZeeshanAhmadKhalil** [comment]
For me its giving this error on https and on http its not giving this error but i am unable to connect my wallet :/

**Comment by aakash4dev** [comment]
i also got same error in mobile phones, at laptop/desktop its working fine.
Error is: cannot read properties of undefined ( reading importKey` )

**Comment by kringt06** [comment]
> me too

nextjs13

**Comment by yourcasualdev** [comment]
I am getting this error on my mobile on  NextJS 12 while on the dev server (HTTP).

**Comment by FatNerdPeng** [comment]
I encountered this problem on the development server. My situation is that my host is running normally and can generate QR code, but when other computers in the LAN access my project, the QR code can pop up, but the console will have this error.

**Comment by juniarto-samsudin** [comment]
Same problem here:
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'importKey')

Only when serving on localhost [127.0.0.1] works...

**Comment by OctoD** [comment]
Same problem here.

It's practically impossible to test a dApp without building it and serving through a trusted domain.

**Comment by rozztopher** [comment]
This needs further looking into.

It happens on mobile devices regardless if we're using https or not.

**Comment by php4fan** [comment]
This hasn't been reopened yet? Unbelievable.

**Comment by Satwik-4** [comment]
> I encountered this problem on the development server. My situation is that my host is running normally and can generate QR code, but when other computers in the LAN access my project, the QR code can pop up, but the console will have this error.

@FatNerdPeng Were you able to solve this error? I'm also experiencing exactly the same thing

**Comment by Willzxxz** [comment]
please reopen obviously a lot of people are having this issue, including myself

**Comment by 0xtchandragupta** [comment]
I'm facing the same error on mobile phones while invoking and eth_sign json rpc request to metamask app installed on mobile.
Desktop with metamask browser extension works perfectly.

**Comment by FatNerdPeng** [comment]
> > I encountered this problem on the development server. My situation is that my host is running normally and can generate QR code, but when other computers in the LAN access my project, the QR code can pop up, but the console will have this error.
> 
> @FatNerdPeng Were you able to solve this error? I'm also experiencing exactly the same thing

Unfortunately, I haven't solved this problem yet.

**Comment by ghost** [comment]
Same error here please re-open

**Comment by amitdubey6261** [comment]
facing same problem reopen it...

**Comment by AliAsgharRanjbar** [comment]
I'm stuck with the same issue, reopen it please.

**Comment by KelvinSan** [comment]
Same error

**Comment by eliudsaj** [comment]
same error here

**Comment by amitdubey6261** [comment]
For me this problem is resolved by using the Https server, when. I was calling the backend via HTTP(unsecured), it's not allowed to make secure calls from unsecured http frontend, make sure you deploy your server, functionality on https

**Comment by KelvinSan** [comment]
How can you use this from localhost?

**Comment by maxhsu-da** [comment]
please reopen

**Comment by bitcoin4cashqc** [comment]
Even https dont fix this.
