### ISSUE TITLE
connect cancellation or AbortController support

### ISSUE THREAD

**Issue by devhawk** [WalletConnect/walletconnect-monorepo#696]
there should be a way to cancel a connect promise if the user changes their mind. having an [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) option on ConnectParams (and wiring it all the way down thru the stack) would be a reasonable approach

**Comment by spencercap** [comment]
agreed. 
is there any way to cancel, abort or kill a transaction request sent via `sendCustomRequest`? best case, if the confirm notification on the mobile app could disappear once this happens, that would be great

**Comment by reslear** [comment]
wait

**Comment by finessevanes** [comment]
@devhawk is this still an issue?
