### ISSUE TITLE
[React native] - Promise doesn't resolve after sending a message for signing

### ISSUE THREAD

**Issue by intergalacticspacehighway** [WalletConnect/walletconnect-monorepo#706]
Thanks for the library!

I am facing an issue while sending data for signing with react native client.

```
const res = await connector.signTypedData(dataToSign);
```
This data gets passed to the wallet for signing but post signature when we move back to app, we receive the below error logs.

```
2022-01-17 21:55:07.982233+0530 [1961:469055] [javascript] Possible Unhandled Promise Rejection (id: 0):
Error: Unable to open URL: https://metamask.app.link
Error: Unable to open URL: https://metamask.app.link
```

Will update if I get more details on the bug. If someone has ideas, please let me know.

**Comment by intergalacticspacehighway** [comment]
It works sometimes and sometimes it doesn't, would be cool if there's a way to debug bridge calls on the default bridge 😅

**Comment by finessevanes** [comment]
@intergalacticspacehighway is this still an issue?
