### ISSUE TITLE
@walletconnect/ethereum-provider (1.7.1) doesn't resolve signer responses after page reload

### ISSUE THREAD

**Issue by amper-fb** [WalletConnect/walletconnect-monorepo#718]
Steps to reproduce:

1. `git clone git@github.com:WalletConnect/walletconnect-monorepo.git`
2. `git checkout 1.7.1`
3. `npm run bootstrap && npm run example`
4. open: http://localhost:8060/ethereum-provider.html
5. Click "Connect"
6. Scan QR with Wallet Connect wallet app
7. Click "Sign Message"
8. Approve request on wallet
9. Verify signature result printed in example dev console
10. Refresh the page
11. Click "Connect" (should resume previous pairing)
12. Click "Sign Message"
13. Approve request on wallet

**Expected result**: 
the signature is printed in example dev console

**Actual result**: 
the promise never resolves and nothing gets printed. (even when rejected on wallet)

Note this does not reproduce with http://localhost:8060/web3-provider.html or http://localhost:8060/ examples,

This is reproducible in Uniswap and more dapps and affects many wallet connect users on a platform I'm developing.

**Comment by amper-fb** [comment]
Adding that it doesn't happen on eth mainnet chain, but reproducible on Ropsten and Kovan from what I've tested.

**Comment by tmm** [comment]
Was able to reproduce this on the `wagmi` library's docs site [here](https://wagmi-xyz.vercel.app/guides/sign-message), by doing the following:

1. Connect with WalletConnect
2. Refresh page
3. Sign message

**Comment by vonoro** [comment]
this is now fixed and can be closed @amper-fb
