### ISSUE TITLE
Updates on react-native-dapp V.2

### ISSUE THREAD

**Issue by alejomendoza** [WalletConnect/walletconnect-monorepo#723]
The package is unusable with the latest client, tried using it with v2 and it failed. Docs are very confusing on a straight forward way to use wallet connect v2 with React Native. Would appreciate any update on the timeline. Thanks

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version  :)
