### ISSUE TITLE
Close QRcode modal causes a critical error

### ISSUE THREAD

**Issue by pauloreis7** [WalletConnect/walletconnect-monorepo#724]
**Bug description**

My squad is using walletConnect in a play to earn game project, where the reward for matches is done based on our token for the wallet connected by walletConnect.
When the user closes the modal with the QRcode that connects a wallet without establishing a connection, an error should be triggered in the console and can be mapped by a try catch for example.

 The problem is that the error generated is a critical error that totally breaks the app and cannot be mapped by a catch, so when the user closes the modal the error is fired, the application breaks critically and the bug happens.

**Package**

We are currently using the @walletconnect/web3-provider package for the implementation.

**Suggestion**

During debugging I realized that the Error: "user closed modal", is generated by an event that catches the modal closure and fires a throw Error. A good solution would be to stop throwing a critical error because the user action of closing the modal is common, this should be treated as an error, but not something critical that breaks the application. 
It is also very important for the solution to this problem that the modal close error can be mapped to a catch or fall into the "onError" callback of the activate method and the developer can do whatever they want with this error.

**Comment by anoushk1234** [comment]
im having the same error, why is this not being addressed?

**Comment by phattranky** [comment]
I got the same problem at my side. But not sure why it's not happening here https://codesandbox.io/embed/web3react-demo-mqlydu?fontsize=14&hidenavigation=1&theme=dark

**Comment by phattranky** [comment]
I found some work around here

https://github.com/NoahZinsmeister/web3-react/issues/454

https://github.com/NoahZinsmeister/web3-react/issues/376

**Comment by luca992** [comment]
Is there any work around that actually lets you close the modal without the error being thrown? I would like a user to be able to switch between walletconnect or metamask

**Comment by pauloreis7** [comment]
### The solution found is: 

Use the error callback of the activate method to detect the error in the modal, check the instanceof WalletConnectConnector and thus set `walletconnect.walletConnectProvider` to `undefined`.

### Example:

`activate(walletconnect, (err) => {`
`      if (walletconnect && walletconnect instanceof WalletConnectConnector) {`
`        walletconnect.walletConnectProvider = undefined`
`      }`
`    })`
`  }`


🚀🚀🚀 I hope it helps

**Comment by luca992** [comment]
yeah... how are you detecting the error in the modal?
