### ISSUE TITLE
iOS build failed because of rn-nodeify hack (duplicate symbols for architecture x86_64)

### ISSUE THREAD

**Issue by jonathanschad** [WalletConnect/walletconnect-monorepo#746]
If you use **walletconnect** together with react-native and you installed it with the **rn-nodeify hack** than this might be relevant to you. Also this issue should serve as a starting point for others who have the same problem. I hope I can save you from a lot of headache. Original Issue: https://github.com/Rapsssito/react-native-tcp-socket/issues/61#issuecomment-653881488. I've also posted this in the rn-nodeify repo: https://github.com/tradle/rn-nodeify/issues/114

Since this is not an issue directly caused by **walletconnect** I don't know what can be done here. However I think there should be a disclaimer in the official docs that either link to this issue or it should be explained right there.

## Steps to reproduce
The issue appears if you try to compile a react native project for iOS, which uses **rn-nodefiy**. To be more specific the cause of the problem seems to come from **react-native-tcp** and **react-native-udp**. 

It seems that it also does not matter if you use a new M1 Mac or an older Intel based Mac. Also it does not matter if you use **npm** or **yarn**

1. Create a new react native project
`npx react-native init AwesomeTSProject --template react-native-template-typescript`

At this point your iOS version should still build correctly.

2. install **rn-nodeify**.
`npx rn-nodeify --install --hack`

3. install pods
`cd ios & pod install`

4. Try to build the project for iOS again 
`npm run ios`

Your build will fail with the message `ld: {number} duplicate symbols for architecture x86_64`

## How to solve it
Credit to @Jiope

>    1. Go to xcode
>    2. into project navigator, click on Pods folder
>    3. then select TcpSockets in targets
>    4. Go to Build Phases > Compile sources
>    5. Here remove reference to CocoaAsyncSocket (this should be the first entry in the list)

in this case you also need to do the same for react-native-udp

It seems like you need to redo this procedure every time you add new dependencies to your project

**Comment by Zestpond** [comment]
same issue

**Comment by miayang0513** [comment]
same issue

**Comment by trungtruc91** [comment]
same issue

**Comment by anhnh-yoong** [comment]
same issue

**Comment by KrishEnacton** [comment]
same issue

**Comment by lucasPDY** [comment]
+1 any updates on this?
Currently on a M1 MBP.

**Comment by finessevanes** [comment]
@lucasPDY @KrishEnacton @anhnh-yoong @trungtruc91 @miayang0513 @Zestpond did @Zestpond solution work for you all?
