### ISSUE TITLE
Buffer is not defined error with CRA

### ISSUE THREAD

**Issue by wnz99** [WalletConnect/walletconnect-monorepo#748]
The standalone client will throw this error with CRA and package `"react-scripts": "^5.0.0"`:

![image](https://user-images.githubusercontent.com/12447140/152679094-f43a285d-b10b-4196-ad99-0bd0800e9c64.png)

The reason is that Webpack 5 and CRA v5 don't add fallbacks for nodejs modules any more.

**Comment by derekcsm** [comment]
@wnz99 I'm also running into this, have you figured out a fix?

**Comment by ynunezaguirre** [comment]
I ran into the same issue with a lot of modules missing when using the last version of CRA a few days ago, it uses webpack 5.x, that has remove some node modules, Buffer is one them, a solution for me was to use Craco to config the webpack without ejecting. https://github.com/gsoft-inc/craco.

```
const webpack = require('webpack');

module.exports = {
    configure: {
      resolve: {
        fallback: {
          buffer: require.resolve('buffer'),
        },
      },
    },
    plugins: {
      add: [
        new webpack.ProvidePlugin({
          Buffer: ['buffer', 'Buffer'],
        }),
      ],
    },
  },
}
```

**Comment by hanahem** [comment]
@ynunezaguirre 
Thanks. The Craco workarout indeed fixes the Buffer dep issue, but pops new dependency issues with other modules. Do you think I should do the same thing for other missing modules to make it work?
(pretty heavy to downgrade so many packages)

**Comment by wnz99** [comment]
Personally, I think that the documentation should not state that the package is compatible with browser, if it depends on modules only available on nodeJS. The browser version should include anything necessary to run out of the box, imho.

**Comment by ynunezaguirre** [comment]
> @ynunezaguirre Thanks. The Craco workarout indeed fixes the Buffer dep issue, but pops new dependency issues with other modules. Do you think I should do the same thing for other missing modules to make it work? (pretty heavy to downgrade so many packages)

For now i haven't found another workaround to make it run :/  
There is a plugin node-polyfill-webpack-plugin that maybe can help you , but doesn't work for me with all modules missing.

**Comment by hanahem** [comment]
Just found a dirty workaround similar to the one posted by @ynunezaguirre 
Not using Craco but react-app-rewired.

Still on webpack 5.x
Added a `config-overrides.js` in the root:
```
const webpack = require('webpack');
module.exports = function override(config, env) {
    config.resolve.fallback = {
        url: require.resolve('url'),
        assert: require.resolve('assert'),
        buffer: require.resolve('buffer'),
    };
    config.plugins.push(
        new webpack.ProvidePlugin({
            process: 'process/browser',
            Buffer: ['buffer', 'Buffer'],
        }),
    );

    return config;
}
```

And
`npm install process`

Then updated the scripts part of `package.json`
```
"scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test",
    "eject": "react-app-rewired eject"
 }
 ```
 
 This works fine with me for now. I can use the client and pop the QR modal.

**Comment by Sednaoui** [comment]
craco config didn't work for me initially until I installed buffer as a dev dependency and did -> `buffer: require.resolve('buffer/')`

missing / at the end of buffer.

from the [docs](https://www.npmjs.com/package/buffer#usage): 

> To require this module explicitly, use require('buffer/') which tells the node.js module lookup algorithm (also used by browserify) to use the npm module named buffer instead of the node.js core module named buffer!

**Comment by armgit5** [comment]
[@esbuild-plugins/node-globals-polyfill](https://stackoverflow.com/questions/70714690/buffer-is-not-defined-in-react-vite) was able to help me out with `global is not defined` and `Buffer is not defined` here is related comment https://github.com/plouc/nivo/issues/1455#issuecomment-1041830487

**Comment by willisk** [comment]
Thanks @hanahem, also got it to work now.
I had to additionally install util and add it to the config
`npm install util`

```js
/* config-overrides.js */
const webpack = require('webpack');
module.exports = function override(config, env) {
    config.resolve.fallback = {
        util: require.resolve('util/'),
        url: require.resolve('url'),
        assert: require.resolve('assert'),
        buffer: require.resolve('buffer'),
    };
    config.plugins.push(
        new webpack.ProvidePlugin({
            process: 'process/browser',
            Buffer: ['buffer', 'Buffer'],
        }),
    );

    return config;
}
```

This is just terrible imo, I spent an ENTIRE day fumbling around, exploring solutions, because of incompatible packages.

**Comment by ddkang** [comment]
Are there any plans to fix this?

**Comment by atropos0902** [comment]
> Are there any plans to fix this?

I was able to make it run by downgrading `react-scripts` version to `4.0.3` but I don't think it's the best solution.
This should be fixed ASAP @pedrouid

**Comment by crazyrabbitLTC** [comment]
Yeah I wish there was a solution for this. I'm on Redwoodjs.

**Comment by ddkang** [comment]
Are there any plans to fix this? This bug prevents updating to the latest versions of packages.

**Comment by ShevaShen** [comment]
Here is a solution from coinbase
https://docs.cloud.coinbase.com/wallet-sdk/docs/web3-react#a-nametroubleshootingatroubleshooting

**Comment by ddkang** [comment]
This does not work with create-react-app, which does not allow webpack overrides

**Comment by ShevaShen** [comment]
> This does not work with create-react-app, which does not allow webpack overrides

downgrade to `react-script` v4, v5 has so many bugs the CRA team needs to fix

**Comment by ericlewis966** [comment]
If we are using React 17 or 18, we can't avoid "Buffer undefined" proflem without "config-overides.js".
We have to downgrade react version to use walletconnect libraries.

**Comment by OmBayus** [comment]
```
npm install buffer
```

```js
window.Buffer = window.Buffer || require("buffer").Buffer;

function App() {
...
}
```

**Comment by DalSoft** [comment]
> I ran into the same issue with a lot of modules missing when using the last version of CRA a few days ago, it uses webpack 5.x, that has remove some node modules, Buffer is one them, a solution for me was to use Craco to config the webpack without ejecting. https://github.com/gsoft-inc/craco.
> 
> ```
> const webpack = require('webpack');
> 
> module.exports = {
>     configure: {
>       resolve: {
>         fallback: {
>           buffer: require.resolve('buffer'),
>         },
>       },
>     },
>     plugins: {
>       add: [
>         new webpack.ProvidePlugin({
>           Buffer: ['buffer', 'Buffer'],
>         }),
>       ],
>     },
>   },
> }
> ```

Slight change (needs to be nested in the webpack property) to get this working with CRACO, and CRA 5.0.1
```js
const webpack = require('webpack');
module.exports = {
    webpack: {
        configure: {
            resolve: {
                fallback: {
                    buffer: require.resolve('buffer'),
                },
            },
        },
        plugins: {
            add: [
                new webpack.ProvidePlugin({
                    Buffer: ['buffer', 'Buffer'],
                }),
            ],
        },
    },
};
```

**Comment by ogbuanu** [comment]
> ```
> npm install buffer
> ```
> 
> ```js
> window.Buffer = window.Buffer || require("buffer").Buffer;
> 
> function App() {
> ...
> }
> ```

This worked for me.

**Comment by finessevanes** [comment]
@wnz99 is this still an issue?

**Comment by ogbuanu** [comment]
No

**Comment by RicFer01** [comment]
I still have this error just installing buffer and doing `window.Buffer = window.Buffer || Buffer;`, in order to fix is it necessary to use CRACO?

**Comment by guppykang** [comment]
I continue to get this error, and am using 
```
  util: require.resolve('util/'),
        assert: require.resolve('assert/'),
        stream: require.resolve('stream-browserify'),
        zlib: require.resolve('browserify-zlib'),
        buffer: require.resolve('buffer'),
        process: require.resolve('process/browser'),
```

as well as adding the plugins via: 
```
plugins: {
      add: [
        new webpack.ProvidePlugin({
          Buffer: ['buffer', 'Buffer'],
          process: 'process/browser',
        }),
      ],
    },
```

I also added `window.Buffer = window.Buffer || Buffer;` to the root index.js file

**Comment by RicFer01** [comment]
> I continue to get this error, and am using
> 
> ```
>   util: require.resolve('util/'),
>         assert: require.resolve('assert/'),
>         stream: require.resolve('stream-browserify'),
>         zlib: require.resolve('browserify-zlib'),
>         buffer: require.resolve('buffer'),
>         process: require.resolve('process/browser'),
> ```
> 
> as well as adding the plugins via:
> 
> ```
> plugins: {
>       add: [
>         new webpack.ProvidePlugin({
>           Buffer: ['buffer', 'Buffer'],
>           process: 'process/browser',
>         }),
>       ],
>     },
> ```
> 
> I also added `window.Buffer = window.Buffer || Buffer;` to the root index.js file

I fixed like this:
```
config.resolve.fallback = {
	crypto: require.resolve('crypto-browserify'),
  	util: require.resolve('util/'),
  	url: require.resolve('url'),
  	assert: require.resolve('assert'),
  	buffer: require.resolve('buffer'),
};

config.plugins.push(
	new webpack.ProvidePlugin({
    	process: 'process/browser',
    	Buffer: ['buffer', 'Buffer'],
	}),
);
```
