### ISSUE TITLE
can't add web3Provider 

### ISSUE THREAD

**Issue by soring323** [WalletConnect/walletconnect-monorepo#764]
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-02-08 at 22 07 37](https://user-images.githubusercontent.com/62229912/153058129-69e156b3-92ba-4ac9-8373-d447a816cee8.png)
I'm facing this issue when I add web3provider. 
any good idea?

**Comment by soring323** [comment]
Just enabled web3 but faced this issue also. 
![Screen Shot 2022-02-08 at 11 30 24 PM](https://user-images.githubusercontent.com/62229912/153070448-9a30fcd0-5fda-4d18-8957-42470ff63c14.png)

**Comment by finessevanes** [comment]
Is this still an issue?
