### ISSUE TITLE
Build fails with Vite

### ISSUE THREAD

**Issue by Zedonboy** [WalletConnect/walletconnect-monorepo#768]
Everything work fine with npm run dev.

But npm run build

Generates this error
`removehexprefix' is not exported by node_modules/@walletconnect/encoding/dist/cjs/index.js, imported by node_modules/@walletconnect/utils/dist/esm/ethereum.js`

**Comment by alex-shortt** [comment]
probably related to #341

**Comment by vrde** [comment]
Related to https://github.com/vitejs/vite/issues/7257

**Comment by tfalencar** [comment]
Related to https://github.com/WalletConnect/walletconnect-monorepo/issues/341

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version  :)
