### ISSUE TITLE
specify modal language in IQRCodeModalOptions

### ISSUE THREAD

**Issue by kusakawazeusu** [WalletConnect/walletconnect-monorepo#769]
Current behavior is to detect language from browser.

```javascript
function getText(): TextMap {
  const lang = getNavigatorOrThrow().language.split("-")[0] || "en";
  return Languages[lang] || Languages["en"];
}
```

It might be better if there's a parameter to specify the language used in modal.

**Comment by terranc** [comment]
We really need it, too.

**Comment by finessevanes** [comment]
@kimpers is this still an issue? Can you let me know if you're using W3M v1 or W3M v2?
