### ISSUE TITLE
make deploy exit error 1 - caddy is missing

### ISSUE THREAD

**Issue by vorotech** [WalletConnect/walletconnect-monorepo#773]
As far as I can see the PR https://github.com/WalletConnect/walletconnect-monorepo/pull/697 has wiped all caddy related configuration.
Was it deprecated? Is there a replacement?

Latest release when running `make deploy` exists with error:

```sh

~/walletconnect-monorepo$ sudo make deploy
sed: can't read setup: No such file or directory
Relay URL domain [localhost]: 
Email for SSL certificate (default noreply@gmail.com): 
Paste your cloudflare API token: 
MAKE: Done with setup

mkdir -p build
mkdir -p .makeFlags
docker pull redis:6-alpine
6-alpine: Pulling from library/redis
Digest: sha256:4bed291aa5efb9f0d77b76ff7d4ab71eee410962965d052552db1fb80576431d
Status: Image is up to date for redis:6-alpine
docker.io/library/redis:6-alpine
docker pull nixos/nix
Using default tag: latest
latest: Pulling from nixos/nix
Digest: sha256:f0c68f870c655d8d96658ca762a0704a30704de22d16b4956e762a2ddfbccb09
Status: Image is up to date for nixos/nix:latest
docker.io/nixos/nix:latest
touch .makeFlags/pull
MAKE: Done with pull

MAKE: Done with nix-volume

docker run --name builder --rm -v nix-store:/nix -v /home/ubuntu/walletconnect-monorepo:/src -w /src nixos/nix nix-shell -p bash --run "nix-build --attr relay.docker --argstr githash ad1670bf && cp -r -f -L result build/build-img-relay && rm -rf result"
/nix/store/xc0ydzg1kasi940k4l54544020gyan6z-relay-server.tar.gz
docker load -i build/build-img-relay | awk '{print $NF}' | tee build/build-img-relay-img
walletconnect/relay-server:v1.0.2
MAKE: Done with build-img-relay

docker run --name builder --rm -v nix-store:/nix -v /home/ubuntu/walletconnect-monorepo:/src -w /src nixos/nix nix-shell -p bash --run "nix-build ./ops/waku-docker.nix --argstr wakuVersionTag v0.5.1 --argstr nixNimRepoSha256 0k55hw1wqcyrpf9cxchhxdb92p75mmskkpvfn1paivl1r38pyb4a && cp -r -f -L result build/build-img-waku && rm -rf result"
/nix/store/jckw0kx1ha032bywyc1rld6z19ap6373-wakunode.tar.gz
docker load -i build/build-img-waku | awk '{print $NF}' | tee build/build-img-waku-img
wakunode:9b5lmv4gdvi28y37riqjyg7a6xygsa32
MAKE: Done with build-img-waku

touch .makeFlags/predeploy
bash ops/deploy.sh
cat: ./build/build-img-caddy-img: No such file or directory

Deploy command: docker stack deploy walletconnect -c ops/docker-compose.yml -c ops/docker-compose.prod.yml  -c ops/docker-compose.monitor.yml

Creating network walletconnect_default
open /home/ubuntu/walletconnect-monorepo/ops/stats.html: no such file or directory
make: *** [Makefile:148: deploy] Error 1
```

**Comment by sbc64** [comment]
Thanks, I will work on fixing this.

**Comment by Vikram710** [comment]
any solution for this?

**Comment by mohzourob** [comment]
Hi @sbc64, Do u manage to fix this issue ?

**Comment by kaumudpa** [comment]
+1

**Comment by Amencee** [comment]
tag :2.0.0-beta.26
This bug still exists

**Comment by vorotech** [comment]
hi @sbc64 @pedrouid @bkrem @IljaDaderko
Can you please clarify where the project direction? 
It seems to me that your team is going to build and maintain own infrastructure.
The are not many info about it in the media sources, but I assumed it because all scripts and other docs how to run the relayer have disappeared (this issue and https://github.com/WalletConnect/walletconnect-monorepo/issues/1219).
To be clear, I don't mind about your decision, but want some clarity here.

Thanks,
Member of TrustWallet team

**Comment by sbc64** [comment]
Our infrastructure has changed considerably to be more reliable. This means that docker-compose was becoming more of a burden than an enabler in our plans.

The relay can be located https://github.com/WalletConnect/relay

and it has the a docker-compose that is good enough for local testing, but we are not going to be supporting `caddy`, `lets's encrypt` due to time constraints.

**Comment by vorotech** [comment]
@sbc64 thank you for a response!
I'm going to close the issue.
Running the service itself is more than enough. Most engineers know how to add a LB and/or Reverse Proxy layer.
