### ISSUE TITLE
Attempting to install via command `npm i @walletconnect/web3-provider` on Windows 10 with Node 17.5

### ISSUE THREAD

**Issue by Khan3930** [WalletConnect/walletconnect-monorepo#792]
Attempting to install via command `npm i @walletconnect/web3-provider` on Windows 10 with Node 16

I'm getting the following error:

```
PS D:\Github\goingup-xyz\web-app> npm i @walletconnect/web3-provider
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mark\AppData\Local\npm-cache\_logs\2022-01-25T10_19_00_644Z-debug-0.log
```

Thanks in advance

_Originally posted by @markibanez in https://github.com/WalletConnect/walletconnect-monorepo/discussions/742_

**Comment by paulflo150** [comment]
Have you been able to get this to work?

**Comment by silc22** [comment]
Hi, I have the same problem, did you fix it?

**Comment by hypotyposis** [comment]
same problem. To provide more info:
- under `node:16.13.1 ubuntu:22.04 npm:8.15.1` install successfully
- under `node:16.13.1-alpine` install error
- under `node:16.13.1-bullseye` install successfully


Looks like this problem is related to whether you have `git` installed. If not, install `git` first.

**Comment by SenadK95** [comment]
I got it working by doing the following steps:

1. change 2 files in `/nodejs` to fix the `npm WARN config global --global, --local are deprecated. Use --location=global instead.` (see https://stackoverflow.com/questions/72401421/message-npm-warn-config-global-global-local-are-deprecated-use-loc)
2. installing git

**Comment by finessevanes** [comment]
Hey @Khan3930 did @SenadK95 solution resolve your issue?
