### ISSUE TITLE
[Wallet Documentation] Not enough examples to infer what needs to be sent as responses to json rpc requests

### ISSUE THREAD

**Issue by SangameswaranRS** [WalletConnect/walletconnect-monorepo#804]
https://docs.walletconnect.com/2.0/json-rpc/ethereum -> A typical web3 signature has r, s, v.

Should I "RLP" encode this for "Personal_sign" and EIP 712? 

I'm using the kotlin integration (V2 sdk) and react-app.walletconnect.org application to test this.

**Comment by SangameswaranRS** [comment]
I kinda saw the web3js impl and figured out the Signature part, but still for personal sign, https://react-app.walletconnect.com always "valid" is set to false, 

I'm using the web3j's Sign.signPrefixedMessage( the first param, keyPair)

I even tried many variants of it, like hashing the first param etc.., giving as UTF-8 decoded, still, the "valid" is always false - Any idea on what I'm missing?

**Comment by SangameswaranRS** [comment]
Adding, Web3j already checks the "recoverability" of the signed messages, still the modal shows as wrong. 
I found similar methods in App.ts too (Checked just in case if the steps in deriving the hash are wrong)

Any idea on what I'm missing?

**Comment by finessevanes** [comment]
@SangameswaranRS is this still an issue?
