### ISSUE TITLE
The application will crash when idle for a while, no matter dapp or wallet.

### ISSUE THREAD

**Issue by GHChrisSu** [WalletConnect/walletconnect-monorepo#809]
In dapp case showing the warning: MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 open listeners added. Use emitter.setMaxListeners() to increase limit
<img width="1503" alt="image" src="https://user-images.githubusercontent.com/13779988/155287689-6a5a27c8-8a4b-4ce2-868b-5bd36e98cb3c.png">

In wallet case a bunch of subscription emit: Emitting subscription_created
<img width="753" alt="image" src="https://user-images.githubusercontent.com/13779988/155287972-f91f814a-84ee-4e0f-a1c7-347fd5d905df.png">

**Comment by chadyj** [comment]
Is this a duplicate of #625?

**Comment by GHChrisSu** [comment]
> Is this a duplicate of #625?

Maybe the same reason, in different case.

**Comment by bkrem** [comment]
This duplicates #625, which we’re currently putting a fix together for.

Closing.
