### ISSUE TITLE
Does WalletConnect support non-immediate transactions

### ISSUE THREAD

**Issue by lironavin** [WalletConnect/walletconnect-monorepo#813]
### Discussed in https://github.com/WalletConnect/walletconnect-monorepo/discussions/812

<div type='discussions-op-text'>

<sup>Originally posted by **lironavin** February 23, 2022</sup>
Does WalletConnect support a transaction initiated by a user and afterwards goes into a session of approvals by different users (A workflow of approvals)?  Meaning from the initial request of making a transaction to the point of actually committing it there might be a few hours time difference.  

From what I read, you only support immediate execution of requested transactions, is that true?

Thanks</div>

**Comment by finessevanes** [comment]
Closing this since this is also already a question.
