### ISSUE TITLE
`ethereum.enable()` deprecated in favor of `ethereum.send('eth_requestAccounts')` EIP-1102

### ISSUE THREAD

**Issue by hexcowboy** [WalletConnect/walletconnect-monorepo#819]
The RPC method `eth_requestAccounts` does not seem to conform to the standard here: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md#concepts

**Comment by pedrouid** [comment]
Actually you can see that the ethereum-provider simply maps enable() to eth_requestAccounts

```typescript
  public async enable(): Promise<ProviderAccounts> {
    const accounts = await this.request({ method: "eth_requestAccounts" });
    return accounts as ProviderAccounts;
  }
 ```
 
 Source code: https://github.com/WalletConnect/walletconnect-monorepo/blob/v1.0/packages/providers/ethereum-provider/src/index.ts#L65
