### ISSUE TITLE
Walletconnect event callback fired multiple times

### ISSUE THREAD

**Issue by samyan** [WalletConnect/walletconnect-monorepo#829]
Hello. I've implemented Walletconnect in Modal dialog. Every time i close and open the dialog. The number of `connect.on('session_update')` callback firing is incremented. So it starts to fire multiple times after close / open dialog. How can i unsuscribe walletconnect event callbacked when the component is unmounted?

I'm trying to unsuscribe from events in this way but it does not working.

```typescript
useEffect(() => {
		connect();

		return () => {
			client.off('connect');
			client.off('session_update');
			client.off('disconnect');
		};
	}, []);
```

**Comment by finessevanes** [comment]
@samyan is this still an issue?

**Comment by samyan** [comment]
> @samyan is this still an issue?

No, solved already. Thanks
