### ISSUE TITLE
RNWalletConnect killSession method throw error, and could not handle in disconnect event

### ISSUE THREAD

**Issue by yuanyu90221** [WalletConnect/walletconnect-monorepo#83]
I'd tried app RNWallectConnect library , create  a connector

after approveSession

I use KillSession and this show in app 

![螢幕快照 2019-03-27 上午10 40 21](https://user-images.githubusercontent.com/7987905/55046604-2269bd80-507d-11e9-891e-02cd80e72cbd.png)

And I listen on disconnect event show in console
<img width="738" alt="螢幕快照 2019-03-27 上午10 44 12" src="https://user-images.githubusercontent.com/7987905/55046681-5a710080-507d-11e9-9413-b6bddb416de8.png">

And I found in _handleSessionDisconnect method
![螢幕快照 2019-03-27 上午10 46 47](https://user-images.githubusercontent.com/7987905/55046801-af147b80-507d-11e9-8fb2-4211d65d395c.png)

my question is how to catch this error

or may be not use console.error

would bypass this error?

**Comment by pedrouid** [comment]
That's a good point, let's create an internal event for `error` events instead that can be subscribed to. Also now that I'm looking at the code, that `console.error` makes no sense because the error message is already being passed to the `disconnect` event. Thanks for reporting this 🙏

**Comment by pedrouid** [comment]
Fixed on commit [907a98357d45bfe8a5bfb03a464983d17a13166b](https://github.com/WalletConnect/walletconnect-monorepo/commit/907a98357d45bfe8a5bfb03a464983d17a13166b0)
