### ISSUE TITLE
[v1] Android fallback when no wallet installed leads to 404

### ISSUE THREAD

**Issue by svenlombaert** [WalletConnect/walletconnect-monorepo#840]
Problem concerning `@walletconnect/react-native-dapp`

# Issue
When you have no Wallets installed on your Android device, and you use `connector.connect()`, you get redirected to: https://walletconnect.org/wallets which results in a 404.

# Expected
I guess the user needs to be redirected to: https://walletconnect.org/registry/wallets

Fixed it here: https://github.com/getdelta/walletconnect-monorepo/tree/fix/android-wrong-redirect

Can't seem to create a PR to 1.7.4. Would be great if this could be merged and released.

**Comment by mcuelenaere** [comment]
This should be `https://walletconnect.com/registry` now, it looks like the URL got changed again

**Comment by davidm03** [comment]
I have been experiencing a similar issue and wonder if it is related to this. 

`connector.connect()` no longer works on Android devices within our react native dapp. We implemented it at the start of the year, worked well on both iOS and Android - now only works on iOS. 

We did see a '404' page on Android devices at one point but now we don't even see that anymore, it just fails silently.

**Comment by adhit7** [comment]
Where sholud I change the url ?

**Comment by finessevanes** [comment]
@svenlombaert is this still an issue?

**Comment by svenlombaert** [comment]
> @svenlombaert is this still an issue?

in v1 for sure, cause the url keeps changing and there's never a redirect from the old url
