### ISSUE TITLE
Yarn PnP not resolving @walletconnect/encoding

### ISSUE THREAD

**Issue by ghost** [WalletConnect/walletconnect-monorepo#844]
Hi,

I'm creating a Next.js app using Yarn PnP workspaces (monorepo) and as soon as I try to import @walletconnect/iso-crypto build process fails with this error message:

```
error - ../.yarn/cache/@walletconnect-iso-crypto-npm-1.7.4-03d954490c-f9116004c4.zip/node_modules/@walletconnect/iso-crypto/dist/esm/index.js:2:0
Module not found: Can't resolve '@walletconnect/encoding'

Import trace for requested module:
./pages/index.js

```

Here is a small reproduction repo: https://github.com/robert-balcerowicz/walletconnect-iso-crypto-pnp

**Comment by xzilja** [comment]
I don't think packages were extensively tested against PnP, so some errors are likely.
You should be able to resolve this issue by explicitly adding `@walletconnect/encoding` as a dependency in your frontend's `package.json` until better PnP support arrives 👍

**Comment by pedrouid** [comment]
Fixed on v1.7.5

**Comment by ghost** [comment]
Thank you guys. 👍

**Comment by einaralex** [comment]
Yeah, this is still an issue in`v.1.7.8`
