### ISSUE TITLE
Reject eth_sendTransaction gets wrong response

### ISSUE THREAD

**Issue by seabornlee** [WalletConnect/walletconnect-monorepo#854]
Using sample app and sample Dapp 2.0 https://react-app.walletconnect.com/

1. Scan QR code to connect
2. Trigger `eth_sendTransaction`
3. Click `Reject` on app
4. It shows `Approved` instead of `Rejected`

<img width="425" alt="image" src="https://user-images.githubusercontent.com/735708/158106376-53e39857-00b0-4545-8795-d96ce01034bc.png">

**Comment by bkrem** [comment]
Thanks for pointing this out @seabornlee 👍  This should now be fixed via the commit linked above.

We've recently set up the new https://github.com/WalletConnect/web-examples repo, where all dapp/wallet examples (including https://react-wallet.walletconnect.com and https://react-app.walletconnect.com/) now live. 
That's also the best and most visible place to open issues around the example implementations going forward :)
