### ISSUE TITLE
WalletConnect v2 does not work with SvelteKit+Vite (rollup)

### ISSUE THREAD

**Issue by tfalencar** [WalletConnect/walletconnect-monorepo#864]
When trying to follow the tutorial on: 

https://docs.walletconnect.com/2.0/quick-start/dapps/ethereum-provider

The following error appears: 

500
Importing binding name 'PairingTypes' is not found.
moduleDeclarationInstantiation@[native code]
link@[native code]
linkAndEvaluateModule@[native code]
@[native code]
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]

Steps to reproduce:
- Setup a new SvelteKit project 
- Follow documentation from WalletConnect

**Comment by zhanzekun** [comment]
+1

**Comment by yekta** [comment]
I'm having the same problem. Are there any good workarounds?

**Comment by avivash** [comment]
@tfalencar as a temporary workaround, I was able to get it all running in sveltekit using these imports. Vite borks unless you import the `umd` files directly for some reason and the types should work if you add `import type` to the beginning to denote that it's a typescript import
```
import WalletConnectProvider from '@walletconnect/ethereum-provider/dist/umd/index.min'
import WalletConnectClient, { CLIENT_EVENTS } from '@walletconnect/client/dist/umd/index.min'
import type { PairingTypes, SessionTypes } from '@walletconnect/types'
```

**Comment by finessevanes** [comment]
@tfalencar @yekta is this still an issue?

**Comment by tfalencar** [comment]
@finessevanes I think its better to ask the walletconnect's development team if they solved the root cause of this issue.

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version  :)

**Comment by glitch-txs** [comment]
SvelteKit + Web3Modal example: https://github.com/WalletConnect/web-examples/pull/346
