### ISSUE TITLE
After successful connect and then disconnect, the QR Modal doesn't come up (Metamask)

### ISSUE THREAD

**Issue by spyshower** [WalletConnect/walletconnect-monorepo#891]
Alright so we are using the latest version of this app on Android and we are only testing Metamask.

The QR Modal was showing up like it should, until we created a Metamask account in the phone that we do the debugging and then connected to it with WallectConnect (this package, via the modal).

However, every single time we try to connect, the modal it just doesn't come up and we get deep linked to Metamask's app and then redirected (logged in) to our app, or we instantly get logged in our app without ever going to the Metamask app.

Deleting our app's data, deleting the app, and cleaning Android with `./gradlew clean` doesn't help. Like, on a fresh install of our app, we try to connect with WalletConnect but again the modal doesn't come up and we go to Metamask.

We can't even understand if this is a problem with the package's code itself or something outside of it. Any help please?

**Comment by finessevanes** [comment]
@spyshower are you still experiencing an issue? On v1 or v2?

**Comment by spyshower** [comment]
> @spyshower are you still experiencing an issue? On v1 or v2?

I am not working on that project anymore. If I remember correctly, I was never able to solve the problem.

It was v1.
