### ISSUE TITLE
User cannot sign Polygon transactions using Ledger/Wallet Connect

### ISSUE THREAD

**Issue by addmorebass** [WalletConnect/walletconnect-monorepo#908]
We are getting errors when a user tries to sign a Polygon transaction using Ledger/WalletConnect.

**Comment by hollywoodpa** [comment]
Problem: When connected with Ledger hardware wallet, it does not seem to support EIP 712 signature confirmation
Is this wallet connect or ledger issue?

**Comment by finessevanes** [comment]
Is this still an issue? What version of WalletConnect are you using?
