### ISSUE TITLE
@walletconnect/web3-provider sends so much eth_getBlockByNumber requests also why do we need those requests

### ISSUE THREAD

**Issue by Yash0018** [WalletConnect/walletconnect-monorepo#910]
I got wallet connect working well. but I noticed so many requests sent in the background for eth_getBlockByNumber. i learned that we can delay them. but my question is why do we even need them. also, can I stop them completely?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version  :)
