### ISSUE TITLE
Engine: implement new session pairing settlement flow

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/walletconnect-monorepo#911]
- [ ] Generate paring
- [ ] Pair
- [x] Proposal
- [ ] Response
- [ ] Settle
- [ ] Acknowledgement

More
- [ ] Expiries
- [ ] Timeouts

**Comment by KristijanSajenko** [comment]
> * [ ]  Generate paring
> * [ ]  Pair
> * [x]  Proposal
> * [ ]  Response
> * [ ]  Settle
> * [ ]  Acknowledgement
> 
> More
> 
> * [ ]  Expiries
> * [ ]  Timeouts

**Comment by KristijanSajenko** [comment]
https://github.com/WalletConnect/walletconnect-monorepo/issues/911#issue-1194308646
