### ISSUE TITLE
BSC Network Switch not working Wallet Connect in MetaMask mobile

### ISSUE THREAD

**Issue by Sudhanmanoharan** [WalletConnect/walletconnect-monorepo#918]
Hi Team,
Right now I'm using on wallet connect to connect DAPP, When I try to switch the BSC network in Metamask mobile App. I’m getting the following error
**_Error: call revert exception CALL_EXCEPTION [https://docs.ethers.io/v5/troubleshooting/errors/#help-CALL_EXCEPTION]._**
Then I console Contract, I’m able to get all methods in the console and checked the Network setting, everything looks fine in Metamask mobile for the **BSC network**. But, the same scenario works fine for the **Ethereum network**.
![photo6224015715304845983](https://user-images.githubusercontent.com/27803356/162147361-fd08eaf1-8bf0-4856-8b48-dbff15b8b5a5.jpg)
#657 #445 #766

**Comment by sc0Vu** [comment]
Does this work if add BSC when initiate WalletConnect connector?

```JS
new WalletConnectConnector({
  rpc: {
    [ChainId.BSC]: 'https://bsc-dataseed.binance.org/'
  },
})
```

**Comment by Sudhanmanoharan** [comment]
> ```js
> ChainId
> ```

It's working
Thanks @sc0Vu

**Comment by Sudhanmanoharan** [comment]
Hi @sc0Vu,
 one more help is needed from you. I'm facing issues in the trust wallet and Safepal wallet. Let me attach the screenshot.
ChainId is not supporting in both.
**TrustWallet:**
![photo5366306790628768559](https://user-images.githubusercontent.com/27803356/162205358-458b9c21-093a-44c5-9d3c-82f8699d5941.jpg)
----
**SafePal**
![photo5366306790628768558](https://user-images.githubusercontent.com/27803356/162205445-4daaa269-1e02-49d5-b9df-e3c59cfb245a.jpg)

**Comment by Jemma1445** [comment]
@Sudhanmanoharan has it been resolved?

**Comment by finessevanes** [comment]
@Jemma1445 @Sudhanmanoharan is this still an issue?
