### ISSUE TITLE
Strange walletconnect-connect__button__text size in the modal

### ISSUE THREAD

**Issue by sc0Vu** [WalletConnect/walletconnect-monorepo#919]
Hi there, 

We found a strange issue with walletconnect modal. Here are screenshot from two dapp, naos and uniswap. Both of them were in computer mode, and the screen is 1232*830, the weird thing is they have different `font-size` style. The `font-size` came from this condition (width < `768px`):

https://github.com/WalletConnect/walletconnect-monorepo/blob/a22bee13df255ee59d338d600175250a3a0ef8aa/legacy/modal/src/browser/components/WalletIcon.tsx#L13

* app.naos.finance
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/10494397/162152759-1f4ae31a-b015-4d24-9919-11c222caa058.png">

* app.uniswap.org
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/10494397/162152850-3c42340d-db16-40cf-bc54-2025d8b4600e.png">

IMHO, they should use the same `inherited` style.

**Comment by finessevanes** [comment]
@sc0Vu  is this still an issue? Have you tried using the newer version of Web3Modal?
