### ISSUE TITLE
(REACT-NATIVE) JSON RPC response format is invalid

### ISSUE THREAD

**Issue by NoahsArk02** [WalletConnect/walletconnect-monorepo#930]
I tried to use the `sendCustomRequest `and the method is `wallet_switchEthereumChain` to request to switch the network on the metamask mobile, when I press switch network button on the metamask app it return me this error on my dApp `JSON RPC response format is invalid`. Here is my sample code

```
 const requestSwitchNetwork = async () => {
    try {
      await connector.sendCustomRequest({
        id: 0,
        jsonrpc: '2.0',
        method: 'wallet_switchEthereumChain',
        params: [ { chainId: ethers.utils.hexlify(CHAIN_ID) } ],
      });
    } catch (error) {
      // Always getting error
      console.log(error);
    }
  };
```
I tried this on the metamask API playground and it works fine.
https://metamask.github.io/api-playground/api-documentation/#wallet_switchEthereumChain

**Comment by saiyam-sage** [comment]
@NoahsArk02 I am getting the same issue. Did you find any solution?

**Comment by duyta7598** [comment]
Same issue, any update?

**Comment by RivarolaNicolas** [comment]
Seems to be linked to this issue #962

**Comment by songkeys** [comment]
looks like the response is parsed to `{id: 1650610281723940, jsonrpc: '2.0', result: null}`. i believe this is an sdk bug.

**Comment by NoahsArk02** [comment]
> @NoahsArk02 I am getting the same issue. Did you find any solution?

NO, I didn't find any solution yet for this issue.
