### ISSUE TITLE
Wallet Connect Provider Does Not Support Astar Network 

### ISSUE THREAD

**Issue by kasheefalbertus** [WalletConnect/walletconnect-monorepo#932]
Failed to load resource: the server responded with a status of 401 ()  

Please can you confirm the following is supported 

   const walletconnect = new WalletConnectProvider({
                    rpc: { 592: "https://rpc.astar.network:8545" },
                    bridge: "https://bridge.walletconnect.org"
                });

Any Support Would Be Appreciated

**Comment by finessevanes** [comment]
@kasheefalbertus is this still an issue?
