### ISSUE TITLE
Network request failed: https://registry.walletconnect.org/data/wallets.json

### ISSUE THREAD

**Issue by CryptishApps** [WalletConnect/walletconnect-monorepo#933]
I'm receiving this error:

> [TypeError: Network request failed]

When loading the app. It's when it's calling this URL: https://registry.walletconnect.org/data/wallets.json. The error given is:

> "isTrusted": false

Started happening yesterday, I believe. Anyone have any ideas why? It means, when I try to use the Connect option, I get this error:

`Mobile registry not yet ready`

Thanks in advance.

**Comment by chadyj** [comment]
That URL is our deprecated registry API. It should still work fine, so I'll look into this issue.

In the meantime, I suggest you try the new registry API as that could fix your issue. https://docs.walletconnect.com/2.0/api/registry-api

**Comment by bkrem** [comment]
Not seeing any issues with either fetching via the legacy endpoint [registry.walletconnect.org/data/wallets.json](https://registry.walletconnect.org/data/wallets.json) or when used inside the modal, e.g. https://example.walletconnect.org/

> When loading the app.

@andyloweruk could you provide context here as to what the app is where you're seeing this? It sounds like a possible content security issue on their side, especially given the `isTrusted` flag you mentioned.

**Comment by CryptishApps** [comment]
Thanks @bkrem but I’m not using it directly, I’m using your React Native client which calls this endpoint, so hopefully that helps narrow down the issue.

Restarting the android emulator seems to do the trick but I’ve had the issue come back since.

**Comment by bkrem** [comment]
Thanks for the additional context here @andyloweruk 👍  

Root cause is still unclear but I'm closing this issue and redirecting further discussion to #950 to avoid duplicated issues on this.

**Comment by CryptishApps** [comment]
Thanks but I’m not using it directly, I’m using your React Native client, so hopefully that helps narrow down the issue.

Restarting the emulator seems to do the trick but I’ve had the issue come back since.

**Comment by dingcxx** [comment]
I had the same problem

in iOS platform working well, Android was failed 

also using React Native

```
dependencies: {
        "@walletconnect/react-native-dapp": "^1.8.0",
        "@walletconnect/web3-provider": "^1.8.0",
}

```

when call  WalletConnectProvider init will receive error

error

>  [TypeError: Network request failed]

init code

```
return (
        <WalletConnectProvider
            redirectUrl={Config.APP_SCHEME}
            storageOptions={{ ...({ asyncStorage: AsyncStorage } as any) }}
            clientMeta={{
                ...clientMeta
            }}>
            {children}
        </WalletConnectProvider>)
```
then call  `useWalletConnect().connect()` will receive

> [Error: Mobile registry not yet ready.]

**Comment by dingcxx** [comment]
> I had the same problem
> 
> in iOS platform working well, Android was failed
> 
> also using React Native
> 
> ```
> dependencies: {
>         "@walletconnect/react-native-dapp": "^1.8.0",
>         "@walletconnect/web3-provider": "^1.8.0",
> }
> ```
> 
> when call WalletConnectProvider init will receive error
> 
> error
> 
> > [TypeError: Network request failed]
> 
> init code
> 
> ```
> return (
>         <WalletConnectProvider
>             redirectUrl={Config.APP_SCHEME}
>             storageOptions={{ ...({ asyncStorage: AsyncStorage } as any) }}
>             clientMeta={{
>                 ...clientMeta
>             }}>
>             {children}
>         </WalletConnectProvider>)
> ```
> 
> then call `useWalletConnect().connect()` will receive
> 
> > [Error: Mobile registry not yet ready.]

only one Android device had this issue , and only request  https://registry.walletconnect.org/data/wallets.json had receive `[TypeError: Network request failed]` other json work fine. and move request to other component , also receive error.
