### ISSUE TITLE
Update @walletconnect/qrcode-modal@1.7.7 dependency tree

### ISSUE THREAD

**Issue by dracorisz** [WalletConnect/walletconnect-monorepo#935]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@walletconnect/qrcode-modal@1.7.7` for the project I'm working on.

Since @walletconnect/mobile-registry is DEPRECATED, could you remove it from the dependency tree, please? 

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@walletconnect/qrcode-modal/package.json b/node_modules/@walletconnect/qrcode-modal/package.json
index 5dad857..bb62dad 100644
--- a/node_modules/@walletconnect/qrcode-modal/package.json
+++ b/node_modules/@walletconnect/qrcode-modal/package.json
@@ -69,7 +69,6 @@
   },
   "dependencies": {
     "@walletconnect/browser-utils": "^1.7.7",
-    "@walletconnect/mobile-registry": "^1.4.0",
     "@walletconnect/types": "^1.7.7",
     "copy-to-clipboard": "^3.3.1",
     "preact": "10.4.1",
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by davidthomasparks** [comment]
Mobile links are no longer showing for our WalletConnect modal on mobile, is this related to the registry being deprecated?

**Comment by dracorisz** [comment]
> Mobile links are no longer showing for our WalletConnect modal on mobile, is this related to the registry being deprecated?

Nope.

**Comment by melissafzhang** [comment]
@davidthomasparks we're also seeing the issue where the mobile links aren't showing up on mobile. Were you able to resolve?

**Comment by davidthomasparks** [comment]
I was yes, but it was pretty hacky @melissafzhang  

Here's the solution:

https://github.com/WalletConnect/walletconnect-monorepo/issues/950
