### ISSUE TITLE
JSON-RPC Request has invalid publish params

### ISSUE THREAD

**Issue by shiny-mountain** [WalletConnect/walletconnect-monorepo#962]
After updating the package to version 2.0.0-beta.26 in the Stellarterm, when calling the "pair" method, I get error "JSON-RPC Request has invalid publish params" in the dApp and wallet. What could be the problem?

I see that you have already been informed about such a problem:
https://github.com/WalletConnect/WalletConnectKotlinV2/issues/96

![Screenshot 2022-04-19 at 16 12 49](https://user-images.githubusercontent.com/47246422/164012301-39a2ab24-d04f-4021-8cfe-b1dac6e5edc9.png)

**Comment by RivarolaNicolas** [comment]
Same here, I've been dealing with this problem for a while now. It only happens using the .org relay `relayUrl: 'wss://relay.walletconnect.org',`, the thing is LOBSTR only works with the .org relay. It happens on every version I tried of the v2 beta

**Comment by shiny-mountain** [comment]
@RivarolaNicolas Thank you! I would never have discovered that ".org" changed to ".com" :) Everything works fine with ".com"!

**Comment by RivarolaNicolas** [comment]
@shiny-mountain No problem! Glad to help you. Can I ask you which wallet you are using? Were you able to connect using the ".com" relay with LOBSTR? AFAIK it's the only wallet that supports WalletConnect in the Stellar ecosystem

**Comment by joharzmn** [comment]
@RivarolaNicolas  can you also help me with this issue? 
https://github.com/WalletConnect/walletconnect-monorepo/issues/956

**Comment by RivarolaNicolas** [comment]
Hello @joharzmn, sorry but I can't help you as I have no experience dealing with the v1 of WalletConnect, this issue is about the v2 (which is in beta)
