### ISSUE TITLE
walletconnect.connected is still true even if there is no connection

### ISSUE THREAD

**Issue by mqklin** [WalletConnect/walletconnect-monorepo#963]
I'm using `@walletconnect/client`. I created session with `createSession`, scanned QR code, everything is OK. After that I rebooted my cell phone - connection is lost. But connector still returns `connected` as `true` and tries to trigger cell phone pop-ups.

**Comment by joharzmn** [comment]
@mqklin Please share your code as well.

**Comment by socheat-leang** [comment]
@mqklin , Please give little more detail than this bro.

**Comment by finessevanes** [comment]
@mqklin is this still an issue?

**Comment by mqklin** [comment]
@finessevanes i've migrated to `@walletconnect/web3-provider`, so can't confirm anymore.
