### ISSUE TITLE
Wallect Connect did not show wallets on Android

### ISSUE THREAD

**Issue by yangjingsong** [WalletConnect/walletconnect-monorepo#969]
![origin_img_v2_a61d23a1-f808-4ad6-969b-259ad908c06h](https://user-images.githubusercontent.com/13377942/164964814-ffc362c5-df88-489f-b742-fdf5c2bc707a.png)

**Comment by yangjingsong** [comment]
https://user-images.githubusercontent.com/13377942/164967734-acb8548d-90be-4bde-95e6-86aa8549f7d3.mp4

**Comment by yangjingsong** [comment]
https://user-images.githubusercontent.com/13377942/164968243-cc53cd9c-4c6a-4fd6-a610-85481444227f.mp4

**Comment by annapmq** [comment]
1.open “okx”app
2.Switch to tab "metax"
3.Click the button "dapps"
4、open the pancake 
5、click“connect wallent”，choose“ wallent connect”

**Comment by finessevanes** [comment]
Is this still an issue?

**Comment by glitch-txs** [comment]
By clicking connect, Android will show your installed wallets. :)

I’m closing this issue because it has been inactive for a few months.
