### ISSUE TITLE
web3-subprovider not shipping types

### ISSUE THREAD

**Issue by NoahZinsmeister** [WalletConnect/walletconnect-monorepo#98]
`yarn add @walletconnect/web3-subprovider`, which currently installs `^1.0.0-beta.10`, does not ship types.

![Screen Shot 2019-04-07 at 1 08 56 PM](https://user-images.githubusercontent.com/3760414/55687046-7fdff300-5936-11e9-8fd0-c2cf6365181e.jpg)

**Comment by pedrouid** [comment]
Current configuration uses `ts-loader` to ship types but since `web3-provider` and `web3-subprovider` are javascript files, it's not able to ship types. We either refactor these two packages into typescript or write the typings manually.

**Comment by pedrouid** [comment]
Probably going to deprecate soon `web3-provider` and `web3-subprovider` in favor of `eth-provider` which doesn't have `web3-provider-engine` dependency, it's EIP-1193 complaint and all written in Typescript so types will be included
