### ISSUE TITLE
Modal search bug on Uniswap and others

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/walletconnect-monorepo#981]
**Describe the bug**

There is a UI bug on the WalletConnect modal happening on both desktop and mobile.
A user can't tap/click the search box. Doing so causes the page to jump.

This breaks the WalletConnect connect flow as a user can't choose their wallet.

It is happening at least on:

https://app.uniswap.org
https://app.gro.xyz/

**SDK Version (if relevant)**
 - JS

**To Reproduce**
1. Go to https://app.uniswap.org or https://app.gro.xyz/ on iOS (or mobile)
2. Click on Connect Wallet
3. Click WalletConnect
4. Try to tap the search box5. 
5. The page will jump, and the user can't enter text6. 

Similar behaviour exists on the desktop, by going to the Desktop tab.

**Expected behavior**

It is expected a user can enter text in the search field and find their wallet.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version 15.3

**Smartphone (please complete the following information):**
 - Device: iPhone X Pro
 - OS: iOS 15.4.1
 - Browser: Safari

**Additional context**

Reported by ZenGo.

**Comment by michaelr524** [comment]
Plenty of user complaints about this one

**Comment by finessevanes** [comment]
@chadyj is this still an issue?
