### ISSUE TITLE
walletConnector.connected shows false with in react-native not work, even if uri is correct, and it is connected. How to detected  connect created successfully when new RNWalletConnect connector?

### ISSUE THREAD

**Issue by yuanyu90221** [WalletConnect/walletconnect-monorepo#99]
walletConnector.connected shows false with in react-native not work, even if uri is correct, and it is connected. How to detected  connect created successfully when new RNWalletConnect connector?

I try to create connect to the bridge server with  new RNWalletConnect connector
<img width="759" alt="螢幕快照 2019-04-08 上午10 16 33" src="https://user-images.githubusercontent.com/7987905/55694601-76629380-59e7-11e9-9547-06e5e7e2c807.png">
and try to console.log the status of connected after create connector
<img width="968" alt="螢幕快照 2019-04-08 上午10 11 31" src="https://user-images.githubusercontent.com/7987905/55694634-98f4ac80-59e7-11e9-9312-92bafafedcae.png">

but the status of walletConnector.connected
<img width="1018" alt="螢幕快照 2019-04-08 上午10 19 02" src="https://user-images.githubusercontent.com/7987905/55694683-d822fd80-59e7-11e9-8a8c-cb3d60f5461b.png">

how to detected walletConnector is connected successfully?
could I use the connected attribute to judge it?

**Comment by pedrouid** [comment]
When you pass the URI you are "connecting" to the bridge server websocket but the connection is not yet established with the peer that you scanned the QR Code. You can verify this by checking WebSocket connection state with `walletConnector._socket.socketState`. Only after you approve the session request that you have received, then the session will be connected.
