### ISSUE TITLE
No easy way to get a connector instance Garbage Collected on Node

### ISSUE THREAD

**Issue by w4-jake** [WalletConnect/walletconnect-monorepo#999]
Hi all, thanks for all your work on this library.

# Problem
My question is about the [V1 Standalone Client](https://docs.walletconnect.com/quick-start/dapps/client). I am currently using version `1.7.7` of `@wallet-connect/client` and testing on Node `v12.16.1`.

I want to use WalletConnect in a specific use case where connectors only need to be created and connected for about a minute -- long enough for a user to connect an account and sign a personal message to prove they are the owner of the account, but that's the whole use case. I want it to be possible for many such connectors to come into existence, complete the use case, and then disappear, so that my Node server with these connectors can serve many different clients concurrently.

The problem is, there doesn't seem to be an easy way to 'clean up' a connector instance to ensure that it will be garbage collected the next time Node's GC runs, so I am worried that running the use case for lots of users over time will lead to a memory leak on my server.

I am using a very simple case for testing. No extra logic yet, just creating the connector instance within a function's scope instead of globally:

```javascript
import WalletConnect from '@walletconnect/client'

const WALLET_CONNECT_OPTIONS = {
    bridge: 'https://bridge.walletconnect.org',
    qrcodeModal: { open: () => {}, close: () => {}},
    clientMeta: {
        name: 'Test App',
        description: 'This is some description about the test app.',
        icons: ['https://image.shutterstock.com/image-photo/smiling-gecko-260nw-647414824.jpg'],
        url: 'https://google.com'
    }
}

function createConnectorButOnlyInThisScope() {
    // Looks like the connector is only in this scope...but it isn't GC'd after the function call is done!
    const connector = new WalletConnect(WALLET_CONNECT_OPTIONS)
})
```

Every time I call 'createConnectorButOnlyInThisScope', a new connector instance is created within the scope of the function, but after the function call is over this object still remains in the V8 heap, even after I manually run garbage collection.

I suppose this is because when creating a connector there are some event watching callbacks that are set up internally, and a socket connection is made, so it makes sense and is a good thing that the connector remains on the heap unlike a simple javascript object or array like below, which would get GC'd away eventually after the function call is over:

```javascript
function brieflyUseArray() {
    // This will always get GC'd since there's obviously no use for it outside the function!
    const a = new Array(9999999)
})
```
NOTE: To test this code, I checked the heap and manually ran GC using Dev Tools similarly to how is described [here](https://marmelab.com/blog/2018/04/03/how-to-track-and-fix-memory-leak-with-nodejs.html).

# Solution that would be nice
It would be nice if there were some kind of public method on the connector instance like `.permanentClose()` that could be called when we are 100% sure that we are for good **done** with this connector instance, unsubscribing any event watchers, closing sockets, and doing whatever else is needed to make sure that the V8 Garbage Collector knows it is safe to clear the connector out:

```javascript
...

function createConnectorButOnlyInThisScope() {
    const connector = new WalletConnect(WALLET_CONNECT_OPTIONS)
    connector.permanentClose()
})
```

Obviously the above code doesn't do anything useful, so it would have to be a method that could be called within a callback set up by the 'on' method. For example:

```javascript
...

function createConnectorButOnlyInThisScope() {
    const connector = new WalletConnect(WALLET_CONNECT_OPTIONS)
    connector.on('connect', (...) => {
        // Do some stuff that needs to be done...
        connector.permanentClose()
    })
})
```

# Alternative Solutions
I tried briefly to do things like manually close the socket transport and unsubscribe from the events that become watched internally during creation of a connector, but the connector still wasn't GC'd. Moreover, the socket did not actually close when I ran the code below, only closing when I called `.killSession()` after making a real connection with a wallet:
```javascript
...

function createConnectorButOnlyInThisScope() {
    const connector = new WalletConnect(WALLET_CONNECT_OPTIONS)

    // Socket
    connector.transportClose()

    // The five events that get 'on' called during creation of a connector.
    connector.off('display_uri')
    connector.off('connect')
    connector.off('call_request_sent')
    connector.off('wc_sessionRequest')
    connector.off('wc_sessionUpdate')
})
```

Is there a better workaround to get unused connector instanced GC'd and prevent a memory leak than what I tried? Or maybe, is WalletConnect simply not designed for a use case like the one I am describing, where we aim to create and destroy a lot of instances of the Standalone Client connector on one backend server? Thank you to anybody who has perspective on this issue!

**Comment by Mahdyar1983** [comment]
Nice the best

**Comment by Mahdyar1983** [comment]
Good

**Comment by finessevanes** [comment]
@w4-jake is this still an issue? We would encourage you to use v2.

**Comment by w4-jake** [comment]
It is probably still an issue, but we ended up using a different approach. I was keeping this issue open in case others have a similar problem, but if new developers are all encouraged to just go with v2 then feel free to close.

Thanks~!

**Comment by finessevanes** [comment]
I appreciate your willingness to help the community! I will be closing since there doesn't seem to be other devs experiencing this issue (no upvotes), but at least that will have this for context if someone does run into an issue in the future.
